### ISSUE TITLE
URL Encoding of Query string needs configuration?

### ISSUE THREAD

**Issue by gpampara** [http4s/http4s#1012]
I found a rather strange problem regarding the query string encoding as provided by [Query](https://github.com/http4s/http4s/blob/master/core/src/main/scala/org/http4s/Query.scala). In my use, I need to pass a URL as a query string and everything is properly URL encoded, except for the `/` character within the parameter value. Reading the source of `Query`, I noticed that there is reference to the [RFC](http://tools.ietf.org/html/rfc3986#section-3.4) where the encoding of `/` seems to vary based on the required usage. It's basically left up to the user.

I'd gladly provide a PR to correct this, but I wanted to get an indication of proposing that this exclusion be made configurable? The character is currently placed in the `NoEncode` CharPredicate. The `encode` function within `Query` that eventually converts the value to a string uses this `encode` function to manipulate the value portion of each query string pair, however, this is a local function definition and is not possible to change at the moment. We could pass it in, using the current definition as a default?

**Comment by rossabaker** [comment]
Paging @refried, who has thought about encoding more than anybody here.  I'm getting sleepy, so I will weigh in with my own opinion tomorrow when I'm thinking more clearly. :)

**Comment by refried** [comment]
(disclaimer: I’m only “awake” due to a train with disappointingly loud engine passing by.)

@gpampara Forgive the question, but given that it’s fine under the RFC to not  percent-encode `/` in the query fragment, why do you want to encode it? For looks, or for some other reason?  For comparison, alphanumeric characters also aren’t currently encoded, because they aren’t required to be; also left up to the user, in the spec.

**Comment by gpampara** [comment]
@refried it's related to a problematic CouchDB interaction. That being said, I think that I can workaround the issue locally and I agree that the spec leaves it up to the user, so this is not an issue at the moment per se.

Sorry for the noise though, but I think we can close this for now.

**Comment by refried** [comment]
@gpampara No problem -- do you want to describe the problematic CouchDB interaction, so we capture that; or link to a CouchDB bug if it's documented there?

**Comment by gpampara** [comment]
@refried This is due to some legacy issues where the key values to CouchDB contains potentially incorrect/invalid characters (such as the slash) as casually stated in their documentation. The real solution is to actually correct the source of the problem. Ideally, this should be that CouchDB prevents the creation of such documents, with the problem keys, but they don't.
