### ISSUE TITLE
Cats Build Deletes Master Documentation

### ISSUE THREAD

**Issue by ChristopherDavenport** [http4s/http4s#1023]
This needs to be addressed before any changes are merged into the `cats` branch.

Area of problem is in [Http4sGHPages](https://github.com/http4s/http4s/blob/master/project/Http4sGhPages.scala#L22)

I am working on this at the moment, but any new builds on cats will delete master branch documentation.

**Comment by rossabaker** [comment]
The quick hack is in `Http4sGhPages`.  The cleaner solution, I think, is #972.

**Comment by ChristopherDavenport** [comment]
Closed By #1033 Hopefully cleaner implementation soon.
