### ISSUE TITLE
Host contributors' guide on http4s.org

### ISSUE THREAD

**Issue by bfritz** [http4s/http4s#1037]
We currently link to GitHub for `CONTRIBUTING.md`.  Look and feel would be more consistent if it was copied to Hugo site similar to `CHANGELOG.md` [in build.sbt](https://github.com/http4s/http4s/blob/v0.15.6/build.sbt#L304).

**Comment by rossabaker** [comment]
I've also considered slimming down contributing.md and making a developers' guide.  I'm open to either idea.

**Comment by rossabaker** [comment]
We [have this](https://http4s.org/contributing/) now.
