### ISSUE TITLE
CORS and auth interaction

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#1039]
CORS [passes the options request to the service](https://github.com/http4s/http4s/blob/61f0ded179e4aaab8d63a972c7da0d743eef69e0/server/src/main/scala/org/http4s/server/middleware/CORS.scala#L62-L74) on a pre-flight request.  When the service is protected by an auth middleware, the preflight request returns a 403.  This unsuccessful response prevents us from adding the CORS headers to the response.

I don't find a lot of support for this behavior:
* [CORS flowchart](https://www.html5rocks.com/static/images/cors_server_flowchart.png) says to return a 200 response with no body.
* The Tomcat CORSFilter [dos not pass along the request](https://github.com/apache/tomcat/blob/trunk/java/org/apache/catalina/filters/CorsFilter.java#L391).
* The [Jetty CrossOriginFilter](http://download.eclipse.org/jetty/stable-9/xref/org/eclipse/jetty/servlets/CrossOriginFilter.html#L408) also does not.
* [The W3C spec](https://www.w3.org/TR/cors/#resource-preflight-requests) doesn't mention that a successful response to the preflight request implies a successful response to the actual request.

A more conservative change would be to respond to preflight requests with CORS headers if the OPTIONS request is successful, 401, or 403.  The latter has stronger support if the CORSConfig has `allowCredentials = true`.  But that also feels like a hack, where an outer middleware understands too much about an internal one, and I worry what other interactions with middleware aren't thought of.
 
/cc @jordantdavis

**Comment by phile314-fh** [comment]
Is this only an auth-related problem, or is it not a more general problem? With the current behavior, I have to add support for OPTIONS requests to all services or else a 404 will be returned. I have solved this for now by using a fallback service which always succeeds for OPTIONS requests.

    def alwaysSucceedForOptions = HttpService {
      case OPTIONS -> _ => Ok("...")
    }
    val myService = CORS(Service.withFallback(realService)(alwaysSucceedForOptions), CORSConfig(...))
