### ISSUE TITLE
Make Session available where available

### ISSUE THREAD

**Issue by prange** [http4s/http4s#104]
Would it be painful to add session support for servers that have built in support for that? I am asking because of security "best practices".

For example make the session data available on a map on the request. When the sessions needs to be updated an updated map can be set in the Response, or maybe one can add a list of updates...

**Comment by mdedetrich** [comment]
A thread just appeared in Reddit on how to create typed Maps, i.e. http://aakashns.github.io/typed-map.html, which can probably be extended to work with http4s.

It uses scala-reflect, but figuring out if this is just for the compiler to figure out the types at compile time, or runtime

**Comment by rossabaker** [comment]
I'm cleaning up issues.  I think this is a nice idea, but does anybody want to argue for this blocking an eventual 1.0 release?  (Read: could it change the model, or can it be bolted on later in a compatible fashion?)

**Comment by mdedetrich** [comment]
I have had little time to do any significant headway into this, I wouldn't argue for this to block `http4s` since I can't guarantee I will be able to provide anything substantive anytime soon

**Comment by rossabaker** [comment]
I just stumbled across https://github.com/hgiddens/http4s-session

**Comment by hgiddens** [comment]
It's much less featureful than what was discussed here, but I do want to try and expand its functionality to some of the other stuff akka-http-session to it. However I don't think that has support for using the underlying e.g. Tomcat session either.

**Comment by rossabaker** [comment]
It looks like you're off to a great start.  This is something we're definitely interested in.

Servlet sessions may require the backends snaking through some sort of context as an attribute.  I'm not quite sure how that would look yet.

**Comment by jmcardon** [comment]
update on this: I'm unsure whether an abstraction for this is necessarily a good thing.

Java session is essentially `String -> Object` which people yolocast into whatever type they want, and it's held in memory always. I find this inflexible and somewhat primitive. Do we still want this?

**Comment by rossabaker** [comment]
If you mean a servlet session, it's not always held in memory, though usually.

I think it could still be wrapped by typed keys, like our Attributes or a Haskell Vault.  The way some backends demand `java.io.Serializable` is probably what I find most vexing in an abstraction.

**Comment by rossabaker** [comment]
`javax.servlet.http.HttpSession` is exposed via a servlet attribute, and [http4s-session](https://github.com/http4s/http4s-session) gives a more portable, functional solution.  Further work should go to the latter.
