### ISSUE TITLE
Unclear support for client basic authentication (secure or insecure)

### ISSUE THREAD

**Issue by NicolasRouquette** [http4s/http4s#1041]
I was looking forward to use http4s to query a server that provides json-ld content.

I managed to do this with [jsonld-java](https://github.com/jsonld-java/jsonld-java-tools/pull/3).
It is unclear to me how to do the equivalent with http4s.

**Comment by NicolasRouquette** [comment]
I figured it out.

I think that the doc could explain the different kinds of headers one can use with http4s.
Currently, the topic of authorization is explained from the perspective of a service; which is important, but substantially different from client requests.

For example, it could be helpful to have a synopsis of basic authentication for client requests like this:

```
val httpClient = PooledHttp1Client(config = 
    // Choose one of the two.
    BlazeClientConfig.default
    // BlazeClientConfig.insecure
)
val uri: Uri = Uri.fromString(....)
val req = Request(Method.GET, uri, Headers(Authorization(BasicCredentials("<username>", "<password>"))))
val task = httpClient.expect[<type>](req)
```

**Comment by rossabaker** [comment]
I've wondered about a `.withBasicAuth(username, password)` method as a convenience for this.  Shortcuts like that could get out of hand, but maybe useful for a few common cases.

Either way, it's worth documenting.

**Comment by NicolasRouquette** [comment]
I definitely agree about documenting this; I'm skeptical about adding convenience methods.

I presume you're talking about a syntax like this:

```
val req = Request(Method.GET, uri).withBasicAuth(username, password)
```

that would be the equivalent of:

```
val req = Request(Method.GET, uri, Headers(Authorization(BasicCredentials(username, password))))
```

I'm skeptical because the convenience method hides the fact that authentication is header information. The savings in syntax doesn't seem to me worth the fact that this convenience method will have to be documented and would only diminuish the minimalistic nature that http4s is intended to be.

**Comment by bfritz** [comment]
Not strongly for or against adding a helper, but one argument for is it increases discoverability.  If I'm in IntelliJ or Ensime, it's probably easy to find `withBasicAuth()` using auto-complete.  Another keystroke or two lets me see how it is implemented.  Docs achieve the same, but they're more detached from the process of writing code.

**Comment by NicolasRouquette** [comment]
It depends on where the helper is defined. 
It would be convenient to define it on `Request`; however, it could mislead a developer in thinking that authentication is a property of a request, thereby writing code like this:

```
val req1 = Request(....).withBasicAuth(username, password)
...
val req2 = Request(....).withBasicAuth(username, password)
...
```

Wouldn't it be preferable to encourage writing instead:

```
val h = Headers(Authorization(BasicCredentials(username, password)), ....)
val req1 = Request(..., headers=h, ...)
...
val req2 = Request(..., headers=h, ...)
...
```

**Comment by rossabaker** [comment]
I think the point above, keeping common authorization in a val (or even a simple middleware), is persuasive.
