### ISSUE TITLE
Blaze client config should have a maximum number of waiters

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#1043]
If your connection pool is too small, and you burst too many requests, you get an indefinitely sized queue of waiters.

**Comment by ChristopherDavenport** [comment]
I believed this was by design. What do you want to occur at this limit? Internally we are not using Task Context so we'd lose referential transparency except to the caller.

**Comment by rossabaker** [comment]
I think tasks should fail here, as a sort of circuit breaker.  The alternative, if you're making requests far faster than you can provide connections to them, is unbounded growth in the wait queue.

**Comment by rossabaker** [comment]
We have this now.
