### ISSUE TITLE
http4s-reactive-streams module

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#1051]
We discussed at the NE Scala Symposium ways for various libraries to abstract over `fs2.Task` and `monix.eval.Task`, both of which have a lot to like and a lot of people who like them.  For us, it's possible to abstract away `Task`, but significantly raises barriers to writing middleware or even composing library-provided building blocks.  Far more difficult would be abstracting over `Stream`, which would require a separate branch, which we are moving away from.

However, a module with entity codecs for monix would offer a nice solution.  Just like we support `Ok(scala.concurrent.Future("hello"))`, we could support `Ok(monix.eval.Task.eval("hello"))`.  Similarly, an `Ok(observable)` or `Ok(iterant)` could be converted to an `EntityBody`.  It would require a monix support import and some runtime conversion, but I imagine this results in a more pleasant Monix experience alongside fs2 than any extra abstractions we've imagined to support Monix without fs2.

**Comment by ChristopherDavenport** [comment]
I think this may be better handled by `cats-effect` and #1129. These will effectively build
modules for fs2, monix, and even future. If we then needed special code that would then be the time to address it.

**Comment by rossabaker** [comment]
It will handle Monix Task. It won't handle Observable, but a reactive streams module would pick up both that and akka-stream.

**Comment by rossabaker** [comment]
I'm evolving this to reactive streams support, which as mentioned above, would pick up the pieces of Monix we don't already have, plus more.

**Comment by rossabaker** [comment]
fs2-reactive-streams would make this very easy.  I think we would host this in a separate repo if it ever came to fruition: we're looking to split this repo, not add to it.

**Comment by armanbilge** [comment]
This issue reads to me a lot like a monix-http4s integration, and there's no Monix you can use alongside CE3 (yet). akka-stream is interesting but seems unlikely use-case IMHO since they have akka-http. Closing but of course if there is interest this can pop up as a new repo at anytime.
