### ISSUE TITLE
Unexplained build failure: client timeouts

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#1055]
[Client tests timed out](https://travis-ci.org/http4s/http4s/jobs/215346335#)

Reminiscent of #978 and #774.  It wasn't Scala 2.12.  There are lots of blocked threads relating to `scalaz.stream.async.mutable.Queue` and `CharsetRangeSpec`, but there is no deadlock detected.
Only thread `specs2.fixed.env-2006515238-11` says which monitor it's waiting to lock.

**Comment by bfritz** [comment]
Also happened in build 3945.5:
https://travis-ci.org/http4s/http4s/jobs/215206641#L2056

**Comment by rossabaker** [comment]
The problems restarted around the time of blaze server builder refactoring, though I can't connect the dots to why that should cause a problem.

**Comment by rossabaker** [comment]
I don't see evidence of death by charset locking this time:
https://travis-ci.org/http4s/http4s/jobs/217214969

**Comment by rossabaker** [comment]
lolwut?

```
"pool-6-thread-48" #859 prio=5 os_prio=0 tid=0x00007fcbc93f1800 nid=0xe9a runnable [0x00007fcaca1f8000]
   java.lang.Thread.State: RUNNABLE
	at java.lang.Long.getChars(Long.java:469)
	at java.lang.Long.toString(Long.java:398)
	at java.lang.Long.toString(Long.java:1032)
	at sbt.TestStatus$$anonfun$write$2.apply(TestStatusReporter.scala:39)
	at sbt.TestStatus$$anonfun$write$2.apply(TestStatusReporter.scala:38)
```

**Comment by bfritz** [comment]
It was passing through [this line](https://github.com/sbt/sbt/blob/v0.13.13/testing/src/main/scala/sbt/TestStatusReporter.scala#L23) in that stack:
```
TestStatus.write(succeeded, "Successful Tests", f)
```

Maybe the watchdog timer was just slightly too quick for that build?

**Comment by rossabaker** [comment]
Though a build failed without apparent charset locking, I have not seen a failure since #1059.

**Comment by rossabaker** [comment]
💩: https://travis-ci.org/http4s/http4s/jobs/219291720

**Comment by rossabaker** [comment]
:hankey: https://travis-ci.org/http4s/http4s/jobs/219936919

Seems like it's more likely to be just async-http-client lately.  Maybe I need to dive back into that.

**Comment by bfritz** [comment]
4030.3 against release-0.15.x had a Blaze client timeout.  OTOH, I've lost track of what improvements are in master and which are also in 0.15x.
https://travis-ci.org/http4s/http4s/jobs/220031337#L4152

**Comment by bfritz** [comment]
Another in 4058.2 for PR against 0.15.x: https://travis-ci.org/http4s/http4s/jobs/220299325#L1553

**Comment by bfritz** [comment]
WIP:

Build | Scala | Scalaz | Branch | Failure 
------|-------|--------|--------|---------
3945.3 | 2.10.6 | 7.2.9 | 0.16 | [AsyncHttpClientSpec 10s timeout](https://travis-ci.org/http4s/http4s/jobs/215206641#L2056) (x3) with thread dump
3948.3 | 2.11.8 | 7.2.9 | 0.16 | [Blaze ClientTimeoutSpec 10s timeout](https://travis-ci.org/http4s/http4s/jobs/215346335#L1633)<br/>[AsyncHttpClientSpec 10s timeout](https://travis-ci.org/http4s/http4s/jobs/215346335#L1800) (x3)

**Comment by rossabaker** [comment]
I like this table.  This is excellent work.

**Comment by bfritz** [comment]
Wouldn't be surprised if there was a mistake or two...all starts to blur together after a while.

Not seeing obvious patterns, but it's nice to see them layed out in one place.  There was a pretty long run without failures before 3945.5, so it definitely feels like something changed.  Calling it a night now, but I plan to review the history leading up to the first failure and also try to trigger one locally this week.

**Comment by rossabaker** [comment]
Maybe a low-tech way of reproducing it is to slam on the commit in 3945, and its parent.  If one fails a few times and the other does not, that's a really big clue.

**Comment by bfritz** [comment]
Using the Vagrantfile in #1035 against `release-0.15.x` (at 5e1c84104) and with VM CPU capped at 45%, I can reproduce the AHC timeout in about 50% of builds.  Using a [poor man's profiler](https://gist.github.com/bfritz/66055062d4b52373dc0aa21466650a5c), I can see that AHC going through `ClientRouteTestBattery` takes significantly longer than either Blaze client spec:

### AsyncHttpClientSpec:

```
AsyncHttpClient.checkResponse:hs took 208 ms
AsyncHttpClient.checkResponse:hs took 226 ms
AsyncHttpClient.checkResponse:status took 811 ms
AsyncHttpClient.checkResponse:status took 811 ms
AsyncHttpClient.checkResponse:body took 1638 ms
AsyncHttpClient.checkResponse:body took 1712 ms
AsyncHttpClient.checkResponse:headers took 2656 ms
AsyncHttpClient.checkResponse:headers took 2579 ms
AsyncHttpClient.checkResponse:version took 106 ms
AsyncHttpClient.checkResponse:total took 5517 ms
AsyncHttpClient.checkResponse:version took 183 ms
AsyncHttpClient.checkResponse:total took 5503 ms
[info] AsyncHttpClientSpec
[info]
[error] ! Execute GET: /simple (20 seconds, 248 ms)
[error]  java.util.concurrent.TimeoutException: Timed out after 10000 milliseconds (ClientRouteTestBattery.scala:27)
[error] org.http4s.client.ClientRouteTestBattery$$anonfun$1$$anonfun$apply$3.apply(ClientRouteTestBattery.scala:27)
[error] org.http4s.client.ClientRouteTestBattery$$anonfun$1$$anonfun$apply$3.apply(ClientRouteTestBattery.scala:21)
[info]
[error] ! Execute GET: /chunked (20 seconds, 239 ms)
[error]  java.util.concurrent.TimeoutException: Timed out after 10000 milliseconds (ClientRouteTestBattery.scala:27)
[error] org.http4s.client.ClientRouteTestBattery$$anonfun$1$$anonfun$apply$3.apply(ClientRouteTestBattery.scala:27)
[error] org.http4s.client.ClientRouteTestBattery$$anonfun$1$$anonfun$apply$3.apply(ClientRouteTestBattery.scala:21)
[info]
[info] AsyncHttpClient should
[info]   o Strip fragments from URI (218 ms)
[info] Can only reproduce against external resource.  Help wanted.
[info]   + Repeat a simple request (3 seconds, 792 ms)
[info]
[info] 
[info] Total for specification AsyncHttpClientSpec
[info] Finished in 33 seconds, 225 ms
[info] 4 examples, 7 expectations, 0 failure, 2 errors, 1 skipped
```

### BlazeSimpleHttp1ClientSpec:

```
SimpleHttp1Client.checkResponse:hs took 91 ms
SimpleHttp1Client.checkResponse:status took 102 ms
SimpleHttp1Client.checkResponse:hs took 0 ms
SimpleHttp1Client.checkResponse:status took 0 ms
SimpleHttp1Client.checkResponse:body took 626 ms
SimpleHttp1Client.checkResponse:body took 132 ms
SimpleHttp1Client.checkResponse:headers took 147 ms
SimpleHttp1Client.checkResponse:headers took 150 ms
SimpleHttp1Client.checkResponse:version took 98 ms
SimpleHttp1Client.checkResponse:version took 98 ms
SimpleHttp1Client.checkResponse:total took 1190 ms
SimpleHttp1Client.checkResponse:total took 504 ms

[info]
[info] BlazeSimpleHttp1ClientSpec
[info]
[info] + Execute GET: /simple (9 seconds, 133 ms)
[info] + Execute GET: /chunked (9 seconds, 150 ms)
```

### BlazePooledHttp1ClientSpec:

```
Blaze PooledHttp1Client.checkResponse:hs took 85 ms
Blaze PooledHttp1Client.checkResponse:status took 104 ms
Blaze PooledHttp1Client.checkResponse:hs took 0 ms
Blaze PooledHttp1Client.checkResponse:status took 62 ms
Blaze PooledHttp1Client.checkResponse:body took 629 ms
Blaze PooledHttp1Client.checkResponse:body took 142 ms
Blaze PooledHttp1Client.checkResponse:headers took 147 ms
Blaze PooledHttp1Client.checkResponse:headers took 147 ms
Blaze PooledHttp1Client.checkResponse:version took 100 ms
Blaze PooledHttp1Client.checkResponse:version took 98 ms
Blaze PooledHttp1Client.checkResponse:total took 1189 ms
Blaze PooledHttp1Client.checkResponse:total took 574 ms

[info] BlazePooledHttp1ClientSpec
[info]
[info] + Execute GET: /simple (6 seconds, 359 ms)
[info] + Execute GET: /chunked (6 seconds, 346 ms)
```

BlazeSimpleHttp1ClientSpec and BlazePooledHttp1ClientSpec were interleaved during the build.  I separated them above so the timing is easier to parse.

**Comment by rossabaker** [comment]
How hard would it be to comment out `TimeoutSpec` and run this again?  I have discovered wickedness.

**Comment by bfritz** [comment]
Did `rm server/**/TimeoutSpec.scala ; sbt server/clean` and restarted my build loop with 45% CPU.  First build failed:
```
AsyncHttpClient.checkResponse:hs took 108 ms
AsyncHttpClient.checkResponse:hs took 107 ms
AsyncHttpClient.checkResponse:status took 507 ms
AsyncHttpClient.checkResponse:status took 482 ms
AsyncHttpClient.checkResponse:body took 1518 ms
AsyncHttpClient.checkResponse:body took 1519 ms
AsyncHttpClient.checkResponse:headers took 2018 ms
AsyncHttpClient.checkResponse:headers took 2017 ms
AsyncHttpClient.checkResponse:version took 312 ms
AsyncHttpClient.checkResponse:version took 313 ms
AsyncHttpClient.checkResponse:total took 4560 ms
AsyncHttpClient.checkResponse:total took 4563 ms
[info] AsyncHttpClientSpec
[info] 
[error] ! Execute GET: /simple (19 seconds, 998 ms)
[error]  java.util.concurrent.TimeoutException: Timed out after 10000 milliseconds (ClientRouteTestBattery.scala:27)
[error] org.http4s.client.ClientRouteTestBattery$$anonfun$1$$anonfun$apply$3.apply(ClientRouteTestBattery.scala:27)
[error] org.http4s.client.ClientRouteTestBattery$$anonfun$1$$anonfun$apply$3.apply(ClientRouteTestBattery.scala:21)
[info] 
[error] ! Execute GET: /chunked (19 seconds, 988 ms)
[error]  java.util.concurrent.TimeoutException: Timed out after 10000 milliseconds (ClientRouteTestBattery.scala:27)
[error] org.http4s.client.ClientRouteTestBattery$$anonfun$1$$anonfun$apply$3.apply(ClientRouteTestBattery.scala:27)
[error] org.http4s.client.ClientRouteTestBattery$$anonfun$1$$anonfun$apply$3.apply(ClientRouteTestBattery.scala:21)
[info] 
[info] AsyncHttpClient should
[info]   o Strip fragments from URI (26 ms)
[info] Can only reproduce against external resource.  Help wanted.
[info]   + Repeat a simple request (3 seconds, 491 ms)
[info] 
[info] 
[info] Total for specification AsyncHttpClientSpec
[info] Finished in 31 seconds, 868 ms
[info] 4 examples, 7 expectations, 0 failure, 2 errors, 1 skipped
```

**Comment by rossabaker** [comment]
Well, hell.

The good news is this is starting to look semi-reproducible.  Unless we're just simply asking too much of 10 seconds on (virtually) limited hardware.  I don't know why it should be so much slower, though.

**Comment by bfritz** [comment]
@rossabaker Pretty sure that increasing the timeout in `JettyScaffold` (or overriding it in `AsyncHttpClientSpec`) to 15 seconds would avoid most of the failures we see now.  On the otherhand, it feels wrong that AHC takes ~11 seconds (in CPU-throttled 2 core VM) to make the same calls that Blaze makes in ~2 seconds.

I spent some time with a profiler trying to understand what's chewing up so much time in `AsyncHttpClientSpec`, but came up empty.  Feels like there might be a problem with the way we're using AHC, or maybe even its implementation, but I can't put my finger on it yet.

**Comment by rossabaker** [comment]
Okay.  Let's test that theory by increasing that timeout, and figure out how to optimize AHC later.

With fs2-reactive on the horizion (#1096), AHC may be getting a major facelift soon, anyway.

**Comment by bfritz** [comment]
Ah, there's the holdup:

![asynchttpclientspect_object_wait_for_5s](https://cloud.githubusercontent.com/assets/70307/24970063/f3c4bee6-1f80-11e7-9e73-26561cb12d5b.png)

And overall:
![asynchttpclientspect_object_wait_overall](https://cloud.githubusercontent.com/assets/70307/24970172/56c82582-1f81-11e7-837b-b6923fa9eeb0.png)

**Comment by 2chilled** [comment]
FYI: We can safely reproduce this issue within our own integration tests using async client. We have no issues with the blaze client. Would love to see this fixed! TIA!

**Comment by rossabaker** [comment]
Lots of changes to the AHC libraries and tests, and I haven't seen this in a while.  Closing.
