### ISSUE TITLE
documentation menu links are broken for v0.17 and v0.15 scaladoc

### ISSUE THREAD

**Issue by bfritz** [http4s/http4s#1061]
Documentation dropdown links to:
* http://http4s.org/v0.17/
* http://http4s.org/v0.17/api/org/http4s/
* http://http4s.org/v0.15/api/org/http4s/
and all 3 are broken.  The v0.15 scaladoc is currently at:
http://http4s.org/v0.15/api/#org.http4s.package

**Comment by rossabaker** [comment]
Even the best baseball player goes 0 for 3 some days.

**Comment by bfritz** [comment]
Closed via #1062 and #1063.
