### ISSUE TITLE
The quick start doc page should show more install help than just g8

### ISSUE THREAD

**Issue by Daenyth** [http4s/http4s#1083]
g8 is great, but most projects don't start from scratch using it, or if they do, they're using their own base.

Show how to add with `libraryDependencies`. Currently the "Service" doc page lists this, which isn't at all discoverable. Make a dedicated "install" page in addition to the quick doc, even if a section needs to be repeated.

The quick start page can show

> To set up a demo project, use `g8` like this: ...
> To add http4s to an existing build.sbt project, add this: ...

The install page should also show the version matrix listing which libraries it pins to which versions - eg 0.15.8a is scalaz-7.?

**Comment by bfritz** [comment]
I'm a bit out-of-the-loop, but #1117 is probably related.

**Comment by calvinbrown085** [comment]
@Daenyth Do you think this is still necessary? When looking at the docs it seems reasonable that people would scroll through all the links on the right hand side.

`Quick Start`
`Service`
`The http4s DSL` 

It feels like there is enough info in there to not have to repeat it in 2 places.

I'm open to discussion on this, 👍

**Comment by rossabaker** [comment]
I think it'd still be wise to make an example build file prominent.  A lot of times when I try a new project, I just scan for the "%%" and paste things and start hacking, and that's something that's lacking for us.

**Comment by calvinbrown085** [comment]
I can work on this one.

**Comment by calvinbrown085** [comment]
I can work on this one.
