### ISSUE TITLE
Documentation doesn't have a page for testing

### ISSUE THREAD

**Issue by Daenyth** [http4s/http4s#1084]
How do I test my services?

**Comment by rossabaker** [comment]
My answer to this has been "it's just functions," which isn't complete, but it resonates and gets people started.  So a good example will make that clear.  

We've got a helper full of matchers, `Http4sMatchers`, which I'd like to split off, but it necessitates an introduction of an http4s-specs2... and then what about scalatest?  Relates to #1024.

Mention of the arbitrary instances we provide and scalacheck would be welcome here, too.

**Comment by rossabaker** [comment]
Actually, this is #969.
