### ISSUE TITLE
How do I handle authorization?

### ISSUE THREAD

**Issue by Daenyth** [http4s/http4s#1085]
AuthedService wants a `getUser: Request => Task[T]` so it clearly only deals with Authentication. What about authorization? Is there a recommended pattern?

**Comment by reactormonk** [comment]
I'd say Authorization comes later in the API, so it's not really part of http4s anymore. Any other opinions?

**Comment by rossabaker** [comment]
I think it's possibly worth showing how the user type might include information about roles.  I think an authorization framework would be out of scope, but authentication providing the information to driver authorization decisions could be a useful hint.

**Comment by cquiroz** [comment]
I agree, authorization is a large subject and normally varies a lot depending on the situation. It sounds like something your application should handle on its own

The one thing that could help is perhaps storing more metadata as part of the user. E.g. User's group but again it sounds to be out of http4s' scope

**Comment by dozed** [comment]
To give an example, this is how one can do authorization with `Either` and simple functions:

```scala

import scalaz._, Scalaz._
import doobie.imports._

object AuthorizationModule {

  // role check
  def checkAdmin(client: User): ErrorCode \/ Unit = {
    if (client.isAdmin) ().right
    else ErrorCode.UserIsNotAdmin.left
  }

  // authorize operations
  def authorizeBaz(client: User): ErrorCode \/ Unit = ???

  def authorizeFoo(client: User): ErrorCode \/ Unit = ???

  def authorizeBar(client: User): ErrorCode \/ Unit = ???


  // with optional database IO
  def checkCanBaz(isFoo: Boolean, isBar: ConnectionIO[Boolean]): ConnectionIO[ErrorCode \/ Unit] = {
    isBar.ifM(FC.delay(().right), other)
  }

  // with an operation type
  def checkAuthorized(op: Operation, client: User): ErrorCode \/ Unit = {
    op match {
      case Operation.Edit   if !isBar => ().right
      case Operation.Delete if !isFoo => ().right
      case _                          => ErrorCode.Forbidden.left
    }
  }

}
```

**Comment by kevinmeredith** [comment]
> I'd say Authorization comes later in the API, 

Could you please say more, @reactormonk? I don't understand what "later" means.

**Comment by reactormonk** [comment]
Later in your code flow. First you find out who you're talking to, and then later you find out if that person is actually authorized.

**Comment by jmcardon** [comment]
I discussed with @rossabaker on gitter, and I will be tackling this specific issue for http4s.

In particular i can think of: Sessions, Cookies, JWTs and Bearer tokens to use, on top of RBAC for the traditional User/Admin/Staff distinctions in a lot of different applications.

I'd appreciate any other ideas related to this that people could use.

**Comment by jmcardon** [comment]
Updating this issue now that M4 is out with better docs:

[As promised a few months prior.](https://jmcardon.github.io/tsec/docs/http4s-auth.html).

**Comment by rossabaker** [comment]
Closing this for now.  If there are specific improvements needed, please open another issue.
