### ISSUE TITLE
Client doc page only shows how to use pooled client

### ISSUE THREAD

**Issue by Daenyth** [http4s/http4s#1086]
Example being

```
import org.http4s.client.blaze._
val httpClient = PooledHttp1Client()
httpClient.expect[A](url)
```

But on the json page there's an example which is unexplained:

```
import org.http4s.client._
POST(uri("/hello"), json"""{"name": "Alice"}""")
```

And further on the scaladoc page, there's a `SimpleHttp1Client` with no example usage

**Comment by rossabaker** [comment]
I intend to deprecate `SimpleHttp1Client` and make the way we create clients more coherent with the way we create servers as part of #1025.

**Comment by Daenyth** [comment]
Sounds good. There's still the difference from the `POST` example.

Also I'm trying to manually call `Request.apply` to make a request I can use in a unit test, and I can't figure out yet how to pass a body with `foo.asJson` - I get

```
[error]  found   : io.circe.Json
[error]  required: org.http4s.EntityBody
```

**Comment by rossabaker** [comment]
`Request(POST, uri).withBody(json)` or `POST(uri, body)`.  The latter requires `import org.http4s.client._`

**Comment by rossabaker** [comment]
There is only one kind of client now.  I think this is obsolete.
