### ISSUE TITLE
Move to fs2-reactive

### ISSUE THREAD

**Issue by zainab-ali** [http4s/http4s#1096]
[fs2-reactive](https://github.com/to-ithaca/fs2-reactive) is a reactive streams implementation for fs2.  It has passed all mandatory tck tests, and is likely to be ready for release over the coming weeks.
Now would be a good time to discuss if:

1. http4s is willing to move to this once it has a first release
2. There are any key features lacking in fs2-reactive

**Comment by ChristopherDavenport** [comment]
My questions
1. What implementation are you looking to use this for? It is currently in use in async-http-client, or will be once we get it implemented. 
2. How would it be implemented?
3. We thought the best place to start implementing scala-js once we get it into core would be async-http-client. Does this intend to have scala-js support?

My concerns

1. Maturity. At 8 commits I can't help but be a bit skeptical, although passing tests is a great sign.
2. Multiple Scala Versions.
3. Code Coverage. I see the plugin but no information.
4. Documentation, if we are going to jump over we'd want information not to be concentrated just in the implementers.
5. Large sections of code commented, such as `PublisherSpec`

I may go dive into the code a bit more later, but those were my initial overview thoughts.

**Comment by wedens** [comment]
What http4s will gain from using it instead of using fs2 directly?
For spec. implementation to be useful, you need to use spec. and http4s doesn't use reactive streams.

**Comment by rossabaker** [comment]
While the reactive streams spec is very well designed for library interop, it's a mutable, null unsafe hellscape in direct use.  So I see `EntityBody` still being based on fs2.  But as a new http4s-reactive module, I see two big wins for http4s:

* As noted above, pulls out the general code in the async-http-client implementation.
* Is a more general form of the proposed Monix support (#1051).  It could provide an EntityEncoder and EntityDecoder for reactive streams, which would cover Monix, akka-stream, and others.  It's a nice bridge to those who didn't choose, or are migrating to, fs2.

I wanted something like this library for scalaz-stream, but never got around to writing it.  I'm very glad to see @zainab-ali picking this up for fs2.

**Comment by yilinwei** [comment]
The purpose of this library, from the name is meant to be a bridge which goes from fs2, to a different reactive streams implementation. 

I think it makes sense to do this at the fs2 layer, rather than each project and have a rigorous implementation to make sure all the cases are dealt with between fs2 and other streaming libraries.

**Comment by rossabaker** [comment]
That's why I think, at minimum, this would help the http4s-async-client, which implemented a lot of this bridge, and probably not as well as it's done here.

Whether entity codecs for `Publisher` and `Subscriber` carry their own weight instead of an explicit conversion to fs2 is a more open question.  Any http4s-reactive would be an extremely thin wrapper around this.

**Comment by zainab-ali** [comment]
To clarify, `fs2-reactive` is **not yet** ready for release.  The code itself was initially ripped out from a proprietary project, before being properly tested against the tck.  [Here](https://github.com/to-ithaca/fs2-reactive/issues/4) is a list of outstanding issues, which will be tackled over the next few weeks.  Documentation, cross scala versions and snapshot publishing are all outstanding.  I would never use a library dependency without docs and rigorous tests, and certainly wouldn't expect it of http4s.

However, the intention is that the library will exist as a rigorous, well documented implementation of reactive streams.

**Comment by rossabaker** [comment]
fs2-reactive-streams looks like it's working as I'd hoped for http4s-async-http-client.  I can still imagine an http4s-reactive-streams module that provides an `EntityEncoder` and `EntityDecoder`.  Does anyone want to try it?

**Comment by ChristopherDavenport** [comment]
I believe this is closed by #1146
