### ISSUE TITLE
bin/travis runs twice sometimes

### ISSUE THREAD

**Issue by bfritz** [http4s/http4s#1110]
Not sure if this is an issue with our setup or Travis itself, but occasionally `bash bin/travis` is run twice.  Sometimes one passes and the other fails.

Recent example is job 4091.4:
* first exit with code 0 - https://travis-ci.org/http4s/http4s/jobs/221074254#L1149
* second exit with code 1 - https://travis-ci.org/http4s/http4s/jobs/221074254#L1350

Details from the raw job output[1].  All times UTC:

command | reported start | reported finish | reported duration (s)
--------|----------------|-----------------|-----------------------
bash bin/travis (run a) | 19:00:32 | 19:03:45 | 193.4
bash bin/travis (run b) | 19:00:57 | 19:11:18 | 621.4

[1] Grab logs with:
    `B=4091.4; J=221074254; curl -L -o tmp/$B "https://api.travis-ci.org/jobs/$J/log.txt"`
    then grep `tmp/$B` for "travis_time:" and look for "exited with" to find the end of the `bash bin/travis` runs. The timings are "hidden" in escape codes, so it may not be visible depending on the configuration of your terminal and/or pager.

**Comment by bfritz** [comment]
Looks like it might be two Travis CI containers writing to the same output stream:
```
B=4091.4
J=221074254
curl -L "https://api.travis-ci.org/jobs/$J/log.txt" | head -n 200 | grep -n -e '^hostname:' -e '^startup:' -e '^instance:'
```
```
2:hostname: i-0b11bca-precise-production-2-worker-org-docker.travisci.net:6c382be3-629b-4266-958c-c9e02902c810
4:instance: b939d60:travis:scala
5:startup: 733.071024ms
7:hostname: i-0579528-precise-production-2-worker-org-docker.travisci.net:8c73f85f-e60d-4441-8058-e9185b75df1f
9:instance: 4427fa9:travis:scala
10:startup: 787.2206ms
```

**Comment by ChristopherDavenport** [comment]
This is terrifying.

**Comment by bfritz** [comment]
Sent an email summarizing this to Travis support.  Will update this issue with any news.

**Comment by bfritz** [comment]
The Travis team is aware of this issue and it might be fixed now.  See https://github.com/travis-ci/travis-ci/issues/7605#issuecomment-294156349 .

**Comment by ChristopherDavenport** [comment]
Heres to hoping one of our CI problems disappear.

**Comment by bfritz** [comment]
Feeling optimistic this afternoon.  Easy to reopen if we see it again.
