### ISSUE TITLE
Quick Start page instructions fail with "not found: object scalaz"

### ISSUE THREAD

**Issue by CalebFenton** [http4s/http4s#1117]
Following the quickstart guide here: http://http4s.org/v0.15/

```bash
╭─caleb@haxcalibur  ~/repos ‹›
╰─$ take delme
╭─caleb@haxcalibur  ~/repos/delme ‹›
╰─$ sbt -sbt-version 0.13.13 new http4s/http4s.g8
[info] Set current project to delme (in build file:/Users/caleb/repos/delme/)
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
name [http4s quickstart]:
organization [com.example]:
package [com.example.http4squickstart]:
scala_version [2.12.1]:
http4s_version [0.17.0-M1]:

Template applied in ./http4s-quickstart

╭─caleb@haxcalibur  ~/repos/delme ‹›
╰─$ cd http4s-quickstart
╭─caleb@haxcalibur  ~/repos/delme/http4s-quickstart ‹›
╰─$ find . -name '*.scala'
./src/main/scala/com/example/http4squickstart/HelloWorld.scala
./src/main/scala/com/example/http4squickstart/Server.scala
╭─caleb@haxcalibur  ~/repos/delme/http4s-quickstart ‹›
╰─$ sbt run
[info] Loading project definition from /Users/caleb/repos/delme/http4s-quickstart/project
[info] Updating {file:/Users/caleb/repos/delme/http4s-quickstart/project/}http4s-quickstart-build...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] Set current project to http4s-quickstart (in build file:/Users/caleb/repos/delme/http4s-quickstart/)
[info] Updating {file:/Users/caleb/repos/delme/http4s-quickstart/}http4s-quickstart...
[info] Resolving jline#jline;2.14.1 ...
[info] Done updating.
[info] Compiling 2 Scala sources to /Users/caleb/repos/delme/http4s-quickstart/target/scala-2.12/classes...
[error] /Users/caleb/repos/delme/http4s-quickstart/src/main/scala/com/example/http4squickstart/Server.scala:7: not found: object scalaz
[error] import scalaz.concurrent.Task
[error]        ^
[error] /Users/caleb/repos/delme/http4s-quickstart/src/main/scala/com/example/http4squickstart/Server.scala:19: not found: type Task
[error]   override def server(args: List[String]): Task[Server] =
[error]                                            ^
[error] two errors found
[error] (compile:compileIncremental) Compilation failed
[error] Total time: 3 s, completed Apr 14, 2017 12:49:38 PM
```

The _built.sbt_ file doesn't include scalaz as a dependency, so I'm guessing I need to somehow have scalaz installed somewhere else? No idea. I'll keep reading the documentation.

Adding `"org.scalaz"     %% "scalaz-core"         % "7.2.10"` to _build.sbt_ results in this error: `object concurrent is not a member of package scalaz`.

**Comment by CalebFenton** [comment]
I tried with version `0.15.8a` instead because it looks like there's been some dependency shifting going on. This works fine.

Looks like the issue is the tutorial is out of date or the giter8 template is out of date. I'll look for examples that work with the latest version.

**Comment by bfritz** [comment]
@CalebFenton Sorry for the confusion.  You are right that we're in the middle of some shuffling.  The versions page might be useful:
http://http4s.org/versions/
but we also need to round off some of these sharp corners.

And don't hesitate to stop by the gitter channel if you get stuck on anything:
https://gitter.im/http4s/

**Comment by rossabaker** [comment]
Yes, this is related to the work on http4s/http4s.g8#15.  We hit some turbulence with the `stable` modifier in g8.  Once we've worked through that, we can have two versions of the g8 template through the transition.

Let's leave this open to make sure we circle back and document the correct branch on 0.17's quickstart when the dust settles on the g8.

**Comment by CalebFenton** [comment]
Thanks! I appreciate the super fast response!
