### ISSUE TITLE
java.lang.NoClassDefFoundError: scalaz/FoldableParent

### ISSUE THREAD

**Issue by lambdista** [http4s/http4s#1135]
I got that error when trying to run the basic hello world example created using:
```
$ sbt -sbt-version 0.13.13 new http4s/http4s.g8
```
After some head-scratching I think I was able to reproduce and isolate the cause.

Apparently, adding a dependency to monocle core, as in the following settings, causes that runtime error to happen:

```scala
scalaVersion := "2.12.2"

val Http4sVersion = "0.15.9"

libraryDependencies ++= Seq(
 "org.http4s"     %% "http4s-blaze-server" % Http4sVersion,
 "org.http4s"     %% "http4s-circe"        % Http4sVersion,
 "org.http4s"     %% "http4s-dsl"          % Http4sVersion,
 "com.github.julien-truffaut" %% "monocle-core" % "1.4.0",
 "ch.qos.logback" %  "logback-classic"     % "1.2.1"
)
```

This also happens using Scala 2.11.8, but in this case the error changes in:
```
java.lang.NoSuchMethodError: scalaz.syntax.Syntaxes$kleisli$.ToKleisliFAOps(Ljava/lang/Object;)Lscalaz/syntax/KleisliFAOps
```
I guess @julien-truffaut could be interested in this too.

**Comment by reactormonk** [comment]
That's most likely scalaz version incompatibility. Check for evictions, and/or the graph via https://github.com/jrudolph/sbt-dependency-graph

**Comment by lambdista** [comment]
As suggested by Paul Snively, via twitter, with version 0.15.9a the issue is not present.
