### ISSUE TITLE
Header reform

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#1143]
Current header model is bad.  Depends on a global registry, abuses equality, hard to extend.  Another problem to be solved by typeclasses over subtyping?

[insert better description here]

@wedens has published http://lpaste.net/8545691949200310272

**Comment by rossabaker** [comment]
Discussion notes, for those who can't keep up with Gitter:
- That funny looking Sigma typeclass preserves `putHeaders` with typed headers.  It's really smart.
- `Headers` as an `Iterable[Header]` is doomed.  An `Iterable[RawHeader]` is possible, but not necessarily desired.  Maybe we equip it with the important methods, and there's always the underlying `Vector` for full collection use.

**Comment by bryce-anderson** [comment]
I like the typeclass pattern. Probably the primary reason we didn't use it from the start was so that header parsing could be memorized. Has that been abandoned?

**Comment by rossabaker** [comment]
Yes, we'd lose that.  I think the only ones we're likely to refer to multiple times on a regular basis are `Content-Type` and `Content-Length`, which could just as well be memoized on the message that contains them.

**Comment by ChristopherDavenport** [comment]
I'm going to see what can be done. I'm not sure why we have a problem with an iterable at least for RawHeader. I know you guys know this better than me, so I wonder what I'm missing.

As we continue the length, if we get a CRLF that is not followed by LWSP char then we have a header, if we do we can dismiss the CRLF and LWSP and continue the body. The first Null Line  where a null line is `CLRF CRLF`

There may be illegal header interactions but header definitions at their core seem to behave.

Here is a specification from [RFC 822](https://tools.ietf.org/html/rfc822) Page 8 Section 3.2 **Header Field Definitions**

```
field       =  field-name ":" [ field-body ] CRLF

field-name  =  1*<any CHAR, excluding CTLs, SPACE, and ":">

field-body  =  field-body-contents
                    [CRLF LWSP-char field-body]

field-body-contents =
                   <the ASCII characters making up the field-body, as
                    defined in the following sections, and consisting
                    of combinations of atom, quoted-string, and
                    specials tokens, or else consisting of texts>
```

**Comment by rossabaker** [comment]
I think an iterable of `RawHeader` is absolutely possible, and whether one thinks it's a good idea probably correlates pretty well with one's opinion of standard library collections.  I, having a mixed opinion on those, have a mixed opinion here. :)

**Comment by m-sp** [comment]
finally resolved with https://github.com/http4s/http4s/issues/4297
