### ISSUE TITLE
Improve Techempower benchmarks

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#1145]
So, it's TechEmpower season again.  \<rant>I think many people use the TechEmpower Benchmarks badly.  They should be one tool of many for consideration, but are instead frequently cited in lieu of thinking about one's problem contextually, with consideration for composability, community, learning curve, documentation, monitoring, or any number of things that are at least as important as the one or two tests that bear little resemblance to the service they're trying to build.  _If there were one magic number that made the best HTTP library for everyone, there wouldn't be 140 projects and growing._\</rant>

Like these benchmarks or not, they're important for outreach, and we shouldn't be signing our name to what's not our best work.  I made a few small tweaks to the benchmark and already improved plaintext performance by 10% locally.  I bet we can do more without really gaming the system.  
If anyone wants to help us do better, I've [forked into http4s](https://github.com/http4s/FrameworkBenchmarks).  We can collaborate there at our own pace, and submit a PR in time for the next round.

**Comment by rossabaker** [comment]
Also, kudos to @bryce-anderson, who put together a raw blaze example that did quite well!

**Comment by ChristopherDavenport** [comment]
- [ ] Switch from `Twirl` -> `ScalaTags`
- [ ] Check with Someone Smarter than me, But I think our Pool Size for HikariCP is far too large
- [ ] Remove All Overhead possible on Plaintext. Blaze is 22x Faster Than Us And We are Using It. 

Is `Task` or `Stream/Process` faster for pulling multiple entries with Doobie? Seems like clamp queries is exactly what Query.processWithChunkSize is all about.

**Comment by rossabaker** [comment]
@jmcardon and @emilypi have been hard at work on this.  Leaving this open until we have a better version committed upstream.  Assigning to only Jose, because I can't also assign to Emily.

**Comment by jmcardon** [comment]
@balatbn because the techempower benches currently live are from an EOL version. We've improved a lot overall. Also there's factors like interpretation into `IO` and whatnot.

**Comment by neko-kai** [comment]
Techemower stil doing damage:

> I explained why I don't like http4s in another thread and got a lot of shit for it.
>  *  It's one of the slowest out of >200 tested frameworks.

https://www.reddit.com/r/scala/comments/dcvctd/sbtplay_framework_in_a_nutshell/f2db2hy/?context=3

**Comment by emilypi** [comment]
@neko-kai feel free to handle this. I've deleted my repository and all previous attempts to improve this for various reasons, but I'd be happy to bless and review anything you come up with. It's not more than a few weekends worth of http4s stuff - the endpoints are simple, and profiling should be simple as well.

**Comment by wjoel** [comment]
@rossabaker I've taken a stab at this, and on my machine my changes improve the composite score by 2.14 (from 271 points to 583 points).

Please take a look at https://github.com/wjoel/FrameworkBenchmarks/tree/improve-http4s and suggest further improvements.

I plan on submitting a PR soon, but it would be great if you could make sure I'm not missing anything. I've tried jsoniter-scala, Skunk, Ember backend (which only got about 25% of the performance of Blaze), Jetty backend, setting socket settings, and changing thread pools, as well as updating to JDK 15 (and G1GC which works great on that one, though I should ParallelGC once more), Scala 2.13.3, and cats-effect 2.2.0.

What I have on that branch summarize the changes that got the best score overall.

The biggest improvement by far comes from replacing doobie with Quill and it's async postgres driver. Updating http4s didn't make much of a difference, but then again it was only from 0.21.3 to 0.21.7, so perhaps that's to be expected.

If the production numbers scale in a similar fashion, and that's a big if, it would put http4s ahead of play2-scala, and from 275th to 194th overall.

After getting familiar with some of the implementations in their repository, I have to say it really is a garbage comparison overall, but people do look at it and I think improving the score of http4s on that benchmark matters, even if I wish it didn't. Overall, I'm pleased with the performance of Blaze and http4s, not only the throughput but also the latency.

**Comment by wjoel** [comment]
@ChristopherDavenport what do you mean by "Remove All Overhead possible on Plaintext. Blaze is 22x Faster Than Us And We are Using It"? What should I change to improve the performance on plaintext for http4s (which does seem a bit too low)?

**Comment by wjoel** [comment]
I found one odd thing from profiling, where Http1ServerStage.renderResponse was parsing the accept header, even if it's not using it. Fixed in https://github.com/http4s/http4s/pull/3701, I hope. Increases the throughput on plaintext by another 15-20%.

**Comment by rossabaker** [comment]
Thanks, @wjoel!

This strikes at the heart of whether we are showing idiomatic usage or doing cynical marketing.  Quill is not a common choice among http4s users, and though I haven't used this specific one, I've soured on DSLs like it.  But, I agree with your commentary.  Let's use our docs to show the recommended way, and optimize the benchmarks for marketing .

I left a few comments.  I think you're generally on the right track, and I don't think anything I mentioned is a blocker to submitting it.

**Comment by wjoel** [comment]
We were using Quill with http4s in two projects at work for more than a year until quite recently when we switched to Doobie to reduce compile times, so it's not unrealistic. ;) I too prefer not using the DSL (harder to learn than just using straight SQL, especially for new developers), but switching to Quill for the async database support is not unreasonable if performance is a concern and the database is the bottleneck, as in those benchmarks.

Thanks for your comments, I'll try and address them later this week.

**Comment by wjoel** [comment]
I've addressed the comments (I think!) and submitted https://github.com/TechEmpower/FrameworkBenchmarks/pull/6040

**Comment by rossabaker** [comment]
Approved over there. Thanks!
