### ISSUE TITLE
Codecov is full of nonsense

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#1162]
How did #1161 affect coverage at all?

Let's figure out what we're doing wrong or disable it. It's just noise right now.

**Comment by ChristopherDavenport** [comment]
So looking here the changes may be associated with actual randomness.

Here are the [changes](https://codecov.io/gh/http4s/http4s/pull/1161/changes).

Just a quick look makes me feel as though our [arbitrary testing](https://github.com/http4s/http4s/blob/release-0.15.x/testing/src/main/scala/org/http4s/testing/ArbitraryInstances.scala) may be causing different code to be covered. For example arbitrary uri could have missed a particular scheme. Or when testing IPV6 then it calls atMost which calls timesBetween. This would if small enough cause a nonce to go stale and then call drop stale. 

Unfortunately, I think this may be on us.

**Comment by rossabaker** [comment]
I think this explanation is correct.
