### ISSUE TITLE
GZip middleware does not add gzip trailer

### ISSUE THREAD

**Issue by mrdziuban** [http4s/http4s#1167]
As described in [RFC 1952](https://www.ietf.org/rfc/rfc1952.txt) gzipped data should contain an 8 byte trailer including a CRC32 checksum and the length of the data. The gzip middleware is not adding this trailer, resulting in "unexpected end of file" errors when trying to extract the data with gunzip (see https://github.com/mrdziuban/http4s-gzip-test for examples). I'm happy to help with this where I can but my knowledge of streams and pipes is still a bit lacking.

**Comment by rossabaker** [comment]
This trailer is also missing in the scalaz-stream version.  This could be one we want to backport when all is said and done.
