### ISSUE TITLE
Changing Uri when copying a Request should clear pathInfo

### ISSUE THREAD

**Issue by frejucafre** [http4s/http4s#1183]
When copying a request object and supplying a new uri, e.g. `req.copy(uri = uri("/new"))`, pathInfo does not currently get cleared. This results in confusing behavior as the previous pathInfo isn't necessarily valid anymore in the new context. Thus, the more intuitive behavior would be to clear the `pathInfo` when uri is changed so that a new, "fresh" copy of the request object is obtained.

**Comment by rossabaker** [comment]
I'm afraid of what this might break if we change it in 0.15, but it seems like a good thing to do for 0.16.

**Comment by sportanova** [comment]
I'd like to take a crack at this - would the best way be to create a custom copy method?

**Comment by reactormonk** [comment]
Just start writing one. The `uri = uri("/new")` syntax looks for the corresponding argument name in the method. Be prepared for some boilerplate.

**Comment by rossabaker** [comment]
Thanks, @sportanova.

You can supply a `copy` method to hide the auto-generated one.  Just create a method called `copy` with each member of the `Uri` case class as a parameter that defaults to the current value.

**Comment by rossabaker** [comment]
Fixed by #1213
