### ISSUE TITLE
Sporadic Stream App Test Failure

### ISSUE THREAD

**Issue by ChristopherDavenport** [http4s/http4s#1189]
Probably a Travis is to small error similar to the blaze tests, however this has been intermittently failing and needs to be investigated.

```
[error]   x requestShutdown Shuts Down a Server From A Separate Thread (10 seconds, 999 ms)
[error]    an exception was thrown null (StreamAppSpec.scala:54)
[error] org.http4s.util.StreamAppSpec.$anonfun$new$13(StreamAppSpec.scala:54)
```

**Comment by rossabaker** [comment]
I think this is related to the failing client timeout tests.  Something is just blocking threads for too long.  Look at the ridiculous times we see for trivial tests in Travis, for example.

**Comment by ChristopherDavenport** [comment]
Is this seemingly resolved now that we have switch to GCE builds?

**Comment by rossabaker** [comment]
Yes, and good riddance.
