### ISSUE TITLE
WebSocket acceptWithActor

### ISSUE THREAD

**Issue by Lasering** [http4s/http4s#1196]
It would be awesome to have a module like the http4s-twirl but for handling a websocket with an actor [like the Play Framework 2.4 does](https://www.playframework.com/documentation/2.4.x/ScalaWebSockets#Handling-WebSockets-with-actors).

**Comment by reactormonk** [comment]
Actors are a rather low-level primitive, could you give an example where it would be an advantage to use one instead of a Stream?

**Comment by Lasering** [comment]
Mainly it would be to talk with existing code that is implemented using actors. Also actors map really well to websockets since you are sending messages between the client and the server.

The implementation should be somewhat straight forward (although I haven't been able to get it to work), the core idea is what is done [here](https://github.com/playframework/playframework/blob/2.4.11/framework/src/play/src/main/scala/play/core/actors/WebSocketActor.scala#L45).

**Comment by reactormonk** [comment]
You could create an `Exchange` where one end sends messages to the actor, and pass the other end to the actor to send in received messages.

**Comment by rossabaker** [comment]
It's easy to connect actors to streams.  Here's a blog post on connecting to [scalaz-stream](http://stew.vireo.org/posts/scalaz-streams-and-actors/).  fs2 would be similar, and I bet has been implemented by someone.

If you are operating in terms of akka-stream, then fs2-reactive adapts from those to fs2.

**Comment by Lasering** [comment]
Is passing a `Queue` to an actor with a message a good practice? I suspect it is not since `Queue` is inside the package `scalaz.stream.async.mutable` or `fs2.async.mutable`.

PS: I know that in the article they any not passing it via a message but rather via the constructor. I was trying to imitate the way play framework does it, and it lead me to have to pass it in a message.

**Comment by reactormonk** [comment]
Passing in via message is the path to the dark side, aka `IllegalStateException`. If you can pass it in via constructor, I'd recommend doing it that way.

**Comment by rossabaker** [comment]
Yeah, I see the queue as being the state that the actor maintains.  The actor acts as an abstract message sink that adapts to an fs2.Stream.  If senders to the actor need to know about the queue, then the actor is not providing any value and senders should just enqueue directly.  I think the two most plausible solutions are "pass via constructor" and "don't use an actor".

**Comment by Lasering** [comment]
The way Play implemented their `acceptWithActor` is:

- They created an Akka extension so they could create a system actor called `websockets`. This actor is at the top of the supervision hierarchy for actors that handle websockets.
- Then for each websocket, `s`, they create two actors:

  1. The `s"supervisor-$s"` which is a child of `websockets` (the `$s` is just to ensure you don't get repeated names).
  2. The `handler` which is a child of `supervisor-$s` and also the actor the user of `acceptWithActor`wants to use.

I like their approach since its has some nice features:

- You get a properly defined, independent supervision hierarchy for websocket actors.
- The `supervisor` can act as the actor on the other end of the websocket, aka the `handler` is the server side of the websocket and the `supervisor` is the client (browser) side of the websocket. This way the `handler` can simply answer to `sender()` to send messages to the browser. Also this has the nice property that whenever the websocket is closed by the browser the `supervisor` can detect it and simply send a `PoisonPill` to `handler` effectively signaling the socket has closed, the `handler` only has to override `postStop` to know the client closed the socket.

The tricky part is the constructor of the `handler` must be invoked inside the `supervisor`, because otherwise it would be impossible for `handler` to be a child of `supervisor`, but to do so you need to pass the queue.

**Comment by Lasering** [comment]
The `websockets` system actor was the one which was causing me so much trouble. After deciding not to use it I solved the problem in no time. [Here is the gist with the solution](https://gist.github.com/Lasering/ce9e137e96c93386ef125ae924b2f6db).

It only handles Text from the websocket but it should pretty straightforward to implement a typeclass capable of handling any other type like Json (Play also does it).

Unfortunately I not longer get the nice "namespace" websockets in the actor names (nor the supervision hierarchy). But that is a fair price in exchange for not having to send mutable state via a message.

If you are interested I can make a PR, probably after introducing the typeclass to handle a generic type, because right now it looks more like a half solution.

**Comment by rossabaker** [comment]
akka isn't a dependency we have in any module, and historically, its breaking changes have caused me an awful lot of trouble.  I'm a bit concerned with putting an akka dependency anywhere in this repo.  An akka integration might make a good repo which we could link to from the docs?

**Comment by SystemFw** [comment]
Slightly off-topic, apologies

> I suspect it is not since Queue is inside the package scalaz.stream.async.mutable or fs2.async.mutable.

That's a case of bad-naming imho. You should replace `immutable` with `readOnly`, and `mutable` with `readWrite`. The `mutable` stuff in fs2 is purely functional as well, just like the `immutable` stuff, since mutation happens via a pure, concurrent reference whose operations are always wrapped in `F`.

**Comment by Lasering** [comment]
@rossabaker Sound like a good ideia, I can make an akka integration repo. Is there any rules I must follow?

@SystemFw So it would be safe to pass a Queue in a message to an actor?

**Comment by SystemFw** [comment]
@Lasering No I actually completely agree with Ross. The actor would act as a facade that receives messages from other actors, which are unaware of the queue (or fs2 for that matter), and encodes things in the queue. This means passing the queue in the constructor.
Also note that in fs2 you won't be able to get a `Queue[F,A]`, but rather an `F[Queue[F,A]`. My comment was merely pointing out the `mutable` there is still `purely functional mutability`, because all the operations happen in `F[_]`, so you have the same guarantees (referential transparency) you would have with `immutable._`

**Comment by ChristopherDavenport** [comment]
@Lasering Chris's Rules For Coding Life

1. Write Code.
2. Enjoy what you write.

Personal Opinion: As you are interfacing with very Functional Library externally with Akka, perhaps consider Typed Actors as they may be easier for testing with Https. However I do not use Akka so this is probably just a manifestation of my love of type safety.

Sidenote: If you find a nice way to do testing with Websockets with Https not using Akka we would be interested as our tests at the moment are non-existent.

**Comment by Lasering** [comment]
Typed Actors or rather in the new incantation Akka Typed is still not stable. Implementing this functionally with a typed actor will prevent anyone that is not using typed actors from using it. I could overload the `handleWithActor` and allow both alternatives.

In the future I might be using Http4s + websockets + Akka in an internal project at my company. If that turns out to be the case I'll want to use secure websockets (wss://). Which means I'll have the necessity to have some tests over `wss`.

**Comment by Lasering** [comment]
Here is the working version (already includes a typeclass, FrameFormatter, to handle more than strings):
https://github.com/Lasering/http4s-akka
It correctly closes the websocket when either of the actors stops, and when the browser closes the websocket the actors stop. Haven't created any tests yet.

You suggested to make an akka integration repo, I really don't know what that implies but I've decided to go with the organization **org.http4s.akka** if that is not acceptable please tell me so I can change.

For the moment the code is implemented for Http4s 0.15.12a and therefor still uses scalaz-stream instead of fs2, although the change should be very straight forward.

I've implemented FrameFormatters for:

- `String` and `Array[Byte]`
- Circe `Json`, any type with a Circe `Encoder` and `Decoder`
- Twirl types: `Html`, `Xml`, `Txt` and `Javascript`.

This means the repo depends on Circe parser and twirl. I don't know the correct way to structure the code, should I create adicional "integration" repos?

**Comment by Lasering** [comment]
The [master branch on http4s-akka](https://github.com/Lasering/http4s-akka) was been updated to use fs2 instead of scalaz-stream. For the moment it depends on http4s 0.17.0-M3.

The code supporting scalaz-stream is in a dedicated branch.
