### ISSUE TITLE
Append path to Uri

### ISSUE THREAD

**Issue by Lasering** [http4s/http4s#1204]
The current method `/` on `Uri` appends the new segment by first URL encoding it. This is very useful, for example, to append a user name to the path:
```
> Uri.uri("https://localhost/api/rest/users") / "Simão Martins"
res25: Uri = Uri(Some(https), Some(Authority(None, RegName(localhost), None)), "/api/rest/users/Sim%C3%A3o%20Martins", Query(), None)
```

However if we want to construct a new Uri from a base Uri, for example:
:
```scala
> val baseUri = Uri.uri("https://localhost/api/v1")
baseUri: Uri = Uri(Some(https), Some(Authority(None, RegName(localhost), None)), "/api/v1", Query(), None)
> baseUri / "/users/scripts/"
res27: Uri = Uri(Some(https), Some(Authority(None, RegName(localhost), None)), "/api/v1/%2Fusers%2Fscripts%2F", Query(), None)
```
We do not get what we wanted (`https://localhost/api/v1/users/scripts/`).

An additional method, which does not perform URL encode, should exist. Something like:
```scala
    def +/(extraPath: String): Uri = {     
      (uri.path.last == '/', extraPath.last == '/') match {
        case (false, true) | (true, false) => uri.withPath(s"${uri.path}$extraPath")
        case (false, false) => uri.withPath(s"${uri.path}/$extraPath")
        case (true, true) => uri.withPath(s"${uri.path}${extraPath.substring(1)}")
      }
    }
```
Or maybe an overloaded version of `/` which receives an additional parameter `urlEncode: Boolean`.

**Comment by reactormonk** [comment]
How about overloading `/` with `List[String]` instead? Or is this purely about syntax.

**Comment by Lasering** [comment]
Like this?
```scala
> Uri.uri("https://localhost/api/v1") / List("users", "scripts")
res27: Uri = Uri(Some(https), Some(Authority(None, RegName(localhost), None)), "/api/v1/users/scripts/", Query(), None)
```

So with a String it would perform the URL encode but with a List of Strings would not? Seems misleading.

**Comment by reactormonk** [comment]
Sure it would still encode. However, it would treat each element of the `String` as a path element.

**Comment by Lasering** [comment]
That would work. Although for the use case above (appending an already built path):
`Uri.uri("https://localhost/api/v1") appendPath "/users/scripts/"` the code would have to be

`Uri.uri("https://localhost/api/v1") / "/users/scripts/".split("/").filter(_.nonEmpty)`

**Comment by reactormonk** [comment]
Or overload `/` to take another `Path` object, that way you can construct the `Path` however you want.

**Comment by Lasering** [comment]
This is already solved by the addPath method on Uri
https://http4s.org/v0.21/api/org/http4s/uri#addPath(morePath:org.http4s.Uri.Path):org.http4s.Uri
