### ISSUE TITLE
Parallel parsing of xml responses produces a null

### ISSUE THREAD

**Issue by cquiroz** [http4s/http4s#1209]
A client that parses the response using XML fails when run in parallel. It produces some null xml responses. 

For example this expression:

```
httpClient.expect[Elem](target).map { xml =>
```

Will work fine on a single request but fail when several are done in parallel. producing a `null` xml

**Comment by cquiroz** [comment]
I'm observing this on the 0.16.x branch

**Comment by ChristopherDavenport** [comment]
Closed by #1214

**Comment by cquiroz** [comment]
Actually I wanted to keep this open until fixed on master, which I'm working on at the moment
