### ISSUE TITLE
EntityDecoder / Message / Client parsing

### ISSUE THREAD

**Issue by julien-truffaut** [http4s/http4s#121]
`Client` expects an `EntityDecoder` in order to decode a `Response`. However, `EntityDecoder[T]` is a `Message => T` and not a `Response => T`. This means that if someone wants to use a client decoder base on a status one has to down cast a `Message` to a `Response` (status present in `Response` but not in `Message`).

I understand the logic behind reusing decoding logic in client and server but I don't think that this abstraction should leak to the user.

From my narrow perspective, it seems that `Request` is a subset of a `Response` so all response decoders should be a able to decode a request but not the other way around.

**Comment by rossabaker** [comment]
I think it was closed due to lack of interest.  It doesn't exist.  Would you like to argue for it? :)

**Comment by dwalend** [comment]
Thanks. I get @julien-truffaut 's point, but won't mistake a request for a response. I'm much more interested in CONNECT support in blaze.

Plus you'd next ask me to write code I'm not yet qualified to write.

**Comment by rossabaker** [comment]
There's nothing inherently HTTP about that proposed codec.  Minus the type aliases, a library of these wouldn't depend on anything from http4s.  Then it starts to look a bit like [scodec-stream](https://github.com/scodec/scodec-stream).
