### ISSUE TITLE
Empty body when using .as[_] with a DSL-based client request

### ISSUE THREAD

**Issue by rajit** [http4s/http4s#1211]
I'm exploring using `client.expect` and other methods vs. the pimped apply methods against the dsl (e.g. `GET(...)`).

This works great:
```
val httpClient = PooledHttp1Client()
val req = httpClient.expect[Json](uri("http://api.postcodes.io/postcodes") / "w1a 1aa")
println(req.run)
```

This, however, gives `Malformed request body: Invalid JSON: empty body`:
```
val req = GET(uri("http://api.postcodes.io/postcodes") / "w1a 1aa").as[Json]
println(req.run)
```

Am I just using the DSL incorrectly?

I'm using http4s 0.15.13 and circe 0.8.0.

**Comment by rajit** [comment]
For full reproduction, my `build.sbt`:
```
scalaVersion := "2.12.2"

libraryDependencies ++= Seq(
  "org.http4s"     %% "http4s-blaze-client" % "0.15.13",
  "org.http4s"     %% "http4s-circe"        % "0.15.13",
  "org.http4s"     %% "http4s-dsl"          % "0.15.13",
  "io.circe"       %% "circe-generic"       % "0.8.0",
  "io.circe"       %% "circe-literal"       % "0.8.0",
  "ch.qos.logback" %  "logback-classic"     % "1.2.1"
)
```

A simple `App.scala` for the `client.expect` method:
```
import io.circe._
import org.http4s.dsl._
import org.http4s.circe._
import org.http4s.client.blaze._

object Main extends App {
  val httpClient = PooledHttp1Client()
  val respExpect = httpClient.expect[Json](uri("http://api.postcodes.io/postcodes") / "w1a 1aa")
  println(respExpect.run)
}
```

And one for the DSL method:
```
import io.circe._
import org.http4s.dsl._
import org.http4s.circe._
import org.http4s.client.blaze._
import org.http4s.client._
                 
object Main extends App {
  val respDsl = GET(uri("http://api.postcodes.io/postcodes") / "w1a 1aa").as[Json]
  println(respDsl.run)
}
```

**Comment by reactormonk** [comment]
That's because on the second one, you're just constructing a `Request` object, not actually executing it. Http4s has no implicit/global magic concerning clients (compare `WSClient`), so executing a request without manually constructing a client is impossible. It still compiles because `.as[_]` is defined on both `Request` and `Response`, see http://http4s.org/v0.15/api/org/http4s/Message.html

**Comment by rajit** [comment]
Thanks, that makes complete sense.

I'd assumed http4s might have a default pooled client somewhere. It turns out I misunderstood the documentation at http://http4s.org/v0.15/json/ under `Receiving raw JSON`. I see now the `POST(uri("/hello"),"""{"name":"Bob"}""").as[Json].run` example is just demonstrating a request and not executing it.
