### ISSUE TITLE
EntityEncoder for a T with a circe.Encoder

### ISSUE THREAD

**Issue by Lasering** [http4s/http4s#1212]
Shouldn't the method [jsonEncoderOf[A]](https://github.com/http4s/http4s/blob/master/circe/src/main/scala/org/http4s/circe/CirceInstances.scala#L71) be declared implicit to allow things such as:

```scala
import io.circe.generic.auto._
case class Role(id: String, name: String)

import org.http4s.dsl._
import org.http4s.circe._
POST(someUri)
  .withBody(Role("someId", "aName"))
```

Right now it complains with:
```could not find implicit value for evidence parameter of type org.http4s.EntityEncoder[Role]```

**Comment by rossabaker** [comment]
We've considered that before.  There are two problems with this:

- What about a `Role` is specific to JSON?  How do we know you don't want to render it as XML or plain text?  In my apps, I write `POST(someUri, role.asJson)`: it's still concise, but makes the choice of JSON rendering explicit.

- If your application is 100% JSON, you are free to declare an implicit method that forwards to `jsonEncoderOf`.  But be careful here: the implicit resolution rules in Scala are complicated, and it's not always clear whether `POST(someUri, "a string")` posts a plain-text string or a quoted JSON string.  I've been surprised once in each direction here, so I stopped using this technique.
