### ISSUE TITLE
CheckPublishable If Statement Incorrect

### ISSUE THREAD

**Issue by ChristopherDavenport** [http4s/http4s#1229]
[Build Example](https://travis-ci.org/http4s/http4s/builds/247745626)

[This If Statement](https://github.com/http4s/http4s/blob/release-0.16.x/bin/setup.sh#L15) isn't picking up the release branch correctly.

I'm sure it's something obvious, but the check is eluding me.

**Comment by bfritz** [comment]
[This](https://travis-ci.org/http4s/http4s/jobs/247745633#L535) is the problem, right?  I think the logic is flawed:
```
 elif [[ $TRAVIS_BRANCH != "master" || $TRAVIS_BRANCH != "release-"* ]]; then
```
Won't that compound expression will always return `true`?

Input   | Expression 1 | Expression 2 | Overall
------- | ------------ | ------------ | -------
`x`     | `true`       | not evaluated | `true`
`master`| `false`      | `true`        | `true`
`release-0.16.x`| `true`      | not evaluated | `true`

Shell scripting isn't one of my strengths, but exiting from a function feels awkward.  Might be better to return `1` or `0` and exit from the caller based on return value.  Like `isPublishableTo "foo" || exit 0`
or:
```
if ! isPublishableTo "foo"; then
    exit 0
fi
```
(Syntax above not tested; I might have botched something.)

Switching to a return value, probably allows for simpler expressions that are easier to reason about.  (Probably just me, but reasoning about `NOT A OR NOT B` makes my brain hurt.)

**Comment by ChristopherDavenport** [comment]
Yup, should probably be 

```bash
elif [[ $TRAVIS_BRANCH == "master" || $TRAVIS_BRANCH == "release-"* ]]; then
     currentElse
else
    currentElif
fi
```
