### ISSUE TITLE
Uri parsing bug with brackets in query param name

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#1240]
> I'm trying to parse `Uri.fromString("http://localhost:8080/index?filter[state]=public")` with no success: `Left(org.http4s.ParseFailure: Invalid URI: Invalid input '[', expected '/', 'EOI', '#', '?' or Pchar (line 1, column 35)`.

Fix should target 0.15.  I ran out of time tonight, but I'll try to fix this tomorrow.

**Comment by rossabaker** [comment]
So, strictly according to RFC 3986, the existing behavior is right.  There is a [nice discussion](https://stackoverflow.com/questions/11490326/is-array-syntax-using-square-brackets-in-url-query-strings-valid).

On the other hand, this usage is:
- common in other web frameworks, specifically dynamic languages
- consistent with `java.net.URI`

I think [Postel's Law](https://en.wikipedia.org/wiki/Jon_Postel#Postel.27s_law) argues for accepting this but rendering it encoded.

**Comment by ChristopherDavenport** [comment]
Fixed By #1242
