### ISSUE TITLE
Audit the HTTP model for cohesion

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#127]
Long ago, we bootstrapped this project in part by importing of the Spray model.  Since then, we have fitfully evolved the model, making it better for our needs, but less cohesive.  We want our 1.0 API to be cohesive and stable.  This will be a ticket solved over multiple pull requests.
## Preferred types:
- `scalaz.\/` over `scala.Either` and `scala.util.Try`.
- `scalaz.NonEmptyList` if at least one element is required.
- `scalaz.concurrent.Task`, over `scala.concurrent.Future`.
- `scala.collection.immutable.*` over `scalaz.IList`, `scalaz.IMap`, etc.
- `scala.Option` over `scalaz.Maybe`.
- `util.CaseInsensitiveString` over `scalaz.CaseInsensitive`.  (The latter takes an implicit, JVM-default Locale.)

Where the Scalaz alternatives are less favored, consider convenience methods.
## Other principles:
- The model shall be immutable.
- Public constructors are total.
  - Literals may be supported via macros.
  - Methods exposed only to support macros are prefixed with the jolly roger character.
- HTTP literals are represented in their standard form, with backticks.
- Implement any relevant Scalaz type classes.
- forall(a) { `A.parse(render(a)) == \/-(a)` }
- Common values are on the companion object of the type.
  - Check the relevant IANA registry for relevant values.

**Comment by ChristopherDavenport** [comment]
Where are we on this issue? Some of this still seems very relevant, and quite a bit scalaz specific which is less important now.

**Comment by rossabaker** [comment]
Yeah, the types section is either obvious or obsolete by this point.

The principles section is still true (except maybe jolly roger), but not particularly actionable.  I just want our API to be predictable in terms of which constructors are total, how I "just get one from a string," etc.  And I want to check for things that were added since RFC2616, which keeps biting us.  (For example, credentials that are just a token.)

I don't know how great this is as a ticket.  The principles might be good for a developer's guide.

**Comment by rossabaker** [comment]
I'm going to close this ticket, but create a long series of specific questions along these lines.

You've all been warned. :smiling_imp:
