### ISSUE TITLE
make org.http4s.util.threads.DefaultPool lazy or a method

### ISSUE THREAD

**Issue by NicolasRouquette** [http4s/http4s#1281]
In 0.17.0-M3, this variable is defined like this:

```scala
  private[http4s] def newDaemonPool(name: String, min: Int = 4, cpuFactor: Double = 3.0, timeout: Boolean = false) = {
    val cpus = Runtime.getRuntime.availableProcessors
    val exec = new ThreadPoolExecutor(
      math.max(min, cpus), math.max(min, (cpus * cpuFactor).ceil.toInt),
      10L, TimeUnit.SECONDS,
      new LinkedBlockingQueue[Runnable],
      threadFactory(i => s"${name}-$i", daemon = true))
    exec.allowCoreThreadTimeOut(timeout)
    exec
  }

  /** Servers and clients shouldn't run on a daemon.  This will go away. */
  private[http4s] val DefaultPool =
    newDaemonPool("http4s-pool")
```

In http4s, it is used as a default method parameter value in several places.
Since it is not lazy, it is initialized regardless of whether it is actually used or not.
When it is not used, an application nonetheless has an extra thread pool configured with the max number of cpus available that does nothing logically useful.

I suggest refactoring this to make the variable lazy so that the default thread pool would be created only if necessary.

**Comment by rossabaker** [comment]
Fixed by #1282
