### ISSUE TITLE
Parameterization of AttributeKeys is problematic

### ISSUE THREAD

**Issue by aeons** [http4s/http4s#1294]
`AttributeKey` only has reference equality. In the current master, this works well as we only use `Task`, so that `AttributeKey[Task[A]]` can be created as a val on an object and reused where needed.

When `Task` is now a generic `F[_]`, we can't save a reference to an `AttributeKey` with a type param using it.

There are three places where `AttributeKey` uses `Task` in its type param.

- In `Message.Keys.TrailerHeaders`. This can be moved to a nested object in `MessageOps` and is accessible from all the same places. However, currently `MessageOps` and a couple of extending traits are universal traits and cannot have nested objects. Is there a reason that these traits are universal? As I understand it, this really only matters when extended by value classes and none of them are in this case.
- In `package object websocket` there's an `AttributeKey` that is used both in the `WS` function in the same object as well as in `WebsocketSupport` in the `blaze` module.
- In `object PushSupport` there's also an `AttributeKey` that is only used in one place to `put` some collected resources. I'm not sure where it could be referenced to as well.

I don't really have a good idea on how to fix the last two issues.

**Comment by aeons** [comment]
So now I realised that I changed the `Effect*Syntax` classes from value classes to regular classes, specifically to get around having a type class constraint on `RequestOps.withPathInfo`.

I am, again, not sure how to handle this. I would prefer to keep the syntax classes as value classes and the ops traits as universal traits, but that invalidates my "solution" to point 1 above.

**Comment by rossabaker** [comment]
Can the keys be stuffed into a private companion object, with accessors on the ops traits?  Then you can (ugh) cast to the effect type, which the ops trait has?

**Comment by aeons** [comment]
That could definitely be an option. Will take a look at it.

Do you have an idea on how to solve the issue of having an overload to a trait requiring a type class?

**Comment by aeons** [comment]
Solved with casting in https://github.com/http4s/http4s/commit/9218e741b81b815f3d27daf02f5dc84c24d91299
