### ISSUE TITLE
Provide Content-Length header when serving static files from URL

### ISSUE THREAD

**Issue by ZizhengTai** [http4s/http4s#1295]
Currently, `StaticFile.fromURL` doesn't provide a `Content-Length` header. It uses `Transfer-Encoding: chunked` instead. We can easily get the content length of a resource with `url.openConnection.getContentLengthLong`.

**Comment by rossabaker** [comment]
This requires a little bit of thought because we don't open the URL until the body is rendered, but we need the connection to get the content length.  We might need to lift this into a Task.  It's also possible that an `EntityEncoder[URL]` shakes down out of this.

**Comment by ZizhengTai** [comment]
@rossabaker I think we already always open the URL to get the last modified time?

**Comment by rossabaker** [comment]
Hmm.  That's true, and that belongs in `Task`, too.  We're opening a connection and leaving it dangling until the body is run.

**Comment by rossabaker** [comment]
I sat down to do this for 0.16, but lifting things into Task is going to cause massive merge conflicts.  Going to retarget 0.17.
