### ISSUE TITLE
`org.http4s.headers.Set-Cookie` should be allowed to return more than one header

### ISSUE THREAD

**Issue by megri** [http4s/http4s#1299]
A server is allowed to return multiple Set-Cookie headers, but is not allowed to fold them into a single field: 
> https://tools.ietf.org/html/rfc6265#section-3
> Origin servers SHOULD NOT fold multiple Set-Cookie header fields into
>   a single header field.  The usual mechanism for folding HTTP headers
> fields (i.e., as defined in [RFC2616]) might change the semantics of
>   the Set-Cookie header field because the %x2C (",") character is used
>   by Set-Cookie in a way that conflicts with such folding.

`Set-Cookie` extends `HeaderKey.Singleton` which yields an optional result.

`HeaderKey.Recurring` signals that recurring headers of the same kind are allowed to be folded into one header-row so it is not usable for Set-Cookie. There needs to be a third way to conform to the spec:

> https://tools.ietf.org/html/rfc6265#section-3.1
> As shown in the next example, the server can store multiple cookies
>   at the user agent.  For example, the server can store a session
>   identifier as well as the user's preferred language by returning two
>   Set-Cookie header fields.  Notice that the server uses the Secure and
>   HttpOnly attributes to provide additional security protections for
>   the more sensitive session identifier (see Section 4.1.2.)
> 
> == Server -> User Agent ==
> 
> Set-Cookie: SID=31d4d96e407aad42; Path=/; Secure; HttpOnly
> Set-Cookie: lang=en-US; Path=/; Domain=example.com

Related issue: #1143

**Comment by rossabaker** [comment]
My band-aid idea here is to define `from` on `Set-Cookie` to return a `List[Set-Cookie]`.  And I guess `unapply` would return a `Option[NonEmptyList[Set-Cookie]]`?
