### ISSUE TITLE
GZip client side middleware

### ISSUE THREAD

**Issue by agourlay** [http4s/http4s#1327]
Currently the GZip middleware is only for server side.

The client could either reuse the server side middleware or just the compression logic added to a client side middleware.

Discussed on Gitter https://gitter.im/http4s/http4s?at=599aef13c101bc4e3a3f7b71

**Comment by agourlay** [comment]
FYI I am currently working on this

**Comment by rossabaker** [comment]
Which version are you targeting?

- If it's 0.18, cool.
- If it's 0.16 or 0.17 and you're only adding signatures, cool.
- If it's 0.16 or 0.17 and it needs to change any signatures, let's plan, because I'm about to cut RCs.

**Comment by agourlay** [comment]
I am gonna go for 0.18 to get complete freedom :bowtie:

**Comment by rossabaker** [comment]
#1373 was accidentally closed.  That's a good starting point if anyone wants to pick this up and finish it.

**Comment by agourlay** [comment]
fixed by https://github.com/http4s/http4s/pull/2673
