### ISSUE TITLE
Don't depend on Typelevel scala library

### ISSUE THREAD

**Issue by nigredo-tori** [http4s/http4s#1330]
org.http4s packages depend on `org.typelevel.scala-library`. SBT fails to reconcile it with `org.scala-lang.scala-library`, leading to two conflicting library dependencies, and non-deterministic problems like https://github.com/tpolecat/doobie/issues/568 . This an SBT issue first, but it would be better to work around it at http4s end too.

Gitter discussion: https://gitter.im/sbt/sbt?at=599b9f2b9acddb2407b69a8b

**Comment by rossabaker** [comment]
Problems related to the Typelevel Scala dependency leaking have affected a few people.  We need a solution for this for 0.16.0.

Related discussion ongoing at https://github.com/typelevel/scala/issues/166.

My first thought is to postprocess the POM as a workaround.

My second thought is to revert to Lightbend Scala.  We're not using too many features exclusive to LBS.  I would prefer to avoid this, as it's nice that we can help test the Typelevel compiler.  But this would be better than passing pain on to our users.

**Comment by rossabaker** [comment]
Fixed by #1337.
