### ISSUE TITLE
Logger Logs application/json as Hex

### ISSUE THREAD

**Issue by ChristopherDavenport** [http4s/http4s#1355]
Despite being text, is considered a binary format. So is logging as HEX, this should instead log as text

**Comment by bpholt** [comment]
FYI [here's where `application/json`](https://github.com/http4s/http4s/blob/13b721ced3c85d741bd0877b4cdef9688d058516/core/src/main/scala/org/http4s/MediaType.scala#L206) is marked as binary.

The comment there (and on [`application/hal+json`](https://github.com/http4s/http4s/blob/13b721ced3c85d741bd0877b4cdef9688d058516/core/src/main/scala/org/http4s/MediaType.scala#L203) and [`application/problem+json`](https://github.com/http4s/http4s/blob/13b721ced3c85d741bd0877b4cdef9688d058516/core/src/main/scala/org/http4s/MediaType.scala#L213) is:
> we treat JSON as binary, since it's encoding is not variable but defined by RFC4627

**Comment by ChristopherDavenport** [comment]
Fixed by #1362 on `release-0.17.x` and will be fixed in `master` on roll-forward.
