### ISSUE TITLE
Top menu on http4s website seems out of sync when in version tutorials

### ISSUE THREAD

**Issue by keirlawson** [http4s/http4s#1376]
Going in to the 0.15 tutorial for example makes the "coding standards" link disappear, and the documentation menu reports versions 0.15, 0.16 and 0.16-cats

**Comment by rossabaker** [comment]
I don't think the 0.15 docs have been republished since some of those emerged.  This is the problem where changes to master publish the common area of the site, but the entirety of the site isn't regenerated.

**Comment by rossabaker** [comment]
This is fixed now, and will be rerendered by #1397.
