### ISSUE TITLE
TimeoutSpec failures

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#1383]
Travis is getting flaky again. 😩 

[TimeoutSpec failure](https://travis-ci.org/http4s/http4s/jobs/274297559#L2348)

**Comment by rossabaker** [comment]
https://travis-ci.org/http4s/http4s/jobs/274772426 💩

**Comment by aeons** [comment]
Is this because the timeout is set to 1 nanosecond? Maybe set it to 10 mills and see if that works?

**Comment by rossabaker** [comment]
https://travis-ci.org/http4s/http4s/jobs/275307583

**Comment by rossabaker** [comment]
https://travis-ci.org/http4s/http4s/builds/275577682 💩
