### ISSUE TITLE
Reconsider lazy vals in Request

### ISSUE THREAD

**Issue by ceedubs** [http4s/http4s#1389]
Currently `Request` stores the results of some attributes lookups in lazy vals. It's worth reconsidering whether the potential performance benefit in the case in which these values are referenced multiple times is worth the extra memory overhead of using a lazy val instead of a `def`.

See [this gitter conversation](https://gitter.im/http4s/http4s?at=59b86311177fb9fe7eb2a041).

**Comment by rossabaker** [comment]
I don't want to add another dependency, but a nice overview of approaches is at [latr](https://github.com/runarorama/latr).  We have [artisanally handcrafted](https://github.com/http4s/http4s/blob/1bb031fd3a55ec3dce08182c1d02af41aa1d3cb4/core/src/main/scala/org/http4s/Header.scala#L89-L95) a few like `@lazify`.  If it's expensive, but not harmful, to calculate it twice, this is a good approach.

If it's inexpensive, or lazified elsewhere, like calculations based on parsed headers, then a simple `def` is most likely correct.

**Comment by rossabaker** [comment]
The only one left is `(scriptName, pathInfo)`, which is important and repeatedly referenced in routing.
