### ISSUE TITLE
`Http4sMatchers` isn't parameterised on Effect type

### ISSUE THREAD

**Issue by agustafson** [http4s/http4s#1430]
I've upgraded to 0.18.0-M1 but `Http4sMatchers` isn't parametrised on the effect type, so matchers like `haveStatus` don't work if I'm using something other than `cats.effect.IO` (eg: `cats.Id`)

**Comment by agustafson** [comment]
Happy to put in a PR if that will help

**Comment by aeons** [comment]
A PR would be cool. All tests are currently using `IO`, so I guess we just haven't hit that use case.

**Comment by calvinbrown085** [comment]
I can work on this one @agustafson

**Comment by calvinbrown085** [comment]
If someone else wants to take a crack at this feel free, I'm not sure I have enough cats, and typeclass experience for this one.

**Comment by calvinbrown085** [comment]
I might try taking another shot at this one

**Comment by diesalbla** [comment]
I might try solving this one. @calvinbrown085 Did you get a chance to make any progress on this one?

**Comment by calvinbrown085** [comment]
I haven't, I apologize. Feel free to take it!
