### ISSUE TITLE
Tomcat example no longer starts up

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#1453]
We get a null back calling `getClass().getResource("/")`.  This used to set the docbase for Tomcat to the root of the classpath, which is really kind of a hazy concept anyway.

Maybe this needs to be parameterized?  And would should a default be?  And why is it just now failing?  Is it sbt-1.0?

**Comment by lukestephenson** [comment]
I've just experienced this issue as well.  Works fine if I launch from intellij, but from the command line with an `sbt run` it fails with the NPE.

**Comment by rossabaker** [comment]
Is this on master or a released version?

**Comment by lukestephenson** [comment]
I don't have your fix on master. Was using 0.18.0-M5.
