### ISSUE TITLE
Remove reflection from HttpHeaderParser

### ISSUE THREAD

**Issue by cquiroz** [http4s/http4s#1484]
`HttpHeaderParser` uses reflection to find the list of methods that can parse headers. This could be brittle and reflection isn't supported on all platforms, e.g. scala.js

Given that this is not a minor change I'd rather discuss this briefly

`HttpHeaderParser` uses reflection and subclassing. I'd rather remove reflection and compose parser implementations. That would require traits like `SimpleHeaders`, `AcceptHeader`, etc become `object` that implement a trait like

```scala
trait HeaderParserProvider {
   def parsers: NonEmptyList[HeaderParser]
}

object AcceptHeader extends HeaderParserProvider {
   def parser = NonEmptyList(ACCEPT)
   ...
}
```

A big drawback is that all that is done automatically with reflection would have to be done manually which is error prone. Perhaps instead we could mark methods and use a macro to generate the provider but I haven't thought much about it

Any other ideas?

**Comment by rossabaker** [comment]
Why a list of parsers?

We introduced the `HttpCodec` type class, which I think every modeled header could implement.  That defines a `def parse(s: String): ParseResult[A]`.  Could we use those instances as we provide them?

**Comment by cquiroz** [comment]
`HttpHeaderParser` maintains a map of `String -> HeaderParser` presumably for fast access to the parser implementation. `parsers` should actually be a `map`. But regardless, we need a set of available parser and the question is how to populate that. Right now it is with reflection but I'm trying to figure out an alternative

`HttpCodec` could probably be a good idea for the Header parsers

**Comment by rossabaker** [comment]
I think `CaseInsensitiveString => (String => ParseResult[Header])` gets the job done, where the first argument is the key and the function is the parsing of the value.  `HttpCodec[A <: Header].parse _` is probably shaped like the second function, though I'm not sure it adds any concision to building that map.

**Comment by cquiroz** [comment]
I'm revisiting this and an extra issue is the presence of the `addParser/dropParser` methods that mutate the list of parser. Is this something we want to keep? Is this the way to add custom parsers?

**Comment by rossabaker** [comment]
That is the way to add custom parsers, and I think it's a bad idea.  It requires registering all custom parsers before serving any requests, which I guess is not unreasonable, but it's a global dependency on a mutable structure, which is not very http4s-like.

#1143 discusses some other ideas.

**Comment by m-sp** [comment]
can this also be closed? I think all the reflection is gone with https://github.com/http4s/http4s/issues/4297

**Comment by rossabaker** [comment]
Yes, has been for a long time.  And now the parser itself is gone.
