### ISSUE TITLE
0.18 Migration Guide

### ISSUE THREAD

**Issue by m4dc4p** [http4s/http4s#1501]
I migrated a 0.16 service to 0.18-M4 recently and took notes on my experience. Here is what I found - please feel free to comment, edit and place this somewhere more appropriate.

-----------------------------

This document details changes necessary to migrate services from
http4s 0.16 (and earlier) versions to 0.18. Between those versions,
http4s dropped support for scalaz and scalaz.concurrent and migrated
to cats/cats-effect.

This isn't exhaustive but details the changes I needed to make and
challenges I faced.

Note that this upgrade requires Scala 2.12 - it is not 2.11 compatible.

build.sbt
=====

Remove any scalaz dependencies.

Add the "-Ypartial-unification" flag to scalac options:

```
scalacOptions ++= Seq(
  "-Ypartial-unification",
  ...
)
```

Scalaz imports
=====

In general, `scalaz.concurrent.Task` is always replaced with
`cats.effect._`. Other `scalaz` imports should be replaced with the
following block (I never found the need to do any finer-grained imports):

```
import cats._
import cats.data._
import cats.implicits._
```

`Task`
====

Replace all instances of `Task` with `IO`. `Task.now`/`Task.delay` becomes
`IO.pure` (if the argument is already an `IO` type use `IO.suspend`). 

`Task.fail` becomes `IO.raiseError`. 

Some `Task` instance methods replacements:

* `x.unsafePerformSync` - `x.unsafeRunSync`.
* `x.unsafePerformSyncAttempt` - `Either.catchNonFatal(x.unsafeRunSync)`.

Finally, `gatherUnordered` isn't implemented directly by `IO` and I 
didn't think it added much value, so I just replaced it with a direct
for-comprehension. For example:

```
for {
  _ <- Task.gatherUnordered(taskA, taskB)
  ...
}
```

became:

```
for {
  _ <- taskA
  _ <- taskB 
  ...
}
```

`timed` also went away (in fact, it never behaved the way I thought).

For error handling, replace `handleWith` with `handleErrorWith`.

Scalaz Types & Methods
====

With scalaz gone, the `\/` (disjunction) type and its constructors no
longer apply.

Migrate `\/` to `scala.util.Either`; `\/-` becomes `Right` and `-\/`
becomes `Left`. `\/.fromTryCatchNonFatal` becomes `Either.catchNonFatal`.

The `EitherT` type exists in cats, but the methods have different names:

* `x.toRightDisjunction(a)` (where `x` has type `Option`) - `x.toRightIor(a).toEither`.
* `x.right` - `EitherT.pure(x)`
* `x.left` - `EitherT.left(x)`

The `sequenceU` method becomes `sequence`.

The `ValidationNel` type becomes `ValidatedNel`. `Failure` and `Success`
become `Validated.Invalid` and `Validated.Valid`, respectively.

The `point` method becomes `pure`. (Defined in the `Applicative` typeclass.)

Effect Parameter
====

http4s adds an effect parameter (`F`) to nearly every class. I fixed
all effects to `IO`, instead of parameterizing:

* `Response` - `Response[IO]`
* `Request` - `Request[IO]`
* `HttpService` - `HttpService[IO]`
* `AuthedService[X]` - `AuthedService[IO, X]`
* `EntityEncoder[A]`, `EntityDecoder[A]` - `EntityEncoder[IO, A]`, `EntityDecoder[IO, A]`

Note that the `IO` type should alse be added whenever using the
companion object's `apply` method for the above types.

The `jsonOf`, `jsonEncoderOf` methods also have an effect, which I
fixed to `IO`:

* jsonOf[A], jsonEncoderOf[A] - jsonOf[IO, A], jsonEncoderOf[IO, A]

http4s imports
====

In all cases, `import org.http4s.dsl._` becomes 
`import org.http4s.dsl.io._`. In some cases (where operators like `||` were
being used to compose services), you need to add the statement `import
org.http4s.implicits._`.

Composing Services
====

The `||` operator becomes `<+>`. Usually this works without change,
but the compiler can't automaticlaly convert `AuthedService[IO, U]` so
you need to add an explicit type annotation in that case:

```
type OptionTIO[A] = OptionT[IO, A]
...
def x : AuthedService[IO, U] = ...
(x : Kleisli[OptionTIO, AuthedRequest[IO, U], Response[IO]]) <+> ....
``` 

OAuthBearerToken/BasicCredentials
====

The `Credentials.Token` class replaces `OAuthBearerToken`. `Token`
requires an additional `AuthScheme` parameter, so
`OAuthBearerToken(token)` becomes
`Credentials.Token(AuthScheme.Bearer, token`.

The extractor `BasicCredentials(username, password)` projects a
`BasicCredentials` value now, which has a `username` and `password`
property. For example:

```
  case BasicCredentials(u, p) => ...
```

becomes

```
  case BasicCredentials(creds) => { 
    val u = creds.username
    val p = creds.password
    ...
  }

```

`Service.lift` and `HttpService.lift`
====

These two methods are replaced with `Kleisli`:

* `Service.lift({req => ...})` - `Kleisli { req => ... }`
* `HttpService.lift({ req => ... })` - `Kleisli { req => ... }`

`MaybeResponse`/`Pass`/`orNotFound`
====

http4s 0.18 implements "fall through" behavior using the `OptionT`
transformer, rather than the previous `MaybeResponse` and `Pass`
approach used earlier.

That means the `orNotFound` method goes away. Replace it like so:

* `service.apply(req).unsafeRunSync.orNotFound` -
  `service.apply(req).getOrElseF(NotFound()).unsafeRunSync`

The `apply` method on `HttpService` returns an `OptionT` where it
previously returned a `MaybeResponse`. Use the `value` method to get
to the underlying `IO` value from the `OptionT` instance:

* `service.apply(req)` - `service.apply(req).value`

For that reason, certain expressions need to `map` on the `OptionT`
value where they previously accessed the response directly. For
example:

* `Ok(created).putHeaders(Location(location))` -
  `Ok(created).map(_.putHeaders(Location(location)))`

**Comment by rossabaker** [comment]
Thanks!  There is good material here, but we need to think about presentation.  The [changelog](https://github.com/http4s/http4s/blob/master/website/src/hugo/content/changelog.md) has been our traditional "migration notes," and its chronological sorting is intended to help people migrate from an arbitrary version.  But this is more thorough.  Should we integrate these notes into the changelog?  Create a dedicated migration document?  (But then it's a bit weird that we don't provide one from 0.17.)

**Comment by ChristopherDavenport** [comment]
We could give it a page on the website. The upgrade is a larger piece and will be critical for the upgrade adoption path. We could create an issue to create a similar if a bit less in-depth guide for 0.17, so it can experience less middle-child syndrome.

**Comment by rossabaker** [comment]
Okay, that makes sense to me.  I think in general a page that's X-1 to X is good, but 0.16->0.18 as a special case seems legit.

@m4dc4p, do you want to add this as a migration.md in the docs project?  Or would you like one of us to do that?

**Comment by m4dc4p** [comment]
Feel free to do it, and make any necessary edits. Thank you

**Comment by aeons** [comment]
I think there should be a section about the cats effect type classes as well. Ie you don’t have to replace Task with IO, you can switch to `F[_]: Effect` instead.

**Comment by SystemFw** [comment]
> Task.now/Task.delay becomes IO.pure

`Task.now` is not the same as `Task.delay`, and only the first translated to `pure`. `Task.delay` becomes `IO(...` (`IO.apply`)

**Comment by rossabaker** [comment]
We failed to get these onto the site.  Anyone want to get this into the tuts?

**Comment by ChristopherDavenport** [comment]
Seems like this one rotted out of existence.
