### ISSUE TITLE
Update Deprecation Warning on Service Composition with ||

### ISSUE THREAD

**Issue by ChristopherDavenport** [http4s/http4s#1502]
[Location](https://github.com/http4s/http4s/blob/0d1ebe8cfbe439703dd189dd0af663d8d9bbed16/server/src/main/scala/org/http4s/server/syntax/package.scala)

 ```
@deprecated("Import `cats.syntax.semigroup._` and use `service1 |+| service2` instead", "0.16")
```
is now outdated.

Should either be removed or replaced with something like
```
"Import `cats.implicits._` and `org.http4s.implicits._` and use `service1 <+> service2` instead. Ensure partial unification is enabled.", "0.16"
```

Open to discussion.

**Comment by rossabaker** [comment]
I think it doesn't hurt to keep it deprecated.  The message looks good, though I might use the actual flag name. `-Ypartial-unification`, I think it is.

**Comment by calvinbrown085** [comment]
@ChristopherDavenport I can pick this one up.

**Comment by calvinbrown085** [comment]
@ChristopherDavenport Can this issue be closed? Not sure what the requirements for a closed issue are.

**Comment by ChristopherDavenport** [comment]
Sorry yes. Thanks again!
