### ISSUE TITLE
Http4s Testing Documentation

### ISSUE THREAD

**Issue by ChristopherDavenport** [http4s/http4s#1504]
In our documentation we are lacking examples and demonstration of using http4s-testing to create unit tests for our services. We have some implementations in http4s.g8, but we should have more concrete examples that show a consensus that people can work from in the Website documentation.

**Comment by calvinbrown085** [comment]
@ChristopherDavenport Could you point me to http4s-testing when you have a chance? I can't seem to find it.

**Comment by rossabaker** [comment]
It's the [testing subproject](https://github.com/http4s/http4s/tree/master/testing/src).  It gets published as:

```
"org.http4s" %% "http4s-testing" % Http4sVersion
```

We have [Http4sMatchers](https://github.com/http4s/http4s/blob/bc2b8f1e66943a4b7812a8fe2d09a04bd6f6c6d8/testing/src/main/scala/org/http4s/testing/Http4sMatchers.scala), which help with Specs2.  If you search our tests for the methods therein, you'll find examples of their use.  (Aside: it's not great that our testing module has a dependency on specs2.  I think we should consider whether that's the right home.)

Other interesting things in there are the [ArbitraryInstances](https://github.com/http4s/http4s/blob/bc2b8f1e66943a4b7812a8fe2d09a04bd6f6c6d8/testing/src/main/scala/org/http4s/testing/ArbitraryInstances.scala), which go nicely with Scalacheck.  We have also started adding some [laws](https://github.com/http4s/http4s/blob/master/testing/src/main/scala/org/http4s/testing/HttpCodecTests.scala) that go well with discipline.  I suspect these are more useful inside http4s than outside, though I can imagine them being used in more advanced testing scenarios.

**Comment by calvinbrown085** [comment]
@rossabaker Awesome, I will play around with that! Thank you!

**Comment by calvinbrown085** [comment]
I've been looking around at this a little bit, one thing i'm unclear on is where these docs are supposed to live. In the [docs/ folder](https://github.com/http4s/http4s/tree/master/docs/src/main/tut)?

**Comment by ChristopherDavenport** [comment]
Definitely seems good enough to close out this issue. If we want we can revisit arbitraries and law testing at some point in the future.
