### ISSUE TITLE
Mistyped 0.18 Entity Handling Doc

### ISSUE THREAD

**Issue by ChristopherDavenport** [http4s/http4s#1505]
http://http4s.org/v0.18/entity/

`Taking a look at Request[F] and Response[F], both have a body of type EntityBody[F], which is simply an alias to Stream[F, ByteVector]. To understand Stream, take a look at the streams-tutorial.`

The alias is now `Stream[F, Byte]`. 

The Stream Tutorial is a 2015 link about scalaz-streaming in 2015 so we should consider whether this should be updated to something more applicable to fs2 0.10.

**Comment by ChristopherDavenport** [comment]
This presentation link may be more accessible as well rather than the older one.

https://youtu.be/cahvyadYfX8

**Comment by calvinbrown085** [comment]
I plan on picking this issue up.
