### ISSUE TITLE
Cats 1.0.0-RC1 Release

### ISSUE THREAD

**Issue by ChristopherDavenport** [http4s/http4s#1507]
We should get a release out when this is available for the Cats Release Candidate dealing with any errors so that we are proactive.

**Comment by rossabaker** [comment]
I tried to begin sorting out the damage tonight, but I couldn't manage to force the version to RC1.  I added this to libraryDependencies in core.sbt and it was ineffective:

```scala
      "org.typelevel" %% "cats-core" % "1.0.0-RC1" force, // temporary
```

What stupid thing am I doing?
