### ISSUE TITLE
Remove Http4s NonEmpty List

### ISSUE THREAD

**Issue by ChristopherDavenport** [http4s/http4s#1510]

**Comment by rossabaker** [comment]
Do we still have one, or just syntax for it?  I think getting that syntax moved onto cats' NonEmptyList would be great.

**Comment by aeons** [comment]
I moved it into org.http4s.syntax in the cats PR and removed one of the methods, since it already exists on NEL.

The rest are still used in a couple of places, but getting them into cats would be nice I guess.

**Comment by jmcardon** [comment]
Where are we on this?

I think just the syntax is ok to have. Can we close?

**Comment by rossabaker** [comment]
Those syntax methods are now in cats-1.1.  And I don't like them being ours, because they're not enhancing our types.  I don't think we can deprecate this without clashing with the cats versions.  I think we should remove this entirely.

**Comment by felixmulder** [comment]
Can this be closed? :)

**Comment by ChristopherDavenport** [comment]
These methods are all deprecated now. :+1:
