### ISSUE TITLE
Missing ETag for Static files

### ISSUE THREAD

**Issue by pvillega** [http4s/http4s#1511]
[Documentation](http://http4s.org/v0.17/static/) for `Static files` says:

> Http4s provides a few helpers to handle ETags for you, they’re located in StaticFile.

Unfortunately the implementation of [StaticFile](https://github.com/http4s/http4s/blob/ecaa1155307fc16616315237ace7280455291b62/core/src/main/scala/org/http4s/StaticFile.scala) is not using `ETag` but `Last-Modified` headers. The documented functionality is missing.

**Comment by rossabaker** [comment]
Going ahead and calling this one a bug since the docs promise it.

There are different strategies for creating ETags, so I suppose the first question would be how they should be generated.  I imagine some sort of parameterized strategy would be desired, because it's not one-size-fits-all.

**Comment by jmcardon** [comment]
#1652 closed this, no?

**Comment by ChristopherDavenport** [comment]
Closed By #1652
