### ISSUE TITLE
Async-http-client Intermittent Failure

### ISSUE THREAD

**Issue by ChristopherDavenport** [http4s/http4s#1521]
This issue has cropped up in several PR's possibly related to upgrade of fs2-reactive-streams.

**Comment by rossabaker** [comment]
[Here is an example](https://ci.appveyor.com/project/ChristopherDavenport/http4s-m0hqu/build/1.0.366/job/oeovirld3vpdajaa#L3282).  It's not limited to Appveyor.  I saw it once in Travis, but restarted that build because someone wanted a snapshot.

**Comment by rossabaker** [comment]
I don't think I've seen this since #1668.  Closing.
