### ISSUE TITLE
Refactor Client Creation

### ISSUE THREAD

**Issue by ChristopherDavenport** [http4s/http4s#1522]
Client by creation is not an effect, but as soon as anything is run then it needs to be shutdown, so it is masking mutable internal state.

As a result Client creation should be within an Effect Type. Such that you can only create a client within an effect. This allows for safer use at the call site. 

`PooledHttpClient[F]() : F[Client]` Which allows `Stream.bracket(client)(Stream.emit(_), _.shutdown)` to be a stream implementation we could also provide.

While we are beating on client. It is probably time for the death of `SimpleHttpClient`

**Comment by aeons** [comment]
:+1:
That is exactly the code I use as well.
