### ISSUE TITLE
Docs need a little cleanup

### ISSUE THREAD

**Issue by jmcardon** [http4s/http4s#1527]
From I can see from a quick scan:

* [The docs on Middleware](http://http4s.org/v0.18/middleware/) reference `Service` everywhere, but `Service` is deprecated. 

* The signature for `AuthMiddleware` is incorrect as well now, as `Middleware` take 5 type parameters, including an effect type, and F is higher kinded.

* No mention of `HttpService[F]` being total, hence the need for `orNotFound` nowadays.

* A lot of references to a service returning `F[Response[F]]` instead of `OptionT` which is currently the case.

**Comment by rossabaker** [comment]
This is of course going to change even more with #1693.

**Comment by armanbilge** [comment]
Not sure how much of this is relevant anymore. Anyway we have plenty of docs issues on today's problems.
