### ISSUE TITLE
Client timeout from time of request

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#1532]
We don't currently have a way to enforce a timeout from when a request is submitted to a client to the response.  Time spent in the wait queue isn't considered.  If a request gets caught in a wait queue, it may be irrelevant by the time it is served.

Some users try to work around this with `unsafeTimed`, but this prevents finalizers from running.

We could:
- Add that timeout to the client config
- Add a per-request timeout to the client API.  I'm not sure how to compose this with the other operations to avoid doubling the API.
- Add methods that additionally return an `F[Unit]` to cancel the request.  More general than a timeout.  Also potentially doubles the API.  And maybe triples it if we add convenience for the timeout case.

We should be able to support this.  I just haven't imagined a good API for it yet.

/cc @vilu

**Comment by eklavya** [comment]
@rossabaker can it be closed or is there something more to do here?

**Comment by rossabaker** [comment]
I think there is more to do now that we can cancel.  There is great opportunity here for the connection pool implementation.  But I think the original spirit of this is fixed.
