### ISSUE TITLE
Warn about making a request in fetch

### ISSUE THREAD

**Issue by eklavya** [http4s/http4s#1553]
Perhaps we should warn against making another http request in the callback in fetch. This would prevent people from getting deadlocked since fetch need to hold onto the connection until the callback returns.

**Comment by rossabaker** [comment]
Note that `fetch` is gone now, though there are similar ways to trip up.

**Comment by danicheg** [comment]
`fetch` is deprecated in the `0.23` series and is gone entirely in the `1.0` series. So I close this.
