### ISSUE TITLE
Streaming of very large documents is (relatively) slow

### ISSUE THREAD

**Issue by lukestephenson** [http4s/http4s#1555]
I've created a service using http4s which streams data back from a database.  I love the API and it feels really elegant.  Unfortunately though performance isn't as good as what I hoped for.

To rule out the database and other things, I've stripped the problem back to just serving a 2GB file from disk using:
```
   case req@GET -> Root / "file" =>
      val file = new File("large-file.txt")    
      StaticFile.fromFile(new , Some(req)).getOrElseF(NotFound())
```

When this file is being served by http4s, I've observed (jvisualvm) a significant spike in CPU usage.  I wasn't expecting this because it's largely an IO activity.

On my macbook pro, it takes 17 seconds to serve the file.  If it helps at all, jvisualvm sampler snapshot looks like:
![image](https://user-images.githubusercontent.com/395523/32813064-62c6e7c6-c9fc-11e7-9793-f92b7d0d5be6.png)

As a comparison, I've created a basic tomcat servlet which serves the same file and that takes 3 seconds.  The rough code for that is:
```
package servlet;

import org.apache.commons.io.IOUtils;

import javax.servlet.ServletException;
import javax.servlet.ServletOutputStream;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;

@WebServlet(
        name = "HelloServlet",
        urlPatterns = {"/"}
    )
public class HelloServlet extends HttpServlet {

    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp)
            throws ServletException, IOException {
        ServletOutputStream out = resp.getOutputStream();
        File file = new File("large-file.txt");

        IOUtils.copyLarge(new FileInputStream(file), out);
        out.flush();
        out.close();
    }

}
```

While tomcat is serving that file CPU usage jumps, but not to the same extent.

Curious to hear thoughts on this.   Am I making an unfair comparison between http4s / tomcat?  Would people expect serving a large file to be so CPU intensive?

Thanks

**Comment by rossabaker** [comment]
There will be a more overhead in fs2 than raw IO streams, and we haven't spent a lot of time tuning static file handling, but I would expect to be in the same ballpark.

My first thought was chunk size, but we're sending bigger chunks (10kb) than commons-io (4kb).

commons-io can recycle the same buffer, whereas fs2 makes copies of the bytes.  Recycling is dangerous if we don't know how the stream will be consumed, but clearly suboptimal for this use case.

We might be able to send a response attribute back as a hint to the backend to ignore the stream and go lower level.  But this would be bad if middlewares wrap the body and change it without clearing the attribute.

🤔

**Comment by rossabaker** [comment]
fs2 has an [unsafe consumer for InputStreams](https://github.com/functional-streams-for-scala/fs2/blob/9acd57f2829129e0c112eab84f05e32a57928c73/io/src/main/scala/fs2/io/io.scala#L63).  It should be possible to write an unsafe version for serving files, with the same caveats.

I think this is something we should consider offering to fs2, and then wrapping with the HTTP-specific bits.

**Comment by lukestephenson** [comment]
My use case isn't static file handling, it's just streaming large results from the database.  For the purposes of creating a simpler issue to reproduce though I narrowed it down to serving a static file.

I was planning on using gzip middleware, but if having to work with the raw output stream that's simple enough.

**Comment by rossabaker** [comment]
Ah, sorry, I started thinking about the problem and then forgot the first sentence I read.

How are you turning the result set into a stream?  Are you using doobie?  Maybe we can optimize that process a bit.

**Comment by jmcardon** [comment]
@lukestephenson instead of `StaticFile`, assuming it's a post request, do you think you could try with [fs2](https://github.com/http4s/http4s/blob/90137bc7ed6bea393e779f1318160c004072ef7a/core/src/main/scala/org/http4s/StaticFile.scala) using `writeAll` or `writeAllAsync`?

Also what version are you running?

**Comment by lukestephenson** [comment]
@rossabaker I'm using slick to access the database which returns a `org.reactivestreams.Publisher`.  This is then converted into an fs2 Stream using https://github.com/zainab-ali/fs2-reactive-streams.  That said, the performance issues appeared to be with writing the response, not the DB access.

@jmcardon The request is a GET.  I'll see if I can make use of fs2 methods to improve performance, but to be honest I'm still struggling to understand fs2.

**Comment by lukestephenson** [comment]
@jmcardon I'm using version `0.18.0-M5`

**Comment by lukestephenson** [comment]
Tried with both `readAll` and `readAllAsync` as below.
```
val DefaultBufferSize = 10240

    case GET -> Root / "file2" =>
      val file = new File(s"bigfile.txt")
      val responseBody: fs2.Stream[IO, Byte] = fs2.io.file.readAll[IO](file.toPath, DefaultBufferSize)

      IO(Response[IO](body = responseBody))
```

With `readAll` I saw the same performance as http4s `StaticFile`.
`readAllAsync` was much slower (50 seconds total).

Using `fs2.io.unsafeReadInputStreamAsync` or `fs2.io.unsafeReadInputStream` were both slower than `fs2.io.file.readAll` for me (roughly 35 seconds total).

**Comment by lukestephenson** [comment]
Perhaps this issue should be closed on http4s and opened on fs2.  I've simplified my test down to just fs2 code to copy a file from one location to another and it's basically the same speed.

**Comment by rossabaker** [comment]
:+1: Sounds like you've isolated that well. If it improves there, it'll help here.
