### ISSUE TITLE
[Json] Support library specific typeclass

### ISSUE THREAD

**Issue by julien-truffaut** [http4s/http4s#156]
Most Json library propose typeclasses to encode and decode json. It would be nice to provide methods to create `EntityEncoder` and `EntityEncoder` from them. For example:

```scala
  def jsonEntityDecoder[A: argonaut.DecodeJson]: EntityDecoder[A] 
```

**Comment by rossabaker** [comment]
@julien-truffaut, do you have one of these laying around, or should I bang it out?

**Comment by julien-truffaut** [comment]
@rossabaker I implemented it quickly at my job for argonaut but I don't have the time to attack this ticket. You or anyone else can start, I am happy to review it though

**Comment by rossabaker** [comment]
Any json4s experts in the house who know how to do this without reflection?

**Comment by rossabaker** [comment]
I guess this is json4s' Reader and Writer?

I'm first working on this for Argonaut.

**Comment by rossabaker** [comment]
Reopening because I'm going to do similar for json4s.
