### ISSUE TITLE
Link Giter8 template in the website (http4s.org)

### ISSUE THREAD

**Issue by gvolpe** [http4s/http4s#1562]
As pointed out in the Gitter channel, it would be good to link in the website the Giter8 template I created for the Typelevel stack (Http4s / Doobie / Circe / Cats Effect / Fs2):  https://github.com/gvolpe/typelevel-stack.g8

What it makes more sense to me is to add it to the `Further Reading` section but I'm not completely sure. Suggestions?

PS: In the meantime I forked the project to start building (trying) it locally.

**Comment by gvolpe** [comment]
Updating here with the current two suggestions:

- Introducing `Giter8 templates` section in the [Further reading page](http://http4s.org/further-reading/) -> my original thought
- Introducing `Templates` section in the [Adopters page](http://http4s.org/adopters/) -> by @ChristopherDavenport

I'm okay with either suggestion and ready to submit a PR in case of agreement.

**Comment by rossabaker** [comment]
Thanks for the Gitter reminder, and sorry this fell through the cracks.  

I think on the adopters page makes the most sense.  That's where the other OSS projects are.

**Comment by gvolpe** [comment]
No worries, I'm about to send a PR for this :)
