### ISSUE TITLE
Java 8 requirement: yea or nay?

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#158]
We are considering a Java 8 upgrade for the following features:

* JSR 310 date time API
* Improved crypto suite

Java 8 has been available for a long time, and Java 7 is going to be [EOL'ed in April](http://www.oracle.com/technetwork/java/eol-135779.html).

If you would not be able to use http4s if it required Java 8, please speak up here.

**Comment by rossabaker** [comment]
The motion passes.  Leaving ticket open for upgrade.

**Comment by before** [comment]
Sorry for stepping in so lately, but for me it would be an issue. Sadly at work we are relying Java 7 at the moment. I think if we are interested supporting Scala 2.10 as well as Servlet API 2.5 and several other old backed stuff it would make sense to keep Java 7 support in 2015. Does it make sense?

**Comment by rossabaker** [comment]
I had a feeling a voice of dissent would appear. :-)

The time issue could potentially be resolved by
https://github.com/reactivecodes/scala-time, but it's not stable yet.  It
also doesn't *need* to be resolved at all.

It's up to @bryce-anderson to speak to the inadequacy of Java 8 crypto.

Sorry for stepping in so lately, but for me it would be an issue. Sadly at
work we are relying Java 7 at the moment. I think if we are interested
supporting Scala 2.10 as well as Servlet API 2.5 and several other old
backed stuff it would make sense to keep Java 7 support in 2015. Does it
make sense?

--
Reply to this email directly or view it on GitHub
<https://github.com/http4s/http4s/issues/158#issuecomment-68600483>.

**Comment by bryce-anderson** [comment]
@before, do you mean for the whole 2015 year? I'd be really happy to get the time changes in before 1.0, but don't really care until then. Considering we are a cutting edge tool, I'd hate to be held back to old technology that is beyond end of life.

The crypto bits in java8 should only be required when attempting to run a http2.0 app, but which JDK its compiled against shouldn't matter. I can check this once http/2.0 hits blaze snapshots.

**Comment by before** [comment]
Enterprise companies have sometimes more constraints to be able to upgrade Java (or other technologies). I would support Java 7 this year, because I expect another wave of upgrades if the Java 7 is EOL and some months are gone (and hopefully Java 9 test versions are out).

If we see us more as a cutting edge library we could also question Servlet 2.5 and Scala 2.10 support. But I see you arguments when supporting HTTP/2.0. For several other Java library improvements we had back-ported JARs (e.g. Fork-Join). Maybe there is an alternative for this too?

**Comment by rossabaker** [comment]
Servlet 2.5 support is not currently on the radar, but would be possible if there were demand.  (I think Google App Engine is the last significant compelling case for 2.5, and nobody has asked for it.)

**Comment by bryce-anderson** [comment]
I'm of the opinion we should let this issue simmer until it becomes clear that we have to make a choice then reevaluate. The status quo is appropriate until java7 EOLs, and considering that current waves in the community, I don't think we will find ourselves at 1.0 for a few more months.

**Comment by refried** [comment]
Just chiming in to say that although I personally would like to ditch Java 7, and even though Java 7 is almost EOL, I don't think Java 8 has yet been approved to run on some gov't computers (etc.).  Seems a ridiculous to me, and I was hoping to use http4s on these.  I can try to find out more if desired.

**Comment by rossabaker** [comment]
That's good information.  We're not taking any immediate action on this, but I love the user feedback.  Lurkers, speak up, so we know the tradeoffs when we revisit this.

**Comment by LeifW** [comment]
Not using Java 8 at my work. I think it might be possible to get them to
upgrade eventually; we're not really a Java shop.

**Comment by coltfred** [comment]
@rossabaker We're just exploring http4s for the first time, but we also are stuck on Java 7 for some non trivial amount of time. Maybe late this year? Don't know for sure.

**Comment by ritschwumm** [comment]
java 7? you guys seem to work in very modern companies...

**Comment by rossabaker** [comment]
lol, I was using Java 1.4 just a few years ago.  I'm not there anymore, but that experience is why I've been reluctant to push this unless it truly holds back progress.

**Comment by mdedetrich** [comment]
Im all for pushing JDK 8, mainly for ecosystem reasons. Scala 2.12.x is aiming for JDK 8, and it will provide significant improvements in a number of areas (one being reducing the huge scala .jar sizes, amongst many other things)

There are other things, like inbuilt javascript engine (nashorn) which does push the case for having jdk 8 as a requirement. From a purely http4s webserver spectrum, the argument isn't so strong, but when you consider where JDK8/Scala 12.x is heading, there is a very strong argument for making it a requirement, both in terms of maintaining http4s, and the user experience

**Comment by ijuma** [comment]
The Scala 2.12 argument will be stronger once it is actually released. Java 8 would present an issue in the environment where we are currently using http4s, sadly.

**Comment by mdedetrich** [comment]
Yes of course, but we already know what the goals of Scala 2.12 will be, so there is a case in http4s preparing itself for Scala 2.12.

Of course, counter arguments are just as legitimate. Personally, I am not sure why companies are so hesitant to upgrade JDK, considering that its basically the most stable VM out there, but thats something thats unlikely ever to change

**Comment by bryce-anderson** [comment]
It should be noted that Java 7 has officially reached EOL.

**Comment by rossabaker** [comment]
This is now blocking an upgrade to Jetty 9.3: https://webtide.com/jetty-9-3-features/

**Comment by ijuma** [comment]
I should mention that my comment above is no longer relevant as the production environment has been upgraded to Java 8 (I am not there anymore, but it was done just before I moved on).

**Comment by bryce-anderson** [comment]
If we are not going to do the upgrade after the EOL and we now have to hold back dependencies, when should we? We need some sort of metric for this. I'm not trying to aggressively push java 8 (though I do want to upgrade), I just think we need some milestone or metric.

**Comment by rossabaker** [comment]
Thanks for the update.  This is still not an urgent issue, but the case for is inevitably growing and the case against is inevitably shrinking.

If any of the other objectors' situations have changed, please speak up again. :)

**Comment by rossabaker** [comment]
@bryce-anderson raises a fair point.  Our userbase has grown considerably since this first came up.  Perhaps we should try to funnel people back here via Twitter and Gitter to retake the temperature?

Another data point: I am no longer running Java 7 anywhere that matters.

**Comment by kryptt** [comment]
For what its worth: I would bump to java 8 on 0.9, write a note on the README making note of the upgrade and that we accept pull requests to the 0.8 branch from people still requiring java 7 support, but all future work will depend at least on java 8.

**Comment by coltfred** [comment]
Java 7 isn't reall EOL, but it isn't getting any more public updates. I wasn't able to get the thing I was doing in http4s into production here anyways so I no longer have an issue with it.

**Comment by mdedetrich** [comment]
Im all for it, note that the main (compelling reason), specifically in regards to Scala, for moving to Java 8, is that Scala 2.12 will only support Java 8 (since Scala 2.12 is going to support Java's Function Interfaces, amongst other things)

My opinion is sooner rather than later, as it will cause less pain, but it obviously all depends on what the community wants

**Comment by LeifW** [comment]
Same thing Ismael just said. I upgraded them to Java 8 (Java 7 not being updated anymore), but am no longer there. Don't think my vote counts for much though; I don't use http4s, but would like to someday (by then we'll all be on Java 9 probably).

**Comment by kryptt** [comment]
@LeifW yes, we can even try those out now with 2.11.7 

https://github.com/scala/make-release-notes/blob/2.11.x/experimental-backend.md

**Comment by bryce-anderson** [comment]
There haven't been any __No__'s yet, but I'm expecting @refried to chime in sometime. I expect people working for government agencies will generally be the ones held back by this at this point.

**Comment by refried** [comment]
So I’m optimistically developing Java 8 now, but the fear is that our govt customer will reject the product and we’ll have to Java-7-ify it (we’ve had a hard time getting concrete information about this sort of thing). 

Anyone know if a JDK 8 -> JRE 7 conversion can be done automatically somehow?

**Comment by refried** [comment]
I guess there’s retrolambda, but no complete solution.

**Comment by mdedetrich** [comment]
I don't think there is a solution that I would put my hands down for working completely correctly (that is using the assumption that, since its a govt customer, they require things to work absolutely correctly without problems)

**Comment by rossabaker** [comment]
@refried: a Java downgrade eventually becomes about more than class format.  There is also new API.  The one that first comes to mind is `javax.time`, though that exists (under different package name) in a backport.  I would Java7ify if necessary by forking and making what should remain the few necessary tweaks.  I can't speak for government, but I've consulted in other technologically conservative environments, and found the EOL acronym to be a powerful force for change.

At this point, it seems all objections have been dropped officially or optimistically.  Let's do this.

**Comment by refried** [comment]
:+1:
