### ISSUE TITLE
Proposal - Remove Timeout middleware

### ISSUE THREAD

**Issue by lukestephenson** [http4s/http4s#1583]
The `Timeout` middleware is defined on some cats-effect `Effect`. 
 https://github.com/http4s/http4s/blob/0d1ebe8cfbe439703dd189dd0af663d8d9bbed16/server/src/main/scala/org/http4s/server/middleware/Timeout.scala#L39

The Timeout implementation involves a second async job.  The timeout logic takes the first of whichever of the original job or the timeout job completes first.  As per the cats-effect docs:
> If you want concurrency, you should use a streaming framework like fs2 or Monix.

The current implementation relies on the `race` method from fs2 which was recently made private. https://github.com/functional-streams-for-scala/fs2/pull/1013/files#diff-10e988c94c4e1d589701191bb50ce692R121.  I think this should be private given the `unsafe` calls it contains.

To upgrade to fs2 0.10.0-M9 means either coming up with a new strategy for Timeouts or dropping this functionality.  I don't think it makes sense to provide a Timeout for any `Effect` so propose removing.

**Comment by SystemFw** [comment]
>  think this should be private given the unsafe calls it contains.

As I said in the fs2 ticket, that's not the reason, those calls are wrapped in `F` so they are pure. The reason is the lack of a guarantee for resource safety. We can discuss reintroducing it as a public method depending on how strongly http4s wants it

**Comment by lukestephenson** [comment]
@SystemFw Thanks for clarifying.

I still think it's not the most desirable usage of cats-effect so should be removed from http4s.  I think in http4s it would be more correct to provide Timeout implementations specific to Future / monix Task etc where it makes sense for the underlying framework (if provided at all by http4s).  There shouldn't be an Timeout implementation for IO in my opinion.

**Comment by aeons** [comment]
In #1584, the private implementation of `fs2.async.race` has been internalized in the Timeout middleware for now.

**Comment by rossabaker** [comment]
As of #1725, `Timeout` middleware is implemented in terms of the new `Concurrent` functionality.
