### ISSUE TITLE
Websocket convention is more intuitive from the point of the Receiver

### ISSUE THREAD

**Issue by jmcardon** [http4s/http4s#1596]
Currently websockets on 0.18 are

`read` -> Sends messages to the RealWorld™
`write` -> Receives messages from RealWorld™

This is pretty backwards. Most people writing websocket services think of it from the point of the server.

@ChristopherDavenport Had a good convention for this:

`read` -> `serverWrite` or maybe `serverEmit`
`write` -> `serverRead`

This is a simple rename, but should also be accompanied by it being noted in the scaladoc.

**Comment by cquiroz** [comment]
This has been the convention for quite a while, since at least 0.14. However I agree that it is confusing. I like the idea of prefixing with `server`.

**Comment by jmcardon** [comment]
@cquiroz maybe you disagree with me, but when you're writing a backend service, the most natural thing to do to when writing a websocket is thinking about it from the point of view of the service you're writing, not the sender to the service.

I think this is natural and to any newcomers (especially from play) it can be a point of confusion.

**Comment by cquiroz** [comment]
I recall being confused too, but didn't want to change the convention when we ported it to fs2. Let's remember though that being a socket there is no preferred side to it. Prefixing seems good but I could be convinced of other options

**Comment by rossabaker** [comment]
Can we use the same model when we add support for the client?  If we prefix with "server", that would impede a shared model.

The words that jump out to me in @jmcardon's explanation are `send` and `receive`.  How about those as names?

**Comment by rsoeldner** [comment]
@rossabaker with `send` and `receive` the flow is (at least for me) much clearer, If you want I can PR this change.

**Comment by rossabaker** [comment]
I would approve `send` and `receive`.  I don't know who else is with me.  😄

**Comment by jmcardon** [comment]
:+1: to `send` and `receive`

**Comment by rossabaker** [comment]
Alright.  @rsoeldner, PR would be appreciated. :)

**Comment by cquiroz** [comment]
@rossabaker 👍 for a shared client/server model
