### ISSUE TITLE
add flatMap on EntityDecoder?

### ISSUE THREAD

**Issue by julien-truffaut** [http4s/http4s#160]
```scala
trait EntityDecoder[T]{
  def flatMap[U](f: T => DecodeResult[U]): EntityDecoder[U] = ???
}
```

**Comment by bryce-anderson** [comment]
I like the method but not the name: its not really a ```flatMap``` operation. Is there a common name for this type of transformation? I believe @rossabaker dug into this at one point and had an answer that didn't work out for some reason or another, but perhaps I'm wrong.

Bottom line, I don't mind adding a method of that form, just not with that name.

**Comment by rossabaker** [comment]
I agree it's not a flatMap, and I don't know a standard name.

Similar precedents: 
* `Service` has a `flatMapTask`.  
* `Kleisli` has a `flatMapK`.

**Comment by kaiserpelagic** [comment]
I ran into this exact problem today when trying to write a decoder from Argonaut Json to T. I ended up with something like this

object ArgonautDecoders extends ArgonautInstances {
  implicit def argonatuDecoder[T](implicit decode: DecodeJson[T]): EntityDecoder[T] = {
    json.map((json: Json) => decode.decodeJson(json).value.get)
  }
}

The value.get is quite nasty. Is there a better way to handle this in the short term.  The 'flatMap; function is exactly what i need, regardless of what is ends up being call.

**Comment by bryce-anderson** [comment]
As there is no obvious method name, lets just make one up. How about ```flatMapR``` where R is for Result? I don't have any particular affinity but a single capitol char at the end seems right.

**Comment by bryce-anderson** [comment]
@kaiserpelagic you may also be interested in issue #156. I imagine that will get done sooner than later, but if you are interested in lending a hand, PR's appreciated :)

**Comment by LeifW** [comment]
Wonder if this might be relevant? http://arxiv.org/abs/1412.7148
"Monads need not be endofunctors". So the "monoid" op of monad doesn't necessarily have to be closed, i.e. yield the same type of monad as the two you were "flattening" together?

**Comment by rossabaker** [comment]
Well, how nice that the relative operation is already named flatMapR. :-)
