### ISSUE TITLE
Repo size

### ISSUE THREAD

**Issue by ceedubs** [http4s/http4s#1605]
I just did a `git pull` on a computer that hadn't pulled http4s for a while, and the diff was ~70 MB. It looks like some major culprits are the `index.js` files such as [this one](https://github.com/http4s/http4s/blob/gh-pages/v0.18/api/index.js) that are in the `gh-pages` branch, which are each ~3.3 MB. As far as I can tell, a new one is generated for each release, so I worry that this might make the repository size grow at an unsustainable rate.

Sorry, I don't have any ideas for a solution here -- I just wanted to raise the concern and hope that someone else had a good answer.

**Comment by rossabaker** [comment]
Is there prior art?  We're not unique in publishing our scaladoc on builds.  Maybe we're unusual in publishing between releases.

**Comment by ceedubs** [comment]
Sorry I'm not sure. I think that two reasons that this is more of a problem in http4s than in Cats is because at the moment the website isn't published very often for Cats (it's a manual process), and we aren't maintaining multiple versions of the docs at once on the gh-pages branch, so that may mean that we are just storing a diff where http4s is duplicating the contents.

Having said that, we will want a better setup for publishing/retaining docs for Cats in the future, so we could benefit from figuring out a better solution.

**Comment by rossabaker** [comment]
Another possible solution is to truncate history on gh-pages periodically.  It's 100% generated code anyway.

**Comment by rossabaker** [comment]
I truncated a while back, and we can do it again as needed.
