### ISSUE TITLE
Upgrade to cats-1.0.0 dependenices

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#1616]
Dependencies:
* [ ] argonaut (argonaut-io/argonaut#209)
* [ ] cats-1.0.0 (#1615)
* [ ] circe
* [ ] fs2
* [ ] fs2-jawn
* [ ] fs2-reactive-streams

**Comment by jmcardon** [comment]
Maybe do 1.0.1 and skip the whole `1.0.0` debacle with MF?
