### ISSUE TITLE
[Feature Request] `Client.expect` gives the option of including body in the `UnexpectedStatus` error

### ISSUE THREAD

**Issue by kailuowang** [http4s/http4s#1632]
Many API only gives the detailed error information in the body, including the body in the `UnexpectedStatus` would be really helpful. 
Right now I am using my own implementation of `expect` like 
```scala
def expect[A](req: Request[F], onError: Option[(String, Status) => Throwable] = None)
 (implicit d: EntityDecoder[F, A]): F[A] = {
   val r = if (d.consumes.nonEmpty) {
        val m = d.consumes.toList
        req.putHeaders(Accept(MediaRangeAndQValue(m.head), 
      m.tail.map(MediaRangeAndQValue(_)): _*))
      } else req
   http.fetch(r) {
      case Successful(resp) =>
        d.decode(resp, strict = false).fold(throw _, identity)
      case failedResponse =>
        onError.fold(F.raiseError(UnexpectedStatus(failedResponse.status))) { f => 
          EntityDecoder[F, String].decode(failedResponse, false)
            .fold(identity, f(_, failedResponse.status).flatMap(F.raiseError)
       }
    }
}
```
If would be nice to have an idiomatic way to do this.

**Comment by rossabaker** [comment]
This is something we've discussed before, but not settled on an ergonomic API.  Your version presumes that the failed response can be decoded to a String, which is probably usually true.  A `Response => F[Throwable]` would be more general, but maybe less convenient to write.

**Comment by kailuowang** [comment]
How about making the error body type parametric? 
```scala
class PartialExpect[A](val dummy: Boolean = true) extends AnyVal {
  private def handle(req: Request[F], onError: Response[F] => F[Throwable])
     (implicit d: EntityDecoder[F, A]): F[A] = {
     val r = if (d.consumes.nonEmpty) {
        val m = d.consumes.toList
        req.putHeaders(Accept(MediaRangeAndQValue(m.head), 
      m.tail.map(MediaRangeAndQValue(_)): _*))
      } else req
    http.fetch(r) {
      case Successful(resp) =>
        d.decode(resp, strict = false).fold(throw _, identity)
      case failedResponse =>
         onError(failedResponse)
    }  
  }
  def apply(req: Request[F])
     (implicit d: EntityDecoder[F, A]): F[A] = handle(req, 
        r =>  F.raiseError(UnepxectedStatus(r.status)
    }  
  }
   def apply[EB](req: Request[F], onError: (EB, Status) => Throwable)
     (implicit d: EntityDecoder[F, A], ed: EntityDecoder[F, EB]): F[A] = handle(req, 
        r => ed.decode(r, false)
            .fold(identity, onError(_, r.status).flatMap(F.raiseError)
    }
  }
}
def expect[A]: PartialExpect[A] = new PartialExpect[A] 
```

So user can either call either the usual way or call it with an onError like
```scala
expect(myReq, (String, Status) => MyServerError)
```

**Comment by rossabaker** [comment]
Is that `PartialExpect` design to get around default arguments on multiple overloads?  I tried adding an `onError: Response[F] => F[Throwable] = DefaultOnError` to all the existing `expect`s and ran face first into that.

I experimented with an `expectOr` syntax that puts the callback in a final parameter group in #1634.  

It's a drag to do this across the board if people want a consistent behavior for failed `expect`s.  It's important to have a good default, but people want different things out of the default.  We could alternatively make it part of the client config?

**Comment by kailuowang** [comment]
The partialExpect is to help the ergonomics of the error type parameter getting inferred by the onEorror function. Yeah overloads with default value is always tempting yet disappointing at the end.
 I think your `expectOr` is a good step. Adding a default handler to client conf sounds a good idea and should cover the majority of the use cases.

**Comment by rossabaker** [comment]
This would be the first client conf that's part of `org.http4s.client.Client` as opposed to either the blaze client config or async client config.  I think it would need to be passed through the latter to reach the former.  I guess this is okay.  Just thinking out loud at this point.

**Comment by rossabaker** [comment]
Do we want to go any further with this, or are we happy with the `expectOr` at this point?

**Comment by kailuowang** [comment]
Super happy!

**Comment by piotrga** [comment]
My 2 pence: Wouldn't it be helpful if the body of response was added to the exception message if it can be decoded to string, possibly truncated to 50kb? 

Wouldn't it make troubleshooting much easier?
