### ISSUE TITLE
Timed tasks with http4s 0.18(fs2)

### ISSUE THREAD

**Issue by balatbn** [http4s/http4s#1633]
In our application, as part of serving a request, we make an external call to another service. We get response from that service in an async manner. i.e., That service will send the response via a different http call.

So far, we were using Task.async to achieve this(along with a timeout). Sample code:

```scala
Task.async[String](callback => pendingRequests.put(controlId, callback))
          .timed(15.seconds)
          .handleWith {
            case e: Exception =>
              logger.error(e)(...)
              pendingRequests.remove(controlId)
              Task.now("<Custom error message to client>")
          }
```

We use callback function to send final response to client. How can I achieve similar "timeout" functionality with fs2(and cats)? I see IO.async that is similar to Task.async(along with IO.shift, I guess), but I don't see any "timed" method there.

**Comment by rossabaker** [comment]
There is an [unsafeRunTimed](https://github.com/typelevel/cats-effect/blob/4616dd6f4dc513320787c11a360f51c9d4b6f192/README.md#testing-and-timeouts), but it will leak resources.

There is a requestTimeout on the BlazeClientConfig, which applies to all requests made by the client.  This is resource safe.

If you need a timeout for specific requests from your client that doesn't apply to the whole request, we don't have a great story for that yet, but we have the plumbing we need to make it.  What we don't have is a proposal for a good API.  We should discuss how you'd like it to look.

**Comment by balatbn** [comment]
This is not a timeout for HTTP client. We are waiting for a response from backend server via a complete different HTTP call. i.e., Our client thread is "waiting" for a different HTTP request. Hopefully I explained it better?

Doesn't unsafeRunTimed block the current thread? With scalaz approach, I believe we never blocked the current thread.

**Comment by balatbn** [comment]
As an example, this is like DeferredResult in Spring (in terms of functionality).

**Comment by wedens** [comment]
I think you can use [`timedGet`](https://github.com/functional-streams-for-scala/fs2/blob/01d7b41cd08fe84b4f345a6ad7b01fc314b4c2be/core/shared/src/main/scala/fs2/async/Promise.scala#L66) from `fs2.async.Promise` to achieve it. Callback invocation will be replaced with a promise completion.

/cc @SystemFw

**Comment by SystemFw** [comment]
Assuming you are on the latest version, you can indeed use `timedGet` from `Promise` to write a `timeout` combinator. However, as Ross mentioned ("but it will leak resources"), it's not really safe to do so (in general). 
The reason is that cats effect IO at the moment is not interruptible in any way, so when it times out you stop waiting on the result (so from the caller point of view "it works"), but the timed out IO is still running in the background, which may leak resources. Up to you if you are ok with this tradeoff or not.

Very likely cats effect IO will be interruptible to some extent in future releases (although there's still limits to what one can do)

**Comment by balatbn** [comment]
Thanks for the pointers about timedGet.

Since we don't have any underlying request waiting for response, resource leakage is not a problem. We just need to remove the pending request from a map. That was done while checking for failure case in timedGet response.
