### ISSUE TITLE
Outdated docs links

### ISSUE THREAD

**Issue by jcranky** [http4s/http4s#1655]
![selection_007](https://user-images.githubusercontent.com/772886/36197359-d4e5b72e-1173-11e8-8420-c7793d536b56.png)

In the initial page it is ok, but in internal pages it is like the picture above. I could send a PR, but I don't know where those links are coming from...

**Comment by rossabaker** [comment]
Older versions of the site publish independently.  As it stands, we need to go back and fix those when we add new versions.

A call to fetch some static JSON to populate the dropdown would fix this more permanently.

**Comment by armanbilge** [comment]
Fixed in https://github.com/http4s/http4s/issues/1655.
