### ISSUE TITLE
websocket sub protocol not supported

### ISSUE THREAD

**Issue by meta8** [http4s/http4s#1656]
when connecting  to a websocket http4s endpoint, the connection fails when sub-protocols are specified

```javascript
w = new WebSocket(url, "protocolOne")
w = new WebSocket(url, ["protocolOne", "protocolTwo"])
```

failing with browser error (chrome) :
_WebSocket connection to 'ws://localhost:8080/wsecho' failed: Error during WebSocket handshake: Sent non-empty 'Sec-WebSocket-Protocol' header but no response was received_

```scala
case req @ GET -> Root / "wsecho" =>
        req.headers.foreach( h => println(s"header [$h]"))  // can see [Sec-WebSocket-Protocol: protocolOne, protocolTwo]      
        val queue = fs2.async.unboundedQueue[IO, WebSocketFrame]
        val echoReply: Pipe[IO, WebSocketFrame, WebSocketFrame] = _.collect { 
          case Text(msg, _) => Text("You sent the server: " + msg)
          case _ => Text("Something new")
        }
        queue.flatMap { q => // Queue[IO, WebsocketFrame]
          val d = q.dequeue.through(echoReply)
          val e = q.enqueue
          WebSocketBuilder[IO].build(d, e)
        }
```

**Comment by rossabaker** [comment]
If the client sends a `Sec-WebSocket-Protocol` header, the server needs to respond with a `Sec-WebSocket-Protocol` header containing one of the values from that request header.  Add a `headers = ` argument to `WebSocketBuilder.build` to supply additional response headers.

**Comment by rossabaker** [comment]
Closing as answered.  If this didn't help, please reopen.
