### ISSUE TITLE
Add parser for Location header

### ISSUE THREAD

**Issue by julien-truffaut** [http4s/http4s#166]

**Comment by bryce-anderson** [comment]
On the job.

**Comment by julien-truffaut** [comment]
btw, do you think we could throw a missing implementation error or something similar in that case?

**Comment by bryce-anderson** [comment]
Do you mean for the ```Location``` header? I hope to get this fixed and @rossabaker implicitly suggests we can do a patch release. We should comb through all our headers and make sure we arn't missing parsers for others as well. Any that we decide to stall on, I would be more inclined to comment out their ```Header``` instance, but this would be a binary breaking change.

**Comment by julien-truffaut** [comment]
yes, I mean it is a bit confusing to have a header definition but you cannot use it to read from `Headers`. Btw, I don't need a patch for this, so there is no rush on my side.

**Comment by bryce-anderson** [comment]
Closed by #167.
