### ISSUE TITLE
Abolish backtics

### ISSUE THREAD

**Issue by jmcardon** [http4s/http4s#1667]
That is, get rid of all spray-like backticks.. Either using snake, camel or pascal case.

Mostly for autocompletion discovery I've never liked the backticks.

**Comment by rossabaker** [comment]
I am generally in favor of this.

Concerns:
- It might make more clashes between header names and type names.  `Cookie` is a big pain right now.
- This is probably worth publishing a scalafix for if we proceed.

**Comment by rossabaker** [comment]
Happening in #4611 .

**Comment by armanbilge** [comment]
We kept them.
