### ISSUE TITLE
Request body as Process[Task,String]

### ISSUE THREAD

**Issue by prange** [http4s/http4s#168]
A convenience function for
```req.body.map { c => new String(c.toArray, req.charset.getOrElse(Charset.`ISO-8859-1`).nioCharset)}.toTask```
on request would be of great benefit.

**Comment by bryce-anderson** [comment]
Do you need the body to be streamed or do you want the whole thing buffered into a single a chunk? The latter is relatively easy already:
```scala
EntityDecoder.text(req).flatMap { myString => Ok("foo" + myString) }
```

**Comment by prange** [comment]
Excellent,

just what i was after.
