### ISSUE TITLE
Scala Native support

### ISSUE THREAD

**Issue by danielyli** [http4s/http4s#1689]
I’d love to see http4s on https://index.scala-lang.org/search?q=*&targetTypes=Native and https://github.com/tindzk/awesome-scala-native.  Looks like scalaz is already Scala Native-ready. :)

**Comment by aeons** [comment]
We depend heavily on the cats part of the ecosystem, and cats itself is not running in Scala Native yet.

This issue is tracking the progress: https://github.com/typelevel/cats/issues/1549

**Comment by jcranky** [comment]
Just out of curiosity, what use case would you see for this? :)

**Comment by danielyli** [comment]
I found a need to write a CLI utility yesterday that, among other things, fetches a bunch of web pages in one go. Fetching them serially was out of the question for performance reasons, but Bash/Zsh/etc. doesn’t easily support parallel curl, and especially doesn’t easily support asynchronous logic such as first-one-wins.

I ended up staying up til the wee hours of the morning slapping something together in Bash, but I’m sure it would’ve been easier (and more pleasant!) writing it in Scala. I imagine such a library would be helpful for any Scala Native CLI utility that needs to access the web.

**Comment by rossabaker** [comment]
The necessary dependency chain is cats -> cats-effect -> fs2 -> http4s.  It's still on step one, but, well, maybe someday. :)

**Comment by jmcardon** [comment]
Piggybacking on @jcranky's remark, it would work iff enough of java's primitives are translated to support what we need in scala-native (I assume yeah, but still). 

From what I gather [here](http://www.scala-native.org/en/latest/lib/javalib.html), it seems the majority of stuff from `java.concurrent` have been translated, so it's possible blaze would work. We'll have to see, but a starting point would be trying to compile blaze for scala-native.

That said, I do want to point out that this _is_  project tax. Multi-platform compiles (scalajs/native) are a tax on the project to maintain, so it's a thing to consider whether the use case is worth it.

**Comment by rossabaker** [comment]
I am not particularly excited about this when we have GraalVM, and scant progress has been made in our dependencies.  I doubt this one is ever going to happen.

We can revisit if and when fs2 gets it.
