### ISSUE TITLE
Cancellation

### ISSUE THREAD

**Issue by hvesalai** [http4s/http4s#1691]
Cancelling asynchronous computations saves CPU cycles and thus our planet.

Http4s should support cancellation of requests both on the client side and server side. Client-side cancellations should be propagated over HTTP to the server side using HTTP2 signalling (to be specified). Also closing a connection should result in a cancellation of tasks on the server side.

**Comment by hvesalai** [comment]
Ping @bryce-anderson, I created this issue in http4s, but it concerns also blaze

**Comment by rossabaker** [comment]
We already have the first use of this in the `Timeout` middleware.  I doubt there is much more we can do in 0.18, but we should absolutely be looking for opportunities to use this in 0.19.

**Comment by rossabaker** [comment]
This is already implemented in some backends.  If we identify any that are missing, let's treat those as separate tickets.

**Comment by hvesalai** [comment]
Thank you!
