### ISSUE TITLE
API change ideas, per gitter discussion

### ISSUE THREAD

**Issue by edmundnoble** [http4s/http4s#1692]
Discussion of these changes begins at https://gitter.im/http4s/http4s?at=5a9ef5196f8b4b9946f7deaa. It extends for a *while*, into the next day, so I'll try to paraphrase, starting with reasons.

### Ideas
- An original goal of http4s was to allow users to enjoy a separation between http4s-dsl and http4s-server, so that custom routing DSLs and code would be easy to use and could add features to http4s.
- I proposed an alternative routing DSL which is less expressive in exchange for being more easy to analyze and more performant.
- There are other routing DSL ideas loosely following Haskell's `servant`.

### Issues
- Routing as a concern is shared between http4s-server, http4s-dsl, and http4s-core. The only way to do routing is really with `HttpService[F]` and `<+>`; that's the only thing middleware supports, that's the only thing `mountService` will take in, and that's what's created by `HttpService.apply`. This means *all* services must have a) effectful routing and b) "unsealed" routing (to be later "capped" by adding 404's for failed matches).
- The above means alternative routing DSLs are unable to create "sealed" routes which *must* succeed and have that encoded in the type, or to use exclusively "non-effectful" routing (with `Option` outside the service effect `F`), and even if they did, middlewares would not be usable on them.
- Routing with `<+>` creates every effectful `F[Response]` in the entire `HttpService`, even when it knows that effect won't be executed because an earlier route was successfully matched. 300 routes, 300 unnecessary object creations.
- More severely, the way those effects are created (if you're using `HttpService.apply`, as most are) includes executing matcher code and then sequencing a resulting `Option`, which means that no matter which route is accessed the routing itself always takes worst-case time.

### Solutions (in decreasing order of controversy)
- `HttpService.apply` should suspend its matching inside an `F[_]: Sync`. It's a bit sneaky, but it's the best way to avoid re-matching on requests. We will still create the unnecessary effect objects, and benchmarking would be nice to establish the degree this helps (and could be made better).
- A new version of `mountService` which works on total services.
- More polymorphic middlewares that can work on different service types.
- Perhaps a rewrite of the old version of `mountService` to use the new version, so that routing is always handled by user code and never `http4s-server` or any backends.

**Comment by jmcardon** [comment]
In regards to solutions:

- 1 should be implemented for now, on master, for the sake of an efficiency fix.
- 2 we need some notion of what services are total. It also seems not independent from numba 3, but both are good solutions.

**Comment by rossabaker** [comment]
Some relevant tickets from the past: #53, #55, #353, #1424.

**Comment by rossabaker** [comment]
This is pretty well addressed by the introduction of `HttpApp`, deferred `<+>` on `HttpRoutes`, and the parameterization of most middleware.
