### ISSUE TITLE
Smite Seq wherever possible

### ISSUE THREAD

**Issue by jmcardon** [http4s/http4s#1695]
#1694 adds [this](https://github.com/http4s/http4s/pull/1694/files#diff-fc471fcf59af6fc124e6a51987dc7fa3R59) as a temp fix for not throwing an exception in multipart/form-data, but a more principled fix is simply acknowledging that you can't transmit a `multipart/form-data` body in a sane way without at least one part.

That said, there's more than one Fishy `Seq`, so we can probably take the opportunity to smite them at the same time.

**Comment by rossabaker** [comment]
What is your genreal replacement for `Seq`?  `List`?  `Vector`?  `immutable.Seq`?  There are the `NonEmpty*` types in certain contexts.

**Comment by rossabaker** [comment]
I still agree with this.  The first step is to identify them, and then we can identify correct replacements.

**Comment by danicheg** [comment]
From my way of thinking, we have smitten `Seq` where it was reasonable and doable. I'm closing this, but feel free to reopen it.
