### ISSUE TITLE
middleware.Logging should log interesting request-/response-specific fields, such as method and response status

### ISSUE THREAD

**Issue by megri** [http4s/http4s#1708]

**Comment by rossabaker** [comment]
I still think it's to our discredit that we don't have a simple way of outputting the [common log format](
https://en.wikipedia.org/wiki/Common_Log_Format), but this seems like a good step in the right direction.

**Comment by megri** [comment]
@rossabaker I first looked to BlazeBuilder for this functionality. Having to wrap every service in a middleware gets ugly. I think it would be reasonable to open a new issue to deprecate middleware.Logging and introduce a BlazeBuilder setting that outputs these logs according to the linked standard.

**Comment by rossabaker** [comment]
I think this is fixed by #1709.  The better way is tracked by #1721.
