### ISSUE TITLE
Make `CORSConfig` more typesafe

### ISSUE THREAD

**Issue by gvolpe** [http4s/http4s#1717]
It would be nice to have a `CORSConfig` more typesafe. This is the definition at the moment ([Source]( https://github.com/http4s/http4s/blob/master/server/src/main/scala/org/http4s/server/middleware/CORS.scala#L18)):

```scala
final case class CORSConfig(
    anyOrigin: Boolean,
    allowCredentials: Boolean,
    maxAge: Long,
    anyMethod: Boolean = true,
    allowedOrigins: String => Boolean = _ => false,
    allowedMethods: Option[Set[String]] = None,
    allowedHeaders: Option[Set[String]] = Set("Content-Type", "*").some,
    exposedHeaders: Option[Set[String]] = Set("*").some
)
```

I propose to have at least `maxAge` as a `FiniteDuration` and `allowedMethods` as `Option[Set[org.http4s.Method]]`. Probably `allowedHeaders` and `exposedHeaders` could make use of the `org.http4s.Header` type as well. `org.http4s.Headers` exists but its internal representation is a `List`.

Don't mind submitting a PR with these changes.

**Comment by rossabaker** [comment]
@gvolpe I think all of these are good ideas.

I also want to move away from case classes as configuration: these don't have a good binary compatibility story if more settings get added later.  I've started creating abstract classes and `with*` methods, which is tedious, but lets us grow in the future without breaking compatibility.

**Comment by rossabaker** [comment]
We should take this opportunity to convert to the builder pattern as well.  If anyone picks this up and doesn't understand what we mean by that, happy to help.

**Comment by rossabaker** [comment]
Good opportunity to pick up #834, though if we do it right, they don't _have_ to go together.

**Comment by gvolpe** [comment]
Oh my! Sorry for leaving this here for so long, completely forgot about it 😅

**Comment by rossabaker** [comment]
I'm backlog grooming.  I started last night in 2014, and am up to 2018!  :rocket:

**Comment by qwbarch** [comment]
If this still hasn't been worked on, I'd like to take this issue please!

**Comment by rossabaker** [comment]
Thanks, @qwbarch!
