### ISSUE TITLE
blaze client fails if no Content-Length header in response?

### ISSUE THREAD

**Issue by refried** [http4s/http4s#172]
using this:
```
import org.http4s.Uri
import org.http4s.Method
import org.http4s.client.blaze.defaultClient

import org.http4s.MessageSyntax._
import org.http4s.client._

val uri = Uri.uri("http://localhost/api")
val result = defaultClient(Method.GET(uri)).as[String].run
```

If the server responds with
```
HTTP/1.1 200 OK
Content-type: application/json
content-length: 2

[]
```
then 
```
result: String = []
```

But given
```
HTTP/1.1 200 OK
Content-type: application/json

[]
```
```
org.http4s.InvalidBodyException: Received premature EOF.
```

Maybe I'm doing something wrong, but I think it's a bug, and since I can't modify the server, I'm not sure what to do.

`Content-Length` is required in [HTTP 1.0](http://tools.ietf.org/html/rfc1945#section-10.4), but optional in [HTTP 1.1](http://tools.ietf.org/html/rfc2616#section-14.13)

Thanks!

**Comment by bryce-anderson** [comment]
This looks like a bug to me. Thanks for submitting the issue!

**Comment by refried** [comment]
P.S. That's what I call service! :-D
