### ISSUE TITLE
Large requests are getting truncated

### ISSUE THREAD

**Issue by benholtzmansmith** [http4s/http4s#1724]
I am running some service configured like so:
```
BlazeBuilder.bindHttp( port, "0.0.0.0" ).withLengthLimits(
      maxRequestLineLen = Integer.MAX_VALUE,
      maxHeadersLen     = Integer.MAX_VALUE
    )
```
However, when I POST to the service with a large piece of json (~65K bytes), it truncates the json cutting off a large portion of the data. As a result, when I try to parse the json, I get a parse error. Is there any other configuration I can play with to enable my service to handle large json bodies or is there some enforced cap on the size of the json data you can send to an http4s service?

**Comment by jmcardon** [comment]
Note: from the gitter chat, this is on 0.15, which is EOL.

If you can provide an example, we can attempt to help you debug.

**Comment by rossabaker** [comment]
Please reopen if this is still an issue.
