### ISSUE TITLE
Refactor Header file into a package

### ISSUE THREAD

**Issue by bryce-anderson** [http4s/http4s#173]
Header.scala is largely out of control. I propose we move things out of the ```Header``` object and into a ```org.http4s.header``` package.

A second change I would like to see, but I don't think is part of this issue but it wouldn't hurt to keep it in mind, is the movement of header parsers from the ```org.http4s.parser``` package onto the individual header objects. We can then unseal the ```Header``` trait, and it should be simple for others to make their own special headers with working parsers.

**Comment by rossabaker** [comment]
The second change is punted to #176.
