### ISSUE TITLE
PermitsBody and NoBody

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#1745]
We have types to represent whether a method is known to permit a body or reject it.  This is used by `Http4sClientDsl` to drive which `apply` syntax is available.  This is a neat party trick, but the machinery is a bit complicated.  Furthermore, this type level construct only guides correctness.  It doesn't guarantee it.  `DELETE("foo")` doesn't compile, but `Request(DELETE).withEntity("foo")` does.  We could do crazy tricks with dependent types to prevent the latter, but it wouldn't work for a request we parsed from the wire.  Does this type level distinction carry its weight if it's at best advisory?

**Comment by Daenyth** [comment]
As a user, especially as a user with a team who has spent less time in scala than I have, I would avoid this. I don't think it buys a lot

**Comment by rossabaker** [comment]
We do similar with status codes, to force a 401 to have a `WWW-Authenticate` and some of the 3xx to have a `Location` header and a 204 to not have a body.  The first two of these have caused users to complain as they try to circumvent it.

I was proud of this at the time, but I think I'm coming around to @Daenyth's point of view.

**Comment by jmcardon** [comment]
For the record, I stumbled upon this recently in the netty PR while implementing streaming vs full requests for requests that allowed method bodies.

I really don't think this buys us a lot at all. This would be done with typeclasses/typelevel tagging tricks/dependent types (`Request @@ Delete` or `Request.Delete[F]`) as well, but it doesn't buy us a lot to just stop someone from shooting themselves in the foot much. Regardless, if the body isn't allowed, on blaze/netty it won't be sent in the first place.

IMO we can close this. It's not worth the effort.

**Comment by rossabaker** [comment]
These traits are gone.
