### ISSUE TITLE
Custom method support

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#1746]
It's impossible to register a custom `Method` with safe/idempotent semantics or whether it permits/forbids a body since the demise of the global, mutable, despicable registry.

```scala
package com.example

package object cornercase {
  val BLORP: Method = ???
}
```

We can make `Method.fromString("BLORP") === BLORP`.  But we can't define that `BLORP` is safe, idempotent, or what type of body it takes.  We also can't make `Method.fromString("BLORP") eq BLORP`.  You can do both of these things in akka-http.

Does anybody out there actually BLORP?  If you do, can you figure out how to do this without global state?

**Comment by rossabaker** [comment]
My view: if you're important enough to be a flyweight with recognized properties, you're important enough to be in the IANA registry.

Anyone want to fight? :boxing_glove: :boxing_glove:

**Comment by jmcardon** [comment]
I think we should be against potentially unholy behavior . I really can't think of a single reason why I would ever not fight a decision in a workplace to do stuff with a custom method over HTTP. 

Down with this idea.

**Comment by cquiroz** [comment]
It's really a corner/custom case, I would skip over it
Having said that this same issue comes up if you want to e.g. add a custom `MediaType` which maybe more common?

**Comment by rossabaker** [comment]
Yes, it's a more challenging question for `MediaType`.  Encoding considerations (7-bit vs. 8-bit vs. binary) and file extensions are interesting properties here that can't be expressed without a custom registry.  People can build their own logic for this, but we can't make `mediaType.isBinary` return true.

If we implement #73, we can shrug our shoulders and point at MimeDB and offer people a patch release.

**Comment by rossabaker** [comment]
Alright, I think #73 is a good ticket for further discussion of the media types.  There are interesting MiMa issues to work through if and when that comes into being.

**Comment by jmcardon** [comment]
The MimeDB PR went through. Can we close?

**Comment by rossabaker** [comment]
There is no longer a mutable registry.
