### ISSUE TITLE
Reorganize header parsers

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#176]
> A second change I would like to see, but I don't think is part of #173 but it wouldn't hurt to keep it in mind, is the movement of header parsers from the org.http4s.parser package onto the individual header objects. ~~We can then unseal the Header trait,~~ and it should be simple for others to make their own special headers with working parsers.

**Comment by bryce-anderson** [comment]
I have an experiment for this on the branch [wip/parsersOnKeys](https://github.com/http4s/http4s/tree/wip/parsersOnKeys).

**Comment by bryce-anderson** [comment]
Closed by #287. It was decided, for now, that it is better to keep a global parser registry. This allows code to 'know' where the parsers are and allows for operations that need to know more information such as if a header can be recurring or not. 

The issue may come up again in the future, but I think this is closed for now.
