### ISSUE TITLE
Request gets executed before effect is run

### ISSUE THREAD

**Issue by drexin** [http4s/http4s#1779]
Running the following code prints `Called`, even though the effect is never run:

```scala
val service = HttpService[IO] {
  case GET -> Root =>
    println("Called")
    Ok()
}

val client = Client.fromHttpService(service)
client.expect[Unit]("/")
Thread.sleep(1000)
```

**Comment by SystemFw** [comment]
@drexin that's because you aren't encapsulating side-effects properly :)

Try `IO(println("Called") *> Ok()`

**Comment by ChristopherDavenport** [comment]
It does the routing, which is a pure operation. You are side-effecting in a pure position. If this is still present with the below then this is indeed an issue.
```scala
val service = HttpService[IO] {
  case GET -> Root =>
    IO(println("Called")).flatMap(_ => Ok())
}
```

**Comment by SystemFw** [comment]
Jinx!

**Comment by drexin** [comment]
Ah, that makes sense. I found this while debugging an issue which seemed to be caused by that, but I think I know what the problem is now. Thanks!
