### ISSUE TITLE
Edit button on website doesn't do anything?

### ISSUE THREAD

**Issue by cb372** [http4s/http4s#1795]
I think having an edit button on all the documentation pages is a great idea. But as far as I can tell, clicking the button doesn't actually do anything. Is it just me?

I'm using Chrome 65.

**Comment by jmcardon** [comment]
I'm not sure if those are intentional. @rossabaker might know more on this.

In particular all docs changes are done through the main repo under the docs directory, so I'm not sure how that would work otherwise.

**Comment by cb372** [comment]
The Contributing page says

>All pages have an edit link at the top right for direct editing of the markdown via GitHub.

So if the buttons are not supposed to be there, that text should probably be removed.

**Comment by rossabaker** [comment]
They are absolutely intended to work, and don't work for me either.  Drat.

**Comment by ChristopherDavenport** [comment]
That's a weird label combination. 😆

**Comment by rossabaker** [comment]
I think it adequately connotes my embarrassment.
