### ISSUE TITLE
Doc revamp proposal

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#1799]
Problems:
1. Publishing several versions of the docs is complicated.  
2. A custom documentation theme is beyond our skills and resources.

I propose we:
1. Flatten website and docs project into one.
2. Rebuild on the [hugo learn theme](https://github.com/matcornic/hugo-theme-learn/). (Bonus: search!)
3. Publish to a docs/x.y branch
4. Netlify will serve each docs/x.y branch at https://vx-y.docs.http4s.org
5. Current production version will be CNAMEd to https://http4s.org/

**Comment by armanbilge** [comment]
Yeah, let's not revamp the docs again for a while, eh? 😁
