### ISSUE TITLE
UriTranslation and (scriptName, pathInfo)

### ISSUE THREAD

**Issue by bryce-anderson** [http4s/http4s#180]
```UriTranslation``` offers similar functionality to the 'mount' properties of the servlet world. However, the servlet bits use ```Request.Keys.PathInfoCaret``` to represent where the path is split into ```(scriptName, pathInfo)``` which is on the ```Request``` while ```UriTranslation``` uses ```translateRootKey``` to store a ```String => String``` and doesn't have any special treatment after that. These should be brought into alignment.

**Comment by rossabaker** [comment]
The reason I like the caret is that it preserves the invariant that script name + path info is the path portion of the URI.

I'd rather it be a field in the URI, but it's a purely Request concept. And a server-side one, at that.

**Comment by bryce-anderson** [comment]
I've almost got ```UriTranslation``` into conformance.

**Comment by bryce-anderson** [comment]
Closed by #183
