### ISSUE TITLE
Query Render Innappropriate with [ and ]

### ISSUE THREAD

**Issue by ChristopherDavenport** [http4s/http4s#1813]
```
@ Uri.uri("""http://www.google.com:8085/?query[event][eq]=something""")
res10: Uri = Uri(Some(Scheme(http)), Some(Authority(None, RegName(www.google.com), Some(8085))), "/", Query(("query[event][eq]", Some("something"))), None)

@ println(res10)
http://www.google.com:8085/?query%5Bevent%5D%5Beq%5D=something
```

This appears because of our inability to render in the passing steps. 

First Uri render - 
https://github.com/http4s/http4s/blob/master/core/src/main/scala/org/http4s/Uri.scala#L108
And then in the utils
https://github.com/http4s/http4s/blob/master/core/src/main/scala/org/http4s/util/UrlCoding.scala#L39

I am inclined to believe that this should be one of the skipped characters for a query.

**Comment by kevinmeredith** [comment]
Hi @ChristopherDavenport. Regarding:

```
@ Uri.uri("""http://www.google.com:8085/?query[event][eq]=something""")
res10: Uri = Uri(Some(Scheme(http)), Some(Authority(None, RegName(www.google.com), Some(8085))), "/", Query(("query[event][eq]", Some("something"))), None)

@ println(res10)
http://www.google.com:8085/?query%5Bevent%5D%5Beq%5D=something
```

what's the problem?

I'm asking since I don't fully understand this issue's reported bug per:

> I am inclined to believe that this should be one of the skipped characters for a query.

**Comment by rossabaker** [comment]
Do we want to skip this in values, or just in keys?
