### ISSUE TITLE
Memory leak found when using blaze client

### ISSUE THREAD

**Issue by Rainfarm** [http4s/http4s#1815]
We implemented client side using blaze HTTP client (Http1Client), and we found memory leak even for the pinging of our dependencies (our own other service, "ping" means e.g., GET towards dependencies for the purpose of health check). After some profiling, we found that the leak happened for the pinging towards our services via HTTPS. But:

- Pinging towards external public services (e.g., https://httpbin.org/ip) via HTTPS didn’t cause leak.
- Pinging towards our dependencies via HTTP didn’t cause leak (e.g., towards Direct-debit service)

Our dependencies are implemented either in Scala (using http4s) or Java, and are deployed in AWS. We use AWS Load Balancer to terminate SSL. And we're NOT using self-signed certificate. The code of our client side is quite straightforward:
```
def attempt[A](request: F[Request[F]])(implicit decoder: Decoder[A],
                                         ae: ApplicativeError[F, Throwable]): F[Either[E, A]] =
    client.expect(withHeaders(request))(accJsonOf[A, F]).attempt.flatMap(x => F.delay(x.left.map(toError)))
```
Where the `client` is:`Client[F]`
When memory leaks the `org.http4s.client.blaze.Http1Connection` and some other types of objects got leaked, at the same speed. The “other types of objects” are:
```
sun.security.ssl.SSLEngineImpl
sun.security.ssl.HandshakeHash
sun.security.ssl.EngineWriter
sun.security.ssl.EngineOutputRecord
sun.security.ssl.EngineInputRecord
sun.security.ssl.CipherSuiteList
sun.security.ssl.CipherBox
sun.security.ssl.Authenticator
sun.security.provider.SHA2$SHA256
sun.nio.ch.UnixAsynchronousSocketChannelImpl$2
sun.nio.ch.UnixAsynchronousSocketChannelImpl$1
sun.nio.ch.UnixAsynchronousSocketChannelImpl
scala.util.Success
scala.util.Failure
scala.collection.mutable.ListBuffer
org.http4s.client.blaze.ReadBufferStage
org.http4s.client.blaze.Http1Connection
org.http4s.client.blaze.BlazeHttp1ClientParser
org.http4s.client.RequestKey
org.http4s.blaze.pipeline.stages.SSLStage$SSLSuccess$
org.http4s.blaze.pipeline.stages.SSLStage
org.http4s.blaze.channel.nio2.ClientChannelFactory$$anon$1
org.http4s.blaze.channel.nio2.ByteBufferHead$$anon$3
org.http4s.blaze.channel.nio2.ByteBufferHead
javax.net.ssl.SNIHostName
javax.crypto.spec.SecretKeySpec
javax.crypto.Cipher
java.util.concurrent.locks.ReentrantReadWriteLock$WriteLock
java.util.concurrent.locks.ReentrantReadWriteLock$Sync$ThreadLocalHoldCounter
java.util.concurrent.locks.ReentrantReadWriteLock$ReadLock
java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync
java.util.concurrent.locks.ReentrantReadWriteLock
java.util.concurrent.atomic.AtomicReference
java.util.TreeSet
java.util.TreeMap$KeySet
java.util.TreeMap
java.util.LinkedList
java.util.Collections$UnmodifiableRandomAccessList
java.security.ProtectionDomain[ ]
java.security.MessageDigest$Delegate
java.security.AccessControlContext
java.nio.DirectByteBuffer
com.sun.crypto.provider.GaloisCounterMode
com.sun.crypto.provider.GHASH
com.sun.crypto.provider.GCTR
com.sun.crypto.provider.CipherCore
com.sun.crypto.provider.AESCrypt
com.sun.crypto.provider.AESCipher$General
```
The memory leak is gone after we switched to use `AsyncHttpClient` instead.
 It might be some strange behaviour of AWS LB SSL termination?... Not sure.

**Comment by zarthross** [comment]
Agreed.  I might be able to make an attempt next week at creating a repro case, but make no promises on timelines.  My infrastructure is running in AWS with CloudFoundary, so it's entirely possible I have the same issue as @Rainfarm because some quirk with AWS.

**Comment by carwynellis** [comment]
FWIW we just experienced this issue over the weekend using Http1Client to implement an influxdb metrics sender. This POSTs metrics to an influxdb instance hosted in AWS over HTTPS every 10 seconds.

The client is pretty much as follows...

```scala
object InfluxClient {

  private val httpClient = Http1Client[IO]()

  def send(body: String) = {
    val request = Request[IO](
      method = Method.POST,
      uri = InfluxUri,
    ).withBody(body)

    httpClient.flatMap { client =>
      client.expectOr[String](request)(r => IO(UnexpectedError(s"Unexpected response status: ${r.status}")))
    }.attempt.unsafeRunSync()
  }

}
```

Switching to `AsyncHttpClient` also resolved the issue for us.

**Comment by rossabaker** [comment]
This wasn't consciously fixed, but versions have moved on, and we haven't seen new reports.  If this problem persists, please reopen.
