### ISSUE TITLE
OptionalMultiQueryParamDecoderMatcher only keeps the last error

### ISSUE THREAD

**Issue by gpoirier** [http4s/http4s#1825]
When using `OptionalMultiQueryParamDecoderMatcher`, the extracted parameter is of type `ValidatedNel`, so I had expected that it woudl accumulate all the validation errors if there's multiple parsing errors. However, only the last one is retained. The relevant code is there:

https://github.com/http4s/http4s/blob/87eb4b0adf2b56702158907d79bb4509781ace66/dsl/src/main/scala/org/http4s/dsl/impl/Path.scala#L280

A simple fix should to use this code instead: 

```
Some(Traverse[List].traverse(values.toList)(s => QueryParamDecoder[T].decode(QueryParameterValue(s))))
```

**Comment by rossabaker** [comment]
I'm sorry.  I meant to look at this, but got distracted.  Would you like to submit a PR for this one?  If you target release-0.18.x, and it's binary compatible (it would be if it works), then we can cut a release for you.

**Comment by gpoirier** [comment]
What I'm doing is only a prototype for now, so there's no rush to get a release out for me. I'll try to create a PR soon, but I won't be able to this week.

**Comment by m-sp** [comment]
seems this one was done long ago, github just didn't autoclose the issue
