### ISSUE TITLE
Uri missing .resolve(Uri) method

### ISSUE THREAD

**Issue by refried** [http4s/http4s#185]
I'm implementing one, but it's blocked by #184.

**Comment by refried** [comment]
https://tools.ietf.org/html/rfc3986#section-5.4 specifies that the relative Uri `g` resolved against the base Uri `http://a/b/c/d;p?q` should be `http://a/b/c/g`; but because `g` is parsed as authority instead of path (#184), it resolves to `http://g` instead.

**Comment by refried** [comment]
Hope I'm not out of line, submitting PRs without an invitation!

**Comment by rossabaker** [comment]
Wait, did none of the other committers tell you about the pull request application fee? ;)

Seriously, we love contributions.  Keep up the good work!
