### ISSUE TITLE
headers.Cookie.from does not read response cookies

### ISSUE THREAD

**Issue by unthingable** [http4s/http4s#1867]
0.18, `header.Cookie.from` appears to ignore cookies set in the response header.

A Response in the debugger:

<img width="703" alt="image" src="https://user-images.githubusercontent.com/925755/40240799-b1a2233a-5ab9-11e8-95e5-ebe0b728672d.png">

Yet, `headers.Cookie.from(resp.headers)` evaluates to `None`:

<img width="256" alt="image" src="https://user-images.githubusercontent.com/925755/40240819-c0a1a194-5ab9-11e8-9e72-f3c50a67a117.png">

The "minusCookie" part is a little confusing, it doesn't mean the cookie is actually being removed, does it?

**Comment by jmcardon** [comment]
Because cookies set in the response are usinf `Set-Cookie`, not cookie

**Comment by unthingable** [comment]
Request headers were looking pretty similar (also using `Set-Cookie`). So then this is expected behavior?

**Comment by jmcardon** [comment]
They're two different headers.`Set-Cookie` != `Cookie`. The latter for sure works.

**Comment by unthingable** [comment]
Ah, yes! Been starting at the screen too long.
