### ISSUE TITLE
missing query parameter shouldnt return 404

### ISSUE THREAD

**Issue by stephennancekivell** [http4s/http4s#1868]
Hi, I've noticed that using `QueryParamDecoderMatcher` in a HttpService returns a 404 for a missing param. I dont think this is quite right.

I think people expect a 400 bad request saying that the param is required. If I get a 404, I think I've got the path wrong. See also [this stackoverflow that suggests using 422](https://stackoverflow.com/questions/3050518/what-http-status-response-code-should-i-use-if-the-request-is-missing-a-required)

Im not sure if we want to introduce a breaking change to change this, maybe some people like it and are depending on the behaviour. But perhaps we could add a new Matcher similar to `ValidatingQueryParamDecoderMatcher` to do this. Or even just document the behavour and a alternative.

I'd like to work on this, Im looking for advice and support on what we should do.

Consider these examples
```scala
  "gives 404 on missing query param" >> {
    object NameQueryParamMatcher
        extends QueryParamDecoderMatcher[String]("name")

    val service = HttpService[IO] {
      case GET -> Root :? NameQueryParamMatcher(name) =>
        Ok(s"hello $name")
    }

    val getRoot = Request[IO](Method.GET, uri("/"))

    val io = service.orNotFound(getRoot)

    io.unsafeRunSync().status.code must beEqualTo(404) // would be better if it was bad request
  }

  "gives 400 on invalid query param manually parsed" >> {
     // how to achieve desired result by manually parsing the request.
    val service = HttpService[IO] {
      case req @ GET -> Root =>
        req.params.get("name") match {
          case None =>
            BadRequest("missing name")
          case Some(name) =>
            Ok(s"hello $name")
        }
    }

    val responseWithName =
      service.orNotFound(Request[IO](Method.GET, uri("/?name=cat")))
    responseWithName.unsafeRunSync().status.code must beEqualTo(200)

    val responseWithoutName =
      service.orNotFound(Request[IO](Method.GET, uri("/")))
    responseWithoutName.unsafeRunSync().status.code must beEqualTo(400)
  }

  "gives 400 on present but invalid query param" >> {
    implicit val yearQueryParamDecoder: QueryParamDecoder[Year] =
      QueryParamDecoder[Int].map(Year.of)

    object YQP extends ValidatingQueryParamDecoderMatcher[Year]("year")

    val service = HttpService[IO] {
      case GET -> Root :? YQP(y) =>
        y.fold(
          nelE => BadRequest(nelE.toList.map(_.sanitized).mkString("\n")),
          year => {
            Ok(s"hello $year")
          }
        )
    }

    val getRoot = Request[IO](Method.GET, uri("/?year=lastyear"))

    val io = service.orNotFound(getRoot)

    io.unsafeRunSync().status.code must beEqualTo(400)
  }
```

**Comment by rossabaker** [comment]
I'm not sure what I think here.  I don't think I like 422, which is for entities, which this is not. 

http://example.com/foo/?id=42

Is the resource the `foo` with id = 42 or is the resource the collection of `foo`s, filtered by id = 42?  What status would you return if there were no foo with ID 42?  What status would you return for `?id=syntacticallyInvalidForThisIdSpace`?

These questions lead me to being able to defend 400 or 404.  Since there is no entity involved, I find 422 harder to justify.

**Comment by stephennancekivell** [comment]
Yea I don't really like 422 either. But if you have a required param, 'id'
and that is missing, I think it should be 400 and say "param id is required
"

**Comment by rossabaker** [comment]
A plausible way that people could be depending on the current behavior:

```scala
    val service = HttpService[IO] {
      case GET -> Root / "foo" :? Id(id) =>
         getFoo(id).fold(NotFound())(Ok(_))
      case GET -> Root / "foo" =>
         // No filtering by ID, so show them all
         Ok(listFoos)
    }
```

Suppose we wanted to change that so the first case returns a 400 on missing id, or introduce a new base matcher for `Id`.  What would its `unapply` return?  It could return a `Validated[String, A]`, but then it's the right hand side's responsibilty to fold that into a `BadRequest` or a response.  It could throw an exception, but that would be very un-FP of us and compose terribly with other matchers.  I guess it could return an `F[A]` and raise error, but that's just as manual as the `Validated[String, A]`.

I think this is an interesting idea, but I'm not yet sure how it fits with an extractor DSL.  What do you think?

**Comment by rossabaker** [comment]
Right, the optional can be folded.  Or an alternative one that returned a `Validated` could be folded and contain the message for the `BadRequest`.  (Careful: echoing back information from the request is a vector for XSS attacks.  Something vague like `"missing name"` is good.)

A good example would be welcome in the docs.

I think making it less manual could be done with a directives-style DSL: those can raise an error in F instead of a sum type that requires folding.

**Comment by jmcardon** [comment]
Feel like it's obligatory to post the [OWASP Article on testing for reflected XSS](https://www.owasp.org/index.php/Testing_for_Reflected_Cross_site_scripting_(OTG-INPVAL-001)) which is what @rossabaker is talking about.

Sorry for the tangent, but yeah.
