### ISSUE TITLE
Logger middleware does not log in case a route is not found or error

### ISSUE THREAD

**Issue by vitorsvieira** [http4s/http4s#1871]
Hi all,

In case a request does not find a route, the logger middleware will not log.

Gitter knowledge:

- Right, because it needs to be matched. We could likely adapt it so that it logged on empty as well. Wouldn’t be that hard.
- It's awkward because we have to infer the response on unmatched or error. Well, we could always log the request. It's awkward for the response.
- Right, we could make request logging work certainly. I’m leaning towards either, forcing people to explicitly state what we assume happens with it, or not saying anything in these situations in middleware
- The two unhandled cases are None and raised error. Requests should be logged regardless.
And then response logger could either fake a 404 and (defaultErrorHandler orElse 500), or log something that reflects the lack of a response (at that level).

**Comment by aeons** [comment]
Can this be closed by #1879

**Comment by rossabaker** [comment]
Yes. :smile:
