### ISSUE TITLE
Requests from Client.fromHttpService do not include Host header

### ISSUE THREAD

**Issue by bpholt** [http4s/http4s#1872]
I added a `VirtualHost` middleware to a test service (so that I can test that the client is making its request to the right server). Requests made using `Client.fromHttpService` to the service do not include a `Host` header, so the middleware rejects them as bad requests. (Blaze-client’s `Http1Connection` has a `validateRequest` method that adds a `Host` header if it’s not already on the request, so this is not a problem for normal client requests.)

See also https://tools.ietf.org/html/rfc7230#section-5.4.

This was [discussed in gitter](https://gitter.im/http4s/http4s?at=5b072c863815f70bffd74741) and I suggested we have `fromHttpService` add a `Host` header if given a request with an absolute URI, and leave the current behavior alone for other requests for now. (I'm working on a PR to implement this.)

**Comment by aeons** [comment]
Closed in #1874
