### ISSUE TITLE
Incosistencies Between Json Encoding Content-Type Headers

### ISSUE THREAD

**Issue by ChristopherDavenport** [http4s/http4s#1878]
Argonaut places a Charset into the header for its encoder - [Argonaut Instance](https://github.com/http4s/http4s/blob/v0.18.11/argonaut/src/main/scala/org/http4s/argonaut/ArgonautInstances.scala#L38)

While Circe/Json4s does not apply the charset - [Circe Instance](https://github.com/http4s/http4s/blob/v0.18.11/circe/src/main/scala/org/http4s/circe/CirceInstances.scala#L72) - [Json4s Instance](https://github.com/http4s/http4s/blob/v0.18.11/json4s/src/main/scala/org/http4s/json4s/Json4sInstances.scala#L57). Is there a reason for this incosistency that I am unaware of? 

As this inconsistency might surprise folks switching between encoders if we want to pick a standard or identify why those differences exist that is likely a good thing for our users.

**Comment by rossabaker** [comment]
It's meaningless to add.  [Quoth the RFC](https://tools.ietf.org/html/rfc7159): 

>  No "charset" parameter is defined for this registration. Adding one really has no effect on compliant recipients.

On the other hand, if we're not explicit, `message.charset` will return `None`, which means we have to just guess when decoding to a String.  We don't want to be in the business of special casing in core every media type that internally defines its character encoding.

I strongly think we should be consistent, and weakly think we should leave it off.

**Comment by ChristopherDavenport** [comment]
Easy solution is to remove the content encoding from argonaut then.

**Comment by rossabaker** [comment]
I think we could target release-0.18.x with it.

**Comment by calvinbrown085** [comment]
I'd be happy to try this one out @rossabaker @ChristopherDavenport
