### ISSUE TITLE
Generalize middlewares

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#1890]
Most of our middlewares could be more parametric.

- By expanding `HttpRoutes` with `Http[F, G]`, the same middleware can be applied to either `HttpRoutes` or `HttpApp`.
- By expanding `Http[F, G]` to either `Kleisli[F, Request[G], B]` or `Kleisli[F, A, Response[G]]`, middleware that only affects one side can compose with Kleislis of different outputs or inputs.  The latter is particularly helpful for applying the same middleware to both regular and authorized HTTP functions.
- Increased parametricity makes it more clear what the middleware can do from the type alone.

This is a mostly mechanical translation, and would make a great first issue for anyone looking to better understand type classes and constraints.  If you claim a middleware and offer to submit a PR, I will help you if you get stuck.

Server:
* [x] AutoSlash.scala
* [x] ChunkAggregator.scala
* [x] CORS.scala
* [x] CSRF.scala
* [x] DefaultHead.scala
* [x] EntityLimiter.scala
* [x] GZip.scala
* [x] HSTS.scala
* [x] Jsonp.scala
* [x] Logger.scala
* [x] PushSupport.scala
* [x] RequestLogger.scala
* [x] ResponseLogger.scala
* [x] Timeout.scala
* [x] URITranslation.scala
* [x] UrlFormLifter.scala
* [x] VirtualHost.scala

Client:
* [x] FollowRedirect.scala
* [ ] Logger.scala
* [ ] package.scala
* [ ] RequestLogger.scala
* [ ] ResponseLogger.scala
* [ ] Retry.scala

**Comment by rossabaker** [comment]
Wow, I should ask for help before going to sleep more often!  This is great.

To make sure we're not duplicating work, please leave a comment here if you're grabbing one.

**Comment by SystemFw** [comment]
Yeah this is awesome 😄

**Comment by tomwadeson** [comment]
I'll pick up `VirtualHost` and `Timeout` 👍

**Comment by aworton** [comment]
Happy to have a go at Logger, RequestLogger and ResponseLogger

**Comment by akilegaspi** [comment]
I'm looking to work with generalizing the HTTP stuff into Kleisli

**Comment by somethingconcon** [comment]
grabbing PushSupport

**Comment by tomwadeson** [comment]
I'll take `CSRF`

**Comment by calvinbrown085** [comment]
I'd be happy to try `ResponseLogger.scala`

**Comment by rossabaker** [comment]
On further thought, I don't think there's anything to do on the client in the current design.  The server ones are a function of Kleisli to Kleisli, and we can be generic in any of its three parameters.  A `Client` only has one free parameter, and we're already polymorphic on that.

If we proceed with @ChristopherDavenport's idea of a `Client` being just a `Kleisli`, then there's something to do.  Until then, I think we're done here.

Am I talking nonsense?

**Comment by tomwadeson** [comment]
I stared blankly at the client middlewares for quite a while before deciding there was nothing for me to do there! 😁

**Comment by rossabaker** [comment]
Alright, then I think we're done here.

I'm very happy about the response we got.  Thanks to all who jumped in.  We'll try to make better use of the first-issue tag and continue this momentum with new contributors.
