### ISSUE TITLE
header.matchHeader matches raw, valid values of same name

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#1891]
[This](https://travis-ci.org/http4s/http4s/jobs/385490247#L3664) hurt #1887, which is breaking master and several other PRs that branched off the broken master. :fire:

```
[error] x header.matchHeader matches raw, valid values of same name (15 seconds, 1 ms)
[error]  Falsified after 70 passed tests.
[error]  > Falsified after 30 passed tests.
[error]  > ARG_0: Accept: 5z/*; eo="²;:¾B"; +cg=""; rW="¢"; 8|m="ÂÑU1", zb_l/*;q=0.301; +n_="d"; NnZ="msfnË"; K+="", TEXt/*, &/*;q=0.287; r="Y|Õeµ6"; Rae="Ò^}z", tMq|M/*;q=0.429; 8Y8=""; #9ZV="üçj"; Cg=""; p="Ëé¶Z"; f`Bw="", Ds&4U`/*;q=0
[error]  > Some(Accept: 5z/*; eo="²;:¾B"; +cg=""; rW="¢"; 8|m="ÂÑU1", zb_l/*;q=0.301; +n_="d"; NnZ="msfnË"; K+="", text/*, &/*;q=0.287; r="Y|Õeµ6"; Rae="Ò^}z", tMq|M/*;q=0.429; 8Y8=""; #9ZV="üçj"; Cg=""; p="Ëé¶Z"; f`Bw="", Ds&4U`/*;q=0) is Some but Accept: 5z/*; eo="²;:¾B"; +cg=""; rW="¢"; 8|m="ÂÑU1", zb_l/*;q=0.301; +n_="d"; NnZ="msfnË"; K+="", text/*, &/*;q=0.287; r="Y|Õeµ6"; Rae="Ò^}z", tMq|M/*;q=0.429; 8Y8=""; #9ZV="üçj"; Cg=""; p="Ëé¶Z"; f`Bw="", Ds&4U`/*;q=0 != Accept: 5z/*; eo="²;:¾B"; +cg=""; rW="¢"; 8|m="ÂÑU1", zb_l/*;q=0.301; +n_="d"; NnZ="msfnË"; K+="", TEXt/*, &/*;q=0.287; r="Y|Õeµ6"; Rae="Ò^}z", tMq|M/*;q=0.429; 8Y8=""; #9ZV="üçj"; Cg=""; p="Ëé¶Z"; f`Bw="", Ds&4U`/*;q=0 (HeaderLaws.scala:21)
```

**Comment by aeons** [comment]
I took a look into this. This pretty snippet generates the arg that fails the test:
```scala
val accept = Accept(NonEmptyList(
  MediaRange
    .parse("5z/*")
    .map(
      _.withExtensions(
        Map("eo" -> "²;:¾B", "+cg" -> "", "rW" -> "¢", "8|m" -> "ÂÑU1"))
        .withQValue(QValue.One)),
  List(
    for {
      mr <- MediaRange.parse("zb_l/*")
      q <- QValue.fromThousandths(301)
    } yield
      mr.withExtensions(Map("+n_" -> "d", "NnZ" -> "msfnË", "K+" -> ""))
        .withQValue(q),
    MediaRange.parse("TEXt/*").map(_.withQValue(QValue.One)),
    for {
      mr <- MediaRange.parse("&/*")
      q <- QValue.fromThousandths(287)
    } yield
      mr.withExtensions(Map("r" -> "Y|Õeµ6", "Rae" -> "Ò^}�z"))
        .withQValue(q),
    for {
      mr <- MediaRange.parse("tMq|M/*")
      q <- QValue.fromThousandths(429)
    } yield
      mr.withExtensions(
          Map("8Y8" -> "",
              "#9ZV" -> "üçj",
              "Cg" -> "",
              "p" -> "Ëé¶Z",
              "f`Bw" -> ""))
        .withQValue(q),
    MediaRange.parse("Ds&4U`/*").map(_.withQValue(QValue.Zero)),
  )
).sequence.right.get)
```

After doing all that I noticed that the diff in the two values is just `text/* != TEXt/*`. With my snippet, where I parse the MediaRange, `TEXt/*` is rendered as `text/*`. In `http4sGenMediaRange`, the MediaRange is created using the package private constructor, which just takes the main type verbatim, and thus allows differently cased strings.

```scala
object test extends App {
  val mr = "TEXt"
  println(new MediaRange(mr))
  println(MediaRange.parse(s"$mr/*"))
}
// MediaRange(TEXt/*)
// MediaRange(text/*)
```

Is the `Gen` wrong? I tried looking at the [RFC](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html), but couldn't see any references to casing.

Digging some more, [this](https://github.com/http4s/http4s/blob/ddf70f0f9ef979f143a355ae782dec2f6f84d416/core/src/main/scala/org/http4s/MediaType.scala#L263-L264) is where the parsed value is downcased.

I'm not sure what the right resolution is here :)

**Comment by rossabaker** [comment]
RFC 2045 says:
> All media type values, subtype values, and parameter names as defined are case-insensitive.

To be consistent with the rest of our model, we should be using `CaseInsenstiveString` for `mainType` and `subtype`.  But that's a breaking change.  (It's also kind of unpleasant to use, and we should have a talk about that before 1.0).

Should we change the .equals and .hashCode methods in 0.18?  Or downcase from the generator?

**Comment by aeons** [comment]
I thought that would be the case, but couldn't find the right RFC.

Downcase in generator imo, it's only generating wrong stuff because it's using a private constructor.
