### ISSUE TITLE
Import style

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#1897]
We have diverging import styles again:

* I reformatted everything by [Twitter import style](http://twitter.github.io/effectivescala/#Formatting-Imports) around the time we started enforcing scalafmt.
* Several users are using the default IntelliJ style, which groups Java and Scala separately.

My preferences are, in descending importance:
1. Low friction for new contributors
2. Consistency
3. The Twitter style, because it's much easier to automate across editors

@aeons is looking into whether we can check in an IntelliJ style that enforces the Twitter style out of the box.  If that doesn't work, we should squabble here, and then run a reset, because we're already inconsistent.

**Comment by rossabaker** [comment]
Oh, cool.  While I was bloviating, @aeons was fixing. See #1896.

**Comment by aeons** [comment]
I personally prefer the Twitter style, but it's not a big headache. I don't think most people really notice, but just stick with the default.
