### ISSUE TITLE
Configurable logging when no response is returned

### ISSUE THREAD

**Issue by bpholt** [http4s/http4s#1918]
We have an app that was relying on the behavior prior to #1875 / #1879 to pick and choose which `HttpService` were logged and which were ignored. (For this app, the routes corresponding to load balancer health checks are ignored, because they're pretty much just noise in the logs.) 

```scala
val loggedServices: HttpService[F] = ???
val healthCheck: HttpService[F] = ???

BlazeBuilder[F]
  .bindHttp(8080, "0.0.0.0")
  .mountService(server.middleware.Logger(logHeaders = true, logBody = true)(loggedServices) <+> healthCheck, "/")
  .serve
```

Unfortunately, with 0.18.12, this no longer works—now all the noisy requests are logged, along with a corresponding “service returned None.” Do you have any thoughts on supporting the old behavior via a flag on `Logger`? I think the intent of the changes was good, but maybe this use case was overlooked.

**Comment by rossabaker** [comment]
Sorry, this one slipped through the cracks.

This is addressed in master by only logging on `HttpApp`.  Any solution would be 0.18 only.  Adding a flag is not likely to be binary compatible.  Is there anything we can do, short of a copy and paste?

**Comment by bpholt** [comment]
Don't worry about the timing, if it was a higher priority I knew where to find you. 🙂

I'm not sure what you mean by a copy and paste. Do you mean duplicating the entire Logging middleware wholesale? If so, maybe I can just do that locally and not worry about it in 0.18. If not, could you elaborate?

I haven't really looked at the changes on master yet and couldn't figure out exactly what you meant about `HttpApp` from a brief browse-thru of the documentation. Could you elaborate a bit on that too, please?

**Comment by rossabaker** [comment]
Yes, I meant duplicating wholesale, if we couldn't figure out how to add the flag without breaking compatibility.

Does [this help](https://github.com/http4s/http4s/blob/183ab8193e285783127d5aab52ed4baecf7a299d/core/src/main/scala/org/http4s/package.scala#L22-L50) for `HttpApp`?

**Comment by rossabaker** [comment]
I _think_ this is obsolete since the middleware was parameterized?  If not, please reopen.
