### ISSUE TITLE
Tautological comparison in HeaderKey?

### ISSUE THREAD

**Issue by hgiddens** [http4s/http4s#1923]
Hi, this is probably a dumb mistake on my part but I was looking at the implementation of `matchHeader` in `HeaderKey.Internal`:

```
override def matchHeader(header: Header): Option[HeaderT] =
  header match {
    case h if runtimeClass.isInstance(h) =>
      Some(header.asInstanceOf[HeaderT])
    case Header.Raw(name, _) if name == header.name && runtimeClass.isInstance(header.parsed) =>
      Some(header.parsed.asInstanceOf[HeaderT])
    case _ =>
      None
  }
```

The if clause in the second case looks suspect to me: `Header.Raw` is a pretty ordinary case class whose first argument is a `val name`:

```
final case class Raw(name: CaseInsensitiveString, override val value: String) extends Header {
  // stuff that doesn't seem relevant here
}
``` 

So it's not clear to me that the `name == header.name` comparison can ever be false? Above the definition of `matchHeader` it defines a different `val name` and I wonder if perhaps that was meant to be used in the comparison instead? It looks like that was what was happening prior to 162962ff91d.

I'm not sure what effects this might actually have but it just looked odd to me.

**Comment by m-sp** [comment]
we now have a type class approach for headers, so this should no longer be relevant
