### ISSUE TITLE
Revert commit 65f9cf72da1a4ada once issue 192 resolves

### ISSUE THREAD

**Issue by bryce-anderson** [http4s/http4s#193]
We should revert commit 65f9cf72da1a4ada once issue #192 resolves. It would be a shame to pollute the logs so much all the time.

**Comment by rossabaker** [comment]
Logs at a level not enabled are free, for some generous definition of free.  I'd be surprised if you can measure a difference.

**Comment by bryce-anderson** [comment]
I'm not worried so much about the performance, but of polluting the logs. I actually plan to keep a few in there, and maybe downgrade them to trace, but I think this is an awful lot to fill the log books. On the other hand, if you think its a good idea to leave them thats fine by me though I would probably still downgrade them to trace.

**Comment by rossabaker** [comment]
Trace is fine.  Things lower than `info` are in my bucket of "things I
don't see unless things are on fire." :)

**Comment by bryce-anderson** [comment]
This has been addressed.
