### ISSUE TITLE
Circuit Breaker Middleware for http4s client

### ISSUE THREAD

**Issue by luisdeltoro** [http4s/http4s#1954]
I would be nice to have a middleware for the http4s client that would add circuit breaker functionality similar to the Akka Circuit Breaker (https://doc.akka.io/docs/akka/2.5/common/circuitbreaker.html)

It should be configurable with:
* maximum amount of failures: if this threshold is reached the circuit breaker will turn to open state.
* reset timeout: time after which the circuit breaker would turn to half open.
* call timeout: time after which the remote call will timeout.

Circuit Breaker States:
* Closed: Calls are let through except when maximum failures threshold is reached, then the state changes to Open.
* Open: Calls will fail fast without initiating a remote call.
* Half-Open: One call will be allowed through while others will fail fast. If the allowed remote call finishes successfully, the circuit breaker state will change to Closed, otherwise to Open.

**Comment by amarrella** [comment]
I agree, this would be really nice to have! Should we work on it first in cats-effect (there is a ticket open here https://github.com/typelevel/cats-effect/issues/206) and then base the middleware on that?

**Comment by luisdeltoro** [comment]
That would probably make sense. I'll about the status of that ticket

**Comment by luisdeltoro** [comment]
Apparently cats-effect 1.0.0 will come with a circuit breaker implementation based on the Monix one. So it probably does not make sense to implement it here.
Should we then close this ticket?

**Comment by rossabaker** [comment]
I love the idea but agree that cats-effect is the better place for it.
