### ISSUE TITLE
Create a dropwizard metrics middleware for the http4s client

### ISSUE THREAD

**Issue by luisdeltoro** [http4s/http4s#1959]
It would be nice a have a metrics middleware for the http4s client similar the existing one for the server.
This middleware would use codehale metrics library to gather metrics that can be sent, for example, to a Graphite backend. It would be the client equivalent of the 'server-metrics' subproject

This middleware should register at least:
* Number of active outgoing requests
* Timing of 1xx responses
* Timing of 2xx responses
* Timing of 3xx responses
* Timing of 4xx responses
* Timing of 5xx responses
* Number requests that timed out

**Comment by rossabaker** [comment]
See #1961

**Comment by luisdeltoro** [comment]
The idea of this metrics middleware is that uses dropwizard metrics library, so it can report metrics to, for example, graphite.
It would be the equivalent of server-metrics. Like #1961 is the client equivalent of prometheus-server-metrics.
Let me be a little bit more specific in the description.

**Comment by luisdeltoro** [comment]
@rossabaker don't you think that it would probably make sense to agree on a common set of metrics for consistency? Probably the metrics reported to Prometeus or to Graphite shouldn't differ that much.
Actually, if it's eventually agreed to implement the Dropwizard metrics middleware, it may make sense to refactor both middlewares and abstract the common parts away, right?

**Comment by rossabaker** [comment]
We tried to do that on the server implementations for dropwizard and prometheus, and it turned out that the code to call the common implementation was about as complicated as the common implementation.

I'd be up for trying to factor out a common layer on the client side of this, because I agree that it feels like the right thing to do, but I suspect we'll find the same as we did on the server.

Do you want to try to make an implementation, either standalone or on top of #1961?

**Comment by luisdeltoro** [comment]
Hi @rossabaker,
I've opened a pull request with an initial implementation for the Dropwizard metrics middleware (https://github.com/http4s/http4s/pull/1974). Would you mind having a look and providing some feedback?

Regarding the future abstraction of the dropwizard and prometeus middleware. What do you think about trying to use Free Monad or tagless final to abstract away the description of the computation and have specific interpreters for each metrics library?

**Comment by rossabaker** [comment]
That's an idea worth playing with.  Tagless final might be lighter weight.  I'm not yet 100% sure what it looks like in this context, but I'd be interested to see a prototype of it... or hear that it's a failed experiment.  Either way, we learn something.

**Comment by luisdeltoro** [comment]
That sounds good. I'll try to play around with it a little bit and see where it takes me. Do I need to create an issue for that or it's fine to do it without one?

**Comment by rossabaker** [comment]
Sure, it doesn't hurt to create another issue.  I think this issue is closed by #1974.

**Comment by luisdeltoro** [comment]
Cool, I've created a new issue for it: https://github.com/http4s/http4s/issues/2005
Let's see where it takes us! :)
