### ISSUE TITLE
UriTranslation.translateRoot behavior is misleading

### ISSUE THREAD

**Issue by howardjohn** [http4s/http4s#1962]
The `UriTranslation.translateRoot` middleware only checks the length rather than the contents. This should probably either be made private, changed, or documented to describe the behavior.

Context from Gitter:

> John Howard @howardjohn Jul 05 18:54
> What I am experiencing though is:
> ```scala
>   val A = HttpService[IO] { case GET -> Root => Ok("a") }
>   val B = HttpService[IO] { case GET -> Root => Ok("b") }
>   val C = HttpService[IO] { case GET -> Root => Ok("c") }
> 
>   val service = URITranslation.translateRoot("a")(A) <+>
>     URITranslation.translateRoot("b")(B) <+>
>     URITranslation.translateRoot("other")(C)
> ```
> Then doing curl on `/a, /b, /other, /, /fake, /q`. I would expect these to output `a, b, c, 404, 404, 404`. The actual output I am getting is `a, a, c, a, c a`. It seems like it only actually checks the length of the Uri not the contents?
> 

> Ross A. Baker @rossabaker Jul 06 07:51
> @howardjohn You're right, it does do a length check. I thought it was a prefix check. It's usually used in the router, where the prefix is aleady checked. So it's an optimization there, but not good for standalone. We should reconsider this.

I would be able to make this change if you indicate which direction we should take

**Comment by rossabaker** [comment]
Thanks, @howardjohn!

So `UriTranslation` needs to check the prefix.  That would fix the bug.

`Router` would then be [duplicating the prefix check](https://github.com/http4s/http4s/blob/release-0.18.x/server/src/main/scala/org/http4s/server/Router.scala#L34).  It might not be that expensive, but to save every nanosecond, we could just have that inline the former logic of `translate` to lop off the known number of characters.

I think all this can be done on release-0.18.x, and we can release it as a patch.
