### ISSUE TITLE
Support multiple connectors with independent service mounts

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#197]
With metrics support coming very soon, it's good practice to have admin functionality on a separate port.  (Dropwizard gives a nice out-of-box example of this.)

**Comment by bryce-anderson** [comment]
For the blaze backend, this will require blaze-core work. Its easy enough to just spin up another server if thats what we want. There will be an asymmetry between NIO1 and NIO2: NIO1 will require a new thread pool (could be 1 thread, admin shouldn't be that heavy) while the NIO2 backend could share an ```AsynchronousChannelGroup``` to preserve resources. 
I believe the servlet backends already support this feature and its just a matter of adding it to the builders? This reminds me of the old question of 'how much do we want to pack into the builders'.

**Comment by bryce-anderson** [comment]
Lucky enough, it seems blaze NIO1 support can also share a ```SelectorLoopPool``` though this feature is entirely untested, but should work without issue.

**Comment by rossabaker** [comment]
Yes, it's a builder issue for the servlets.

I wasn't too excited about this before we started exposing metrics.  Now it makes a great deal of sense to have the adminy type of stuff on its own port.

**Comment by rossabaker** [comment]
Is there any reason not to just spin up two Blaze servers concurrently for this use case?  I think maybe we can let this one go.

**Comment by jmcardon** [comment]
:+1: on closing this
