### ISSUE TITLE
http4s banner may be displayed incorrectly

### ISSUE THREAD

**Issue by pshirshov** [http4s/http4s#1980]
Seems like the operation order is not defined:

```
I 2018-08-08T13:24:21.273+01:00[Europe/Dublin] ...nsportTest:1  (BlazeBuilder.scala:281)   _   _   _        _ _     
D 2018-08-08T13:24:21.275+01:00[Europe/Dublin] ...ector-0-0:12  (SelectorLoop.scala:122) Channel initialized.
I 2018-08-08T13:24:21.275+01:00[Europe/Dublin] ...nsportTest:1  (BlazeBuilder.scala:281)  | |_| |_| |_ _ __| | | ___
I 2018-08-08T13:24:21.277+01:00[Europe/Dublin] ...nsportTest:1  (BlazeBuilder.scala:281)  | ' \  _|  _| '_ \_  _(_-<
I 2018-08-08T13:24:21.278+01:00[Europe/Dublin] ...nsportTest:1  (BlazeBuilder.scala:281)  |_||_\__|\__| .__/ |_|/__/
I 2018-08-08T13:24:21.279+01:00[Europe/Dublin] ...nsportTest:1  (BlazeBuilder.scala:281)              |_|
```

**Comment by aeons** [comment]
Does this happen consistently?
I don't think we can really control the order of log statements from different places.

**Comment by pshirshov** [comment]
From time to time.
You can't control but you may print the whole banner in one message. Or just remove it.

**Comment by ChristopherDavenport** [comment]
I like our banner, it looks nice and only appears once on server start. I'm very against its removal. There is the possibility of conflicting log messages, however that is just a reality about logging. 

If you set the banner in the blaze builder to an empty List or Vector this will mute the banner for you - https://github.com/http4s/http4s/blob/master/blaze-server/src/main/scala/org/http4s/server/blaze/BlazeBuilder.scala#L68

**Comment by rossabaker** [comment]
What happens if we `mkString("\n")` it?  Most log formats aren't going to indent the subsequent lines properly, I suspect?  If it had a leading newline, it might work.

**Comment by pshirshov** [comment]
Yup, you may use multiline output and add a leading newline. That would work.

**Comment by rossabaker** [comment]
Would you be interested in submitting a PR?

**Comment by pshirshov** [comment]
Okay, will do.
