### ISSUE TITLE
CSRF to handle url parameter/manually fed token

### ISSUE THREAD

**Issue by jmcardon** [http4s/http4s#1989]
So while creating a websocket service, you want to prevent [CSWSH](http://www.christian-schneider.net/CrossSiteWebSocketHijacking.html).

Solution 1 is checking origin, and that can be done in userland no problem.

Soultion 2: Our CSRF service would work for this, _except that_ clients have to use javascript to embed the locally cached token into the request... which isn't possible with the native client websocket interface.

The solution to this, of course, is that sending the token in a url parameter or as a `/<token>` part of the url itself (especially for WSS) in a similar way to CSRF, is effective enough when the tokens themselves are generated securely with enough entropy.

I already have a sketched out solution in a private repo (this is using `TSecCSRF`, but same thing for ours in this repo)

```scala
  private[this] def checkCSRF(
      token: String,
      r: Request[IO],
      f: => IO[Response[IO]]
  ): IO[Response[IO]] =
    (for {
      c    <- cookieFromRequest(csrf.cookieName, r)
      raw1 <- csrf.extractRaw(CSRFToken(c.content))
      raw2 <- csrf.extractRaw(CSRFToken(token))
      res <- if (csrf.isEqual(raw1, raw2))
        OptionT.liftF(f)
      else
        OptionT.none[IO, Response[IO]]
      newToken <- OptionT.liftF(csrf.signToken(raw1))
    } yield res.addCookie(Cookie(name = csrf.cookieName, content = newToken)))
      .getOrElse(Response[IO](Unauthorized))
```

All is left is for either me or someone that beats me to it to add it to the `CSRF` class.

**Comment by jmcardon** [comment]
so you don't evaluate it if the csrf check fails

**Comment by jmcardon** [comment]
@rossabaker the above block is for specific actions.

You can also generalize it to a query parameter if you decide you have a bunch of websocket routes grouped together and do it that way.

**Comment by rossabaker** [comment]
I can't think of other places we lazily create the effect, whose interesting parts are already thunked.  I guess it does prevent computation of the effect on the unhappy path.  `=> IO` just stood out to me as an unusual signature.

**Comment by jmcardon** [comment]
I mean, if you want, we can ignore the thunked portion really. I copy pasted that from my impl, in where I used `def`s for the sake of not computing the data structure in case the check failed, but it's a minor implementation detail that buys you some efficiency.

This is a hill I won't die on, if you want it to be strict.
