### ISSUE TITLE
fs2-1.0.0-M4 upgrade

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#1990]
We want to upgrade to fs2-1.0.0-M4 before the next 0.19 milestone.

* [ ] jawn-fs2 (need to release again for fs2-1.0.0-M4)
* [ ] zainab-ali/fs2-reactive-streams#51
* [ ] fix compilation failures in http4s

**Comment by SystemFw** [comment]
Is the fs2-reactive-streams stuff on a branch somewhere?

**Comment by rossabaker** [comment]
No.  All I did was upgrade the build and hope for the best.  Do you want to take a crack at it?

**Comment by SystemFw** [comment]
Yeah I can have a look :)

**Comment by rossabaker** [comment]
Bumping this from M3 to M4 due to the fs2-reactive-streams issue.

**Comment by rossabaker** [comment]
Ticket checklist out of date, superseded by milestone.
