### ISSUE TITLE
shutdown

### ISSUE THREAD

**Issue by KhagayN** [http4s/http4s#1992]
Is there a way I can watch for when the http server is shutdown and log a message once that happens?

**Comment by rossabaker** [comment]
If you're calling `.serve` on your `ServerBuilder`, you can add `.onFinalize(IO(logger.info("Bye"))` to it.

If you'e calling `.start`, you can `server.shutdown <* IO(logger.info("Bye")` where you shut it down.

It might not be a bad idea to add a log message [here](https://github.com/http4s/http4s/blob/77c094ab6be8dd78ac6a40f751187b265d64299d/blaze-server/src/main/scala/org/http4s/server/blaze/BlazeBuilder.scala#L262), so everyone gets it out of the box.
