### ISSUE TITLE
Client's Retry with empty body 

### ISSUE THREAD

**Issue by maxkorolev** [http4s/http4s#1999]
I found strange code, is this bug or feature?
Why new attempt occurs with empty body in case of failure?

https://github.com/http4s/http4s/blob/9655331c743ca91326c94bd98730f2a3f382415a/client/src/main/scala/org/http4s/client/middleware/Retry.scala#L62

**Comment by rossabaker** [comment]
Back in the scalaz-stream days, we could introspect the stream and determine whether the body was pure, and safely resubmit the same request body.  Now that the algebra is hidden from us, we don't have this guarantee.  Accordingly, the [default retry policy is more restrictive now](https://github.com/http4s/http4s/blob/03304e031607d30eb076d3bc5797a4d7e9260e1b/client/src/main/scala/org/http4s/client/middleware/Retry.scala#L105-L110), and we only retry methods without a body.  So the line in question doesn't change the default policy.

But `unsafeRetriable` is _usually_ going to be safe.  The vast majority of request bodies are pure, or some other probably benign effect (i.e., reading from a disk).  And if the user opts into this policy, then the expectation is that the body is resubmitted.   It's probably going to be fine, and if it's not, we [did warn them](https://github.com/http4s/http4s/blob/03304e031607d30eb076d3bc5797a4d7e9260e1b/client/src/main/scala/org/http4s/client/middleware/Retry.scala#L120-L122).

I propose that on release-0.18.x branch, we `prepareLoop` with `req`.  I propose that on master, the `unsafeRetriable` becomes the default policy and the default policy becomes something labelled more conservative.

**Comment by ChristopherDavenport** [comment]
Could this as written result in the `ContentLength` being reported as a different size then the actual body? Since we have modified the body but not the length?

**Comment by rossabaker** [comment]
No, `withEmptyBody` removes payload headers.

But it's a slight risk after the bug fix resubmit.  I don't think any of our backends will send too many bytes, but they could send not enough.  Imagine `req.withBody(file)`, if the `file` shrinks.

**Comment by maxkorolev** [comment]
Thanks for reply! I see your point about effects, but I think user understands that if request requires complicated environment or makes big changes in the world, then in case of retry it will be repeated.

I think that it would be nice, if we just removed default "retriable". So user will read caution and will peek right solution.

**Comment by rossabaker** [comment]
I'm inclined to agree.  I would prefer `unsafeRetriable` 100% of the time over `defaultRetriable`.  Maybe rename `unsafeRetriable` to `defaultRetriable`, and leave a deprecated from `unsafeRetriable` to `defaultRetriable` so people who were using it get assistance migrating?

**Comment by maxkorolev** [comment]
Actually, I am using my own `retriable`, because imho it's very user specific, that's why I think we should avoid default value here to lightly push users to decide themselves such politics.

About renaming, not good surprise for somebody. I am not sure that everyone uses `deprecation warning` compiler's flag. 
Well, that's just my thought.

**Comment by rossabaker** [comment]
Fixed by #2001

**Comment by rossabaker** [comment]
Actually, reopening so we modify retriable.  But the bug is fixed and will be released in 0.18.17.
