### ISSUE TITLE
Need a logo

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#200]
With all due respect to the artistic talents of @bryce-anderson, he is a hell of an engineer.

Any creative types out there want to make us a logo?

**Comment by mdedetrich** [comment]
I might look into it

**Comment by rossabaker** [comment]
To tie into the Typelevel theme, maybe something like [this](https://www.figma.com/file/Sit0pHi1XSgPLCEmtgnK7Kvm/http4s)?

/cc @reactormonk

**Comment by rossabaker** [comment]
I think @trepidacious has a winner: https://www.figma.com/file/PGwrDeNCMK81IDyLI6IzT2/http4s-logo.  We discussed shading tweaks on Gitter to match the Typelevel logo, but I love the concept.

I think the orange is good.  It's a subtle nod to blaze.
