### ISSUE TITLE
Factor a common layer for client metrics

### ISSUE THREAD

**Issue by luisdeltoro** [http4s/http4s#2005]
There is two standalone implementations for client metrics on Htttp4s, one for prometeus metrics and one for dropwizard metrics.
It would be nice to try to get an abstraction that can deal with both implementations, hopefully removing duplication and enhancing long-term maintainability.

**Comment by rossabaker** [comment]
As mentioned before, I tried this and failed server side.  As mentioned before, I'd love to see another attempt, because it still seems like a good idea.

**Comment by luisdeltoro** [comment]
Hi @rossabaker,

I have a draft implementation of this issue. It can be found here: https://github.com/luisdeltoro/http4s/tree/CommonLayerClientMetrics_%232005/client-metrics/src

If you like the solution and think that it's worth committing I would clean up the branch, which still contains the other prometheus-client-metrics project and run it through scala format etc..

At the end, I'm using type classes to abstract the common layer that both implementations share.
From my point of view the code reads now more easily and it has the advantage of allowing other developers to easily provide typeclasses implementations for their metrics framework of choice.
I have added tests for both implementations to make sure, I did not brake anything.

Please let me if you think this is heading in the right direction.

**Comment by rossabaker** [comment]
I think the approach is generally nice.  I see that a lot of the operations on `MetricsOps` are being `Sync.delay`'ed.  It would make more sense to me to keep the `MetricsOps` pure and return an `F` context.

This is tangentially related to #2053, where there's a listener interface for events that feed into metrics.  I think the right approach may end up having some similarities here.

**Comment by luisdeltoro** [comment]
Hi @rossabaker,

I've changed the MetricsOps so it returns always an context F.

Regarding your second comment. I'm not sure I fully understand it. Do you mean that you would prefer that I convert MetricsOps to some kind of listener for events?

Maybe something like:
trait RequestListener[F[_]] {
  def requestInitiated(destination: Option[String]): F[Unit]
  def headersReceived(destination: Option[String]): F[Unit]
  def BodyConsumed(destination: Option[String]): F[Unit]
}

Or are you more referring to the fact of making the publishing of metrics asynchronous by getting it to run on another Fiber?

**Comment by rossabaker** [comment]
I don't think it should be async publishing.  All of these calls should be very quick.  It _could_ be async publishing if the interpreter takes a `ContextShift`, but this would almost always be a bad idea.

I think we either want to publish the timestamps as part of the events if it's a "listener", or calculate the elapsed time and pass that, as you were originally doing.  I don't have a strong opinion on that.  I guess see what feels more right to you, and we can examine it on a PR.

**Comment by luisspringernature** [comment]
Hi @rossabaker,
I would, for the time being, stick to the approach of calculating the elapsed time and passing that, as it is more consistent with the way the server metrics are gathered.

I will prepare the PR and send it to. But before that, I would have one more question:
Would you like to have all metrics implementations in one project (client-metrics) like it's right now in my branch?
Or would actually prefer that I separate them into 3 different projects, something like:
client-metrics-core, client-metrics-prometheus, client-metrics-dropwizard?

**Comment by luisdeltoro** [comment]
Hi @rossabaker,
I would, for the time being, stick to the approach of calculating the elapsed time and passing that, as it is more consistent with the way the server metrics are gathered.

I will prepare the PR and send it to. But before that, I would have one more question:
Would you like to have all metrics implementations in one project (client-metrics) like it's right now in my branch?
Or would actually prefer that I separate them into 3 different projects, something like:
client-metrics-core, client-metrics-prometheus, client-metrics-dropwizard?

**Comment by luisdeltoro** [comment]
Sure, that's what I though too. All do that then

**Comment by luisdeltoro** [comment]
Hi @rossabaker,

I've opened a PR with the agreed changes: https://github.com/http4s/http4s/pull/2094

Let me know if there is still something to be changed.

Best,

Luis

**Comment by luisdeltoro** [comment]
A follow-up task has been created to try to do a similar job on the server metrics metrics: https://github.com/http4s/http4s/issues/2131
