### ISSUE TITLE
Origin header is a well defined triple

### ISSUE THREAD

**Issue by jmcardon** [http4s/http4s#2007]
Origin can be stated as:

```haskell
data Origin = Empty | Origin Scheme Host (Maybe Port)
```
Currently it's a `RawHeader`, which is wrong.

**Comment by davegurnell** [comment]
I'll take a look at this one...

**Comment by davegurnell** [comment]
I've been going through this with @hosamaly. We have a first draft of the header in this branch of my fork:

https://github.com/davegurnell/http4s/tree/topic/origin-header

Our parser breaks some tests in `CORSSpec`. These tests specify an Origin header with a trailing slash, which is technically not valid according to the spec:

http://tools.ietf.org/html/rfc6454#section-7

We *cooouuuld* take a permissive parsing approach, accept trailing slashes, and silently drop them. Or we could hold fast to the spec and edit the CORS tests. What do folks think?

(We also need to modify our code to accept a list of hosts in the Origin header, which is also technically part of the spec.)

**Comment by rossabaker** [comment]
I think it would be reasonable to hold fast to the spec here and change the tests.

**Comment by davegurnell** [comment]
Aces. In that case, here comes a PR...
