### ISSUE TITLE
Identify headers with a default model, and then model them.

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#2011]
Headers that extend `HeaderKey.Default` should have a case class that models them as something more than a String.  This task involves:

- Enumerating such headers, with link to relevant RFC.
- For each one, interpreting the RFC into a case class and writing the parser.

This, like the recent middleware reform, will be a source of good first issue tickets.

**Comment by rossabaker** [comment]
Here is a list of headers we have declared a key for, but not modeled:

```scala
object `Accept-Patch` extends HeaderKey.Default
object `Access-Control-Allow-Credentials` extends HeaderKey.Default
object `Access-Control-Allow-Headers` extends HeaderKey.Default
object `Access-Control-Allow-Methods` extends HeaderKey.Default
object `Access-Control-Allow-Origin` extends HeaderKey.Default
object `Access-Control-Expose-Headers` extends HeaderKey.Default
object `Access-Control-Max-Age` extends HeaderKey.Default
object `Access-Control-Request-Headers` extends HeaderKey.Default
object `Access-Control-Request-Method` extends HeaderKey.Default
object `Content-Base` extends HeaderKey.Default
object `Content-Language` extends HeaderKey.Default
object `Content-Location` extends HeaderKey.Default
object `Content-MD5` extends HeaderKey.Default
object `Content-Security-Policy` extends HeaderKey.Default
object `Content-Transfer-Encoding` extends HeaderKey.Default
object Expect extends HeaderKey.Default
object From extends HeaderKey.Default
object `Front-End-Https` extends HeaderKey.Default
object `If-Match` extends HeaderKey.Default
object `If-Range` extends HeaderKey.Default
object `If-Unmodified-Since` extends HeaderKey.Default
object `Max-Forwards` extends HeaderKey.Default
object Origin extends HeaderKey.Default
object Pragma extends HeaderKey.Default
object `Proxy-Authentication` extends HeaderKey.Default
object `Proxy-Authorization` extends HeaderKey.Default
object `Sec-WebSocket-Accept` extends HeaderKey.Default
object `Sec-WebSocket-Key` extends HeaderKey.Default
object `Sec-WebSocket-Key1` extends HeaderKey.Default
object `Sec-WebSocket-Key2` extends HeaderKey.Default
object `Sec-WebSocket-Location` extends HeaderKey.Default
object `Sec-WebSocket-Origin` extends HeaderKey.Default
object `Sec-WebSocket-Protocol` extends HeaderKey.Default
object `Sec-WebSocket-Version` extends HeaderKey.Default
object Server extends HeaderKey.Default
object TE extends HeaderKey.Default
object Trailer extends HeaderKey.Default
object Upgrade extends HeaderKey.Default
object Vary extends HeaderKey.Default
object Via extends HeaderKey.Default
object Warning extends HeaderKey.Default
object `WebSocket-Location` extends HeaderKey.Default
object `WebSocket-Origin` extends HeaderKey.Default
object `WebSocket-Protocol` extends HeaderKey.Default
object `X-Content-Type-Options` extends HeaderKey.Default
object `X-Forwarded-Proto` extends HeaderKey.Default
object `X-Frame-Options` extends HeaderKey.Default
object `X-Powered-By` extends HeaderKey.Default
object `X-Requested-With` extends HeaderKey.Default
```

`Referer` is a fairly clean example of a modeled header: it has a case class `org.http4s.headers.Referer` and you can trace how the parser hooks in from there.

The way headers are registered is under review in the more ambitious #1143, but the parsers themselves will still be useful even if they move before 1.0.

**Comment by CucumisSativus** [comment]
I'll gladly take this one if you don't mind

**Comment by ChristopherDavenport** [comment]
I would be inclined to tackle one at a time, which one are you looking to take on first?

**Comment by CucumisSativus** [comment]
Okay so let me start with AcceptPatch!

Dnia czw., paź 25, 2018 o 16:39, Christopher Davenport <notifications@github.com> napisał:

**Comment by calvinbrown085** [comment]
I can take `Access-Control-Max-Age`

**Comment by nelusnegur** [comment]
I'm going to take `Access-Control-Allow-Headers`.

I don't know what is the status with the Accept-Patch as there is a comment from 2018; if there is no progress there, I could take it.

Also, maybe we could create a small table with columns: header, modeled/done, PR link, for an easier tracking? If you think it's a good idea, I can create it as a comment in this issue and afterwards it could be updated.

**Comment by amitrai48** [comment]
I will pick `Access-Control-Allow-Methods`. Haven't seen any comments for picking it.

**Comment by cquiroz** [comment]
A table would be great, I was trying to
Tackle these in alphabetical order but I haven’t had time lately

**Comment by rossabaker** [comment]
@amitrai48 Sounds great!

I converted the list above to a checklist.  I'll try to keep that current as they're claimed.  It's possible I missed some: if you get there, and it doesn't extend `HeaderKey.Default`, please come back for another!

**Comment by amitrai48** [comment]
Hi all, I would like to pick `Content-Language`.

**Comment by nelusnegur** [comment]
I would like to pick `Access-Control-Expose-Headers`.

**Comment by rossabaker** [comment]
This got cleaned up in the Header remodel.  A few that had a default model disappeared, but we can handle those on a case-by-case basis.
