### ISSUE TITLE
jetty-client

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#2013]
In addition to server, jetty provides a client.  An http4s-jetty-client backend could provide us our first asynchronous, HTTP/2 client.

This is an ambitious first issue, but there is a lot of prior art with three other client backends.

**Comment by marcodippy** [comment]
hey @rossabaker, if nobody's already working on this I would be happy to take a stab at implementing it (since I'm not an expert I might need some guidance) :)

**Comment by rossabaker** [comment]
I am not aware of anybody else working on it.  I would look at the async-http-client and okhttp-client backends for inspiration.  The hardest part is going to be to map the bodies to an `fs2.Stream`.  I don't think either does it in exactly the way you'll need to do it here.

If you get stuck, please ask for help here or on Gitter, and someone will be glad to assist!
