### ISSUE TITLE
Look at other middleware for inspiration

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#2014]
Let's look at other languages and see what we're missing.  Many of them are trivial, and it's a great way to make a first contribution to the project.  If you see one that you'd like, add it here.  And better yet, grab it.  We're here to help.

- [Ruby](https://github.com/rack/rack/wiki/List-of-Middleware)
- [Haskell](http://hackage.haskell.org/packages/search?terms=wai-middleware) and [more Haskell](http://hackage.haskell.org/package/wai-extra)

**Comment by gstro** [comment]
Would there be interest in something like a `ResponseTimer` middleware, similar to express.js' [response-time](https://expressjs.com/en/resources/middleware/response-time.html)? Could use [cat's `Clock`](https://github.com/typelevel/cats-effect/blob/master/core/shared/src/main/scala/cats/effect/Clock.scala).

**Comment by rossabaker** [comment]
Would this be different than the existing Prometheus Metrics and Dropwizard Metrics integrations?  Also see #2131, for making a common metrics implementation with library-specific interpreters.

**Comment by gstro** [comment]
Oh nice! I think my intention would be another "Simple middleware" like `HeaderEcho` for basic timing info without external metrics integrations. If those metrics are sufficient, I can look into other middleware to add.

**Comment by rossabaker** [comment]
You mean like a middleware that returns an `X-Response-Time` header?  I think this might be possible after #2131: instead of writing to a metrics backend, produce a header.

**Comment by rossabaker** [comment]
The existing work has been on the client.  The other ticket is to do similar for the server.  Since the MetricsOps operations return `F[Unit]`, I'm not sure it would work for a response header.

**Comment by rossabaker** [comment]
I'm open to it.  One thing we struggled with on the server metrics: is response time the time until the header, or time until the entire response body is created?  Both can be useful.  You'll want to make clear what's being measured.

**Comment by nebtrx** [comment]
@rossabaker would you be interested in a **Http Method Overrider** middleware (kinda like the [Python's Django](https://pypi.org/project/django-method-override/))?

**Comment by rossabaker** [comment]
@nebtrx Yes, that has proven useful in other languages.

**Comment by nebtrx** [comment]
> @nebtrx Yes, that has proven useful in other languages.

Cool! I just pushed a PR with that purpose. Please take a look at it and let me know how it goes.

**Comment by rossabaker** [comment]
We got a couple out of this.  I think it's served its purpose, but please don't hesitate to bring more useful ones.
