### ISSUE TITLE
Interest in a vert.x backend?

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#2016]
@eklavya and @jmcardon have mentioned vert.x on the channel recently.  The project has a sterling reputation for performance, and could make an interesting backend for us.

I'd probably rather see #1831 helped across the finish line first, rather than a backend on top of a backend on top of Netty.  But it's supposedly fast.

Opening a ticket to gauge interest, or vocal disinterest.

**Comment by rossabaker** [comment]
This should live in a separate repo if anyone acts on it.

**Comment by armanbilge** [comment]
No comments over several years. Closing because we have 300 other open issues but we can certainly make a repo if someone wants to work on it.
