### ISSUE TITLE
EntityEncoder and EntityDecoder: yea or nay

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#2017]
Pro:
- We've had them since the beginning, and eliminating them would be a massive change
- They're really pleasant where there is a canonical encoding to `Stream[F, Byte]`.
- They promote a DSL that is generally well liked: `Ok(foo)` and `req.as[Foo]`.

Con:
- Incoherence: there is no canonical encoding for many types.
  - JSON with or without spaces
  - JSON vs. other formats
  - `InputStream` chunk sizes
- Calling with explicit instances is ugly in both principle and syntax

I'm finding them increasingly dubious as typeclasses, but have yet to see an ergonomic replacement for them.  Let's hear some alternatives and apologetics.

**Comment by jcranky** [comment]
You mean you want to replace them, or perhaps completely remove them? I find it very handy not having to write my own `Entity{E/D}` for "obvious" types. Maybe offer them as a separated library?

**Comment by rossabaker** [comment]
I don't want to remove them without something that's clearly better, but I'm souring on the idea of codecs as typeclasses.  I'm hoping to discover a better idiom here.

**Comment by jmcardon** [comment]
I'm :+1: on their removal.

My idea is a tad more verbose I think. I think `EntityEncoder` ++ the dsl does quite a lot. It not only defines the common serialization you want,  but it also sets headers and the whatnot.

I.e, I wouldn't mind something like (note this could look different but bear with me)

```scala
object CirceEncoder {
 def embedJson(j: io.circe.Json, r: Response[IO]): Response[IO]
}
```

and calling `Ok().map(embedJson(_, someJson))`

You might get strong disagreements with this, but consider that `EntityEncoder` currently:
- Is pure, or can be effecting? There's no single canonical answer here, we changed it but there's uses in both.
- has a static headers field, which is annoying AF with multipart and _any other body_ that requires headers set based on the entity instance itself (so RIP setting headers if you wanted to say, have a custom entity encoder for some coproduct type).
- Content length debacle we talked about before

Similarly `EntityDecoder`:
- is generic over requests and responses, but they're not exactly symmetric entities (esp w.r.t headers present)

(the entitydecoder stuff is off the top of my head).

Really, the biggest pain is the scalafix for users that wrote a lot of code in terms of the DSL, but if not for 0.19 then for 1.0 or 2.0, I don't think the way forward is what a typeclass used not unlike an implicit conversion, which is what we have now. 

explicit serialization makes sense in many situations honestly, and calling a function isn't the worst thing in the world, people get used to it (i.e haskell calling `show a` for composing strings, I don't hear many complaints about it)

**Comment by jmcardon** [comment]
From chatting on gitter, my other proposal, assuming everyone finds the above a death sentence, is

```scala
EntityEncoder[F[_], A] {
  def encode(m: Message[F], a: A): F[Message[F]]
 //or Ross' alternative
 // def encode(m: Message[F], a: A): Message[F]
}
```

**Comment by rossabaker** [comment]
I haven't successfully eliminated these over a few attempts.  I think they're here to stay.
