### ISSUE TITLE
scala-2.13.0

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#2025]
1. Publish our internal dependencies.
2. Identify which of our external dependencies are published.
2. Once they all are, publish.

Recommend we begin this exercise with 2.13.0-M5.

Our monorepo is going to mean we're at the tail end of this, which is why we haven't even tried yet.

**Comment by rossabaker** [comment]
There is no scalacheck-2.13.0-M5 yet, and cats-1.3.0 looks like it will ship on 2.13.0-M4.  We might want to target M4 instead, though it's sad to start out a step behind.  The value is that we can see what breaks.

**Comment by SethTisue** [comment]
many more of your dependencies have now published for 2.13.0-M5

maybe it's time to take a fresh whack at this, see what's missing, and see what other maintainers we should go (politely) pester...?

**Comment by aeons** [comment]
Currently core has two dependencies that have no 2.13.0-M5 release:

- log4s, which builds on 2.13, but just needs a release ([issue here](https://github.com/Log4s/log4s/issues/29))
- Our shapeless-less fork of parboiled [http4s/parboiled2](https://github.com/http4s/parboiled2), which only needs a few fixes and a release

With those published locally, I'm running into some issues with `scalacOptions` that are no longer supported, but I can't figure out where in the build they are set. Will continue investigating.

**Comment by rossabaker** [comment]
scalacOptions are set by sbt-tpolecat.  It's possible that needs a bump or a fix.  A nice thing about sbt-tpolecat is it should give us reasonable flags out of the box for crossbuilds.

**Comment by aeons** [comment]
Where is sbt-tpolecat added to the build? I couldn't find it in plugins.sbt

**Comment by ChristopherDavenport** [comment]
It comes in through sbt-rig

**Comment by rossabaker** [comment]
It should be overridable if there's a new version.

Worst case, scalacOptions can be tweaked post-plugin.

**Comment by SethTisue** [comment]
I opened https://github.com/DavidGregory084/sbt-tpolecat/issues/5

**Comment by aeons** [comment]
I opened https://github.com/http4s/parboiled2/pull/5

The build failure looks like some issue with string comparisons. If anyone wants to take a look at it, feel free.

**Comment by SethTisue** [comment]
fixed in sbt-tpolecat 0.1.5, according to 
https://github.com/DavidGregory084/sbt-tpolecat/issues/5#issuecomment-460854726

**Comment by aeons** [comment]
I opened https://github.com/Verizon/sbt-rig/pull/25 to get it into our build as well.

**Comment by rossabaker** [comment]
I approved that, but the Verizon infrastructure for rig is gone, and that project hasn't been ported to the Nelson org yet.  Can we just override the plugin version here to keep things moving?

**Comment by aeons** [comment]
Yep, I have a branch I'm working on. Will get it pushed soon
