### ISSUE TITLE
g8 templates for version 0.19.0-x fail compie

### ISSUE THREAD

**Issue by kayvank** [http4s/http4s#2031]
Here are the steps:
-  sbt -sbt-version 0.13.15 new http4s/http4s.g8
-  select 0.19
cd quickstart
sbt compile
`
quickstart/src/main/scala/com/example/quickstart/HelloWorldServer.scala:19:18: IO takes no type parameters, expected: one
[error]     BlazeBuilder[IO]
[error]                  ^
[error] /home/kayvan/tmp/quickstart/src/main/scala/com/example/quickstart/HelloWorldServer.scala:21:21: diverging implicit expansion for type cats.effect.Effect[F]
[error] starting with method catsWriterTEffect in object Effect
[error]       .mountService(helloWorldService, "/")
[error]                     ^
[error] /home/kayvan/tmp/quickstart/src/main/scala/com/example/quickstart/HelloWorldServer.scala:11:83: class IO takes type parameters
[error]   def stream(args: List[String], requestShutdown: IO[Unit]) = ServerStream.stream[IO]
[error]                                                                                   ^
[error] three errors found
[error] (Compile / compileIncremental) Compilation failed
[error] Total time: 1 s, completed Aug 23, 2018 6:40:43 PM
`

**Comment by jmcardon** [comment]
Would you mind, instead, raising this issue in the g8 repo?

**Comment by kayvank** [comment]
moved the issue to http4s/g8 repo.
See [issue-73](https://github.com/http4s/http4s.g8/issues/73)  for detail
