### ISSUE TITLE
Interest in a caching middleware?

### ISSUE THREAD

**Issue by Slakah** [http4s/http4s#2038]
Created a quick caching middleware (using [Scaffiene](https://github.com/blemale/scaffeine)).

Implemented based on this reference, [Cacheable MDN](https://developer.mozilla.org/en-US/docs/Glossary/cacheable).

Code example can be found [here](https://gist.github.com/Slakah/670e932dace0b669c55eae3d6b386a54).

Would be nice to know if there's any interest in something like this, and ideas for how such a middleware would be configurable. i.e. would it want some kind of configurable `isCacheable` predicate, maybe a different caching implementation should be used, is there anything that can be done with e-tags, etc.

**Comment by rossabaker** [comment]
Thanks, @Slakah.  I apologize for the delayed response.  We've been very busy getting ready for the cats-effect release.

I love the idea of a caching middleware, but I'm also wary of adding more dependencies to the main repo. Historically, we've run a monorepo to make sure that everything evolves together.  The more we add, the harder it's getting to align the dependencies of all these integrations.  The long term solution here is probably going to be to split these integrations into a polyrepo.

That said, I would like to get these projects more visibility.  We have a list of releated libraries at https://github.com/http4s/http4s/blob/master/website/src/hugo/content/adopters.md#libraries, and a PR here would be great.

And if the scaffeine dependency can be made pluggable so we can pull something like this in cleanly, I can imagine a caching middleware in the server module and an http4s-scaffeine somewhere else.

**Comment by bfdes** [comment]
Is there any interest in implementing this?
If so, I could try to do this and provide an in-memory cache for testing and simple use.

I took a look at @slakah’s code and it looks like it is possible to pull out the cache implementation from the middleware.

**Comment by rossabaker** [comment]
We added a `Caching` middleware a while back, and mules has an http4s integration for something more sophisticated.
