### ISSUE TITLE
Noisy "unhandled inbound command: Disconnected" warnings

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#2039]
```
11:08:43.268 [blaze-selector-0-1] WARN  o.h.b.p.stages.QuietTimeoutStage - org.http4s.blaze.pipeline.stages.QuietTimeoutStage Stage: 30 seconds received unhandled inbound command: Disconnected
11:08:43.268 [blaze-selector-0-1] WARN  o.h.s.blaze.Http1ServerStage$$anon$1 - Http4sServerStage received unhandled inbound command: Disconnected
```

Several users seeing this.  All(?) reported on 0.19.0-M1.

Reproduction straight from materialized g8 template: https://github.com/andimiller/blaze-debug

We should see if this is truly innocuous, and if so, quiet it.

**Comment by andimiller** [comment]
https://github.com/http4s/blaze/issues/218 for more information on this bug in Blaze
