### ISSUE TITLE
Silence expected stack traces in test output

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#2049]
1. Steal [silenceSystemErr](https://github.com/typelevel/cats-effect/blob/c7af84bc2d3ae63d77336d521818cb05c66579cf/core/shared/src/test/scala/cats/effect/internals/TestUtils.scala#L31), with credit
2. Find the tests that are dumping stack traces
3. Wrap them in `silenceSystemErr`
4. Enjoy cleaner Travis runs

**Comment by ashwinbhaskar** [comment]
@rossabaker can this issue be marked as resolved/close as [this](https://github.com/http4s/http4s/pull/2179) seems to fix it?

**Comment by rossabaker** [comment]
We have the helper now thanks to #2179, but the CI build is still full of them.  We need to apply the helper.  A good way to find them would be to look at a [recent test run](https://github.com/http4s/http4s/runs/655202092?check_suite_focus=true), download the raw log, and search for "at org.http4s".  We should silenceSystemErr in the relevant tests.

**Comment by ashwinbhaskar** [comment]
@rossabaker okay, I can take this up. Can you assign it to me?

**Comment by ashwinbhaskar** [comment]
@rossabaker the trait `ErrorReportingUtils` has been deprecated. I can understand that it is being deprecated from public api usage. But marking it deprecated fails the tests too 
```
 trait ErrorReportingUtils in package testing is deprecated (since 0.21.0-RC2): Not related to HTTP, and will be removed from public interface.
```

**Comment by rossabaker** [comment]
Oops, hadn't seen this yet.  Answered the question on the PR itself.

**Comment by ashwinbhaskar** [comment]
@rossabaker might be a naive question. But wanted to confirm if I have got this right.

[this](https://github.com/http4s/http4s/blob/af4a5b5242685a0add29f44ed60335538b380f2b/blaze-server/src/test/scala/org/http4s/server/blaze/Http1ServerStageSpec.scala#L123) line throws an exception when the IO is evaluated. In this case the evaluation is forced by `Await` [here](https://github.com/http4s/http4s/blob/af4a5b5242685a0add29f44ed60335538b380f2b/blaze-server/src/test/scala/org/http4s/server/blaze/Http1ServerStageSpec.scala#L158). Is my understanding correct?

**Comment by rossabaker** [comment]
Ah, yeah, so that one is actually going through the logger.  We can see the `service-error`  logger name right above it, which points to `serviceErrorLogger`, which is installed by the `DefaultServiceErrorHandler` in the test.  We might need a version of that that doesn't log.

**Comment by ashwinbhaskar** [comment]
@rossabaker ah got it. I created an ErrorHandler which does not log and used it in `Http1ServerStageSpec`. I have pushed the code. Can you see if it is okay

**Comment by rossabaker** [comment]
Yes, I'll go look and comment on the PR itself.

**Comment by ashwinbhaskar** [comment]
@rossabaker I think I have fixed all the test error stack traces. Can you review the PR - https://github.com/http4s/http4s/pull/3456

**Comment by ashwinbhaskar** [comment]
@rossabaker all test stack traces silenced
