### ISSUE TITLE
Http1Client won't process new request

### ISSUE THREAD

**Issue by sjmyuan** [http4s/http4s#2068]
# Version
0.18.1

# Description
This is an edge case and not 100% happens. when we send requests in parallel and the parallel number is greater than `maxTotalConnections`, sometimes the new request will not return(no error and no response) and our app will be stuck forever.

This issue always happens after the error
```
In wait queue for too long, timing out request. at org.http4s.client.PoolManager.releaseRecyclable(PoolManager.scala:200)
``` 

# Analysis
From the heap of our app, we can see `curTotal==maxTotalConnections` and there are more than 30 requests in `waitQueue`,  this issue always happens when `PoolManager.scala:200` happened `maxTotalConnections` times.

So we guess the root cause is [PoolManager.scala:200](https://github.com/http4s/http4s/blob/v0.18.1/client/src/main/scala/org/http4s/client/PoolManager.scala#L200)

In this line, when the waiting request timeout, it just returns `Left`, haven't reduced the number of `curTotal` and destroy the connection. So after this error, we lose the connection but still count it in the `curTotal`. 

After this error happens `maxTotalConnections` times, `curTotal==maxTotalConnections`, the following new request will be put in `waitQueue`, but there is no connection will be recycled and process the request in `waitQueue`, then the request just live in `waitQueue` forever

# How to reproduce
1. Set the `maxTotalConnection` to be 1
2. Set the latency time of the server is 200ms
3. Send the request to the server in parallel

The error log looks like this
```
[pool-32-thread-142] DEBUG o.h.c.PoolManager - Recycling connection: curAllocated=1 idleQueues.size=0 waitQueue.size=83 maxWaitQueueLimit=256 closed=false
[pool-32-thread-142] DEBUG o.h.c.PoolManager - Request expired
[pool-32-thread-142] ERROR LoggingErrorHandler - Uncaught exception: In wait queue for too long, timing out request. at org.http4s.client.PoolManager.releaseRecyclable(PoolManager.scala:200), org.http4s.client.PoolManager.$anonfun$release$1(PoolManager.scala:271), scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12), cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:85), cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:310), cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:292), cats.effect.internals.Callback$AsyncIdempotentCallback$$anon$3.run(Callback.scala:142), cats.effect.internals.TrampolineEC.cats$effect$internals$TrampolineEC$$localRunLoop(TrampolineEC.scala:62), cats.effect.internals.TrampolineEC.$anonfun$execute$1(TrampolineEC.scala:54), scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12), scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81), cats.effect.internals.TrampolineEC.execute(TrampolineEC.scala:54), cats.effect.internals.Callback$AsyncIdempotentCallback.apply(Callback.scala:139), cats.effect.internals.Callback$AsyncIdempotentCallback.apply(Callback.scala:130), org.http4s.client.blaze.Http1Connection.parsePrelude(Http1Connection.scala:279), org.http4s.client.blaze.Http1Connection.$anonfun$readAndParsePrelude$1(Http1Connection.scala:177), org.http4s.client.blaze.Http1Connection.$anonfun$readAndParsePrelude$1$adapted(Http1Connection.scala:176), scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624), java.lang.Thread.run(Thread.java:748)
[anInnocuousThread] DEBUG o.h.b.p.Stage - Stage ByteBufferHead sending inbound command: Disconnected
[anInnocuousThread] DEBUG o.h.b.p.Stage - ReadBufferStage shutting down at Mon Sep 10 07:20:35 UTC 2018
[anInnocuousThread] DEBUG o.h.b.p.Stage - Stage ReadBufferStage sending inbound command: Disconnected
[anInnocuousThread] DEBUG o.h.b.p.Stage - Stage Http1Connection sending outbound command: Disconnect
[anInnocuousThread] DEBUG o.h.b.p.Stage - ReadBufferStage shutting down at Mon Sep 10 07:20:35 UTC 2018
[anInnocuousThread] DEBUG o.h.b.p.Stage - Stage ReadBufferStage sending outbound command: Disconnect
[anInnocuousThread] DEBUG o.h.b.p.Stage - closeWithError(EOF)
[anInnocuousThread] DEBUG o.h.b.p.Stage - Http1Connection shutting down at Mon Sep 10 07:20:35 UTC 2018
[anInnocuousThread] DEBUG o.h.b.p.Stage - closeWithError(EOF)
```

**Comment by rossabaker** [comment]
Thanks for the detailed report!  I suspect it's still a bug, but before we chase this, can you easily check whether it happens on 0.18.17?  This is fully binary compatible with 0.18.1.

**Comment by sjmyuan** [comment]
Thanks for the response, will check it on 0.18.17 as soon as possible

**Comment by rossabaker** [comment]
I'm not able to reproduce this on 0.18.20.  If you still see it, please reopen.
