### ISSUE TITLE
Use the new `readRange` in fs2

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#2071]
@asoltysik added a [`readRange`](https://github.com/functional-streams-for-scala/fs2/pull/1246) function to fs2.  We can replace our messy [`fileToBody`](https://github.com/http4s/http4s/blob/1c2e4c053b60c4cd978d11e87e8b60e94bede48e/core/src/main/scala/org/http4s/StaticFile.scala#L187) with it.

**Comment by asarturas** [comment]
^ started working on this

**Comment by aeons** [comment]
Fixed by #2079
