### ISSUE TITLE
Introduce `ClientBuilder` trait

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#2075]
`ClientBuilder` is an algebra that I'm not sure will be abstracted over often, but declaring it and extending `JavaNetClientBuilder`, `OkHttpBuilder`, and `BlazeClientBuilder` with it would at least enforce uniformity in creation.

```scala
import cats.effect.Resource
import fs2.Stream

trait ClientBuilder[F[_]] {
  def resource: Resource[F, Client[F]]
  final def stream: Stream[F, Client[F]] = Steam.fromResource(resource) 
}
```

We have a similar `ServerBuilder` trait that is an unholy maze of subtraits that we'd like to get rid of, but a minimal algebra like this still makes sense to me.

I'd like to hear from another committer before we waste volunteer time on this, but _I_ think it would be useful.

**Comment by ChristopherDavenport** [comment]
Yes. But only this minimal subset. Could this be a typeclass instead of relying on inheritance?

**Comment by rossabaker** [comment]
I don't think it's a typeclass.  What are the laws?  We're not providing implicit instances for `IO`, `Task`, etc., but rather explicit interpreters for blaze, okhttp, etc.

**Comment by rossabaker** [comment]
I don't know how we'd test that law.  There's no `isShutdown` on `Client` (I guess it could be added?), and we've even discussed moving `shutdown` off so it's always managed by the Resource.

**Comment by ChristopherDavenport** [comment]
Right, I'm just trying to think of ways to abstract. Refer to is as an algebra instead. The point being that a concrete construction from the Server satisfies it, without forcing inheritance or other burden into the class itself.

**Comment by rossabaker** [comment]
I think maybe you're right.  `BlazeClientBuilder` isn't just an interpreter.  It's a data type that provides its own methods.

I'm coming around to the idea of `ClientBuilder` as a flimsy typeclass and a not very useful algebra, and that we don't really need it at all.

**Comment by rossabaker** [comment]
I'm convinced this is not needed.
