### ISSUE TITLE
Promise already completed

### ISSUE THREAD

**Issue by julien-truffaut** [http4s/http4s#210]
I am getting the following error with blaze server 0.6.0. It seems to happens roughly 1 / 5000 requests

```
[ERROR] [2015-02-03 16:31:05,334] [FixedPoolLoop-4]  o.h.b.c.n.SelectorLoop: Error performing channel operations. Closing channel.
java.lang.IllegalStateException: Promise already completed.
        at scala.concurrent.Promise$class.complete(Promise.scala:55) ~[scala-library.jar:na]
        at org.http4s.blaze.channel.nio1.NIO1HeadStage$PipeClosedPromise.complete(NIO1HeadStage.scala:17) ~[blaze-core_2.10-0.5.0.jar:0.5.0]
        at org.http4s.blaze.channel.nio1.NIO1HeadStage.readReady(NIO1HeadStage.scala:52) ~[blaze-core_2.10-0.5.0.jar:0.5.0]
        at org.http4s.blaze.channel.nio1.SelectorLoop.run(SelectorLoop.scala:98) ~[blaze-core_2.10-0.5.0.jar:0.5.0]
```

**Comment by bryce-anderson** [comment]
@julien-truffaut I have this patched in ```0.5.1-SNAPSHOT``` which should be in sonatype snapshots repo now. Can you pull that in and see if the problem persists? If not, I can do a release.

**Comment by julien-truffaut** [comment]
man you're awesome. I will try that tomorrow morning and tell you how it goes

**Comment by bryce-anderson** [comment]
Don't thank me yet, I'm only 98% sure its fixed. For reference, the changes are in the [blaze project](https://github.com/http4s/blaze/commit/fdfa4926f113893f2851d786df328697cbdce155).

**Comment by julien-truffaut** [comment]
It worked, I don't see the error message anymore.
When I load test, I still a few "java.io.IOException: Remotely closed" from the client, maybe 1 every 50K requests but I don't see any error message on server log. It might be an error on my application or from the test framework.

Do you think we could make a patch release? Thanks again bryce

**Comment by bryce-anderson** [comment]
Yup, I can do a patch release. For reference, the channel is getting closed by something, and if your logs don't include any ```logger.warn(t)("Abnormal NIO1HeadStage termination")```, then it looks to be normal termination as far as blaze is concerned. There could still be a problem in http4s that is causing said termination.

If you want, I can add some debug code to help you figure out whats going on before doing a patch release. The choice is yours.

**Comment by julien-truffaut** [comment]
I am quite curious about this termination issue but I will need to release my app very soon and it happens very rarely. So if you don't mind, I would go for a release now and investigate later.

**Comment by bryce-anderson** [comment]
Alright, blaze 0.5.1 is released to maven, should be there soon. Can you double check that it solves the problem before I do a http4s-0.6.1 release with the updated transient dependencies (and some bug fixes)?

**Comment by julien-truffaut** [comment]
sure, let me 30 min

**Comment by julien-truffaut** [comment]
it is all good

**Comment by bryce-anderson** [comment]
Cool. Should we close this issue?

**Comment by julien-truffaut** [comment]
sure
