### ISSUE TITLE
Stale issue cleanup

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#2135]
We have 131 open issues and 23 open pull requests.  Is something like [stale bot](https://github.com/apps/stale) a good idea?  I have mixed feelings.

Discuss.

**Comment by m-sp** [comment]
seems the stale issue ticket got a bit stale it self :D
I was idling browsing through the issues and so a couple which probably have been solved. can I just close them?

**Comment by rossabaker** [comment]
Yes, please!  We have not been very good about this.

**Comment by rossabaker** [comment]
I'm making this pass now.
