### ISSUE TITLE
JettyBuilder gives 404 where BlazeBuilder gives 200?

### ISSUE THREAD

**Issue by refried** [http4s/http4s#215]
With http4s 0.6.0 and rho 0.3.0, given:
```
import org.http4s.rho._
import org.http4s.server.jetty.JettyBuilder
 
object Main extends App {
  val rhoService = new RhoService {
    GET / "incident" / 'incidentNum |>> { id: String => Ok(s"Incident $id: Joe did it.") }
  }
 
  JettyBuilder
    .mountService(rhoService.toService)
    .bindLocal(8080)
    .start
    .run
}
```

`$ curl http://localhost:8080/incident/3`
```
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 404 </title>
</head>
<body>
<h2>HTTP ERROR: 404</h2>
<p>Problem accessing /incident/3. Reason:
<pre>    Not Found</pre></p>
<hr /><i><small>Powered by Jetty://</small></i>
</body>
</html>
```

Replacing JettyBuilder with BlazeBuilder:
`Incident 3: Joe did it.`

**Comment by rossabaker** [comment]
This can be worked around by mounting service with `""` instead of the default `"/"`.  I can't think of a reason we shouldn't trim trailing slashes in this argument and make it work either way.

**Comment by bryce-anderson** [comment]
As @rossabaker said, this appears to be with the default path located [here](https://github.com/http4s/http4s/blob/master/server/src/main/scala/org/http4s/server/ServerBuilder.scala#L28). @rossabaker, is the easiest solution to just override the default to ```""```?

**Comment by rossabaker** [comment]
Yes, that's the easiest solution.  I think a friendlier additional solution might be to normalize by trimming `"/+$".r`.  I can't think of a case where intent would ever be different.

**Comment by refried** [comment]
Sorry I never got to it!

**Comment by rossabaker** [comment]
No worries, I was just looking for an easy one before bed. :-)
