### ISSUE TITLE
HTTP2 support

### ISSUE THREAD

**Issue by stephenjudkins** [http4s/http4s#216]
The HTTP2 spec is nearing completion, and offers many of benefits for browsers and API implementors. How interested are people in HTTP2 support for http4s?

**Comment by bryce-anderson** [comment]
@stephenjudkins, very interested. The groundwork has already been done in blaze [here](https://github.com/http4s/blaze/tree/master/http/src/main/scala/org/http4s/blaze/http/http20) and the only thing left to do is make a http4s server stage.
On the other backend fronts, if you servlet container supports http2, you should be ready to do.

**Comment by stephenjudkins** [comment]
How far along is the Blaze HTTP2 server? Would further functional tests be helpful? What server implementation have you been testing this with?

**Comment by bryce-anderson** [comment]
The blaze server is finished sans bugs. I've done some manual testing using [h2spec](https://github.com/summerwind/h2spec) but that is far from conclusive. Its been a about three weeks sense I've run the tests and there have been quite a few commits adding more tests etc so it might be worth it to run again.

Blaze would certainly benefit from some more tests, few of the existing tests check for total protocol correctness.

Ultimately we need to integrate with http4s: currently only the basic blaze server supports http2. This should be somewhat minor as all the protocol stuff is taken care of already.

There is almost no work on a http2 client, though the codec should work nearly without modification.

**Comment by bryce-anderson** [comment]
As a quick update, it seems that [HTTP/2 and HPACK](https://www.mnot.net/blog/2015/02/18/http2) are finished with their technical evolution and its now just paperwork type stuff.

@stephenjudkins, are you interested in helping move this along for http4s, or just curious of the status?

**Comment by stephenjudkins** [comment]
I am interested but cannot commit to any specific amount of time at the moment. I'll check back in in a few weeks when work stuff settles down for me, and see what I can contribute. If there are small issues to deal with I could work on those now.

**Comment by bryce-anderson** [comment]
Commit c3be3a352ec4d3ecb07dc8baf9b13d309880b00f should adddress this to the extent possible by our server architecture. There is will likely be bugs etc that need to be addressed, but http2 is now a thing in http4s.
