### ISSUE TITLE
Support for pac4j or any Oidc library? 

### ISSUE THREAD

**Issue by pravin-raha** [http4s/http4s#2161]
Is there any plan of implementing  pac4j for http4s?
I did not find any example for odic + http4s. It would be nice if we can provide pac4j support, so most of the Authentication and Authorization problem would be solved.

**Comment by rossabaker** [comment]
I've never heard of pac4j.  Do you have a sketch of what an integration might look like?

**Comment by pravin-raha** [comment]
Currently, I am working on integration. Let you know once I am done with a first rough draft.

Pac4j is a Java security engine [http://www.pac4j.org/](url). It also have play integration [https://github.com/pac4j/play-pac4j](url)

**Comment by pravin-raha** [comment]
you can find a starting guide for implementation here [http://www.pac4j.org/docs/how-to-implement-pac4j-for-a-new-framework.html#how-to-implement-pac4j-for-a-new-framework-tool](url)

**Comment by arashi01** [comment]
Looks like Pac4J have an example implementation started. See [pac4j/http4s-pac4j](https://github.com/pac4j/http4s-pac4j). 

Maybe it might be a good idea to work with them?

**Comment by rossabaker** [comment]
I'm surprised to see version 0.16 three months ago.  I'd be happy to link to it to promote it, and if anyone needs help getting it upgraded to a current version, the support channels are open.

**Comment by philliptaylorpro** [comment]
Silhouette and Keycloak can be made to work together.

**Comment by rossabaker** [comment]
Looks like http4s-pac4j is an established project now.  Closing.
