### ISSUE TITLE
Windows builds on Travis

### ISSUE THREAD

**Issue by aeons** [http4s/http4s#2165]
Maybe we can get rid of the whole appveyor setup.

https://blog.travis-ci.com/2018-10-11-windows-early-release

**Comment by rossabaker** [comment]
Would require something like [this](https://travis-ci.community/t/java-support-on-windows/286) for now.

**Comment by aeons** [comment]
Ah, shows how much I know about Travis :)

Close for now and open a new issue once it's feasible?

**Comment by rossabaker** [comment]
Sounds good to me.
