### ISSUE TITLE
jmh for benchmarking

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#217]
I'd like to get some more formal, repeatable benchmarks in place so we can better monitor the cost of our future design decisions.

The work @julien-truffaut did could be an inspiration: non/cats#190

**Comment by julien-truffaut** [comment]
I can make a similar set-up if you want. Also, what do you think about adding a load testing module? I have used [gatling](http://gatling.io/) in the past, the dsl is very simple.

**Comment by rossabaker** [comment]
Are you thinking gatling-sbt?  I'd love to have a simple way to run load tests and track progress without the ad hoc ab tests I've been running.

**Comment by julien-truffaut** [comment]
Yeah gatling with their sbt plugin. If you want I can show you how it looks
like next week end (I am on ski holidays now)

--
Julien Truffaut

**Comment by rossabaker** [comment]
That would be great.  The more I think about it, I think gatling integration scratches a more immediate itch than jmh.  I'd like automated load tests to monitor progress in the large, and then we can look into jmh for the lower level optimizations.

**Comment by julien-truffaut** [comment]
basic setup is merged, we "just" need to write benchmarks now :)
