### ISSUE TITLE
RequestLogger logs sensitive headers

### ISSUE THREAD

**Issue by IssueMonoid** [http4s/http4s#2181]
In the 0.18.x branch of RequestLogger the deprecated apply method ignores redactHeadersWhen when calling logMessage, resulting the default value being passed and hence sensitive headers being logged.

This issue was fixed in:
d0ce8f36e196508bfc15195ba1b7412fce10fe6d

But then reintroduced in:
801b58ce8dd

**Comment by rossabaker** [comment]
Fixed by #2182, released in 0.18.20.
