### ISSUE TITLE
PoolManager waitQueue not cleaned up

### ISSUE THREAD

**Issue by ptrlaszlo** [http4s/http4s#2193]
We are using http4s 0.19.0-M1 and we observed an issue with the http client. If we call an API which is slow, the waitQueue of the PoolManager fills up and start to throw "Max wait length reached, not scheduling". This seems to be OK, but the wait queue seems to be never freed up. So once we enter this state, there is no going back.

Some details:
- `borrow` ends up in a [situation](https://github.com/http4s/http4s/blob/v0.19.0-M1/client/src/main/scala/org/http4s/client/PoolManager.scala#L177-L179) where the `idleQueues` is empty, but the `waitQueue` is full
- the test configuration we use: `maxTotal: 2, maxWaitQueueLimit: 5, responseHeaderTimeout: 18 seconds, requestTimeout: Inf`
- when the wait queue is not freed up the attributes are: `isClosed: false, curTotal: 2, size of allocated: 1, size of idleQueues: 0, size of waitQueue: 6`

I'm happy to provide more information if needed.

**Comment by rossabaker** [comment]
I'm having trouble reproducing this.  Does anyone have a runnable example?

**Comment by rossabaker** [comment]
Is this happening when the requests are timing out, not just slow?  I think that is the key here.

**Comment by rossabaker** [comment]
Thinking this may be related to #2068.

**Comment by rossabaker** [comment]
Trying to reproduce this on 0.18.x:

```scala
import cats.effect._
import fs2._
import java.util.concurrent.atomic._
import org.http4s._
import org.http4s.client.blaze._
import scala.concurrent.ExecutionContext.Implicits.global
import scala.concurrent.duration._

object Issue2193 {
  def main(args: Array[String]) = {
    val int = new AtomicInteger(0)
    (for {
      c <- Http1Client[IO](BlazeClientConfig.defaultConfig.copy(
        maxTotalConnections = 2,
        maxWaitQueueLimit = 5,
        responseHeaderTimeout = 5.seconds,
        requestTimeout = Duration.Inf
      ))
      submit = c.status(Request[IO](uri = Uri.uri("http://httpbin.org/delay/10"))).attempt
      step = submit
      s <- Stream(Stream.eval(step)).repeat.covary[IO].join(8).take(20)
        .observe1(x => IO(println(">>> " + int.incrementAndGet + " " + x))).compile.drain
      _ <- IO.sleep(10.seconds)
      status <- c.status(Request[IO](uri = Uri.uri("http://httpbin.org/get"))).attempt
      _ <- IO(println("STATUS = " + status))
    } yield ()).unsafeRunSync()
  }
}
```

After the `responseHeaderTimeout`, it clears out the wait queue:

```
23:45:38.723 [scala-execution-context-global-1231] DEBUG org.http4s.client.PoolManager - Requesting connection: curAllocated=2 idleQueues.size=0 waitQueue.size=5 maxWaitQueueLimit=5 closed=false
23:45:38.724 [scala-execution-context-global-1231] DEBUG org.http4s.client.PoolManager - No connections available for the desired key. Adding to waitQueue: curAllocated=2 idleQueues.size=0 waitQueue.size=5 maxWaitQueueLimit=5 closed=false
23:45:38.724 [scala-execution-context-global-1231] ERROR org.http4s.client.PoolManager - Max wait length reached, not scheduling.
23:45:43.940 [scala-execution-context-global-1227] DEBUG org.http4s.client.PoolManager - expired requests: 5
23:45:43.940 [scala-execution-context-global-1227] DEBUG org.http4s.client.PoolManager - Dropped expired requests: curAllocated=1 idleQueues.size=0 waitQueue.size=0 maxWaitQueueLimit=5 closed=false
```

After a series of `WaitQueueFullFailure`, the final request goes through:

```scala
STATUS = Right(200 OK)
```

I'll modify and try on master in the morning, since it has been reported twice.  But if anyone has a reproducible case, that would help a lot.
