### ISSUE TITLE
Flaky test: BlazeHttp1ClientSpec GET: /simple

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#2197]
```
[info] BlazeHttp1ClientSpec
[info] + Execute GET: /chunked (496 ms)
[info] + Execute GET: /not-found (510 ms)
[info] + Execute GET: /no-content (522 ms)
[error] ! Execute GET: /simple (10 seconds, 313 ms)
[error]  java.util.concurrent.TimeoutException: Response header timeout after 10000 ms. (ResponseHeaderTimeoutStage.scala:27)
[error] org.http4s.blazecore.ResponseHeaderTimeoutStage$$anon$1.run(ResponseHeaderTimeoutStage.scala:27)
[info] + Execute GET: /delayed (1 second, 44 ms)
```

https://travis-ci.org/http4s/http4s/jobs/443905281

**Comment by rossabaker** [comment]
An [appveyor version](https://ci.appveyor.com/project/ChristopherDavenport/http4s-m0hqu/builds/19776714/job/g0dfrnmj86h3kb9u#L4801) that failed on /no-content.  This was first seen on appveyor the blaze-0.14.0-M9 upgrade, though it's not an SSL test, so it seems unlikely to be related.

**Comment by rossabaker** [comment]
https://travis-ci.org/http4s/http4s/jobs/447372204#L3826

**Comment by rossabaker** [comment]
I think this might be an actual problem.  I want to get this resolved before 0.20.0.

**Comment by rossabaker** [comment]
https://travis-ci.org/http4s/http4s/jobs/449167552#L3758

**Comment by rossabaker** [comment]
Probably related: https://travis-ci.org/http4s/http4s/jobs/449823379#L3298

**Comment by rossabaker** [comment]
We haven't seen this in a while.  Optimistically closing.  I have a hunch that #2258 was helpful here.

**Comment by rossabaker** [comment]
[Nuts](https://travis-ci.org/http4s/http4s/jobs/456725017#L3927).

**Comment by mahe-ymc** [comment]
Happens occasionally in one of our prod apps using org.http4s:blaze-http_2.12:0.14.0-M12. Note that this happens although we set the timeout to 60 seconds, which is certainly pretty high. Additionally, the HTTP method seems irrelevant as it also occurs using PUT.

**Comment by pandaforme** [comment]
I have the same issue in our production. The version we use is `0.20.0`.
Error logs:
```
Response header timeout after 10000 ms.
java.util.concurrent.TimeoutException: Response header timeout after 10000 ms.
        at org.http4s.blazecore.ResponseHeaderTimeoutStage$$anon$1.run(ResponseHeaderTimeoutStage.scala:27)
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```
We passed all unit test/intergration test/regression test and don't know somehow it fails on production.

**Comment by rossabaker** [comment]
I can't reproduce this in the wild.  If it's still an issue on a supported version (currently, >= 0.21), please reopen.
