### ISSUE TITLE
Http4s 0.20.0-M1: withMaxHeaderLength not in BlazeClientBuilder

### ISSUE THREAD

**Issue by amarrella** [http4s/http4s#2217]
I just stumbled upon this working on the scalafix, is there a reason why `withMaxHeaderLength` is not exposed in the new builder? It seems to be a parameter of the builder itself

**Comment by rossabaker** [comment]
Yes, that's an oversight.

**Comment by bhop** [comment]
Hi Guys, I am happy to fix it
