### ISSUE TITLE
Add request attributes for SSL requests

### ISSUE THREAD

**Issue by sebastianvoss** [http4s/http4s#2218]
When using mutual TLS authentication it would be useful to have access to a few SSL-specific request attributes (e.g. to use the clients certificate common name (CN) to do authorization):

- `javax.servlet.request.ssl_session_id`
- `javax.servlet.request.cipher_suite`
- `javax.servlet.request.key_size`
- `javax.servlet.request.X509Certificate`

See [jetty docs](https://github.com/eclipse/jetty.project/blob/6b335877d9cc8a6be0c61c5d6d2a559ab9035323/jetty-server/src/main/java/org/eclipse/jetty/server/SecureRequestCustomizer.java#L210-L213) for more details.

**Comment by balatbn** [comment]
We are planning to do mTLS and we are facing the same issue: Getting client certificate(X509) from the request. Is there any other way we can get this info?

**Comment by rossabaker** [comment]
We can add these to the servlet backend fairly easily.  @sebastianvoss was working on adding to blaze, but it is non-trivial.  There is no solution right now, but I'd like to support this.

**Comment by sebastianvoss** [comment]
Yes, I got distracted by other stuff (it is more effort than we initially thought). I will hopefully have some time to get back to it soon. If someone else wants to jump in I'm happy to help.

**Comment by aeffrig** [comment]
The PR allows for http4s to be usable for those types of applications that require client certificate information by running in a compliant servlet container. If someone wants to comment more on working with SSL session information in blaze, I might be able to help with that as well.

**Comment by rossabaker** [comment]
@aeffrig The blaze branch in progress is at https://github.com/sebastianvoss/http4s/tree/add_ssl_request_attributes.  I can't remember precisely where that stalled, but @sebastianvoss may recall.

@balatbn Does this Undertow setting map map cleanly to `needClientAuth` and `wantClientAuth` on the `SSLEngine`?  An enum instead of a boolean seems appropriate.

**Comment by balatbn** [comment]
Undertow seems to map correctly to `need` and `want` in `SSLEngine`.

https://github.com/undertow-io/undertow/blob/master/core/src/main/java/io/undertow/protocols/ssl/UndertowAcceptingSslChannel.java#L173

**Comment by rossabaker** [comment]
Okay.  In that case, I think we should change that boolean to a sum type, and map it accordingly.

**Comment by aeffrig** [comment]
PR #2328 includes merged changes for both servlets and blaze.  I was wondering about tests for this functionality, and lamenting the general lack of testing support for maintaining certificate-related tests.  I noticed the current blaze-client certificate expired on 14 March 2015, which means disabling the expiration checking in tests.   Would http4s be interested in programmatically-generated certs, as explained at https://www.mayrhofer.eu.org/create-x509-certs-in-java for testing purposes?  It might help prevent expiration issues and prevent the need to disable certificate checking.  I haven't tried that approach before, but it would be nice if it works to create self signed certificates with key size and algorithm exposed as verifiable generated parameters.  Of course this does add a bit of testing code, and it could be overkill.  Thoughts?

**Comment by balatbn** [comment]
Certificate in the PR is valid for 10 years. But, I agree that programmatically generating certificate would be great.

**Comment by rossabaker** [comment]
I would love to see that.  I feel hypocritical telling people not to disable certificate validation in dev (in my best soccer coach voice: "Practice like you play!") and then cheating in tests.

**Comment by balatbn** [comment]
Raised another PR for converting `clientAuthMode` to an enum

**Comment by rossabaker** [comment]
This exists.
