### ISSUE TITLE
Failed to parse custom header

### ISSUE THREAD

**Issue by julien-truffaut** [http4s/http4s#222]
```scala
object `X-Custom` extends HeaderKey.Singleton {
  type HeaderT = `X-Custom`
  def name: CaseInsensitiveString = "x-custom".ci
  def matchHeader(header: Header): Option[`X-Custom`] = Some(`X-Custom`(header.value))
}

final case class `X-Custom`(token: String) extends Header.Parsed {
  override def key = `X-Custom`
  override def renderValue(writer: Writer): writer.type =
    writer.append(token)
}

val r: Request = ...
r.headers.get(`X-Custom`) == Some(x-custom: localhost:9999)
r.headers.get(`X-Custom`.name) == Some(x-custom: JULIEN)
```

`localhost:9999` seems to be the first header when I print the request.

**Comment by rossabaker** [comment]
Where does the request come from?  Is this from a client, or are you constructing it yourself?

**Comment by julien-truffaut** [comment]
I used blaze client to send request to a blaze server

**Comment by bryce-anderson** [comment]
@julien-truffaut: looking back on this, I think your 
```scala
def matchHeader(header: Header): Option[`X-Custom`]
``` 
method is wrong. You also need to check the key. It should probably look more like this:
```scala
def matchHeader(header: Header): Option[`X-Custom`] = {
  if (header.name == name) Some(`X-Custom`(header.value))
  else None
}
```
Could you give that a try and see if it works?

**Comment by julien-truffaut** [comment]
thanks, I will give it a try

**Comment by julien-truffaut** [comment]
Sorry for the delay @bryce-anderson, your solution works. 

What happens when you do: `r.headers.get(`X-Custom`)` ? does it iterate through all headers until one match?

**Comment by bryce-anderson** [comment]
Yes: https://github.com/http4s/http4s/blob/master/core/src/main/scala/org/http4s/HeaderKey.scala#L30

**Comment by julien-truffaut** [comment]
will it cause a problem to look up by header name and then call match header?

**Comment by bryce-anderson** [comment]
I'm not sure what you mean. Can you give a quick example?

**Comment by julien-truffaut** [comment]
sure, could from be implemented like this?
```scala
trait Singleton extends Extractable {
    def from(headers: Headers): Option[HeaderT] = 
      headers.get(name).flatMap(matchHeader)
  }
```

**Comment by bryce-anderson** [comment]
Technically yes, but I personally think ```Headers.from``` should be made to enforce that ```matchHeader``` as the standard way to match a header. @rossabaker, do you have an opinion on that?

**Comment by bryce-anderson** [comment]
Let try to close this issue. If we want to change the definition of ```from``` we should change a few others things such as the definition of ```get(CaseInsensitiveString)``` so that we don't reparse headers. I'm partial to making ```from``` final and moving forward.
