### ISSUE TITLE
Clean up Message and subclasses

### ISSUE THREAD

**Issue by aeons** [http4s/http4s#2224]
Currently, it's hard to get an overview of the methods on `Message`, `Request` and `Response`, due, in part, to the split of some methods to the `*Ops` traits. These traits are only used for the deprecated `Effect*Syntax` stuff, as far as I can see.

For example, we have `replaceAllHeaders` and `putHeaders` on `MessageOps`, and `withHeaders` on `Request`.

I know there's some rumbling about a typeclass reimplementation of `Message`, but I think this could be done now anyway.

I would like to remove the `*Ops` traits, but I don't really see how that can be done without removing the deprecated `Effect*Syntax` traits.

**Comment by rossabaker** [comment]
We deprecated that effect syntax a long enough time ago I think we can get rid of that.

@ChristopherDavenport has poked at this a few times.  #1572 has some prior art.

**Comment by aeons** [comment]
Alright, I might go ahead and PR that.

Wrt. the Message typeclass, did we go back on that idea? Or what was the reason for the PR being abandoned? Just lack of time?

If so, I might try reviving the idea.

**Comment by ChristopherDavenport** [comment]
Its a great idea! Its a ton of work. I don't think that's possible to get into 0.20

**Comment by aeons** [comment]
Alright.
So, how about,
- a PR that removes the effect syntax stuff and streamlines some of the methods on Message/Request/Response, aimed at 0.20
- a PR that builds on the previous typeclass work, aimed at some future release

**Comment by ChristopherDavenport** [comment]
That sounds ideal.
