### ISSUE TITLE
Removal of `ResponseOps` breaks Rho's `Result` - Http4s `Response` parity.

### ISSUE THREAD

**Issue by zarthross** [http4s/http4s#2257]
This commit b54af3a12b5f7b838d9346171a902224411a13d1 in PR #2234 breaks Rho [here](https://github.com/http4s/rho/blob/a12cbe1d2e5722b8fe72a30ea095b36655b753ba/core/src/main/scala/org/http4s/rho/Result.scala#L87).  Rho was using the `ResponseOps` trait to keep the the signature of the Result and response types the same.  Unfortunately without it Rho will need to manually keep pace.  Could we possibly bring back the `ResponseOps`?  Is there some other mechanism we can use to have Rho keep pace?

**Comment by zarthross** [comment]
I would say an `AuthedRequest` is a 2nd kind of http4s `Request` and could benefit from that typeclass approach as well.

**Comment by rossabaker** [comment]
Okay, my resistance is wearing down.

In the short term, I guess the shortest path is to bring back `ResponseOps`?  Maybe even as `private [http4s]` so we're not breaking a public interface when we evolve to a full typeclass?

**Comment by ChristopherDavenport** [comment]
Why does this need to be in http4s, rather than somewhere in Rho?

**Comment by rossabaker** [comment]
Pros:
* It avoids duplication and keeps rho more consistent with core.
* The operations look like the eventual typeclass

Cons:
* Child classes in another project are easy to break. (See: this ticket)

**Comment by zarthross** [comment]
@rossabaker Will a fix for this make it into 0.20?

**Comment by rossabaker** [comment]
I would like to have a solution for 0.20, but can't do it myself between the blaze tickets and obligations this weekend.  I think the typeclass is the correct long term solution for 1.0.

I think the two correct short term solutions are to either bring it back as a `private[http4s]` trait or to copy the old `ResponseOps` into rho.  I'm open to either.

**Comment by ChristopherDavenport** [comment]
I personally vote for moving this to Rho, it no longer needs to be in core.

**Comment by zarthross** [comment]
Here's what I think we will do for now.  I'll define typeclass instances for Response in Rho for now, with the goal of (at least making an attempt) to moving that into the Core.

**Comment by rossabaker** [comment]
This moved to rho for now, and we can look into removing that from rho when the typeclass happens.
