### ISSUE TITLE
OAuth2 bearer token BNF doesn't match spec?

### ISSUE THREAD

**Issue by toby5box** [http4s/http4s#226]
Ref. https://github.com/http4s/http4s/blob/master/core/src/main/scala/org/http4s/parser/AuthorizationHeader.scala#L65
vs
http://self-issued.info/docs/draft-ietf-oauth-v2-bearer.html#authz-header

It seems that the http4s grammar would disallow Base64URL-encoded tokens, but Base64URL-encoded tokens are fundamental so specifications like that cited, and also JWS/JWT: https://tools.ietf.org/html/draft-ietf-jose-json-web-signature-41#section-3.1

Or have I missed something? (I'm also trying to find example patterns for implementing challenge/response for Bearer tokens)

**Comment by toby5box** [comment]
Hm, this seems to be matching a JWS token, which is what I want. That's base64url and periods, which is not going to be matched by the grammar linked above. Strange.

**Comment by bryce-anderson** [comment]
Hi @toby5box, clearly this has been neglected: sorry about that.

First things first, I believe the base64 alphabet is correct it is consistent with [rfc 4648](http://tools.ietf.org/html/rfc4648#section-4 ).

The reason it is matching the token is that definition of base64 is only used in ```BasicCredentialDef```. It is using the definition of ```Token```, found [here](https://github.com/http4s/http4s/blob/master/core/src/main/scala/org/http4s/parser/Rfc2616BasicRules.scala#L56). I also think that is wrong, particularly the ```'/'``` is missing.

I'll poke around and maybe just implement the spec you linked. Have you had any problems, or has it just been working?

**Comment by toby5box** [comment]
Ah yes, I misread, I am not familiar with this grammar syntax. 

It's working for me, but I use only Json web tokens, which use the url-safe alphabet. To properly support oauth2 tokens it looks like you'd have to support both base64 alphabets per rfc.

Btw, the rule for CTL looks wrong? Shouldn't that be 0x00-0x1f and 0x7f?

**Comment by bryce-anderson** [comment]
Excellent eye, yes, CTL does look wrong. I'm going to have quite a queue of PRs after tonight. :smile: 

The definition of [```b64token```](https://github.com/http4s/http4s/pull/267/files#diff-97a7725d4b4f752d4fcf6b47c3e0ed39R68) should follow [rfc 6750](https://tools.ietf.org/html/rfc6750#page-5). Let me know if PR #267 isn't quite right.
