### ISSUE TITLE
Make scalafix github-based

### ISSUE THREAD

**Issue by amarrella** [http4s/http4s#2274]
Scala steward is going to try to support opening prs with scalafixes (see https://github.com/fthomas/scala-steward/issues/149). They are initially going to support github based scalafixes. I think it would be a nice idea to convert our scalafix from binary to github based so the day 0.20 gets released and scalasteward supports it (whichever is the latest) people get flooded with nice prs and have almost a 0-step migration :) 

What do you think?

**Comment by amarrella** [comment]
(This would also make the scalafix 1 step for people who do it manually, the drawback for us is uniquely that we need to have everything in one file instead of separate files). But I think we should favor user usability above all.

**Comment by rossabaker** [comment]
What does the one-file constraint mean?  Would we still be able to support multiple incremental versions?

**Comment by amarrella** [comment]
Yes that's not related. It's just a bit harder to maintain as the entire migration rule is in one file.
Multiple incremental versions are supported via git tags (see readme here https://github.com/typelevel/cats/tree/master/scalafix )

**Comment by rossabaker** [comment]
The people who would benefit from this change are http4s apps that use scala-steward?  It sounds exciting, but I imagine most http4s apps are in private repos and thus wouldn't get PRs from scala-steward.  That may mitigate some of the upside.

The downside doesn't sound that bad.

And another upside is that we could release improvements to the scalafixes without doing a patch release, right?

**Comment by amarrella** [comment]
> And another upside is that we could release improvements to the scalafixes without doing a patch release, right?

Correct, and another one is that the scalafix becomes one step.
Eventually all of this will be available on scalafix for binary releases too. But not sure about the timeline on that. It would be nice to have the one-step scalafix before 0.20 final is out

**Comment by fthomas** [comment]
@rossabaker I know of at least three people who run their own scala-steward instances (or at least tried running it) with GitHub Enterprise or with private GitHub repos. So there is no restriction that only public repos would benefit from this.

**Comment by rossabaker** [comment]
Oh, that makes it even more compelling then. :+1:

**Comment by amarrella** [comment]
Cool, i'll work on it :)
