### ISSUE TITLE
Timeout on `Client` constructed using `fromHttpApp` does not work as expected

### ISSUE THREAD

**Issue by zarthross** [http4s/http4s#2312]
It appears the `timeout` functionality has changed with the release of cats effect 1.1.0.
Previously the two below methods of doing a timeout worked the same way, now they do not.
Regardless of timeing, both methods result in a timeout error even though the `timeoutTo` method was allowed to run to completion.

I suspect the problem stems from this issue in cats effect (https://github.com/typelevel/cats-effect/pull/376)[https://github.com/typelevel/cats-effect/pull/376]

Whats even more of an issue, if you change the `Timer[IO].sleep` here to `IO.never` the second method just blocks indefinitely.  

## Setup
```
val startTime = System.currentTimeMillis()
def timeFromStart = (System.currentTimeMillis() - startTime) / 1000
val hostClient = Client.fromHttpApp(HttpApp[IO] {
  case _ =>
    IO(println(s"Sleeping: ${timeFromStart}")) *>
      Timer[IO].sleep(4.seconds) *>
      IO(println(s"Awake: ${timeFromStart}")) *>
      Ok(())
})
```
## `unsafeRunTimed`
```
println(s"Starting: ${timeFromStart}")
hostClient.expect[Unit]("").unsafeRunTimed(1.second)
println(s"Done: ${timeFromStart}")
```
Results: 
```
Starting: 0
Sleeping: 0
Done: 1
Awake: 4
```

## `timeoutTo`
```
println(s"Starting: ${timeFromStart}")
hostClient.expect[Unit]("").timeoutTo(1.second, IO.unit).unsafeRunSync()
println(s"Done: ${timeFromStart}")
```

Results:

```
Starting: 0
Sleeping: 0
Awake: 4
Done: 4
```

**Comment by zarthross** [comment]
While that may be true, the problem is how the change from cats-effect 1.0.0 to cats-effect 1.1.0 (I believe this one https://github.com/typelevel/cats-effect/pull/376) changed the way `timeoutTo` behaves within `Client.fromHttpApp`.  

I have some unit tests in my app that was ensuring that a timeout was properly setup, and I noticed the change in cats effect caused my tests to fail.  My test is basically, construct a client from an http app that completes in an absurd amount of time, pass it to a class that has a timed out client call, test that the call fails and that it takes about the timeout amount of time to complete.  Before cats effect 1.1.0 this worked, afterwards the timeout condition is still triggered, but it takes that absurd amount of time to complete now.

Looking at the code for `fromHttpApp` I'm not even sure what can be done to correct it since it seems that `IO.race` used in the `timeoutTo` will always wait for a `Resource`s allocation and finalization to finish... so... it seems that we can't timeout a client made from an http app?

**Comment by zarthross** [comment]
If this is an issue I should bring up with on the Cats effect issue board let me know... its just I first noted the issue for `fromHttpApp` because that's how it affected me.

**Comment by rossabaker** [comment]
Yes, this is an unfortunate change.  I'm running out of energy tonight, but I'd like to find a solution to this.

**Comment by rossabaker** [comment]
I don't think there's a lot we can do here.  If this is still causing pain, please reopen.
