### ISSUE TITLE
Under obscure conditions StaticFile.fromURL throws an unexpected exception

### ISSUE THREAD

**Issue by kryptt** [http4s/http4s#232]
When running under a docker container (with a limited set of ports being forwarded) StaticFile.fromURL throws the exception:
`java.lang.IllegalArgumentException: URI is not hierarchical`
This is avoidable if fromURL does not rely on fromFile.

I'll submit a patch for your opinion

**Comment by bryce-anderson** [comment]
This looks like it should have been closed. @kryptt, please reopen if this is still an issue. We seem to have gotten behind on our issue tracking.
