### ISSUE TITLE
Tighten up resource handling in Blaze server builder

### ISSUE THREAD

**Issue by nigredo-tori** [http4s/http4s#2330]
The current approach seems to be to create everything in one huge `delay`, and yield `shutdown` for cleanup. This works when the initialization is successful, however a lot of statements here can throw, in which case anything allocated before them doesn't get freed.

As an example, the part that bit me today is in [this part of code](https://github.com/http4s/http4s/blob/487e1d3558a0ab86b0fff50e24e96634e5d4e1a2/blaze-server/src/main/scala/org/http4s/server/blaze/BlazeServerBuilder.scala#L259-L268). Note how if the `bind` call throws, the `factory.closeGroup()` is never called, leaking an unaccounted thread pool.

**Comment by rossabaker** [comment]
Very good point.
