### ISSUE TITLE
Tutorial references old code

### ISSUE THREAD

**Issue by rohdef** [http4s/http4s#2334]
Hey,

reading through the tutorial I stumbled over code that no longer runs. Also found the solution at https://github.com/http4s/http4s/issues/1501

It's in the dsl-chapter where it references orNotFound in the testing part, which seems that it should be written using ```apply(getRoot).orElseF(NotFound())``` in stead (that is what works for me at least).

Would the best way to fix it be to fork the project and make a pull request on the release-0.18.x branch? Then I could probably easily update dsl.md :) I just don't have much experience with contributing, and would like to do it right

**Comment by rossabaker** [comment]
@rohdef Yes, that would be exactly right.  Anything merged to release-0.18.x eventually gets merged to master, so it would correct it for both versions.  Thanks!

**Comment by rohdef** [comment]
I hope I did it right :) at least there's a suggestion, and I also added a short part about getting the status and the body as a string (last one caused a lot of search and confusion, so hopefully, I'll save others from that)

**Comment by rohdef** [comment]
If I did it right, I will make a bit more changes and create pull requests for those too, since I can see the problem is also present in later parts of the tutorial
