### ISSUE TITLE
Client hangs when firewall blocks request

### ISSUE THREAD

**Issue by tilmanrossmy** [http4s/http4s#2338]
If the client sends a tcp Syn and never gets an Syn-ack, the http4s client hangs forever and timeout settings don't have any effect. This is demonstrated in this gist:
https://gist.github.com/tilmanrossmy/cef2489230db0068b082061c9e840d22
Using a java.net Client the connectTimeout Setting will end the request for the same URL as in the gist above:
https://gist.github.com/tilmanrossmy/04421b2efc8fc934a0dfb73b03ca933e

**Comment by rossabaker** [comment]
I suspect this would require a change all the way into blaze, but it's worth pursuing.  I consider the lack of a reasonable timeout, even if hardcoded, a bug.

**Comment by RafalSumislawski** [comment]
@tilmanrossmy @rossabaker I think this ticket can be closed now.

**Comment by rossabaker** [comment]
Fixed by #2470.
