### ISSUE TITLE
Client RequestLogger does not work with some client implementations

### ISSUE THREAD

**Issue by bastewart** [http4s/http4s#2346]
`http4s` version: `0.20-M4`

The `RequestLogger` middleware does not seem to work with the `AsyncHttpClient` or the `OkHttpClient`. It does work with `BlazeClient`.

When trying to view headers and a body of a request nothing seems to log (not even an empty log line). The `ResponseLogger` does work with all of the above clients.

See gitter discussion: https://gitter.im/http4s/http4s?at=5c3622f06370df0b91b56732

Have tried setting `<logger name="org.http4s.client.middleware" level="INFO"/>` in logback and my root logger to display `DEBUG`

**Comment by rossabaker** [comment]
This looks like a manifestation of #2348.
