### ISSUE TITLE
Strict query parameter matching

### ISSUE THREAD

**Issue by sideeffffect** [http4s/http4s#2347]
if I have this case in my `HttpService`
```scala
object OptionalYearQueryParamMatcher extends OptionalQueryParamDecoderMatcher[Int]("year")
...
case GET -> Root / "temperature" :? OptionalYearQueryParamMatcher(maybeYear) =>
```
it matches requests like `http://localhost/temperature` or `http://localhost/temperature?year=1` and that's fine.

but it also matches `http://localhost/temperature?superfluous=someval` or `http://localhost/temperature?year=1&superfluous=someval`

is there a way to do strict matching on the query parameters that doesn't allow any superfluous parameters to be present?

**Comment by rossabaker** [comment]
I can't think of anything built in that would do that.  All of them are designed to be chained with others, so none of them imply the absence of others.  Maybe you could do something like:

```scala
case req @ GET -> Root / "temperature" :? OptionalYearQueryParamMatcher(maybeYear) if req.params.size <= 1 => 
```

It might be possible to define an operator for an exclusive query matcher.  Anything you can do with extractors, you should be able to do here.  I just don't know offhand what syntax would be desired for this case.

**Comment by kevinmeredith** [comment]
Could you please say why you added RFC, @rossabaker? Does the RFC talk about this topic?

**Comment by aeons** [comment]
The label literally means request for comments :)
To get input from users on how this case should be handles so everyone's happy.

**Comment by kevinmeredith** [comment]
Thanks, @aeons. 

In my 2 years using `http4s` professionally, I've never had a concern or need to handle what @sideeffffect noted:

> is there a way to do strict matching on the query parameters that doesn't allow any superfluous parameters to be present?

**Comment by rossabaker** [comment]
The workaround with the if-guard seems to be sufficient here.
