### ISSUE TITLE
"BadResponse: LineFeed found without CR" exception

### ISSUE THREAD

**Issue by ermyas** [http4s/http4s#236]
Hello thanks for sharing this library,
I was trying to run the client code below which calls the Github API but it fails with the following exception "BaseExceptions$BadResponse: LineFeed found without CR". Any ideas what I might be doing wrong?
Thanks!

```scala
val client = org.http4s.client.blaze.defaultClient
val request = Request(method = GET, uri = uri("https://api.github.com/events"),
headers = Headers(Header("Accept", "application/json")))
val page: Task[String] = client(request).as[String]
println(page.run)

```

**Stack Trace**
  
22:30:32.999 [pool-5-thread-2] DEBUG org.http4s.blaze.pipeline.Stage - Beginning request: Request(GET,https://api.github.com/events,HTTP/1.1,Headers(Accept: application/json),Halt(End),org.http4s.AttributeMap@230f0031)

22:30:34.234 [pool-5-thread-1] DEBUG org.http4s.blaze.pipeline.Stage - SSL Read Request Status: Status = BUFFER_UNDERFLOW HandshakeStatus = NOT_HANDSHAKING
bytesConsumed = 0 bytesProduced = 0, java.nio.HeapByteBuffer[pos=0 lim=16921 cap=16921]

22:30:34.634 [Thread-4] DEBUG org.http4s.blaze.pipeline.Stage - SSL Read Request Status: Status = OK HandshakeStatus = NOT_HANDSHAKING
bytesConsumed = 341 bytesProduced = 303, java.nio.HeapByteBuffer[pos=303 lim=16921 cap=16921]

22:30:34.635 [Thread-4] DEBUG org.http4s.blaze.pipeline.Stage - SSL Read Request Status: Status = BUFFER_UNDERFLOW HandshakeStatus = NOT_HANDSHAKING
bytesConsumed = 0 bytesProduced = 0, java.nio.HeapByteBuffer[pos=0 lim=16921 cap=16921]

22:30:34.640 [pool-5-thread-2] ERROR org.http4s.blaze.pipeline.Stage - Error during client request decode loop
org.http4s.blaze.http.http_parser.BaseExceptions$BadResponse: LineFeed found without CR

22:30:34.641 [pool-5-thread-2] DEBUG org.http4s.blaze.pipeline.Stage - Stage org.http4s.client.blaze.Http1ClientStage sending outbound command: Disconnect

22:30:34.645 [pool-5-thread-2] DEBUG org.http4s.blaze.pipeline.Stage - org.http4s.blaze.pipeline.stages.SSLStage shutting down at Tue Mar 24 22:30:34 EST 2015

22:30:34.645 [pool-5-thread-2] DEBUG org.http4s.blaze.pipeline.Stage - Stage org.http4s.blaze.pipeline.stages.SSLStage sending outbound command: Disconnect

22:30:34.645 [pool-5-thread-2] DEBUG org.http4s.blaze.pipeline.Stage - closeWithError(EOF)

22:30:34.645 [pool-5-thread-2] DEBUG org.http4s.blaze.pipeline.Stage - org.http4s.client.blaze.Http1ClientStage shutting down at Tue Mar 24 22:30:34 EST 2015
[error] (run-main-0) org.http4s.blaze.http.http_parser.BaseExceptions$BadResponse: **LineFeed found without CR**

**Comment by bryce-anderson** [comment]
Thanks for the bug report @ermyas! I can reproduce this issue and will look into it. The client is relatively new so sorry for the bug. I'll post updates here.

**Comment by bryce-anderson** [comment]
OK, heres what I've found. Http4s client doesn't include a ```User-Agent``` header so github sends a 'Forbidden' response. It appears that this response doesn't use the correct ```\r\n``` and only ```\n``` when encoding the status line and headers. So technically, the parser is acting correctly. It seems reasonable to decrease the strictness of this and allow simple ```\n``` line endings, but I think thats for another ticket.
In the mean time, can you add a ```User-Agent: http4s-blaze``` header, eg
```scala
val req = Request(uri = uri("https://api.github.com/events")).withHeaders(Header.Raw("User-Agent".ci, "http4s-blaze"))
```
and make sure it works for you? It works on my end.

**Comment by ermyas** [comment]
Great thanks for that! Yes adding a User-Agent header does solve the problem on my end too.

**Comment by bryce-anderson** [comment]
This should have been closed long ago.
