### ISSUE TITLE
CORS Middleware docs example doesn't generate correct headers

### ISSUE THREAD

**Issue by CloudNiner** [http4s/http4s#2361]
The instructions on the [documentation site](https://http4s.org/v0.20/cors/) for adding CORS to a server do not work as expected. I would expect to see a longer response headers list that includes the appropriate CORS headers based on the default allow all CORSConfig().

Using:
- Scala 2.11.12
- http4s 0.20.0-M5

I typed the entirety of the first set of examples up to the [Configuration section](https://http4s.org/v0.20/cors/#configuration) into my project REPL and did not see CORS headers included in the response headers (the intermediate instructions that demonstrate a non-CORS request/response are omitted for simplicity):
```scala
import cats.effect._
import org.http4s._
import org.http4s.dsl.io._
import org.http4s.implicits._
import org.http4s.server.middleware._
val service = HttpRoutes.of[IO] {
  case _ =>
    Ok()
}
val corsService = CORS(service)
val originHeader = Header("Origin", "somewhere.com")
val request = Request[IO](Method.GET, Uri.uri("/"))
val corsRequest = request.putHeaders(originHeader)
val corsResponse = corsService.orNotFound(corsRequest).unsafeRunSync
// corsResponse: org.http4s.Response[cats.effect.IO] = Response(status=200, headers=Headers(Content-Length: 0))
corsResponse.headers
// res0: org.http4s.Headers = Headers(Content-Length: 0)
corsResponse.headers.size
// res1: Int = 1
```

I see the same result (headers not included) when I include the CORS middleware in my project:
```scala
import cats.effect._
import cats.implicits._
import org.http4s._
import org.http4s.dsl.io._
import org.http4s.implicits._
import org.http4s.server.blaze._
import org.http4s.server.middleware._
import org.http4s.server.Router

object MyServer extends IOApp {
  def run(args: List[String]): IO[ExitCode] =
    ServerStream.stream[IO].compile.drain.as(ExitCode.Success)
}

object ServerStream {
  def service[F[_]: Effect]: HttpRoutes[F] =
    new MyService[F].routes

  def stream[F[_]: ConcurrentEffect: Timer]: fs2.Stream[F, ExitCode] =
    BlazeServerBuilder[F]
      .bindHttp(8080, "0.0.0.0")
      .withHttpApp(Router("/" -> CORS(service)).orNotFound)
      .serve
}
```

Then making a request to that server with HTTPie:
```
http --print=Hh :4044/api/data Origin:foo.com
GET /api/data HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Host: localhost:4044
Origin: foo.com
User-Agent: HTTPie/0.9.9

HTTP/1.1 200 OK
Content-Length: 1359
Content-Type: application/json
Date: Thu, 17 Jan 2019 14:09:17 GMT
```

**Comment by vglushak** [comment]
I've encountered the same issue.
Something changed in Origin header parser.
If you provide header like "https://somewhere.com" it will add necessary CORS headers in output.

**Comment by CloudNiner** [comment]
Docs PR #2374 was merged to clarify behavior. Given that [scheme is a required part of the Origin header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Origin#Syntax) this can be closed. I wouldn't expect this middleware to support appending proper CORS headers for an out-of-spec Origin header.
