### ISSUE TITLE
Unexpected `request_count` increase for `4xx`

### ISSUE THREAD

**Issue by mr-git** [http4s/http4s#2394]
I made a small test application, mostly copy-pasted from examples, like:
```
object Main extends IOApp {
  override def run(args: List[String]): IO[ExitCode] =
    Server.stream[IO].compile.drain.as(ExitCode.Success)
}
object Server {
  def httpApp[F[_]: Effect: ContextShift: Timer: ConcurrentEffect]: HttpApp[F] = {
    val registry = CollectorRegistry.defaultRegistry
    DefaultExports.initialize()
    val prometheus = Prometheus(registry, "server")
    val websocketRoutes = Metrics[F](prometheus)(new WebSocketHttp[F].routes)

    Router(
      "" -> PrometheusExportService.apply[F](registry).routes,
      "" -> websocketRoutes
    ).orNotFound
  }

  def stream[F[_]: ConcurrentEffect: Timer: ContextShift]: Stream[F, ExitCode] = {
    BlazeServerBuilder[F]
      .bindHttp(8080)
      .withoutBanner
      .withHttpApp(httpApp[F])
      .serve
  }
}
```

`WebSocketHttp` is copy-pasted from from examples too, it is not really important, important is fact, that it is instrumented with metrics wrapping.

With this setup, each call on `/metrics` increases `request_count{classifier="",method="get",status="4xx",}` metric - it is logically expected, but I kind of expected, that metrics get counted only for those routes, which are wrapped in `Metrics` and which have path prefix match.

I am just starting with `http4s`, probably I made some mistake in setup.
It seems that `Metrics` notice, that none of assigned routes handled call and increases `4xx` counter.

Is there a way to not increase `4xx` in case, if none of wrapped routes handles request, but some other route handles it?

I am using `v0.20.0-M5`.

**Comment by ChristopherDavenport** [comment]
On HttpRoutes, if it falls through the metric system then it will by default increase to 404, however this can be tweaked by altering the parameters to your metric middleware.

https://github.com/http4s/http4s/blob/master/server/src/main/scala/org/http4s/server/middleware/Metrics.scala#L36

If you switch `emptyResponseHandler = None` then you should see the behavior you want.

**Comment by mr-git** [comment]
Thank you, good gentleman!
I didn't expect to such behaviour by default and I failed to understand the description of it.
