### ISSUE TITLE
Add Abstract PathVar with map function

### ISSUE THREAD

**Issue by diesalbla** [http4s/http4s#2405]
The `http4s` dsl provides a `PathVar` object defined as follows: 
```Scala
protected class PathVar[A](cast: String => Try[A]) {
  def unapply(str: String): Option[A] =
    if (!str.isEmpty)
      cast(str).toOption
    else
      None

}
```
It may be useful to have a super-trait `PathMatch[A]`, which had the following: 
- A single abstract method `unapply(str: String): Option[A]`, 
- A `map` method, that takes a converter function `A => B` and 
- An `emap` method, that takes a converter function `A => Option[B]` (or `Either`).

**Comment by fredshonorio** [comment]
This was marked as completed but I don't see anything like it in `main` or `series/0.23`, was it dropped by some reason?

**Comment by diesalbla** [comment]
@fredshonorio We closed it, but I am not sure there was "completed" labels in Github in 2020, so that must be a default value. You can do it if you think it would improve the library.
