### ISSUE TITLE
Is there a way to provide different buckets for Prometheus histogram?

### ISSUE THREAD

**Issue by mr-git** [http4s/http4s#2423]
In Prometheus, default histogram is defined as:
```java
private double[] buckets = new double[]{.005, .01, .025, .05, .075, .1, .25, .5, .75, 1, 2.5, 5, 7.5, 10};
```
It is used in `org/http4s/metrics/prometheus/Prometheus.scala:157` to measure response times.

The default bucket has good steps at start, but at is quite useless at end with resolution of 2.5s.

It would be nice, if there would be a way to set own bucket list, but I didn't find such.
Maybe it would be good idea to use custom bucket list, like:
```scala
responseDuration = Histogram
  .build()
  .buckets(0.005, 0.01, 0.02, 0.04, 0.08, 0.1, 0.2, 0.4, 0.8, 1, 1.2, 1.4, 1.6, 1.8, 2, 2.2, 2.4, 2.6, 2.8, 3, 3.2, 3.4, 3.6, 3.8, 4, 4.2, 4.4, 4.6, 4.8, 5, 5.2, 5.4, 5.6, 5.8, 6, 6.2, 6.4, 6.6, 6.8, 7, 7.2, 7.4, 7.6, 7.8, 8, 8.2, 8.4, 8.6, 8.8, 9, 9.2, 9.4, 9.6, 9.8, 10)
  //...
```

It has more than 4x buckets and has a bit better resolution on "fast" end and much better one on "slow" end, resolution is closer to linear - this can be useful in cases, when generated response depends on slow backend system(s).
It could be even useful to add `0.5` steps up to `20` seconds.

**Comment by kevinmeredith** [comment]
The `Histogram` class comes from https://github.com/prometheus/client_java/blob/master/simpleclient/src/main/java/io/prometheus/client/Histogram.java.

As a result, does this question qualify as an issue? In other words, might it be better to pose this question in StackOverflow?

**Comment by mr-git** [comment]
Current `http4s` API doesn't expose this ability and uses default bucket, which is quite shallow and wide...
Options:
* use the buckets as I mentioned in main
* close this as "not an issue" and forget about it
* complicate current API and expose ability to provide custom bucket list

**Comment by mr-git** [comment]
Default one is not very nice, when working with external systems with SLAs around 3..4 seconds - there are 2.5s and 5s buckets and "acceptable" calls are stored in "bad" bucket :)
2.5s wide steps are not very nice, and with heat-map panels in recent Grafana they look bad too

**Comment by ChristopherDavenport** [comment]
@mr-git @kevinmeredith 	Epimetheus-http4s currently supports this integration, but a PR here would be welcome that added buckets as List[Double] with the default being the default set that we currently have. 

https://github.com/ChristopherDavenport/epimetheus
https://github.com/ChristopherDavenport/epimetheus-http4s

**Comment by kevinmeredith** [comment]
Do you care about this in `0.18.x`, @mr-git, or it `0.20.x` sufficient?

I'm asking per https://github.com/http4s/http4s/pull/2510#issuecomment-483067592.

**Comment by mr-git** [comment]
0.20.x is sufficient. thanks for letting me know!
