### ISSUE TITLE
Upgrade from 0.20.0-M5 to 0.20.0-M6 causes specs2 matchers to fail

### ISSUE THREAD

**Issue by Fristi** [http4s/http4s#2428]
Since the upgrade of 0.20.0-M5 to 0.20.0-M6 causes specs2 matchers fail:

```
IO(Response(status=200, headers=Headers(Content-Length: 0))) != 
IO(Response(status=200, headers=Headers(Content-Length: 0)))
```

```scala
errorTranslate.translate(DocuSignEnvelopeProcessingError.UserNotFoundByEmail(refineMV("test@test.com"), EnvelopeId("id"))) must beEqualTo(Ok())
```

**Comment by rossabaker** [comment]
I can't think offhand what changed, but I would not compare `IO` with `equals`.  If you compare the `Response`s directly, you should find that they are equal.

**Comment by Fristi** [comment]
As @rossabaker suggested on gitter you can use these matchers to avoid testing on `IO` https://github.com/http4s/http4s/blob/master/testing/src/main/scala/org/http4s/testing/Http4sMatchers.scala
