### ISSUE TITLE
WaitQueueFailure defines incorrect method name

### ISSUE THREAD

**Issue by ChristopherDavenport** [http4s/http4s#2461]
https://github.com/http4s/http4s/blob/master/client/src/main/scala/org/http4s/client/PoolManager.scala#L16

defines message and does not define getMessage so throwable render with a null message. We can override that and delegate to message and maintain full compatibility.

**Comment by VladKopanev** [comment]
I would like to fix this!

**Comment by aeons** [comment]
Closed in #2466
