### ISSUE TITLE
Add anchors to changelog page

### ISSUE THREAD

**Issue by calvinbrown085** [http4s/http4s#2475]
Hi All 👋  I was trying to show a changelog today, and I realized that the changelog page doesn't have anchors to quickly link someone to the changelog i'm trying to reference,

https://http4s.org/changelog/

Thoughts on adding those ?

**Comment by rossabaker** [comment]
There is JavaScript that could do it automatically.  My front end skills are abysmal, but I'm :+1: to the idea.

**Comment by rossabaker** [comment]
I have been using paradox in http4s-jdk-http-client, whose material theme gives us this for free.  I'd like to port the https docs to that.

**Comment by armanbilge** [comment]
We have these now:
https://http4s.org/changelog.html
