### ISSUE TITLE
Client.fromHttpApp in Testing Documentation

### ISSUE THREAD

**Issue by ChristopherDavenport** [http4s/http4s#2497]
Our Testing Section of the documentation does not mention `Client.fromHttpApp`, or for that matter mention client testing, which is a significant portion of testing that individuals write. 

This is an place for more documentation under a `Client` header in on the `Testing` page. 

Where we introduce testing a client through this functionality.

Should be a good first issue, and will help to point people to existing testing approaches.

**Comment by vasiliybondarenko** [comment]
@ChristopherDavenport would you mind if create PR for this?
We are talking about this doc `docs/src/main/tut/testing.md`, right?

**Comment by key-eugene** [comment]
I guess it was a long tine since someone took this issue, I'll take this one.

**Comment by rossabaker** [comment]
Thanks, @key-eugene.

I'm sorry we all overlooked @vasiliybondarenko's offer earlier.  If you're still interested in contributing, we have plenty of similar tickets!

**Comment by aeons** [comment]
Closed by #4845
