### ISSUE TITLE
StaticFile.fromFile ignores modified ETag if unmodified since

### ISSUE THREAD

**Issue by ajluker** [http4s/http4s#2529]
StaticFile.fromFile will return early with a 302 if the resource has not modified since, ignoring the request ETag. If the ETag provided in the If-None-Match header is different from that of the resource, a 302 should not be returned, regardless of the not modified since check.

As far as I understand from the spec, both conditions need to be checked before returning a 302:

> If both an entity tag and a Last-Modified value have been
>         provided by the origin server, SHOULD use both validators in
>         cache-conditional requests.

This makes more sense if you consider rolling back a file to an older version, where the modification date is taken as when the version was authored, rather than when it was rolled back. Maybe this is unusual, although the above suggests it's covered in the spec and I just encountered it in the wild.

**Comment by ajluker** [comment]
Also, it looks like this code is looking up the "ETag" response header from the request, rather than the client If-None-Match header.

**Comment by rossabaker** [comment]
Fixed by #2571.
