### ISSUE TITLE
Error loading config

### ISSUE THREAD

**Issue by tampler** [http4s/http4s#2547]
Hello
Trying to load a config with pureconfig in v.0.20.0 like [this](https://github.com/Clover-Group/front/blob/cc28fb162031f1349f41a5a508f6ad2d6a3da0d6/src/main/scala/config/package.scala#L21).
This works, but I'm unhappy, since need to run the end-of-the-world inside a presumably pure function.
I found a [better solution](https://github.com/jaspervz/todo-http4s-doobie/blob/e28bfb2f7a55a9d16047398097c65a803d12982e/src/main/scala/Server.scala#L15), which worked in v.0.18.22, but fails now with the following:
```bash
[error] /home/bku/work/clover/front/src/main/scala/Server.scala:48:5: type mismatch;   │Untracked files:
[error]  found   : fs2.Stream[[x]Any,fs2.INothing]                                     │  (use "git add <file>..." to include in what will be committed)
[error]  required: fs2.Stream[F,Nothing]                                               │
[error]   }.drain 
```
How can I fix that? Wanna eliminate side effect

**Comment by ChristopherDavenport** [comment]
`Stream.eval(IO(Config.load()))`

**Comment by tampler** [comment]
Hi @ChristopherDavenport 
That doesn't work:
```bash
[error] /home/bku/work/clover/front/src/main/scala/Server.scala:44:23: value server is not a member of cats.effect.IO[config.Config]
[error] .bindHttp(cfg.server.port, cfg.server.host)
```
If I try to flatMap it again with the code below, I get again a value server is not a member of cats.effect.IO[config.Config]
```scala
    for {      
      cfg <- Stream.eval(IO(Config.load()))
      port <- cfg.server.port
    ....
 }
```
Any ideas ? Thank you

**Comment by ChristopherDavenport** [comment]
```scala
 for {      
      cfg <- Stream.eval(IO(Config.load()))
      port = cfg.server.port
    ....
 }
```

So key is that the for loop desugars to flatMaps, so everything to the right of a `<-` must be a `Stream[IO, ?]`, after the first line you can assign directly in the for loop as I ahve done above.

`port = cfg.server.port`

**Comment by tampler** [comment]
Thank you for the idea, but still doesn't work. I did this:
```scala
  def stream[F[_]: ConcurrentEffect](implicit T: Timer[F], C: ContextShift[F]): Stream[F, Nothing] = {
    //val cfg = load.unsafeRunSync
    
    for {
      
      cfg <- Stream.eval(IO(Config.load()))
      port = cfg.server.port
      host = cfg.server.host
      ...
      exitCode <- BlazeServerBuilder[F]
        .bindHttp(port, host)
        //.bindHttp(cfg.server.port, cfg.server.host)
        .withHttpApp(finalHttpApp)
        .serve
    } yield exitCode
  }.drain
```
and get the following:
```bash
[error] /home/bku/work/clover/front/src/main/scala/Server.scala:26:18: value server is not a member of cats.effect.IO[config.Config]
[error]       port = cfg.server.port
[error] /home/bku/work/clover/front/src/main/scala/Server.scala:46:19: type mismatch;
[error]  found   : Any
[error]  required: Int
[error]         .bindHttp(port, host)
```
What am I doing wrong tonight ?

**Comment by ChristopherDavenport** [comment]
Whats the signature of `Config.load()`?

**Comment by tampler** [comment]
My [config](https://github.com/Clover-Group/front/blob/cc28fb162031f1349f41a5a508f6ad2d6a3da0d6/src/main/scala/config/package.scala#L21)

**Comment by ChristopherDavenport** [comment]
Error was an concrete type attempting to be used in a function with an abstract type signature. Another option was to use `LiftIO[F].liftIO(Config.load())`


https://github.com/Clover-Group/front/pull/1

**Comment by tampler** [comment]
Thank you, Chris, worked like a charm! Type inference is still a complex topic...
I advice you to integrate pureconfig to your Giter8 template for others benefit

Thanks for a great project and a great support !

Boris
