### ISSUE TITLE
responseHeaderTimeout should be < idleTimeout

### ISSUE THREAD

**Issue by RafalSumislawski** [http4s/http4s#2550]
The `BlazeServerSpec` says ["A server should return a 503 if the server doesn't respond"](https://github.com/http4s/http4s/blob/master/blaze-server/src/test/scala/org/http4s/server/blaze/BlazeServerSpec.scala#L87) and it works like that in the test, but it does only because [response header time-out is set to 1 second](https://github.com/http4s/http4s/blob/master/blaze-server/src/test/scala/org/http4s/server/blaze/BlazeServerSpec.scala#L17). The default for `responseHeaderTimeout ` is 1 minute while the default for `idleTimeout` is 30 seconds (see: [BlazeServerBuilder](https://github.com/http4s/http4s/blob/master/blaze-server/src/main/scala/org/http4s/server/blaze/BlazeServerBuilder.scala#L402-L403) ). That means that when running with default configuration, the `idleTimeout` kicks in first, and instead of the nice behaviour of returning HTTP 503 response, we get an abrupt TCP connection termination, leaving the client with no clue what went wrong. 

IMO the defaults for the timeouts should be changed so that the `responseHeaderTimeout` is shorter than the `idleTimeout`. In addition to that, the blaze server could log a warning it is started with `responseHeaderTimeout >= idleTimeout`.

**Comment by rossabaker** [comment]
I agree with all of this, but what do we propose as the new values?

**Comment by RafalSumislawski** [comment]
I did some research on default timeouts used in other http client/server libraries:

- [`akka-http` ](https://github.com/akka/akka-http/blob/eb7311130021c6fa72dff05090c20568ee1319dd/akka-http-core/src/main/resources/reference.conf)
  - client-side: connecting-timeout = 10s
  - client-side: request-timeout not implemented
  - server-side: request-timeout = 20s
  - client-side: idle-timeout = 60 s
  - server-side: idle-timeout = 60 s
- [`lihaoyi/requests-scala`] (https://github.com/lihaoyi/requests-scala/blob/0c654ef3948e8e29c67d968ab4d08c325c1663ea/requests/src/requests/package.scala)
  - client-side: connectTimeout = 10s
  - client-side: readTimeout = 10s 
- [`sttp`](https://sttp.readthedocs.io/en/latest/conf/timeouts.html)
  - client-side: Connection timeout = 30s
  - client-side: Read timeout = 60s
- [`async-http-client`](https://github.com/AsyncHttpClient/async-http-client/blob/16bca5c66aca934e7653cdcb7f439f3bde659902/client/src/main/resources/org/asynchttpclient/config/ahc-default.properties)
  - client-side: connectTimeout = 5s
  - client-side: pooledConnectionIdleTimeout = 60s
  - client-side: readTimeout = 60s
  - client-side: requestTimeout = 60s
- [OkHttp client](https://github.com/square/okhttp/blob/master/okhttp/src/main/java/okhttp3/OkHttpClient.kt#L452)
  - client-side: connectTimeout = 10s
  - client-side: readTimeout = 10s
- [Tomcat 9](https://tomcat.apache.org/tomcat-9.0-doc/config/http.html) 
  - server-side: asyncTimeout = 30s // simillar to responseHeaderTimeout
- Jetty 9 [Server](https://stackoverflow.com/questions/25548341/jetty-idletimeout) / [client](https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/jetty-client/src/main/java/org/eclipse/jetty/client/HttpClient.java)
  - server-side: idleTimeout = 30s
  - client-side: connectTimeout = 15s
  - client-side: idleTimeout = 0 (no timeout)
  - client-side: requestTimeout = 0 (no timeout)

As far as I understand `readTimeouts` work similarly to `responseHeaderTimeout`.

Current http4s blaze defaults:
 - client-side: responseHeaderTimeout = 10.seconds,
 - server-side: responseHeaderTimeout = 1.minute
 - client-side: requestTimeout = 1.minute,
 - client-side: idleTimeout = 1.minute,
 - server-side: idleTimeout = 30.seconds

I would like to propose following values for http4s blaze defaults
 - client-side: connectingTimeout = 10.seconds, // coming soon
 - client-side: responseHeaderTimeout = Duration.Inf, // simplifies configuration
 - server-side: responseHeaderTimeout = 30.seconds // same as tomcat and jetty
 - client-side: requestTimeout = 45.seconds, // shorter than idle timeout, long enough to receive timeout responses from tomcat, jetty and akka-http
 - client-side: idleTimeout = 60.seconds,
 - server-side: idleTimeout = 60.seconds
In addition to that I would like to add runtime warnings in case `responseHeaderTimeout ` or `requestTimeout` is larger than `idleTimeout`.
 
 A note on `responseHeaderTimeout`:
 Http4s client has two timeouts which are designed to cancel a request when it's taking too long. The `responseHeaderTimeout` and the `requestTimeout`. `responseHeaderTimeout` handles only a subset of scenarios handled `requestTimeout`. It is reasonable to use the client with just `requestTimeout`, but it's unreasonable to use the client with just `responseHeaderTimeout`. For example if the servers starts sending the response early, but it's sending it very slowly, the `requestTimeout` will kick-in, the `responseHeaderTimeout` wouldn't. That doesn't mean that `responseHeaderTimeout` is useless, rather that it's an advanced feature, not necessary in basic setup. Setting `responseHeaderTimeout` to `Inf` by default, makes timeout configuration more straightforward. 
 
A note on `idleTimeout`:
Idle timeouts result in abrupt TCP connection termination. IMO they should be used for:
 - shrinking of connection pools.
 - protecting against resource leaks

but not for:
 - business-level control of request execution time

**Comment by RafalSumislawski** [comment]
@rossabaker 
I'll wait from some comments/discussion in this issue. Once everything is clear, I can provide a PR.

**Comment by sergiojoker11** [comment]
Can I suggest to update the ResponseLogger responseHeaderTimeout error message (service request canceled) to something more meaningful if the only reason for that message to show up is that the request timeout?

**Comment by rossabaker** [comment]
@sergiojoker11 I'm not sure that would be the case.  What if the response gets canceled by the service itself?  All we know at that logger level is that we were canceled, without a reason.

**Comment by sergiojoker11** [comment]
If the response gets canceled by the service itself it should say so IMO otherwise one will never be able to distinguish between these different scenarios.

**Comment by armanbilge** [comment]
I think this can be closed as of https://github.com/http4s/http4s/pull/2746.
