### ISSUE TITLE
Path swallows trailing slash

### ISSUE THREAD

**Issue by mossprescott** [http4s/http4s#257]
The way the `Path` extractor abstraction works make it impossible to tell the difference between a path like `/foo/bar` (a file) and `/foo/bar/` (a directory with the same name). See https://github.com/http4s/http4s/blob/v0.6.5/dsl/src/main/scala/org/http4s/dsl/Path.scala#L18-24.

Although most applications might not consider that distinction significant, there's apparently nothing in the URI spec that says they must be treated the same. As it happens, we'd like to use both names for different semantic entities. See discussion here: https://github.com/slamdata/slamengine/issues/675.

We can work around it, but it's painful since it's woven into the whole method/path/params dsl.

**Comment by jdegoes** [comment]
:+1: Would you consider accepting a PR for this issue?

**Comment by rossabaker** [comment]
Absolutely!  I think it's an important distinction to be able to make.

**Comment by jdegoes** [comment]
@rossabaker Awesome! Any pointers for where / how to fix this or should we just dive right in? /cc @mossprescott

**Comment by rossabaker** [comment]
Not much off the top of my head, but:
* Make sure `request.pathInfo` isn't somehow eating it (i.e., is it an input error or a DSL error?)
* A committer emeritus ripped this DSL from Finagle.  See whether a similar bug was noticed and fixed there.

**Comment by jdegoes** [comment]
Thanks for the pointers!

**Comment by bryce-anderson** [comment]
@rossabaker: are we going to hold the release for this? If it's not a long
endeavor I think it would be good to get in.

**Comment by rossabaker** [comment]
Yes, let's leave the door open for this one.

**Comment by mossprescott** [comment]
I'll take a closer look soon and figure out where the slash is being trimmed off. Then we'll have to decide how to represent this in the DSL:

Option 1: a trailing slash becomes a final `""` segment in the Path. This is how dispatch handles it (see [here](http://dispatch.databinder.net/Defining+requests.html#Appending+path+elements)); it's simple and it would allow you to pattern match with something like `case GET -> Root / "foo" / dirName / "" =>`. On the other hand, it would *require* you to match that way, and most likely break the common usage (where you just say `Root / "foo"` and expect it to match both `/foo` and `/foo/`). So although this would be best for us, I suspect it's not a viable solution.

Option 2: keep the existing properties of `Path` as is, and add a new property to distinguish between the two possibilities. This would be enough for slamengine's purposes, and won't break anyone, but it's not obvious to me how to make that accessible in the DSL. Also, I don't have any good ideas for what to call the new property (`isDir: Boolean` :see_no_evil:).

Thoughts?

**Comment by rossabaker** [comment]
Option 1 seems reasonable to me.  It would be possible to write a middleware function to chop a trailing slash for looser matching.  It's a bit regrettable to change the default behavior, but that's why it's still major version 0.
