### ISSUE TITLE
Remove Uri.uri calls in the docs.

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#2603]
`Uri.uri(...)` is deprecated in favor of a `StringContext` macro.  We should replace all those calls in the tuts with `uri"..."`.

Reported in #2598.  Preventing this in the build in #2602.  Separated as a quick win for someone looking for a first issue.

**Comment by mcintdan** [comment]
May I please be assigned this issue? I am a new contributor and believe I could help fix the documentation. :-)

**Comment by rossabaker** [comment]
@mcintdan :+1: thanks!  Please let us know here or on gitter if you need any help.

**Comment by rossabaker** [comment]
Oops, this is already fixed.  We just neglected to close it.
