### ISSUE TITLE
String contexts for literals: where should they live?

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#2616]
Regarding our string context macros (e.g., `uri`), @yoohaemin brings up on #2608:

> I was a bit surprised that the required import was not org.http4s.syntax.all._ nor org.http4s.implicits._ (which is the same thing), but org.http4s._

They're a syntactic extension, so putting them in implicits fits my intiution.  And I like our imports to fit in well with the Typelevel ecosystem, but there isn't a lot of precedent.

This issue is to discuss, before we write more: did we put them in the right place?

**Comment by ChristopherDavenport** [comment]
They should be in implicits.

**Comment by kubukoz** [comment]
Definitely implicits. I had a hard time importing the uri interpolator because it's in `org.http4s`.

**Comment by rossabaker** [comment]
I agree.  Does anybody have a clean migration strategy through deprecation, or can we only achieve this through scalafix?

**Comment by ChristopherDavenport** [comment]
I think scalafix due to implicit conflicts.
