### ISSUE TITLE
Request fails to build a JSON

### ISSUE THREAD

**Issue by tampler** [http4s/http4s#2621]
Hello 
Working to integrate http4s with ZIO. Wrote a simple [json test here](https://github.com/Clover-Group/zio_front/blob/1832ee6590fa63a90750415c7008cb99f1d1f43b/src/test/scala/http/JsonSpec.scala#L41).

However, I get an error, see below:
```bash
sbt:front> test
[info] HTTPSpec:
Fiber failed.
A checked error was not handled.
org.http4s.MalformedMessageBodyFailure: Malformed message body: Invalid JSON
        at org.http4s.circe.CirceInstances$.$anonfun$defaultCirceParseError$1(CirceInstances.scala:179)
        at cats.syntax.EitherOps$.leftMap$extension(either.scala:144)
        at org.http4s.circe.CirceInstances.$anonfun$jsonDecoderByteBufferImpl$1(CirceInstances.scala:37)
```
I guess http4s is the victim. Using 0.21-SNAPSHOT, ZIO 1.0-RC5, Circe - 0.12.0-M2

**Comment by rossabaker** [comment]
http4s master is still on circe-0.11.1.  I doubt that's this problem, but it's _a_ problem.

**Comment by tampler** [comment]
So what should I do? Do you want me to stick to 0.11.1 ?

**Comment by tampler** [comment]
Upd: I get the error for Circe 0.11.1
```bash
[info] JsonSpec:
[info] Simple Service
[info] - should create new todo items
[info] - work with json *** FAILED ***
[info]   scalaz.zio.FiberFailure: Fiber failed.
[info] A checked error was not handled.
[info] org.http4s.MalformedMessageBodyFailure: Malformed message body: Invalid JSON
[info]  at org.http4s.circe.CirceInstances$.$anonfun$defaultCirceParseError$1(CirceInstances.scala:179)
[info]  at cats.syntax.EitherOps$.leftMap$extension(either.scala:144)
[info]  at org.http4s.circe.CirceInstances.$anonfun$jsonDecoderByteBufferImpl$1(CirceInstances.scala:37)
```

**Comment by aeons** [comment]
If you dig a bit deeper, the next exception is
```
Caused by: io.circe.ParsingFailure: expected json value got 'The re...' (line 1, column 1)
```
So something somewhere is not correctly turned into json.

**Comment by travisbrown** [comment]
See my answer [here](https://github.com/circe/circe/issues/1146)—the issue is that the JSON you're posting can't be decoded into the appropriate type, so you get a 4xx-whatever with an error message in the body (probably the `The re...` in @aeons's comment), which your test tries to decode into something and fails.

**Comment by travisbrown** [comment]
…so the solution is to make sure the `io.circe.Json` value you're passing to `withEntity` can actually be decoded as the Scala type the endpoint expects.

**Comment by rossabaker** [comment]
Thanks, Travis.
