### ISSUE TITLE
RequestLogger ignores redactHeadersWhen

### ISSUE THREAD

**Issue by IssueMonoid** [http4s/http4s#2639]
In server/middleware/RequestLogger.scala the redactHeadersWhen argument is omitted in a call to  Logger.logMessage which results in sensitive headers being logged.

**Comment by rossabaker** [comment]
Already a PR open in #2638 for 0.20.x.  If you're related to the team that needs it for 0.18.x, I'll cut a release when we get a PR.

**Comment by IssueMonoid** [comment]
yes I submitted a PR for 0.18 https://github.com/http4s/http4s/pull/2640

**Comment by aeons** [comment]
Closed by #2641
