### ISSUE TITLE
Static file service

### ISSUE THREAD

**Issue by bryce-anderson** [http4s/http4s#265]
While a lot of people will probably want to serve their files from nginx or some other dedicated file server when pushing static content to the wire, I often find myself cut and pasting the ```ResourceCache``` class I slapped together for the demo. It would be pretty convenient to have a pre packaged file service. In my minds eye, I see this supporting:
* Actual files
* Static resources
* Caching strategies
* byte ranges

(this list has been updated since creation)

I'm just spit balling here, comments welcome.

**Comment by ritschwumm** [comment]
As soon as you have somewhat bigger resources (video, audio..) you probably want to support ranges

**Comment by LeifW** [comment]
I've liked using the "static app" thing over on WAI:
https://hackage.haskell.org/package/wai-app-static-3.0.1/docs/Network-Wai-Application-Static.html
Just takes some settings, and gives you an "Application" (Application is their Request => Response type alias)
They also provide 4 different settings objects to use (or use as a starting point), with defaults suited for webapps, static file servers, or in-memory (a Map[FilePath, Bytes]).

**Comment by bryce-anderson** [comment]
I've made some progress on this. See PR #271. I'd appreciate comments, etc.

**Comment by bryce-anderson** [comment]
Closed by 411805fbd85034a614732e74efab4e95c17f138b.
