### ISSUE TITLE
Websocket close : EOF

### ISSUE THREAD

**Issue by ikempf** [http4s/http4s#2651]
I'm using http4s 0.20.3 (with blaze-server) for my websocket backend.

I tested numerous websocket clients against it and often get the following error when closing the connection :
```
http4s-eof 15:26:15.903 [scala-execution-context-global-38] ERROR org.http4s.blazecore.websocket.Http4sWSStage - Error closing Web Socket
http4s-eof org.http4s.blaze.pipeline.Command$EOF$: EOF
http4s-eof 	at org.http4s.blaze.pipeline.Command$EOF$.scala$util$control$NoStackTrace$$super$fillInStackTrace(Command.scala:23)
http4s-eof 	at scala.util.control.NoStackTrace.fillInStackTrace(NoStackTrace.scala:28)
http4s-eof 	at scala.util.control.NoStackTrace.fillInStackTrace$(NoStackTrace.scala:27)
http4s-eof 	at org.http4s.blaze.pipeline.Command$EOF$.fillInStackTrace(Command.scala:23)
http4s-eof 	at java.lang.Throwable.<init>(Throwable.java:265)
http4s-eof 	at java.lang.Exception.<init>(Exception.java:66)
http4s-eof 	at org.http4s.blaze.pipeline.Command$EOF$.<init>(Command.scala:23)
http4s-eof 	at org.http4s.blaze.pipeline.Command$EOF$.<clinit>(Command.scala)
http4s-eof 	at org.http4s.blaze.channel.nio1.NIO1HeadStage$$anon$3.run(NIO1HeadStage.scala:322)
http4s-eof 	at org.http4s.blaze.util.TaskQueue.go$1(TaskQueue.scala:82)
http4s-eof 	at org.http4s.blaze.util.TaskQueue.executeTasks(TaskQueue.scala:99)
http4s-eof 	at org.http4s.blaze.channel.nio1.SelectorLoop.org$http4s$blaze$channel$nio1$SelectorLoop$$runLoop(SelectorLoop.scala:166)
http4s-eof 	at org.http4s.blaze.channel.nio1.SelectorLoop$$anon$1.run(SelectorLoop.scala:67)
http4s-eof 	at java.lang.Thread.run(Thread.java:748)
```

This seems to only happen when the connection is closed by the server. Cleanly closing from the client side does not result in the above error log.

Some clients seem to never encounter the error (Akka-http, and some gui clients: [Web Socket Client](https://chrome.google.com/webstore/detail/web-socket-client/lifhekgaodigcpmnakfhaaaboididbdn), [Smart WebSocketClient](https://chrome.google.com/webstore/detail/smart-websocket-client/omalebghpgejjiaoknljcfmglgbpocdp), [Browser Websocket client](https://chrome.google.com/webstore/detail/browser-websocket-client/mdmlhchldhfnfnkfmljgeinlffmdgkjo?hl=en)).
For other clients (AsyncHttp, JavaWebsocket, rust-websocket) the error is *almost* systematic. There is something not deterministic that very probably is time related, by placing some sleeps between the protocol messages the error will sometimes not manifest.

The weirdest part is that I sniffed the network with wireshark and the exchanged messages respect the rfc and are 100% identical for all the clients I tested, but the result is obviously different.

Any idea ? Am I misunderstanding the websocket protocol (I read the closing [handshake rfc](https://tools.ietf.org/html/rfc6455#page-9)) or are there some resources that are not being freed correctly by the blaze backend ?

Here are some [code samples](https://github.com/ikempf/http4s-eof) of my tests. I also tried the Jetty backend but I think websockets are not supported.

**Comment by kubukoz** [comment]
I encountered this with websocat, but not raw WS from the browser. Might be helpful.

**Comment by ikempf** [comment]
I just tested it with websocat and indeed it also produces an EOF.

Websocat closes first
```
echo "test" | websocat  ws://127.0.0.1:8080/wsclose
=> org.http4s.blaze.pipeline.Command$EOF$: EOF
```

Server closes first
```
websocat -E  ws://127.0.0.1:8080/wsclose
test
=> org.http4s.blaze.pipeline.Command$EOF$: EOF
```

**Comment by rossabaker** [comment]
It's correct that there is not yet a servlet implementation of web sockets.  The servlet implementations require ownership of the whole namespace, rather than fitting into our existing model where it's an attribute of the response.

I think we might be able to clean this up by handling EOF in the `sendClose` call.

**Comment by rossabaker** [comment]
Recovering it in `sendClose` didn't fix it, but I've proposed a less surgical fix in #2695.

**Comment by kubukoz** [comment]
Confirmed to work with websocat after #2695, is that going to master too? :)

**Comment by rossabaker** [comment]
Yes, when I get back to my laptop.

**Comment by ikempf** [comment]
Thx for looking into the issue, I just tested it out on 0.20.4 and it works great.
