### ISSUE TITLE
Drop Scala 2.11 support

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#2660]
Some of our integrations have dropped or are dropping scala 2.11 support.

* scalatags
* scala-xml
* circe (proposed: https://github.com/circe/circe/pull/1176)

Scala 2.11 represented approximately 5% of our downloads according to Maven Central's (dubious) stats.

Our core libraries all support 2.11, so we can continue to support it, with a bit of cross versioning in our integrations.  We have an increasing amount of complications because of it, and it's common for libraries to only support two versions of Scala concurrently.  Is it time?

Discuss.

**Comment by ChristopherDavenport** [comment]
I'm mildly against this. So long as our core supports it I don't see a great reason to drop it. However most folks still on 2.11 likely aren't on the newest versions.

**Comment by rossabaker** [comment]
Part of my work is on Scala 2.11, and that part is on old versions of everything.

All of my previous work was on 2.10 and 2.11, and making it work was part of my job.  That's no longer.

We help people incrementally migrate when we're generous in support, but at the expense of our own limited time.

I'm mildly in favor of keeping 2.11, but decreasigly so.  I think 0.21 might be the end.

**Comment by aeons** [comment]
I am in favor of dropping 2.11, even on 0.21. I don't have any strong feelings on this either way though.

**Comment by rossabaker** [comment]
Circe dropped 2.11 in the latest milestone, so we'll definitely need a strategy on master.

**Comment by ChristopherDavenport** [comment]
I think it likely that those on 2.11 just aren't on the newest stuff. I don't think it's a bad idea to drop it under the condition that one of our most used modules can no longer support it.

**Comment by rossabaker** [comment]
Per June Sonatype stats:
- 10% of all core downloads are 2.11
- 4% of all core downloads were 2.11 without circe.  These are the marginal users we'd leave behind.
- 63% of 2.12 users are on http4s >= 0.20, vs. 24% of 2.11 users 
- 2.11 downloads are down 50% (vs. up 13% for 2.12)

If the last three populations are independent, we're talking about roughly 1% of our users with a half-life of a month.  And we can support them with binary-compatible fixes for as long as people send them to us.  I think it's time.

**Comment by rossabaker** [comment]
The result of #2694 is a small net loss in code, simpler imports, reduced build times, and more flexibility to maintain binary compatibility with abstract classes in 0.21.

**Comment by ijuma** [comment]
Good call in my opinion, especially with the recent release of 2.13.0.

**Comment by hamnis** [comment]
Scala `2.11` has been dropped in `0.21`. Looks like 2.11 will be dropped from cats as well, so closing this.
