### ISSUE TITLE
Scalafix the string contexts to org.http4s.implicits

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#2667]
We couldn't do #2661 through our normal deprecation cycle.  This would be very nice to have a scalafix for, but I'm not sure how to conditionally add an import.  Rewriting old references to call the string contexts explicitly would keep code compiling, but be horribly ugly.

This is beyond my scalafix skills.

**Comment by armanbilge** [comment]
This seems old and unlikely to happen.
