### ISSUE TITLE
Provide QueryParamMatchers for the various java.time data types

### ISSUE THREAD

**Issue by LukaJCB** [http4s/http4s#2670]

**Comment by kevinmeredith** [comment]
Do you have any opinions on which [java.time.format.DateTimeFormatter](https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html) is appropriate, @LukaJCB? How about `ISO_OFFSET_DATE_TIME`?

```scala
@ import java.time._, java.time.format._

@ DateTimeFormatter.ISO_OFFSET_DATE_TIME.parse(Instant.now.toString) 
res21: temporal.TemporalAccessor = {OffsetSeconds=0, InstantSeconds=1562730675},ISO resolved to 2019-07-10T03:51:15.050

@ Instant.from 
def from(x$1: java.time.temporal.TemporalAccessor): java.time.Instant
@ Instant.from(res21) 
res22: Instant = 2019-07-10T03:51:15.050Z
```

**Comment by kevinmeredith** [comment]
@LukaJCB - https://github.com/http4s/http4s/pull/2724 added support for `Instant`. What other types would you find useful - `ZonedDateTime` and `LocalDate`?

**Comment by m-sp** [comment]
I think we can close this one right? feel free to reopen if this is not completely done yet
