### ISSUE TITLE
FollowRedirect middleware needs to support CookieJar functionality

### ISSUE THREAD

**Issue by abhsrivastava** [http4s/http4s#2680]
Currently the FollowRedirect middleware doesn't collect and pass the cookies between various redirects. 

This functionality is needed if we make a call to an endpoint which re-directs to an authentication endpoint which sets cookies and then re-directs again to the original endpoint.

For this authentication handshake to work, cookies must be preserved and transmitted as required during the re-directs.

**Comment by rossabaker** [comment]
Have you seen #2623?

**Comment by rossabaker** [comment]
I think #2623 addresses this.  If not, please reopen.
