### ISSUE TITLE
Client hangs indefinitely on connection, ignores `requestTimeout` setting

### ISSUE THREAD

**Issue by kamilkloch** [http4s/http4s#2690]
For what it's worth, both `curl` and `sttp` client cancel the same connection after the provided timeout.

**Comment by rossabaker** [comment]
Which backend are you using?  In what context are you seeing this?  Do you have code that would help reproduce this?

And yes, we have cancellation as well.

**Comment by kamilkloch** [comment]
> Which backend are you using? In what context are you seeing this? Do you have code that would help reproduce this?

Version `0.20.3`. I am querying a host which is filtered on the firewall. Requests hang and slowly eat up client's wait queue until it's full. 

> And yes, we have cancellation as well.
Do you mean Timeout middleware?

**Comment by RafalSumislawski** [comment]
Looks very similar to #2386. #2386 is fixed in a way which makes it *eventually* (15 seconds on my machine) time out. It doesn't respect the configured timeout. May this be what you're experiencing? Or do they actually **never** time out?

**Comment by kamilkloch** [comment]
@RafalSumislawski The request is stuck forever. Behaviour is reproducible with the snippet from #2386, just replace `http://1.2.3.4:nn` with any host:port so that the port is filtered on the host firewall.

**Comment by RafalSumislawski** [comment]
@kamilkloch On what OS are you trying it? The behaviour of establishing TCP connections differs between OSes.

**Comment by kamilkloch** [comment]
@RafalSumislawski Ubuntu.

**Comment by RafalSumislawski** [comment]
One more thing: What version of cats-effect do you have on your classpath?

**Comment by kamilkloch** [comment]
1.3.0.

**Comment by kevinmeredith** [comment]
Hi @RafalSumislawski - do you expect https://github.com/http4s/blaze/pull/308 and/or https://github.com/http4s/http4s/pull/2736 have resolved this issue? I'm asking as an interested user of this library. Thanks

**Comment by RafalSumislawski** [comment]
Hi
Yes, I expect they've solved it, although I can't be sure, as I wasn't able to reproduce it.

**Comment by rossabaker** [comment]
I think it did. Please reopen if it's still a problem.
