### ISSUE TITLE
Using predefined status responses without extending Http4sDsl

### ISSUE THREAD

**Issue by valenterry** [http4s/http4s#2725]
Is there an easy way to use use e.g. `NotFound()` without extending `Http4sDsl`?

I would imagine something like `import import org.http4s.magic` and then `magic.NotFound[IO]()` or `magic.NotFound[F]()`

**Comment by rossabaker** [comment]
For hardcoded IO:

```scala
import org.http4s.dsl.io._

object MyHttpApp {
  // Your HTTP code here
}
```

For other hardcoded concrete effect types:

```scala
object monixDsl extends org.http4s.dsl.Http4sDsl[Task]
import monixDsl._

object MyHttpApp {
  // Your HTTP code here
}
```

For polymorphic effect types:

```scala
trait MyHttpApp[F[_]] {
  object dsl extends Http4sDsl[F]
  import dsl._

  // your HTTP code here
}
```

I prefer polymorphic, and I prefer to extend `Http4sDsl[F]` rather than create the boilerplate object to import.  But all of those techniques should work, depending on your desires.

**Comment by valenterry** [comment]
Thank you - I was looking for the last example. Should have probably figured that out myself, haha.

Do you think it makes sense to add dsl methods in a more static way so that they could be used, passing the effect type on-call rather than fixing in for the object?

**Comment by rossabaker** [comment]
We tried that when we decoupled from the old `fs2.Task`, and the type inference was terrible, and I remember not liking the explicit calls.  I think it looked like `Ok[F]("blah")`.  Making it part of the DSL, which has to be specified once, seemed better than repeating the parameter on every DSL call.

I'm open to new experimentation on it, though even if it works, it's probably a hugely breaking change and would need a different name.

**Comment by ChristopherDavenport** [comment]
Do not use object. That creates a reference to itself. `val dsl = new Http4sDsl[F]{}; import dsl._` is a one liner that makes it fairly convenient, and doesn't leak in methods.

**Comment by valenterry** [comment]
I think we should make a convenience-function for what @ChristopherDavenport said. When using final tagless, the same style is used anyways, e.g.:
`doSomethingBasedOn[F](request) >> Logger[F].log("Action executed") >> Ok[F]("All good")`

**Comment by rossabaker** [comment]
The `val dsl` one-liner can't be a function, because functions can't import.  There's an `apply` on the companion, so we might be able to golf it down to:

```scala
val dsl = Http4sDsl[F]; import dsl._
```

The type parameter is not in the right place for `Ok[F]("all good")` syntax in the DSL, because it's not inferred in the traditional usage.  It could be done, but I don't think it can be done with the same machinery as the existing DSL.  If you cant extend the DSL or use the one-liner, I'd probably just not use the DSL at all. `Response[F](Ok).withEntity("All good")` is a little more verbose, but a lot less magical.

**Comment by ChristopherDavenport** [comment]
Not saying we should do it, but the import trick specifically does work. 

```
@ import $ivy.`org.http4s::http4s-dsl:0.21.0-M2`
import $ivy.$

@ import cats.effect._, cats.implicits._, org.http4s._, org.http4s.dsl._
import cats.effect._, cats.implicits._, org.http4s._, org.http4s.dsl._

@ def Ok2[F[_]: Sync, A: EntityEncoder[F, ?]](a: A): F[Response[F]] = {
     val dsl = new Http4sDsl[F]{}; import dsl._
     Ok(a)
  }
defined function Ok2
```

**Comment by valenterry** [comment]
I like that. Seems we can create these methods without breaking existing code and proving them under a different namespace with the same names, so that the user can choose which style they prefer. If you think it's a good idea, I can make a PR.

**Comment by rossabaker** [comment]
`org.http4s.dsl.tagless`, maybe?

**Comment by valenterry** [comment]
> `org.http4s.dsl.tagless`, maybe?

Let me make a draft PR and see how it feels :)

**Comment by rossabaker** [comment]
Closing due to inaction.  Please reopen if still interested.
