### ISSUE TITLE
client EmptyRequestGenerator and EntityRequestGenerator return types

### ISSUE THREAD

**Issue by rnd4222** [http4s/http4s#2738]
Client's `EmptyRequestGenerator` and `EntityRequestGenerator` does have `apply` methods, that returns `F[Request[F]]`.
However, both methods uses `F.pure` and there is absolutely no reason to wrap it in such way.
Shouldn't it return just `Request[F]` instead?

**Comment by rossabaker** [comment]
That's a fair question.  Entity encoding used to be effectful, so lifting into `F` made them consistent with the ones that take a body.  There is probably much less argument for that now, other than inertia.  People using it to pass directly to the client would be unaffected, but it might turn some `flatMap`s into `map`s.

I can't think of another reason _not_ to change this.

**Comment by ChristopherDavenport** [comment]
We should do this, last I heard the only reason not to presently was Rho.

**Comment by rossabaker** [comment]
I can't think of a reason that would be bad for rho.  Putting apply directly on the status would be.  This is in client, so I don't think rho is affected at all.  @zarthross, am I missing anything?

**Comment by zarthross** [comment]
Since `EmptyRequestGenerator` and `EntityRequestGenerator` are both in the client it will have no impact on Rho since its not even a dependency.  

As @rossabaker said, having a apply on status could potentially be problematic.

**Comment by Lasering** [comment]
This would also simplify the Client API (#2483) and could be made simultaneously to achieve a better and more consistent API.

**Comment by rossabaker** [comment]
Okay, let's move forward with it for 1.0.  I think it might be tedious to fix the tests, but good practice.  Volunteers?
