### ISSUE TITLE
Wrong Router call in authentication tutorial

### ISSUE THREAD

**Issue by qwe2** [http4s/http4s#2764]
There's the following piece in the authentication tutorial (https://http4s.org/v0.20/auth/):

> Use a Router with unique route prefixes
> ```scala
> val service = Router {
>   "/spanish" -> middleware(spanishRoutes)
>   "/french" -> frenchRoutes
> }
> ```

`Router` takes a vararg, so this actually only passes the last route. Should be

```scala
val service = Router(
  "/spanish" -> middleware(spanishRoutes),
  "/french" -> frenchRoutes
)
```

**Comment by rossabaker** [comment]
Ugh.  Good find.  Thank you!

**Comment by m-sp** [comment]
thanks again, this has been fixed quite some time ago
