### ISSUE TITLE
Socket Options Integrated Into Ember

### ISSUE THREAD

**Issue by ChristopherDavenport** [http4s/http4s#2768]
FS2 Just Integrated in Support for various socket options into the fs2 Socket code.

https://github.com/functional-streams-for-scala/fs2/pull/1549

So when released, we should continue this support into ember to offer the ability to configure the client and server with these changes.

**Comment by vilu** [comment]
I would like to give this one a go.

**Comment by vilu** [comment]
I've pushed a draft of how I imagine it would be done when the new fs2 version would be released. Would love some feedback if things aren't looking ok.
