### ISSUE TITLE
Make TrustingSslContext available in BlazeClientBuilder

### ISSUE THREAD

**Issue by ikr0m** [http4s/http4s#2786]
Looks like, before we could disable SSL Handshake checking with `TrustingSslContext`. For this we had to get [This Context](https://github.com/http4s/http4s/blob/6a8f3bc477e1a70971b16700314d710b312af362/blaze-client/src/main/scala/org/http4s/client/blaze/bits.scala#L24) into [BlazeClientBuilder.apply](https://github.com/http4s/http4s/blob/6a8f3bc477e1a70971b16700314d710b312af362/blaze-client/src/main/scala/org/http4s/client/blaze/BlazeClientBuilder.scala#L218)
But after switching off `BlazeConfig`, this functionality is not available anymore.
This is the sample code which gives `SSLHandshakeException`:
```
object Main extends IOApp {
  def run(args: List[String]): IO[ExitCode] = {
    val uri = Uri.uri("https://...")
    BlazeClientBuilder[IO](global).resource.use { client: Client[IO] =>
      client.get(uri) { _=>
        IO()
      }
    }.as(ExitCode.Success)
  }
}
```
`TrustingSslContext` should be brought into context to disable ssl handshake checking.

**Comment by rossabaker** [comment]
That was removed from the public API for two reasons:

1) It has nothing to do with HTTP.  More Scala-like configuration of SSL Contexts belongs in a separate library.
2) It's almost always a horrible idea.

You should be able to copy that SSLContext and pass it into blaze builder if you really want to disable all checks.

**Comment by ikr0m** [comment]
You're right. I was recommended to create this issue because it was worked before and then stopped working after some changes.
I'm going to close this issue and provide workaround to disable ssl handshake checking. This issue can be reopened if necessary.
```scala
import java.security.SecureRandom
import java.security.cert.X509Certificate
import cats.effect.{ExitCode, IO, IOApp}
import cats.implicits._
import javax.net.ssl.{SSLContext, X509TrustManager}
import org.http4s.Uri
import org.http4s.client.blaze.BlazeClientBuilder
import scala.concurrent.ExecutionContext.Implicits.global

object Main extends IOApp {
  def run(args: List[String]): IO[ExitCode] = {
    val uri = Uri.uri("https://...")
    lazy val TrustingSslContext: SSLContext = {
      val trustManager = new X509TrustManager {
        def getAcceptedIssuers(): Array[X509Certificate] = Array.empty
        def checkClientTrusted(certs: Array[X509Certificate], authType: String): Unit = {}
        def checkServerTrusted(certs: Array[X509Certificate], authType: String): Unit = {}
      }
      val sslContext = SSLContext.getInstance("TLS")
      sslContext.init(null, Array(trustManager), new SecureRandom)
      sslContext
    }

    BlazeClientBuilder[IO](global, Some(TrustingSslContext)).resource.use { client =>
      client.get(uri) { response =>
        response.bodyAsText.compile.toList.flatMap(s => IO(println(s)))
      }
    }.as(ExitCode.Success)
  }
}
```

**Comment by Lasering** [comment]
This would be very useful to test in development environments where the certificate is self-signed, or issued by a self-signed untrusted CA.
