### ISSUE TITLE
content-type charset for media-type 'application/json' should default to UTF-8

### ISSUE THREAD

**Issue by driak** [http4s/http4s#279]
Hi,

When working with json it seems the HTTP4S uses the wrong character set encoding, resulting in garbled string values.

A json property value containing the UTF-8 character \u00EB  ('ë') turns into something like 'Ã«'.

This is apparent when working with a library like couchdb-scala (https://github.com/beloglazov/couchdb-scala).

------------- Update : some more context, validation of the issue and a proposed solution ------------

Context:

We're building a scala application which uses the 'couchdb-scala' lib (https://github.com/beloglazov/couchdb-scala) to access a Couch database (http://couchdb.apache.org), which is a json document database.

The 'couchdb-scala' lib uses http4s to communicate with the db.

As we need to store Dutch texts containing accented characters like é, ë, à,... etc, we rely heavily on the fact that json is an UTF-8 encoded format.

I noticed that there's is a character encoding issue when pulling json data of the database using the http4s library (through the couchdb-scala lib).
The issue is not related to any other parts of the stack, I made sure to check the encoding on the wire is ok and that the other components of the 'couched-scala' lib do not interfere with encoding. The problem also is not apparent when using other libraries.

Couchdb returns data as 'content-type' = 'application/json', which implies that the default character encoding used must be 'UTF-8'. (unless of course the content-type header explicitly states otherwise by appending a different character encoding to the header, which is not the case here)
However, it seems http4s currently decodes 'application/json' data using the 'ISO-8859-1' character encoding instead of 'UTF-8', making special characters come out garbled.

Problem:

When looking at the code it seems that http4s always defaults to 'ISO-8859-1' when no explicit character encoding is provided by the 'content-type' header, which is generally fine (I think) but not when dealing with 'application/json' content.

To verify I changed the default content type as defined by the 'org.http4s.'Content-Type'' object; changing the line defining the default character encoding in 'Content-Type.scala' from:
    def charset: Charset = definedCharset.getOrElse(Charset.'ISO-8859-1')
to :
    def charset: Charset = definedCharset.getOrElse(Charset.'UTF-8')

This fixes the issue; special characters in the json are no longer garbled when retrieved from the database.

However, while this fix is ok for demonstrating the issue, I don't think it is a valid solution in a general sense since this might break decoding for other types of content, which may need yet another default encoding type...

Proposed solution:

A possible solution might be to define an optional default character encoding on each of the known mime-types (see MediaType.scala file in the core project).
This 'per mime-type default' could then be used when no explicit character encoding is provided on the 'content-type' header, while only defaulting to the global character encoding of 'ISO-8859-1' when no explicit character encoding was provided by content-type header and no encoding was defined for the mime-type (as defined on the content-type header).

This way we could explicitly define the 'application-json' media-type with the correct encoding type of 'UTF-8' without impacting other media-type encoding defaults.

---------- update --------
After digging a little further... besides defining character encoding defaults per media-type, it might also be an idea to allow the client to optionally provide the expected response character-encoding on each request, overruling any system defaults.

**Comment by bryce-anderson** [comment]
Can you elaborate the circumstances where this happens? Eg, which JSON library are you using?

**Comment by driak** [comment]
Yes, of course... see update in the issue description.

**Comment by bryce-anderson** [comment]
What a thorough analysis if the problem, thank you.

Looking through chouchdb-scala, it looks like the request body is being decoded as a ```String``` and not through an intermediate Json tree. There are a lot of ```message.as[String]``` calls in the [client code](https://github.com/beloglazov/couchdb-scala/blob/fb5a7a7e883e710c362dc782361951d234f8a42c/src/main/scala/com/ibm/couchdb/core/Client.scala), all of which would fail to properly decode a UTF-8 body to a ```String``` without a defined charset in the ```Content-Type``` header. Generally, the ```EntityDecoder``` used to decode the message would be responsible for picking its default charset, as is done with the normal Json tools of http4s. However, in this case, upickle seems to be responsible for decoding things from a ```String```, so the ```EntityDecoder[String]``` is being used incorrectly to obtain that ```String```.

Anyway, to fixing the problem. 
I don't want to add optional charsets to all the ```MediaType```s as most of them are not text. I'm not strongly against this, but it feels like an overkill solution to me. I also don't think its the clients problem to figure out the default charset: that responsibility would seem to belong to the ```EntityDecoder```. I think we should modify [this](https://github.com/http4s/http4s/blob/master/core/src/main/scala/org/http4s/EntityDecoder.scala#L113) function to take an optional charset. Then I would change all those ```.as[String]``` to ```EntityDecoder.decodeString(whatever, Some(UTF-8))``` in couchdb-scala.

The bad news is that seems like a pretty slow fix to land considering two projects need to cooperate.

And perhaps I'm wrong here, does anybody else have an opinion?

**Comment by beloglazov** [comment]
Thanks for looking into this! I'm happy to make the necessary changes on the couchdb-scala side.

**Comment by driak** [comment]
Thanks a lot for backing this up!

I totally agree that it is ultimately the client's responsibility to decide if it wants to override the default character encoding of a response, but might it also be a good idea to have Http4s use a sane default when the client does not explicitly define one (using the as[String] on an 'application/json')?

Character encoding issues are always tough to detect and debug, this might avoid some of them.

...just a suggestion of course.

**Comment by bryce-anderson** [comment]
OK, my plan is to add the ```Option[Charset]``` as a parameter to the ```EntityDecoder.decodeString``` function. I don't know when this will get into a release, the 0.8 release hasn't come up yet in discussion. That said, it tends to move faster if someone is waiting on it.

@beloglazov, once that happens the changes can be made to couchdb-scala.

Let me know if there are objections to that plan.

**Comment by driak** [comment]
Sounds great! Thanks to all!
I for one am definitely looking forward to the https 0.8 release (and the subsequent update to couchdb-scala) since we are depending on special characters.
(Until the fix is available we're 'surviving' using a locally build version of http4s-core that simply sets the global default character set to UTF-8.)

**Comment by bryce-anderson** [comment]
This should be fixed on our end. Let me know if we can be of help with patching couchdb-scala.
