### ISSUE TITLE
IO and unsafeRunSync used directly to create keys

### ISSUE THREAD

**Issue by satyajit-bhadange** [http4s/http4s#2803]
https://github.com/http4s/http4s/blob/7a1d51bcb96a2bb12114b284a613c6c294467ca3/core/src/main/scala/org/http4s/Message.scala#L441

Is this a good practice to create Keys in this manner?

What should be a better way to pass F for creating a key and adding to the request attribute?

**Comment by rossabaker** [comment]
[Embarrassingly late answer for posterity]

`Key.newKey` is not referentially transparent, and thus is returned in `F`.  But we need this key be a shared global reference.  There's nothing to be gained by parameterizing it on `F`: it's just a nuisance effect here.   We just need a simple effect that we can unwrap that's already the classpath.  And `SyncIO` is simpler still, so it has been refactored to that.
