### ISSUE TITLE
Decode NoBody/Empty body as Unit

### ISSUE THREAD

**Issue by Lasering** [http4s/http4s#2806]
Using 0.21.0-M4 I can do:

```scala
import cats.effect._
import org.http4s._
import org.http4s.dsl.io._
import org.http4s.implicits._
val response = NoContent().unsafeRunSync
response.as[Unit].unsafeRunSync
```

I get no compile errors nor runtime errors.

However if I try the same using Json:
```scala
val merror = implicitly[MonadError[IO,Throwable]]
```
- Jawn
```scala
import org.http4s.jawn._
import cats.MonadError
response.as(merror, jawnDecoder[IO, Unit]).unsafeRunSync
```
```
cmd15.sc:1: could not find implicit value for evidence parameter of type org.typelevel.jawn.RawFacade[Unit]
val res15 = response.as(merror, jawnDecoder[IO, Unit]).unsafeRunSync
                                                                         ^
Compilation Failed
```
- Circe
```scala
import org.http4s.circe._
response.as(merror, jsonOf[IO, Unit]).unsafeRunSync
```
```
org.http4s.MalformedMessageBodyFailure: Malformed message body: Invalid JSON: empty body
  org.http4s.jawn.JawnInstances$.defaultJawnEmptyBodyMessage(JawnInstances.scala:43)
  org.http4s.jawn.JawnInstances.jawnEmptyBodyMessage(JawnInstances.scala:17)
  org.http4s.jawn.JawnInstances.jawnEmptyBodyMessage$(JawnInstances.scala:16)
  org.http4s.circe.package$.jawnEmptyBodyMessage(package.scala:3)
  org.http4s.jawn.JawnInstances.$anonfun$jawnDecoderImpl$4(JawnInstances.scala:34)
  scala.Option.getOrElse(Option.scala:138)
  org.http4s.jawn.JawnInstances.$anonfun$jawnDecoderImpl$3(JawnInstances.scala:34)
  scala.Function1.$anonfun$andThen$1(Function1.scala:57)
  ...
```
Circe has a [Decoder for Unit](https://github.com/circe/circe/blob/master/modules/core/shared/src/main/scala/io/circe/Decoder.scala#L583).

It this intentional? If yes, can I somehow configure it?

PS: If I declare `implicit val nullFacade: Facade[Unit] = NullFacade` and run `response.as(merror, jawnDecoder[IO, Unit]).unsafeRunSync` I get the same stack trace as when using `jsonOf`.

**Comment by rossabaker** [comment]
I had to think about it, but it makes sense to me.

An empty string is not valid JSON.  Circe can decode any JSON to `Unit`, but it needs a JSON to decode.

```scala
@ io.circe.parser.parse("").isLeft 
res11: Boolean = true
```

The second parameter to `JawnDecoder` is the JSON AST.  I don't know whether NullFacade is one that you wrote or one provided by jawn.  But I would still expect a null facade to check for validity.

I think `.as[Unit]` is the proper way to do this.  Why do you want to decode it as JSON when it's not?  Is this just to treat everything as JSON throughout your API?

**Comment by Lasering** [comment]
[NullFacade](https://github.com/typelevel/jawn/blob/master/parser/src/main/scala/jawn/NullFacade.scala) is defined in Jawn.

I don't know to which `.as` you are referring but I think they are the same. I passed the implicit arguments explicitly just to make it easier to distinguish which decoder I was using.

`def as[A](implicit F: MonadError[F, Throwable], decoder: EntityDecoder[F, A]): F[A] = (...)`

 Yes, basically I want to treat everything as JSON.

In my code I've made `jsonOf` implicit, so it always tries to decode from json. I found an hack that solves it, although I don't like it: `implicit val void: EntityDecoder[F, Unit] = EntityDecoder.void`.

It seems that the choice is intentional, I just have a weird use case/usage.

**Comment by rossabaker** [comment]
Yes, this is why we don't make `jsonOf` implicit.  Because the JSON codecs are orphan instances, we get brain teasers between those and the codecs in the companion objects.  I think your hack is bringing the non-JSON one back into a higher priority scope.

Another flavor of this is `String` and whether they get quoted or not.
