### ISSUE TITLE
Per request timeout for HTTP client

### ISSUE THREAD

**Issue by balatbn** [http4s/http4s#282]
Can we have per request timeout to HTTP client? This would be helpful in case we need to call multiple backend servers, with server specific timeouts.

**Comment by rossabaker** [comment]
[thinking out loud]  Would the timeout be provided on the call, or some sort of function to map requests to timeouts?  The former could be based on the latter, I suppose.

**Comment by balatbn** [comment]
Does the Client interface support making multiple calls with a list/seq? If not, wouldn't adding a timeout parameter be simpler?

**Comment by julien-truffaut** [comment]
I would like a timeout parameter on the call, maybe defaulted to `Duration.Inf`

**Comment by bryce-anderson** [comment]
The only problem I foresee is that there are many calls, some with the same names so we cannot simply have defaults. We can overload the methods, so it shouldn't be a big problem, it will just make the API quite noisy. 
Also, I'd rather have the default be the default setting specified per client, not just ```Duration.Inf```, but that would mean we need to introduce a ```protected def defaultClientTimeout: Duration``` to the ```Client``` trait. Again, not a problem, just a matter of noise.

Anybody interested in digging into this? I know I'm the one who wrote the client and the NIO framework its based on, but I'm hoping this can be an opportunity to spread the knowledge of how it works.

**Comment by rossabaker** [comment]
Nobody has brought forth a good API for this, and backends that support cancellation have a nice way to do this with cats-effect `timeout`.
