### ISSUE TITLE
Allow passing classloaders anywhere we use `getResource`

### ISSUE THREAD

**Issue by nigredo-tori** [http4s/http4s#2834]
- https://github.com/http4s/http4s/blob/0f8ae7113f0afec89b695c34d94295d55c91de85/core/src/main/scala/org/http4s/StaticFile.scala#L40
- https://github.com/http4s/http4s/blob/0f8ae7113f0afec89b695c34d94295d55c91de85/core/src/main/scala/org/http4s/StaticFile.scala#L51
- https://github.com/http4s/http4s/blob/0f8ae7113f0afec89b695c34d94295d55c91de85/tomcat/src/main/scala/org/http4s/server/tomcat/TomcatBuilder.scala#L155

These assume that http4s and application resources come from the same classloader, which is not always the case. We should allow passing a custom classloader instead, defaulting to `getClass.getClassLoader`.

The change itself is trivial. The main pain here will probably come from MiMa.

**Comment by kevinmeredith** [comment]
> These assume that http4s and application resources come from the same classloader, which is not always the case.

Could you please say the problem with using different class loaders, @nigredo-tori? In other words, what problem does this issue intend to solve?

Note - I don't know much about class loaders, so this is a question to which I'm genuinely interested to know the answer for my own learning.

**Comment by nigredo-tori** [comment]
@kevinmeredith, different class loaders can have different sets of resources (and classes) available. Consider this setup:

- Class loader **A** contains all the external libraries for the application, including http4s.
- Class loader **B** has all the classes and resources of the application itself, and has **A** as its parent.
- The application starts from a main class in class loader **B**. However, any referenced library classes are actually loaded from class loader **A** (as specified [here](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/ClassLoader.html#loadClass(java.lang.String,boolean)) ).  In particular, `StaticFile` has **A** as its class loader.
- When we do `StaticFile.getClass.getResource("foo")`, the call gets [delegated](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/Class.html#getResource(java.lang.String)) to **A**, so you can't get application resources this way!

This is uncommon, since Scala applications generally don't mess with extra class loaders. In my case, this arose from an old Java web application (with `Spring`, class instrumentation servlets...) slowly evolving to a standalone Scala/Java application. So I have Jetty, bootstrapping, libraries etc. in one class loader, and application proper in another (instrumentable) one. The whole thing is a mess, but it works.

Another (theoretical) example for this would be if someone used `StaticFile` in their tests. SBT uses layered class loaders for running code in the same JVM, so this could lead to the same issue.

**Comment by rossabaker** [comment]
I think this is a smart idea.  

Maybe #2158 would help, although if it's just an addition of default parameters, it might not be so bad in current form.  Just, as noted, not going to be binary compatible.

Either way, 0.21 is an opportunity to fix this.

**Comment by nigredo-tori** [comment]
@hamnis, the third part was not addressed:
https://github.com/http4s/http4s/blob/43cded211c8d4cc9b0fc7ae3559ea5095b553ffa/tomcat/src/main/scala/org/http4s/server/tomcat/TomcatBuilder.scala#L155

**Comment by hamnis** [comment]
@nigredo-tori yes, I missed that. Should be fixed by #3007
