### ISSUE TITLE
[Documentation] Prometheus docs incorrect?

### ISSUE THREAD

**Issue by unthingable** [http4s/http4s#2845]
package org.http4s.metrics.prometheus:

```
  * For example, the following code would wrap a [[org.http4s.HttpRoutes]] with a [[org.http4s.server.middleware.Metrics]]
  * that records metrics to a given metric registry.
  * {{{
  * import org.http4s.client.middleware.Metrics
  * import org.http4s.client.prometheus.Prometheus
  *
  * val meteredRoutes = Metrics[IO](Prometheus(registry, "server"))(testRoutes)
  * }}}
```

`Prometheus.apply` returns `F[MetricsOps[F]]` but `Metrics.apply` expects `MetricsOps[F]`, and the code does not compile.

**Comment by ChristopherDavenport** [comment]
Yep, that's wrong. Although I will point folks to [epimetheus](https://github.com/ChristopherDavenport/epimetheus/)/[epimetheus-http4s](https://github.com/ChristopherDavenport/epimetheus-http4s). Makes it much safer to work with prometheus than the underlying java tools alone.

That being said we should update the scaladoc.

**Comment by iRevive** [comment]
@ChristopherDavenport  I guess this one can be closed as well. I've updated docs in the scope of https://github.com/http4s/http4s/pull/2972.
