### ISSUE TITLE
BlazeClient withTcpNodelay(true) is not working on AIX 

### ISSUE THREAD

**Issue by neutrospec** [http4s/http4s#2886]
I am using http4s 0.20.9 on AIX 7.2
Blaze client performs very poorly. (following code)

```scala
    val client: Resource[IO, Client[IO]] = BlazeClientBuilder[IO](blockingEC)
      .withRequestTimeout(90.seconds)
      .withIdleTimeout(15.seconds)
      .withTcpNoDelay(true)
      .resource
```

With jetty client, no problem.
```scala
    val clientJetty = Resource.make(IO.delay {
      val jettyClient = new HttpClient()
      jettyClient.setTCPNoDelay(true)
      jettyClient
    })(_ => IO.pure(())).flatMap(JettyClient.resource[IO](_))
```

I reviwed source code but `applyChannelOption` is there!

**Comment by rossabaker** [comment]
I'm sorry nobody got back to this sooner.  I need more details on "very poorly", and I don't have access to an AIX machine to chase this.  If this still happens on a still supported version (0.21 or later), please reopen, and we'll see what we can figure out.
