### ISSUE TITLE
Add `withQueryParams(stringMap)` to `Uri`

### ISSUE THREAD

**Issue by Daenyth** [http4s/http4s#2920]
Currently, adding a `Map[String, String]` of query parameters to `Uri` looks like this:

```scala
paramMap.foldLeft(uri) {
  case (uri, (k, v)) => uri.withQueryParam(k, v)
}
```

That's extremely verbose for a common operation. I think it would be a helpful addition.

**Comment by rossabaker** [comment]
Some elaboration:
1. What happens if a key is already present?  Replace or add?
2. Should there also be a version for a multi-map?

**Comment by phongngtuan** [comment]
Looks like it's done in #3024

**Comment by aeons** [comment]
Yep.
