### ISSUE TITLE
Request.addCookie is Broken

### ISSUE THREAD

**Issue by ghost** [http4s/http4s#2938]
Using [Request.addCookie](https://github.com/http4s/http4s/blob/master/core/src/main/scala/org/http4s/Message.scala#L342) does not properly insert cookies after the first insertion. Example:
```
val request: Request[IO] =
  Request()
    .addCookie(RequestCookie("test1", "test1"))
    .addCookie(RequestCookie("test2", "test2"))
println(request.headers)
println(request.headers.size)
```
This will output:
```
Headers(Cookie: test1=test1, Cookie: test2=test2)
2
```
But the proper result for the [HTTP specification](https://tools.ietf.org/html/rfc6265#section-4.2.1) should be:
```
Headers(Cookie: test1=test1; test2=test2)
1
```
Note: this also happens using the [string-only overload](https://github.com/http4s/http4s/blob/master/core/src/main/scala/org/http4s/Message.scala#L346). I realize this is a small thing as the usage of `Request.addCookie` is not as prevalent as `Response.addCookie`, but this has caused me some headaches while designing a testing framework for myself, and this should be fixed for semantic reasons anyhow.

I can fix this, but wanted to post first in case this behavior is intended for some reason.

**Comment by rossabaker** [comment]
This works as requested now.
