### ISSUE TITLE
client tests fail on windows

### ISSUE THREAD

**Issue by martijnhoekstra** [http4s/http4s#294]
The tests `org.http4s.client.blaze.BlazePooledHttp1ClientSpec` and `org.http4s.client.blaze.BlazeSimpleHttp1ClientSpec` fail on Windows

The stacktraces are

    [info] ! Execute GET: http://localhost:37920/simple
    [error]    IOException: : The format of the specified network name is invalid.
    [error]   (null:-1)
    [error] sun.nio.ch.Iocp.translateErrorToIOException(Unknown Source)
    [error] sun.nio.ch.Iocp.access$700(Unknown Source)
    [error] sun.nio.ch.Iocp$EventHandlerTask.run(Unknown Source)
    [error] sun.nio.ch.AsynchronousChannelGroupImpl$1.run(Unknown Source)
    [error] java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    [error] java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    [error] java.lang.Thread.run(Unknown Source)

The address argument in runTest is 0.0.0.0/0.0.0.0:37920

**Comment by martijnhoekstra** [comment]
the tests fail for both /simple and /chunked

**Comment by bryce-anderson** [comment]
Without trying it out, this seems to be a difference in interpretation of localhost between OS's. Have you tried running requests other than the tests?

**Comment by martijnhoekstra** [comment]
the example client works "fine" (it throws an exception on trying to parse JSON from https://twitter.com/doesnt_exist ,which despite it's name implying the opposite, does exist), this seems mainly a test issue
