### ISSUE TITLE
Add a Request.cookies function

### ISSUE THREAD

**Issue by ghost** [http4s/http4s#2943]
To mirror [Response.cookies](https://github.com/http4s/http4s/blob/master/core/src/main/scala/org/http4s/Message.scala#L509), except it would return a `List[RequestCookie]`. I find myself using an extension method to accomplish this quite often, so I think it would be a good quality-of-life enhancement.

I can implement this if there are no objections. I will make the implementation compatible with the [HTTP specification](https://tools.ietf.org/html/rfc6265#section-4.2.1) (for more information, see #2938).

**Comment by rossabaker** [comment]
I think this is reasonable.  Since [multiple cookie headers are allowed in HTTP/2.0](https://tools.ietf.org/html/rfc7540#section-8.1.2.5), I would still aggregate multiple headers.  You did the right thing in #2938 for what we _emit_, but we should _accept_ the split cookies as well.

**Comment by ScalaFanatic** [comment]
Noted, I will get to work on this.

**Comment by m-sp** [comment]
this was added in https://github.com/http4s/http4s/pull/2992/files#diff-adcd6450231fbb969572de7bdd97e36c7dd50fe3e577135b505c3a7e90320077R346
