### ISSUE TITLE
UserInfos: reject userinfos with invalid characters

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#2944]
Hit this in an unrelated PR:

```
[error]   x reject userinfos with invalid characters (376 ms)
[error]    Falsified after 1 passed tests.
[error]    > ARG_0: "+"
[error]    The seed is TqslytqDInIEdPOhRix7yNUhmhNq3vpzfe8O_zHpfdM=
[error]    
[error]    > Right(UserInfo(+,None)) is not Left (UserInfoSpec.scala:77)
```

**Comment by bfdes** [comment]
`+` falls under the sub-delim rule and is allowed by the `UserInfo` parser in `Uri`.
This seems to conform to [RFC 3988](https://tools.ietf.org/html/rfc3986).

I *think* we are getting a false negative because the spec allows some characters which fall within the reserved set.
