### ISSUE TITLE
Client side Request Logger doesn't log GET requests when logBody is set 

### ISSUE THREAD

**Issue by mhriemers** [http4s/http4s#2951]
#1849 fixed this for the server side but the issue still remains on the client side.

**Comment by ipsq** [comment]
I'm using the JdkHttpClient. This is happening because the body stream is not consumed in the `convertRequest` method. 

```scala
val publisher = FlowAdapters.toFlowPublisher(
  StreamUnicastPublisher(req.body.chunks.map(_.toByteBuffer))
)
if (req.isChunked)
  BodyPublishers.fromPublisher(publisher)
else
  req.contentLength
    .fold(BodyPublishers.noBody)(BodyPublishers.fromPublisher(publisher, _))
```

I can see two ways on how to fix this. Either, require all clients to consume the request body or simply add a check inside the request logger:

```scala
Client { req =>
  if (logBody && req.contentLength.isDefined)
    Resource.suspend { ... }
  else
    Resource.liftF(Logger
      .logMessage[F, Request[F]](req)(logHeaders, logBody, redactHeadersWhen)(log(_))
    ) *> client.run(req)
```

**Comment by rossabaker** [comment]
The logger has been touched several times since this was reported, so unconfirmed, but cautiously flagging it as still a bug.

**Comment by dzanot** [comment]
Just confirmed this is still an issue with `http4s-jdk-http-client` version `0.7.0` and `0.23.11` of `http4s`

**Comment by armanbilge** [comment]
@dzanot thanks for confirming. This seems straightforward to fix, would appreciate PR :)

**Comment by dzanot** [comment]
Sure thing: https://github.com/http4s/http4s/pull/6535/files
