### ISSUE TITLE
Can't get WebSockets Example to Work

### ISSUE THREAD

**Issue by recompilecom** [http4s/http4s#296]
The changes made on March 30 to `server/src/main/scala/org/http4s/server/websocket/package.scala` and `examples/blaze/src/main/scala/com/example/http4s/blaze/BlazeWebSocketExample.scala` seem not to be compatible. If you use the example as is:

    WS(Exchange(src, t.publish))

Your web client gets `501 Not Implemented` from this default value of `status` in the call to `ws`:

    status: Task[Response] = Response(Status.NotImplemented).withBody("This is a WebSocket route.")

Taking a couple of hours to look into this, it would appear that this is what's required:
    
    WS(
      Exchange(src, t.publish),
      SwitchingProtocols().withHeaders( "Upgrade" -> "websocket", "Connection" -> "upgrade", etc...)
    )
  
But this does not seem like the correct way to go.

**Comment by bryce-anderson** [comment]
It works for me. One issue I can see is not following the server setup in the BlazeWebSocketExample.scala file. Its not a normal setup as websocket support is mixed as a trait, which is perhaps something that should be changed. What you're seeing is a normal HTTP response which can happen if WS support isn't mixed in or if you are just doing a normal HTTP request.

**Comment by recompilecom** [comment]
Yes, I can see now that was the issue -- I was mixing this from the main
examples page:

 BlazeBuilder.bindHttp(8080)
   .mountService(ExampleService.service, "/http4s")
   .run
   .awaitShutdown()


So now when I try and

import org.http4s.blaze.channel.nio1.NIO1SocketServerGroup

I get:  object NIO1SocketServerGroup is not a member of package
org.http4s.blaze.channel.nio1

Is it possible to use "with WebSocketSupport" and
"BlazeBuilder.bindHttp()..." ?

**Comment by bryce-anderson** [comment]
Funny, that should work. Are you using the latest release, 0.8.1? ```NIO1SocketServerGroup``` was renamed from ```NIO1SocketServerChannelFactory``` in the 0.8.x series.

**Comment by bryce-anderson** [comment]
And no, its not possible to use it with``` BlazeBuilder.bindHttp()```. In the future it may end up integrated by default, maybe not.

**Comment by bryce-anderson** [comment]
I'm going to close this as an issue. Feel free to join us in gitter.im/http4s/http4s for more discussion!
