### ISSUE TITLE
How to forward request?

### ISSUE THREAD

**Issue by v00** [http4s/http4s#2977]
I want to write simple Single Page Application (SPA) using http4s as backend. Routing will work on the client side. I just need to forward all requests to the root (`/`) if there is no static file on the requested path and the requested path is not api endpoint (does not start from `/api`).

High-level overview of the semantics of forward vs. redirect:

 * redirect will respond with a 302 and the new URL in the Location header; the browser/client will then make another request to the new URL
 * forward happens entirely on a server side; the URL won't change in the browser

See also:

 * [How to forward request using Spring Boot?](https://stackoverflow.com/questions/38783773/spring-boot-single-page-application-forward-every-request-to-index-html/39625064) on StackOverflow

Can you show example how to use http4s for SPA?

**Comment by aeons** [comment]
Something like this should work. I haven't tested it though.

```scala
val staticRoutes: HttpRoutes[IO] = ???
val apiRoutes: HttpRoutes[IO]    = ???

val redirectToRootResponse: Response[IO] =
    Response[IO]()
        .withStatus(Status.Found)
        .withHeaders(Location(Uri.uri("/")))

def orRedirectToRoot(routes: HttpRoutes[IO]): HttpApp[IO] =
    Kleisli(req => routes.run(req).getOrElse(redirectToRootResponse))

val routes: HttpApp[IO] =
    orRedirectToRoot(staticRoutes <+> apiRoutes)
```

**Comment by v00** [comment]
I think it should send response with `/index.html` content but with original headers from request:

```scala
val staticRoutes: HttpRoutes[IO] = ???
val apiRoutes: HttpRoutes[IO]    = ???

def redirectToRootResponse(request: Request[IO]): Response[IO] =
    Response[IO]()
      .withStatus(Status.Found)
      .withEntity(Source.fromResource("webapp/index.html").getLines().mkString)
      .withHeaders(request.headers)

def orRedirectToRoot(routes: HttpRoutes[IO]): HttpApp[IO] =
    Kleisli(req => routes.run(req).getOrElse(redirectToRootResponse(req)))

val routes: HttpApp[IO] =
    orRedirectToRoot(staticRoutes <+> apiRoutes)
```

It works for me. Thank you!

**Comment by aeons** [comment]
I'm pretty sure the body on a 302 Found is ignored by the client, so that is unnecessary.
