### ISSUE TITLE
sbt-pgp is broken on Travis CI

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#3001]
Signing the last release [didn't work].  #2903 is the obvious related change, but the problem is not obvious.  I reverted the commit to unblock the release, but I'd like to stay current, so let's figure out how to revert the reversion.

**Comment by hamnis** [comment]
the format of `gpg` keys changed in gnupg v2 so that might be a reason

**Comment by hamnis** [comment]
we might consider https://github.com/jodersky/sbt-gpg instead of sbt-pgp

**Comment by rossabaker** [comment]
RIP, Travis CI. :skull:
