### ISSUE TITLE
MediaType does not properly encode extensions

### ISSUE THREAD

**Issue by mossprescott** [http4s/http4s#301]
MediaTypes are properly decoded during parsing, but `MediaType.render` makes a pretty half-hearted attempt to encode them, handling spaces but not any of the other special characters, including `"` and `;`.

This make it impossible to use the pre-defined `Content-Type` in a response if the MediaType involves any of these characters.

See https://github.com/http4s/http4s/blob/master/core/src/main/scala/org/http4s/MediaType.scala#L78.

We're running into this trying to use a type like `text/csv; charset=UTF-8; columnDelimiter="	"; rowDelimiter=";"; quoteChar='; escapeChar="\\"`. See discussion at https://github.com/slamdata/slamengine/pull/776#discussion_r32746356.

**Comment by bryce-anderson** [comment]
Looks like a bug to me. Is this a relevant RFC to follow in addressing the problem? https://tools.ietf.org/html/rfc7230#section-3.2.6

**Comment by mossprescott** [comment]
I believe that's the right place to go for the `quoted-string` syntax, however, there seem to be special rules for when quoting is required, which you can see here https://tools.ietf.org/html/rfc2045#section-5.1 and on the last page of the same RFC. That's a very old RFC, but there doesn't seem to be any update that affects ASCII values.

**Comment by mossprescott** [comment]
Also probably worth pointing out that http4s's [AcceptHeader parser](https://github.com/http4s/http4s/blob/master/core/src/main/scala/org/http4s/parser/AcceptHeader.scala) *seems* to do the right thing, so testing rendering against it is probably a good idea.

**Comment by bryce-anderson** [comment]
This will be fixed in the 0.8.2 release happening today. If you want to make sure things are as you need, the branch that will be the release is [here](https://github.com/http4s/http4s/tree/release-0.8.2).

**Comment by mossprescott** [comment]
Taking a look right now. Thanks for the quick turnaround!

**Comment by rossabaker** [comment]
0.8.2-SNAPSHOT is published in case you want to try it before it gets etched in Maven Central stone.
