### ISSUE TITLE
Change the default port of the BlazeServer to 420

### ISSUE THREAD

**Issue by kujon** [http4s/http4s#3026]
Seems to be defaulting to 8192, and I think we can do better than this.

**Comment by rossabaker** [comment]
Correct me if I'm wrong, but wouldn't binding a port below 1024 require root?  What is the motivation?

**Comment by ChristopherDavenport** [comment]
I thought default was random port on localhost. Would be happy with defaults of 0.0.0.0 and x080 where x is some number, 8080 is quite classic.

**Comment by bfdes** [comment]
> Correct me if I'm wrong, but wouldn't binding a port below 1024 require root? What is the motivation?

I believe the OP wanted an Easter Egg / reference to [this](https://en.wikipedia.org/wiki/420_(cannabis_culture)) subculture.

**Comment by rossabaker** [comment]
Ah, of course.  I didn't think hard enough about the "blaze".

Since we've already ruined the joke, the [default is actually 8080](https://github.com/http4s/http4s/blob/ae6892cb81dc037e49ec6f4d81060bea2ad11cf0/server/src/main/scala/org/http4s/server/package.scala#L26).
