### ISSUE TITLE
circe: Allow to configure parsing of the duplicate keys

### ISSUE THREAD

**Issue by vvlevykin** [http4s/http4s#3034]
The `allowDuplicateKeys` cannot be changed: https://github.com/http4s/http4s/blob/2fa25a74d31ecfc9a6e61c8076ca6ad7d02e8b4a/circe/src/main/scala/org/http4s/circe/CirceInstances.scala#L20

It would be better if it could be configured e.g. via CirceInstancesBuilder.

**Comment by ashwinbhaskar** [comment]
I can pick this up.
