### ISSUE TITLE
Consider dropping client request body support for GET and HEAD

### ISSUE THREAD

**Issue by hamnis** [http4s/http4s#3036]
For `GET`

```
  A payload within a GET request message has no defined semantics;
   sending a payload body on a GET request might cause some existing
   implementations to reject the request.
```

for `HEAD`

```
 A payload within a HEAD request message has no defined semantics;
   sending a payload body on a HEAD request might cause some existing
   implementations to reject the request.
```

**Comment by rossabaker** [comment]
For the client?  With the goal of sending neither Content-Length nor Content-Transfer-Encoding headers?  I assume this is inspired by #3027?

**Comment by hamnis** [comment]
for the client yes. the server can do what it wants. Since the spec also discourages use of bodies on GET and HEAD, i think we should follow that even if its not a MUST or SHOULD

**Comment by rossabaker** [comment]
We've run into a few people using terrible APIs that require it.  I think we should grudgingly allow it, but not send `Content-Length` or `Transfer-Encoding` headers that imply a body unless there is one, which we've been tightening up. #4509 should lock that down further.
