### ISSUE TITLE
Document and streamline the release process for new maintainers

### ISSUE THREAD

**Issue by Daenyth** [http4s/http4s#3048]
The release process currently has some manually-driven steps that we can streamline, and at minimum we can make sure that the process is documented so that new maintainers are able to contribute effort to release management.

-----

[January 8, 2020 11:03 AM](https://gitter.im/http4s/http4s?at=5e15fd5ca74ac8537774c825)

> I might have written something in the contributors guide. I can't remember. I update changelog.md, and manually bump the version.sbt, which triggers the release when merged.

-----
To collect a commit list for manual editing/presentation in the changelog:

```
git log --grep '#' --reverse --format=oneline master ^${LAST_RELEASE_TAG}
```

**Comment by rossabaker** [comment]
I hear good things about release drafter and I'm getting more serious about issue labels.  Maybe that will help.

**Comment by armanbilge** [comment]
Things are much more streamlined now. Label stuff and create a release on GH, watch the notes write themselves :)
