### ISSUE TITLE
Ember Server Graceful Shutdown

### ISSUE THREAD

**Issue by ChristopherDavenport** [http4s/http4s#3067]
Currently shutting down an ember server is not graceful, and leads to a very [large stacktrace](https://gist.github.com/BalmungSan/99978e5d699575f19b8cbcc608032a05), we can improve experience by shutting down gracefully and having reporting display that.

**Comment by RaasAhsan** [comment]
I'm interested in knowing -- what part of the ember-server's shutdown sequence isn't graceful? I'm thinking about ways to add graceful shutdowns to blaze-server and right now the thorn is selector threads may still be active after the server acknowledges shutdown

**Comment by ChristopherDavenport** [comment]
So presently it will cancel the response processing that is in flight. Graceful would be to stop handling incoming while completing those already in flight.

**Comment by rossabaker** [comment]
It's helpful to define grace here.  Typically, you want to wait for in-flight requests to finish, but you don't want to wait indefinitely.  I think generally we want to:

1. Stop accepting new connections immediately.
2. Finish servicing existing responses, closing any connections.
3. After a configurable timeout, clean up forcibly.

You also want some way of communicating to the caller that the server has terminated, either gracefully or not.
