### ISSUE TITLE
Would adding a defined charset to the MediaType be worth the trouble?

### ISSUE THREAD

**Issue by bryce-anderson** [http4s/http4s#308]
Due to the recent [fun with the couchdb library](https://github.com/beloglazov/couchdb-scala/pull/5) and the handling of UTF-8 character encoding, the suggestion/question has come up concerning adding a default `Charset` to each defined `MediaType`. 

For JSON, the encoding is **defined** to be `UTF-8`. This would be good information to know when interpreting a JSON body as a `String`, which has a **default** charset of `ISO-8859-1`. So in this case a default/defined charset for the `text/json` `MediaType` would have been a big help.
## Questions:
- Where can we get this information en masse? Going through them all by hand sounds like work one gets paid for.
- Is this a more general concern or is JSON just special? This would be answered by an answer to the above question.

**Comment by rossabaker** [comment]
I suggested it as an optional property of the `MediaType`, but even that is insufficient: in XML, the encoding comes from the prolog, meaning the answer depends on the entity body. :(

**Comment by rossabaker** [comment]
Relevant: https://tools.ietf.org/html/rfc6657#page-3

**Comment by rossabaker** [comment]
On the heels of #312, `MediaType` could take a signature like:

```scala
def asText(cs: Option[Charset], body: EntityBody): Option[Task[Process, String]]
```

That construction would support inspecting the payload to determine the encoding. `Message.bodyAsText` could then delegate to that.  Whether that's worthwhile, I'm less certain.

**Comment by rossabaker** [comment]
This information is not part of the IANA database, so I don't know where to get it en masse.  I'm inclined to close it, but let's see if a new generation of committers finds it stimulating first.

**Comment by rossabaker** [comment]
The `asText` idea would require crazy dependencies to do right: we wouldn't want to parse the XML declaration without an XML library.  This would all be a giant effort to maybe do a little better at text for types that mostly shouldn't be treated as text.  Body logging is probably the most compelling case for it, and I don't recall a single complaint.

I think we're better off focusing on good types and good entity codecs for them.
