### ISSUE TITLE
Pretty-print an org.http4s.Request as a curl command

### ISSUE THREAD

**Issue by MasseGuillaume** [http4s/http4s#3095]
A neat feature in the chrome inspector network tab is to export a request as a curl command:

![out](https://user-images.githubusercontent.com/921490/72844324-43ce1280-3c6a-11ea-90a6-1255f7760344.png)

I would be useful to have something like this for `org.http4s.Request`.

`request.asCurl: String`

**Comment by erewl** [comment]
Hey, thats a cool first issue.
I am working on it :-)

**Comment by rossabaker** [comment]
Wonderful! Let us know if you need any help.

**Comment by honzatrtik** [comment]
Hi! Is there any progress @MasseGuillaume ? If not, I'd like to help.. We'd love to have this feature too...

**Comment by shreyashpatodia** [comment]
@honzatrtik looks like @erewl already made a PR for this. @rossabaker could this issue be closed then?

**Comment by MasseGuillaume** [comment]
https://github.com/http4s/http4s/pull/3113

**Comment by rossabaker** [comment]
Note that we don't do the body.  There were questions about how to proceed on that in #3113, and we went for the partial win.  If anyone still wants the body, let's open another issue.
