### ISSUE TITLE
ClassCastException on AuthMiddleware

### ISSUE THREAD

**Issue by gvolpe** [http4s/http4s#3100]
I'm seeing this error on both `0.21.0-M6` and `0.21.0-RC1`. I think it's related to the recent generalization of `AuthedRequest`. Has anyone else seen this?

```scala
core 21:31:04.031 [ioapp-compute-2] ERROR org.http4s.server.service-errors - Error servicing request: POST /v1/cart from 127.0.0.1
core java.lang.ClassCastException: org.http4s.ContextRequest cannot be cast to org.http4s.AuthedRequest
core 	at cats.data.Kleisli.apply(Kleisli.scala:119)
core 	at org.http4s.server.package$AuthMiddleware$.$anonfun$apply$5(package.scala:122)
core 	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:139)
core 	at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:355)
core 	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:376)
core 	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:316)
core 	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:136)
core 	at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:355)
core 	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:376)
core 	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:316)
core 	at cats.effect.internals.IOShift$Tick.run(IOShift.scala:36)
core 	at cats.effect.internals.PoolUtils$$anon$2$$anon$3.run(PoolUtils.scala:51)
core 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
core 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
core 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by rossabaker** [comment]
That's odd, because `AuthedRequest` is a type alias for `ContextRequest`.  I'm not immediately sure what's happening there.

**Comment by gvolpe** [comment]
Okay, I found a lead. 

I'm using `http4s-jwt-auth`, which calls `req.context` (see [here](https://github.com/profunktor/http4s-jwt-auth/blob/master/core/src/main/scala/dev/profunktor/auth/middleware.scala#L21)). That, somehow, seems to trigger this `ClassCastException`.

If I call `req.authInfo` instead, which is *deprecated* now, I no longer get this error. 

It seems one of those corner cases of the Scala compiler... Leaving the definition of `ContextRequest` here for posterity:

```scala
final case class ContextRequest[F[_], A](context: A, req: Request[F]) {
  def mapK[G[_]](fk: F ~> G): ContextRequest[G, A] =
    ContextRequest(context, req.mapK(fk))

  @deprecated("Use context instead", "0.21.0")
  def authInfo: A = context

}
```

**Comment by hamnis** [comment]
This really sound like you have two `http4s-core` versions on the classpath

**Comment by gvolpe** [comment]
You may be right @hamnis, I forgot to check that detail and can confirm `http4s-jwt-auth` is on `0.21.0-M5`.

I'll make a new release soon and see if that fixes the issue. Thanks for your support!

**Comment by gvolpe** [comment]
I can confirm it was due to `http4s-jwt-auth` being on `0.21.0-M5`. A new release just fixed the issue, sorry for the trouble.

**Comment by gvolpe** [comment]
Wait, does this mean that binary compatibility is broken between `M5` and `M6`? If so, was that expected?

Maybe we should add this to the Changelog if it's not already there?

**Comment by rossabaker** [comment]
Compatibility was broken, and again between M6 and RC1.  I tihnk that's implied by the non-final numbers, but we could make that more explicit if it's confusing.

**Comment by gvolpe** [comment]
Fair enough. Just wanted to understand if that was under consideration, thanks, Ross :)
