### ISSUE TITLE
Cannot have more than one pending read request

### ISSUE THREAD

**Issue by khrupalyk** [http4s/http4s#3120]
I got `java.lang.IllegalStateException: Cannot have more than one pending read request`
when doing this:

```
    case GET -> Root / "ws" =>
      val toClient: Stream[F, WebSocketFrame] =
        Stream.awakeEvery[F](1.seconds).map(d => Text(s"Ping! $d"))

      val fromClient: Pipe[F, WebSocketFrame, Unit] = inputStream => {
        val parsedStream = inputStream.map(parseInput)

        val processStream1 = parsedStream.map(process)
        val processStream2 = parsedStream.map(process)

        processStream1.concurrently(processStream2).map(_ => ())
      }
      WebSocketBuilder[F].build(toClient, fromClient)
```

So if the input stream is split into two streams we will got this exception.
In `Http4sWSStage` we build stream:

```
val wsStream = inputstream
      .through(ws.receive)
      .concurrently(ws.send.through(sinkQueue.enqueue).merge(sinkStream).drain) //We don't need to terminate if the send stream terminates.
      .interruptWhen(deadSignal)
      .onFinalizeWeak(ws.onClose.attempt.void) //Doing it this way ensures `sendClose` is sent no matter what
      .onFinalizeWeak(sendClose)
      .compile
      .drain
```
`ws.receive` here is `fromClient` from previous example.

So we evaluate inputstream two times.

inputstream defined like: 
```
def inputstream: Stream[F, WebSocketFrame] =
    Stream.repeatEval(handleRead())
```

So handleRead is called few times. 
Reading should be synchronized (actually we need synchronize only readFrameTrampoline). 

A similar problem was fixed here [Cannot have more than one pending write request](https://github.com/http4s/http4s/issues/3102) by using `Semaphore`.

**Comment by rossabaker** [comment]
I can reproduce this, but I think it's strange to read the same stream twice.  

Are you trying to parallelize the stream processing?  I don't get the error with `inputStream.map(Stream.emit).parJoinUnbounded`.

Or are your two `process` calls different, so you can apply two kinds of processing to each input?  In that case, you might want to look at something like `observe`.

**Comment by khrupalyk** [comment]
Yes, you are right, there are more convenient ways to parallelize stream processing.

This error appears only when you will read the same stream twice, so not sure that is a critical bug.

**Comment by rossabaker** [comment]
I think you're right that a semaphore would allow this case to work, but it would be (small) overhead on everyone when there's probably a better way to express the consumption.  I'm inclined to leave this one alone, but know what the solution is if a different kind of concurrent read appears.
