### ISSUE TITLE
Ember client struggles with large responses

### ISSUE THREAD

**Issue by Baccata** [http4s/http4s#3123]
I've been experimenting with the Ember client and found that it seems to struggle with large response payloads. 

* http4s version : 0.21.0-RC2
* scala version: tried 2.12.10 and 2.13.1 
* java version: tried 8 and 13 

The following get request against https://httpbin.org/image/png takes a full minute, whereas it takes ~1s  for a get request against https://httpbin.org/get 

```scala
package foobar

import org.http4s.ember.client.EmberClientBuilder
import cats.implicits._
import cats.effect.IOApp
import cats.effect.ExitCode
import cats.effect.IO

object Main extends IOApp {

  def run(args: List[String]) =
    EmberClientBuilder
      .default[IO]
      .build
      .use { client =>
        // Calling get with https://httpbin.org/get returns instantly
        client.get("https://httpbin.org/image/png") { response =>
          for {
            _ <- IO(println(response.headers))
            _ <- response.body.compile.drain
          } yield ()
        }
      }
      .as(ExitCode.Success)
}
```

**Comment by bpholt** [comment]
I've been trying to track this down, and I believe it has to do with the way ember-client tries to drain the response body in order to try to reuse connections for future requests. As a workaround, adding a `Connection: close` header to the request seems to avoid the timeout, but this means you need to use a request style that allows setting additional headers. For example:

```scala
for {
  connectionCloseHeader <- Connection.parse("close").liftTo[F]
  req <- GET(uri"https://httpbin.org/image/png", connectionCloseHeader)
  _ <- client.fetch(req) { response =>
    for {
      _ <- IO(println(response.headers))
      _ <- response.body.compile.drain
    } yield ()
  }
} yield ()
```

**Comment by rossabaker** [comment]
Don't have the ticket that solved this, but it seems snappy to me, now.  Please reopen if you're still struggling.
