### ISSUE TITLE
Fix Mergify

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#3170]
Mergify is looking for a Travis CI status check, which will no longer come.

We can make it wait for GitHub Actions jobs, but we need them to wait for several jobs, I think.  This seems verbose and unmaintainable?  Is there a way to look for the success of a workflow rather than a job?

https://doc.mergify.io/conditions.html#github-actions

**Comment by aeons** [comment]
It looks like the example is a yaml list, so it could just get all the jobs it should wait for?
