### ISSUE TITLE
Graal: remove reflective header parsers

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#3189]
Based on @noelwelsh's fine work, [this commit](https://github.com/rossabaker/http4s-native-image/commit/28f7d65) shows a problem with modeled headers:

```
$ curl http://localhost:8080/raw
Some(Accept: */*)
$ curl http://localhost:8080/model
None
```

It works on the JVM:

```
$ curl http://localhost:8080/raw
Some(Accept: */*)
$ curl http://localhost:8080/model
Some(Accept: */*)
```

This is almost certainly a result of bootstrapping the header parsers with runtime reflection.  It's been a hidden implementation detail for years, but fails in the world beyond the JVM.

**Comment by joprice** [comment]
I'm seeing this same problem on jvm. I had to switch to using `.ci` as well.

**Comment by rossabaker** [comment]
Sorry, can you be more specific?  Is this using the example service linked above?

**Comment by rossabaker** [comment]
And this should have been closed by #3190, but I'll leave it open while we resolve this question.

**Comment by joprice** [comment]
I spoke too soon. I have a completely different issue that looked similar to this one: An Authorization header with a single token, that is, not containing the "type" specifier. The compliant parser of http4s doesn't let that one slide. Please excuse the noise!

**Comment by rossabaker** [comment]
This is a common pitfall.  Maybe we should consider a version that returns either the raw header or the modeled header so things don't just "disappear" like this.
