### ISSUE TITLE
Seems like there are a memory leak in the AsyncHttpClient

### ISSUE THREAD

**Issue by kaarenilsen** [http4s/http4s#3202]
Attached is a screenshots showing the memory usage of a pod we have in kubernetes.
The one to the left is using AsyncHttpClient the one on the right BlazeClientBuilder. That is the only change done in the code.
Also attached is a screenshot of the analysis of the heap dump in eclipse memory analyzer saying that io.netty.channel.socket.nio.NioSocketChannel was the one that built up in memory.
Version used 0.21.0

We use 2 instances of the client. 
```
  object HttpClient {
    private[this] val streamingHttpClientConfig = new DefaultAsyncHttpClientConfig.Builder().setRequestTimeout(-1).setReadTimeout(-1).build()

    def rpc[F[_]: ConcurrentEffect]: Resource[F, Client[F]]   = AsyncHttpClient.resource[F]()
    def streaming[F[_]: ConcurrentEffect]: Resource[F, Client[F]] = AsyncHttpClient.resource[F](streamingHttpClientConfig)
  }
```

One for traditional rpc types of calls, and one for subscribing to a serversent event http stream from a http4s server. I am not certain which one of the two instances that eat up memory

![image](https://user-images.githubusercontent.com/82751/74538971-85866c00-4f3d-11ea-9c55-d79436720a20.png)
![image (1)](https://user-images.githubusercontent.com/82751/74539025-9931d280-4f3d-11ea-97c7-1fd449a6ba47.png)

**Comment by rossabaker** [comment]
I'll hazard a guess it's the streaming one, but it would help a lot to see a repro, or failing that, to narrow it down.  Since blaze seems unaffected, maybe running one as blaze and one as AHC, and then flipping, would show something.

**Comment by rossabaker** [comment]
Not enough to reproduce this, but please reopen if you have something.
