### ISSUE TITLE
Consider using alternative to `Files.probeContentType` for static content mime type

### ISSUE THREAD

**Issue by stephenjudkins** [http4s/http4s#322]
It turns out that the implementation is buggy, not standard across platforms, and depends on `~/.mime.types` files. I'd argue that, since we have file extensions already in `MediaType`, guessing content types from that would be a preferable approach.

**Comment by rossabaker** [comment]
I've heard good things about Apache Tika, but I wouldn't be excited about carrying around a new jar just for that.  There is also [Transparently improve Java 7 mime-type recognition with Apache Tika](https://odoepner.wordpress.com/2013/07/29/transparently-improve-java-7-mime-type-recognition-with-apache-tika), which is simultaneously intriguing and nauseating.

**Comment by ShengC** [comment]
I think we should be pragmatic and "choose bad over worse" in this case, which essentially means using`MediaType.forExtension` consistently across the code base until `jdk` can fix the buggy `probeContentType`. I am not a big fan of introducing another library just for the sake of determining the mime type.

**Comment by ritschwumm** [comment]
ServletContext#getMimeType works better - would it make sense to use that when available? probably not, but i think it's a question work asking.

**Comment by ShengC** [comment]
@ritschwumm let's think about this ? what if user just wanna show an html file as `text/plain` in the browser ? I *think* we should _not_ overthink from user's perspective. If a file is with extension ".html", then best guess of server should just send back `content-type` of `text/html`, no matter what the actual content is ...

**Comment by bryce-anderson** [comment]
I was not aware that the `probeContentType` function was broken. Good to know.

The Apache Tika project doesn't look all that bad, its a relatively small jar. That said, I'm of the opinion that we should use `MediaType.forExtension` as the primary method of determining the media type. Its probably the most intuitive method and has the advantage of not needing to actually access the file system which is a hidden blocking call in our asynchronous framework.
 Is there a case where we would want to use `probeContentType` as a backup, or should we just give it the ax? I'm somewhat content to just give it the ax for the sake of consistency.

**Comment by stephenjudkins** [comment]
I think we should give it the axe. The default behavior should be simple, predictable, and not dependent on either implicit IO or system configuration. If someone wants something more exotic it could be implemented with different middleware that's more explicit about what it's doing.

**Comment by bryce-anderson** [comment]
Note PR #381.

**Comment by ritschwumm** [comment]
@ShengC ultimately you either know the mime type, or you have to guess. you might try an educated guess - based on the file extension or content probing - but which one is 'better' very much depends on the use case. personally, i try to avoid this kind of guesswork, but people seem to want it.

**Comment by rossabaker** [comment]
I agree with "the default behavior should be simple, predictable, and not dependent on either implicit IO or system configuration".  Magic has its place, and that place is opt-in middleware.
