### ISSUE TITLE
Correct comments/docs about: HTTP connection is disposed after many client functions

### ISSUE THREAD

**Issue by kovacshuni** [http4s/http4s#3229]
Often displayed scaladoc comments and [in the API](https://http4s.org/v0.21/api/org/http4s/client/client) statements like:

_The underlying HTTP connection is closed at the completion of the decoding._

and variations of it don't seem to be true for me.

Checked with tcpdump, connection is maintained between multiple calls happening to the same host.
Tested this within a stream of HTTP requests-responses even set apart by 1 second gaps.

Also such implementation detail appearing on the interface `Client` is not a good practice. Connection handling should depend on the implementation (if this is not a very specific client aimed to close after each request) and comments should appear, for example, in the `blaze-client` subproject.

Tell me if i'm wrong. Even if I'm not seeing something or I didn't understand correctly, probably more people do the same and there should be some better clarification, documentation about how connections are maintained through multiple HTTP requests.

**Comment by armanbilge** [comment]
Addressed in https://github.com/http4s/http4s/pull/6313.
