### ISSUE TITLE
Can't execute applicative calls with import org.http4s.dsl._. 

### ISSUE THREAD

**Issue by wpoosanguansit** [http4s/http4s#323]
Hi,

I am not sure if this is intended and there is some setup that needs to be done for the code to use scalaz.  I am simply trying to use applicative for object init.  Something like:

9.some <*> {(_: Int) + 3}.some

doesn't compile if I do have import org.http4s.dsl._ along with import scalaz._ and import Scalaz._.  It compiles when I take it off.  Scalaz is the latest v. 7.1.3.  What should be done?  Thanks for your help.

**Comment by rossabaker** [comment]
It works with the following imports in place of the Scalaz wildcards:

```scala
  import scalaz.syntax.apply._
  import scalaz.syntax.std.option._
```

It also works if `org.http4s.Http4s` does not extend `scalaz.std.AllInstances`.  That was done to reduce the "import tax", but may have been a bad idea.  Would any Scalaz experts like to chime in on proper import idiom?

**Comment by bryce-anderson** [comment]
If we are thinking of supporting `cats`, maybe now is the time to drop the scalaz specific import tricks. Whether the `cats` business will happen is a whole different, and long, discussion.

**Comment by rossabaker** [comment]
Does anybody else have that recurring nightmare where all their open source projects are run through the C preprocessor to handle directives like `#ifdef CATS` and `#ifdef SCALAZ` and then wake up in a cold sweat?

Whether and how Cats support happens depends on whether and how scalaz-stream handles the issue.  I don't want to reinvent Scalaz types, but if we can avoid gratuitous couplings like this one, it puts us in better position to eventually support whichever FP librar{y,ies} have critical mass in the future.

**Comment by LeifW** [comment]
I like doing the specific imports, both to speed up compile times, and also things can sometimes go haywire with interactions when `scalaz.Scalaz._` is imported. Then again, I'm the kind of guy who favors naming specific things being imported over importing ._ in a lot of cases (I like to see explicitly where identifiers are coming from). My coworkers at my last job would complain "I don't want to use scalaz cause I don't know what imports to use, and Scalaz._ breaks stuff." :/

**Comment by rossabaker** [comment]
Yes, I've always avoided the Scalaz wild card imports.  I think it follows in that same spirit that we not extend `AllInstances` ourselves.
