### ISSUE TITLE
Logger should consider MediaType.application.`vnd.api+json` as text

### ISSUE THREAD

**Issue by carlos-verdes** [http4s/http4s#3231]
In the next line of Logger middleware you can observer an `isJson` clause:
```scala
val isJson = message.contentType.exists(mT =>
      mT.mediaType == MediaType.application.json || mT.mediaType == MediaType.application.`vnd.hal+json`)
```

I'm doing an implementation using MediaType.application.`vnd.api+json` which is also json.
Is is possible to add on the source code so it's logged as json?
It would help a lot the debug :)

https://github.com/http4s/http4s/blob/b97d92bd82c6e6cc7b26d8e49b0497aa27a3ac63/server/src/main/scala/org/http4s/server/middleware/Logger.scala#L60

**Comment by rossabaker** [comment]
I have a feeling there are a lot of these, and there's no field in the IANA database we parse to find them.  We might do better to change this check to anything that ends in `+json`?

**Comment by m3is0** [comment]
I'd like to work on it!
