### ISSUE TITLE
Pre-signed AWS URIs expect no decoding of %2F ('/')

### ISSUE THREAD

**Issue by glammr1** [http4s/http4s#3233]
Description: Parsing URIs is correct according to RFC 3986, but AWS expects its pre-signed AWS URIs to be used as-is without URL-decoding in the query string.

Reproducible example (using ammonite with http4s 0.21.1):

```
Uri.fromString("https://bucket.s3.amazonaws.com/object?uploadId=.KFey.IJHLCmyRpxkyssU9KS0hh0TC9Z6ALXh1y.M8S44xAT1c19kIfwqYQu2kiYIXCyvFlPTHnahpag9z0VBVL790o3WnmB.qge9ly3jXazG0N1bnc5whj5c_P0DXPn&partNumber=1&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20200304T142549Z&X-Amz-SignedHeaders=content-length%3Bcontent-md5%3Bhost&X-Amz-Expires=119&X-Amz-Credential=AKXXXXXXXXXXXXXXXXXX%2F20020304%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=e2437fe26dcef3f5118150b1c316ca286098335981256e421a3ff676489ea703")
res0: ParseResult[Uri] = Right(
  Uri(
    Some(Scheme(https)),
    Some(Authority(None, RegName(bucket.s3.amazonaws.com), None)),
    "/object",
    uploadId=.KFey.IJHLCmyRpxkyssU9KS0hh0TC9Z6ALXh1y.M8S44xAT1c19kIfwqYQu2kiYIXCyvFlPTHnahpag9z0VBVL790o3WnmB.qge9ly3jXazG0N1bnc5whj5c_P0DXPn&partNumber=1&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20200304T142549Z&X-Amz-SignedHeaders=content-length%3Bcontent-md5%3Bhost&X-Amz-Expires=119&X-Amz-Credential=AKXXXXXXXXXXXXXXXXXX/20020304/us-east-1/s3/aws4_request&X-Amz-Signature=e2437fe26dcef3f5118150b1c316ca286098335981256e421a3ff676489ea703,
    None
  )
)
```

Note that the `%2F` is translated to `/` in the query string.  The corresponding renderer then does not re-escape the `/` back into `%2F` and AWS rejects the URI with a 400, presumably because it cannot verify the signature.

Suggested fix: make the decoding `toSkip` list configurable for instances like this?  Alternatively, enable the writer to be configured to encode `/` back into `%2F` (e.g. Query.NoEncode = "?" instead of "?/"; the RFC referenced in the comment above does say "sometimes" instead of "MUST" or always.)

**Comment by rossabaker** [comment]
This is somewhat tied into @hamnis' work on #3221.  He is working on the path, and this is the query, but it's manifestations of the same basic problem: are we storing decoded values and encoding at render time, or are we storing raw values and decoding as we process them?  

If we store decoded values, processing becomes simpler, but we lose the ability to round trip.

If we store raw values, we need to be careful about string operations.  We need to consider normalization every time we do pattern matching.  Does like `uri"http://example.com" / "a/b"` result in `http://example.com/a/b` or `http://example.com/a%2fb`?

**Comment by Daenyth** [comment]
> Does like uri"http://example.com" / "a/b" result in http://example.com/a/b or http://example.com/a%2fb?

Just noting for posterity that it currently is the latter - it's a bit of a footgun for new users
