### ISSUE TITLE
Ember Client Request Concurrency Issues

### ISSUE THREAD

**Issue by bpholt** [http4s/http4s#3235]
AFAICT, there are a couple places where Ember-client tries to read and write to its socket connection concurrently:

https://github.com/http4s/http4s/blob/aebcde970df3fcac182cd8a93989a1dd327c63b4/ember-client/src/main/scala/org/http4s/ember/client/internal/ClientHelpers.scala#L85-L92

https://github.com/http4s/http4s/blob/aebcde970df3fcac182cd8a93989a1dd327c63b4/ember-client/src/main/scala/org/http4s/ember/client/internal/ClientHelpers.scala#L70-L78

I frequently run into issues with this implementation throwing `org.http4s.ember.core.EmberException$ParseError: Incomplete Header received (sz = 0): Right()` when making HTTPS requests. (It seems fine when TLS is not involved, but that's hard to prove.)

I rewrote `ClientHelpers.request` to send the request before reading from the socket, and I haven't seen this error since. I'm not sure if this is really the solution, so I thought I'd open it up for discussion before making a PR.

```scala
def request[F[_]: Concurrent: ContextShift](
    request: Request[F],
    requestKeySocket: RequestKeySocket[F],
    chunkSize: Int,
    maxResponseHeaderSize: Int,
    timeout: Duration
)(logger: Logger[F])(implicit T: Timer[F]): F[Response[F]] = {
  def writeRequestToSocket(socket: Socket[F], timeout: Option[FiniteDuration]): fs2.Stream[F, Unit] =
    Encoder
      .reqToBytes(request)
      .through(socket.writes(timeout))

  def onNoTimeout(socket: Socket[F]): F[Response[F]] =
    writeRequestToSocket(socket, None).compile.drain >>
      Parser.Response.parser(maxResponseHeaderSize)(
        socket.reads(chunkSize, None)
      )(logger)

  def onTimeout(socket: Socket[F], fin: FiniteDuration): F[Response[F]] =
    for {
      start <- T.clock.realTime(MILLISECONDS)
      _ <- writeRequestToSocket(socket, Option(fin)).compile.drain  // this used to start a fiber
      timeoutSignal <- SignallingRef[F, Boolean](true)
      sent <- T.clock.realTime(MILLISECONDS)
      remains = fin - (sent - start).millis
      resp <- Parser.Response.parser[F](maxResponseHeaderSize)(
        readWithTimeout(socket, start, remains, timeoutSignal.get, chunkSize, logger.mapK(fs2.Stream.functionKInstance))
      )(logger)
      _ <- timeoutSignal.set(false).void
    } yield resp

  timeout match {
    case t: FiniteDuration => onTimeout(requestKeySocket.socket, t)
    case _ => onNoTimeout(requestKeySocket.socket)
  }
}
```

@ChristopherDavenport do you have any thoughts? What else can I provide to further narrow this down?

**Comment by ChristopherDavenport** [comment]
If it fixes that issue, then that is definitely worth integration. We should be able to read and write concurrently, but that is perhaps something that takes more coordination.
