### ISSUE TITLE
Thread leak in async http client

### ISSUE THREAD

**Issue by djspiewak** [http4s/http4s#3236]
```scala
          Resource(F.async[(Response[F], F[Unit])] { cb =>
            c.executeRequest(toAsyncRequest(req), asyncHandler(cb))
            ()
          })
```

This is incorrect (in `AsyncHttpClient.scala`. You need to `guarantee` a `shift` following the `async`. Unfortunately, you don't have a `ContextShift` in scope here, only a `ConcurrentEffect`, which makes this a little tricky to correct. It has real consequences though: we're seeing heap dumps with compute running on the async-http-client worker pool. An amusing example:

<img width="1211" alt="Screen Shot 2020-03-08 at 9 19 43 PM" src="https://user-images.githubusercontent.com/752/76180100-9ca62b80-6182-11ea-8e57-b30753fab06e.png">

You'll notice that we managed to get part of the http4s-server machinery scheduled onto the async-http-*client* thread pool.

**Comment by rossabaker** [comment]
We have fixed these issues in the past with name change and deprecation of the broken one.  One option is to introduce the builder pattern used on many other backends, but we only have one parameter for the builder.  

A second option is to introduce `stream0`, `resource0`, etc., but then people will need to switch, and switch back next release.  We've done that before on lesser used middlewares, but this would be the highest profile case of that.

**Comment by djspiewak** [comment]
Actually I realized retroactively that we can fix this just using `ConcurrentEffect` by using the same trick as `invokeCallback`. I'll write that up.
