### ISSUE TITLE
Design issue affecting middleware & route composability

### ISSUE THREAD

**Issue by japgolly** [http4s/http4s#3245]
Hello! :wave: 

So firstly, I meant to raise this so long ago so apologies if I get a few details wrong. I'm not currently working on a http4s project so I have to go from memory. Finally I need to be doing other work right now so I'm just going to smash this out without polish.

Requests are currently isomorphic to `Request => IO[Option[Response]]` right? That shape makes it impossible to do a safe authentication middleware because there's no way for the middleware to know whether a request has a response without executing it.

I've give a concrete example.

1. Say you've got a deleteUser route. Provide a Request with `/user/3/delete` and it returns an IO. Execute that IO and it deletes user 3 from the DB and returns `Some[Response]`
2. An auth middleware has two choices in how to wrap this...
    1. Check JWT immediately and return `IO[Some[NahMateFailure]]` on auth-fail, even if the Request has a url of `/about`
    2. Call underlying route to see if it's applicable to the given route. If it is (i.e. underlying returns `IO[Some`), then check JWT and return `Some[NahMateFailure]` on auth-fail

Can you see the problem here?
1. Method 1 means we lock down *all* routes. It also means we can't compose it with other routes because it will return `IO[Some` which will prevent other composed routes from even getting a chance to respond.
2. Method 2 means we retain route composability but actually perform the deletion before we the auth-check.

My idea on how to solve this you'd actually need a `Request => IO[Option[IO[Response]]]` where the first IO layer (contractually) allows for checking preconditions and the inner IO layer actions the request and can mutate the world accordingly. With this design a middleware could safely merge with the outer-layer IO to run it's own side-effects (eg. maybe check user exists in DB or whatever), then give the underlying route a change to check the URI and maybe perform it's own side-effect-driving pre-conditions. Only if we get a `Some[IO[Response` do we activate the authentication and then execute the response handler.

Ok cool, I hope this was helpful. Cheers & good luck!

**Comment by rossabaker** [comment]
It has been our position that authentication should not first check whether there is a matching route, because the difference between a 401 and a 404 leaks information.  The traditional way to make this composable with public routes is to put the public routes first in `<+>`, or to use a `Router` where a prefix is hidden.  This proposal is more powerful, but the extra power is very rarely what you actually want.
