### ISSUE TITLE
[Docs] Port tut to mdoc

### ISSUE THREAD

**Issue by marcraminv** [http4s/http4s#3259]
[Tut library](https://github.com/tpolecat/tut) has not support for 2.13.x(https://github.com/tpolecat/tut/issues/263), and it is not maintained in support to [mdocs](https://scalameta.org/mdoc/).

- [ ] Replace plugin (keep in mind the source directory where docs are placed)
- [ ] Replace `tut` by `scala mdoc` syntax
- [ ] Fix duplicates naming variables with [`nest`](https://scalameta.org/mdoc/docs/tut.html#double-binding) feature from mdoc

**Comment by marcraminv** [comment]
@rossabaker as you know, I can help you with this one.

**Comment by rossabaker** [comment]
Fixed by #3399.
