### ISSUE TITLE
Quick start page is outdated

### ISSUE THREAD

**Issue by anilkumarmyla** [http4s/http4s#3260]
In https://http4s.org/v0.21/ this part about HelloWorldServer & HelloWorldService and the subsequent lines don't match the current code in http4s.g8 (this was part of 0.18 series)
```
$ find src/main -name '*.scala'
./src/main/scala/com/example/http4squickstart/HelloWorldServer.scala
./src/main/scala/com/example/http4squickstart/HelloWorldService.scala
```

**Comment by rossabaker** [comment]
Agreed. Any volunteers to clean this up? It would be in docs/src/main/tut/index.md.

**Comment by Guisanpea** [comment]
Taking a look to it

**Comment by Guisanpea** [comment]
Shouldn't this be marked as solved?

**Comment by rossabaker** [comment]
Yes! Sometimes we miss these when the PR doesn't have one of the magic GitHub ticket-closing words.
