### ISSUE TITLE
bufferSize in Gzip middleware factory method is not used in the body stream of response

### ISSUE THREAD

**Issue by ShengC** [http4s/http4s#327]
def apply(service: HttpService, buffersize: Int = 512, level: Int = Deflater.DEFAULT_COMPRESSION): HttpService = {
    ...
              val b = emit(ByteVector.view(header)) ++
                        resp.body.pipe(scalaz.stream.compress.deflate(level = level, nowrap = true))
              // shouldn't it be
              // val b = emit(ByteVector.view(header)) ++
              //          resp.body.pipe(scalaz.stream.compress.deflate(level = level, nowrap = true, bufferSize = bufferSize))

    ...

**Comment by rossabaker** [comment]
Yes, thank you!

**Comment by rossabaker** [comment]
Will be releated in v0.8.4.
