### ISSUE TITLE
Recycled Connection uses old idleTimeout stages.

### ISSUE THREAD

**Issue by FreddieSanchez** [http4s/http4s#3283]
I'm using a BlazeClient http4s v0.20.15 on blaze v0.14.11 and setting a very high idleTimeout but randomly, I still get timeouts after 60 seconds.
```
java.util.concurrent.TimeoutException: Idle timeout after 60000 ms.
        at org.http4s.blazecore.IdleTimeoutStage$$anon$1.run(IdleTimeoutStage.scala:27)
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

I'm building the client like so:
```
    for {
        ec2 <- ExecutionContexts.fixedThreadPool[IO](32)
        timeout = 30.minutes
        lemurClient <- BlazeClientBuilder[IO](ec2)
          .withIdleTimeout(timeout)
          .withResponseHeaderTimeout(Duration.Inf)
          .withRequestTimeout(timeout)
          .resource
...
```

It appears here https://github.com/http4s/http4s/blob/3baf5d6baff7536937b3976595141e686ec31bb1/blaze-client/src/main/scala/org/http4s/client/blaze/BlazeClient.scala#L75
the `IdleTimeoutStage` is spliced into the connection. 

However, here https://github.com/http4s/http4s/blob/63f3dbaf1f5c3887ae6b9baf0d167bb55974d413/client/src/main/scala/org/http4s/client/PoolManager.scala#L161 the connection is recycled without any clearing of the connections stages. 

This leads to recycled connections to use `idleTimeout` from a previous request which may have been used for a different client with a different `idleTimeout`.

**Comment by rossabaker** [comment]
I'm not feeling my sharpest right now, but aren't we removing the stage [here](https://github.com/http4s/http4s/blob/3baf5d6baff7536937b3976595141e686ec31bb1/blaze-client/src/main/scala/org/http4s/client/blaze/BlazeClient.scala#L96-L97) before we recycle?

**Comment by FreddieSanchez** [comment]
@rossabaker I believe you are correct. 

The original issue had nothing to do with the the http4s client (library versioning issue). 

Closing this issue.
