### ISSUE TITLE
Client request execution gives Segmentation Fault in graal / native-image binary 

### ISSUE THREAD

**Issue by drocsid** [http4s/http4s#3288]
Example of `Segmentation Fault` using `http4s` with graal `native-image`. I've published reproduction steps in my example repository.

https://github.com/drocsid/https_example

```
[scala-execution-context-global-11] INFO  c.e.w.WeatherdemoRoutes - request IO(Request(method=POST, uri=https://api.flowroute.com/v2/messages, headers=Headers(Content-Type: application/json, Content-Length: 95))) 
[ioapp-compute-0] DEBUG o.h.c.PoolManager - Requesting connection: curAllocated=1 idleQueues.size=1 waitQueue.size=0 maxWaitQueueLimit=256 closed=false 
[ioapp-compute-0] DEBUG o.h.c.PoolManager - Active connection not found. Creating new one. curAllocated=1 idleQueues.size=1 waitQueue.size=0 maxWaitQueueLimit=256 closed=false

Segmentation Fault
```

**Comment by drocsid** [comment]
Looks like I have solved my own issue with the `native-image` argument `--enable-all-security-services`

**Comment by drocsid** [comment]
Sometime it makes successful requests but most frequently I get a segfault.

**Comment by drocsid** [comment]
I've been using the Blaze Client Builder. I'm going to try using other clients, and see if I end up with one that works for Graal / native-image...

**Comment by drocsid** [comment]
I've tried building and testing native-images against 4 clients. https://github.com/drocsid/https_example/blob/master/src/main/scala/com/example/weatherdemo/WeatherdemoServer.scala#L25

Not every request generates a segfault. However every client segfaults within a few requests via native-image binary. But when testing against the Blaze client run against a jar on the JDK, can continually make requests without exception or crash.

**Comment by rossabaker** [comment]
I don't have much GraalVM experience, other than to test a toy server.

Java does weird things initializing an SSLContext.  I wonder whether it's more stable hitting a service that doesn't use SSL.  That's not an acceptable answer to the problem, but might help narrow it down?

**Comment by drocsid** [comment]
However on lines above we make a get request via SSL : 

https://github.com/drocsid/https_example/blob/master/src/main/scala/com/example/weatherdemo/WeatherdemoRoutes.scala#L47

I don't think that request causes any segfault issues.
 
Then would it be specifically related to the POST request?

Finally I think a different issue might exist when running against the EmberClient. I will toggle this example back to Blaze for now.

**Comment by drocsid** [comment]
@rossabaker I removed the --static flag from `native-image` which I think creates a static binary vs. linked. Anyhow removing that and the application seems to work against blaze. My lucky day as I'm going to deploy my hobby application soon!

**Comment by drocsid** [comment]
Created an issue regarding --static on https://github.com/oracle/graal/issues/2309

**Comment by rossabaker** [comment]
Glad to hear it.  I added an issue so we can document what you found.
