### ISSUE TITLE
StaticFile.fromURL throws IllegalStateException when called on a directory in resources

### ISSUE THREAD

**Issue by chadselph** [http4s/http4s#3289]
Here's the snipplet of the stacktrace

```
[scala-execution-context-global-28] ERROR o.h.s.b.Http1ServerStage$$anon$1 - Error writing body 
java.lang.IllegalStateException: Expected `Content-Length: 96` bytes, but only 11 were written.
	at org.http4s.blazecore.util.IdentityWriter.writeEnd(IdentityWriter.scala:70)
	at org.http4s.blazecore.util.EntityBodyWriter.$anonfun$writeEntityBody$1(EntityBodyWriter.scala:53)
	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:87)
	at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:359)
```

Looks like it's using `openConnection().getContentLength` for content length header, which actually calls `File::getSize` on the directory but the bytes come from `URL::openStream` which apparently returns newline separated file listing:

```
new String(u.openStream().readAllBytes())
$23 ==> ".git\n.gitignore\n.idea\nbuild.sbt\nindex.html\nproject\nREADME.md\nsrc\ntarget\n"
```

Not sure what expected behavior should be for directories, probably either have always return `OptionT.none` like it does for `StaticFile.fromFile`. Unfortunately it looks like there's no straightforward way to determine this.

Note: this doesn't happen when the resources are packaged in the jar, since `JarURLConnection` just returns 0 for file size and no bytes

**Comment by rossabaker** [comment]
Yuck.  Well, `getURL` on the resource tells us whether it's a file, and from there we could use the file API to tell if it's a directory?  Would still be nice to make it consistent between file service and jar service.

**Comment by ashwinbhaskar** [comment]
@rossabaker I can pick this up.

**Comment by ashwinbhaskar** [comment]
I am not able to reproduce this. Should this have produced the exception?

```
 val s = StaticFile
        .fromURL[IO](getClass.getResource("/foo"), testBlocker)
        .value
        .unsafeRunSync
        .fold[EntityBody[IO]](sys.error("Couldn't find resource"))(_.body)
```
where `foo` is a folder in resources directory with no files in it. The value of `s` is an empty string.

**Comment by chadselph** [comment]
There's several layers to this bug, but specifically the `IllegalStateException` happens when you try to return it as a response, since it's trigger by the content-length not matching. Check `_.contentLength` 

The way the bug surfaces in your examples is that StaticFile.fromUrl on a folder in resources directory with no files in it should probably resolve to `OptionT.none`, not an empty string.

You can connect these together with

```
scala> val s = StaticFile.fromURL[IO](getClass.getResource("/"), testBlocker).value.unsafeRunSync
s: Option[org.http4s.Response[cats.effect.IO]] = Some(Response(status=200, headers=Headers(Content-Length: 192, Last-Modified: Fri, 26 Jun 2020 17:20:58 GMT)))
```

relevant here is `headers=Headers(Content-Length: 192`, which is a different number of bytes actually in `_.body`.

```
scala> s.get.body.compile.toVector.unsafeRunSync.length
res67: Int = 27
```
