### ISSUE TITLE
staticcontent.fileService behavior change after 21.1

### ISSUE THREAD

**Issue by drocsid** [http4s/http4s#3308]
in 21.1 fileService served index.html to / which seems like a handy way to deploy a micro site. There might have been a security flaw that caused the change.

after 21.1 index.html is no longer served to root. Then as a display of my ignorance I needed to create two routes to achieve this.

```
  def fileServiceImpl[F[_] : Sync : ContextShift](blocker: Blocker) = {
    val dsl = new Http4sDsl[F] {}
    import org.http4s.server.staticcontent.fileService
    fileService[F](FileService.Config("/site/", blocker, "/"))
  }

  def staticRoutes[F[_] : Sync : ContextShift](blocker: Blocker): HttpRoutes[F] = {
    val dsl = new Http4sDsl[F] {}
    import dsl._

    HttpRoutes.of[F] {
      case request@GET -> Root =>
        StaticFile.fromFile(new File("/site/index.html"), blocker)
          .getOrElseF(NotFound()) // In case the file doesn't exist
    }
  }
```

**Comment by rossabaker** [comment]
That change is unintentional.  We still have a passing unit test for index.html being served.  I wonder if we broke something subtle with regards to trailing slashes.  I'm going to tentatively call this a bug and come back to it once I catch up on the other backlog.

**Comment by danbim** [comment]
FYI: made the test fail by changing it to:
```
"Return index.html if request points to a directory" in {
      val path = Paths.get(defaultSystemPath).resolve("testDir/")
      println(path)
      val s0 = fileService(
        FileService.Config[IO](systemPath = path.toAbsolutePath.toString, blocker = testBlocker))
      val req = Request[IO](uri = uri("/"))
      val rb = s0.orNotFound(req).unsafeRunSync()

      rb.as[String] must returnValue("<html>Hello!</html>")
      rb.status must_== Status.Ok
    }
```
Using `defaultSystemPath` in `FileService.Config` and requesting `/testDir/` works nicely though so it seems to be related to requesting the root resource `/` as it seems to only fail in this case.

**Comment by danbim** [comment]
Opened a PR to fix the bug: https://github.com/http4s/http4s/pull/3331
