### ISSUE TITLE
Allow passing a ClassLoader to ResourceService and WebjarService

### ISSUE THREAD

**Issue by nigredo-tori** [http4s/http4s#3313]
See #2834 for motivation. `StaticFile.fromResource` now has a `ClassLoader` parameter, but `ResourceService` [always uses the default value](https://github.com/http4s/http4s/blob/v0.21.3/server/src/main/scala/org/http4s/server/staticcontent/ResourceService.scala#L58-L63). Same goes for `WebjarService`.

**Comment by rossabaker** [comment]
:+1: This would be great. Easy to do source compatibly, probably harder to do binary compatibly.

**Comment by ashwinbhaskar** [comment]
@rossabaker can I take this up

**Comment by rossabaker** [comment]
If it's binary compatible, please target series/0.21.  If it's not, master.  If in doubt, try series/0.21, and we can change the base to master if that's wrong.

**Comment by ashwinbhaskar** [comment]
@rossabaker I am unable to run `WebjarServiceSpec`. `sbt test:testOnly *WebjarServiceSpec` does not seem to run the tests in `WebjarServiceSpec`

```
[info] Finished in 68 ms
[info] 0 example, 0 failure, 0 error
[info] Passed: Total 0, Failed 0, Errors 0, Passed 0
```

How can I run them?

**Comment by nigredo-tori** [comment]
@ashwinbhaskar, it's in the `server` subproject, so it should be
```
server/test:testOnly *WebjarServiceSpec
```
You might also need to properly escape the arguments - or just start `sbt`, and run the command above there.

**Comment by ashwinbhaskar** [comment]
@nigredo-tori my bad, I did not paste my command here correctly. I did try within in the server subproject. But `WebjarServiceSpec` tests don't seem to run. But `ResourceServiceSpec` tests run

**Comment by nigredo-tori** [comment]
@ashwinbhaskar, confirmed, the tests aren't run. I suppose, this is https://github.com/etorreborre/specs2/issues/757, since the default Scala version is 2.13.1. Changing `WebjarServiceSpec` from `object` to `class` fixes this.

**Comment by ashwinbhaskar** [comment]
@nigredo-tori I will refrain from changing `object` to `class` in this PR. Because there are other specs too which are `objects` and it might be confusing as to what this PR is trying to address.  WDYT?

**Comment by nigredo-tori** [comment]
IMO, if there's a bug that prevents the changes in this PR from being properly tested, and you can trivially fix it (at least for this particular place), then it's fair game. But let's wait and see what the maintainers say.

**Comment by ashwinbhaskar** [comment]
@rossabaker your call.

**Comment by ashwinbhaskar** [comment]
@rossabaker wdyt?
