### ISSUE TITLE
org.http4s.client.middleware.Metrics does not record elapsed time on timeout

### ISSUE THREAD

**Issue by tian000** [http4s/http4s#3315]
The documentation/and comments on org.http4s.client.middleware.Metrics says that "Time duration of errors, timeouts and other abnormal terminations" is recorded.

But we see on line 73, that the duration is not recorded, but rather a hard coded value of 1 nano second is recorded.

https://github.com/http4s/http4s/blob/2c21e66d8312973ba159c6c271bf9e6225077b60/client/src/main/scala/org/http4s/client/middleware/Metrics.scala#L73

**Comment by rossabaker** [comment]
Hmm, yeah, I can't think why we would do that, and if there is a reason, we need to more clearly explain ourselves.

**Comment by tian000** [comment]
@rossabaker Happy to put up a PR that records the time from `start` up until `registerError` is called if that's the desired behavior.

**Comment by rossabaker** [comment]
That would be great, thanks!

**Comment by tian000** [comment]
@rossabaker this issue can be closed i think?

**Comment by rossabaker** [comment]
Yes, thanks.  When I cherry-pick instead of merge, we don't get the auto-close.  But your fix is in snapshots for 0.20, 0.21, and 1.0 now. I hope to release this week.
