### ISSUE TITLE
Uri parser fail

### ISSUE THREAD

**Issue by alissapajer** [http4s/http4s#333]
Hello,

case 1: succeeds
```scala
scala> Uri.fromString("http://172.17.0.21:2091/pathystuff").toOption.get
res19: org.http4s.Uri = http://172.17.0.21:2091/pathystuff
```

case 2: fails
```scala
scala> Uri.fromString("http://172.17.0.217:2091/pathystuff").toOption.get
res20: org.http4s.Uri = http://172.17.0.21
```

It seems when the provided IP address has three digits in the fourth block (`217` in case 2), the parser fails.

Background: The IP address in case 2 is the IP of a running docker container. According to [docker docs](https://docs.docker.com/articles/networking/) this address is chosen from the range RFC 1918. Reading the http4s [Uri source](https://github.com/http4s/http4s/blob/master/core/src/main/scala/org/http4s/Uri.scala#L124), I see that `Uri.fromString` is using RFC 3986 to encode. This is probably the problem :)

Similarly, I tried `Uri.requestTarget` (which uses RFC 7230) and the same decode problem occurs.

Is there currently a way to decode RFC 1918? If not, do you think it would be worth adding? Especially since docker containers use it, it seems likely that others will hit the problem again :)

**Comment by bryce-anderson** [comment]
Which version are you using? Commit 2e9254c925a01d435b53597a0979b54ba038b435 should have fixed this and is available in 0.8.3.

**Comment by alissapajer** [comment]
I'm back on 0.7.0, it seems. I'll try out the later version, thanks!

**Comment by alissapajer** [comment]
Fix is confirmed:

```scala
scala> Uri.fromString("http://172.17.0.217:2091/pathystuff").toOption.get
res0: org.http4s.Uri = http://172.17.0.217:2091/pathystuff

scala> res0.path
res1: org.http4s.Uri.Path = /pathystuff
```

Thanks!
