### ISSUE TITLE
websocket not closed properly ?

### ISSUE THREAD

**Issue by ShengC** [http4s/http4s#334]
created a route like this...

      import scalaz.stream._
      import scalaz.concurrent._
      
      val queue = async.boundedQueue[String](10)
      
      import scalaz.syntax.monad._
      
      val src = queue.dequeue.map(Text(_)).onComplete(Process.eval_(Task.delay(Console.println("I'm done!")) >> queue.close))

      WS(Exchange(src, Process.halt))

point browser to do websocket connection with server using this route, of course nothing is sent to the page. Then close the browser, the onComplete message is not printed in the console.

**Comment by ShengC** [comment]
Reading Http4sWSStage, and here is the sink code for Exchange.read ...

   def sink: Sink[Task, WebSocketFrame] = {
      def go(frame: WebSocketFrame): Task[Unit] = {
        Task.async { cb =>
          if (!alive) cb(-\/(Terminated(End)))
          else {
            channelWrite(frame).onComplete {
              case Success(_)           => cb(\/-(()))
              case Failure(Command.EOF) => cb(-\/(Terminated(End)))
              case Failure(t)           => cb(-\/(t))
            }(directec)
          }
        }
      }
  
      Process.constant(go)
    }

    ....

    ws.exchange.read.through(sink).run.runAsync(onFinish)

if no messages has ever been emit from read, sink won't even have a chance to signal Terminated(end) (remember `through` in its essence is just a tee, so if read does not emit anything, sink gets stuck too). I *think* the right way to do it is to switch `alive` from a var to a signal, and somehow wye the process to it with `interrupt`

**Comment by bryce-anderson** [comment]
That is a bit of a nasty situation. I'll look into it some more. 

Fair warning: this is pretty low on my priority list right now, but PR's are welcome. :smile:

**Comment by ShengC** [comment]
Not sure how this can be unit tested - I tested it in the browser with the custom route and it fixed that problem.

**Comment by bryce-anderson** [comment]
closed via #335.

**Comment by bryce-anderson** [comment]
@ShengC, fyi: 0.8.4 should be in Maven Central now. Thanks again for the PR.

**Comment by ShengC** [comment]
@bryce-anderson thanks :)
