### ISSUE TITLE
Update documentation examples to use async-http instead of blaze

### ISSUE THREAD

**Issue by Daenyth** [http4s/http4s#3348]
It seems like the general consensus on gitter has been for a while that most people should prefer to use implementations other than blaze.

To that end, I suggest:
- Update the documentation on the site to show async-http as the 'safe default'
- Have a doc somewhere (maybe just an issue ticket we can link to) explaining the specifics about why they might want another (eg, has flappy tests reducing confidence, isn't fully nonblocking, small bus factor because it's an in-house project, future dev effort more likely to go toward ember instead, etc)

**Comment by rossabaker** [comment]
We've talked about splitting integrations into a polyrepo, which raises a question of which backend, if any, stays in the main repo.  I'd argue for none, except that would make documentation hard.  If we keep one, Ember or JDK8 make the most sense, and JDK8 is really crappy.  So I think switching to ember is correct in the long term here.

So I'm fine with this, although it's not a great long-term answer.

I also agree we need a matrix of the backends and their features, which could live in the core repo.

**Comment by rossabaker** [comment]
We're going to cut the docs over to Ember as the default in 0.22.
