### ISSUE TITLE
Change basic authentication to use UTF-8

### ISSUE THREAD

**Issue by nigredo-tori** [http4s/http4s#3368]
At the moment, `BasicCredentials` [use ISO 8859-1](https://github.com/http4s/http4s/blob/744a70252e7c7c1f0c8d6e0fab557f34ccd77c17/core/src/main/scala/org/http4s/Credentials.scala#L70) charset, which would break authentication if, say, a password contains a character not present in that charset.

[RFC 7617](https://tools.ietf.org/html/rfc7617) outlines support for UTF-8 in basic authentication scheme. The short of it is, that in an older RFC the charset was left unspecified by mistake, so handling of non-ASCII characters was non-standard. Now the server can choose to declare its support for UTF-8 via the `charset` auth-param, and the client can choose to use it. See [appendix B](https://tools.ietf.org/html/rfc7617#appendix-B) for ways to provide some backward compatibility.

**Comment by ashwinbhaskar** [comment]
I can pick this up. @rossabaker  If it's okay, can you assign this to me?

**Comment by rossabaker** [comment]
I read the spec a bit more carefully.  I'm not sure what our strategy is here yet.

@ashwinbhaskar's PR sends it unconditionally on the Challenge.  It seems like a good default, but should it be configurable?  (It's the kind of quirk that might be used to fingerprint an http4s server.)

And how are we going to implement Appendix B?  As the RFC suggests, we could fall back to a legacy encoding if parsing as UTF-8 fails.  But retrying in a legacy encoding if decode works and authentication fails has security ramifications.  It's a shame that the inbound header can't declare its encoding.

**Comment by ashwinbhaskar** [comment]
@rossabaker 
>And how are we going to implement Appendix B? As the RFC suggests, we could fall back to a legacy encoding if parsing as UTF-8 fails. But retrying in a legacy encoding if decode works and authentication fails has security ramifications. It's a shame that the inbound header can't declare its encoding.

I have tried to address this by decoding with UTF-8 first and only if the decoding fails then fall back to the original charset. - https://github.com/http4s/http4s/pull/3555/files#diff-66ce7925487855226b39f727e2dcfaee

**Comment by ashwinbhaskar** [comment]
@rossabaker what about [this](https://github.com/ashwinbhaskar/http4s/blob/a2030719b93c999fadf9b687dfe4698a4e0ea4f3/core/src/main/scala/org/http4s/Credentials.scala#L62) line? Would this be used by the client to create the token? If so, we should give the flexibility of providing the charest.

**Comment by rossabaker** [comment]
Yes, it makes sense to me to parameterize that.
