### ISSUE TITLE
Exceptions and Task failure not handled in Jetty backend

### ISSUE THREAD

**Issue by mossprescott** [http4s/http4s#337]
When a service either throws an exception or yields a task that fails (see `/throw` and `/fail` in the code below), the Blaze backend immediately produces a 500 response. The Jetty backend: 

1. Keeps the connection open for 30 seconds, ignoring `idleTimeout`.
2. Then returns a 200 OK with no body.

Obviously, one can fix this problem at the source but this behavior, especially the 30 second delay, makes it very hard to debug when something does go wrong.

```scala
import scala.concurrent.duration._
import scalaz.concurrent._
import org.http4s.dsl._
import org.http4s.server._

object JettyTest extends App {
  val service = HttpService {
    case GET -> Root / "throw" => sys.error("/throw")
    case GET -> Root / "fail" => Task.fail(new RuntimeException)
  }

  val js = org.http4s.server.jetty.JettyBuilder
    .withIdleTimeout(1.second)
    .bindHttp(8080, "0.0.0.0")
    .mountService(service)

  val bs = org.http4s.server.blaze.BlazeBuilder
    .withIdleTimeout(1.second)
    .bindHttp(8180, "0.0.0.0")
    .mountService(service)

  js.run
  bs.run
}
```

**Comment by bryce-anderson** [comment]
If you don't mind, what version of http4s are you using?

**Comment by mossprescott** [comment]
Sorry, this is http4s 0.8.2.

**Comment by rossabaker** [comment]
This also affects Tomcat.
