### ISSUE TITLE
Blaze backend doesn't route requests by path

### ISSUE THREAD

**Issue by mossprescott** [http4s/http4s#338]
If multiple services are mounted with different prefixes, the Jetty backend will map requests to just the correct service in what seems to be a reasonable way, with only matching request paths being handled by each service, and the prefix stripped from the path by the time it reaches the service.

With the Blaze backend, all requests seem to be offered to the last-mounted service first, and the path is altered just by having the number of characters in the prefix stripped off (even if they don't match).

Given the setup below:
1. `GET /a/foo` gets handled by the service mounted at `/x`, with the path `/foo`.
2. `GET /abc/foo` also gets handle by the wrong service, and the path is `/bc/foo`.

This behavior makes it impossible to mount multiple services that interpret the path in some way (rather than simply matching some particular paths.) I believe it can be worked around by making sure that each service imposes enough constraints on the path to never be defined for a request intended for another service. Another workaround, which I'm experimenting with, would be to write a `Prefix` middleware that matches and rewrites the paths correctly.

Tested with http4s 0.8.2.

```scala
object BlazeTest extends App {
  def service(id: String) = HttpService {
    case GET -> path => Ok(id + "; path: " + path)
  }

  val js = org.http4s.server.jetty.JettyBuilder
    .withIdleTimeout(1.second)
    .bindHttp(8080, "0.0.0.0")
    .mountService(service("abc"), "/abc")
    .mountService(service("x"), "/x")

  val bs = org.http4s.server.blaze.BlazeBuilder
    .withIdleTimeout(1.second)
    .bindHttp(8180, "0.0.0.0")
    .mountService(service("abc"), "/abc")
    .mountService(service("x"), "/x")

  js.run
  bs.run
}
```

**Comment by mossprescott** [comment]
Here's my workaround, which makes the Blaze backend usable:

```scala
  object Prefix {
    def apply(prefix: String)(service: HttpService): HttpService = {
      import monocle.macros.GenLens
      import scalaz.std.option._

      val _uri_path = GenLens[Request](_.uri) composeLens GenLens[Uri](_.path)

      val stripChars = prefix match {
        case "/"                    => 0
        case x if x.startsWith("/") => x.length
        case x                      => x.length + 1
      }

      def rewrite(path: String): Option[String] =
        if (path.startsWith(prefix)) Some(path.substring(stripChars))
        else None

      Service.lift { req: Request =>
        _uri_path.modifyF(rewrite)(req) match {
          case Some(req1) => service(req1)
          case None       => Task.now(None)
        }
      }
    }
  }
```

**Comment by bryce-anderson** [comment]
As a quick tidbit, your `Prefix` middleware looks an awful lot like the [`UriTranslation`](https://github.com/http4s/http4s/blob/master/server/src/main/scala/org/http4s/server/middleware/URITranslation.scala) middleware used by blaze to simulate the path prefix behavior. 

You're right, the prefix isn't checked which is ridiculous. If memory serves me, at one point `UriTranslation` was much the same form as your `Prefix` middleware, but the behavior was slightly different than that of the servlet backends. Therefor, it was changed and we now have our bug.

**Comment by bryce-anderson** [comment]
I've been mistaken: `UriTranlation` has never been suitable.

**Comment by mossprescott** [comment]
Yes, I found UriTranslation when I tried to find the problem in the BlazeBuilder, and cribbed a little bit of code. I'm not really sure my path rewriting is quite correct, either, but it works for the cases we need right now. Probably the right way to fix this is just to make UriTranslation do something a little more useful.

**Comment by bryce-anderson** [comment]
@mossprescott, I have a branch up to fix this issue. I took a different strategy than you have, so some testing is in order. I will likely be making another commit with a unit test before the PR lands.

**Comment by mossprescott** [comment]
I like this approach and I confirmed that it does handle my tests, allowing me to use blaze-server without my workaround. It's also a plus that it doesn't require the services to be mounted in the correct order.

I'm not entirely sure how it will compare on the remaining use case that we have (not covered by our automated tests), which is redirecting any requests that fall through, via a mount at `/`, but I think it should be ok for that as well.

However, I noticed in the process of testing that it breaks my workaround. Essentially, I was mounting multiple services at `/` and then depending on the backend to try them all until one handled the request. This version doesn't do that, it selects the last-added service with a matching prefix, and then only invokes that one service, even if it doesn't handle the request. That's not a problem for me, but it's something other people *could* be doing.

**Comment by rossabaker** [comment]
I think it's going to break your `/` fall through for requests whose prefix matches another mount.  Presumably, this service aggregator could invoke the next-best service on a `None` result.

That, however, is in jeopardy with #332.  We incur much complexity handling the `Option` without much in the way of use cases that can't be handled by prefix mapping.  You could write a middleware to act on a 404 result from the aggregated service, but any distinction between `None` and `Some(Response(NotFound))` is lost if #332 happens.

**Comment by bryce-anderson** [comment]
@mossprescott, we've merged what we think is a fix for your problem into the release-0.8.4 branch but it might be worth your time to check it. It should honor your fall through usage.

**Comment by mossprescott** [comment]
I'll retest with this version ASAP, but I think we'll be good to go. We don't need fall-through when the prefix matches.

**Comment by mossprescott** [comment]
Looks good on all our tests. Thanks!
