### ISSUE TITLE
Get mdoc working on 2.13

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#3412]
We get deprecation warnings running mdoc on Scala 2.13.

The easy approach is to turn them off, or to tolerate fatal warnings.  The better approach is to figure out why they're happening and make them stop.

**Comment by valencik** [comment]
Mostly so I don't forget, I looked into this and realized we were running into this issue: https://github.com/scalameta/mdoc/issues/210

I attempted to minimize the problem to help debug in mdoc but haven't come up with anything one would call minimal yet.

It might be worth [manually specifying `toString` usage in mdoc](https://scalameta.org/mdoc/docs/modifiers.html#to-string) for now. I'll give that a shot and report back.

(in the interest of having lots of hyperlinks to related discussions: https://gitter.im/scalameta/mdoc?at=6018368555359c58bf154511)

**Comment by armanbilge** [comment]
This was done at some point.
