### ISSUE TITLE
util.decode doesn't terminate on malformed input

### ISSUE THREAD

**Issue by susuro** [http4s/http4s#3453]
When the `decode` function transforms stream encoded in another charset than expected, it may never terminate due to `CharsetDecoder.decode` errors being ignored.
Example:
```
val source = Stream.emits(Seq(0xb3.toByte)) // 'ł' in windows-1250 encoding
decode(Charset.`UTF-8`)(source).toList // incorrect encoding provided
```
`CharsetDecoder.decode` returns an error in such a case without consuming data from `byteBuffer` thus causing an infinite loop.

This part of `decode`:
```
decoder.decode(byteBuffer, charBuffer, false)
val nextStream = stream.consChunk(Chunk.byteBuffer(byteBuffer.slice()))
Pull.output1(charBuffer.flip().toString).as(Some(nextStream))
```
should be probably rewritten to something like this:
```
val coderResult = decoder.decode(byteBuffer, charBuffer, false)
if(coderResult.isError)
  Pull.raiseError[F](new CharacterCodingException)
else {
  val nextStream = stream.consChunk(Chunk.byteBuffer(byteBuffer.slice()))
  Pull.output1(charBuffer.flip().toString).as(Some(nextStream))
}
```
This will however require to have an implicit `ApplicativeError` for `F`.

**Comment by rossabaker** [comment]
This is a function that I have been meaning to clean up and contribute back to fs2, since there is no HTTP in it.  But your solution looks correct to the matter at hand.

**Comment by rossabaker** [comment]
Unfortunately, we don't have a `RaiseThrowable` constraint, so fixing this in a binary compatible way is going to be a pain.

**Comment by susuro** [comment]
Hi Ross. I see that you’ve provided a quick solution first but finally decided to change function signature and use `raiseError`. Thank you. 

I spotted one more small issue with current solution, probably not significant enough to open a ticket but maybe you would like to consider it. It's related to the logic of BOM removal:
- BOM is removed at the beginning of **every** new chunk. It should be however removed only at the very beginning of the stream. `U+FEFF` may be used as zero width no-break space inside of encoded content.
- Removal of `EF BB BF` before decoding works only for UTF-8. It would be more universal to remove `U+FEFF` after decoding and thus cover UTF-16 and UTF-32 encodings.

I’m closing the ticket, the above is not related to the original issue.

**Comment by rossabaker** [comment]
Yes, I wanted to follow up on the BOM.  It looked suspicious to me as well, but I hadn't studied the relevant specs on it.

I wanted to use the `RaiseThrowable` from the beginning, but wasn't sure how to do it without breaking binary compatibility.  I think the deprecation will be a good solution.  I'd still like to get this function moved into fs2 eventually.
