### ISSUE TITLE
Support parsing the 'Forwarded' header: RFC 7239

### ISSUE THREAD

**Issue by kalexmills** [http4s/http4s#3471]
There's a specification [1,2] for a header which does not have native parsing support in http4s. The `Forwarded` header can be included by proxies as a standards-track alternative to `X-Forwarded-For`, `X-Forwarded-Proto`, and `X-Forwarded-Host`. http4s should consider providing support for it.

[1] [Forwarded - HTTP | MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Forwarded)
[2] [RFC 7239 - Forwarded HTTP Extension](https://tools.ietf.org/html/rfc7239])

**Comment by rossabaker** [comment]
Agreed, and we should be able to do so in series/0.21.

**Comment by satorg** [comment]
Hey there. Is someone working on this issue? I looked through it briefly and I think I could take on it, if no one else minds.

**Comment by rossabaker** [comment]
Thanks, @satorg!

**Comment by m-sp** [comment]
thanks again for the contribution, seems the issue didn't get autoclosed
