### ISSUE TITLE
pattern match for Path does not work

### ISSUE THREAD

**Issue by ShengC** [http4s/http4s#352]
The unapply methods in Path object are useless,

    val path: Path = ???
  
    val Path(xyz) = path // does not work
    val Path(x, y, z) = path // does not work, nor compile !

 The right way of doing this if http4s does want to support them,

    object PathList { def unapply(path: Path): Option[List[String]] = ???}

    object PathItems { def unapplySeq(path: Path): Option[List[String]] = ??? }

    // both compiles
    val PathList(xyz) = path 
    val PathItems(x, y, z) = path

**Comment by rossabaker** [comment]
These don't typically get used in the DSL (this problem has been there since 2013!), but it might as well work. :)

`Path.unapply` works on `Request`, not `Path`.

The presence of `Path.unapply` prevents `Path.unapplySeq` from working.  The `unapplySeq` seems more correct for this Seq-like data structure.  I will remove `Path.unapply`.

**Comment by ShengC** [comment]
yes, they should be removed. Also the documentation for this project is kinda... and no offense... lame. I see it heavily borrows the idea from Spray, but one thing that definitely making Spray stand out is its documentation. Another missing piece is the change note per each release. It is at least not easy to persuade people upgrading version of their dependencies if they cannot clearly see a picture why they should do so. It does not need to be exhaustive, but I'd at least expect list of commits since the last release.... would be better to simply point out new feature(s) introduced, and bug(s) fixed, and people can just dig into the diff to find out the details themselves, and make a decision accordingly.

**Comment by rossabaker** [comment]
There is a CHANGELOG.md in the root of the repository that is updated with every release.  It could stand some formalization, which will come as the project continues to mature.

I am actively working on documentation with sbt-tut (#351).  There is commercially backed open source, labor-of-love open source, and a whole continuum in between.  Right now, we're firmly on the labor-of-love phase, and it takes a while to get complete features, complete tests, and complete docs.  We'll get there, and we gladly accept contributions to speed the process along!
