### ISSUE TITLE
GitHub releases irritation

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#3532]
I don't like GitHub releases.

1. Their metadata doesn't live in the repo. It's another form of lockin.
2. It's a pain to automate with metadata from the repo.
3. If we go back and fill them out later, it takes today's date, not the tag's date.

I've cheerfully ignored them since 0.18.4.  And now, with the GitHub redesign, prominently on the front page:

"Latest release 0.18.4, on Mar 23, 2018"

:weary: 

Anybody have a neat way of automating these?  I guess maybe we only need to start doing recent ones instead of going back?

**Comment by ChristopherDavenport** [comment]
The meta data stuff we can populate ourselves from copying when we release via a github tag.

Like we leave all the stuff but create the tag ourselves via the api. All the information for that release lives in the tag.

**Comment by rossabaker** [comment]
I don't see the automation in that repo?

I would like a git-managed source of truth for release descriptions that could be assembled into a changelog _and_ feed GitHub releases.  I'm particularly irritated that we can't change the date of GitHub releases to match the tag that they describe.  I think if we automated creating one when we published, we could update notes at our leisure, but we can't fill in the old ones without making an awful mess of the sort.

**Comment by ChristopherDavenport** [comment]
I just do releases manually on github with my current system. The fact that its a web interface and then it goes and takes care of it all has been awesome for me personally. I don't think what I've done is what your looking for though. So I will leave it in case you find a cleaner approach.

I also never modify releases once created. Because they are releases. 😉

**Comment by rossabaker** [comment]
I just "released" v0.21.4 on my fork, and it shows as released now.

From the GitHub docs:

> Releases are based on Git tags, which mark a specific point in your repository's history. A tag date may be different than a release date since they can be created at different times. 

The thing is, releases as distinct from tags are totally useless for us.  We're not uploading binaries to GitHub, as is common in other languages.

**Comment by rossabaker** [comment]
> I just do releases manually on github with my current system. 

Oh, you mean instead of creating tags locally and pushing them, you're tagging from the GitHub interface?  I've never done it that way, but I guess that would keep them in lockstep.

**Comment by rossabaker** [comment]
And I don't make a habit of changing things, but we've gone back and corrected typos and lies in the release notes.  I don't necessarily view the descriptions as immutable. The code, certainly.

**Comment by ChristopherDavenport** [comment]
Yes. That's what I've been doing. It makes it so I can do update based releases much easier and from much more places than if I had a full git repo of all my libraries on hand. Probably less relevant for a library of this size though.

**Comment by rossabaker** [comment]
I just tagged v1.0.0-M2 through the interface and it tried to infer a bunch of things from the last commit, and because it's a prerelease, still didn't update that stale indicator on the right.  But at least it set a sensible timestamp.

My big itch here is that it looks like we haven't done a release since 2018.

**Comment by ChristopherDavenport** [comment]
Well we can just update the "release" from the interface for 0.21.5 and that should get fixed.

**Comment by rossabaker** [comment]
I guess tagging from the GitHub UI is sufficient for now.

It still makes me grumpy.
