### ISSUE TITLE
StaticFile.fromURL() does not handle exceptions

### ISSUE THREAD

**Issue by dubinsky** [http4s/http4s#3565]
When there is no object at the `url` specified, `url.openStream` causes `StaticFile.fromUrl()` effect to throw `FileNotFoundException` instead of returning (the equivalent of) `None`: see
https://github.com/http4s/http4s/blob/master/core/src/main/scala/org/http4s/StaticFile.scala#L93

Is there anything I can do at the place of the call to work around this while waiting for the fix?
Thanks!

**Comment by satorg** [comment]
As I can see from the code, the exception should be thrown not by the `fromUrl` result effect itself, but rather by the response body stream – i.e. when you try to run the response body. Is it correct?

**Comment by dubinsky** [comment]
Indeed; sorry for my misuse of the terminology - I am new to this :)

One of the routes of the `HttpApp` that I configure in `BlazeServerBuilder.withHttpApp()` does 
`StaticFile.fromURL(url, blocker, Some(request)).getOrElseF(NotFound(s"Not found: $url"))`, and when the requested object does not exist, `FileNotFoundException` gets thrown - instead of `NotFound` being returned.

So yes, exception *is* thrown by the response body stream, but I think it *should not* be thrown at all...
Or did I misunderstand the contract of the `StaticFile.fromURL()`?
In which case, how should I turn this exception into `NotFound` in my code?

Thanks!

**Comment by satorg** [comment]
The way how `StaticFile.fromURL` is implemented is that it only opens input stream to the URL resource when the response body stream gets executed. And despite its `OptionT` return value it never returns 'None' actually (except if the resource is a directory, which is quite a border case).

It would be possible to change `StaticFile.fromURL` implementation to first check if a resource exists and return `None` if it doesn't but it could break backward compatibility.

@rossabaker @ashwinbhaskar wdyt?

**Comment by ashwinbhaskar** [comment]
@satorg I think just adding one more check to see if the file exists should suffice? 
```
if (file.isDirectory() || !file.exists)
        None
else
 ...
```

**Comment by dubinsky** [comment]
@satorg  It's hard for me to imagine code that actually *relies* on exceptions being thrown when running a functional effect :)
I am playing with a local copy of the `fromURL()`, and can't figure out how to adjust the rest of the code accordingly, since `OptionT.apply(F.delay{...})` wrapped around most of it expects `Option`, not `F[Option]`...

@ashwinbhaskar local `file.exists` has no connection with the existence of the object specified by the remote URL;
using it will make *all* URLs treated as non-existent :(

**Comment by satorg** [comment]
@ashwinbhaskar unfortunately, it isn't going to work with remote resources:
```
new URL("https://raw.githubusercontent.com/http4s/http4s/master/core/src/main/scala/org/http4s/StaticFile.scala").getFile
```
returns `/http4s/http4s/master/core/src/main/scala/org/http4s/StaticFile.scala`

**Comment by ashwinbhaskar** [comment]
@dubinsky @satorg got it

**Comment by satorg** [comment]
@dubinsky, meanwhile, I came up with the following snippet that you could try to use at the call site of `fromURL`:
```scala
    StaticFile.fromURL[F](myURL, blocker)
        .semiflatMap { res =>
          res.body.chunks // chunks for better efficiency
            .pull // start pulling to replay the original body stream
            .fold(Stream.empty.covaryAll[F, Byte]) { _ ++ Stream.chunk(_) }
            .flatMap { restream =>
              Pull.output1(res.withBodyStream(restream))
            }
            .recoverWith { case ex: FileNotFoundException =>
              Pull.output1(Response[F](status = Status.NotFound).withEntity("not found: " + ex.getMessage))
            }
            .stream // Stream[F, Response[F]]
            .compile
            .lastOrError // there should be a single `Response` entity after all
        }
```
This code attempts to start executing the body stream and if it fails with `FileNotFoundException` then `Response(status = NotFound)` gets returned.

I am totally not sure that it is either the simplest or most efficient solution though. Perhaps there's a better way to achieve the same behavior. Maybe @SystemFw could suggest something better.

**Comment by dubinsky** [comment]
@satorg Wow! Thanks!
I think it'd be cleaner if `FileNotFoundException` was handled inside `fromURL`,
but so far I wasn't able to apply your suggestion about `redeem` to the code inside `OptionT.apply(F.delay(...))`.

**Comment by rossabaker** [comment]
Handling that exception in `fromFile` makes sense to me, since it does return a `Response`, and there's a pretty obvious status mapping for it.

**Comment by satorg** [comment]
@rossabaker do you mean `fromURL`?

**Comment by rossabaker** [comment]
> @rossabaker do you mean fromURL?

Oops. Yes.

**Comment by ashwinbhaskar** [comment]
@satorg will you be picking it up? If not I can pick this up

**Comment by satorg** [comment]
@ashwinbhaskar yes, sure. Right now I have another task to work on, so feel free to pick this one up.

**Comment by ashwinbhaskar** [comment]
@dubinsky sorry, been working on another issue. Will try this out over this weekend.

**Comment by dubinsky** [comment]
@ashwinbhaskar thanks!!!

**Comment by ashwinbhaskar** [comment]
@dubinsky   I have picked up this issue. Like @satorg pointed out this will not be backward compatible because we will have to change the type of `body` in `Response`  to `Option [Stream]` from just `Stream`. CMIIW @satorg
