### ISSUE TITLE
RFC: Cookie Backdoor for Invalid Cookies

### ISSUE THREAD

**Issue by ChristopherDavenport** [http4s/http4s#3569]
> " or ,

Are characters that often end up in cookies despite the fact they are illegal. We cannot parse the cookie correctly so. However that means people have to brew their own parsers for their illegal cookies.

Perhaps we can make this easier in some regard. Discuss.

**Comment by rossabaker** [comment]
Right now, header parsing is a global registry that's awfully hard to customize.  I've thought about making it a parameter of the backends, that can be customized, but we're currently able to parse headers constructed straight from Strings without any backend reference.  I think the lazy header parsing model is an obstacle to configuration.

A simpler answer might be to relax these given real world use.

**Comment by jweidler** [comment]
Hi there, relaxing the parser sounds great! we just ran into an issue where invalid cookie names and values that are set by some wonderful third party scripts at the other end of our organisation would make customers on our end run into no-cookies-provided based app states (session timeout, not logged in etc) as the parser appears to be failing silently, returning no cookies at all if there's a bad one 🙃

Not sure how relevant, but it looks like in akka-http invalid cookies are simply dropped and only valid ones returned.

**Comment by rossabaker** [comment]
So all the cookies should always be available as raw headers, but that's not exactly convenient.

The akka-http compromise doesn't sound unreasonable.

**Comment by prophe05** [comment]
Already got the issue with third party cookie

**Comment by rossabaker** [comment]
Starting in 0.22, headers are a typeclass, and it's possible to define both a strict cookie and a lax cookie, and relax it however you need.
