### ISSUE TITLE
Model `Forwarded` header

### ISSUE THREAD

**Issue by hamnis** [http4s/http4s#3608]
The alternative and de-facto standard versions of this header are the `X-Forwarded-For`, `X-Forwarded-Host` and `X-Forwarded-Proto` headers.

https://tools.ietf.org/html/rfc7239#section-4

**Comment by satorg** [comment]
@hamnis, I'm already working on this issue: #3471

**Comment by hamnis** [comment]
@satorg great. didnt notice that. Closing this.
