### ISSUE TITLE
Suppress compile time warnings in the scalafix module

### ISSUE THREAD

**Issue by satorg** [http4s/http4s#3613]
Warnings like these below are important in general, but make no sense in the `scalafix` module (or at least in the given file), since these unused parameters were introduced intentionally to let the output match the input after applying the scalafix rule to the latter.
```
[warn] /.../http4s/scalafix/input/src/main/scala/fix/ClientFetchTests.scala:15:78: parameter value G in method doFetchR1 is never used
[warn]     final def doFetchR1[A](req: Request[G], f: Response[G] => G[A])(implicit G: Sync[G]): G[A] =
[warn]                                                                              ^
[warn] /.../http4s/scalafix/input/src/main/scala/fix/ClientFetchTests.scala:18:82: parameter value G in method doFetchFR1 is never used
[warn]     final def doFetchFR1[A](req: G[Request[G]], f: Response[G] => G[A])(implicit G: Sync[G]): G[A] =
[warn]                                                                                  ^
[warn] /.../http4s/scalafix/input/src/main/scala/fix/ClientFetchTests.scala:21:78: parameter value G in method doFetchR2 is never used
[warn]     final def doFetchR2[B](req: Request[G], f: Response[G] => G[B])(implicit G: Sync[G]): G[B] =
```

**Comment by rossabaker** [comment]
Agreed.  Do we want to start opting out of warnings individually to make sure we're preserving useful ones, or are none of them useful?

**Comment by satorg** [comment]
I haven't investigated it yet... But I guess it should be pretty safe to disable most of lint warnings for modules `scalafixInput` and `scalafixOutput` – apparently these two are not intended to provide some high quality code but rather model various user cases.

**Comment by rossabaker** [comment]
I definitely agree with the reasoning on input.  I'm less sure on output: I think it's a noble goal to produce output that lints cleanly.  But maybe that's not possible in practice.  I think we should disable on input, and evaluate where we stand on output.

**Comment by satorg** [comment]
Agree – we can start by addressing input only. Especially since there're no additional warnings produced by output right now.

**Comment by m-sp** [comment]
done in https://github.com/http4s/http4s/pull/3741
