### ISSUE TITLE
Jetty+Http4s: timeout response 500

### ISSUE THREAD

**Issue by vetalbabenko** [http4s/http4s#3626]
**Intro**
Found a interesting behaviour when jetty server used with http4s.
When request timed out, 500 Response code sent instead of 503.

**Library versions used**
- "org.http4s" %% "http4s-core" % "0.21.1",
- "org.http4s" %% "http4s-jetty" % "0.21.1"
- "dev.zio" %% "zio" % "1.0.0-RC18-2",
- "dev.zio" %% "zio-interop-cats" % "2.0.0.0-RC12",
- "org.http4s" %% "http4s-dsl"  % "0.21.1"

**Steps to reproduce**
Run following code and call endpoint: "http://0.0.0.0:10800"
```
import org.http4s.HttpRoutes
import zio.{App, Task, ZIO}
import org.http4s.dsl.Http4sDsl
import org.http4s.server.jetty.JettyBuilder
import zio.duration.Duration
import zio._

import scala.concurrent.duration.{Duration => SDuration}
import zio.interop.catz._

object Main extends App {

  val dsl = new Http4sDsl[Task] {}
  import dsl._

  val httpRoutes =  HttpRoutes.of[Task] {
    case GET -> Root / "ping" =>
      ZIO.sleep(Duration.fromScala(SDuration.apply("40 s"))).provide(Runtime.default.environment) *>
      Ok("pong")
  }

  override def run(args: List[String]): ZIO[zio.ZEnv, Nothing, Int] = {
    implicit val runtime: Runtime[Any] = this

    JettyBuilder[Task]
      .bindHttp(port = 10800, host = "0.0.0.0")
      .mountService(httpRoutes, "/")
      .serve
      .compile
      .drain
      .as(0)
      .orDie
  }
}
```
**Actual result:** 500 Response code sent to client
**Expected result:** 503 Response code sent to client

**Investigation notes**
After some self-investigation, was found that two handlers used to monitore request on timeout, first is http4s:
**AsyncHttp4sServlet:handleRequest** which is correctly triggered and set appropriate 503 code response
![image](https://user-images.githubusercontent.com/12881797/89538818-b3b97a00-d803-11ea-8351-5f67c36c33df.png)
The second one is located in **HttpChannelState**  which set 500 response code on request timeout 
![image](https://user-images.githubusercontent.com/12881797/89539101-06933180-d804-11ea-9cca-39bce6908717.png)
Second handler triggered firstly and when response with 500 code already sent to client, then first handler tried to send response code 503 as well and next error occurred:
![image](https://user-images.githubusercontent.com/12881797/89544791-35f96c80-d80b-11ea-9dad-68bb9eb2ee5d.png)

**Interesting that this issue doesn't exist if we use Blaze instead of Jetty.**

**Comment by rossabaker** [comment]
Thanks, this is a nicely researched report.

Blaze and Jetty have very different mechanisms for timeout handling.  The happy paths between backends are largely the same, but there are implicit behaviors like this that cause subtle differences.

I wonder whether we need to render the timeout response synchronously in the `onTimeout` callback in order to force our custom 503 response before the server's own 500.

**Comment by vetalbabenko** [comment]
Hello @rossabaker. Any updates on this issue ? Is there would be some fix regarding this, or maybe you can suggest how we can solve it or create some temporary workaround.
Thanks in advance!

**Comment by rossabaker** [comment]
Apologies for losing track of this.

I ported it to IO, and it works for me on the head of the 0.21 branch.  You might want to try again with 0.21.22.

```scala
import cats.effect._
import org.http4s.HttpRoutes
import org.http4s.dsl.Http4sDsl
import org.http4s.server.jetty.JettyBuilder
import scala.concurrent.duration._

object Main extends IOApp {

  val dsl = new Http4sDsl[IO] {}
  import dsl._

  val httpRoutes =  HttpRoutes.of[IO] {
    case GET -> Root / "ping" =>
      IO.sleep(40.seconds) *> Ok("pong")
  }

  override def run(args: List[String]): IO[ExitCode] = {
    JettyBuilder[IO]
      .bindHttp(port = 10800, host = "0.0.0.0")
      .mountService(httpRoutes, "/")
      .serve
      .compile
      .drain
      .as(ExitCode.Success)
  }
}
```

```
$ curl -i http://localhost:10800/ping
HTTP/1.1 503 Service Unavailable
Date: Sun, 11 Apr 2021 20:03:47 GMT
Content-Type: text/plain;charset=utf-8
Content-Length: 18
Server: Jetty(9.4.39.v20210325)

Response timed out
```

**Comment by robot-govorun** [comment]
Hi @rossabaker !
Looks like the problem is still there :). It appears that given issue is always reproduced when use ZIO instead of Cats IO. 

```scala
import cats.effect.{ConcurrentEffect, Sync, Timer}
import cats.syntax.functor._
import org.http4s.dsl.io._
import org.http4s.server.jetty.JettyBuilder
import org.http4s.{HttpRoutes, Response}
import zio._
import zio.interop.catz._

import scala.concurrent.duration._

object ZioJettyRequestTimeout extends App {

  implicit val zioRuntime: zio.Runtime[ZEnv] = this
  type mZIO[A] = RIO[ZEnv, A]

  private def httpRoutes[F[_]: Sync : Timer](): HttpRoutes[F] = {
    HttpRoutes.of[F] { case _ =>
      Timer[F].sleep(10.seconds).as(Response[F](NoContent))
    }
  }

  private def jettyProgram[F[_]: ConcurrentEffect: Timer]: F[Unit] = {

    JettyBuilder[F]
      .withAsyncTimeout(5.seconds)
      .bindHttp(8080, "0.0.0.0")
      .mountService(httpRoutes(), "/")
      .serve
      .compile
      .drain
      .void
  }

  override def run(args: List[String]): URIO[zio.ZEnv, zio.ExitCode] = {
    jettyProgram[mZIO]
      .as(zio.ExitCode.success)
      .orDie
  }
}
```

```bash
curl -i 'http://localhost:8080'
HTTP/1.1 500 Server Error
Cache-Control: must-revalidate,no-cache,no-store
Content-Type: text/html;charset=iso-8859-1
Content-Length: 479
Server: Jetty(9.4.39.v20210325)

<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 500 AsyncContext timeout</title>
</head>
<body><h2>HTTP ERROR 500 AsyncContext timeout</h2>
<table>
<tr><th>URI:</th><td>/</td></tr>
<tr><th>STATUS:</th><td>500</td></tr>
<tr><th>MESSAGE:</th><td>AsyncContext timeout</td></tr>
<tr><th>SERVLET:</th><td>servlet-0</td></tr>
</table>
<hr><a href="https://eclipse.org/jetty">Powered by Jetty:// 9.4.39.v20210325</a><hr/>

</body>
</html>
```
