### ISSUE TITLE
Middleware Documentation

### ISSUE THREAD

**Issue by ChristopherDavenport** [http4s/http4s#3652]
Discoverabilith of middleware is not as good as it could be. We can create a middlewares page on the site documenting what we have available as well as a community section at the bottom where others can list their middlewares since a lot of our features come from middleware.

**Comment by fredshonorio** [comment]
I could pick this up, I was thinking promoting the `Included Middleware` section to its own page and complete the list with description and usage examples. Is that a good idea?

**Comment by armanbilge** [comment]
Sounds good!

**Comment by fredshonorio** [comment]
I've added a draft PR https://github.com/http4s/http4s/pull/6992

**Comment by fredshonorio** [comment]
I'm planning on adding a page for client middleware

**Comment by fredshonorio** [comment]
Added https://github.com/http4s/http4s/pull/7058
