### ISSUE TITLE
Bug in CSRF error handler for `onFailure`

### ISSUE THREAD

**Issue by faustas** [http4s/http4s#3665]
### Intention

I wanted to handle an error during CSRF validation with the `onFailure` response of the CSRF class.
The problem with some of the browsers (e.g. Firefox, Chrome) is that they do not remove session cookies. They provide settings which use the session cookies even when the browser was restarted.

The idea is to catch the CSRF validation error and provide an own `onFailure` response that sends the user to a page where a new CSRF cookie is set. (For `GET` requests.)

### Current situation

Using http4s Version 0.21

I tried the following approach by adding an own `onFailure` response to the specification of the CSRF object.

```
csrfProtect = csrfBuilder
  .withClock(csrfClock)
  .withCookieName(CSRF_COOKIE)
  .withCSRFCheck(CSRF.checkCSRFinHeaderAndForm[IO, IO](CSRF_COOKIE, FunctionK.id))
  .withOnFailure(
    Response(status = Status.SeeOther, headers = Headers(List(Header("Location", "/"))))
      .removeCookie(CSRF_COOKIE)
  )
  .build
```

### Expected result

If a user with an invalid CSRF cookie opens the site, the CSRF check will fail. The `onFailure` response should redirect the user to the frontpage and refresh the CSRF cookie.

### Actual result

The `onFailure` response is not used.

I checked the code and assume that the hard-coded `Response[G](Status.Forbidden)` in some of the check methods could be the reason. These could be replaced by the `onFailure` reponse which by default is also a `Response[G](Status.Forbidden)`.

One of these checks is:
```
  def checkCSRFToken(r: Request[G], respAction: F[Response[G]], rawToken: String)(implicit
      F: Sync[F]): F[Response[G]] =
    if (!headerCheck(r))
      F.pure(onFailure)
    else
      (for {
        c1 <- CSRF.cookieFromHeadersF[F, G](r, cookieSettings.cookieName)
        raw1 <- F.fromEither(extractRaw(c1.content))
        raw2 <- F.fromEither(extractRaw(rawToken))
        response <-
          if (CSRF.isEqual(raw1, raw2)) respAction
          else F.raiseError[Response[G]](CSRFCheckFailed)
        newToken <- signToken[F](raw1) //Generate a new token to guard against BREACH.
      } yield response.addCookie(createResponseCookie(newToken)))
        .recover {
          case CSRFCheckFailed => Response[G](Status.Forbidden)
        }
```
The recover uses the hard-coded `Forbidden`. Also in the `validate` method the `recover` does the same.

**Comment by faustas** [comment]
Any progress with this bug? Is the PR fine and could be merged into the `series/0.21`?

**Comment by rossabaker** [comment]
I'm sorry we didn't get to this sooner.  This is an exemplary issue description, and the fix looks good.  I'm aiming to do an 0.21.8 release this week, which will include the PR.

**Comment by hamnis** [comment]
This seems to be fixed, reopen if not
