### ISSUE TITLE
org.http4s.Method.fromString may succeed on invalid inputs

### ISSUE THREAD

**Issue by satorg** [http4s/http4s#3680]
The initial conversation is [here](https://gitter.im/http4s/http4s-dev?at=5f55d832ec534f584fea2572)

Consider the example:
```
scala> Method.fromString("FOO:BAR")
val res: org.http4s.ParseResult[org.http4s.Method] = Right(FOO)
```
In other words, although the entire input string `"FOO:BAR"` is not a valid token, but its initial part `"FOO"` gets captured since it is still a token.
Therefore, `fromString` captures everything up to the first non-token symbol but not necessarily to the end of the entire input string.

Expected behavior: `Method.fromString("FOO:BAR")` should fail to create `Method`, i.e. return `Left(...)`.

**Comment by rossabaker** [comment]
Fixed by #3716
