### ISSUE TITLE
Do we need `ServerBuilder.mount` or would `.start(service): Task[Server` be better?

### ISSUE THREAD

**Issue by bryce-anderson** [http4s/http4s#369]
Right now you can mount different prefixes with 

``` scala
builder.mount(service, "/foo")
```

to add a prefix to a service. In master (as of right now) we use a type called `Router` for this. 

I'm thinking its better to:
- Expose `Router` to the user
- remove `ServerBuilder.mount`
- Change `Builder.start: Task[Server]` to `Builder.start(service: HttpService): Task[Server]`.

**Upsides:**
- Backends become uniform in how they deal with multiple services: they don't!
- This routing information is now a part of the `Service` and not the server

**Downsides:**
- Requires users to now know about `Router` and our documentation sucks.

I think we can settle this for 0.9. If not, we can punt.

**Comment by bryce-anderson** [comment]
cc: @dcsobral

**Comment by dcsobral** [comment]
That `Router` thing is post-0.8.4, right? I can't find such a class here, and `mountService` isn't using any such thing on 0.8.4, so I can't comment on that.

Honestly, I think that, even on 0.8.4, `mountService` is redundant. You can use `orElse` to chain services. You can use `URITranslation` to add prefix.

**Comment by bryce-anderson** [comment]
@dcsobral: Yes, it is a post 0.8.4 thing that can be found [here](https://github.com/http4s/http4s/blob/master/server/src/main/scala/org/http4s/server/Router.scala).

**Comment by rossabaker** [comment]
`mountServlet` is still helpful for interop scenarios in that ecosystem, but is an extension for those server builders.  I could get on board with this for the common interface.  The status quo was always a bit forced in the blaze world.

**Comment by rossabaker** [comment]
One hangup: how does this play with the eventual idea of setting up multiple connectors (#197)?  For example, admin service on one port, public service on another?

**Comment by rossabaker** [comment]
The new precedent on `BlazeServerBuilder` is now `withHttpApp`, and we'll have a `.resource: Resource[F, Server[F]]` and `.stream Stream[F, Server[F]]` to construct it.

The multiple connector idea has been rejected in favor of composing two blaze resources.

Servlets will still allow multiple mounts for legacy integration, and because it's a native concept anyway.

`ServerBuilder` is on the way out.

I think we're done here?
