### ISSUE TITLE
Update jawn dependency to 0.8.3

### ISSUE THREAD

**Issue by mossprescott** [http4s/http4s#371]
Prior to 0.8.3, jawn had an unintentional runtime dependency on jmh, which is under an incompatible license. See non/jawn#33 (comment).

See https://github.com/rossabaker/jawn-streamz/pull/3, but there are also dependencies on `org.spire-math:argonaut-support` and `:json4s-support`, neither of which seems to have had an 0.8.3 release yet.

**Comment by rossabaker** [comment]
Giving this a bug label.  It's not our bug, but we can do a patch release to get people license compliant.

**Comment by rossabaker** [comment]
Figured it out.  The jawn 0.8.3 artifacts changed names in 0.8.1.  http4s-0.8.5 coming shortly.
