### ISSUE TITLE
Warning for future deprecation in Scala 2.13.3

### ISSUE THREAD

**Issue by alejandrohdezma** [http4s/http4s#3719]
## What's the problem?

When using [`+?` operator](https://github.com/http4s/http4s/blob/e45ca2c8703c43d7c00a55d47a35d3bd3b79dfdd/core/src/main/scala/org/http4s/QueryOps.scala#L39) to add a query param to an `Uri` value in Scala 2.13.3 the following warning is raised:

```scala
[warn] ${BASE}/Test.scala:14:37: multiarg infix syntax looks like a tuple and will be deprecated
[warn]   val uri = uri"localhost" / "test" +? ("key", "value")
[warn]                                     ^
```

The warning only dissapears if no-infix syntax is used:

```scala
(uri"localhost" / "test").+?("key", "value")
```

...which completely breaks the goal of those operators.

## Possible solution

Changing the [`+?` operator](https://github.com/http4s/http4s/blob/e45ca2c8703c43d7c00a55d47a35d3bd3b79dfdd/core/src/main/scala/org/http4s/QueryOps.scala#L39) to directly receive a tuple. It would break back-compatibility but it shouldn't break many codebases since there is no difference between the two params infix syntax and the one param tuple one.

```scala
def +?[K: QueryParamKeyLike, T: QueryParamEncoder](param: (K, T)): Self =
  +?(param._1, param._2 :: Nil)
```

> For anyone that bumps into this error and is using `-Xfatal-warnings` (or just wants to get rid of the warning) you can suppress it by adding the following to your `build.sbt`:
> 
> ```sbt
> scalacOptions += "-Wconf:cat=lint-multiarg-infix:silent"
> ```

## How to test?

Just create a simple project with these two files:

```scala
//build.sbt

scalaVersion := "2.13.3"
libraryDependencies += "org.http4s" %% "http4s-core" % "0.21.7"
```

```scala
//Test.scala

import org.http4s._
import org.http4s.syntax.literals._

object Test {

  val uri = uri"localhost" / "test" +? ("key", "value")

}
```

**Comment by rossabaker** [comment]
I don't love these operators in the first place.  It feels DSLish, and if we're into DSL land, I wonder where is the `=` to go with the `?`.  But I think people do like them, and this solution looks as good as any.

I'm in favor either of this, or of deprecation.

**Comment by rossabaker** [comment]
The proposal here is probably a smoother transition than deprecation.  Let's give it a try.  Volunteers?

**Comment by alejandrohdezma** [comment]
I can do it 😸
