### ISSUE TITLE
Forum discussion

### ISSUE THREAD

**Issue by ghost** [http4s/http4s#3729]
Forum discussion
=============

Hi Folks - I am new to http4s. We have noticed that with a large payload (over 6k bytes), https connections are being shutdown. After I adding logs, examined tcpdump and browsed the code, the issue seems to be in the http4s. After connection reset, instead of calling `isReusable`, a call is made to `shutdown` the connection. Therefore, it could be a bug with idle timeout or with the http client. I am using an Http Blaze client with connection pool. The http protocol version is 1.1.
With smaller payloads (like 3kb payloads), the https connection stays alive and is re-usable for the next https call. With larger payloads and with chunk transfers, the connection is being shutdown by http4s client.

Christopher Davenport @ChristopherDavenport 16:37
@vmanpuria That seems like perhaps an idle timeout bug. If you could create an issue with the logs on highest level when it occurs we can try to figure out what's killing the connection.

_Originally posted by @vmanpuria in https://github.com/http4s/http4s/issue_comments/670792265_

**Comment by Daenyth** [comment]
Which backend are you seeing this with?

**Comment by rossabaker** [comment]
Reporter has ghosted, and idle timeout sounds plausible. Closing.
