### ISSUE TITLE
Prometheus metrics route never matches in 1.0.0-M4

### ISSUE THREAD

**Issue by willtrnr** [http4s/http4s#3731]
In `1.0.0-M4` and `master` at this time, the `pathInfo` field of `Request` was changed to a `Uri`, however the Prometheus `/metrics` route still does an equality check against a string which simply never passes.

https://github.com/http4s/http4s/blob/v1.0.0-M4/prometheus-metrics/src/main/scala/org/http4s/metrics/prometheus/PrometheusExportService.scala#L49

**Comment by rossabaker** [comment]
Yikes!  Any volunteers to clean this one up?

**Comment by jyoo980** [comment]
I can pick it up @rossabaker 

Should we remove the equality check altogether or cast the `pathInfo` to a `String`?

**Comment by rossabaker** [comment]
[impl discussion on #3738]
