### ISSUE TITLE
Port core to cats-effect-3

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#3759]

**Comment by rossabaker** [comment]
@domaspoliakas expressed an interest in this.  I'll assign it if he comments.

**Comment by domaspoliakas** [comment]
Yep, already started. Should I just do ce3 or fs3 as well?

**Comment by rossabaker** [comment]
They're going to have to go together.  I like @mpilquist's suggestion from Gitter:

> as we get more libraries actively porting to ce3, we’ll probably need to settle in to using milestones, but i’d start with the current fs2 hash release as it has Dispatcher

I _think_ `Dispatcher` is less critical for core, but it'll put us on a better foundation as we progress into the modules.

**Comment by rossabaker** [comment]
Also, you want to push intermediate commits for feedback or see a way we might divide and conquer it, don't be shy to push works in progress.  I don't mind several failed builds along the way as long as it steers us toward a green one at the end. :smile:

**Comment by domaspoliakas** [comment]
Sure thing! Do I push to my own fork and then PR for feedback?

**Comment by rossabaker** [comment]
@domaspoliakas Yes, that's perfect. And you can open it as a draft to signify it's a WIP.

**Comment by domaspoliakas** [comment]
I think what I'll do is get a little more done and then make a draft PR before the end of the day.

**Comment by djspiewak** [comment]
I'll get a M2 up asap

**Comment by domaspoliakas** [comment]
I created a draft PR now; would one normally add reviewers themselves or is it more like whoever can spare time would pick the PR up?

**Comment by djspiewak** [comment]
Also just in case it helps… If there's anything I can do to help out on this, don't hesitate to ask. Happy to dive in and work on thorny bits in here as well.

**Comment by SystemFw** [comment]
>  don't hesitate to ask.

I pinged you on a couple of things in the PR ;)
