### ISSUE TITLE
Port our literal macros to Dotty

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#3760]
`LiteralSyntaxMacros` need to be ported to Dotty macros, and probably have crossbuild source folders between Scala 2 and Scala 3.

**Comment by satorg** [comment]
To me it looks like that this issue strictly depends on #3761, doesn't it? I mean I guess we cannot make this one working on Dotty until we port all the parsers to there first.

**Comment by rossabaker** [comment]
I can't think of any that don't go through a parser, so I think you're right.  If we prioritize these parsers, perhaps someone else can get a jump on this.

**Comment by m-sp** [comment]
pretty sure this can be closed? feel free to reopen if there is still work left
