### ISSUE TITLE
Replace parboiled2

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#3761]
Parboiled2 does not work on Dotty.  The [effort to upgrade it](https://github.com/sirthias/parboiled2/issues/210) is stalled.  I tried for a weekend, and it's a heavy lift.

Similar performance has been observed with [Parsley](https://github.com/J-mie6/Parsley).

Much worse performance, but a project with more familiarity among the maintainers, is [Atto](https://github.com/tpolecat/atto).  It's unclear how much performance would suffer in practice vs. in contrived benchmarks.

Both choices come with their own risk.  We need to decide on one and start porting parsers.

This is what's most likely to break API and force an 0.22 release, though we've tried to internalize every parboiled2 reference, so, maybe not?

**Comment by satorg** [comment]
I wonder should this effort imply replacing the obsolete RFC rules we have now with their successors?

**Comment by erwan** [comment]
What about [fastparse](https://github.com/lihaoyi/fastparse)?

I've had good experience with it, both as ease of use and performances. I haven't seen a benchmark comparing it to other parsers.

Is it something that can be considered? If there is a benchmark somewhere I can integrate fastparse to see how it performs compared to the others.

**Comment by hamnis** [comment]
Fastparse is very macro-driven and is not a path towards dotty, unless there is some effort to port it.

**Comment by rossabaker** [comment]
> I wonder should this effort imply replacing the obsolete RFC rules we have now with their successors?

Absolutely, though we should be thoughtful about whether resulting semantic changes are considered bugfixes, or breaking changes that deserve a version bump.  I'm leaning toward calling them bugfixes, but let's be mindful as we go.

> What about fastparse?

I looked at porting that, and it seemed about the same order of difficulty or worse as parboiled2, for the reasons @hamnis describes.  I did some JSON benchmarking with it -- not HTTP, but something that was easy to compare across libraries -- and it was on the same order as parboiled2 and parsley.  For similar performance and similar Dotty upgrade work, I'd be inclined to stick to parboiled2 and not also rewrite our parsers.  But if someone does make it work on Dotty, and soon, then sure!

**Comment by rossabaker** [comment]
I'm engaging with Parsley upstream: 
* cross-build: https://github.com/J-mie6/Parsley/pull/6
* publish: https://github.com/J-mie6/Parsley/pull/7

A (temporary?) fork for our exploration: https://github.com/http4s/Parsley

**Comment by rossabaker** [comment]
I just released parsley-1.5.0-M2 under org.http4s.  I won't be awake to see it hit Maven Central tonight.

**Comment by rossabaker** [comment]
I created a parsley branch and added a dependency.

It branched off series/0.21.  There's nothing dotty-specific about it.  My guess is that it ultimately merges to the dotty branch, which will ultimately become series/0.22, but we've got options.  We can start trying out this parser library without immediately dealing with the other dotty failures.

**Comment by J-mie6** [comment]
By the way, if you have any problems with your transition just let me know and I'll try to help out a bit!

**Comment by rossabaker** [comment]
There is also a [proposed cats-parse](https://posco.medium.com/designing-a-parsing-library-in-scala-d5076de52536), which is worth a look as well.  As we proceed, please remember to be kind:

1. Both authors have been kind to us.
2. One author is watching.
3. Regardless, be kind.

**Comment by ChristopherDavenport** [comment]
https://github.com/typelevel/cats-parse - Now created

**Comment by satorg** [comment]
Just curious – is it a private repo? Cannot open this link, GitHub shows a Jedi instead.

**Comment by rossabaker** [comment]
cats-parse is being extracted from bosatsu and getting a build to ready it for the public ASAP. Meanwhile, you can [see the original](https://github.com/johnynek/bosatsu/blob/0934eb9ec3043e45cabf3df783cc8d6d31e19875/parser/src/main/scala/org/bykn/bosatsu/parser/Parser.scala), or read [Oscar's blog](https://posco.medium.com/designing-a-parsing-library-in-scala-d5076de52536).

In Parsley news, I cut another milestone in our repackage with Dotty support: `"org.http4s" %% "parsley" % "1.5.0-M3"`.

**Comment by rossabaker** [comment]
Re-organized with some steps and examples on #3984.
