### ISSUE TITLE
Silencer and Dotty

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#3764]
Silencer won't be supported by Dotty.  Figure out how to silence warnings as we cross-compile, as well as conditionally add the Silencer plugin.  

Using it is already repetitious enough that we embedded it in sbt-http4s-org, but it's tricky to reference `isDotty.value` there.

**Comment by aeons** [comment]
`scala.annotation.nowarn` is only 2.13, right?

**Comment by rossabaker** [comment]
Yes. scala-collection-compat includes the new annotation, so maybe if we changed the silencer annotations to that, we'd be in good shape: https://contributors.scala-lang.org/t/configurable-warnings-warning-suppression/4096/15

**Comment by rossabaker** [comment]
We rolled our own collection compat traits so far.  I can't remember why we have avoided the official compat library to this point: was it not wanting the weight of an extra dependency, or was there something deeper?  It's also something worth revisiting.

**Comment by Daenyth** [comment]
Silencer in combination with collections-compat allows you to use `nowarn` on 2.12 - I do this in my codebases

**Comment by rossabaker** [comment]
@Daenyth Great!  In that case, I think we can adopt that strategy and target the series/0.21 branch with it.  The more we can do there, the less we'll diverge as the more difficult Dotty work is done.
