### ISSUE TITLE
Log4s and Dotty

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#3766]
We need a log4s release that's compatible with dotty.  Log4s is heavily based on macros.

**Comment by ashwinbhaskar** [comment]
I cannot see an open issue in Log4s repo for dotty compatibility. Is it already done? If not, I can create an issue there and get started with it.

**Comment by rossabaker** [comment]
:+1: It's going to be a bit challenging, because log4s is so macro heavy, but I think the macros are much easier to port than something like parboiled2.

**Comment by rossabaker** [comment]
Upstream issue: https://github.com/Log4s/log4s/issues/51

**Comment by rossabaker** [comment]
WIP: https://github.com/Log4s/log4s/pull/57

**Comment by rossabaker** [comment]
log4s-0.10.0-M1 is now on our dotty branch

**Comment by rossabaker** [comment]
We'll need an 0.10.0-M2.  M1 depends on scalatest.  Sorry, everybody.

https://github.com/Log4s/log4s/pull/61
