### ISSUE TITLE
Add parens to lambdas for Dotty

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#3768]
This is probably a scalafmt setting we can tweak.  It will be valid Scala 2, so we should do this on series/0.21.

```
[error] -- Error: /home/ross/src/http4s/core/src/main/scala/org/http4s/metrics/MetricsOps.scala:97:58 
[error] 97 |  ): Request[F] => Option[String] = { request: Request[F] =>
[error]    |                                                          ^
[error]    |           parentheses are required around the parameter of a lambda
[error]    |           This construct can be rewritten automatically under -rewrite.
```

**Comment by jyoo980** [comment]
I can take this on!

**Comment by jyoo980** [comment]
A cursory glance at the docs for `scalafmt` seems to show that there actually isn't an option to enforce this type of rule... @rossabaker do you have any other ideas on how to approach this? I guess I could compile with dotty and track down where these lambdas are. That said I'm not sure if dotty compiles the code nicely right now.

**Comment by rossabaker** [comment]
Thanks for stepping forward!

I just remembered that @travisbrown [added them](https://github.com/http4s/http4s/pull/3242/commits/eab8d61b07461c25f0f0705687b930e0ad5fa2be) a while back.  Reapplying that commit might help, but it probably applies very uncleanly by now.  Even then, we need to find a switch so scalafmt doesn't eat them a second time.  A pure scalafmt solution would be better both for getting it done and keeping it done.

May also be worth checking how projects with a proper Dotty build have handled this.  Cats is one.

**Comment by jyoo980** [comment]
Hey @travisbrown!

I heard you did some work to add parens around lambda parameters to prep `http4s` for dotty. Do you have any `scalafmt` rules you used to do this?

**Comment by rossabaker** [comment]
@djspiewak pointed out the problem may be [this line](https://github.com/http4s/http4s/blob/3dd2340b0f6f2f78104f0c210436801afaaf0ed9/.scalafmt.conf#L15). If it were me, I'd try:

1. Remove it and rerun scalafmt.  Maybe we're done!
2. If not, try to reapply Travis' commit and see how bad the conflicts are.
3. Clean up what's left and what's new.

**Comment by jyoo980** [comment]
@rossabaker those sound like great steps to run after I've added the parens around the lambda params. But before that, I'm wondering if there are any tools to point out where exactly in the code we'll need to do this. Doing this manually would probably be quite error-prone (but perhaps that's the only way to go about it right now)

**Comment by djspiewak** [comment]
If it helps, take a look at my GitHub profile for the sublime text packages fork. In there is the Scala mode, which includes a "lambda look ahead" regular expression (it's labeled as such). It will work in ack/ag/rg and can be modified slightly to find all lambda declarations in the code base which lack parentheses. I would link directly but I'm on my phone.

**Comment by travisbrown** [comment]
@jyoo980 Just saw your question, but there's a `ParenthesizeLambdaParamWithType` Scalafix rule here: https://github.com/typelevel/simulacrum-scalafix

**Comment by rossabaker** [comment]
Leaving open after #3798 while we seek an automated solution, but that got us closer to a compiling core.

**Comment by m-sp** [comment]
we are now building with fatal warnings again so this should be resolved
