### ISSUE TITLE
Web framework benchmark

### ISSUE THREAD

**Issue by shengc** [http4s/http4s#378]
Is it a good idea to submit the blaze server to compare with other frameworks at techmpower 's "web framework benchmark" ?

http://www.techempower.com/benchmarks/#section=data-r10&hw=ec2&test=plaintext

**Comment by rossabaker** [comment]
I would welcome that.  We've chosen correctness over raw speed -- though we aim for both -- so I don't expect us to top the list.  But it also serves as a nice directory of tools.

To compete on speed grounds, a raw blaze example without http4s would also be interesting, though significantly more work.

**Comment by bryce-anderson** [comment]
Note that this is already been [done/attempted](https://github.com/TechEmpower/FrameworkBenchmarks/tree/master/frameworks/Scala/http4s) but I haven't actually looked at it.

The raw blaze server should be pretty simple: there is a [simple http server already built](https://github.com/http4s/blaze/blob/master/examples/src/main/scala/org/http4s/blaze/examples/HttpServer.scala) and ready to use.

**Comment by ShengC** [comment]
@bryce-anderson Oh, I was not aware of that. so we should be able to see `blaze` is listed in the next round (11) ?

**Comment by bryce-anderson** [comment]
I believe so, but I was not involved in the implementation or discussion or in the general process of the Techempower benchmarks. If you see opportunities to improve it I'm sure they are willing to take PRs.

**Comment by mfirry** [comment]
Preliminary results: https://www.techempower.com/benchmarks/previews/round11/

**Comment by bryce-anderson** [comment]
Cool! We are not doing great, especially in the plaintext result, but hey, no errors!

**Comment by mfirry** [comment]
I wrote the code, so I'm to blame if something's wrong :) I'll soon be pushing 'just' a version bump but leave the code as it is

**Comment by bryce-anderson** [comment]
I vaguely remember looking your implementation over it is was idiomatic. I expected us to come in around the same place as Play2 which is exactly what happened.

**Comment by rossabaker** [comment]
As noted, we've been in the techempower benchmarks for a while now.  Getting in more of them and continuing to improve in them can be the subject of subsequent issues and PRs. :)
