### ISSUE TITLE
ZioStreams support for backend

### ISSUE THREAD

**Issue by IcyEagle** [http4s/http4s#3785]
Hi there!

I'm looking for a way how to support a WebSocket server with ZIO Stream integrated.

So I have the next endpoint:
```scala
  val websocketEndpoint
      : Endpoint[Unit, Unit, Stream[Throwable, ClientRequest] => Stream[Throwable, ServerMessage], ZioStreams with capabilities.WebSockets] =
    endpoint
      .in("ws")
      .out(webSocketBody[ClientRequest, OctetStream, ServerMessage, OctetStream](ZioStreams))
      .description("Websocket channel")
      .get
```

and now I need to cast it to `HttpRoutes` somehow. Well, it's pretty simple with fs2 Streams but I can't find an implementation for ZIO. I found that such an endpoint is supported by `sttp` library if you wanna be a client, but as for server-side - nothing.

**Comment by rossabaker** [comment]
Interop between fs2 and other stream libraries is provided through [fs2-reactive-streams](https://fs2.io/guide.html#reactive-streams).
