### ISSUE TITLE
Port laws to cats-effect-3

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#3788]

**Comment by rossabaker** [comment]
I can't assign until he comments, but @domaspoliakas is looking at this.

**Comment by domaspoliakas** [comment]
I am indeed aiming to do this

**Comment by domaspoliakas** [comment]
Apologies for the lack of activity on this, having a bit of trouble wrapping my head around some things.

**Comment by SystemFw** [comment]
Feel free to ask questions or open a WIP PR (even if it's chaotic right now) to get advice :)
