### ISSUE TITLE
Enable implicit conversions

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#3829]
Dotty is stricter than Scala 2 about implicit conversions.  We need to add `-language:implicitConversions`.

Maybe sbt-tpolecat does this, maybe we need to do it.

Target the `dotty` branch if you use `isDotty.value`, or target `series/0.21` if you don't.

**Comment by dwlizlo** [comment]
-`language:implicitConversions` was removed from sbt-tpolecat for Dotty

**Comment by dwlizlo** [comment]
@rossabaker could you please move it to in progress/done once it's merged? I don't think I have permission to shuffle the project around. Cheers!

**Comment by rossabaker** [comment]
Fixed by #3975.
