### ISSUE TITLE
`withHeaders` is often confused with `putHeaders`

### ISSUE THREAD

**Issue by bryce-anderson** [http4s/http4s#383]
This has bitten me more than once and it appears to get others as well. I propose we rename `withHeaders` to something more verbose such as `replaceAllHeaders` (alternative suggestions welcome).

**Comment by rossabaker** [comment]
:+1:.  `.with*` is a nice convention for "sugar to copy one value", but that convention is not so well established for collections.

**Comment by kryptt** [comment]
Maybe its just a matter of education, I remember having to look it up as well, but *is* there a naming convention for this?

**Comment by bryce-anderson** [comment]
I believe @rossabaker is correct: there is a somewhat lose convention to use `withX` when replacing `X` in a case class. However, I think its a pretty loose convention. How often do are we replacing the headers wholesale? It doesn't appear that we are using it in our code that couldn't be replaced with `putHeaders`.

**Comment by ShengC** [comment]
:+1: Let's not drop `withHeaders` immediately though. Annotate it with `deprecated`, and give user some time to get used to the transition.

**Comment by lucianojoublanc-da** [comment]
Another thing to note is that this will also remove any `withContentType` header that has been added earlier through `withContentType`, e.g.:
```
  Request(...).withContentType(`Content-Type`(MediaType.application)).withHeaders(....)
```
will wipe out the content type, resulting in 415 HTTP error.
