### ISSUE TITLE
Enable kind projector for Dotty

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#3830]
Dotty requires `-Ykind-projector`.  Maybe sbt-tpolecat does this, maybe we need to do it.

Target the dotty branch if you use isDotty.value, or target series/0.21 if you don't.

**Comment by rossabaker** [comment]
Yes, upgrading sbt-tpolecat to the latest will handle this.

**Comment by jyoo980** [comment]
@rossabaker it looks like the latest update to `sbt-tpolecat` was previously performed via `scala-steward` for `v0.1.14`

Is it safe to manually bump the value to `v0.1.15` or should this be something that's automated?

**Comment by rossabaker** [comment]
Nothing is automated upstream of the main branch. Doing it manually on series/0.21 would be perfect.

**Comment by jyoo980** [comment]
@rossabaker sorry for the delay; school is insane right now. New PR opened against `series/0.21`

**Comment by rossabaker** [comment]
Fixed by #3910.
