### ISSUE TITLE
Port tests to cats-effect-3

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#3835]
This one will be large and unpleasant. We might want to discuss a way to split it up.

**Comment by yanns** [comment]
I've started working on it: https://github.com/http4s/http4s/pull/4007

**Comment by jonathanschoeller** [comment]
Did this change make it into a release of `http4s-testing`? I see that it's merged into `series/0.23` but can't seem to find a `0.23.x` release of `http4s-testing`.

**Comment by armanbilge** [comment]
@jonathanschoeller we don't publish the http4s-testing module, although we do publish laws. Is there something specific you are looking for?

**Comment by rossabaker** [comment]
There is no longer a published http4s-testing module.  Out of curiosity, what are you missing from it?  Maybe we can propose a good alternative.

**Comment by jonathanschoeller** [comment]
I inherited a project that I'm in the process of migrating from cats-effect 2.x to 3.x and it had a build dependency on `http4s-testing` declared. On looking closer though, that dependency was always unnecessary and I can just remove it and continue upgrading the other http4s modules to 0.23.x. Thanks!
