### ISSUE TITLE
Port ember-core to cats-effect-3

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#3836]
ember-server and ember-client are blocked on server and client, respectively, but @ChristopherDavenport did a good job packing most of it into ember-core.

**Comment by ashwinbhaskar** [comment]
has this been picked up by someone?

**Comment by rossabaker** [comment]
Not yet.  It's going to be one of the trickier ones, but we love volunteers and are here to help!

**Comment by ashwinbhaskar** [comment]
@rossabaker `emberCore` takes it's cat-effect dependency from `core`. Changing the cats-effect version in core might break other modules that are depending on it?

**Comment by rossabaker** [comment]
On the cats-effect-3 branch, I think we should keep up with the latest milestone, which is 3.0.0-M3. I think it's ready to go, unless there's some specific breaking change you're looking for on a later snapshot.

You're right, as we bump that, we risk breaking modules that were already working.  Hopefully those changes will be minimal and easy to keep up with.  Whenever we bump that dependency, we should recompile the modules that are already ported.

**Comment by ashwinbhaskar** [comment]
@rossabaker sorry for the late reply. If I understand this correctly, I need to make the changes in `cats-effect-3` branch?

**Comment by ashwinbhaskar** [comment]
seeing a few `java.lang.NoSuchMethodError: io.chrisdavenport.vault.Key$.newKey(Lcats/effect/kernel/Sync;)Ljava/lang/Object;` errors on running `ember-core/test`. I don't see any branch on the `vault` repo to migrate to cats-effect 3. I think I should start with that first?

**Comment by rossabaker** [comment]
Yes, that's the right branch.

The vault errors should be fixed on release of https://github.com/ChristopherDavenport/vault/pull/175. @ChristopherDavenport, anything we can do to help that one along?

**Comment by ashwinbhaskar** [comment]
@rossabaker https://github.com/ChristopherDavenport/vault/pull/175 does not use cats effect `3.0.0-M3`

**Comment by ashwinbhaskar** [comment]
@rossabaker @ChristopherDavenport anything I can do to make progress on this?

**Comment by rossabaker** [comment]
We just merged a copy into the cats-effect-3 branch while we await the release.  We don't want to release that way, but it'll get us unblocked as we continue the CE3 port.

**Comment by rossabaker** [comment]
Incorrectly autoclosed when cats-effect-3 branch was merged.
