### ISSUE TITLE
Port blaze-core to cats-effect-3

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#3837]
This one is for the brave.  Will require a knowledge of Cats-Effect and Future.

**Comment by yanns** [comment]
I think that we can put this task into progress.
There is a PR for it: https://github.com/http4s/http4s/pull/3894

**Comment by rossabaker** [comment]
I still owe that one a review and will aim to get to it this weekend.

**Comment by rossabaker** [comment]
Fixed by #3894.
