### ISSUE TITLE
Json Streaming is slow

### ISSUE THREAD

**Issue by ChristopherDavenport** [http4s/http4s#3890]
We actually encode the json in our streaming encoder using a bunch of very small chunks. Since this is going through chunked rather than Content-Length. This means backends will flush buffers on every single chunk. Resulting in buffer flushes for (N * 2) the number of elements in the stream.

Likely we will want to follow this logic via rechunking with `chunkMin` or interpolating within a chunk to keep consistent chunking as the provided stream.

https://github.com/http4s/http4s/blob/main/circe/src/main/scala/org/http4s/circe/CirceInstances.scala#L126-L129

**Comment by rossabaker** [comment]
Fixed by #3891
