### ISSUE TITLE
blaze ServerBuilder should support a configurable number of selectors

### ISSUE THREAD

**Issue by bryce-anderson** [http4s/http4s#393]
A configurable buffer size wouldn't hurt. At a minimum, it shouldn't be fixed to [an arbitrary value of 12](https://github.com/http4s/http4s/blob/master/blaze-server/src/main/scala/org/http4s/server/blaze/BlazeServer.scala#L147).

**Comment by ShengC** [comment]
Guess we should still have some sort of default value for that. A reasonable guess should be `2 * #cores + 1` ?

**Comment by bryce-anderson** [comment]
Thats what I have it set to in [blaze propper](https://github.com/http4s/blaze/blob/0f6120edbb44271049c43bbf365606a7d9699cb1/core/src/main/scala/org/http4s/blaze/channel/package.scala#L12). Somewhere between `cores + 1` and `2*cores + 1` seems appropriate.

**Comment by ShengC** [comment]
BTW - I read the code, and found out that 8k buffer space is allocated to the `HeapByteBuffer` to buffer the reads/writes inside the `SelectorLoop` thread, which is consistent with the the profile snapshot. Regarding that `64k` byte array allocated in `EPollArrayWrapper`, I think that belongs to the `nio.Selector` itself.
