### ISSUE TITLE
Replace cats.implicits._ with cats.syntax.all._

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#3944]
Reminded by https://twitter.com/mpilquist/status/1331810540595916800, this is the new recommendation.

This should mostly be a search-and-replace.  A few will be tricky: either leave those the way they are, or we can puzzle them out.

Please base the work on the series/0.21 branch.

**Comment by amiguez** [comment]
I would like to work on this one.

**Comment by amiguez** [comment]
@rossabaker Thought I linked this Issue with the PR by writing in the description:
`Fix: #3944`
I do not know why this was not closed automatically :/

**Comment by rossabaker** [comment]
I usually say "fixes #XXXX" or "closes #xxxx".  From [the docs](https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword), I'm not sure why yours didn't work.

Thanks for the PR, and thanks for calling attention to the issue.  I'm bad about coming back and closing these when the automation doesn't work.
