### ISSUE TITLE
Replace our compatibility shims with scala-collection-compat

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#3945]
We have various compatibility shims between Scala 2.12, Scala 2.13, and coming soon, Scala 3:

* The `@nowarn` annotation in core/src/main/scala-2.12
* The `CollectionCompat` objects in core/src/main/scala-2.*

We should be able to replace all of these with [scala-collection-compat](https://github.com/scala/scala-collection-compat).

We will need to make MiMa exceptions in build.sbt.  If you don't know what those are, we'll explain how and why.

This work should be performed on the series/0.21 branch.

**Comment by valencik** [comment]
I can take this on :)
Working on it over on https://github.com/valencik/http4s/tree/collection-compat

I'll likely have some questions about MiMa in a bit.

**Comment by rossabaker** [comment]
@valencik I'm sorry.  I failed to close this one.  I had a PR that did this, and it got no attention, and we just stuck with a lighter weight solution.

**Comment by rossabaker** [comment]
Ha, the PR came in while I was typing.  Well, let's take a look. :smile:

Sorry for being a bad backlog groomer.

**Comment by rossabaker** [comment]
Decided to go with the lighter approach of #4310.
