### ISSUE TITLE
Hash and BoundedEnumerable instances for QValue

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#3949]
A `QValue` can have a `Hash` and `BoundedEnumerable` instance.  The procedure is similar to #3902 and should be done from the series/0.21 branch.  This will give a tour of defining cats instances, how to avoid them clashing, and how to test for lawfulness.

**Comment by rossabaker** [comment]
If we have more volunteers than tickets, we can spin off similar tickets to this.

**Comment by jyoo980** [comment]
I'd like to give this a go!

**Comment by rossabaker** [comment]
@jyoo980 Do you still have time for this or should I throw it back in the pool for LSUG this weekend?  Thanks!

**Comment by jyoo980** [comment]
@rossabaker 

Sorry for the delay, I think I'm quite occupied at the moment, so it's better if anyone else who is interested can pick this up!

**Comment by rossabaker** [comment]
Okay, no worries. And I'm sure we'll have more tickets like this in case you want one later. :smile:

**Comment by Hiroki6** [comment]
I'd like to work on this issue.

**Comment by Hiroki6** [comment]
Hi @rossabaker , I've made a PR for this issue: https://github.com/http4s/http4s/pull/4479

**Comment by m-sp** [comment]
thanks again for your contribution!
