### ISSUE TITLE
Lift ETag.EntityTag to org.http4s

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#3955]
Most headers are in `org.http4s.header`, and most HTTP-defined values of those headers are in the `org.http4s` root package.  

1. Lift the inner `EntityTag` class out of the `org.http4s.headers.ETag` and into `org.http4s`.
2. Leave a deprecated type alias in `ETag` pointing to the new location of the class.
3. Leave a deprecated val in `ETag` pointing to the new location of the companion object.
4. Update any references in the code.

This work is a binary-breaking change, and should be done on the main branch.

**Comment by lukoyanov** [comment]
Hi. I'd like to pick this one.

**Comment by m-sp** [comment]
seems this was already done quite some time ago? thanks again for picking this up!
