### ISSUE TITLE
Fix boolean blindness of `EntityTag`'s weakness indicator

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#3956]
An entity tag can be "weak" or "strong", but we model it as `true` or `false`.  Without looking, is `true` strong or weak?  Don't know?  That's a form of "boolean blindness."  (Knowing, but having several such flags as parameters, is another.)

In the companion object of `EntityTag`:
1. Add a `sealed trait Weakness`.  
2. Extend `Product with Serializable`. This helps with type inference
3. Create a `Weak` and `Strong` that implement weakness.
4. Replace the variable.
5. Follow the compiler errors to glory.

Communicate with whoever claims #3955: whoever goes second is going to have a merge conflict if you don't!

This is a breaking change and should go on `main`.

**Comment by lukoyanov** [comment]
Hi, @rossabaker. I want to pick this one.

**Comment by rossabaker** [comment]
Wonderful, thank you!
