### ISSUE TITLE
Chip away at Dotty errors

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#3959]
From the dotty branch,

```
++3.0.0-M1 core/compile
```

For now, ignore:
* Errors mentioning parboiled2 (#3761)
* Errors mentiong CollectionCompat (#3945)
* Errors mentioning literal macros (#3760)

What progress can we make?  If they're indecipherable, can we begin to categorize them and make more tickets?

This is tedious work that won't land a feature during the Open Source event, but it's high value: many people are asking for Dotty support.

**Comment by m-sp** [comment]
first official dotty support release is imminent
