### ISSUE TITLE
Third-party cookie breaks cookie parsing

### ISSUE THREAD

**Issue by pcaisse** [http4s/http4s#4003]
Scenario:

`http4s` version: 0.20.0

On a project using `http4s` v0.20.0, we ran into a situation where our cookie-based authentication was mysteriously breaking _sometimes_ only in development and would not work again until we manually cleared cookies. As it turns out, a separate project also run on `localhost` in development was setting a cookie for Google Tag Manager like so:

```
initialTrafficSource=utmcsr=(direct)|utmcmd=(none)|utmccn=(not set);
```

The fact that there was a space in that cookie value meant that our cookies failed to parse when calling `headers.Cookie.from(requestHeaders)` in our `http4s` project. We did not expect that an invalid 3rd party cookie could have this effect.

We would like to be able to configure cookie parsing to be more permissive or have some other way to mitigate this issue.

**Comment by rossabaker** [comment]
We should consider this as part of #3982.

**Comment by pcaisse** [comment]
Thank you for being so responsive to my issue! :clap: :tada:

**Comment by rossabaker** [comment]
Absolutely. Please let us know if it's not suiting your needs, and we'll see what else we can do.
