### ISSUE TITLE
Revisit the order of type parameters in ContextRoutes

### ISSUE THREAD

**Issue by nigredo-tori** [http4s/http4s#4015]
Accross the ecosystem we have a convention to have type parameters of kind `* -> *` go before type parameters of kind `*`. We can see that in FS2, in Cats, even in Haskell! So it is surprising that we have `ContextRoutes[T, F]` rather than `ContextRoutes[F, T]`.

**Comment by rossabaker** [comment]
I agree with this.  I think it improved type inference a long time ago, but that was probably in the days of Scala 2.11?  I'd like to see how terrible this is to break, but it's deeply confusing as it is.

**Comment by danicheg** [comment]
Considering the partial unification mechanism, we can't do this refactoring, unfortunately. More details are described in #1506. Though using Scala 3 things work fine with suggested changes, using Scala 2 (2.13.8) is still causing a problem. So I close this issue for now but feel free to reopen it when we drop support of Scala 2, or magically Scala 2 will fix something.
