### ISSUE TITLE
ResponseLogger constructor overload receiving the response

### ISSUE THREAD

**Issue by Lasering** [http4s/http4s#4019]
It would be helpful if `ResponseLogger` had a "constructor" where the `logAction` would have the type `Option[Response[F] => F[Unit]]` this would allow for example: successful messages to be printed in green, client errors in yellow, and server errors in red.

A similar idea could be applied for the `RequestLogger` which would allow for example printing the request uri in bold. Or read methods (GET, HEAD, etc) in a color and write methods (PUT, POST, DELETE, etc) in another color.

We could even make a default implementation something like `ResponseLogger.colored` which would make some choices right of the gate.

I can make PR.

**Comment by rossabaker** [comment]
:+1:
