### ISSUE TITLE
What Am I doing wrong here( EntityEncoder Issue)

### ISSUE THREAD

**Issue by SarpongAbasimi** [http4s/http4s#4031]
Hello, please can someone help me to understand what I am doing wrong here. Have some patience with me please, I am just trying to understand what is going on. Thanks 😊

I have this for the route
```    
import org.http4s._
import org.http4s.implicits._
import cats._
import org.http4s.dsl.Http4sDsl
import cats.effect._
import doobie._

def show[F[_]](transactor: Transactor.Aux[F, Unit] )(implicit sync: Sync[F]) = {
    val dsl = new Http4sDsl[F] {}
    import dsl._

    HttpRoutes.of[F]{
      case GET ->  Root/"todos"/IntVar(id) => {
        val todo = TodoHelpers.getTodoByID(id,transactor)
        Ok(todo)
      }
    }
  }
```
and this for Encoding

```
object Encoders {
  final case class Todo(id: Int, todo: String)
  implicit val todoEncoder: Encoder[Todo] = new Encoder[Todo] {
    final def apply(a: Todo): Json = {
      Json.obj(
        ("id", Json.fromInt(a.id)),
        ("todo", Json.fromString(a.todo))
      )
    }
  }
  implicit def todoEntityEncoder[F[_]: Applicative]: EntityEncoder[F, Todo] = jsonEncoderOf[F, Todo]
}
```
But I am getting this error even though I have an `EntityEncoder[F, Todo]`
<img width="779" alt="Screen Shot 2020-12-17 at 22 07 09" src="https://user-images.githubusercontent.com/37377831/102550037-0d388c00-40b5-11eb-9195-898513c10c19.png">

**Comment by hamnis** [comment]
Looks like an import issue.

try adding `import Encoders._`

**Comment by hamnis** [comment]
if you place your Encoder and the EntityEncoder in the companion object of Todo, they should be found without having to import.

**Comment by rossabaker** [comment]
I'm going to move this to the new discussion board.  Please let us know if that helps, or needs more explanation!
