### ISSUE TITLE
CE3 bracket uncaught exception

### ISSUE THREAD

**Issue by RaasAhsan** [http4s/http4s#4055]
Follow up to #3857. When https://github.com/typelevel/cats-effect/pull/1535 is resolved, we can go back and fix two test cases in `ClientSyntaxSuite` that throw exceptions.

**Comment by ashwinbhaskar** [comment]
I can pick this up if it's not already taken

**Comment by rossabaker** [comment]
Thanks!  Looking at the dates, I'm not sure the fix is released yet.
