### ISSUE TITLE
Loosen Async constaints that were an artifact of MonadCancel + Sync

### ISSUE THREAD

**Issue by RaasAhsan** [http4s/http4s#4056]
Another follow up to #3857. `BracketRequestResponse` originally needed `Sync` and `MonadCancel` constraints, but using them together causes implicit ambiguity errors (they both extends `Monad`). CE3-M6 should resolve this in the hierarchy somehow

**Comment by m-sp** [comment]
was looking into that @RaasAhsan seems it doesn't have the async constraint anymore?
https://github.com/http4s/http4s/blob/main/server/src/main/scala/org/http4s/server/middleware/BracketRequestResponse.scala#L117

**Comment by RaasAhsan** [comment]
Hmm yeah I guess somebody must've fixed it already. I think we can close then
