### ISSUE TITLE
NOTICE file might need updates

### ISSUE THREAD

**Issue by gokyo** [http4s/http4s#4069]
This file might need the end years to be up to date: https://github.com/http4s/http4s/blob/main/NOTICE

**Comment by rossabaker** [comment]
I think we don't need to bother refreshing the copyrights of the things we copied from, as long as we haven't continued to copy from them.  But our own should be kept consistent with #4068.

**Comment by rossabaker** [comment]
Task: change the date on the second line of NOTICE from 2013-2018 to 2013-2021.

This is a lightweight task, if a new contributor wants to practice the PR workflow.

**Comment by rossabaker** [comment]
Fixed by #4306.
