### ISSUE TITLE
Uri should properly encode, decode, etc.

### ISSUE THREAD

**Issue by MasseGuillaume** [http4s/http4s#408]

**Comment by rossabaker** [comment]
?

**Comment by MasseGuillaume** [comment]
Ops I did'nt meant to send it like this.

is there a reason a path with spaces is not escaped with %20 ?

**Comment by rossabaker** [comment]
You're arguing that the `/` operation on `Uri` should encode its argument?  I agree.  I'm surprised it doesn't.

Does anybody think this would be bad?

**Comment by MasseGuillaume** [comment]
```scala
import org.http4s.Http4s._
uri("http://example.org/a file") //http://www.example.org/a
```

**Comment by jedesah** [comment]
@MasseGuillaume brings up a good point that this is broken elsewhere (I don't think anyone would consider the above example expected), I can say as the author of the `/` method on `Uri` that the thought of what should happen with a string that contains a space did not cross my mind one second.

I don't see any reason for it not to encode the string argument, in fact I rather think it is incorrect for it not to encode it.

@MasseGuillaume Do you want to do the honors of providing a PR with some tests cases and fixes for this or would you prefer I clean up after myself?

**Comment by jedesah** [comment]
@rossabaker @bryce-anderson So the `uri` macro function defers to `Uri.fromString` which expects an encoded `String` and decodes it. I think there should probably be two functions, one that takes an encoded `String` and one that takes a decoded `String`. And I think probably the `uri` macro should defer to the one taking a non-encoded `String`.

Does this make sense?

Also, could this work `Uri.fromString(urlDecode(someString))`? That way there might not be a need for two functions `Uri.fromString`, we could just have one that expects a non-encoded String.

**Comment by bryce-anderson** [comment]
I haven't looked at that code base much and I don't have a lot of time right now to do it, but quickly skimming the `Uri` rendering code [here](https://github.com/http4s/http4s/blob/master/core/src/main/scala/org/http4s/Uri.scala#L87) it seems we encode the query parameters and the fragment but [not the path](https://github.com/http4s/http4s/blob/master/core/src/main/scala/org/http4s/Uri.scala#L87), which should be fixed as well. Basically, we should store the _entire_ internals of `Uri` in either encoded or unencoded form but right now we have a mixture.

I do think we should have a `Uri.fromUnencoded` and `Uri.fromEncoded` or something with the same result but different names. However, if both such methods exist I think `fromString` is to ambiguous and should be renamed. As to which should be the default for the `uri` macro, I'm not decided.

**Comment by refried** [comment]
Let's proceed with caution re. whitespace specifically, because RFC 2396 Appendix E mentions whitespace being used to break up long URIs, across multiple lines, etc.

How will `Uri.fromUnencoded` treat `/` characters?  Should it escape them?  etc.

**Comment by ceedubs** [comment]
The behavior of `/` just caught me by surprise. Here's the sort of thing that I was expecting to result in URL-encoding:

```scala
scala> import org.http4s.Uri.uri
import org.http4s.Uri.uri

scala> val username: String = "foo/bar" // contains a slash, which isn't URL-safe
username: String = foo/bar

scala> uri("https://example.com") / "users" / username
res0: org.http4s.Uri = https://example.com/users/foo/bar
```

I would have expected `https://example.com/users/foo%2Fbar` as the last result.

In the past (and not in the open-source world), I've created a DSL for creating URIs that has something like:

```scala
def /[A:PathEncoder](a: A): Uri
```

A benefit of this approach is that you can do things like create `PathEncoder[Int]` and `PathEncoder[Long]` instances that know that `Int`s and `Long`s don't need to be URL-encoded but that `PathEncoder[String]` needs to perform URL-encoding to be safe. I'm not necessarily saying that http4s should go down this route, but I'm bringing it up as a possibility. It seems like so far people agree that http4s should be doing _something_ about encoding with `/`.

**Comment by rossabaker** [comment]
I think #706 scratched this itch.  There is a bunch more to discuss in URI design, but that's discussed elsewhere.
