### ISSUE TITLE
Port okhttp-client to cats-effect-3

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#4090]

**Comment by ashwinbhaskar** [comment]
Has this been picked up? If not, I can pick it up

**Comment by rossabaker** [comment]
Nope, not yet.  This one will be interesting because it has some synchronous calls.  I would expect to see some `F.blocking` in it.

**Comment by rossabaker** [comment]
Incorrectly autoclosed when cats-effect-3 branch was merged.
