### ISSUE TITLE
Port servlet to cats-effect-3

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#4091]

**Comment by ashwinbhaskar** [comment]
@rossabaker I need a bit of help here. I could not find the equivalent of `runAsync` in ce3. The code snippet where I am stuck is [this](https://github.com/http4s/http4s/blob/a7e820cca5311ab6c510d3f453f934af0de60f8a/servlet/src/main/scala/org/http4s/servlet/AsyncHttp4sServlet.scala#L59)

**Comment by rossabaker** [comment]
I'd like to hear from someone who has done more with CE3, but I think we could replace the callbacks with a `guaranteeCase`, and call an `unsafeRunAndForget()` on a `Dispacher` to replace the `unsafeRunSync()`.

**Comment by yanns** [comment]
```
F.runAsync(
        toRequest(servletRequest).fold(
          onParseFailure(_, servletResponse, bodyWriter),
          handleRequest(ctx, _, bodyWriter)
        )) {
        case Right(()) =>
          IO(ctx.complete())
        case Left(t) =>
          IO(errorHandler(servletRequest, servletResponse)(t))
      }.unsafeRunSync()
```

could be transformed into:
```
      val result = F.attempt(
        toRequest(servletRequest).fold(
          onParseFailure(_, servletResponse, bodyWriter),
          handleRequest(ctx, _, bodyWriter)
        )).map {
        case Right(()) =>
          IO(ctx.complete())
        case Left(t) =>
          IO(errorHandler(servletRequest, servletResponse)(t))
      }
     dispatcher.unsafeRunSync(result)
```
(the new version would need a `dispatcher: Dispacher[F]`)

**Comment by ashwinbhaskar** [comment]
@yanns thank you
