### ISSUE TITLE
Port examples to cats-effect-3

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#4093]

**Comment by yanns** [comment]
I can work on that.
The ember part is depending on https://github.com/http4s/http4s/issues/4086 I guess

**Comment by rossabaker** [comment]
I'm in favor of massive reform here.  We tried to DRY up the services, which is great for testing behavior of various types of routes across backends, but absolutely horrible for someone trying to find a self-contained example.  I'd say if anything is difficult, don't hesitate to either refactor it or just delete it, and we'll build back better.
