### ISSUE TITLE
Add mentioning of `EntityLimiter` to website

### ISSUE THREAD

**Issue by adschwartz** [http4s/http4s#4111]
There's a lack of information regarding the `EntityLimiter` middleware on the website: https://http4s.org/v0.21/middleware/

Being able to limit the acceptable payload size submitted to endpoints is a common feature and it would be helpful to newcomers to point them to the `EntityLimiter`.

**Comment by armanbilge** [comment]
Superseded by https://github.com/http4s/http4s/issues/5883.
