### ISSUE TITLE
Java 8 dependency?

### ISSUE THREAD

**Issue by nrinaudo** [http4s/http4s#412]
I might be doing something wrong, but when trying to use `0.10.0` on a setup that uses Java version `1.7.0_55-b13`, I'm getting some compilation errors on core http4s classes.

Specifically:
```
[error] (compile:compileIncremental) java.lang.UnsupportedClassVersionError: org/http4s/Uri$macros$ : Unsupported major.minor version 52.0
```

Note that while the error was only reported for this one class, a random sampling of various other classes also had a class file version of 52.0.

Does http4s now have a Java 8 dependency? Was this mentioned somewhere and I missed it?

**Comment by bryce-anderson** [comment]
@nrinaudo: we are compiling against Java 8 as of `0.10.0`. See https://github.com/http4s/http4s/issues/158 for the discussion.

**Comment by nrinaudo** [comment]
I *thought* I had looked into previously closed issues to find something just like that. Seems I was less thorough than I should have been, apologies for wasting your time and thanks for the swift answer!

**Comment by bryce-anderson** [comment]
No worries! It comes up enough that I have submitted a PR for the website
to note that requirement. (https://github.com/http4s/http4s/pull/413)
