### ISSUE TITLE
corrupted resolver

### ISSUE THREAD

**Issue by MasseGuillaume** [http4s/http4s#415]
https://jcenter.bintray.com/org/http4s/http4s-blazeclient_2.11/0.8.5/
https://jcenter.bintray.com/org/http4s/http4s-blazeclient_2.11/0.8.6/

the jar are missing from those versions

**Comment by rossabaker** [comment]
Weird.  I didn't know we published there.  Is that an automated, broken mirroring process?

The artifacts are in Maven Central.  Is that sufficient?

**Comment by MasseGuillaume** [comment]
@rossabaker the problem is with sbt 0.13.9. the resolver put jcenter first for some reason.

see https://github.com/MasseGuillaume/quasar/commit/aedee70b6a8993c1df9bf9b53ee8b7b539b5a1ab#diff-fdc3abdfd754eeb24090dbd90aeec2ceR22
