### ISSUE TITLE
Give blaze-server its own executor in tests

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#4166]
With regard to https://github.com/http4s/http4s/pull/4161/files/7c30f316ccc0e696d7b2b60e1475465859452f3b#r554253034, we shouldn't be testing against default thread names, but against a dedicated thread pool with obviously different names, so what we're testing for is explicit and not subject to the names of shared resources.  It will express intent better and be more robust to refactoring.

**Comment by vasilmkd** [comment]
What else needs to be done here?

**Comment by rossabaker** [comment]
We should give the BlazeServerBuilder in that test its own execution context with threads named something unique to the test, and then fix the assertion linked above to look for threads by that name.  The test is to make sure that routing happens on the given ExecutionContext, and not on an internal blaze pool, or on some global Scala or Cats Effect context.  When we gave it the global in a refactoring, we lost that nuance to the test.

**Comment by vasilmkd** [comment]
I thought that was already the case with #4161 but I see your point now.
