### ISSUE TITLE
Blaze client documentation

### ISSUE THREAD

**Issue by raimohanska** [http4s/http4s#420]
Hi guys! We've found getting started with BlazeClient to be have quite steep a learning curve, because there's no documentation to be found except for the single example at http://http4s.org/

Do you have plans to improve the documentation? What I'd really like to have would be a tutorial for performing typical tasks with the client. Including
- Http GET, POST
- Encoding, decoding
- Handling errors / different HTTP response codes

I might be willing/able to help with this too, if there just was a place for this documentation.

**Comment by bryce-anderson** [comment]
Hi @raimohanska: its true, we are really bad at documentation! Sorry about that. We had hoped to focus on documentation for a spell, but unfortunately most of the contributors have found themselves in a busy spell. @rossabaker was working on addressing documentation using [tut](https://github.com/tpolecat/tut) before he got bogged down. I don't know how far he has gotten, or if any client work at all has made it in there.

We really appreciate contributions, and docs are seriously hurting right now. Do you have any particular ideas? In my minds eye, the easiest and probably most intuitive way to begin is to have a separate 'examples' section on the site with a tree of topics and examples. This is something I thought about in the last 2 minutes, so it could be the least intuitive and most difficult way...

**Comment by raimohanska** [comment]
Something like this would be nice from my perspective

- simple HTTP get example to give an overview
- introduction to the philosoph, key concepts (client, request, task...) and how they relate to getting things done
- decoders: how to use json (argonaut, json4s), how to do simple text decoding
- handling errors / different http response codes
- http post, how to encode the post body
- http delete et al, this should be easy

**Comment by rossabaker** [comment]
The new doc site at the top of my list when I finish a work project, hopefully in a couple weeks.  I'm working on getting a tut framework set up and a few basics, and then hopefully it will be easier for others to contribute as well.

**Comment by raimohanska** [comment]
That's great news! I'll be glad to contribute to some extent on the client docs at least.

**Comment by rossabaker** [comment]
There is [client documentation](http://http4s.org/v0.15/client/) now, with a convenient edit link for anyone who wants to make it better.

**Comment by jpswain** [comment]
@rossabaker it would be super helpful to have a simple POST request with JSON.  if i could tell how it works, i'd add it myself ;-)

**Comment by rossabaker** [comment]
Does http://http4s.org/v0.15/json/ help?  Maybe we could reorganize that a bit?

**Comment by jpswain** [comment]
@rossabaker Ah that is helpful, I missed the JSON page.  Thanks!
