### ISSUE TITLE
Encoding query parameters inconsistent with standard URL encoding

### ISSUE THREAD

**Issue by sloshy** [http4s/http4s#4203]
(moved from a comment on #4103)

I'm debugging an issue where query parameters for an http4s client are not being encoded in the way the server expects them, specifically that the `+` and `:` characters are %-encoded and not presented literally (47degrees/github4s#569). I was able to trace it down to the exact characters `toSkip` when passed to Uri.encode.

The set of characters to skip when encoding a query parameter (on main):
https://github.com/http4s/http4s/blob/f5c38c1946515dc1aac2cae1039ed86e423cdace/core/src/main/scala/org/http4s/internal/UriCoding.scala#L26

The default set of characters to skip:
https://github.com/http4s/http4s/blob/f5c38c1946515dc1aac2cae1039ed86e423cdace/core/src/main/scala/org/http4s/Uri.scala#L1419

This also seems to be the case in 0.21.x where the bug I mention (for github4s) was discovered. Now I'm wondering, would this be a bug in http4s or maybe just a clash of what the world and browsers seem to support as far as query parameter encoding VS what spec http4s might have adhered to.

Quick example I was using to debug this, for reference:

```scala
import $ivy.`org.http4s::http4s-core:0.21.15`, import org.http4s.{Query, Uri}

@ Uri.encode("q=+repo:sloshy/fs2-es+label:enhancement") 
res1: String = "q=+repo:sloshy/fs2-es+label:enhancement"
@ Query.fromMap(Map("q" -> List("+repo:sloshy/fs2-es+label:enhancement"))).renderString 
res2: String = "q=%2Brepo%3Asloshy/fs2-es%2Blabel%3Aenhancement"
```

**Comment by rossabaker** [comment]
Does `Query.fromString` do what you need?  That's supposed to preserve the encoded version of the String.  The model currently supports either a vector of decoded key-pairs or an encoded raw query string.  `Query.fromString` does the latter.  This dual support was only recently bolted on, awkwardly in support of binary compatibility, and I would love to see us do better in 0.22.

**Comment by sloshy** [comment]
That it does! Thank you! I was able to figure out a fix for the specific issue we've been having using this as well (using `.copy` on the Uri, so not super clean, but, it's good enough for now). Thanks again!
