### ISSUE TITLE
CORS: comma delimit Access-Control-Allow-Methods header values

### ISSUE THREAD

**Issue by drostron** [http4s/http4s#421]
e.g.

currently:
`Access-Control-Allow-Methods: OPTIONS MOVE PUT GET POST DELETE`

should likely be:
`Access-Control-Allow-Methods: OPTIONS, MOVE, PUT, GET, POST, DELETE`

**Comment by bryce-anderson** [comment]
Hum, it seems you're right.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#Access-Control-Allow-Methods

The current behavior is defined here: https://github.com/http4s/http4s/blob/e4f1b89fa9664fb14ec20f0192aee8139567e4ab/server/src/main/scala/org/http4s/server/middleware/CORS.scala#L75

I'll put in a patch in a few minutes.

**Comment by drostron** [comment]
@bryce-anderson I submitted #422 in case you want to use that.

**Comment by bryce-anderson** [comment]
@drostron, you beat me to the punch! Thanks for the PR.

**Comment by kryptt** [comment]
thanks @drostron !

**Comment by drostron** [comment]
for sure :smiley:
