### ISSUE TITLE
Edge case test for Allow header

### ISSUE THREAD

**Issue by hamnis** [http4s/http4s#4210]
https://tools.ietf.org/html/rfc7230#section-7

allows e.g. `"foo , ,bar,charlie   "` as a valid value for the `#element` syntax

the header is just weirdly specified https://tools.ietf.org/html/rfc7231#section-7.4.1
the syntax is described as `Allow = #method` which would mean at least one method, but they immediately contradict the syntax: `An empty Allow field value indicates that the resource allows no methods`

_Originally posted by @m-sp in https://github.com/http4s/http4s/pull/4208#discussion_r557930467_

**Comment by rossabaker** [comment]
If at least one is required, the ABNF uses `1#element`.  We have `headerRep1` for this, which should probably be renamed to `headerRep` with cats-parse-0.3.

When it's optional, but with these weird delimiters, it's `#element`, which I think needs to be written and should be called `headerRep0`.

**Comment by m-sp** [comment]
> When it's optional, but with these weird delimiters, it's `#element`, which I think needs to be written and should be called `headerRep0`.

I might misunderstand the spec but https://tools.ietf.org/html/rfc7230#section-7 mentions `#element => [ 1#element ]`.
so it reads too me like `Allow = #method` should actually have at least one method

**Comment by rossabaker** [comment]
Nope, that's me spreading false information from my memory of the spec instead of rereading it.

[hangs head in shame]

**Comment by m-sp** [comment]
I think this one could be closed 😃
