### ISSUE TITLE
Remove the printlns from the tests

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#4215]
There are printlns in the tests, and there shouldn't be.  printlns in docs, and in `ErrorReporting`, are okay.

Just remove them, starting on series/0.21.

```
ember-core/src/test/scala/org/http4s/ember/core/ParsingSpec.scala
260              _ = println(trailers)
323        println(headers)

dropwizard-metrics/src/test/scala/org/http4s/metrics/dropwizard/DropwizardClientMetricsSuite.scala
274            println(valuesOf(registry, Timer("client.default.requests.headers")).map(_.headOption))
```

**Comment by rossabaker** [comment]
@jan0sch Thanks for the PR.  We're still maintaining the series/0.21 branch, where the dropwizard-metrics one still is.  (It's gone in later branches.)  If you're still interested, it would be great to clean that one up, too. Thanks!

**Comment by jan0sch** [comment]
Here you go: https://github.com/http4s/http4s/pull/4274 :-)
