### ISSUE TITLE
Port to Typelevel log4cats

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#4232]
This one should be mostly a search and replace, with a tiny bit of SBT work.

1. On series/0.22, update the dependency to `1.2.0-RC2`, published under `org.typelevel`.  This is all in Http4sPlugin.scala.
2. Change the imports from `io.chrisdavenport.log4cats` to `org.typelevel.log4cats`

**Comment by cquiroz** [comment]
I can do this one
