### ISSUE TITLE
Upgrade scalaz-stream to 0.8

### ISSUE THREAD

**Issue by ngbinh** [http4s/http4s#424]
Looks like there are some breaking changes in the use of `Terminated` https://github.com/scalaz/scalaz-stream/wiki/0.8

**Comment by rossabaker** [comment]
This might be a reason to expedite an 0.11.  Would be nice to stay current on one of our backbone libraries.

**Comment by bryce-anderson** [comment]
I'm not opposed to making it happen sooner rather than later.

**Comment by bryce-anderson** [comment]
Closed via #440.
