### ISSUE TITLE
scala-xml and specs2 and Dotty

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#4246]
specs2 depends on scala-xml.  We can't upgrade to scala-xml-2 without triggering a Dotty compatibility problem using specs2 in withDottyCompat mode.

```
[error] Modules were resolved with conflicting cross-version suffixes in ProjectRef(uri("file:/home/ross/src/http4s/"), "scala-xml"):
[error]    org.scala-lang.modules:scala-xml _3.0.0-M2, _2.13
[error] stack trace is suppressed; run 'last scala-xml / update' for the full output
[error] (scala-xml / update) Conflicting cross-version suffixes in: org.scala-lang.modules:scala-xml
[error] Total time: 0 s, completed Jan 23, 2021 11:40:24 PM
```

We're going to have to rearrange these modules such that they're not both on the classpath at once, which I don't think is a small task.

**Comment by m-sp** [comment]
checking the branches I'm pretty sure this one is done?
https://github.com/http4s/http4s/blob/series/0.22/project/Http4sPlugin.scala#L320 already refs the new scala xml

**Comment by rossabaker** [comment]
It is, yes. Thanks!
