### ISSUE TITLE
DecodeResult.success ambiguities

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#4268]
These signatures are creating ambiguities in Dotty.  We should deprecate and rename one.  Same with failure.

```scala
  def success[F[_], A](fa: F[A])(implicit F: Functor[F]): DecodeResult[F, A] =
    EitherT(fa.map(Right(_)))

  def success[F[_], A](a: A)(implicit F: Applicative[F]): DecodeResult[F, A] =
    EitherT(F.pure(Right(a)))
```

Galaxy brain: maybe that type alias is bad.

**Comment by rossabaker** [comment]
`successT` and `failureT` would be consistent with `EitherT`.

**Comment by m-sp** [comment]
I stumbled over this one again recently, so I'm :+1: on `successT` and friends. I feel the type alias is still useful

**Comment by rossabaker** [comment]
Do you want to run with this one?

**Comment by m-sp** [comment]
Sure, but it might be a couple of days until I have time for it 🙂
