### ISSUE TITLE
add `→` alias for `org.http4s.dsl.->` ?

### ISSUE THREAD

**Issue by refried** [http4s/http4s#427]
Analogous to `scala.Predef.->` vs `scala.Predef.→`  except that those are `def`s and not objects, and as such a little easier to alias.

It came up because IntelliJ IDEA can be set to convert `=>` to `⇒`, `<-` to `←` (which are equivalent in Scala) and `->` to `→` (equivalent in the stdlib, due to that alias in `Predef`).  It was converting my `org.http4s.dsl.->` to `→` too, which then wouldn't compile.

Not necessarily a great reason, but a reason nonetheless.  Thoughts?

**Comment by refried** [comment]
Grr, apparently `→` has different (higher) precedence than `->` when compared to `/`

**Comment by bryce-anderson** [comment]
Bummer.
I personally don't care much for the Unicode symbols, but as it appears to be a technical issue as well, do we close this?

**Comment by refried** [comment]
Yeah.  I’ll reopen and PR (assuming no objections) if Scala changes to give the two the same lower precedence, which seems unlikely.
