### ISSUE TITLE
Ember Server resource closure doesn't unbind port sometimes

### ISSUE THREAD

**Issue by RaasAhsan** [http4s/http4s#4282]
Followup from #4281 . It seems like after a server shuts down, if we try to re-bind to the same port, it'll fail with a `BindException: Address already in use`. To be clear, this is nondeterministic. I've noticed that as long as I'm running the same SBT shell, the port is no longer bindable. FS2 is also setting the `SO_REUSE_ADDR` option by default, so in theory it should just work.

Since this doesn't work, we can't deterministically run more than one test here: https://github.com/http4s/http4s/blob/b274f3f0e76224860b5ffe55a0bc1c6a5bfcfd58/ember-server/src/test/scala/org/http4s/ember/server/EmberServerSuite.scala#L66

We should probably try to fix this as testing on Ember ramps up.

**Comment by RaasAhsan** [comment]
A hacky stopgap solution for this is to bind to a random port for each test

**Comment by ChristopherDavenport** [comment]
This could indeed explain the doc issue

**Comment by RaasAhsan** [comment]
Seems like the particular issue I was running into was because the tests were using a parasitic `ExecutionContext`, but I don't really know what the relationship between that and failure to unbind is. Keeping this open til the docs issue is resolved.

**Comment by rossabaker** [comment]
What is the doc issue on this?

**Comment by RaasAhsan** [comment]
I think @ChristopherDavenport was running ember-server on mdoc but servers wouldn't close or something. It _should_ be fixed now
