### ISSUE TITLE
Maybe rename Ember Server's maxConcurrency to maxConnections

### ISSUE THREAD

**Issue by RaasAhsan** [http4s/http4s#4283]
`maxConnections` is a much more tangible and well-understood concept for people in the server space (and is consistent with the name of a similar knob in other servers), whereas `maxConcurrency` kind of brings up the question of "the concurrency of what?" 

Obviously this is a breaking change but I figured it was at least worth throwing out

**Comment by rossabaker** [comment]
I expect that could be handled with a deprecation.

**Comment by RaasAhsan** [comment]
I like deleting code, not adding new code! :D

**Comment by rossabaker** [comment]
I like having an incremental upgrade path when working in large codebases that don't give time to keep up but once every few years! :D

**Comment by rossabaker** [comment]
Let's do it.  I don't mind a clean break in 0.22/1.0.  Extra credit for a scalafix.

**Comment by RaasAhsan** [comment]
Closed via #5040
