### ISSUE TITLE
Modules compiling on 3.0.0-M3

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#4293]
Speak here if you're working on one

* [ ] core (#4319)
* [x] laws (@rossabaker) 
* [x] testing
* [ ] tests (@hamnis?)
* [ ] server (non-compiling test)
* [ ] prometheusMetrics (LSUG)
* [x] client
* [ ] dropwizardMetrics (LSUG)
* [x] emberCore
* [ ] emberServer (@rossabaker)
* [x] emberClient (@rossabaker)
* [x] blazeCore (https://github.com/http4s/blaze/pull/492)
* [ ] blazeServer (https://github.com/http4s/blaze/pull/492)
* [x] blazeClient (https://github.com/http4s/blaze/pull/492)
* [x] asyncHttpClient
* [x] jettyClient
* [x] okHttpClient
* [ ] servlet
* [ ] jetty
* [ ] tomcat
* [x] theDsl (@m-sp)
* [x] jawn
~~* [ ] argonaut (depends on jawn-parser_2.13)~~
* [ ] boopickle (no Dotty release)
* [ ] circe (non-compiling test)
~~* [ ] json4s (no Dotty release)~~
~~* [ ] json4sNative (no Dotty release)~~
~~* [ ] json4sJackson (no Dotty release)~~
* [ ] playJson (non-compiling test)
* [x] scalaXml (@rossabaker) (conflicts with specs2's scala-xml)
* [x] twirl (https://github.com/playframework/twirl/issues/390)
* [x] scalatags (https://github.com/lihaoyi/scalatags/pull/215)
* [ ] bench
* [ ] examples
* [ ] examplesBlaze
* [ ] examplesDocker
* [ ] examplesEmber
* [ ] examplesJetty
* [ ] examplesTomcat
* [ ] examplesWar
* [ ] scalafixInput
* [ ] scalafixOutput
* [ ] scalafixRules
* [ ] scalafixTests

**Comment by rossabaker** [comment]
`tests` are failing on `illTyped`, butI thought @hamnis had something related to that.

**Comment by rossabaker** [comment]
blaze is blocked by no Dotty release

**Comment by rossabaker** [comment]
jawn is blocked by no jawn-fs2 release

**Comment by hamnis** [comment]
@rossabaker I do not have a solution for `illTyped`, i'm not sure how `Media.covary` is supposed to work.

**Comment by m-sp** [comment]
I can take a look at the dsl

**Comment by rossabaker** [comment]
Argonaut's use of withDottyCompat paints us into a corner.  Us using withDottyCompat on any non-test dependency paints our users into a corner.  Some dependencies may need to be disabled, and I'm not very interested in publishing a ragged build matrix for their Scala 2 versions.  We may be approaching the point of spinoffs here very soon.

**Comment by rossabaker** [comment]
core has already bitrotted on M3, and looks like it will need a separate set of macros. I say we give up on M2.

**Comment by rossabaker** [comment]
Getting a lovely VerifyError on Tomcat and Jetty:

```
==> X org.http4s.server.tomcat.TomcatServerSuite.expected error running tests  0.003s java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    org/http4s/servlet/AsyncHttp4sServlet.<init>(Lcats/data/Kleisli;Lscala/concurrent/duration/Duration;Lorg/http4s/servlet/ServletIo;Lscala/Function1;Lcats/effect/ConcurrentEffect;)V @20: getfield
  Reason:
    Type uninitializedThis (current frame, stack[2]) is not assignable to 'org/http4s/servlet/AsyncHttp4sServlet'
  Current Frame:
    bci: @20
    flags: { flagThisUninit }
    locals: { uninitializedThis, 'cats/data/Kleisli', 'scala/concurrent/duration/Duration', 'org/http4s/servlet/ServletIo', 'scala/Function1', 'cats/effect/ConcurrentEffect' }
    stack: { uninitializedThis, 'cats/data/Kleisli', uninitializedThis }
  Bytecode:
    0x0000000: 2a2d b500 452a 1904 b500 472a 1905 b500
    0x0000010: 492a 2b2a b400 4519 05b7 004c 2a2c b600
    0x0000020: 5099 000a 2cb6 0054 a700 0614 0055 b500
    0x0000030: 58b1                                   
  Stackmap Table:
    full_frame(@43,{Object[#2],Object[#97],Object[#29],Object[#99],Object[#101],Object[#103]},{Object[#2]})
    full_frame(@46,{Object[#2],Object[#97],Object[#29],Object[#99],Object[#101],Object[#103]},{Object[#2],Long})

    at org.http4s.server.tomcat.TomcatBuilder.mountHttpApp$$anonfun$1(TomcatBuilder.scala:148)
    ```

**Comment by m-sp** [comment]
btw the move to munit might solve the `illTyped` problem as well: https://scalameta.org/munit/docs/assertions.html#compileerrors

**Comment by m-sp** [comment]
@rossabaker do you want to keep this open? I think this is done as far as possible

**Comment by rossabaker** [comment]
I think that's right.  We'll need similar for RC1, but hopefully that's less of an ordeal.

**Comment by m-sp** [comment]
ah I assumed https://github.com/http4s/http4s/issues/4452 is for rc1

**Comment by rossabaker** [comment]
That one is tracking the dependencies.  We'll need to be sure the modules all compile.  I just tried, and we needed a blaze fix, but I don't think it's going to be too bad.
