### ISSUE TITLE
Decide how to handle error in situations concerning invalid input

### ISSUE THREAD

**Issue by bryce-anderson** [http4s/http4s#43]
This is important to things like `EntityDecoder`. Two obvious solutions are:
- Use an either type such as the scalaz `\/` or, less desirable, the stdlib `Either`
- Make a coherent `Exception` structure and leverage the exception capabilities of scalaz `Task`

I personally think the second could be more elegant, if we can pull it off, but I think that has been attempted and failed numerous times throughout history.

**Comment by rossabaker** [comment]
`MessageFailure` addressed this well enough that nobody commented for two years.  Closing.
