### ISSUE TITLE
Http4sServlet init method should call GenericServlet init

### ISSUE THREAD

**Issue by arixmkii** [http4s/http4s#4307]
`GenericServlet` is doing some minimal setup in its `init` - preserving ref to `ServletConfig` in private field.

If the method is not called, then it will stay uninitialized (null) and when calling `log` method on implemented servlet it will throw exception:

```
java.lang.NullPointerException: Cannot invoke "javax.servlet.ServletConfig.getServletContext()" because the return value of "javax.servlet.GenericServlet.getServletConfig()" is null
```

**Comment by rossabaker** [comment]
@arixmkii I agree. Do you want to open a PR for that?  If so, please target series/0.21.

**Comment by arixmkii** [comment]
@rossabaker did one for the main branch. Will redo to 0.21.

**Comment by rossabaker** [comment]
Ha, you're typing on one issue while I'm typing on the other. Yeah, if you target series/0.21, we can release it as part of 0.21.17, and then it'll merge forward into 0.22 and 1.0 series as well.

**Comment by arixmkii** [comment]
PR for 0.21 series #4309
