### ISSUE TITLE
Uri and other types in their own subproject

### ISSUE THREAD

**Issue by purefn** [http4s/http4s#431]
`Uri` is a much better implementation of the URI spec than the standard `java.net.URI`. It would be fantastic if it were in a separate subproject, so that others could use it without bringng in the whole of `http4s-core`. Other types that would be useful are the `Method`, `Status`, and header related types. A goal of this `http4s-types` subproject would be to be free of any dependencies so it is useful too everyone, much like [scodec-bits](https://github.com/scodec/scodec-bits) was pulled out of scodec.

**Comment by bryce-anderson** [comment]
There are others interested in that as well. For a `Uri` specific example see https://github.com/http4s/http4s/issues/428. Quite a bit of it would be straight forward to extract (I imagine, it could be much worse in practice) but there are some knots with regards to the headers. I think we'd be happy to see someone come up with a plan and get an understanding of the fallout.

**Comment by rossabaker** [comment]
Many headers take one or more values. This tends to be modeled by us as a NonEmptyList.  In a hypothetical http4s-types, how are these modeled?

**Comment by rossabaker** [comment]
We created our own `NonEmptyList` because of the churn in scalaz's, so that's one problem solved.

**Comment by rossabaker** [comment]
Closing due to lack of interest, but welcome reopening if someone brings a use case.
