### ISSUE TITLE
Blaze client cannot access self-signed certificate with invalid hostname

### ISSUE THREAD

**Issue by jamalsa** [http4s/http4s#432]
I am using Blaze client to access site with self-signed SSL certificate and got exception: `java.security.cert.CertificateException: No subject alternative names matching IP address <IP Address> found`. After digging the code, by default blaze client will accept invalid certificate but still try to verify hostname. I try to find whether class [HostnameVerifier](https://docs.oracle.com/javase/7/docs/api/javax/net/ssl/HostnameVerifier.html) is used by http4s/blaze but found nothing. 

Can you give me a pointer how to use custom HostnameVerifier in blaze client?

**Comment by bryce-anderson** [comment]
Indeed, this is probably a result of this PR: https://github.com/http4s/http4s/pull/394. Interestingly, I don't seem to have a problem with sites using a self signed certificate (such as my own personal site) which would seem to be a problem.

Its easy enough to add a boolean flag to skip that process but considering verification doesn't seem to work for me, I'm concerned there is something not quite right with the process as is.

**Comment by bryce-anderson** [comment]
@jamalsa, I'm not sure if you're in a position to test the branch I've made a PR from, but it would be good to know if it works for you or not before merging it.

**Comment by jamalsa** [comment]
Thanks for your response @bryce-anderson. I will test that branch and report the result to you.

**Comment by bryce-anderson** [comment]
@jamalsa, did you ever get around to testing the branch?

**Comment by jamalsa** [comment]
Sorry for late response. I have tested that branch by defining 

    val client = SimpleHttp1Client(endpointAuthentication = false)

and it successfully skipped hostname verification. Thanks for your help.

**Comment by bryce-anderson** [comment]
I believe this should be closed via #435.
