### ISSUE TITLE
Move to munit tests

### ISSUE THREAD

**Issue by m-sp** [http4s/http4s#4322]
Coordination ticket for the move to munit. If you work on any please do comment here and start with `series/0.21` if possible.

- [x] ForwardedRenderersSpec (org.http4s.headers)
- [x] ProxyAuthenticateHeaderSpec (org.http4s.parser)
- [x] Http4sSpec (org.http4s)
- [x] Http1ClientStageSpec (org.http4s.client.blaze)
- [x] QueryParserSpec (org.http4s.parser)
- [x] LocationHeaderSpec (org.http4s.parser)
- [x] EntityEncoderSpec (org.http4s)
- [x] BlazeServerMtlsSpec (org.http4s.server.blaze) https://github.com/http4s/http4s/pull/4367/
- [x] HeaderSpec (org.http4s)
- [x] Ipv6AddressSpec (org.http4s) https://github.com/http4s/http4s/pull/4376
- [x] QueryParamCodecSpec (org.http4s) https://github.com/http4s/http4s/pull/4376
- [x] DateSpec (org.http4s.server.middleware) https://github.com/http4s/http4s/pull/4320
- [x] HttpDateSpec (org.http4s)
- [x] RegNameSpec (org.http4s)
- [x] Rfc3986ParserSpec (org.http4s.parser)
- [x] MediaTypeSpec (org.http4s) https://github.com/http4s/http4s/pull/4355
- [x] AuthoritySpec (org.http4s)
- [x] QValueSpec (org.http4s)
- [x] StatusSpec (org.http4s)
- [x] CharsetRangeSpec (org.http4s)
- [x] QuerySpec (org.http4s)
- [x] TransferCodingSpec (org.http4s)
- [x] CookieSpec (org.http4s) https://github.com/http4s/http4s/pull/4355
- [x] Ipv4AddressSpec (org.http4s) https://github.com/http4s/http4s/pull/4376
- [x] OriginHeaderSpec (org.http4s.parser)
- [x] ServerSentEventSpec (org.http4s) https://github.com/http4s/http4s/pull/4355
- [x] RangeParserSpec (org.http4s.parser)
- [x] HeadersSpec (org.http4s)
- [x] AuthorizationHeaderSpec (org.http4s.parser)
- [x] SchemeSpec (org.http4s)
- [x] HttpRoutesSpec (org.http4s)
- [x] JsonDebugErrorHandlerSpec (org.http4s.circe.middleware)
- [x] Http1ServerStageSpec (org.http4s.server.blaze) https://github.com/http4s/http4s/pull/4367/
- [x] MethodSpec (org.http4s)
- [x] UriSpec (org.http4s)
- [x] CharsetSpec (org.http4s)
- [x] HeaderLaws (org.http4s.headers)
- [x] RefererSpec (org.http4s.headers)
- [x] DateSpec (org.http4s.headers)
- [x] ContentTypeHeaderSpec (org.http4s.headers)
- [x] AcceptEncodingSpec (org.http4s.headers)
- [x] AccessControlAllowCredentialsSpec (org.http4s.headers)
- [x] ContentEncodingSpec (org.http4s.headers)
- [x] RetryAfterSpec (org.http4s.headers)
- [x] MaxForwardsSpec (org.http4s.headers)
- [x] TransferEncodingSpec (org.http4s.headers)
- [x] AcceptLanguageSpec (org.http4s.headers)
- [x] AccessControlExposeHeadersSpec (org.http4s.headers)
- [x] AcceptHeaderSpec (org.http4s.headers)
- [x] StrictTransportSecuritySpec (org.http4s.headers)
- [x] ContentLengthSpec (org.http4s.headers)
- [x] AcceptCharsetSpec (org.http4s.headers)
- [x] AgeSpec (org.http4s.headers)
- [x] ExpiresSpec (org.http4s.headers)
- [x] AcceptPatchSpec (org.http4s.headers)
- [x] AllowSpec (org.http4s.headers)
- [x] ZipkinHeaderSpec (org.http4s.headers)
- [x] LinkSpec (org.http4s.headers)
- [x] LastEventIdSpec (org.http4s.headers)
- [x] AccessControlAllowHeadersSpec (org.http4s.headers)
- [x] SimpleHeadersSpec (org.http4s.parser)
- [x] UriParserSpec (org.http4s.parser)
- [x] Http4sWSStageSpec (org.http4s.blazecore.websocket) https://github.com/http4s/http4s/pull/4367/
- [x] UrlFormSpec (org.http4s)
- [x] UserInfoSpec (org.http4s)
- [x] UriHostSpec (org.http4s)
- [x] MetricsOpsSpec (org.http4s.metrics)
- [x] ContentLocationHeaderSpec (org.http4s.parser)
- [x] MediaRangeSpec (org.http4s)
- [x] ZipkinHeaderSpec (org.http4s.headers)
- [x] UriTemplateSpec (org.http4s)
- [x] HttpVersionSpec (org.http4s)
- [x] ContentCodingSpec (org.http4s) https://github.com/http4s/http4s/pull/4376
- [x] FormDataDecoderSpec (org.http4s)
- [x] Http1WriterSpec (org.http4s.blazecore.util) https://github.com/http4s/http4s/pull/4367/
- [x] DecodeSpec (org.http4s)
- [x] SetCookieHeaderSpec (org.http4s.headers) https://github.com/http4s/http4s/pull/4324
- [x] ResponderSpec (org.http4s)
- [x] WebSocketSpec (org.http4s.websocket)
- [x] ClientHelpersSpec (org.http4s.ember.client.internal) https://github.com/http4s/http4s/pull/4354
- [x] MultipartSpec (org.http4s.multipart)
- [x] ForwardedHeaderSpec (org.http4s.parser)
- [x] AcceptLanguageSpec (org.http4s.parser)
- [x] ExecutionSpec (org.http4s.internal)
- [x] WebSocketHandshakeSpec (org.http4s.websocket)
- [x] OriginHeaderSpec (org.http4s.parser)
- [x] CacheControlSpec (org.http4s.parser)
- [x] MediaRangeSpec (org.http4s.parser)
- [x] AcceptHeaderSpec (org.http4s.parser)
- [x] HeaderParserSpec (org.http4s.parser)
- [x] AcceptEncodingSpec (org.http4s.parser)
- [x] ForwardedSpec (org.http4s.headers)
- [x] ContentLanguageSpec (org.http4s.parser)
- [x] WwwAuthenticateHeaderSpec (org.http4s.parser)
- [x] ParsingSpec (org.http4s.ember.core) https://github.com/http4s/http4s/pull/4376
- [x] AcceptRangesSpec (org.http4s.parser)
- [x] ContentTypeHeaderSpec (org.http4s.parser)

**Comment by cquiroz** [comment]
I'll do some tests focusing on the `org.http4s.headers` package

**Comment by m-sp** [comment]
there might be one or the other still on 0.21 but 22 and onwards are exclusively on munit
