### ISSUE TITLE
OData uses non-standard query parameter keys

### ISSUE THREAD

**Issue by kryptt** [http4s/http4s#4346]
OData uses query parameter keys that start with "$" and many implementations do not correctly url-decode parameter keys.
Microsoft Sharepoint and others 

Since #511  query parameter keys are correctly url-encoded but everything is final, so this is proving hard to workaround....

**Comment by rossabaker** [comment]
Does the new encoding with `Query` wrapping an `Either[Vector[KeyValue], String]` help?  That was supposed to preserve raw access for these APIs that play fast and loose with the spec.

**Comment by kryptt** [comment]
Yes indeed! I just found that out, maybe I missed it in the documentation / as I was exploring the code..... 

Feel free to close it if you want

p.s. Its nice to be using http4s again... :D

**Comment by rossabaker** [comment]
It's relatively new and the docs probably haven't caught up yet. Glad that worked!
