### ISSUE TITLE
CORS breaks under the new Fallthrough 404 responses

### ISSUE THREAD

**Issue by kryptt** [http4s/http4s#441]
Maybe we need to consider the empty fallthrough response as a viable condition to send CORS headers on an incoming request.

**Comment by bryce-anderson** [comment]
I assume this is a bug? Do we want to get it fixed before a release? I don't see it being a binary compatibility issue if we don't but it also doesn't sound to difficult to address.

**Comment by kryptt** [comment]
I think it should be treated as a bug. Working on it now.

**Comment by bryce-anderson** [comment]
I believe this has been addressed by #442.
