### ISSUE TITLE
Blaze client throws java.lang.NoClassDefFoundError: cats/effect/implicits/package$ with cats-effect 3.0.0-RC1

### ISSUE THREAD

**Issue by arixmkii** [http4s/http4s#4427]
Seems that cats effect RC1 introduced source and binary incompatible changes in various clients (blaze, async, ember).

**Comment by rossabaker** [comment]
Yep, there are a lot of other pieces that aren't binary compatible.  We can leave this open as a the "it doesn't work on RC1 yet" ticket, but watch #4414 for the fix.

**Comment by arixmkii** [comment]
@rossabaker I shared some more updates from my side for #4414 here https://github.com/scala-steward/http4s/pull/1 
Didn't manage to get ember-server working (managed to compile it though, but it for sure is not merge ready).

**Comment by m-sp** [comment]
I think we can close this?
we have a new [release](https://github.com/http4s/http4s/releases/tag/v1.0.0-M17) with cats-effect-3.0.0-RC2

**Comment by arixmkii** [comment]
Yes, I think it is safe to do. Will test the new release this week.
