### ISSUE TITLE
Dependencies needed for Scala 3.0.0-RC1

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#4452]
* [x] cats-effect
* [x] log4s
* [x] cats-parse
* [x] fs2
* [x] vault
* [x] scodec-bits
* [x] case-insensitive
* [x] ip4s
* [x] cats
* [ ] scalafix (we should hack around this)
* [x] keypool
* [x] log4cats
* [x] unique
* [x] jawn
* [x] jawn-fs2
* [x] circe
* [x] play-json
* [x] scala-xml
* [ ] boopickle
* [ ] twirl
* [ ] scalatags
* [x] blaze

**Comment by SethTisue** [comment]
I'll make sure play-json gets published soon. (and I started work on Twirl, but not sure yet on timeframe to finish)

**Comment by ScalaWilliam** [comment]
Amazing initiative :-) 
This is like the core library for those of us wanting to move into Scala 3 sooner than later

**Comment by rossabaker** [comment]
We're very close on 3.0.0-M3 just as RC1 arrives.  I expect we'll publish a mostly full milestone for M3, plus whatever we manage to already have working on RC1.

**Comment by SethTisue** [comment]
play-json 2.10.0-RC2 has been published with 3.0.0-RC1 support, as per https://github.com/playframework/play-json/issues/570

**Comment by rossabaker** [comment]
Yep, already integrated play-json. Thanks!

**Comment by rossabaker** [comment]
We released on RC1 today.  I think we can retire this ticket.
