### ISSUE TITLE
Header.value strips value after hyphen

### ISSUE THREAD

**Issue by Pyppe** [http4s/http4s#446]
Encountered something fishy. Given following server:
```scala
HttpService {
  case req @ GET -> Root / "testing" =>
    val ifNoneMatch= req.headers.get(`If-None-Match`).map(_.value).getOrElse("NO_VALUE")
    Ok(ifNoneMatch)
}
```

We have this kind of behavior:
```bash
curl -XGET "localhost:8080/testing" -H "If-None-Match: 123-999"
123
```
Am I missing something about HTTP header specification, or why in the example above the result is `123` instead of `123-999`?

**Comment by Pyppe** [comment]
If I were to use quoted `If-None-Match` -header (`curl ... --header 'If-None-Match: "quoted-string"'`), the http4s parses the corresponding header as an empty String.

**Comment by bryce-anderson** [comment]
@Pyppe, you're right, the parser is broken. PR #447 should address it. Note that RFC 7232 appears to require tags in double quotes (http://tools.ietf.org/html/rfc7232#section-2.3) so your origional header is invalid while your follow up comment should be valid.

**Comment by Pyppe** [comment]
:+1:
