### ISSUE TITLE
Access-Control-Allow-Credentials no longer implements `HeaderKey.Extractable` (v0.22+)

### ISSUE THREAD

**Issue by zarthross** [http4s/http4s#4498]
https://github.com/http4s/http4s/blob/8f52735b5362395c86acb3d33c51b9dc3551aa4f/core/src/main/scala/org/http4s/headers/Access-Control-Allow-Credentials.scala#L23-L24

This breaks usage with Rho's `captureMapR` function.  

I think this header should probably implement `HeaderKey.Singleton`

**Comment by rossabaker** [comment]
Have you seen the header refactor proposal in the main repo? We better figure out what that means for rho.

**Comment by zarthross** [comment]
Took a quick glance at PR #4415 and I like it.  The only part of Rho that was broke from this issue was you couldn't extract this specific header from a Headers anymore when previously you could.  Looking at the proposed `Headers.get[HeaderType]` should work in Rho.  I'll keep my eyes on that proposal so i can try and integrate it as soon as its ready.

**Comment by rossabaker** [comment]
If there's anything I can do to help rho integrate it, let me know, but I think there's nothing to do here.
