### ISSUE TITLE
What does the "connectorPoolSize" parameter do?

### ISSUE THREAD

**Issue by sovereignsoftware** [http4s/http4s#450]
It's a parameter on BlazeBuilder, but it doesn't appear to actually be used anywhere. What is the parameter for?

I also noticed that NIO1SocketServerGroup and NIO2SocketServerGroup, in the BlazeBuilder.start function, both use a hardcoded pool size of 12. Is this a bug and is it related to connectorPoolSize?

**Comment by sovereignsoftware** [comment]
The bufferSize parameter is similarly not used... it seems suspiciously like should be `NIO2SocketServerGroup.fixedGroup(12, 8 * 1024)` should really be `NIO2SocketServerGroup.fixedGroup(connectorPoolSize, bufferSize)`.

**Comment by bryce-anderson** [comment]
Hi @sovereignsoftware, you're right, that is a problem. Thanks for pointing it out!

**Comment by sovereignsoftware** [comment]
Cool! Since a fix is merged, I'll close my issue :)
