### ISSUE TITLE
Fix deprecations from header refactor

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#4535]
The header refactor in #4415 was done with a temporary "v2" package.  We need to clear out references to the old.

These are the files with warnings.  For new contibutors, headers will be the easiest.  There are patterns to follow in #4533 (recurring) and #4534 (singleton).

All this work needs to happen on series/0.22.  We'll be accepting volunteers at the LSUG event on Feburary 27 to kick this off.

[March 2: resetting the list]

* [x]  HeaderEchoSuite.scala 2 server/src/test/scala/org/http4s/server/middleware/ (@rossabaker)
* [x]  HeaderLaws.scala 1 tests/src/test/scala/org/http4s/headers/ [@phongngtuan]
* [x]  HeaderParserSuite.scala 3 tests/src/test/scala/org/http4s/parser/ (@rossabaker)
* [x]  HeaderSuite.scala 15 tests/src/test/scala/org/http4s/
* [x]  HeadersSpec.scala 25 tests/src/test/scala/org/http4s/
* [x]  Http1ServerStageSpec.scala 9 blaze-server/src/test/scala/org/http4s/server/blaze/
* [x]  HttpHeaderParser.scala 55 core/src/main/scala/org/http4s/parser/ (@rossabaker)
* [x]  HttpHeadersBench.scala 9 bench/src/main/scala/org/http4s/bench/ (@rossabaker)
* [x]  Last-Modified.scala 7 core/src/main/scala/org/http4s/headers
* [x]  Location.scala 7 core/src/main/scala/org/http4s/headers/
* [x]  LocationHeaderSuite.scala 11 tests/src/test/scala/org/http4s/parser/
* [x]  Max-Forwards.scala 7 core/src/main/scala/org/http4s/headers/
* [x]  MediaTypeSuite.scala 3 tests/src/test/scala/org/http4s/ (@rossabaker)
* [x]  Origin.scala 7 core/src/main/scala/org/http4s/headers/
* [x]  OriginHeaderSuite.scala 19 tests/src/test/scala/org/http4s/parser/
* [x]  Proxy-Authorization.scala 7 core/src/main/scala/org/http4s/headers/
* [x]  Range.scala 7 core/src/main/scala/org/http4s/headers/
* [x]  Referer.scala 7 core/src/main/scala/org/http4s/headers/
* [x]  ResponseParser.scala 7 blaze-core/src/test/scala/org/http4s/blazecore/
* [x]  Retry-After.scala 7 core/src/main/scala/org/http4s/headers/
* [x]  Server.scala 6 core/src/main/scala/org/http4s/headers/
* [x]  Set-Cookie.scala 9 core/src/main/scala/org/http4s/headers/
* [x]  SimpleHeadersSpec.scala 11 tests/src/test/scala/org/http4s/parser/
* [x]  WebSocket-Protocol.scala 1 core/src/main/scala/org/http4s/headers/ (@rossabaker)

**Comment by phongngtuan** [comment]
Hi @vder @VlachJosef I gave a go for those headers below in #4547 
i think there are already some duplicate but i'm happy to rebase later
``` 
addParser_(CIString("ACCESS-CONTROL-EXPOSE-HEADERS"), `Access-Control-Expose-Headers`.parse)
addParser_(CIString("AGE"), Age.parse)
addParser_(CIString("ALLOW"), Allow.parse)
addParser_(CIString("AUTHORIZATION"), Authorization.parse)
addParser_(CIString("CACHE-CONTROL"), `Cache-Control`.parse)
addParser_(CIString("CONNECTION"), Connection.parse)
addParser_(CIString("CONTENT-DISPOSITION"), `Content-Disposition`.parse)
addParser_(CIString("CONTENT-ENCODING"), `Content-Encoding`.parse)
addParser_(CIString("CONTENT-LANGUAGE"), `Content-Language`.parse)
addParser_(CIString("CONTENT-LENGTH"), `Content-Length`.parse)
addParser_(CIString("CONTENT-LOCATION"), `Content-Location`.parse)
addParser_(CIString("CONTENT-RANGE"), `Content-Range`.parse)
addParser_(CIString("CONTENT-TYPE"), `Content-Type`.parse)
addParser_(CIString("COOKIE"), Cookie.parse)
addParser_(CIString("ACCEPT-ENCODING"), `Accept-Encoding`.parse)
addParser_(CIString("ACCEPT-RANGES"), `Accept-Ranges`.parse)
```

**Comment by rossabaker** [comment]
Had a [lengthy Gitter chat](https://gitter.im/http4s/http4s-dev?at=603c6f8c5d0bfb4e587b5ab9) with @phongngtuan about standards for these.  To avoid the boilerplate, we think it makes sense to do as follows:

- In the companion, define `name`, `value`, and `parse` only via the instance.  So:
   
    ```scala
    object Date {
      /* `Date = HTTP-date` */
      private[http4s] val parser: Parser[`Date`] =
        HttpDate.parser.map(apply)

      implicit val headerInstance: v2.Header[Date, v2.Header.Single] =
        v2.Header.createRendered(
          CIString("Date"),
          _.date,
          ParseResult.fromParser(parser, "Invalid Date header")
        )
        
      // no `name` (formerly inherited through `Internal`)
      // no `parse` (it's the third argument to `createRendered`)
    }
   ```

- In the case class, don't worry about `name`, `value`, or `renderString`:

   ```scala
   final case class Date(date: HttpDate) {
     // The old `value` is part of the Header instance
     // The old `renderString` can be derived from the Header instance
     
     // If you had a complicated `render` method, maybe comment it out, or use it in
     // your instance definition.  We're still benchmarking how that makes a difference
     // in backends.

     // Some of these might end up with no body at all:
   }
   ```

- `.name`, `.value`, and `.renderString` can be called from the typeclass, and we'll provide syntax via the `Header` typeclass in the usual way under `org.http4s.syntax`.  We'll want to get this in quickly, since it affects tests as we port the other headers, but I think @phongngtuan is already looking at this.

This will lead to maintainable, readable definitions.  It might make a few more users have to import `syntax.all._`, but those methods are mostly used in tests and backends, so I think it's a price we can bear.

**Comment by rossabaker** [comment]
I fell behind on the checklist above.  But in the meantime, if you're working on these, please leave a comment like @phongngtuan did, just to make sure we're not duplicating any work.  I'll try to cleanly separate out a list of headers tomorrow.

**Comment by VlachJosef** [comment]
Hi @phongngtuan  
here is a list of `Recurring` headers ported in #4545 
```
Access-Control-Allow-Headers
Access-Control-Expose-Headers 
Cache-Control
Content-Language
Cookie
Forwarded 
Link
Proxy-Authenticate 
WWW-Authenticate
X-Forwarded-For
```
Once the new syntax is in place I'll make use of it in these headers as well.

**Comment by phongngtuan** [comment]
those are the the remaining headers (excluding what's in #4545 and #4547) up for grab :) might as well reserve a few at a time if you're working on them
```
  0 Access-Control-Allow-Credentials.scala                                                                                                                                         
  1 Date.scala                                                                                                                                                                     
  2 ETag.scala                                                                                                                                                                     
  3 Expires.scala                                                                                                                                                                  
  4 Host.scala                                                                                                                                                                     
  5 If-Match.scala                                                                                                                                                                 
  6 If-Modified-Since.scala                                                                                                                                                        
  7 If-None-Match.scala                                                                                                                                                            
  8 If-Unmodified-Since.scala                                                                                                                                                      
  9 Last-Event-Id.scala                                                                                                                                                            
 10 Last-Modified.scala                                                                                                                                                            
 11 Location.scala                                                                                                                                                                 
 12 Max-Forwards.scala                                                                                                                                                             
 13 Origin.scala                                                                                                                                                                   
 14 Proxy-Authorization.scala                                                                                                                                                      
 15 Range.scala                                                                                                                                                                    
 16 Referer.scala                                                                                                                                                                  
 17 Retry-After.scala                                                                                                                                                              
 18 Server.scala                                                                                                                                                                   
 19 Set-Cookie.scala                                                                                                                                                               
 20 Strict-Transport-Security.scala                                                                                                                                                
 21 Transfer-Encoding.scala                                                                                                                                                        
 22 User-Agent.scala                                                                                                                                                               
 23 X-B3-Flags.scala                                                                                                                                                               
 24 X-B3-ParentSpanId.scala                                                                                                                                                        
 25 X-B3-Sampled.scala                                                                                                                                                             
 26 X-B3-SpanId.scala                                                                                                                                                              
 27 X-B3-TraceId.scala 
```

**Comment by vder** [comment]
I'm booking the following numbers then:
10 Last-Modified.scala                                                                                                                                                            
 11 Location.scala                                                                                                                                                                 
 12 Max-Forwards.scala                                                                                                                                                             
 13 Origin.scala                                                                                                                                                                   
 14 Proxy-Authorization.scala                                                                                                                                                      
 15 Range.scala   

and I'll try to push PR later today

**Comment by VlachJosef** [comment]
@phongngtuan thanks for the list, I'll grab the the ones on the end:
```
 20 Strict-Transport-Security.scala
 21 Transfer-Encoding.scala
 22 User-Agent.scala
 23 X-B3-Flags.scala
 24 X-B3-ParentSpanId.scala
 25 X-B3-Sampled.scala
 26 X-B3-SpanId.scala
 27 X-B3-TraceId.scala
```

**Comment by phongngtuan** [comment]
hi @rossabaker I tried to bring the Select Renderer instance to `Select` but don't know you to use it without importing the `implicit def` itself. Do you have any advice?

**Comment by m-sp** [comment]
also have some time so will do
```
  5 If-Match.scala                                                                                                                                                                 
  6 If-Modified-Since.scala                                                                                                                                                        
  7 If-None-Match.scala                                                                                                                                                            
  8 If-Unmodified-Since.scala                                                                                                                                                      
  9 Last-Event-Id.scala   
```

**Comment by m-sp** [comment]
and:

```
  0 Access-Control-Allow-Credentials.scala                                                                                                                                         
  1 Date.scala                                                                                                                                                                     
  2 ETag.scala                                                                                                                                                                     
  3 Expires.scala                                                                                                                                                                  
  4 Host.scala  
```

**Comment by phongngtuan** [comment]
I'm tackling `HeaderLaw` in #4552. Once it merges we could change `headerLaw(Expires)` to `headerLaw[Expires]` (parentheses to square bracket)

**Comment by VlachJosef** [comment]
Hi, I'll start migrating last cookies (I hope no one is doing it yet):
```
16 Referer.scala
17 Retry-After.scala
18 Server.scala
19 Set-Cookie.scala
```

**Comment by phongngtuan** [comment]
Hi all, I'm tackling these 3...
- ResponseParser.scala
- Http1ServerStageSpec.scala
- HeaderSuite.scala

**Comment by VlachJosef** [comment]
I've noticed that headers:
```
Last-Modified.scala
Location.scala
Max-Forwards.scala
Origin.scala
Range.scala
```
has not been migrated yet. @vder are you still working on them?

**Comment by rossabaker** [comment]
Fantastic work, everyone.  #4576 removes the legacy headers.  If we remove the `v2`, I think we're done.  I'll tackle that tonight, unless someone claims it.

**Comment by rossabaker** [comment]
I've gone ahead tried the move in #4576, too.
