### ISSUE TITLE
NonBlockingServletIo does not work with jetty

### ISSUE THREAD

**Issue by hvesalai** [http4s/http4s#454]
When using [`NonBlockingServletIo`](https://github.com/http4s/http4s/blob/master/servlet/src/main/scala/org/http4s/servlet/ServletIo.scala#L57), `Http4sServlet` [calls](https://github.com/http4s/http4s/blob/master/servlet/src/main/scala/org/http4s/servlet/Http4sServlet.scala#L69) `AsyncContext.complete()` while the last chunk's write is still pending. This results is jetty closing the connection prematurely (all data is not sent to client) and a warning (`java.nio.channels.WritePendingException`). This occurs especially when the chunk is large (for good repeatability, try some hundreds of megabytes, but even a few hundred kilobytes is enough to trigger it).

While I don't know if this is a bug in jetty or http4s (i.e. is http4s doing something illegal or is jetty just broken), I think it would be simplest to fix on http4s side. The fix would simply be that Http4s should not issue the `AsyncContext.complete()` until the `ServletOutputStream.isReady()` returns true (and wait for last `onWritePossible` if necessary).

**Comment by bryce-anderson** [comment]
@rossabaker, you're the servlet expert so I'll deffer this to your expertise for now. If this is still open when I find some time I'll take a look.

**Comment by rossabaker** [comment]
Yes, I'll take a look.

**Comment by hvesalai** [comment]
Nice @rossabaker. If there's any info you need from me, I'll be glad to help.

**Comment by hvesalai** [comment]
@rossabaker jetty team is saying it's not their bug https://bugs.eclipse.org/bugs/show_bug.cgi?id=483091

**Comment by rossabaker** [comment]
Is there an http4s version of the test in Jetty's Bugzilla yet?  If not, I can adapt it.  If there is, that will give me a head start.

**Comment by hvesalai** [comment]
```scala
import org.eclipse.jetty.server.{ServerConnector, Server, HttpConnectionFactory, HttpConfiguration}
import org.eclipse.jetty.servlet.{ServletContextHandler, ServletHolder}
import org.http4s.server.HttpService
import org.http4s.servlet.{ServletContainer, Http4sServlet}
import org.http4s.dsl._
import scala.concurrent.duration._
import scalaz.concurrent.Strategy

object JettyTest {
   // If the bug is not triggered right away, try increasing or
   // repeating the request. Also if you decrease the data size (to
   // say 32mb), the bug does not manifest so often, but the stack
   // trace is a bit different.
  val insanelyHugeData = Array.ofDim[Byte](1024*1024*128)

  {
    var i = 0
    while (i < insanelyHugeData.length) {
      insanelyHugeData(i) = ('0' + i).toByte
      i = i+1
    }
    insanelyHugeData(insanelyHugeData.length - 1) = '-' // end marker
  }

  def main(args: Array[String]): Unit = {
    val server = new Server

    val connector = new ServerConnector(server, new HttpConnectionFactory(new HttpConfiguration()))
    connector.setPort(5555)

    val context = new ServletContextHandler
    context.setContextPath("/")
    context.addServlet(new ServletHolder(servlet), "/")

    server.addConnector(connector)
    server.setHandler(context)

    server.start()
  }

  val servlet = new Http4sServlet(
    service      = HttpService {
      case req@GET -> Root => Ok(insanelyHugeData)
    },
    servletIo    = org.http4s.servlet.NonBlockingServletIo(4096)
  )
}
```

**Comment by hvesalai** [comment]
To test it, start the server and wget/curl/etc from port 555

Note: the insanelyHugeData is huge because if you test on localhost, the transmission speed is very high. Alternatively you could test over physical network or using a slow client and then the bug would manifest with much smaller data.

**Comment by bryce-anderson** [comment]
This issue should close itself once we release 0.11.1. Thanks @hvesalai for digging through it and providing such helpful samples!

**Comment by hvesalai** [comment]
@bryce-anderson very good! Is there any estimate on when it might be released? We are keen to get the fix so we can start using NIO.

**Comment by bryce-anderson** [comment]
Hopefully today sometime after we merge #456.

**Comment by rossabaker** [comment]
Yes, let's release after #456.
