### ISSUE TITLE
Since NIO2 is being deprecated, what should be used as a replacement?

### ISSUE THREAD

**Issue by tovbinm** [http4s/http4s#4572]

**Comment by rossabaker** [comment]
NIO1.  It's always performed better in any benchmark I've thrown at it, and only it has the CVE fix.  If you have a compelling case for NIO2, I'd entertain a PR to blaze that brings it back, but we need the CVE fix ported to it as well.

**Comment by tovbinm** [comment]
NIO1 should be ok in our case. Do I need to do anything special to enable it?

My current code looks like this:
```scala
for {
    routes <- api.routes
    _ <-  BlazeServerBuilder[IO](ec)
            .bindHttp(port, address)
            .withHttpApp(routes.orNotFound)
            .withoutBanner
            .withTcpNoDelay(true)
            .serve
            .compile
            .drain
} yield ExitCode.Success
```

**Comment by rossabaker** [comment]
Nope, NIO1 was already the default for servers.

**Comment by tovbinm** [comment]
Great! Thank you. I will give it a try.
