### ISSUE TITLE
Use Literally

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#4600]
We'll be inheriting this soon from ip4s anyway, so there's no extra dependency liability, and it clean things up for us.

See https://github.com/Comcast/ip4s/pull/261 for an example.

**Comment by kevinmeredith** [comment]
OK to close this, @rossabaker? Or you only close once you cut a release! Thanks

**Comment by rossabaker** [comment]
Close on merge is good.  I just am not as diligent as I ought to be about mopping up.
