### ISSUE TITLE
Flaky test on QueryParam[ZonedDateTime]

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#4615]
```
==> X org.http4s.QueryParamCodecSuite.ZonedDateTime QueryParamCodec: QueryParamCodec.decode . emap(Right) . encode == successNel  0.054s munit.FailException: /home/runner/work/http4s/http4s/tests/src/test/scala/org/http4s/QueryParamCodecSuite.scala:42
41:  checkAll("LocalDate QueryParamCodec", QueryParamCodecLaws[LocalDate])
42:  checkAll("ZonedDateTime QueryParamCodec", QueryParamCodecLaws[ZonedDateTime])
43:

Failing seed: rS0fcc_1Wo96m09wXZinaJ3sOUx5_bZ47DXSr6yUi4E=
You can reproduce this failure by adding the following override to your suite:

  override val scalaCheckInitialSeed = "rS0fcc_1Wo96m09wXZinaJ3sOUx5_bZ47DXSr6yUi4E="

Falsified after 57 passed tests.
> ARG_0: +66127929-10-27T02:18:19+01:00[Europe/Warsaw]
```

**Comment by phongngtuan** [comment]
This one is due to bug in jdk 8 (https://bugs.openjdk.java.net/browse/JDK-8183553) shall we just... ignore it for jdk8?

**Comment by rossabaker** [comment]
Ugh. Yes, I think we can ignore it.  Users in Warsaw in the year 66127929 around the fall Daylight Saving Time change will hopefully not still be on Java 8.

Thanks for finding the cause!

**Comment by phongngtuan** [comment]
it's also failing right now for half of the year but perhaps nobody is using this
1. as a query param, and
2. using the same date formatter we have in test, we have both the ZoneId and the offset (the formatter is only defined in test so I guess nobody is really using it)

**Comment by rossabaker** [comment]
This failed again  It's more serious than I appreciated.  In https://github.com/http4s/http4s/pull/3691, we filtered out `GMT0`.  What if we filtered out every `ZoneId` that is not an instance of `ZoneOffset` on 1.8?

**Comment by phongngtuan** [comment]
`ZoneId.getAvailableZoneIds()` doesn't return offset-based zone ID. It sounds like it should fail more often on jdk8: for anything with daylight saving time

There is 1 comment in the jdk ticket https://bugs.openjdk.java.net/browse/JDK-8066982,

> As a general rule, when transmitting dates and times across a network boundary, the time-zone is not sent at all. As such, the receiving party necessarily places all their trust in the offset. The same should apply here, placing trust in the offset, not the zone (as the offset is a fixed known element, but the zone varies over time). 

How about we generate test cases using offset based `ZoneId` for all jdk and additionally region-based for jdk11 and above? Or some thing along that line, I haven't wrapped my head around the root cause yet

**Comment by rossabaker** [comment]
If I understood the bug right, what you propose should be reliable.

It kind of sucks to declare this property as something to help reason about the code, and then restrict the property on JDK8 because it's buggy and they haven't backported the fix in several years.

Another thing we could do is just disable the property entirely on JDK8.  If people really want to put zoned-date times using a regional time zone in a query parameter -- something I'm not sure any user actually does -- they do so at their own peril, at least until Java 11.  Put a comment on the instance in the scaladoc and call it a day.
