### ISSUE TITLE
`Header.Select` needs a method like `from` that preserves `ParseFailure`s

### ISSUE THREAD

**Issue by zarthross** [http4s/http4s#4706]
I'm working on updating [Rho](https://github.com/http4s/rho/pull/501) to support the new header redesign. One of the issues I've run into is Rho prefers to throw errors for headers that fail to parse, and the new header redesign appears to prefer simply ignoring the errors?

- Can we get a method on `Header.Select` that doesn't convert the `Either` to `Option`?
- Should this same type of method exist on `Headers`?
- Should this method preserve every parse error or just the first in the case of `Recurring`? 
- Would we prefer something like:
   - `List[Header.Raw] => Either[ParseFailure, F[A]]`
   - `List[Header.Raw] => F[Either[ParseFailure, A]`
   - `List[Header.Raw] => EitherNel[ParseFailure, F[A]]`

Happy to submit a PR, just need advice and guidance.

**Comment by rossabaker** [comment]
I think this might be a rare use case for `Ior`, specifically `Ior[NonEmptyList[ParseFailure], F[A]]`.  "Tell me everything you had to throw away, but give me a value if you can."

* On the happy path, we get an `Ior.Right`.
* If it's total garbage, we get an `Ior.Left`.
* If it's a recurring header and m of n are bad, for 0 <  m < n, we'll get an `Ior.Both` with the good values and warnings of what we choked on, and the caller can decide what to do about it.

/cc @SystemFw.  This was all his brainchild.
