### ISSUE TITLE
Move ConnectionManager and PoolManager to blaze-client module.

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#4712]
Ember is using keypool, which is a generally superior solution.  The `ConnectionManager` evolved for blaze and never really generalized, and I don't want to maintain it in the commons moving forward.

Because client can't see blaze-client, I don't think a deprecation cycle is practical, and there are few direct references anyway.

**Comment by vasilmkd** [comment]
I'd like to take this one.
