### ISSUE TITLE
Connection refused / poss SSL handshake stale with Ember Server on 0.21.21

### ISSUE THREAD

**Issue by sbuzzard** [http4s/http4s#4714]
We have been using Ember Server with SSL for our application with no issue until upgrading to 0.21.21  where we started getting connection refused attempting to make requests to our server.  The trace logging indicated that the SSL handshake might be stalling.  This is an [output of that tracing with 0.21.21](https://gist.github.com/sbuzzard/6fcb12f8e1e6692cd5cbec43a3985c6f), contrasted with [0.21.20](https://gist.github.com/sbuzzard/3e310c237792e5e464aba0df752c1a03).  We are using http4s 0.21.21, fs2 2.5.4, cats-effect 2.4.1.

In investigating this issue, we were able to fix it by adding error handling around the new [initial read call](https://github.com/http4s/http4s/blob/series/0.21/ember-server/src/main/scala/org/http4s/ember/server/internal/ServerHelpers.scala#L202), with an `attempt`, similar to the [runApp invocation](https://github.com/http4s/http4s/blob/series/0.21/ember-server/src/main/scala/org/http4s/ember/server/internal/ServerHelpers.scala#L214-L216), so that the stream ends and the socket can be properly closed rather than the stream itself erroring.  A PR is forthcoming.

**Comment by RaasAhsan** [comment]
Closed by #4715
