### ISSUE TITLE
Provide json support for zio-json

### ISSUE THREAD

**Issue by remiguittaut** [http4s/http4s#4718]
As of now, only Circe, Argonaut and Json4s (might have, correct me if I'm wrong) are supported to handle json with http4s.

It would be very helpful to have zio-json support.

**Comment by remiguittaut** [comment]
Actually, there are others, like play-json it seems. Just mentioned the ones in the doc.

**Comment by rossabaker** [comment]
We are not integrating that ecosystem under http4s.org.

**Comment by remiguittaut** [comment]
I have no word.... well so be it.

**Comment by kubukoz** [comment]
@rossabaker why? Are there any technical reasons for this?

**Comment by remiguittaut** [comment]
No, it's political, whatever that has to do with json...

**Comment by ChristopherDavenport** [comment]
The maintainers do not want to promote an ecosystem we believe is inconsistent with our values. There's plenty of history available for folks that want more information but that's off topic.
