### ISSUE TITLE
Provide mountFilter on JettyBuilder

### ISSUE THREAD

**Issue by prange** [http4s/http4s#472]
Filters are handy when dealing with http. You should add mountFilter on JettyBuilder, and maybe alspo a similar mechanism om the Blaze server.

**Comment by rossabaker** [comment]
The portable mechanism is composition via server middlewares (a function of one HttpService to another).

The non-portable mechanism, which is handy in legacy scenarios, is to apply a javax.servlet.ServletFilter.  That's what would make sense on ServletBuilder, inherited by JettyBuilder and TomcatBuilder.

**Comment by bryce-anderson** [comment]
:+1: to adding this to `ServletBuilder`. I agree that middleware is the solution to this class of problems for those interested in using the blaze backend.
