### ISSUE TITLE
Rename modules to jetty-server and tomcat-server

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#4744]
`jetty` has been `jetty` since before we had a `client`, but now we have a `jetty-client`, so it really ought to be called `jetty-server`.

And everything else is `*-server` or `*-client`, so Tomcat ought to be `tomcat-server`, too.

(Reminded of this by @vasilmkd's comment on #2702.)

I don't think we can scalafix an sbt script.  Fortunately, these modules are both <10% usage.  We'll just have to scream in the release notes.

**Comment by vasilmkd** [comment]
I'll take this if you don't mind.
