### ISSUE TITLE
Don't hide errors.

### ISSUE THREAD

**Issue by hvesalai** [http4s/http4s#478]
We are still (after the fixing of issues #459 and #454) having problems with the NIO-mode of http4s servletIo. This time we don't know where the problem is, but the symptom is that things just hang.

To help us debug it, we need http4s to stop hiding errors. For example https://github.com/http4s/http4s/blob/master/servlet/src/main/scala/org/http4s/servlet/ServletIo.scala#L153 will loose data without a trace if `out.isReady` is false. I think the implementor has meant to say that it will never be false (since writeChunk is called only when the OutputStream should be ready), but this is not reflected in the code. It should throw an exception or at least alog the failure of the "assertion" in an else block.

**Comment by hvesalai** [comment]
I'll make a pull request if you agree with my analysis.

**Comment by bryce-anderson** [comment]
I agree with your analysis: if `out.isReady` should never evaluate to `false` we should not need the `if` statement.

I suspect you're using `servlet` intentionally but if not, maybe the blaze backend would work better for you.

**Comment by bryce-anderson** [comment]
BTW in the past I've noticed that the behavior of different servlet implementations (specifically jetty and tomcat) tend to have subtle differences. It might be helpful to know which implementation you're using.

**Comment by hvesalai** [comment]
We're using jetty... and the problem might well be in our code, but since I'm not sure, I'm shooting everything that moves.
