### ISSUE TITLE
integrations.md looks bad

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#4804]
As [reported](https://github.com/http4s/http4s/pull/3712#issuecomment-827904787) by @LeifW:

> Things like :white_check_mark: look nice on the GitHub markdown, but they're not rendered on the actual site:
https://http4s.org/v1.0/integrations/

**Comment by armanbilge** [comment]
Subjective, I reckon it looks pretty good now.
https://http4s.org/v0.23/docs/integrations.html
