### ISSUE TITLE
Blaze Client racy write/EOF retry

### ISSUE THREAD

**Issue by RaasAhsan** [http4s/http4s#4809]
Two aspects of how Blaze Client operates:
1. Blaze Client writes a request and reads a response concurrently when called.
2. If Blaze Client observes an EOF when reading a response, it will open a new connection and retry the request.

This implementation admits the following execution:
1. Client submits a request. The request write is started concurrently, and the response read begins on the current fiber.
2. The write is completed and the server processes the request.
3. For whatever reason, before returning a response, the server closes the connection. This could be because of an idle timeout, a max connection age, or a server shutdown.
4. The client initiates the read and observes that the peer closed the connection. It then establishes a new connection and retries the request.

So, what happened here is that the client has opaquely retried the request in such a way that the server processes it twice. This is really dangerous for non-idempotent operations! In practice, I think seeing this execution path is unlikely because most HTTP servers are usually well-behaved and the timing is really unlikely, but the Internet is a wilderness and our client code doesn't eliminate it either.

**Comment by RafalSumislawski** [comment]
That's exactly what happened to me in the issues I described in #4796

I've hacked a bunch of tests which reproduce this behaviour here. The most interesting one being this one https://github.com/RafalSumislawski/http4s/blob/blaze-half-closed-connection-issue/blaze-client/src/test/scala/org/http4s/client/blaze/BlazeIssues.scala#L135 which demonstrates how blaze-client may keep retrying unbounded number of times, taking unbounded amount of time.

In my opinion the best solution to this issue is a complete removal of the retry mechanism.

**Comment by RaasAhsan** [comment]
@RafalSumislawski One thing I noticed was that there is an execution Blaze _does_ respond to the FIN/ACK handshake gracefully without a RST packet. The client write and read happens concurrently as described above, so if the read sees an EOF and closes the socket before the write happens, no RST is sent through. It's racy so it doesn't always happen, and the connection also sits idle in the pool for that time like you described

Does that sound right to you ?

**Comment by RafalSumislawski** [comment]
Yes. That sound right. I was testing this a lot today (and on a different machine than before), and indeed, sometimes the scenario with no RST takes place.

**Comment by RafalSumislawski** [comment]
I don't think the racyness is the core issue. I mean, we're dealing with network communication, the FIN from the server can come at any time and race with things happening locally. IMO the core problem is that blaze retries something that cannot be (or at least we cannot assume that it can) safely retried.

**Comment by RaasAhsan** [comment]
Yeah exactly, I don't think it's possible to eliminate this case exhaustively for that reason. However, I feel like we should be able to detect the scenario where a half-closed connection is sitting idle in the connection pool (which your PR should handle). 

For some context, in Ember, the read and write are linearizable; first the entire response is written, then the read is performed, which is why the `Connection reset by peer` error is raised when you try to use a half-closed connection. I was thinking we could perform a zero-byte read before submitting a request to detect a closed connection. It's a best attempt 
so it doesn't cover every corner case (particularly when the FIN comes as you're writing), but do you think that's a reasonable approach?

**Comment by RafalSumislawski** [comment]
I think there's no point fighting FIN during write edge-case, so in that area this is fine. 

In principle reading before writing to detect EOF makes sens. I see the following potential issues:
- I'm not sure how the channel will behave when you'll ask it for zero bytes. Will it complete immediately if the connection is still open and there is no data?
- That zero byte read is additional system call. That will hurt performance.
- I assume that zero byte read will happen after borrowing the connection from the pool, so you're going to have to dispose this connection and then borrow another. Not a big issue but it complicates the flow.

To be clear, I'm not saying it won't work. It just worth to consider the above points when designing/implementing the solution.

**Comment by RaasAhsan** [comment]
👍  All great points. IIRC reading zero bytes from a nonblocking socket should return immediately, either returning 0 bytes or a -1 status code if it reached EOF, but there's definitely testing to be done to validate that. For control flow, we could definitely avoid the extra read by implementing a concurrent state machine like in your PR, so I'll figure out what both approaches look like and gauge if it's better to go that route first, or as a follow up. Thanks !

**Comment by RafalSumislawski** [comment]
> which demonstrates how blaze-client may keep retrying unbounded number of times, taking unbounded amount of time.

Correction:
The time is bounded by the `requestTimeout` (if it's enabled)
