### ISSUE TITLE
Ember Client keeps half-closed connection after server sends FIN-ACK through an idle connection

### ISSUE THREAD

**Issue by RafalSumislawski** [http4s/http4s#4811]
See the analysis in #4798 (which shows that ember exhibits the same problematic behaviour as blaze)

**Comment by RaasAhsan** [comment]
I've been putting together a fix for the related #4805 which has plagued Ember Client for a long time now, but I think fixing that should fix this issue as well

**Comment by RaasAhsan** [comment]
Closed by #5064
