### ISSUE TITLE
Intermittent premature cancelation of requests due to idle timeout

### ISSUE THREAD

**Issue by andybryant** [http4s/http4s#4829]
We have a service running Http4s Blaze Server 0.21.22 using ZIO 1.0.7 as our effect system.
The last week or two we've seen 3 or 4 requests every hour being cancelled part way through. In ZIO this causes the effect to be interrupted. Turning debug logging on for http4s, we were able to see this was being caused by the idle timeout 

>Idle timeout after 60000 ms.
>Shutting down due to idle timeout

This was happening for requests running for much less that 60 seconds. Some only 100ms or so.
Disabling the idle timeout by setting it to `Duration.inf` made the issue go away completely.

Looking more closely at the logs, and by adding some extra debug logging, it appears the issue is around HTTP 1.1 clients keeping the connection open between requests. If the second request comes in just prior to the idle timeout, and does not have a body to parse, we could see it did not trigger `IdleTimeoutStage` to reset its timer.

This issue was particularly problematic for us as we had a number of scheduled tasks being trigger by Google Cloud Scheduler often timed to happen one minute apart. Cloud Scheduler sends POSTs with no body and our idle timeout was set to 60 seconds.

It seems the solution would be to trigger `IdleTimeoutStage` to reset its timer at the start of reading any request headers, and not wait for incoming or outgoing data.

**Comment by rossabaker** [comment]
@RafalSumislawski has been doing a lot of work on idle timeouts and might know offhand a ticket that already addresses this.

**Comment by RafalSumislawski** [comment]
Hi @andybryant 
I address this issue in #4796. The fix is planned for release 0.21.23.

**Comment by andybryant** [comment]
@rossabaker Minor point - the label should be module:blaze-server not blaze-client

**Comment by rossabaker** [comment]
Oops! Thanks.
