### ISSUE TITLE
Don't serve subsequent requests after an incomplete response

### ISSUE THREAD

**Issue by hvesalai** [http4s/http4s#485]
If a buggy service explicitly sets the Content-Length header, but then doesn't give enough bytes, http4s will still happily service other requests from the same connection. This will result in the pipelining client seeing the response to the second request as belonging to the first.

For example given this service

```
case req @ GET -> Root / "incomplete" =>
      val data = "incomplete"

      Ok(data.dropRight(1)).putHeaders(`Content-Length`(data.length))
```

Http4s with blaze server will not close the connection after the incomplete response:

```
hvesalai@lume:~/projects/http4s (codereview2)$ telnet localhost 8080
Trying ::1...
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
GET /http4s/incomplete HTTP/1.1
Host: localhost

HTTP/1.1 200 OK
Content-Type: text/plain; charset=UTF-8
Content-Length: 10
Date: Mon, 28 Dec 2015 12:09:12 UTC

incompletGET /http4s/incomplete HTTP/1.1
Host: localhost

HTTP/1.1 200 OK
Content-Type: text/plain; charset=UTF-8
Content-Length: 10
Date: Mon, 28 Dec 2015 12:09:26 UTC

incomplet
```

__Note: responses to HEAD requests need to be handled so that a Content-Length headers are passed through and the connection is re-used even if there is no entity-body.__

**Comment by hvesalai** [comment]
... so the client would have seen two responses. The first one would have been

```
HTTP/1.1 200 OK
Content-Type: text/plain; charset=UTF-8
Content-Length: 10
Date: Mon, 28 Dec 2015 12:09:12 UTC

incompletH
```

and the second one

```
TTP/1.1 200 OK
Content-Type: text/plain; charset=UTF-8
Content-Length: 10
Date: Mon, 28 Dec 2015 12:09:26 UTC

incomplet
```

which would ofcourse have resulted in either a protocol error (since the protocol string is `TTP/1.1`) or a timeout (witing for last byte of second request).

**Comment by bryce-anderson** [comment]
Indeed, this seems like an issue that may happen if someone explicitly shoots themselves in the foot.

I can see this being handled by the `ProcessWriter` here: https://github.com/http4s/http4s/blob/master/blaze-core/src/main/scala/org/http4s/blaze/util/IdentityWriter.scala#L22

Just Change that to
```scala
override def requireClose(): Boolean = size < 0 || bodyBytesWritten != size
```
(Strictly speaking the second part would be sufficient as bodyBytesWritten will always be <= 0, but I think it helps to document the behavior documenting the behavior in the case of unknown message sizes)

**Comment by bryce-anderson** [comment]
I suspect the second condition would also warrant a warning or error log entry in the `writeEnd` function.

**Comment by hvesalai** [comment]
An other idea would be to change the `writeEnd` to return `Future.failed` if the last chunk was not enough to fulfill the request. I think this would be a cleaner approach.

**Comment by hvesalai** [comment]
(and ofcourse I expect that somebody closes the connection if a write fails)

**Comment by bryce-anderson** [comment]
I don't see a reason not to do both.

**Comment by hvesalai** [comment]
I'll make a PullRequest of my suggestion. While I don't see any real problem with the `requireClose` solution, I don't like how its value changes from one chunk to the next.

**Comment by bryce-anderson** [comment]
I like the 'both' solution: a short body should _require_ the connection be
closed so I would like to see the return value of `requireClose` predicated
on writing a complete body. I also think the `writeEnd` should result in a
`Failure` if it doesn't get enough bytes.

On Mon, Dec 28, 2015 at 9:49 AM, Heikki Vesalainen <notifications@github.com
