### ISSUE TITLE
Link from homepage for 0.23 is broken

### ISSUE THREAD

**Issue by ScalaWilliam** [http4s/http4s#4877]
![image](https://user-images.githubusercontent.com/2464813/119421652-19c1b000-bcf7-11eb-8071-50b243c5d04b.png)

**Comment by rossabaker** [comment]
Thanks.  Sonatype [failed to clean up](https://github.com/http4s/http4s/runs/2642305725?check_suite_focus=true), so the build crashed before the website publish ran.

This should resolve itself when we publish the RC, which is only waiting on Circe.  If that doesn't happen in the next 24 hours or so, I'll figure out a manual publish.

**Comment by rossabaker** [comment]
It's worse that I thought.  We haven't ported the docs to Cats-Effect 3.  :grimacing:

**Comment by rossabaker** [comment]
The content is there, but the styling is not.  I think it's the baseUrl, but I'm exhausted. :zzz:

**Comment by rossabaker** [comment]
It looks fine now.  I guess it took Netlify a while to sync.
