### ISSUE TITLE
Replace Defer constraints with Concurrent

### ISSUE THREAD

**Issue by mpilquist** [http4s/http4s#4883]
In 1.0.x, `AuthedRoutes` currently requires an instance of `Defer[F]`. This causes ambiguous implicits since `Concurrent[F]` is typically in scope and as of CE3, `Concurrent` is unrelated to `Defer`.

Per @ChristopherDavenport, these `Defer` usages should be replaced with `Concurrent.unit.flatMap(_ => ...)`. We should check for all such `Defer` constraints, not just `AuthedRoutes`.

**Comment by hamnis** [comment]
Fixed by https://github.com/http4s/http4s/commit/d3e7f85dbad19062f2b9757ddcb11a3e74102748
