### ISSUE TITLE
value blaze is not a member of org.http4s.server

### ISSUE THREAD

**Issue by psylinse** [http4s/http4s#4892]
I'm hitting the above error on scala 3. Here is a minimal repro: https://github.com/psylinse/zio-scala-3-error

Sorry if I'm missing something obvious, I'm relatively new to scala/scala 3!

**Comment by qwbarch** [comment]
I believe the packages were slightly changed for consistency.
Try using ``import org.http4s.blaze.server.BlazeServerBuilder``

**Comment by psylinse** [comment]
Ah, that's it thank you!
