### ISSUE TITLE
Support Unicode in the Content-Disposition filename

### ISSUE THREAD

**Issue by nigredo-tori** [http4s/http4s#4914]
At the moment, this attribute is [sanitized](https://github.com/http4s/http4s/blob/6227ad21e0ddc372e433d279a7cdde387b0b0e3e/core/src/main/scala/org/http4s/headers/Content-Disposition.scala#L100), meaning that international filenames are mangled. We should support the `filename*` version of this attribute, with the encoding described in [RFC 8187](https://datatracker.ietf.org/doc/html/rfc8187). As per [RFC 6266, Appendix D](https://datatracker.ietf.org/doc/html/rfc6266#appendix-D):

> - Include a "filename*" parameter where the desired filename cannot
be expressed faithfully using the "filename" form.  Note that
legacy user agents will not process this, and will fall back to
using the "filename" parameter's content.
> - When a "filename*" parameter is sent, to also generate a
"filename" parameter as a fallback for user agents that do not
support the "filename*" form, if possible.  This can be done by
substituting characters with US-ASCII sequences (e.g., Unicode
character point U+00E4 (LATIN SMALL LETTER A WITH DIARESIS) by
"ae").  Note that this may not be possible in some locales.

**Comment by nigredo-tori** [comment]
Nevermind, it seems this was [addressed](https://github.com/http4s/http4s/pull/4604) back in March, but not in the 0.21 branch.

**Comment by rossabaker** [comment]
I'm not actively backporting anymore, but on quick scan, this could be if the header parameters weren't made case insensitive.  I'd do a release if there's a bin-compat PR.

I also expect to release 0.22.0 and 0.23.0 this weekend.
