### ISSUE TITLE
Ember Server - Delayed Processing with TLS Requests

### ISSUE THREAD

**Issue by etspaceman** [http4s/http4s#4934]
I switched my [kinesis-mock](https://github.com/etspaceman/kinesis-mock/pull/115) to use the Ember backend per a discussion w @djspiewak and @ChristopherDavenport. After doing so, one of my functional tests started failing non-deterministically: https://github.com/etspaceman/kinesis-mock/blob/main/src/fun/scala/kinesis/mock/DescribeStreamSummaryTests.scala#L42-L56

This will run 11 requests in parallel and check the response. In successful iterations, this test takes about 1.5 seconds in total (including the test setup). In the failed scenarios, it times out after 30 seconds. 

I did some research into what is happening. Attached the logs from one of my [CI runs](https://github.com/etspaceman/kinesis-mock/actions/runs/954693299). If you do a search for "2021-06-20 15:50:14", you'll find the logs from the server when the test starts. 10 of the 11 streams get processed at this timestamp. stream7, however, isn't processed until "2021-06-20 15:50:45". So almost exactly 30 seconds later. 

There is a `ShutdownTimeout` in Ember that is set to 30 seconds, which might be a clue. I'm kind of grasping at straws here though.

I have also only seen this on TLS enabled servers. Might be a coincidence. I'll mention if I see it on a plain-text server. 

[6_Print Docker Logs.txt](https://github.com/http4s/http4s/files/6682761/6_Print.Docker.Logs.txt)

**Comment by etspaceman** [comment]
I've started witnessing this issue on non-parallel tests as well. So far this is only occurring on the TLS server so I'm betting it has to do with the TLS setup in http4s.

**Comment by RaasAhsan** [comment]
@etspaceman just to validate the 30 second shutdown timeout theory, could you maybe raise or lower that to another value and see if the processing time changes ?

**Comment by djspiewak** [comment]
Random thought: given that this is CE2, we probably have to consider fairness here. Anything that bounces into TLS land would hold a thread for a long period of time. 30 seconds though does seem a bit extreme.

**Comment by etspaceman** [comment]
That is a good callout @djspiewak - I'm using ExecutionContext.global in Blaze but not in Ember (which would use the fixedThreadPool from IOApp). That would explain a couple of things:

- Why its only showing up in the Ember server
- Why I cant recreate it locally

**Comment by etspaceman** [comment]
I believe this was resolved with a recent update from FS2. Closing.
