### ISSUE TITLE
Doc: Cannot load 1.0 documentation pages

### ISSUE THREAD

**Issue by dontpanic92** [http4s/http4s#4960]
It looks like we have wrong hostname here:

https://github.com/http4s/http4s/blob/4696d23c7ed07e904bf4462daa9624272b475f2b/v1.0/index.html#L9-L14

**Comment by rossabaker** [comment]
I think we might have published that one locally.  I'd expect the next milestone, which is imminent, to clean it up.

**Comment by armanbilge** [comment]
All good now.
