### ISSUE TITLE
Header value is always parsed, even if name does not match

### ISSUE THREAD

**Issue by ziggystar** [http4s/http4s#4971]
As the argument to `as` is passed by value, the parser is always executed, for every header field, regardless of a matching name.

https://github.com/http4s/http4s/blob/399453460889a144aee83cafea6ef91cac6c917f/core/src/main/scala/org/http4s/Header.scala#L185

The line should probably read

     (h.name == Header[A].name).guard[Option].map(_ => Header[A].parse(h.value).toIor)

**Comment by aeons** [comment]
Good catch :)

This was fixed for `series/0.22` in #4933
