### ISSUE TITLE
Scalaz: 7.1, 7.2, or both?

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#499]
functional-streams-for-scala/fs2#519 may soon be bringing us a Scalaz 7.2 port of scalaz-stream.  This is a moot point after fs2, but we've had questions about this on Gitter.

Options for us:
1) Stay the course on Scalaz 7.1 until fs2 is released and we've resolved #390.
2) Upgrade to Scalaz 7.2 and leave 7.1 behind.
3) Branch and support both versions of Scalaz.

The third is palatable to me only if Travis CI can carry most of the work.  I don't have a strong opinion on the first two options, though different outcomes to #390 would tilt my opinion one direction or the other.

**Comment by ngbinh** [comment]
Many libraries we are using already upgraded to Scalaz 7.2 (monocle, scalacss,...), I really wish for a quick update to Scalaz 7.2. Currently, http4s is the only dependency that blocking us from upgrading.

**Comment by rossabaker** [comment]
Thanks. Also willing to hear arguments for why dropping 7.1 might be painful.

**Comment by bryce-anderson** [comment]
What are our biggest impediments (other than lack of free time) to the upgrade? I think `NonEmptyList` is the only thing that really stands out to me. Is it to unpalatable to just use `List` with a documentation promise that its not empty? Alternatively we could try using the `::` type since it is, in fact, a non-empty list:
```scala
type NonEmptyList[A] = ::[A]
object NonEmptyList[A] {
  def apply(a: A, as:A*): NonEmptyList[A] = new ::(a, as.toList)
  ...
}
```
There may be unforeseen fallout due to the invariance in the `::[A]` type param and the type signatures of the helper functions (`map` etc).

**Comment by refried** [comment]
@rossabaker As of today, https://github.com/tpolecat/doobie is still on 7.1.
@bryce-anderson Do you mean how 7.1's `NonEmptyList` is built around `List` vs around `IList`?  Not a fan of `::` because the type signatures on `map`, etc.

**Comment by bryce-anderson** [comment]
@refried: correct.

**Comment by aaubert** [comment]
Argonaut is also still using 7.1, and http4s uses jawn-argonaut which itself uses argonaut.

**Comment by rossabaker** [comment]
Ah, yes, good catch. Argonaut master is decoupling from Scalaz, but there is no release that does so yet.

I guess that means a 7.2-based release temporarily loses Argonaut support.

**Comment by lukasz-golebiewski** [comment]
Argonaut already supports scalaz 7.2.0 in a snapshot build as seen on https://github.com/argonaut-io/argonaut
> Note that the 6.2 development stream supports scala 2.10.* and 2.11.* with scalaz 7.2.*.

**Comment by ngbinh** [comment]
https://github.com/functional-streams-for-scala/fs2/pull/532 is merged. So we will have a SNAPSHOT version for fs2 soon.

**Comment by rossabaker** [comment]
I just pushed a topic/one-and branch that shows the main complication of upgrading to 7.2.  It all seems to flow from the change in `NonEmptyList` from `List` to `IList`.

* If we continue to use `NonEmptyList`, 7.1 and 7.2 branches will diverge.  I am a lot more enthused about this if we can do it through a build matrix and keep the same source tree.
* If we use `OneAnd` to stick with the `List` backing, we lose some important methods like `.list`.  They aren't hard to implement, but it's not native to the type.
* Note that cats' `NonEmptyList` is a type alias for a richer `OneAnd` than scalaz provides.  But cats isn't on the table until fs2.

**Comment by rossabaker** [comment]
More observations:
* There is a whole lot of deprecation, including common operations on `Task`.
* I needed to provide syntax to make `OneAnd` usable.  The same would be true for `NonEmptyList`.

I think this is pointing toward two source trees unless we abandon 7.1.x or skip 7.2.x.

**Comment by rossabaker** [comment]
topic/non-empty-list shows what scalaz-7.2 does to our NonEmptyLists.

@bryce-anderson has floated the idea of dropping it in favor of a simple `List`.  That avoids all the problems introduced by `IList`, and the breaking change in Scalaz.  We can enforce the non-emptiness with private case class constructors and the appropriate apply methods.  The biggest downside is that the type becomes less self-documenting.  A lesser downside is that it permits extractors that can't match.  I think I like this approach if we're going to support 7.1 and 7.2.  For 7.2 only, it's more debatable.

**Comment by rossabaker** [comment]
And cf8cd20 reverts to a List.  The NonEmptyList guided us toward correctness where we now have to reason about it ourselves more often than I imagined.  Retaining the contravariance came in handy in a few places.

**Comment by refried** [comment]
I'm kinda sad about dropping `NonEmptyList`, and have been facing this issue (NonEmpty List? IList? List with/without Equal/Order constraints?).  My approach was to split out some OneAnd data structures into a separate library with optional scalaz or cats adapters.  I had planned to include all the combinations, but so far have only implemented the ones I'm using.  They would have `.list` and other native methods as needed.

**Comment by rossabaker** [comment]
Is doobie compatibility the only thing keeping us on scalaz-7.1?  The tentative plan is for doobie-0.3 to jump to scalaz-7.2.  If that's the case, I'm inclined to say we just keep it simple, move to scalaz-7.2 in 0.13.x, and have our scalaz-cats day of reckoning when fs2 is ready.

**Comment by bryce-anderson** [comment]
:+1: To keeping it simple, for now.

**Comment by rossabaker** [comment]
I don't know how many people are already on an 0.13.0-SNAPSHOT, so here's the plan:

* 0.13.x will be the final release on Scalaz-7.1.
* 0.14.x will require Scalaz-7.2.

I don't want to maintain both branches for long, so 0.13.x will be released soon, but we'll start publishing snapshots for 0.14.x now.
