### ISSUE TITLE
Be Consistent About Providing An Ordering Instance

### ISSUE THREAD

**Issue by isomarcte** [http4s/http4s#5017]
We sometimes have data types which subtype `Ordered` and other times have types which implement `Ordering`. We only _need_ to do `Ordering`. We should ensure that all types which are `Ordered` also have an `Ordering` instance.

Context: https://github.com/http4s/http4s/pull/5013#discussion_r682655331

**Comment by rossabaker** [comment]
@san-coding This is a good one.  `HttpDate` is an example: it extends `Ordered`, but we'd rather have an `Ordering` instance.  Are you familiar with the two types?

**Comment by san-coding** [comment]
I am not familiar yet, but will look into it, thanks @rossabaker

**Comment by san-coding** [comment]
@rossabaker , I can see that some classes inherit `ordered`

**Comment by isomarcte** [comment]
@san-coding if a class is already extending `Ordered`, we need to leave it that way, at least for now. This is so we don't break binary compatibility. 

In the context of this ticket, any type in http4s which is currently only extending `Ordered` should also have an implicit `Ordering` added, and they should be consistent with each other.

Hopefully, most of the types which are extending `Ordered` have a `cats.kernel.Order` instance. If they do, then adding the `Ordering` is very simple. For example, 

```scala
final case class Foo(bar: Int) extends Ordered[Foo] {
    override final def compare(that: Foo): Int = 
      // Ordered derived from cats Order instance
      Order[Foo].compare(this, that)
}

object Foo {
    implicit val catsOrderInstanceForFoo: Order[Foo] = new Order[Foo] {
      override def compare(x: Foo, y: Foo): Int = x.bar.compare(y.bar)
    }
    
    // scala Ordering derived from cats Order
    implicit val stdLibOrderingInstance: Ordering[Foo] = catsOrderInstanceForFoo.toOrdering
}
```

If they don't have a `cats.kernel.Order` instance (which you are free to add as well if you'd like, or not, either way), as in the case of `HttpDate`, then we'd do something like this.

```scala
class HttpDate private (val epochSecond: Long) extends Renderable with Ordered[HttpDate] { /* elided */ }

object HttpDate {
    implicit val stdLibOrderingInstance: Ordering[HttpDate] = /* Ordering definition */
}
```

For the sake of consistency, I'd also probably make the `compare` method from `Ordered` and the `equals` method (if it's not a case class) use the underlying `Ordering` instance. Something like,


```scala
class HttpDate private (val epochSecond: Long) extends Renderable with Ordered[HttpDate] { 
  override def compare(that: HttpDate): Int = 
    Ordering[HttpDate].compare(this, that)
    
  override def equals(o: Any): Boolean = 
    o match {
      case that: HttpDate => Ordering[HttpDate].compare(this, that) === 0
      case _ => false
    }
```

That was a lot of text...let me know if that makes sense and don't hesitate to reach out if you have questions.

**Comment by san-coding** [comment]
Thanks @isomarcte  for such a detailed explanation

**Comment by san-coding** [comment]
hey @isomarcte @rossabaker , this file doesn't extend `Ordered`, neither does it have `cats.kernel.Order` , but it has `Ordering` instance


https://github.com/http4s/http4s/blob/a942a83e2b88bafc644fc9916fd1979eb951ced8/core/shared/src/main/scala/org/http4s/RequestPrelude.scala#L25-L29


https://github.com/http4s/http4s/blob/a942a83e2b88bafc644fc9916fd1979eb951ced8/core/shared/src/main/scala/org/http4s/RequestPrelude.scala#L118-L119

**Comment by isomarcte** [comment]
@san-coding it does have an `Order`.

https://github.com/http4s/http4s/blob/a942a83e2b88bafc644fc9916fd1979eb951ced8/core/shared/src/main/scala/org/http4s/RequestPrelude.scala#L102

The signature is a bit different because both `cats.kernel.Hash` and `cats.kernel.Order` extend `cats.kernel.Eq`. To avoid ambiguous implicit issues, the implementation for both `Hash` and `Order` have to be the same concrete value.

**Comment by san-coding** [comment]
Now I understand what to do , so whichever class extend `Ordered` and has `cats.kernel.Order`  instance, I should add an `implicit Ordering`  like this
```    
Object Foo {
}
implicit val stdLibOrderingInstance: Ordering[Foo] = catsOrderInstanceForFoo.toOrdering
```
When we don't have a `cats.kernel.Order` 
We can add `implicit Ordering` like this :
``` 
object className/traitName {
    implicit val stdLibOrderingInstance: Ordering[className/traitName] = /* Ordering definition */
}
```
For example , 
In this file I can see that it has :
https://github.com/http4s/http4s/blob/c17d2df0ce972247a5d77486f9b6fe220ecc4a68/client/jvm/src/main/scala/org/http4s/client/oauth1/ProtocolParameter.scala#L21

But this trait is not extending `Ordered` (So the classes that extend/mix this `trait`, should also extend `Ordered` ? )  
https://github.com/http4s/http4s/blob/c17d2df0ce972247a5d77486f9b6fe220ecc4a68/client/jvm/src/main/scala/org/http4s/client/oauth1/ProtocolParameter.scala#L27

Okay, maybe it does have  `Order` , bit confused with the signature
https://github.com/http4s/http4s/blob/c17d2df0ce972247a5d77486f9b6fe220ecc4a68/client/jvm/src/main/scala/org/http4s/client/oauth1/ProtocolParameter.scala#L88-L92

But I can see that it doesn't have any `Ordering` instance , so should I go ahead an add it like this ?
https://github.com/http4s/http4s/blob/c17d2df0ce972247a5d77486f9b6fe220ecc4a68/client/jvm/src/main/scala/org/http4s/client/oauth1/ProtocolParameter.scala#L88-L92
    
###   `Ordering` instance that I have to add outside the object (below the above lines of code)
```
 implicit val stdLibOrderingInstance: Ordering[ProtocolParameter] = http4sClientOauth1SortForProtocolParameters.toOrdering

```
## Am I correct ? , is the syntax correct ?

**Comment by rossabaker** [comment]
> Thanks @isomarcte @rossabaker , Now I understand what to do , so whichever class extend `Ordered` and has `cats.kernel.Order`  instance, I should add an `implicit Ordering`  like this
> ```    
> Object Foo {
> implicit val stdLibOrderingInstance: Ordering[Foo] = catsOrderInstanceForFoo.toOrdering
> }
> ```

That works.  I think you could alternatively extend `Ordering` in the same value that extends `Order`, since the signatures are the same, but I've never seen it done that way.  Maybe @isomarcte knows why not.

> But this trait is not extending `Ordered` (So the classes that extend/mix this `trait`, should also extend `Ordered` ? )  

I would not add any more `Ordered`s.  As @isomarcte notes, those need to remain for binary compatibility, but we shouldn't propagate it.

> But I can see that it doesn't have any `Ordering` instance , so should I go ahead an add it like this ?

When you have a `cats.kernel.Order`, you can get `Ordering` just like what's described at the top of this comment.

**Comment by san-coding** [comment]
> > Thanks @isomarcte @rossabaker , Now I understand what to do , so whichever class extend `Ordered` and has `cats.kernel.Order`  instance, I should add an `implicit Ordering`  like this
> > ```
> > Object Foo {
> > implicit val stdLibOrderingInstance: Ordering[Foo] = catsOrderInstanceForFoo.toOrdering
> > }
> > ```
> 
> That works. I think you could alternatively extend `Ordering` in the same value that extends `Order`, since the signatures are the same, but I've never seen it done that way. Maybe @isomarcte knows why not.
> 
> > But this trait is not extending `Ordered` (So the classes that extend/mix this `trait`, should also extend `Ordered` ? )
> 
> I would not add any more `Ordered`s. As @isomarcte notes, those need to remain for binary compatibility, but we shouldn't propagate it.
> 
> > But I can see that it doesn't have any `Ordering` instance , so should I go ahead an add it like this ?
> 
> When you have a `cats.kernel.Order`, you can get `Ordering` just like what's described at the top of this comment.

Ok thanks , I will make a PR for the `ProtocolParameter` and `HttpDate` , and I will look for what all files / classes need to implement `Ordering` Instance , any idea how I can find all those classes which need `Ordering` Instance , should I search manually ?

**Comment by san-coding** [comment]
Having a separate PR for each class that needs `Ordering` instance would be better right?

**Comment by san-coding** [comment]
What should be the Ordering definition for HttpDate , because I don't see a statement like this anywhere

```
 implicit val http4sClientOauth1SortForProtocolParameters: Order[ProtocolParameter] = 
```

```
class HttpDate private (val epochSecond: Long) extends Renderable with Ordered[HttpDate] { /* elided */ }

object HttpDate {
    implicit val stdLibOrderingInstance: Ordering[HttpDate] = WHAT.toOrdering
}


```

**Comment by san-coding** [comment]
Meanwhile I  will go ahead and add a PR for `ProtocolParameter`

**Comment by san-coding** [comment]
@isomarcte @rossabaker , thanks for the guidance and detailed explanations, I have added `Ordering` instance to `ProtocolParameter` trait  , can you review if whatever I have done is correct ?

**Comment by san-coding** [comment]
> @rossabaker @isomarcte
> What should be the Ordering definition for HttpDate , because I don't see a statement like this anywhere
> 
> In the case of `ProtocolParameter` , we have
> 
> ```
>  implicit val http4sClientOauth1SortForProtocolParameters: Order[ProtocolParameter] = 
> ```
> 
> in the above case I can define `Ordering` instance like this :
> 
> ```
> implicit val stdLibOrderingInstance: Ordering[ProtocolParameter] = http4sClientOauth1SortForProtocolParameters.toOrdering
> ```
> 
> But in the case of HttpDate , how do I define `Ordering` instance
> 
> ```
> class HttpDate private (val epochSecond: Long) extends Renderable with Ordered[HttpDate] { /* elided */ }
> 
> object HttpDate {
>     implicit val stdLibOrderingInstance: Ordering[HttpDate] = WHAT.toOrdering
> }
> ```
> 
> Should It be `epochSecond.toOrdering`

@isomarcte @rossabaker @hamnis could you clear this doubt whenever you have time ?

**Comment by san-coding** [comment]
@isomarcte @rossabaker , this is another file I need to add Ordering instance to, it doesn't have `cats.kernel.Order` instance , shall I add it ?
https://github.com/http4s/http4s/blob/a942a83e2b88bafc644fc9916fd1979eb951ced8/core/shared/src/main/scala/org/http4s/HttpVersion.scala#L30

**Comment by rossabaker** [comment]
Yes, separate PRs are good.

I think `HttpVersion` does have a `cats.kernel.Order`, in `catsInstancesForHttp4sHttpVersion`.

Adding the cats instance for `HttpDate` would be a good exercise, but honestly, it's going to be hard if you haven't sorted out installing sbt yet.  I don't have an M1, but it looks like other people have figured out a way.  I'd start with that, so you can compile instead of relying on CI.  You'll be much more efficient and learn faster.

**Comment by armanbilge** [comment]
If you can't get SBT running locally you can try running metals in an online IDE e.g. see https://scalameta.org/metals/docs/editors/online-ides/

**Comment by san-coding** [comment]
> Yes, separate PRs are good.
> 
> I think `HttpVersion` does have a `cats.kernel.Order`, in `catsInstancesForHttp4sHttpVersion`.
> 
> Adding the cats instance for `HttpDate` would be a good exercise, but honestly, it's going to be hard if you haven't sorted out installing sbt yet. I don't have an M1, but it looks like other people have figured out a way. I'd start with that, so you can compile instead of relying on CI. You'll be much more efficient and learn faster.

Ohh okay, I will figure out a way

**Comment by san-coding** [comment]
> Yes, separate PRs are good.
> 
> I think `HttpVersion` does have a `cats.kernel.Order`, in `catsInstancesForHttp4sHttpVersion`.
> 
> Adding the cats instance for `HttpDate` would be a good exercise, but honestly, it's going to be hard if you haven't sorted out installing sbt yet. I don't have an M1, but it looks like other people have figured out a way. I'd start with that, so you can compile instead of relying on CI. You'll be much more efficient and learn faster.

### @rossabaker @isomarcte  In the case of HttpDate , how do I define `Ordering` instance
```
class HttpDate private (val epochSecond: Long) extends Renderable with Ordered[HttpDate] { /* elided */ }

object HttpDate {
    implicit val stdLibOrderingInstance: Ordering[HttpDate] = WHAT.toOrdering
}


```
Should It be `epochSecond.toOrdering`

**Comment by san-coding** [comment]
Hey @rossabaker @isomarcte , `QValue` class is extending `Ordered`, and has a `cats.kernel` instance, but and `Ordering` instance has to be added to it right?
https://github.com/http4s/http4s/blob/a942a83e2b88bafc644fc9916fd1979eb951ced8/core/shared/src/main/scala/org/http4s/QValue.scala#L131

I think `HttpVersion` class also needs `Ordering` instance
https://github.com/http4s/http4s/blob/a942a83e2b88bafc644fc9916fd1979eb951ced8/core/shared/src/main/scala/org/http4s/HttpVersion.scala#L30-L32

ContentCoding also requires `Ordering` instance
https://github.com/http4s/http4s/blob/a942a83e2b88bafc644fc9916fd1979eb951ced8/core/shared/src/main/scala/org/http4s/ContentCoding.scala#L37-L40

There are many more classes which require `Ordering` instance, I will search and make PRs for each of them one by one, please mention other classes which I need to add `Ordering` instance to

**Comment by san-coding** [comment]
@isomarcte @rossabaker have opened a PR for adding `Ordering` instance `QValue` class
