### ISSUE TITLE
HMAC-SHA256 support for OAuth1

### ISSUE THREAD

**Issue by barryoneill** [http4s/http4s#5022]
I'm currently using the `oauth1.signRequest` function in http4s for communication with a 3rd party service.  The http4s implementation is hardcoded to use HMAC-SHA1.  Our 3rd party will soon require HMAC-SHA256.

Would there be any objection if I raised a PR to make this value configurable (while maintaining backwards compatibility for existing code)?

**Comment by rossabaker** [comment]
That would be great.  I'm not sure what version you're on, but series/0.22 is ideal if it's compatible.  If you're on Cats-Effect 3, go ahead and try series/0.23, and someone can backport it if they're so inclined.

Aside: love the Quack avatar.

**Comment by barryoneill** [comment]
Quack is my spirit animal.  

We're on 0.22 as it happens, so I'll base against that.  Thanks!

**Comment by barryoneill** [comment]
Oh, 0.21 for some projects 🤦🏻  -  I'll start with 0.22 anyway

**Comment by rossabaker** [comment]
We're not actively maintaining 0.21 anymore, but if you need it all the way back there and can do it compatibly, I am willing to release it.

**Comment by barryoneill** [comment]
Understood, in dependency hell with those projects but will see how I get on :)

**Comment by barryoneill** [comment]
WIP - https://github.com/http4s/http4s/pull/5023/files - though unsure how to do this in series/0.22 without failing binary compatibility checks
