### ISSUE TITLE
Further purify the JVM/JS cross

### ISSUE THREAD

**Issue by armanbilge** [http4s/http4s#5044]
Now that I better understand the merging challenges that lie ahead (e.g., #5023), I wanted to sketch out some ideas to further improve things post-cross.

1. Crypto. My proposal: create a new library (would org.http4s like to host?) that provides a `Crypto[F]` typeclass. Implementations for JVM, Node.js, and browser platforms will be available with a Cats dependency for JVM and CE 3 dependency for JS. Starting from 0.22, re-implement all cryptography with `Crypto[F]` (its use can be kept internal) and merge this up through 1.0. If executed right, all crypto code will be identical for JVM and JS (i.e., pure cross). Second bird with this stone: remove the copy-pasted Web Crypto facade currently in core.

2. Files: coreJVM already has a dependency on fs2.io. Also add an optional dependency to fs2.io to coreJS. Re-implement StaticFiles and friends using new fs2.io cross-platform file APIs (hopefully we can run this up through 0.23) and un-platform all file-related methods. Critical assumption here (not 100% on this) is that as long as browser-based apps don't touch these file-related methods, they should be fine without the fs2.io dependency.

3. Miscellany: several of the platformed classes in core are simply to provide convenience methods to convert to/from JVM-only net classes. I say drop these in 1.0, those who really need this can always use the conversions available in ip4s (slightly less convenient).

Following 1, 2, and 3, I think it's very likely that core can actually become pure again, or nearly so. More importantly, we'll have scourged platformed classes across several modules that make merges difficult. Thoughts? :)

**Comment by isomarcte** [comment]
> Crypto. My proposal: create a new library (would org.http4s like to host?) that provides a Crypto[F] typeclass. Implementations for JVM, Node.js, and browser platforms will be available with a Cats dependency for JVM and CE 3 dependency for JS. Starting from 0.22, re-implement all cryptography with Crypto[F] (its use can be kept internal) and merge this up through 1.0. If executed right, all crypto code will be identical for JVM and JS (i.e., pure cross). Second bird with this stone: remove the copy-pasted Web Crypto facade currently in core.

Are you suggesting a class `Crypto[F]` which is just a facade for all the operations needed in http4s, or something more general, e.g. classes describing encryption, decryption, hashing/digesting, etc.

A more general variant has been sorely needed in the ecosystem for some time now, even without considering the additional complications that the js based builds add here. @ChristopherDavenport and I had been playing around with some encodings for crypto and hashing classes, but I think we both got side tracked with everything else going on around CE3 and Scala3.

> Files: coreJVM already has a dependency on fs2.io. Also add an optional dependency to fs2.io to coreJS. Re-implement StaticFiles and friends using new fs2.io cross-platform file APIs (hopefully we can run this up through 0.23) and un-platform all file-related methods. Critical assumption here (not 100% on this) is that as long as browser-based apps don't touch these file-related methods, they should be fine without the fs2.io dependency.

(Scalajs novice here) Am I correct in understanding that we _can_ implement these APIs for nodejs, but not for the browser based apps?

> Miscellany: several of the platformed classes in core are simply to provide convenience methods to convert to/from JVM-only net classes. I say drop these in 1.0, those who really need this can always use the conversions available in ip4s (slightly less convenient).

Personally, I'm pretty open to this idea. The JVM types are usually a pain to deal with directly. Their primary utility being that they are the default common interface for expressing these types, but I'm not sure that makes them worth keeping around.

**Comment by armanbilge** [comment]
> Are you suggesting a class Crypto[F] which is just a facade for all the operations needed in http4s, or something more general, e.g. classes describing encryption, decryption, hashing/digesting, etc.

Definitely something more general! Hopefully, we could use this library to provide cryptography for any JVM/JS crossing source e.g. in https://github.com/tpolecat/skunk/pull/515.

> (Scalajs novice here) Am I correct in understanding that we can implement these APIs for nodejs, but not for the browser based apps?

We _have_ implemented these APIs in Node.js :) see https://github.com/typelevel/fs2/pull/2519. For the browser, it's a bit more iffy ... _technically_, browsers do have at least [file reading](https://developer.mozilla.org/en-US/docs/Web/API/File) so there is probably something we could do. But this might be better suited for dom-core than core itself. I.e. I assume people will work with files fairly similarly on JVM and Node.js, but quite differently in the browser which is a pretty different situation :)

**Comment by rossabaker** [comment]
> provides a Crypto[F] typeclass

Is this a type class or an algebra?  I am thinking of it more as the latter.

> Also add an optional dependency to fs2.io to coreJS.

I don't know about JS, but optional dependencies are a massive pain on the JVM.  On the JVM, they explode if not used properly.  I guess they might just explode in a different way if used on the wrong JS platform.  I've also struggled with them participating in eviction, which I imagine could be a similar problem on JS.

> Several of the platformed classes in core are simply to provide convenience methods to convert to/from JVM-only net classes. I say drop these in 1.0,

If we go this route, we should investigate deprecating the same in earlier versions.

**Comment by armanbilge** [comment]
> Is this a type class or an algebra? I am thinking of it more as the latter.

Woops, I guess it's an algebra! Sorry, still learning my FP ABCs :) Besides terminology, any other thoughts? :)

> I don't know about JS, but optional dependencies are a massive pain on the JVM.

100% agree. The underlying problem is that the Scala.js community doesn't distinguish (and cross-build) between Node.js and Browsers even though they are fundamentally different platforms. Thus, we resort to horrible hacks. I posted about this at [Scala Users](https://users.scala-lang.org/t/scala-js-how-to-support-both-node-js-and-browser-platforms).

> If we go this route, we should investigate deprecating the same in earlier versions.

Makes sense 👍

**Comment by isomarcte** [comment]
> Is this a type class or an algebra? I am thinking of it more as the latter.

I was actually thinking of these as typeclasses based around the various algorithms. Similar to how Cryptonite does this (https://hackage.haskell.org/package/cryptonite-0.29/docs/Crypto-Hash-Algorithms.html#t:HashAlgorithm).

However, things get a bit complicated on the JVM. In theory, given a class like `HashAlgorithm`, there is only one valid instance for a given algorithm, but since the JVM has some many duplicate implementations for the same algorithm, then you get into an awkward situation. You also have some difficulties with algorithms which have many parameters. When conceptualizing what would be required for either a typeclass or algebra, I've found considering Argon2 (https://en.wikipedia.org/wiki/Argon2) to be ideal. This is because Argon2 has the maximal complexity of any commonly used hashing algorithm in use today, so if the encoding works with Argon2, it is likely to work for most other algorithms.

And that's just talking for hash/digest/pbkdf. Encryption/Decryption is a whole other animal.

There are sketches of similar interfaces in tsec, but nothing quite fits right. @ChristopherDavenport and I were in the early stages of toying with encodings and ergonomics, but we both got pulled off to other things. 

> I don't know about JS, but optional dependencies are a massive pain on the JVM. On the JVM, they explode if not used properly. I guess they might just explode in a different way if used on the wrong JS platform. I've also struggled with them participating in eviction, which I imagine could be a similar problem on JS.

I'm also hesitant about this. It almost feels like Scalajs for the browser and Scalajs based on Node should be different ecosystems in some way.

**Comment by armanbilge** [comment]
> However, things get a bit complicated on the JVM.

If possible, I wonder if we can take a lesson from the new cross-platform Files APIs in FS2? Where the goal was not to support every single platform-specific feature but instead to provide a shared interface for the most common use-cases. The assumption is the user who needs something fancy can always "drop-down" and write platform-specific code. My goal here at least is to simplify the code in http4s. Maybe I'm missing something, but how hard would it be to codify something like `SubtleCrypto` (https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto) as an algebra and implement it cross-platform?

> I'm also hesitant about this. It almost feels like Scalajs for the browser and Scalajs based on Node should be different ecosystems in some way.

They _should_ be treated as different platforms, just as we cross-build for 2.12/2.13/3, and cross for JVM/JS/Native. I.e. they can have some shared sources, but also require some platform-specific sources. Sorry to be a broken record but [I'll point again to my Scala Users post about this issue](https://users.scala-lang.org/t/scala-js-how-to-support-both-node-js-and-browser-platforms/). Fortunately @tpolecat is acutely aware of this issue and he's offered to present a proposal I/we write up to the Scala Center.

Theoretically, if http4s is brave (at least with its JS users), we could pave the way for this by releasing artifacts such as `core_node_sjs1_2.13` and `core_webapi_sjs1_2.13` and a tiny sbt plugin to make the `%%%` magic work.

In fact, this should _really_ start from fs2 itself. Compression is one of the things that didn't make the JS cross, even though compression APIs are available on both Node.js and Browsers, just not the _same_ APIs. fs2 is where that should be fixed.

**Comment by isomarcte** [comment]
> If possible, I wonder if we can take a lesson from the new cross-platform Files APIs in FS2? Where the goal was not to support every single platform-specific feature but instead to provide a shared interface for the most common use-cases. The assumption is the user who needs something fancy can always "drop-down" and write platform-specific code. My goal here at least is to simplify the code in http4s. Maybe I'm missing something, but how hard would it be to codify something like SubtleCrypto (https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto) as an algebra and implement it cross-platform?

I think that's definitely more achievable in the near term. In some ways these are different goals. If we just want a facade to make cross compilation more clean, then the fastest way to that result is exactly what you are suggesting. 

OTOH hand, if we want a clean set of classes or algebras for generalized hash and crypto usage in a strict FP context, like Cryptonite, then that requires a great deal more up front work. This would also satisfy the cross platform use case, assuming it was built with Scalajs in mind, but would like take a lot longer to get there.

> Sorry to be a broken record but I'll point again to my Scala Users post about this issue.

Sorry, I missed this on your other PR.

**Comment by armanbilge** [comment]
> In some ways these are different goals.

@isomarcte thanks for clarifying, that makes sense. Doubtful, Is there a way we can start with the "SubtleCrypto algebra" to get us going and meaningfully evolve it into the FP crypto library you are imagining?

**Comment by isomarcte** [comment]
> Doubtful, but is there a way we can start with the "SubtleCrypto algebra" to get us going and meaningfully evolve it into the FP crypto library you are imagining?

I personally think that is a great idea. The real question would be where to host it, which is not something I can answer in isolation.

**Comment by armanbilge** [comment]
> The real question would be where to host it, which is not something I can answer in isolation.

I posted about this in the #http4s channel on discord for discussion.

**Comment by isomarcte** [comment]
@armanbilge and there would need to be a discussion about the maintenance/liability trade off of this with the various library authors. 

Correct me if I'm wrong, but it sounds like this would need to be depended on by the core modules of many of the primary FP libraries (fs2/http4s/skunk). As you likely know, most of those modules have very few dependencies by design. There is an argument for _not_ creating this library just to keep the dependency set smaller, even though it leads to a lot of duplicated code.

**Comment by tpolecat** [comment]
> There is an argument for not creating this library just to keep the dependency set smaller, even though it leads to a lot of duplicated code.

Another dependency (as long as it's managed by typelevel and we can get it out the door fast when upgrades are needed) isn't a problem for me (Skunk).

**Comment by armanbilge** [comment]
I don't think fs2 has any crypto in it. So far skunk and http4s would be the primary users, _maybe_ scodec but not entirely sure since actually scodec-bits would probably be a dependency of this crypto lib. I thought a bit about this here: https://github.com/scodec/scodec-bits/issues/300

**Comment by isomarcte** [comment]
@armanbilge I was basing my fs2 mention off of this,

> In fact, this should really start from fs2 itself. Compression is one of the things that didn't make the JS cross, even though compression APIs are available on both Node.js and Browsers, just not the same APIs. fs2 is where that should be fixed.

I may have been misunderstanding the context on that.

**Comment by armanbilge** [comment]
BTW, the key trick to making this work across http4s 0.22/0.23/1.0 is to require only a Cats dependency for the JVM implementations (i.e. use a MonadError for `F`) and the Cats Effect dependency only for the JS implementations which will need `Async`.

> I may have been misunderstanding the context on that.

Yep, sorry! That was about Node.js and Browser being different platforms, separate but also important issue :)

**Comment by rossabaker** [comment]
Dependencies on a user repo are rough, unless the user has deputized a few other people, _with full admin rights_.  That's key: tsec is suffering right now because its CI provider rotted, and it can still be published, but it can no longer be published automatically without a fork.

I feel much safer with Typelevel dependencies.  Everyone hits busy stretches where they run off and do Haskell for a year (😰 ) or whatever else and declare inbox bankruptcy.  But a Typelevel project can always find an admin.  I've tried to push my libraries (e.g., case-insensitive) and other microdependencies to Typelevel for just that reason.  I would strongly recommend spinning off to there if this proceeds.

**Comment by armanbilge** [comment]
That's two votes 👍 for a typelevel project from @tpolecat and @rossabaker, happy to wait for others to weigh in as well. If someone sets up a repo I can try and get cracking at this :)

**Comment by armanbilge** [comment]
Done via #5139, #5226, #5303.
