### ISSUE TITLE
Version stability on website is stale

### ISSUE THREAD

**Issue by kag0** [http4s/http4s#5048]
https://http4s.org/versions indicates that 0.23 and 0.22 are stable and 0.21 is EOL. 
However the dropdowns under "Documentation" (top bar) and "get started with http4s" (center of page) on https://http4s.org indicate that 0.21 is stable and 0.23 and 0.22 are under development.

**Comment by rossabaker** [comment]
Thanks for the report, and thanks to @armanbilge for jumping on it.
