### ISSUE TITLE
Request#withEntity appends Content-Type instead of replacing it since 0.22

### ISSUE THREAD

**Issue by matil019** [http4s/http4s#5059]
Nice to meet you!

I've discovered a behavior change of `Request#withEntity` between 0.21.25 and 0.22.x.

If a `Request` already has a `Content-Type` header, it is replaced with a new value of `EntityEncoder` in 0.21.25, while it is appended as another header in any version of 0.22.x.

Example:

```scala
import cats.effect.IO

import org.http4s.MediaType
import org.http4s.Request
import org.http4s.headers.`Content-Type`

println {
  Request[IO]()
    .putHeaders(`Content-Type`(MediaType.text.plain))
    .withEntity[String]("foo")
}
```

Running with Coursier:

```
$ scala -cp .:"$(cs fetch --classpath org.http4s::http4s-core:0.21.25)" Test.scala
Request(method=GET, uri=/, headers=Headers(Content-Length: 3, Content-Type: text/plain; charset=UTF-8))
```

```
$ scala -cp .:"$(cs fetch --classpath org.http4s::http4s-core:0.22.2)" Test.scala
Request(method=GET, uri=/, headers=Headers(Content-Type: text/plain, Content-Length: 3, Content-Type: text/plain; charset=UTF-8))
```

(The output should be the same)

I couldn't find a relevant entry in the changelog. I understand that I may be misusing the library. However, since multiple `Content-Type`s are never allowed, it would be helpful to revert the behavior to the old one.

**Comment by rossabaker** [comment]
Thanks for the report.  We had a similar issue with Accept headers on the client (#4987).  I'll take a look.

**Comment by matil019** [comment]
Thank you for a quick response and your hard work!
