### ISSUE TITLE
EntityEncoder for File, Path, and InputStream could be implicit

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#5072]
These encoders were all explicit through series/0.22, because they required an explicit `Blocker` instance.  This is not necessary in Cats-Effect 3, so there's no reason these encoders couldn't be made implicit.  They are located in `EntityEncoder.scala`, and could be made implicit in a PR against series/0.23.

To resolve the TODOs on chunk size, we could provide explicit alternatives with a parameterized chunk size.  These encoders are old and nobody has asked for that control, so I'm content to just delete the TODOs.

**Comment by san-coding** [comment]
Hey @rossabaker can I work on this issue ?

**Comment by armanbilge** [comment]
I think my PR fixed it!
