### ISSUE TITLE
`Uri.resolve` behaviour very surprising, seems to discard last segment of `base`

### ISSUE THREAD

**Issue by chwthewke** [http4s/http4s#5099]
This is a REPL with http4s 0.23.1 (and Scala 2.13):

```scala
scala> uri"http://example.com/foo".resolve(uri"bar")
val res4: org.http4s.Uri = http://example.com/bar

scala> uri"http://example.com/foo/bar".resolve(uri"baz")
val res9: org.http4s.Uri = http://example.com/foo/baz
```

As I understand [RFC 3986 5.2.3](https://datatracker.ietf.org/doc/html/rfc3986#section-5.2.3), which the http4s source mentions, the above is intended behaviour.

However, adding a / at the end of the base uri literal has no effect

```scala
scala> uri"http://example.com/foo/".resolve(uri"bar")
val res12: org.http4s.Uri = http://example.com/bar

scala> uri"http://example.com/foo/bar/".resolve(uri"baz")
val res13: org.http4s.Uri = http://example.com/foo/baz
```

I would expect the result to be http://example.com/foo/bar and http://example.com/foo/bar/baz, respectively.

As a workaround, calling `/ ""` on the base before resolve produces the expected result, but I would hope that this is not necessary.

```scala
scala> (uri"http://example.com/foo" / "").resolve(uri"bar")
val res2: org.http4s.Uri = http://example.com/foo/bar
```

I think that in order to implement RFC 3986 5.2.3 correctly, `Uri.Path.merge` should check whether the base path ends with a /, for example

```scala
    /* Merge paths per RFC 3986 5.2.3 */
    def merge(path: Path): Path = {
      val merge = if (isEmpty || endsWithSlash) segments else segments.init
      Path(merge ++ path.segments, absolute = absolute, endsWithSlash = path.endsWithSlash)
    }
```

Thank you for consideration

**Comment by daddykotex** [comment]
I have the same issue. Are you open to a fix or the new behaviour is the way to go.

OP explained it all but in a nutshell, here's how I got the problem:

1. have a configurable base url `http://some-host.com/api/v3`
2. have a client that build request path & query like `/projects/1`
3. resolve request uri like so: `base.resolve(request.uri)`

Before I would have `http://some-host.com/api/v3/projects/1`now I get `http://some-host.com/api/projects/1`

The workaround is fine, but I can fix this if you are open to a fix.

**Comment by FrancescoSerra** [comment]
Implementation of the proposed fix at: https://github.com/http4s/http4s/pull/6481
