### ISSUE TITLE
Http4s scalatest Asserting syntax for testing responses

### ISSUE THREAD

**Issue by geirolz** [http4s/http4s#5146]
I have no idea if there is already something to do this, if exits I'm more than happy to delete custom code  

I wrote a simple "asserting" syntax based on  `cats.effect.testing.scalatest.AsyncIOSpec` to test my responses.

I wonder if something like this can be implemented into http4s, should be useful for `scalatest` + `http4s` + `circe` users

example:
```scala
class RoutesSpec extends AsyncWordSpec with AsyncIOSpec with Http4sAsserting with Matchers {
  
   case class Foo(value: String)

  "test" in {
    
    val response: IO[Response[IO]] = ???

    for {
       _ <- response.assertingStatus(_ shouldBe Status.Ok)
       _ <- response.assertingBody[Foo](_ shouldBe Foo("TEST"))
     } yield ()
  }
}
```

Http4sAsserting
```scala
trait Http4sAsserting { this: Matchers with AsyncIOSpec with CirceSpec =>

  type ResponseAssertion = Response[IO] => IO[Assertion]

  implicit class Http4sResponseAssertionsSyntax(actual: IO[Response[IO]]) {

    def assertingStatus(f: Status => Assertion): IO[Assertion] =
      asserting(actualResp => actualResp.status.pure[IO].asserting(f))

    def assertingBodyDecode[A](implicit ev: EntityDecoder[IO, A]): IO[Assertion] =
      asserting(_.as[A].assertNoException)

    def assertingBody[A](f: A => Assertion)(implicit ev: EntityDecoder[IO, A]): IO[Assertion] =
      asserting(_.as[A].asserting(f))

    def assertingEmptyBody: IO[Assertion] =
      asserting(_.body.compile.toVector.asserting(_ shouldBe empty))

    def asserting(assertion: ResponseAssertion): IO[Assertion] =
      actual.flatMap(assertion)
  }
}
```

**Comment by rossabaker** [comment]
We used to publish Specs2 matchers, but deprecated and removed them.  The concept lives on at [specs2-http4s](https://github.com/etorreborre/specs2-http4s).  Our version had nothing to say about effects, so yours is operating on a slightly different level, and I haven't seen the approach elsewhere.

**Comment by geirolz** [comment]
Ok thanks for sharing, but there is something also for `scalatest` ?

**Comment by rossabaker** [comment]
It used to be that if you used the right specs2 jar, you could use Specs2 matchers in ScalaTest without  pulling in most of the Specs2 machinery.  I can't remember which one that was, or whether it's still true.

I don't know of any ScalaTest integrations.  We're using MUnit in the project these days.

**Comment by geirolz** [comment]
Ok, thanks for the answers :)
