### ISSUE TITLE
deduceKeyLength returns 0 for TLSv1.3 Cipher Suites

### ISSUE THREAD

**Issue by geoffreytchew** [http4s/http4s#5153]
While writing tests for another issue, I noticed that org.http4s.internal.tls deduceKeyLength is returning 0 for the key length when a TLSv1.3 cipher suite is specified. The function doesn't support the TLSv1.3 cipher suites, so the default value of 0 is returned for them. 

Also, the comment for the function references version 1.0 of the TLS spec, but it should also be updated to reference the 1.1, 1.2, and 1.3 versions as well. The function should be updated to handle ciphers from versions 1.0 through 1.3. A test should be added to confirm the expected behavior.

**Comment by geoffreytchew** [comment]
I'll be happy to take this one if someone wants to assign it to me.

**Comment by rossabaker** [comment]
:+1: I should have asked on the other ticket: is this also relevant in Cats-Effect 2?  I can try a backport if it is.  I got immersed in the CORS work.

I anticipate another release train next week.

**Comment by geoffreytchew** [comment]
> 👍 I should have asked on the other ticket: is this also relevant in Cats-Effect 2? I can try a backport if it is. I got immersed in the CORS work.
> 
> I anticipate another release train next week.

Are you asking if the other issue (#5110) is relevant in cats effect 2? The bug was in EmberServer's ServerHelpers.scala at least as far back as 0.21.x.

As far as this issue, I also found it as far back as 0.21.x. It affects both the blaze and ember servers.

**Comment by rossabaker** [comment]
Yes, #5011. Sorry, I meant to reference it by number.  We're generally starting on series/0.22 with anything that can be done without breaking compatibility, and merging it forward.  I'll look into backporting #5110.  series/0.21 is only getting security patches now.

series/0.22 would be the ideal place to start this one, but I'll look at (and maybe cherry-pick) a PR to any branch.

**Comment by geoffreytchew** [comment]
I can submit a PR to the series/0.22 branch

**Comment by geoffreytchew** [comment]
Just submitted the following PR that addresses this issue: https://github.com/http4s/http4s/pull/5166

**Comment by armanbilge** [comment]
Fixed in https://github.com/http4s/http4s/pull/5166.
