### ISSUE TITLE
Retry Client Hanging

### ISSUE THREAD

**Issue by tdbgamer** [http4s/http4s#5180]
I've been experiencing an issue where the retry client seems to hang in certain cases. I was able to replicate it here:
https://github.com/tdbgamer/http4s-retry-hang

Not sure what's going on, but in the thread dump, all the IO threads are waiting on the same thing.

Maybe it could be related to [this](https://github.com/typelevel/cats-effect/issues/2050)?

**Comment by Qi77Qi** [comment]
think I might have run into the same issue. I didn't see a bunch http4s threads in thread dump, but after removing some retries, I got passed the hanging issue

**Comment by rossabaker** [comment]
I am sorry.  I remember starting to comment on this when it came in, and I flaked.

I can reproduce this on the 0.23 branch from @tdbgamer's code.  We'll target a fix there.

**Comment by armanbilge** [comment]
Pretty sure this is fixed.
