### ISSUE TITLE
Update Bootstrap to 5.1.1

### ISSUE THREAD

**Issue by noelwelsh** [http4s/http4s#5191]
I find the current http4s website very cluttered, but much improved with some minor tweaks to the styling to add more white space between, e.g. above a heading to more clearly distinguish section breaks.

I notice the site currently uses bootstrap + some custom styles. A way forward might be:

- Update to current bootstrap (5.1.1 from current 4.0 beta)
- Changing some of the custom styling to add more white space. (Tbh bootstrap's defaults are pretty good, so probably deleting some of the customisation would be sufficient.)

This should be fairly self contained.

Alternatively the styling could be redeveloped using Tailwind, which I've worked with recently. Tailwind is nicer for more complex sites but I think it's overkill for http4s' needs.

**Comment by noelwelsh** [comment]
Send me in coach!

**Comment by slice** [comment]
> Send me in coach!

@noelwelsh Does this mean you've undertaken this effort? I'd like to help!

**Comment by rossabaker** [comment]
What @noelwelsh proposes makes sense to me, though I do regret starting a new theme from scratch instead of picking a one mostly off the shelf from the static site generator.  We should probably marry or break up with Hugo before investing very much here, as a new site generator might most easily come with a new base theme.  And if these tweaks are still relevant on the chosen tool, cool.

I am in over my head and defer to @noelwelsh as to whether @slice's second set of hands is useful on this ticket.  If not, I am confident we can find more.  (For example, I'd love to have warning callout boxes, or a banner on the EOLed versions to direct people to the new.)

**Comment by noelwelsh** [comment]
@slice What I'm planning to do has very limited scope so there is plenty of room for further improvements.

**Comment by noelwelsh** [comment]
Work progressing here: https://github.com/noelwelsh/http4s/tree/feature/bootstrap-5
Commit message should explain what's going on.

**Comment by slice** [comment]
@noelwelsh I can help with the Bootstrap upgrade, but I've used http4s for a while now and my inner web designer has accumulated some mental notes that could improve the design of the website, so I'm taking this issue as the opportunity to do so :D

Not only with regards to things like whitespace, but also callouts, navigation, etc.

**Comment by noelwelsh** [comment]
@slice I propose shrinking this issue down to just updating to Bootstrap 5. This will give us a basis for other improvements, which we can open other issues for. I would rather have lots of small issues / PRs that get closed quickly than a giant unfocused issue that is never resolved.

(On the topic of Bootstrap, I prefer Tailwind these days [though I'm not a designer by trade] but I think Bootstrap is the best choice for this project as it is 1) widely known and 2) doesn't require a build system to work. [Tailwind doesn't *require* a build system but I think practical use does.])

**Comment by slice** [comment]
@noelwelsh Seems like a good idea!

With some personal things that just came up I may or may not be able to help with the Bootstrap upgrade 😅. However I'm still interested in proposing some fixes and improvements post-upgrade, eventually.

**Comment by noelwelsh** [comment]
No problem! I can almost surely finish the Bootstrapping on my own.

**Comment by noelwelsh** [comment]
It looks like the rest of the documentation works just fine with Bootstrap 5 without any modification.
