### ISSUE TITLE
UnixSocket Client/Server

### ISSUE THREAD

**Issue by ChristopherDavenport** [http4s/http4s#5218]
Ember's Parser/Encoder logic on top of the Unix Socket Implementation introduced in fs2.

I wanted to make sure we had an issue since this got mentioned recently, and its a fairly straight encoding.

**Comment by armanbilge** [comment]
Without taking a look, does this actually need anything special? IIRC fs2's unix sockets also extends `SocketGroup` so can't you just pass it directly to the ember builders?

**Comment by ChristopherDavenport** [comment]
I didn't realize that. I'll try that out first.

**Comment by armanbilge** [comment]
Woops, I think I put my foot in my mouth. The unix sockets are not a socket group, but an instance of a unix socket is just a socket.

**Comment by ChristopherDavenport** [comment]
https://github.com/typelevel/fs2/blob/main/io/shared/src/main/scala/fs2/io/net/unixsocket/UnixSockets.scala#L33 - Yeah, I am going to PR it. Its fairly straightforward, but needs a different builder.
