### ISSUE TITLE
ResourceServiceBuilder using OS-dependent file paths instead of resource paths

### ISSUE THREAD

**Issue by gfpeltier** [http4s/http4s#5240]
https://github.com/http4s/http4s/blob/56c50a9c6ebc4969c707a19595820983b06ba6bf/server/src/main/scala/org/http4s/server/staticcontent/ResourceService.scala#L101

The above line invokes [Path#toString](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/nio/file/Path.html#toString()), which emits a string using the default OS path separator. However, that string path is then used to load the resource file with [ClassLoader#getResource](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/ClassLoader.html#getResource(java.lang.String)), which expects all paths to use a '/' separator.

**Comment by rossabaker** [comment]
I'm guessing this is a Windows problem?  I think I understand, but I might have a difficult time testing a fix.

**Comment by rossabaker** [comment]
Ah, yes, I see your comment on Matrix now.  Is this something you'd be comfortable trying to PR a fix for?  I don't have a Windows machine to test on.

**Comment by gfpeltier** [comment]
Sorry, I should have been more explicit. Yes, this is a Windows issue. I would be glad to do the PR. I just wanted to check with you guys first to see if there is a particular way you want to handle it since http4s has some handy internal URI utilities. Or if my one-line `path.toString.replaceAll("\\\\", "/")` would suffice? Also, which branch would you like me to target?

**Comment by mabasic** [comment]
I'm not sure but I think that this is causing me problems too. 

I'll try to debug since I am on Windows and can use WSL for Linux.
