### ISSUE TITLE
Ease migration to 0.22/0.23 by implementing 0.21 APIs as deprecated aliases.

### ISSUE THREAD

**Issue by bplommer** [http4s/http4s#5264]
This is what ScalaFix did in 3.1.0 when they renamed everything. Possible aliases:

- Case-insensitive string API
- `Header.apply` for instantiating `Header.Raw`
- Blaze client/server package renamings
- other things?

**Comment by rossabaker** [comment]
I'm trying to free up time to write a scalafix for these, but lots of people won't run them.  I think this is a reasonable idea.  We usually leave liberal and long-lived deprecations, and I can't recall why we didn't here.

**Comment by armanbilge** [comment]
Fixed in https://github.com/http4s/http4s/pull/5344.
