### ISSUE TITLE
Consider removing QValue from MediaRange and MediaType

### ISSUE THREAD

**Issue by jedesah** [http4s/http4s#527]
My understanding of the HTTP spec is that it would be incorrect to have a `qValue` in the `Content-Type` header. Which to me makes sense, since the content type of the request should be a definitive value whereas `qValue` is designed to express preference, for instance, in the content-type of the response, through the use of the `Accept` header.

If the above statement is correct, then I would argue that `qValue` has no place in `MediaRange` and `MediaType` and should instead be defined on headers for which a `qValue` has meaning.

**Comment by rossabaker** [comment]
Yes, we need to do something here.  This model originated from a fork of Spray, and then had various attempts to improve it in the early days, and no pass to go back and make it consistent.  (#521 begins to address this.)

For example:
* `Charset` is not a `CharsetRange`.
* `MediaType` is a `MediaRange`.
* `ContentCoding` is the only type, and is range-like.
* `LanguageTag` is the only type, and is range-like.

Furthermore, the corresponding content negotiation headers are not consistent in the operations they expose or in their treatment of asterisks, where applicable.

**Comment by bryce-anderson** [comment]
This seems like a reasonable idea to me although it will end up muddying the affected headers to some extent. I imagine that will be paid back from simplifying `MediaRange` etc.

**Comment by jedesah** [comment]
Fixed by #532
