### ISSUE TITLE
Optimized `MimeDB`

### ISSUE THREAD

**Issue by armanbilge** [http4s/http4s#5273]
This topic came up in https://github.com/http4s/http4s/issues/5255#issuecomment-925895749. See also https://github.com/http4s/http4s-dom/issues/30 (cc @cquiroz). To quote Ross:

> I think we can revisit the notion of the MimeDB, given that we're creating constants for proprietary formats for business that went under a decade ago. The bar to get into that registry wasn't high. It's neat that we're adhering to standards, but rearranging how we adhere to it is definitely on the table.

As I see it, there are two halves to the MimeDB interface:
1. the static half, which provides static access to mime type constants in code; and
2. the dynamic half, which allows parsers, `FileService`, etc. to dynamically lookup mime types.

I suspect (2) is the trickier part of this problem. The constants in (1) can basically be moved wherever (even another module for the particularly obsolete ones) and users can import/add dependencies as needed to get at what they want. However, anything relying on (2) dynamic lookup currently references a static singleton "ground truth".

Also, for Scala.js in #5113 it's not (1) that is the problem (SJS will dead-code-eliminate any unused constants in the optimization phase). It's (2), because creating that dynamic lookup map involves referencing all these constants thus obstructing the aforementioned optimization.

My proposal would be:
1. we create a trait e.g. `MimeDBProvider` defining the dynamic lookup methods
2. anything that needs dynamic mime type lookup, should require an implicit `MimeDBProvider`
3. we provide a default lightweight/practical implicit for `MimeDBProvider` (of course, what goes into this is up for debate)
4. also provide additional `MimeDBProvider`s (e.g., one containing the whole lot) that could be explicitly imported (possibly from another module)

(3) and (4) could be reversed: the default `MimeDBProvider` could be the big one, and the lightweight one could be the explicit import.

I think we could run these changes up binary-compatibly by continuing to use the global MimeDB anywhere we cannot compatibly add an implicit `MimeDBProvider` constraint to.

**Comment by rossabaker** [comment]
> what goes into this is up for debate

This is a big part of why it exists in the first place.  We didn't have to draw a line because the IANA draws the line.  They just drew it in an awfully permissive place.  I'd like to see a proposal for which ones matter.

Changing the MimeDB is often not binary compatible, because constants move.  If we were more careful rather than blindly running the app, that might no longer bre a concern.

**Comment by armanbilge** [comment]
How do the akka-http folks decide? That's not the full list right?

https://github.com/akka/akka-http/blob/master/akka-http-core/src/main/scala/akka/http/scaladsl/model/MediaType.scala

**Comment by rossabaker** [comment]
No, there are thousands.  But that's a good question.  Theirs seems a reasonable size.

**Comment by bblfish** [comment]
yes, it makes sense to split it up in the most used ones and then have a few other packages for other mime-types. Perhaps ones for the `x-*` ones, ... One could have one for all the RDF mime types for example, as they tend to all be used by apps that use them.

I had to put a list together for Akka, but it seems like most of them are available in http4s.
https://github.com/co-operating-systems/Reactive-SoLiD/blob/master/src/main/scala/run/cosy/http/RDFMediaTypes.scala
