### ISSUE TITLE
Parse errors are difficult to read

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#5280]
We should be able to do better:

```
scala> HttpVersion.fromString("blech")
res1: org.http4s.ParseResult[org.http4s.HttpVersion] = Left(org.http4s.ParseFailure: HTTP version: Error(0,NonEmptyList(OneOfStr(0,List(HTTP/)))))
```

**Comment by armanbilge** [comment]
Is this something that can be improved here, or in cats-parse?

**Comment by rossabaker** [comment]
Relevant: https://github.com/typelevel/cats-parse/issues/239

**Comment by rossabaker** [comment]
We can do it here, but if it's not HTTP specific, it might be contributable back to cats-parse.

**Comment by johnynek** [comment]
It would be nice to have a prettier rendering, but for programming language applications you probably want to control that.

I would make sure you look at LocationMap which at least will compute line/col for you, and can fetch lines so you can show a context to users.

**Comment by johnynek** [comment]
https://github.com/johnynek/bosatsu/pull/808

There is a PR with code you can copy if you want.

I don't know how easy it is to make it general (e.g. bosatsu is showing errors to users using paiges Doc, but you might be serializing errors and sending them over the network).
