### ISSUE TITLE
Timeouts are getting worse on Travis

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#529]
Seem to be getting more of these.  Afflicts both blaze and async-http-client.  Need to spend some time getting to the bottom of it.

```
[error]   x Idle timeout on slow response body
[error]    Expected: java.util.concurrent.TimeoutException. Got: java.lang.IllegalStateException: Cannot serve multiple concurrent read requests instead 
```

**Comment by bryce-anderson** [comment]
If its coming from both async-http-client and blaze its probably just a matter of thread contention for the travis CPU time. Is there a way to ask specs2 to not rust tests with timeouts concurrently with other tests?

There is a sbt flag (allegedly, haven't use it myself) that tells it to run specifications sequentially but I don't know of a way we can single out a single spec to say 'for this one, make sure nobody else is running please.'

**Comment by shengc** [comment]
either try set `parallelExecution in Test := false`, or as I can recall, adding `sequential` to the body of specs is the only way that turns the parallel test off.
