### ISSUE TITLE
Retrieving InputStream in NonBlockingServletIo

### ISSUE THREAD

**Issue by lukiano** [http4s/http4s#541]
val in = servletRequest.getInputStream should be a lazy val or similar (in case lazy val synchronization is an issue) so that getInputStream is called when the scalaz-stream Process is run and not before. 

This is so that (at least in Jetty 9) the 100-continue response is sent when a service actually wants to read from the request body and not before.

I guess the alternative is to modify getInputStream() in Jetty's org.eclipse.jetty.server.Request

BlockingServletIo works fine in this regard, but is blocking...

**Comment by rossabaker** [comment]
I have not done much with 1xx responses.  It seems the servlet container is responsible for sending the 100.  If you send a 100, you can't send another status.  Is the use case to inspect the headers before touching the body, and possibly send an error response to preempt the 100?

#543 introduces a difference in behavior: on a route that doesn't read the body, Tomcat returns a 100 Status, whereas Jetty no longer does.  I'm unsure which is more correct or what to do about the other.

**Comment by lukiano** [comment]
There's nothing in the servlet spec about this. Jetty's approach works well, but it's just an implementation detail. Hopefully it will be possible to open a request in Tomcat to match Jetty's behaviour.
