### ISSUE TITLE
Issue with GZip compression?

### ISSUE THREAD

**Issue by vilu** [http4s/http4s#5417]
Hi, we noticed an issue when upgrading from 0.23.4 to 0.23.6. Some clients started failing and blaming the gzip compression. One example would be 

`io.netty.handler.codec.compression.DecompressionException: CRC value mismatch.`

**Comment by Ravenow** [comment]
i can confirm this on 0.22.7, 0.22.6 works fine

**Comment by armanbilge** [comment]
Thanks for reporting. Yep, that would be the similar https://github.com/http4s/http4s/pull/5368 that targeted 0.22.

**Comment by armanbilge** [comment]
If either of you has an opportunity, would you be able to make a replication? Obviously this is something that is slipping through _both_ the fs2 and http4s test suites 😕

**Comment by armanbilge** [comment]
@vilu @ybasket thanks to @AL333Z's fantastic work on multiple fronts, if you use http4s 0.23.6 with fs2 `3.2-14-a2508ec` it should fix your issues. Please give it a try and report back, when you have a chance!

@Ravenow never fear, a backport to fs2 2.x is on the way in https://github.com/typelevel/fs2/pull/2701.

**Comment by armanbilge** [comment]
@Ravenow Now available for http4s 0.22 in fs2 `2.5-2-0f99472`.

**Comment by rossabaker** [comment]
Where does that leave us?  Leave this open until we have fs2 releases with the fix, but no code change on our end?

**Comment by armanbilge** [comment]
Yes, the default behavior was changed in fs2 so we don't need any code changes here. Up to you when to close the issue :)

**Comment by rossabaker** [comment]
Eh, no further action on our part, and people have a (snapshot) solution toward the bottom of this.  Closing.

Great job tracking this one down.

**Comment by armanbilge** [comment]
For those afraid of hashes, this fix is now available in fs2 3.2.3:
https://github.com/typelevel/fs2/releases/tag/v3.2.3

**Comment by armanbilge** [comment]
And now (finally!) in fs2 2.5.11 as well:
https://github.com/typelevel/fs2/releases/tag/v2.5.11
