### ISSUE TITLE
Backport previous versions of site?

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#5454]
Now that we're on Laika with 1.0, it looks different from 0.22 and 0.23.  It's worth a quick spike on how hard it would be to backport the nicer version of those sites.  I don't want to spend hours on it, but if we can get a quick win on those branches that are still maintained, that would be cool.

**Comment by danicheg** [comment]
We've migrated to the `0.23` series. Also, I'll try to do this for the `0.22` series, but it's perhaps will be much longer.

**Comment by rossabaker** [comment]
Nicely done, @danicheg.
