### ISSUE TITLE
The search function for the doc site

### ISSUE THREAD

**Issue by Kevin-Lee** [http4s/http4s#5457]
Could you add the search function for the doc site?
I recommend [Docsearch](https://docsearch.algolia.com). It is free for open source projects.
I'm not sure if it works well with Laika, but if it does, it would be nice to have it.

**Comment by armanbilge** [comment]
Good idea. Upstreamed the issue, so all Typelevel projects can benefit.
- https://github.com/typelevel/sbt-typelevel/issues/267
