### ISSUE TITLE
"Edit this page" returns 404

### ISSUE THREAD

**Issue by i10416** [http4s/http4s#5488]
For example, "Edit this page" in https://http4s.org/v1.0/integrations  refers to https://github.com/http4s/http4s/edit/main/docs/src/main/mdoc/integrations/README.md, but actual file is https://github.com/http4s/http4s/edit/main/docs/src/main/mdoc/integrations.md. 

Note: According to Laika documentation, Laika assumes document is located in ${PAGE_TITLE}/README.md.

**Comment by armanbilge** [comment]
The "Edit this page" functionality has been removed for now. It would be nice to bring it back as a contribution to the sbt-typelevel-site plugin so that all typelevel/http4s projects can have this feature :)

https://github.com/typelevel/sbt-typelevel/
