### ISSUE TITLE
Lint is full of warnings on series/0.22

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#5537]
I painstakingly fixed a bunch of these, but I guess it was on a different branch, and there are bincompat concerns.  But when I run quicklint on series/0.22, [warnings abound](https://github.com/http4s/http4s/runs/4105585792?check_suite_focus=true).  Are we just living with those?  `@nowarn`ing them away some how?

**Comment by rossabaker** [comment]
It's [similar on series/0.23](https://github.com/http4s/http4s/runs/4105585792?check_suite_focus=true#step:9:1).  I guess I knew this: fixing it would break MiMa.

I guess the question is, are we trying to hold the line on the preexisting ones and lint to avoid adding more?  If so, we need to flag these and make the warnings final.  If not, we just need to be good about catching them in 1.0 before they get released and locked into early versions if there's something we can still do.

**Comment by bplommer** [comment]
Sorry, only just saw this! My intention is to go through these and either fix them or exclude them from scalafix - then we can change the severity level to `error` and purge the exclusions from `main`. I have something in progress but have banned myself from opening http4s in an editor until I catch up on some other things 😅

**Comment by bplommer** [comment]
Resolved by #5549
