### ISSUE TITLE
Publish user-relevant scalafix rules

### ISSUE THREAD

**Issue by bplommer** [http4s/http4s#5558]
The rewrites for literals syntax fall into this category.

The other rules aren't http4s-specific - we should consider contributing them upstream (to fs2 for the fs2 ones, to scalafix for the generic ones) or splitting them into a separate repo.

This will need some more reorganizing of the build, as the published scalafix rules only test against input written for http4s 0.21 - as part of that work we could also integrate the `http4s-scalafix` into the top-level build.

**Comment by rossabaker** [comment]
I was just coming to add an issue about this!  We had a need for a Jetty 10/11 experiment at $WORK, so I started an http4s-servlet repo to see what The Great Schism looks like, and we're losing all the linters.  We're already polyrepo, so there's already a use case for being able to run the http4s ones outside core.

**Comment by armanbilge** [comment]
> so I started an http4s-servlet repo to see what The Great Schism looks like

Exciting!

**Comment by bplommer** [comment]
Resolved by creation of https://github.com/typelevel/typelevel-scalafix/
