### ISSUE TITLE
The framework should take care of http encoding everything when using the client API

### ISSUE THREAD

**Issue by jedesah** [http4s/http4s#560]
Currently, when using `http4s` as an http client, the user code must make sure to properly encode all parts of the `Request`. They must make sure the `URI`, along with it's `path`, `query` and `fragment` are all properly encoded. Furthermore, the user must make sure all headers are properly encoded. It would be nice if the framework took care of such things so that someone using the client API need not concern themselves with HTTP encoding.

**Comment by jedesah** [comment]
@refried Sorry to bug you, I know you are busy, but also curious to get your take on this and how it relates to #533.

**Comment by refried** [comment]
It sounds like a good idea to me. #533 tries to define all the ways that the URI should be encoded, and then accidentally grew to try to tackle how forms are encoded, since there's overlap.  It doesnt try to tackle headers yet.

**Comment by jedesah** [comment]
I mention encoding headers in my original description. But I think headers actually don't have any generic escaping rules so they don't need to be encoded. Of course, the headers that `http4s` knows about are guaranteed to be "correctly" encoded (as per the rules for that specific header) if the client uses the type-safe interface, but if the client uses *raw* headers, they are on their own. Does that sounds right?

So it's possible #533 will address all of this depending on the exact form it ends up taking. If it doesn't address it per say, it should lay the groundwork to craft an elegant client API that behaves as described.

**Comment by rossabaker** [comment]
Are we missing anything for this other than a less awful URI implementation?  I'd like to open an issue for that that covers all the things we aim to fix with a better `Uri`.

**Comment by rossabaker** [comment]
I think we have enough similar URI tickets, nothing novel to do here.
