### ISSUE TITLE
Populate the list of trailer headers (if present) in chunked requests

### ISSUE THREAD

**Issue by frejucafre** [http4s/http4s#566]
Chunked transfer-encoding may include trailer headers in the request after the last chunk. Http4s seems to parse these correctly but populating the list of them (accessed via `request.trailerHeaders`) seems to be currently not implemented.

Although the usage of trailer headers is not very common, there are some good use cases for them (e.g. passing the checksum of the request stream afterwards). Thus, it would be a useful feature to implement.

**Comment by rossabaker** [comment]
[The todo that needs to be todone](https://github.com/http4s/http4s/blob/3211616cad28f726b7cf7f042e81749222afb519/blaze-core/src/main/scala/org/http4s/blaze/Http1Stage.scala#L152)
