### ISSUE TITLE
Publish docs site for the 1.0

### ISSUE THREAD

**Issue by danicheg** [http4s/http4s#5674]
For now, we have links to page https://http4s.org/v1.0/downloads/ that lead to 404 (because of the recent publishing of the website). We need to publish the docs site for 1.0.

**Comment by danicheg** [comment]
It seems that the landing page of the website is returning 404 now 😮 
I think that because the website was published for the `0.22` and `0.23` versions and might be because of `includeLandingPage = false` setting (for `0.22` and `0.23`). But not 100% sure.

**Comment by armanbilge** [comment]
I think the problem is that series 0.22 and series 0.23 shouldn't be publishing the site at all? As I understand it, we have four laika websites:
1. the shared/unversioned pages. This includes the landing page.
2. /v0.22
3. /v0.23
4. /v1.0

(1) and (4) are published from the main branch. So series/0.22 and series/0.23 should only create their documentation pages and not the rest of the site.

**Comment by danicheg** [comment]
Also, I've noticed that building the website is failing (what strange for the JDK17 only) https://github.com/http4s/http4s/runs/4457849085?check_suite_focus=true#step:3:32. This reproduces locally on the JDK17 only too. I've made a fix for it in https://github.com/http4s/http4s/pull/5689/commits/4b24833446f1d8d103ad27fd6169b872a03587c2.

**Comment by armanbilge** [comment]
Site is back up for now :)

**Comment by danicheg** [comment]
Great! But the publishing of the docs site is still needed.

**Comment by armanbilge** [comment]
Also we still need to fix the problem which caused the site to go down.

**Comment by rossabaker** [comment]
When I fixed the default JDKs, I made the site build on 17 because it's an "app" and because people were grumpy about old JDKs.  It shouldn't really matter 8, 11, or 17 for that job.

**Comment by armanbilge** [comment]
Yeah, I don't think the JDK was specific to the issue. I think it's that each of our branch's builds is configured for its own docs and the shared site, when really only one of builds has that responsibility.

**Comment by rossabaker** [comment]
Yep, that division is how it used to work.

**Comment by armanbilge** [comment]
The 1(.0) site is now updated.
