### ISSUE TITLE
Document how to get cookies from a request

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#568]
As we improve our documentation, I'm going to start recording questions that are confusing our users.

> "is there a method for reading the cookies out of a request's headers?"

**Comment by reactormonk** [comment]
Kinda covered by https://github.com/http4s/http4s/blob/master/docs/src/main/tut/auth.md#cookies

**Comment by rossabaker** [comment]
While we're talking about cookies, it's very annoying that our Cookie value and our Cookie header have the same name.  Just as we have helpers for some other very common headers on Message (like Content-Type), I wonder if some cookie stuff there would be an improvement.

**Comment by bryce-anderson** [comment]
+1 to having the header and value the same name being a pain.

**Comment by rossabaker** [comment]
I don't have a good suggestion for which one's name should change or to what, which is why I wondered about just adding helpers to the message.  Overkill?  Maybe.

**Comment by rossabaker** [comment]
The header value is no longer the same.  If people have specific complaints here, please open a new ticket.
