### ISSUE TITLE
Improve release notes process

### ISSUE THREAD

**Issue by armanbilge** [http4s/http4s#5683]
Continuing from https://github.com/http4s/http4s/pull/5679#issuecomment-988381692.

**Comment by rossabaker** [comment]
Brain dump

## Naive GitHub approach

Run the GitHub automation and be done with it.

### Good

* Easy
* Credits authors.  Sort of.

### Bad

* Does not categorize meaningful PRs
* Misses cherry picks and reverts that aren't PRs.  (Mitigation: don't do that anymore.)
* Isn't branch aware.  (Mitigation: maybe we want to repeat forward merges?)
* Miscredits authors of multi-author PRs.

## Curated GitHub approach

What we did for 0.22.8 and 0.23.7.

### Good

* Credits authors

### Bad

* Labor intensive to categorize
* Manual search of cherry picks and reverts that aren't PRs.  (Mitigation: don't do that anymore.)
* Manual filtering of merges forward.  (Mitigation: maybe we want to repeat forward merges?)
* Miscredits authors of multi-author PRs.

## Ross Magit approach

What Ross has been doing for a long time

### Good

* Finds everything automatically
* Automatically filters merges forward
* Makes us think about what's noteworthy on each PR

### Bad

* Labor intensive replacing "Merge ..." with descriptions
* Labor intensive to categorize
* Nobody else knows how to do it (but the git commands aren't hard!)
* Manual credit to authors.  (I haven't bothered.)

## Add to changelog in each PR

### Good

* Finds everything if we're diligent
* Automatically filters merges forward
* Makes us think about what's noteworthy on each PR

### Bad

* Oh, $DEITY, the merge conflicts!!!
* Adds to burden of each merge
* Only works if we're diligent
* Manual credit to authors

## Release Drafter

Label each PR.  Let Release Drafter sort it out

### Good

* Automated release note drafts
* Can see at a glance if it may be worth releasing!
* Free categorization if the metadata is good

### Bad

* Requires a Principal Staff YAML Engineer to configure it
* Every PR must be labeled. (Mitigation: more automation to label Scala Steward?)

### Unknown

* Does it credit all the authors?
* Does it work across branches?

## Release more often

Works with any of the above!

### Good

* Makes them all suck less
* Features in user's hands quicker

### Bad

* Makes it suck more often
* More time spent overall doing it
* User release fatigue

**Comment by rossabaker** [comment]
On the main branch, GitHub autogenerate goes all the way back to 0.23.5. 👎

**Comment by armanbilge** [comment]
Crap. I was just feeling in favor of it, apparently it can be configured to categorize by label.
https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes

**Comment by rossabaker** [comment]
Oh.  Well, that configuration makes me feel a little better about the GitHub model.  It needn't be perfect.

For the main failure, I just went through my git command, categorized the relevant ones, fixed the link, and dumped the rest.  It was tedious, but it was also two months of PRs, which shouldn't be normal.

```
git log --grep='#' --format=oneline main ^series/0.23 ^v1.0.0-M29 --reverse
```

**Comment by armanbilge** [comment]
So in summary:

> Does not categorize meaningful PRs

Does, so long as we label PRs.

> Misses cherry picks and reverts that aren't PRs. (Mitigation: don't do that anymore.)

I'd argue PRs for everything are best practice anyway. CI and stuff.

> Isn't branch aware. (Mitigation: maybe we want to repeat forward merges?)

I wonder if we label each PR by its target branch, we can easily filter them out.

> Miscredits authors of multi-author PRs.

Eh, how often do these happen?

**Comment by rossabaker** [comment]
> > Does not categorize meaningful PRs

> Does, so long as we label PRs.

I used to label Breaking / Enhancement / Bugfix and which module.  Two levels is beyond this tool, and maybe too much anyway.  Which of those axes is more useful?

I started the module labels mostly in anticipation of the Great Schism, which still feels some ways off.

>> Misses cherry picks and reverts that aren't PRs. (Mitigation: don't do that anymore.)

> I'd argue PRs for everything are best practice anyway. CI and stuff.

This is enforced as of about 15 seconds ago.  We can still merge with failing checks, since our CI isn't yet perfect, and sometimes we just need partial credit.

>> Isn't branch aware. (Mitigation: maybe we want to repeat forward merges?)

> I wonder if we label each PR by its target branch, we can easily filter them out.

That sounds dreadful unless a workflow does it.

>> Miscredits authors of multi-author PRs.

> Eh, how often do these happen?

Mostly the cherry-picks, so mostly me plus a new contributor who doesn't know the branching.

**Comment by armanbilge** [comment]
> Which of those axes is more useful?

I like the per-module labels. The PR title should be informative about its content.

> That sounds dreadful unless a workflow does it.

Really? When you label the PR's module also label it's target branch. Not to undercut the value of a workflow assist :) but, not sure how this interacts with the double-labeling issue.

> Mostly the cherry-picks, so mostly me plus a new contributor who doesn't know the branching.

Right, I forgot that's how those work. Huh.

**Comment by armanbilge** [comment]
@rossabaker should we try and make a plan before we start merging lots of PRs again? 😅

**Comment by rossabaker** [comment]
Let's try #5690.  Let's try not to go two months between releases.  Worst thing that can happen with unlabeled versions is we have to cull some duplicates, and I bet we can workflow our way out of that.  I bet we can even workflow our way to labeling modules.

**Comment by armanbilge** [comment]
I think we're mostly happy with this, so I'll close.
