### ISSUE TITLE
Node.js ember-core TraversalSpec failure

### ISSUE THREAD

**Issue by armanbilge** [http4s/http4s#5684]
```
==> X org.http4s.ember.core.TraversalSpec.Request Encoder/Parser should preserve body with a known uri 0.63s munit.FailException: Failing seed: HpLPaM8JBl1x8n6MOA6WPN6oGhsCMVzbJcB5mmFWb4E=
You can reproduce this failure by adding the following override to your suite:

  override def scalaCheckInitialSeed = "HpLPaM8JBl1x8n6MOA6WPN6oGhsCMVzbJcB5mmFWb4E="
```
https://github.com/http4s/http4s/runs/4444713273?check_suite_focus=true#step:15:3387

**Comment by armanbilge** [comment]
Oh, is this a symptom of https://github.com/http4s/http4s/issues/3935?

**Comment by armanbilge** [comment]
Dupe of https://github.com/http4s/http4s/issues/2794.

**Comment by rossabaker** [comment]
[Another one](https://github.com/http4s/http4s/actions/runs/9522260793/job/26251453037#step:15:239), on 7c15478e7871eb19256e54ebd08140a673c124dd:

==> X org.http4s.ember.core.TraversalSpec.Request Encoder/Parser should preserve body with a known uri  0.863s munit.FailException: Failing seed: V7IhcNXi8qaV9zm8Bxm3vV7hUOb6FQwBf60MFFsfu_J=
You can reproduce this failure by adding the following override to your suite:

  override def scalaCheckInitialSeed = "V7IhcNXi8qaV9zm8Bxm3vV7hUOb6FQwBf60MFFsfu_J="
