### ISSUE TITLE
given EntityDecoder[IO, T] = jsonOf[IO, T] does not compile with Scala 3.1.0

### ISSUE THREAD

**Issue by vi-p4f** [http4s/http4s#5685]
This simple [example](https://github.com/vi-p4f/giventest) does not compile with Scala 3.1.0.

Replacing line 
```given EntityDecoder[IO, T] = jsonOf[IO, T]```
with
```implicit val d1: EntityDecoder[IO, T] = jsonOf[IO, T]```
solves the problem however it is not clear why it happens.

Compiler error message:
> [error] 38 |    val ioT: IO[T] = clientResource.use( _.run(request).use(_.as[T]) )
> [error]    |                                                                   ^
> [error]    |Cannot decode into a value of type T, because no EntityDecoder[cats.effect.IO, T] instance could be found.
> [error]    |
> [error]    |One of the following imports might fix the problem:
> [error]    |
> [error]    |  import Decoders.given_EntityDecoder_IO_T
> [error]    |  import org.http4s.circe.CirceEntityCodec.circeEntityDecoder
> [error]    |  import org.http4s.circe.CirceEntityDecoder.circeEntityDecoder
> [error]    |  import org.http4s.circe.CirceSensitiveDataEntityDecoder.circeEntityDecoder

**Comment by armanbilge** [comment]
Try replacing `import Decoders.*` with `import Decoders.given`.

**Comment by vi-p4f** [comment]
This solved the problem. I always forgot about this little catch. Thanks a lot!
