### ISSUE TITLE
Website is broken as of 0.23

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#5691]
https://github.com/http4s/http4s/runs/4458460635?check_suite_focus=true

Looks like the duplicate header names have made Laika sad.

**Comment by danicheg** [comment]
The fix is on the way in #5689. Will port it to 0.23/0.22.

**Comment by rossabaker** [comment]
We'll still need to republish it.  The jars worked for v0.23.7, but the site publish job failed.
