### ISSUE TITLE
Ember appears to support websockets but the Integrations page shows a question mark

### ISSUE THREAD

**Issue by yatesco** [http4s/http4s#5720]
https://http4s.org/v1.0/integrations/ shows:
![image](https://user-images.githubusercontent.com/181469/145709756-1c889df2-9733-4505-b1f1-71b08e7b5d89.png)

but https://github.com/http4s/http4s/discussions/5662 indicates that it does, pointing out that https://github.com/http4s/http4s/blob/c9f54a9bb2fc71c81031aa8ddf090e42bb564bd5/examples/ember/src/main/scala/com/example/http4s/ember/EmberServerSimpleExample.scala#L75 shows an example.

I don't know how to update the Integrations page, hence this issue and not a PR.

**Comment by armanbilge** [comment]
Don't know when, but this seems fixed.
