### ISSUE TITLE
Deprecation in v1.0 Static Files Tutorial

### ISSUE THREAD

**Issue by darkfrog26** [http4s/http4s#5823]
On https://http4s.org/v1.0/static/ it uses a deprecated signature of `BlazeServerBuilder`. Should look like:
```scala
  val app: Resource[IO, Server] = for {
    server <- BlazeServerBuilder[IO]
      .bindHttp(8080)
      .withHttpApp(fileService[IO](FileService.Config(".")).orNotFound)
      .resource
  } yield {
    server
  }
```

**Comment by rossabaker** [comment]
Triaging instead of looking, but I bet this is also true in 0.23...

**Comment by bplommer** [comment]
The `for` comprehension is also redundant - it should just be:
```scala
val app: Resource[IO, Server] =
  BlazeServerBuilder[IO]
    .bindHttp(8080)
    .withHttpApp(fileService[IO](FileService.Config(".")).orNotFound)
    .resource
```

**Comment by valencik** [comment]
Yeah this is definitely the case in 0.23

I'll tackle this after https://github.com/http4s/http4s/pull/5970
