### ISSUE TITLE
CI is hanging

### ISSUE THREAD

**Issue by armanbilge** [http4s/http4s#5844]
This is getting to be a pattern.

https://github.com/http4s/http4s/pull/5839#issuecomment-1008349663
https://github.com/http4s/http4s/runs/4767682086?check_suite_focus=true
https://github.com/http4s/http4s/runs/4767690258?check_suite_focus=true

**Comment by rossabaker** [comment]
Is this also related to the bind exceptions in #5843?

**Comment by rossabaker** [comment]
This is the earliest timeout I see, unless maybe someone reran an earlier one. https://github.com/http4s/http4s/actions/runs/1672936425

**Comment by rossabaker** [comment]
Has anybody observed this hang locally yet?  I am trying and have not.

**Comment by rossabaker** [comment]
But I can reproduce the bind exception erratically:

```
==> X org.http4s.ember.server.ConnectionSuite.close connection after response when request body stream is partially read 0.15s fs2.io.net.JavaScriptBindException: Address already in use
Caused by: scala.scalajs.js.JavaScriptException: Error: listen EADDRINUSE: address already in use 127.0.0.1:8080
```

**Comment by armanbilge** [comment]
Huh, I haven't seen Node.js jobs failing in CI lately, are they caught up in this too?

I think I know the story behind those bind exceptions though, multiple suites starting ember on the same port. I can probably fix that.

**Comment by armanbilge** [comment]
> Has anybody observed this hang locally yet? I am trying and have not.

Our local machines all probably have more cores than a GHA runner, maybe this can only be observed with 1-2 cores.

**Comment by armanbilge** [comment]
@rossabaker couple quick questions—when you are running the test suite locally, I assume you are running `test` for everything at once right? i.e. not `rootJVM/test` and `rootJS/test`, like we do in CI. Also, have you ever observed the `BindException` on JVM?

I was trying to understand why it's happening, but I didn't take into account that on your machine the JVM and Node.js test suites may be running simultaneously and could be conflicting with each other. This is why it doesn't happen in CI, and this is why the `Test / parallelExecution := false` setting doesn't save us here, since ember.jvm and ember.js are technically independent projects in our build.

**Comment by bplommer** [comment]
> Our local machines all probably have more cores than a GHA runner, maybe this can only be observed with 1-2 cores.

Should be reproducible in Docker?

**Comment by rossabaker** [comment]
Yes, I run `test`.  I'm surprised it matters with regards to ports: we should be binding to any available port instead of hardcoding ports.  I think you're right that I should be targeting one or the other to reproduce it in general, though.

I have not previously had luck using Docker to reproduce CI-only failures, nor does running on an underpowered Chromebooke.  Adjusting the global ExecutionContext used to be helpful, but I'm not sure that will work in a modern Cats-Effect world.

**Comment by armanbilge** [comment]
> I'm surprised it matters with regards to ports: we should be binding to any available port instead of hardcoding ports.

Gotcha, thanks. Then https://github.com/http4s/http4s/pull/5848 should fix that.

**Comment by armanbilge** [comment]
Our CI health just took another catastrophic plummet, see discussion in https://github.com/http4s/http4s/pull/5895#issuecomment-1016323697. It's exasperating.

**Comment by rossabaker** [comment]
I'm going to try to focus on this.  I don't think we can release past 0.22 in this state.

**Comment by rossabaker** [comment]
It's not perfect yet, but we're unhung.
