### ISSUE TITLE
error-handling with fetchAs

### ISSUE THREAD

**Issue by ceedubs** [http4s/http4s#587]
`Client.fetchAs` doesn't give you access to the status code of the response, so one could reasonably assume that it only returns a successful `Task` in the success case. However, it completely ignores the status code. So if you do something like `fetchAs[String]` and the server responds with a `500`, you get a successful `Task` wrapping an empty string (or whatever the body was). With this approach there's not a good way to distinguish that result from the `200` response body that you were expecting.

There was [some discussion](https://gitter.im/http4s/http4s?at=56f5ac5376b6f9de194b59f8) about this on Gitter.

**Comment by hvesalai** [comment]
+1 on this. `fetchAs` should only return the value if the response was a success with entity (namely `200 OK`). Even other success responses (like, for example, `204 No Content`) should *not* return a successful Task since they do not have the requested entity.

**Comment by rossabaker** [comment]
+1 to the general concept.

I'm not sure I see the harm in returning a 204's entity if it has one.  I consume an API that intentionally violates the spec like that. :disappointed:  I strongly believe that we should keep making it difficult to produce a 204 with an entity.

More questions:

1. What does `fetchAs` return on a non-2xx?  A failed task with some sort of `UnsuccessfulResponse(response)`?
2. Is it okay that `fetchAs` assumes success while `fetch` handles all responses?  I like the semantics of `fetch`, and the proposed semantics of `fetchAs`.  How confusing is it to have these two with similar names?
3. A lot of people are lifting things into EitherT.  Maybe some sort of `attemptFetchAs`.  I see three classes of things that can go wrong:
   1. Network failure.  I'm happy making this a failed task.
   2. Decode errors.  This is a good candidatefor EitherT's left.
   3. Unsuccessful response.  This is also a good candidate for EitherT's left.  But if we're already handling decode errors, we've just widened the type of the left.  Is that okay?

**Comment by hvesalai** [comment]
- A `204` with an entity is not possibly in HTTP, so I don't see why it should be supported.
- I think it's OK for fetch to handle all cases while fetchAs expects a success with an entity
- I like `attemptFetchAs`

We have an API that returns 204 when there is no content and 200 when there is something. In this case for us 204 is not an error, it's a successful result, just without a result. Thus we would need to differentiate between entity, no entity, error. The way we do it is when using `fetchAs[String]` we return empty string for 204 and for `fetchAs[Json]` we return jNull.

**Comment by ceedubs** [comment]
I'd be fine with any 2xx returning a a successful `Task`. There's potentially an argument for not even bothering with trying to read the body if the response is 204, but I don't have particularly strong feelings about this.

I'm wondering if network failures and decoding errors are both errors that you are less likely to try to recover from while a 404 is something that you might turn into a `None`, a `401` might trigger some authentication logic, etc. So I'm wondering if network failures and decode errors are best handled by a failed `Task` and non-success status codes should be the use-case for something like `EitherT`.

I've also thought about whether it might make sense to create a `ResponseDecoder` similar to `EntityDecoder` (and some may require implicit `EntityDecoder`s) but that also gets to look at the status code of the response. Then I could see people creating their own custom `ResponseDecoders` that handle 404s, 401s, etc and return disjunctions etc depending on how they want to handle errors. I'll ponder this a bit more over the next couple of days as I set up some error-handling in some of my code.

**Comment by rossabaker** [comment]
Proposed strategy after [gitter conversation](https://gitter.im/http4s/http4s?at=574deaf2ec10ddbb09dc788a):

* Leave `fetch` alone.
* Deprecate `fetchAs`, because it has surprising semantics.
* Add `expect[A]: Task[A]`, which returns a failed task wrapping the static code if status is not successful.
* Add `attemptFetchAs[A, B](onFailure: Response => Task[B]): Task[B \/ A]` to do principled error handling with all the power of the former `fetchAs`.

**Comment by rossabaker** [comment]
#629 does not include `attemptFetchAs`.  Do people want this?
