### ISSUE TITLE
Typelevel Incubator application

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#588]
I would like to apply for Typelevel Incubator status for http4s.  

The criteria are:

1. There must be a consensus amongst the project's stakeholders that they want to join Typelevel.
   * To be assessed by this ticket.
2. The project must be willing to support the Typelevel code of conduct or something equivalent.
   * Our [code of conduct](http://http4s.org/community/conduct.html) is a copy-and-paste-and-sed of theirs.
3. The project should be aiming to promote pure, typeful, idiomatic functional programming in Scala.
   * Combining these principles with HTTP is why we are here.
4. If the primary output of the project is software artefacts then it should aim to complement them with accessible, idiomatic documentation.
   * A known weak point, but have a new tut-based infrastructure that will help us improve here.

http4s can help Typelevel by providing an HTTP library that shares their principles, both technical and non-technical.  Typelevel can help http4s through the visibility and prestige that comes with that association.

Shall we?

**Comment by rossabaker** [comment]
Personal statement: I will always value the contributions of those who are ambivalent to the non-technical goals of Typelevel.  I also have a six-year-old daughter who already thinks girls don't need math.  I hope she sends us the pull request for a Dotty cross build someday, and I think this helps.

**Comment by bryce-anderson** [comment]
I'm vote 'yea'. I think being a typelevel project could bring a lot of new interest, contributors, and most importantly, ideas to http4s.

I reserve the right to change my mind if I hear some compelling 'nay' arguments.

**Comment by refried** [comment]
I can’t think of any reason not to, can anyone else? Is there anything bad
about typelevel?

**Comment by LeifW** [comment]
Sounds good to me.

**Comment by julien-truffaut** [comment]
:+1:

**Comment by refried** [comment]
:+1:

**Comment by rossabaker** [comment]
This looks like a strong mandate to me.  Thanks, everyone.

**Comment by rossabaker** [comment]
The application is approved.  Hooray!
