### ISSUE TITLE
git workspace is dirtied in CI

### ISSUE THREAD

**Issue by armanbilge** [http4s/http4s#5917]
The snapshot in https://github.com/http4s/http4s/runs/4887900416 was versioned as `0.22.8-231-9327a8b-20220120T201924Z-SNAPSHOT`. The addition of the date/timestamp indicates that the git workspace was dirty.

**Comment by armanbilge** [comment]
Huh, but the `git status` run immediately before the publish step comes up clean. This could be an sbt-typelevel bug.

**Comment by rossabaker** [comment]
I hit this on a different project recently, forget which, and it was a header.

**Comment by armanbilge** [comment]
Yeah, those are the usual suspects. Except CI should specifically check for those and fail if they are missing/wrong.

**Comment by rossabaker** [comment]
Something was changing the headers before the check, so they were right when the check ran.  I figured it out by adding `git status` workflow steps as a form of debugging.

**Comment by armanbilge** [comment]
Ah, you were right 😁 I wasn't scouring the log hard enough.
```
 [info] Headers created for 3 files:
[info]   /home/runner/work/http4s/http4s/scalafix-internal/rules/src/main/scala-2/fix/UseLiteralsSyntax.scala
[info]   /home/runner/work/http4s/http4s/scalafix-internal/rules/src/main/scala-2/fix/GeneralLinters.scala
[info]   /home/runner/work/http4s/http4s/scalafix-internal/rules/src/main/scala-2/fix/package.scala
```
