### ISSUE TITLE
http4s.org main page down

### ISSUE THREAD

**Issue by reactormonk** [http4s/http4s#5919]
https://http4s.org/

![Screenshot_20220121_012520](https://user-images.githubusercontent.com/49185/150443648-58a3ec4f-2a12-40a6-b552-c255c2defdc5.png)

<hr />

[Added by @rossabaker]:

* [X] restore site
* [X] recreate cert for gh-pages
* [x] restore Laika site for 0.22
* [x] restore Laika site for 0.23
* [x] fix localhost link in header of 1.0
* [X] recreate jdk-http-client cert for gh-pages
* [x] restore jdk-http-client site

**Comment by armanbilge** [comment]
Thanks for reporting.

This is a combination of our site publishing pipeline already being broken + enabling snapshots on 0.22 (I forgot that publishing the site is tagged on to the end of a publish job).

**Comment by rossabaker** [comment]
Do we need to roll back the snapshots and republish the website project manually?

**Comment by armanbilge** [comment]
Yeah, that's probably the easiest fix. To restore the website we could probably just rollback the gh-pages branch as well.

I would like to fix the site, but it's too daunting right now.

**Comment by rossabaker** [comment]
It's easy to restore the site.  I'm just mostly worried about the problem coming back.  I'll rollback #5908 and then roll back the branch.

**Comment by rossabaker** [comment]
a8fa9cfa33c0a2fb2d8b0cf7a405c1a86fb3b38a should restore the site, and #5920 should stop it from happening again until we have a better idea.

**Comment by rossabaker** [comment]
This is back, probably from the 0.22.9 release this morning.

**Comment by armanbilge** [comment]
I actually never saw the site restored even after https://github.com/http4s/http4s/commit/a8fa9cfa33c0a2fb2d8b0cf7a405c1a86fb3b38a.

**Comment by rossabaker** [comment]
The restoration job timed out, and I'm the only one who can see it, because Netlify doesn't have open source plans.  We need to get that rolled back to GitHub, but it's going to break the redirects when we do.

I reverted it to January 7, before the snapshot published, but now 0.22 and 0.23 have the Hugo theme, and the header in the 1.0 version links to 127.0.0.1, and I don't understand how any of it works anymore. :shrug:

**Comment by rossabaker** [comment]
I switched back to GitHub Pages.  Things will be broken, but things were already broken, and now other people can help.

**Comment by rossabaker** [comment]
It may take 30-60 minutes for that cert error to go away.

@amesgen, this is also going to affect the jdk-http-client site.  I've set up the CNAME, but GitHub is still having trouble seeing it.

**Comment by rossabaker** [comment]
0.23.8 killed it again.  I will fix it.

Outside of the more ambitious typelevel/sbt-typelevel#100, we need to fix that regression.

**Comment by rossabaker** [comment]
The 0.22.10 release is likely to kill it, because we still haven't fixed it.  The solution is to roll back the head commit of gh-pages branch.  I will not be around to it until very late this evening.

**Comment by rossabaker** [comment]
I canceled the pages deployment before heading out, so maybe we're safe.  (The site is getting increasingly stale until we do something about this, though.)

**Comment by rossabaker** [comment]
This shit sucks.  I had to revert two more commits.  I don't even know where they're coming from anymore.

**Comment by armanbilge** [comment]
Should we just disable site publishing completely for now? The site will be frozen, but at least it will be there.

**Comment by rossabaker** [comment]
I don't figure the actual problem is too hard to find.  I just haven't managed to prioritize it.  Could probably get a real good guess just by looking at the commits I've reverted.

**Comment by armanbilge** [comment]
Come to think of it, those two commits you reverted were probably due to the release 0.22.10 and 0.23.9 the other day. Unless, you'd already reverted for those?

**Comment by armanbilge** [comment]
This is next on my hit list, using all the latest site plugin stuff.

**Comment by armanbilge** [comment]
Ha, didn't take me long to get disillusioned 😵 

I'm taking an aggressive strategy and prioritizing minimal config over the bells and whistles. Right now it's a lot of settings and custom extensions and hacks and IMHO these are just not worth it. There's something to be said for a site that very nearly configures itself and behaves exactly like the Laika sites in every other Typelevel project (I hope Cats will migrate too btw).

I think we may end up with broken URLs, but we'll see.

\</rant>

**Comment by armanbilge** [comment]
@rossabaker are we feeling pretty good about this? Everything seems to be roughly working:
- https://http4s.org/
- https://www.javadoc.io/doc/org.http4s/http4s-docs_2.13
- redirects, e.g. https://http4s.org/versions, https://http4s.org/v1.0/cors

Some of the API doc links still need to catch up, but this should all resolve itself.

**Comment by rossabaker** [comment]
We haven't tested that a release from main doesn't make a mess, and we got a community contrib to 0.21.  If either of those break things, we can reopen.  But I'd say declare victory here.

Very nice work.
