### ISSUE TITLE
Release notes configuration is broken

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#5936]
`Invalid release notes configuration: The property '#/changelog/exclude/labels' of type null did not match the following type: array`

**Comment by rossabaker** [comment]
I'm not that optimistic it was going to work anyway.  That GitHub feature has been fucked up on several simpler projects I've tried it on.  I wonder whether we wouldn't be better off auto-populating milestones, and we could just assemble from those.

**Comment by rossabaker** [comment]
Okay, #5937 generates notes. :tada:  Let's see how it goes.  The real test will be 0.23: it's the subsequent branches that have been full of Type I and Type II errors on other repos.

**Comment by rossabaker** [comment]
I should clarify my grumpiness: I think the workflow here is a good start.  I find the underlying GitHub feature has been unreliable.

**Comment by armanbilge** [comment]
Yeah, no worries :) I've also been frustrated with the underlying feature's inability to understand pre-releases.
