### ISSUE TITLE
Syncing up docs across branches

### ISSUE THREAD

**Issue by valencik** [http4s/http4s#5978]
In working on a few mdoc related PRs I've noticed that tweaks or fixes may happen in one branch but not others.

Consider the oauth1 fix in streaming.md happening in v1.0.0 here: https://github.com/http4s/http4s/commit/c6f350d53ee68e6a00033e0c989c392493dc9510
But not yet in v0.23 (PR here: https://github.com/http4s/http4s/pull/5979)

What's the best way to make sure I don't exacerbate the issue with upcoming doc tweaks?
After merging a doc tweak to v0.23 should I open another PR against v1.0.0?
Additionally, should I also target v0.22?

**Comment by armanbilge** [comment]
@valencik Thanks for asking, and all your good work on docs :)

> Additionally, should I also target v0.22?

Yes, if possible, ideally you should target your changes to series/0.22.

 > After merging a doc tweak to v0.23 should I open another PR against v1.0.0?

For most changes hopefully this won't be necessary: we regularly merge 0.22 -> 0.23 -> main. Heck, the other day we got docs fixes for 0.18 in f795a2329a06104a75a2f754fbf1075af540de06 and you'll even find that commit in main 😆

**Comment by rossabaker** [comment]
I'm immersed in a download data spreadsheet... maybe don't work too hard on 2.12 yet!

**Comment by rossabaker** [comment]
I meant 0.22, but I've got lots of columns here. :laughing:

**Comment by valencik** [comment]
Looking at the numbers in https://github.com/http4s/http4s/discussions/5982 should I be targeting 0.21 for doc tweaks? Or do we just do 0.23 and 1.0, dropping 0.22?

**Comment by armanbilge** [comment]
@valencik is going to work on moving the mdocs to from 2.12 to 2.13, following a brief Discord discussion. Before today's numbers it already made good sense IMO as the median Scala version in our matrix. It makes even more sense with https://github.com/http4s/http4s/pull/5337 on the horizon.

**Comment by rossabaker** [comment]
It was only on 2.12 because the tooling didn't work at all on 2.13 at first, and inertia took over.  2.13 is good.

As for http4s, I like the focus on 0.23.  The 0.22/0.23 strategy came at a time of high uncertainty between Scala 3 and CE3, and it's clear now that people are going to CE3 before Scala 3.

**Comment by armanbilge** [comment]
I think we're good on this.
