### ISSUE TITLE
mount `HttpService` to different thread pool

### ISSUE THREAD

**Issue by shengc** [http4s/http4s#601]
It is kind of a bad idea to let all `HttpService` run in the same thread pool in _some_ scenarios. Let's say I want to throttle the rate for handling the requests coming at a particular route, while serve as fast as possible for the other one. I don't know if this is possible out of the box in the current code base. If yes, could you point me to its whereabouts? Thanks!

**Comment by hvesalai** [comment]
You can always fork the Tasks. That's what we do. For each service we fork it to either _interactive_ or _background_ `ExecutorService`. You could have a single thread servicing the background excutor and a large thread pool servicing the interactive.

However, at some point you need to start rejecting the background requests. Otherwise you will run of open files, memory, or both.

**Comment by rossabaker** [comment]
I agree that filling up a thread pool is not a good means of throttling.  This would be a good candidate for a middleware.  Something that acquires a token on the way in, releases a token on the way out, and rejects the request when no token is available.  

Still, there can be value in isolating thread pools.  Forking is one option.  Another option on a servlet backend is to wrap it in an `Http4sServlet`, which takes an executor as an argument.  (That servlet is typically hidden behind the `mountService` signature.)  We could also consider adding an optional executor to the `mountService` signature.

**Comment by shengc** [comment]
I think `fork` is an option I can accept for now. In the long term, adding an option to the server builder to mount `HttpService` to different `ExecutorService` would be quite neat.

**Comment by rossabaker** [comment]
I think shift is still the proper approach here vs. complicating the server builder interface with things that we can do easily with cats-effect and Kleisli primitives.
