### ISSUE TITLE
v0.23 website is out of sync with the repo

### ISSUE THREAD

**Issue by bplommer** [http4s/http4s#6026]
https://http4s.org/v0.23/cors/ is not up to date with the new, fixed version of the CORS middleware, although the sources in the repo (https://github.com/http4s/http4s/blob/series%2F0.23/docs/src/main/mdoc/cors.md) are. Both the 0.22 and the 1.0 versions of the page are up to date 🤔

**Comment by rossabaker** [comment]
Because of #5919, I've been reverting the website every time we publish.  It may be related to that, but I can't explain 0.22 vs. 0.23.

**Comment by armanbilge** [comment]
Everything should be up-to-date now.
