### ISSUE TITLE
Change default branch to `series/0.23`?

### ISSUE THREAD

**Issue by armanbilge** [http4s/http4s#6040]
1. Most PRs probably want to target a stable branch. Many of them are targeting `main`.
2. It's easier to merge a PR originally targeted at `series/0.23` into `main` than it is to cherry-pick a PR onto an old branch, which also messes up our automated release notes.

**Comment by rossabaker** [comment]
It's kind of weird to have a `main` that _isn't_ the default.  We might want to rename that to `series/1.x`.  But :+1:.

**Comment by armanbilge** [comment]
While we're doing this (I think it'll have to be an admin) it might be nice to cleanup some of the stale branches as well.

**Comment by rossabaker** [comment]
I lost track of this one.  It should probably happen after the dust settles on the website?

**Comment by armanbilge** [comment]
Changing the default branch can happen whenever. Renaming `main` requires us to be more thoughtful.

**Comment by rossabaker** [comment]
Okay, default branch changed.  Left main alone until the dust settles and I'm feeling more thoughtful.

**Comment by danicheg** [comment]
It happened, so I'm closing this.
