### ISSUE TITLE
KeepAliveSuite.Keep-Alive flake Scala 3

### ISSUE THREAD

**Issue by hamnis** [http4s/http4s#6059]
==> X org.http4s.headers.KeepAliveSuite.Keep-Alive: header.parse(a.value) == right(a)"  0.085s munit.FailException: Failing seed: 1VE4-Kn23Ku3oLhvMg2G7YDpGmZxPwlxVDvK_x7wW_C=
You can reproduce this failure by adding the following override to your suite:

  override val scalaCheckInitialSeed = "1VE4-Kn23Ku3oLhvMg2G7YDpGmZxPwlxVDvK_x7wW_C="

Exception raised on property evaluation.
> Exception: org.http4s.ParseFailure: Invalid Keep-Alive header: Reserved token of list List(token, max) was found in the extensions.
    at munit.ScalaCheckSuite.propToTry(ScalaCheckSuite.scala:98)
Caused by: org.http4s.ParseFailure: Invalid Keep-Alive header: Reserved token of list List(token, max) was found in the extensions.

**Comment by rossabaker** [comment]
[Different test](https://github.com/http4s/http4s/runs/5686746129?check_suite_focus=true#step:12:1162), same exception:

```
==> X org.http4s.headers.KeepAliveSuite.Keep-Alive: header.renderString == "name: value"  0.042s munit.FailException: Failing seed: mL7Ax3Y2spY7TC0xRCvVrn004HEAGoFRRtJaWoxiXTM=
You can reproduce this failure by adding the following override to your suite:

  override val scalaCheckInitialSeed = "mL7Ax3Y2spY7TC0xRCvVrn004HEAGoFRRtJaWoxiXTM="

Exception raised on property evaluation.
> Exception: org.http4s.ParseFailure: Invalid Keep-Alive header: Reserved token of list List(token, max) was found in the extensions.
    at munit.ScalaCheckSuite.propToTry(ScalaCheckSuite.scala:98)
Caused by: org.http4s.ParseFailure: Invalid Keep-Alive header: Reserved token of list List(token, max) was found in the extensions.
```
