### ISSUE TITLE
Further relax cookie parsing? 

### ISSUE THREAD

**Issue by kailuowang** [http4s/http4s#6067]
Similar to #4003, a double quote in a third-party cookie will break cookie parsing in Http4s. For example, the cookie set by Google's "Sign in with Google" button has double quotes in it and thus silently broke the cookie parsing in Http4s (`request.cookies` becomes empty even though there are other cookies. ) 

In this [discussion](https://groups.google.com/a/chromium.org/g/chromium-discuss/c/T3oHExJMr0M), Ryan from Chromium pointed out that the RFC6265 has two sections specifying the requirements for cookie value. Apparently, the requirements defined in section 5.2 are less strict than section 4.1.1 implemented by Http4s. Thus [Chromum allows](https://source.chromium.org/chromium/chromium/src/+/main:net/cookies/parsed_cookie.cc;drc=1241c4db3549f497bcaa14815cc6b232a32cf534;l=497) all ASCII chars except control characters and `;`

Based on these considerations, is it possible to further relax `RelaxedCookies` to conform to the requirements set by Chromium?

**Comment by kailuowang** [comment]
If we can get some maintainer approval, I am happy to submit a PR. I don't see why http4s should be failing on cookie parsing due to unnecessary enforcement of a poorly specified cookie spec.

**Comment by kailuowang** [comment]
> It's messed up people broke the spec so much they are just editing the spec.

I would say that the web stack (HTTP, HTML, CSS, JS) overall is not as principled as functional programmers are used to.

**Comment by rossabaker** [comment]
There's a PR that tries to provide an ABNF for the more relaxed rules.  It still has some open problems, but worth reading: https://github.com/httpwg/http-extensions/pull/1759

**Comment by rossabaker** [comment]
The Section 4 rules on what we send are SHOULD and the Section 5 rules on what we parse are MUST.  I don't think this is a case of standards vs. practice: they both say we should fix this.

**Comment by kailuowang** [comment]
Thanks @rossabaker ,  
I just noticed that http4s seems to be missing the range `0x80` to `0xFF`. which is specified in both sections. (`0x7F` seems to be excluded in section 4.4.1 but very [ambiguously](https://github.com/httpwg/http-extensions/issues/1399#issuecomment-1058097695) )

**Comment by rossabaker** [comment]
Fixed by #6082.
