### ISSUE TITLE
Preparing for Scala 2.12

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#613]
Unresolved dependencies for a scala-2.12.0-M4 build.  Not yet exhaustive, because it can't get past these for deeper modules:
- [x] org.http4s#http4s-websocket_2.12.0-M4;0.1.3: not found
- [x] org.log4s#log4s_2.12.0-M4;1.1.5: not found
- [ ] org.parboiled#parboiled_2.12.0-M4;2.1.1: not found
- [x] org.scalaz.stream#scalaz-stream_2.12.0-M4;0.8: not found
- [ ] org.scoverage#scalac-scoverage-plugin_2.12.0-M4;1.1.0: not found
- [ ] org.scoverage#scalac-scoverage-runtime_2.12.0-M4;1.1.0: not found
- [x] org.specs2#specs2-core_2.12.0-M4;3.7.2-scalaz-7.1.7: not found
- [x] org.specs2#specs2-matcher-extra_2.12.0-M4;3.7.2-scalaz-7.1.7: not found
- [ ] org.specs2#specs2-scalacheck_2.12.0-M4;3.7.2-scalaz-7.1.7: not found
- [ ] org.typelevel#discipline_2.12.0-M4;0.4: not found

**Comment by bryce-anderson** [comment]
@rossabaker, I believe this is complete. I'll close this in a day or so unless you let me know I'm wrong.

**Comment by rossabaker** [comment]
🏁
