### ISSUE TITLE
Enable Github Two-Factor Requirement

### ISSUE THREAD

**Issue by ChristopherDavenport** [http4s/http4s#6144]
As of this moment this is not a requirement to be a member of the org.

It is put forward for consideration that this should be enabled to help guarantee that http4s organization members are secure in their interaction with code.

A note that if enabled will silent kick anyone who does not have it enabled.

> Members, billing managers, and outside collaborators who do not have two-factor authentication enabled for their personal account will be removed from the organization and will receive an email notifying them about the change.

@http4s/maintainers

**Comment by RafalSumislawski** [comment]
Prompted by this post, I just enabled 2FA for myself. And I think it's a good idea to enable it as requirement in the org, but preferrably without the silent-kicking-out-of-org part. Can we see who would be kicked before we make the decision to enable it?

**Comment by rossabaker** [comment]
Oh, this also impacts outside collaborators.  Making a couple more contacts...

**Comment by armanbilge** [comment]
I think we're ready to go on this one 👍

**Comment by rossabaker** [comment]
Done.
