### ISSUE TITLE
Client backends should support web sockets

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#615]
- [ ] blaze-client
- [ ] async-http-client

**Comment by rossabaker** [comment]
WIP is on the topic/async-http-client-websockets branch.

**Comment by rossabaker** [comment]
What should the interface look like here?

* `client.webSocket(Request): Task[WebSocket]`: No `Response` if status != 101.
* `client.webSocket(Request)(WebSocket => Task[A]): Task[A]`: similar to the above.  Do we need a callback interface to close the connection, or does the natural closing of the web socket suffice?
* `client.webSocket(Request): Task[Response]: get `WebSocket` from attribute.  Supports failure, but async-http-client doesn't appear to return anything but a status on non-101.
* Variations of the above, with `Uri` and `Headers` instead of `Request`: prevents sending bad methods or entity bodies.

**Comment by rossabaker** [comment]
I think I don't hate [this interface](https://github.com/http4s/http4s/blob/f19a2aecc76f13750d3090d1149a5111e162c8b7/client/src/main/scala/org/http4s/client/Client.scala#L178-L197).

**Comment by rossabaker** [comment]
See #618.

**Comment by andyscott** [comment]
Are there any updates on this? I've been toying with the 618 PR branch and would be interested in seeing this in future releases.

**Comment by rossabaker** [comment]
This got put on the backburner while we discussed other issues and major contributors changed jobs and such, but it's still very wanted.

@bryce-anderson, any thoughts on #618 and how it fits into blaze-client?  I know you were thinking about that side of the house.

**Comment by rossabaker** [comment]
This isn't low-hanging fruit, but it's an issue that would make a lot of people very happy if someone wants to dive in.

**Comment by rossabaker** [comment]
Duplicate of #330.
