### ISSUE TITLE
Releases from v0.21 completely destroy the site

### ISSUE THREAD

**Issue by armanbilge** [http4s/http4s#6150]
I didn't see this one coming 😓 https://github.com/http4s/http4s/commit/1e67876ff4113d7c143ba6c8d174c9f3139eaef7

**Comment by armanbilge** [comment]
Manually reverted.

**Comment by rossabaker** [comment]
I had a hunch.  Thanks for checking.

**Comment by rossabaker** [comment]
Fixed by #6151.
