### ISSUE TITLE
Documentation gap for Multipart handling

### ISSUE THREAD

**Issue by Daenyth** [http4s/http4s#6202]
If we have docs for Multipart, I couldn't find them

There's no top-level page in the nav for it
"multipart" doesn't show up on the "entity handling" page

**Comment by armanbilge** [comment]
(Tangential, but @valencik this is an example where search functionality would be awesome!)

**Comment by fredshonorio** [comment]
I've added https://github.com/http4s/http4s/pull/7328, reviews welcome
