### ISSUE TITLE
Publish testing module internally?

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#6229]
To get the schismatic http4s-servlet repo compiling, I had to copy the code from `testing`.  This will be a problem as we spin off more modules.  We might want to publish that, without MiMa guarantees, and everything tightly locked down to `private[http4s]`.

**Comment by armanbilge** [comment]
Yes, IMO this is essential. See also https://github.com/http4s/http4s/issues/5320.

Should be straightforward. Add the `private` modifiers, remove this line, and set `mimaPreviousArtifacts := Set.empty` or something.
https://github.com/http4s/http4s/blob/7ca6dc150641a3915e31beb29ab6f862b566c7c1/build.sbt#L308

**Comment by rossabaker** [comment]
#5320 is the interesting part.  I think we can live without this.
