### ISSUE TITLE
Remove examples, which have been relocated

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#6232]
All examples have been exported to the [http4s-examples](https://github.com/http4s/http4s-examples) repo.  This is the first step of The Great Schism, because it's all the leaf nodes, and some things we want to move out of this repo are depended upon by the examples.

**Comment by armanbilge** [comment]
Is this just an `rm` PR? I like deleting 😁

**Comment by rossabaker** [comment]
Having some second thoughts on this. As I was splitting repos, I got annoyed how often I was duplicating ExampleService. But that is as much a sketchpad as a cohesive example.  The new examples repo is still a junk drawer.  This is an opportunity to have a simple example relevant to each repo.

**Comment by armanbilge** [comment]
I agree with that. I thought it was a bit odd the ember examples moved out of core, since ember will continue living here.
