### ISSUE TITLE
Question: Client persistent connection

### ISSUE THREAD

**Issue by nihil-admirari** [http4s/http4s#6312]
In [`Client` ScalaDoc](https://www.javadoc.io/doc/org.http4s/http4s-docs_3/latest/org/http4s/client/Client.html), all requesting methods (`expect`, `fetchAs`, `get`) say that:
> The underlying HTTP connection is closed at the completion of the decoding.

How to keep the connection open across multiple requests?

More generally, libraries such as Python's `requests` have the notion of [`Session`s](https://docs.python-requests.org/en/latest/user/advanced/#session-objects), which preserve cookies etc. Does `http4s` support anything like that?

**Comment by rossabaker** [comment]
> In [](https://github.com/http4s/http4s/issues/6312#issue-1208127518)In [Client ScalaDoc](https://www.javadoc.io/doc/org.http4s/http4s-docs_3/latest/org/http4s/client/Client.html), all requesting methods (expect, fetchAs, get) say that:
> 
>     The underlying HTTP connection is closed at the completion of the decoding.

That's very poorly phrased in the docs.  We _release_ the connection, which may either close the connection or return it to a pool for reuse on a subsequent request to the same host and port.  There are cases that HTTP does not let us reuse the connection (e.g., when the response sends an explicit `Connection: close` header), but generally, if we can reuse, we do.

> More generally, libraries such as Python's requests have the notion of [Sessions](https://docs.python-requests.org/en/latest/user/advanced/#session-objects), which preserve cookies etc. Does http4s support anything like that?

There is a [CookieJar](https://github.com/http4s/http4s/blob/649f06ab1d80d986de0c84cb071e80942592d0ae/client/shared/src/main/scala/org/http4s/client/middleware/CookieJar.scala#L81-L82) middleware that wraps a client and manages cookies.  `impl` is the simplest constructor, but there are more powerful ones that return a reference to the jar and give finer grained control.
