### ISSUE TITLE
Depend on scalaz-stream that builds against scodec-bits-1.1

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#632]
We had a user hit an issue when using http4s with remotely.  We inherit scodec-bits-1.0 from scalaz-stream, whereas remotely builds against scodec-bits-1.1.

scalaz-stream plans to release a build against scodec-bits-1.1.  We need to rebuild against that, and then it will be possible to build an http4s/remotely stack again.

**Comment by rossabaker** [comment]
This is the last change I want to get in before 0.14.0.  We expect the scalaz-stream release in the next day or two, and I will cut a release after that against the new scalaz-stream.

If anyone sees a reason this is a bad idea, speak before I tag it.

/cc @ahjohannessen, @etorreborre

**Comment by etorreborre** [comment]
@rossabaker it's all good for me.

**Comment by ahjohannessen** [comment]
@rossabaker 👍
