### ISSUE TITLE
Don't create redundant `Ref` in the `Client#fromHttpApp`

### ISSUE THREAD

**Issue by danicheg** [http4s/http4s#6326]
This is a follow-up from https://github.com/http4s/http4s/pull/6325.
Ross made a [proposal](https://github.com/http4s/http4s/pull/6325#pullrequestreview-951279467) that we can don't create `Ref` in a case when the request/response body isn't streaming. 
One should keep in mind, that a single `Ref` instance is reusing.

**Comment by omaximov** [comment]
I'd like to take a crack at this, if that's okay!

**Comment by armanbilge** [comment]
That's wonderful, thank you!

**Comment by omaximov** [comment]
What's the ideal timeline on getting this implemented? I've been rather swamped at work lately, and I'm not *super* familiar with cats-effect or http4s. But I'd like to be! So it may be two weeks before I get a chance to really dig in and familiarize myself with the tech to come up with a solution. Maybe it'll be a quick fix but I don't want to half-ass it.

**Comment by danicheg** [comment]
Currently, no one is working on this issue, so it's up to you exactly 👍🏻

**Comment by geoffjohn11** [comment]
@omaximov I took a look at this issue and thought I would try it.  Don't want to step on your toes, though.  If you'd like you can use my PR (if it's the right approach).

**Comment by omaximov** [comment]
Please do! I admittedly let this issue get away from me

**Comment by geoffjohn11** [comment]
Addressed in https://github.com/http4s/http4s/pull/6654
