### ISSUE TITLE
Status reason currently not set

### ISSUE THREAD

**Issue by travisblakeney** [http4s/http4s#635]
The Status.scala function with signature

`private def mkStatus(code: Int, reason: String = ""): ParseResult[Status] `

currently takes the reason phrase in but doesn't set it on the Status class as part of the ParseResult. 

Are you happy to accept a PR to fix this?

**Comment by rossabaker** [comment]
Yes, please! Thank you for finding this.

**Comment by travisblakeney** [comment]
Shall I issue it against any particular branch?

**Comment by rossabaker** [comment]
release-0.13.x would be ideal, and then I can also merge that to master.
Thanks!
