### ISSUE TITLE
Use a version of argonaut such that its scalaz dependency would be compatible with ours

### ISSUE THREAD

**Issue by gwils** [http4s/http4s#640]
Between argonaut 6.1 and 6.2 the project was split out so that all the scalaz parts were in a separate package called argonaut-scalaz. Currently http4s uses argonaut 6.2-M1. The scalaz parts are in a corresponding argonaut-scalaz 6.2-M1, which http4s does not depend on.

http4s goes to great lengths to make sure it works with both scalaz 7.1.x and 7.2.y. But argonaut-scalaz 6.2-M1 and even 6.2-M2 will **only** work with scalaz 7.2.x. So I'm in the unfortunate position of being unable to use argonaut-scalaz and http4s 0.13.2 together in the same project.

Argonaut has recently released 6.1a, which is like 6.1, but with scalaz 7.2.x. If we moved back from argonaut 6.2-M1 to 6.1, we could support both versions of scalaz via 6.1a as we are with specs2, jawn, etc.

**Comment by rossabaker** [comment]
Thanks.  This is more evidence we're doing the right thing on #637.
