### ISSUE TITLE
ember-server hanging on cancellation

### ISSUE THREAD

**Issue by armanbilge** [http4s/http4s#6420]
Running into this in https://github.com/http4s/http4s-jdk-http-client/pull/645.

I extracted the test into a scala-cli runnable `IOApp` and did a fiber dump. They are both here:
https://gist.github.com/armanbilge/ec958260fc4bd0fed34e86c8c5091035

The fiber dump seems to indicate a hang here:
```
cats.effect.IOFiber@5f03cbbf WAITING
 ├ delay @ fs2.io.net.SocketCompanionPlatform$AsyncSocket.$anonfun$readChunk$1(SocketPlatform.scala:123)
 ├ async @ fs2.io.net.SocketCompanionPlatform$AsyncSocket.readChunk(SocketPlatform.scala:117)
 ├ flatMap @ fs2.io.net.SocketCompanionPlatform$BufferedReads.$anonfun$read$1(SocketPlatform.scala:85)
 ├ delay @ fs2.io.net.SocketCompanionPlatform$BufferedReads.$anonfun$withReadBuffer$1(SocketPlatform.scala:54)
 ├ release @ org.http4s.jdkhttpclient.CompletableFutureTerminationApp$.stallingServerR(bug.scala:182)
 ├ release @ org.http4s.jdkhttpclient.CompletableFutureTerminationApp$.stallingServerR(bug.scala:182)
 ├ release @ org.http4s.jdkhttpclient.CompletableFutureTerminationApp$.stallingServerR(bug.scala:182)
 ╰ apply @ org.http4s.jdkhttpclient.CompletableFutureTerminationApp$.run(bug.scala:70)
```

However, in an ember-client cancellation bug the fiber dump also pointed us to that exact same line, but it was a red herring. See:
- https://github.com/http4s/http4s/issues/6058#issuecomment-1043299750

**Comment by amesgen** [comment]
Another comletely different, but more minimal example of ember-server hanging up, minimized from a test in the linked issue above (https://github.com/http4s/http4s-jdk-http-client/pull/645): Add

```scala
  fixture.test("send and receive messages") { case (server, dispatcher) =>
    for {
      client <- createClient(
        URI.create(s"ws://${server.address.getHostName}:${server.address.getPort}/ws-echo"),
        dispatcher,
      )
      _ <- client.connect
      _ <- (client.send("foo") *> IO.println("sent sth")).replicateA(10).void
      msgs <- (client.messages.take <* IO.println("received sth")).replicateA(10)
      _ <- client.close
      _ <- IO.println("done")
    } yield assertEquals(msgs, List.fill(10)("foo"))
  }
```
to `EmberServerWebSocketSuite` and run 
```
bloop test ember-server --args '*send and receive messages'
```
to get sth like
```
sent sth
sent sth
sent sth
sent sth
sent sth
sent sth
sent sth
sent sth
sent sth
sent sth
received sth
received sth
org.http4s.ember.server.EmberServerWebSocketSuite:
==> X org.http4s.ember.server.EmberServerWebSocketSuite.send and receive messages  30.014s java.util.concurrent.TimeoutException: Future timed out after [30 seconds]
    at scala.concurrent.impl.Promise$DefaultPromise.tryAwait0(Promise.scala:248)
    at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:261)
    at scala.concurrent.Await$.$anonfun$result$1(package.scala:201)
    at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:62)
    at scala.concurrent.Await$.result(package.scala:124)
    at munit.internal.PlatformCompat$.$anonfun$waitAtMost$1(PlatformCompat.scala:21)
    at scala.util.Try$.apply(Try.scala:210)
    at munit.internal.PlatformCompat$.waitAtMost(PlatformCompat.scala:21)
    at munit.FunSuite.waitForCompletion(FunSuite.scala:51)
    at munit.FunSuite.$anonfun$test$1(FunSuite.scala:37)
    at munit.GenericTest.$anonfun$withBodyMap$1(GenericTest.scala:33)
    at munit.MUnitRunner.$anonfun$runTestBody$1(MUnitRunner.scala:296)
Execution took 30s
1 tests, 1 failed
```

**Comment by armanbilge** [comment]
Note that the websocket bug from https://github.com/http4s/http4s/issues/6420#issuecomment-1138864091 was fixed in https://github.com/http4s/http4s/pull/6587.

**Comment by kubukoz** [comment]
I'm seeing some hanging too. Fiber dump: [gist](https://gist.github.com)

**Comment by armanbilge** [comment]
> I can provide a reliable reproduce if needed

@kubukoz yes please, that would be great!

**Comment by kubukoz** [comment]
Looks like I can only do it with a browser... my guess is that some keep-alive system in Firefox keeps a client connection open (until I close the browser or do some funky stuff like force reload the page), so the server doesn't shut down until that connection closes.

**Comment by armanbilge** [comment]
@kubukoz have you tried configuring `shutdownTimeout`?
https://github.com/http4s/http4s/blob/77e4f3adc73875ac62ea9def48542bdb58365868/ember-server/shared/src/main/scala/org/http4s/ember/server/EmberServerBuilder.scala#L126

**Comment by kubukoz** [comment]
I have now, it seems to work ;)

**Comment by armanbilge** [comment]
I also fixed this by adding `withShutdownTimeout(1.second)` as well.
