### ISSUE TITLE
Add Host.fromIp4sHost

### ISSUE THREAD

**Issue by matthughes** [http4s/http4s#6421]
`Uri.Host` already has a `fromIpAddress` that uses the IP4S IpAddress type.  Since Ip4s also has a `Host` type, can we support that as well?  I believe http4s and ip4s Host models are isomorphic.

**Comment by matthughes** [comment]
Alternatively could 1.0.0 drop http4s.Host in exchange for ip4s.Host?  The project already brings in that dependency.

**Comment by rossabaker** [comment]
I don't see a reason we couldn't add an alternate constructor in 0.23.  For 1.0, I like the cats-uri idea.

$DEITY, I need to find energy to help with cats-uri.
