### ISSUE TITLE
AuthMiddleware with Ember backend returning chunked http response

### ISSUE THREAD

**Issue by christiankjaer** [http4s/http4s#6427]
The default `AuthMiddleware` (returning an empty 401) in combination with the Ember backend will return a chunked response that will leave the socket open.

Minimal example with version 1.0.0M33, scala 3.1.2 and the ember backend:
```scala
import cats._, cats.effect._, cats.implicits._, cats.data._
import cats.effect._
import com.comcast.ip4s._
import org.http4s.implicits._
import org.http4s.ember.server._
import org.http4s._
import org.http4s.dsl.io._
import org.http4s.server._

val helloWorldService = AuthedRoutes.of[Unit, IO] {
  case GET -> Root as _ =>
    Ok()
}

val authUser: Kleisli[[X] =>> OptionT[IO, X], Request[IO], Unit] =
  Kleisli(_ => OptionT(IO(None)))

val middleware: AuthMiddleware[IO, Unit] =
  AuthMiddleware(authUser)

object Main extends IOApp {
    def run(args: List[String]): IO[ExitCode] =
      EmberServerBuilder
      .default[IO]
      .withHost(ipv4"0.0.0.0")
      .withPort(port"8080")
      .withHttpApp(middleware(helloWorldService).orNotFound)
      .build
      .use(_ => IO.never)
      .as(ExitCode.Success)
}
```
Testing with cURL:
```
$ curl -v localhost:8080
*   Trying 127.0.0.1:8080...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET / HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.81.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 401 Unauthorized
< Date: Mon, 30 May 2022 13:36:16 GMT
< Connection: keep-alive
< Transfer-Encoding: chunked
<
```
And then the connection is just left open.

**Comment by christiankjaer** [comment]
Just by inlining what the auth middleware is doing, then the following handler will have the same behavior:
```scala
val service = HttpRoutes.of[IO] { case GET -> Root =>
  IO.pure(Response[IO](Status.Unauthorized))
}
```

**Comment by danicheg** [comment]
Thanks for reporting. That seems like a bug. I opine that it's a rather Ember-related bug, not a `core` module itself. Also, the `core` module has a dedicated test https://github.com/http4s/http4s/blob/4b928e0dc0ba6edbdbe7461204663e13a7013f8c/server/shared/src/test/scala/org/http4s/server/middleware/authentication/AuthMiddlewareSuite.scala#L149  (one could check that headers are empty within the response).

**Comment by christiankjaer** [comment]
> Thanks for reporting. That seems like a bug. I opine that it's a rather Ember-related bug, not a `core` module itself.
Since Ember should do something sensible with an empty response with no content length header?
