### ISSUE TITLE
Decouple core from shapeless

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#646]
We inherit a shapeless dependency via parboiled2.  A lot of our users use shapeless, but they don't all use the same version, and it's the only reason core needs shapeless.

Can we make a parboiled2 that doesn't depend on shapeless?

**Comment by LeifW** [comment]
Seems this comes up in Java / Scala a bit. Could just keep adding more `%` to dep specifiers in sbt (a la scala-js)?
What if parboiled included a shaded version of shapeless (i.e. under a renamed package name), so as not to tie users to a particular version? Tomcat does this with commons-logging, I believe.

**Comment by rossabaker** [comment]
That's roughly what I've proposed on the linked PR: `shapeless.HList` becomes `org.parboiled2.support.HList`.

**Comment by rossabaker** [comment]
This is a hot issue in my workplace, but it's worth nothing that shapeless comes into the picture anyway with either argonaut-shapeless or circe-generic.

**Comment by rossabaker** [comment]
Fixed by #928.
