### ISSUE TITLE
Use `TestControl.executeEmbed` for time-based tests

### ISSUE THREAD

**Issue by armanbilge** [http4s/http4s#6467]
I noticed a flake in the server `TimeoutSuite` yesterday and realized that many/all of our time-based tests are actually running against real time, I believe.

In Cats Effect 3.3 `TestControl.executeEmbed` was introduced as a way of running an `IO` against "simulated" time instead of real time. This allows the test to run much more quickly (since it can simulate a sleep instantly, instead of actually sleeping) and more reliably.

Cats Effect docs: https://typelevel.org/cats-effect/docs/core/test-runtime#full-execution

I recently used `executeEmbed` in https://github.com/typelevel/fs2/pull/2922, as an example :) 

So `executeEmbed` should be sprinkled in the appropriate places in our test suite. The `Timeout` suite is a good place to start :)

https://github.com/http4s/http4s/blob/08d219ba64f08a3741ebf2816f97a81b9561269a/server/shared/src/test/scala/org/http4s/server/middleware/TimeoutSuite.scala#L30

**Comment by danicheg** [comment]
FWIW: unfortunately, `TestControl.executeEmbed` doesn't work with 'layered' `IO`s and `IO`s produced by `Async#async`. So it could be kinda tricky to make this actually work.

**Comment by danicheg** [comment]
I've tried to apply `TestControl` in tests and many times faced with [this](https://github.com/typelevel/cats-effect/blob/series/3.x/testkit/shared/src/main/scala/cats/effect/testkit/TestControl.scala#L374-L379). But sure, maybe I was doing something wrong, just wanted to add some nota bene :)

**Comment by fserra-mdsol** [comment]
I'd like to give it a crack, if it's fine with everyone

**Comment by FrancescoSerra** [comment]
OK, this is the right account on which I can look into this :-)

**Comment by FrancescoSerra** [comment]
thanks @armanbilge and sorry for all the trouble!
