### ISSUE TITLE
Testing Documentation

### ISSUE THREAD

**Issue by medge-tc** [http4s/http4s#649]
There is a very small blurb under the DSL page's "The simplest service" section that I think I missed at least 4 times before finally nailing it down x) 

Would be nice to see that maybe in it's own section properly called out. Examples don't have any test examples either so it's rather easy for a newcomer to miss this while searching.

What do you all think?

**Comment by rossabaker** [comment]
That change makes sense to me.  If you're up for sending a PR, it's under docs/src/main/tut.

I have been considering adding a testkit to help with some common patterns, specifically around matchers (e.g., `service(req) should be status(Ok)`).  But http4s uses specs2 internally, and I use scalatest at work, and adding custom matchers for both makes me sad.  If people have testing idioms that they've been successful with, I'd love to hear them.

**Comment by MatthewEdge** [comment]
Sure, I'll send one over. I can add a ScalaTest snippet as well if you think it'd be beneficial?

Cheers!
