### ISSUE TITLE
Missing 0.23.13 release for http4s-blaze-server

### ISSUE THREAD

**Issue by andreisilviudragnea** [http4s/http4s#6542]
Where is https://mvnrepository.com/artifact/org.http4s/http4s-blaze-server_3/0.23.13?

**Comment by armanbilge** [comment]
See the release notes for 0.23.12:
https://github.com/http4s/http4s/releases/tag/v0.23.12

Blaze is now published independently:
https://github.com/http4s/blaze

**Comment by andreisilviudragnea** [comment]
Thanks.
