### ISSUE TITLE
It's not possible to unit test a WebSocket application

### ISSUE THREAD

**Issue by psisoyev** [http4s/http4s#6543]
Hi, 
I’m migrating my `Http4s` WebSocket application from `1.0.0-M23` to `1.0.0-M34`.

Now, as I shouldn’t create a `WebSocketBuilder` myself, but it is provided by the server, how can I unit test my routes if they require passing a `WebSocketBuilder` which I can’t create myself?

**Comment by armanbilge** [comment]
We added a `client-testkit` recently, maybe we can make a `server-testkit` and put it in there?

**Comment by gvolpe** [comment]
IIUC the main idea behind creating a `WebSocketBuilder` internally is that it should have the same lifecycle as the HTTP server.

However, as long as the HTTP server builder doesn't allow the users to use a custom instance, it should be fine to make the constructors public. For example, the current Ember builder takes a function:

```scala
def withHttpWebSocketApp(f: WebSocketBuilder2[F] => HttpApp[F]): EmberServerBuilder[F] = ???
``` 

If this is the only way to use a `WebSocketBuilder` and build a WebSocket application, I'd say it doesn't make sense to hide the constructors from the users, and it will facilitate unit-testing where a server is not involved.

Am I missing some other reason why these constructors have been made private?

**Comment by armanbilge** [comment]
@gvolpe thanks, great point. Seems reasonable to me. Does anyone want to PR the change? And also add a small test demonstrating how this would work. Thanks! :)

**Comment by gvolpe** [comment]
I can definitely send a PR for this (including test example), though not sure where this change stands regarding binary compatibility but I guess this being a milestone is ok?

**Comment by armanbilge** [comment]
Making a method public or adding a method is binary compatible. We can take this in 0.23 :)
