### ISSUE TITLE
Phase out the client DSL in the docs

### ISSUE THREAD

**Issue by armanbilge** [http4s/http4s#6552]
It seems to me that the prevailing recommendation is to just use `Request(...)` directly instead of using the DSL. Meanwhile, beginners frequently struggle to find all the right imports to get the magic to work.

**Comment by gringrape** [comment]
Could I work on this? If so, could you tell me where to start?

**Comment by armanbilge** [comment]
@gringrape great!

The docs are here:
https://github.com/http4s/http4s/tree/series/0.23/docs

The client DSL is this import
```scala
import org.http4s.client.dsl.io._
```

The goal is to remove that import anywhere it is used in the docs, and rewrite the code to use non-DSL APIs (so, probably just `Request`).

Directions how to preview the website are here:
https://http4s.org/contributing.html#running-the-site-locally

Let me know if you have any questions!

**Comment by gringrape** [comment]
Thank you for kind reply! 
Is it ok to fix like below? 
To me, it is clear to use named argument but I am not sure it is good.

FROM:
```scala
import org.http4s.client.dsl.io._
import org.http4s.headers._
import org.http4s.MediaType

val request = GET(
  uri"https://my-lovely-api.com/",
  Authorization(Credentials.Token(AuthScheme.Bearer, "open sesame")),
  Accept(MediaType.application.json)
)

httpClient.expect[String](request)
```

TO:
```scala
import org.http4s.Request
import org.http4s.headers._
import org.http4s.MediaType
import org.http4s.Headers

val request = Request(
  method = Method.GET,
  uri = uri"https://jsonplaceholder.typicode.com/posts/2",
  headers = Headers(
    Authorization(Credentials.Token(AuthScheme.Bearer, "open sesame")),
    Accept(MediaType.application.json),
  )
)

httpClient.expect[String](request)
```

**Comment by armanbilge** [comment]
@gringrape that looks good to me!

Feel free to put up a draft PR, it will make it easier to get feedback :)
