### ISSUE TITLE
Jsonp middleware

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#658]
We should have an easy way to support jsonp responses.

Quick sketch:
https://gist.github.com/rossabaker/5528ab604d988c225165b108335fc61e

/cc @hvesalai

**Comment by hvesalai** [comment]
We need to
- validate the callback name https://gist.github.com/hvesalai/3f9c22cfb7696b8ecdfe6c7dda087eff
- correct the content-length

**Comment by hvesalai** [comment]
See #659
