### ISSUE TITLE
`WSClient.fromHttpWebSocketApp`

### ISSUE THREAD

**Issue by armanbilge** [http4s/http4s#6590]
A websocket analog to `Client.fromHttpApp`, it would have a signature like:

```scala
def fromHttpWebSocketApp[F[_]](f: WebSocketBuilder[F] => HttpApp[F]): WSClient[F]
```

The tricky bit is you then can't get a `Client` as well. I wonder if we need something for `Client & WSClient`.

**Comment by kovstas** [comment]
If there is no one working on this, I would like to work on this issue.

**Comment by kovstas** [comment]
@armanbilge Just to clarify the expected API, the only method signature I managed to create is the snippet below. I'm wonder if there is any way to get the `WSClient` from `HttpApp` and is this any need to testing purposes? It seems that `WebSocketBuilder2` might be enough.
```scala
object WSTestClient {
  def fromHttpWebSocketApp[F[_]: Async](f: WebSocketBuilder2[F] => HttpApp[F]): F[Client[F]] = ....
}

WSTestClient.fromHttpWebSocketApp[IO] { wsb =>
    HttpRoutes
      .of[IO] { case GET -> Root / "ws" =>
        wsb.build(Stream.emit(WebSocketFrame.Text("hello world")), _.as(()))
      }
      .orNotFound
 }
```

**Comment by armanbilge** [comment]
> I'm wonder if there is any way to get the `WSClient` from `HttpApp` and is this any need to testing purposes?

Sorry, I'm not sure if I understood your question. The goal is to get a `WSClient`, so that it can be used to test web socket applications. It's possible that the signature may need to be effectual, so `F[WSClient]` instead of `WSClient` like I wrote above. Also I wonder if `Concurrent` is sufficient instead of `Async`.
