### ISSUE TITLE
Should jsonOf and jsonEncoderOf be implicit?

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#660]
In all of our JSON support modules, `jsonOf` and `jsonEncoderOf`, which create an `EntityDecoder` or `EntityEncoder` from an implicit instance of each library's JSON codecs, are not implicit.  Users frequently expect defining a JSON codec for their case class is sufficient for an entity codec.

We historically have not made this implicit, because it's not a given that users want to code case classes as JSON.  But maybe we should: if the user supplied a way to encode it as JSON, without any other available encodings, then it's probably a JSON API.  And if there are multiple codecs for a case class in scope, it should fail due to ambiguous resolution.

Thoughts?

/cc @tskardal

**Comment by rossabaker** [comment]
Another vote from a colleague that it should be implicit.

**Comment by reactormonk** [comment]
What about

    scala> jsonOf[String]
    res0: org.http4s.EntityDecoder[String] = org.http4s.EntityDecoder$$anon$2@55dc3bd7

**Comment by ceedubs** [comment]
Another item to note is that there currently isn't any way to configure your argonaut `PrettyParams` for `jsonEncoderOf`. For example, if you want to drop fields with `None` values instead of including them as `null` in the JSON, as far as I can tell you basically need to copy/paste the relevant http4s-argonaut code and replace the `PrettyParams`.

In addition to the `String` case from above (which I suspect probably isn't much of a problem in practice due to implicit priorities), this is something that makes these encoders seem less "universal" to me and therefore potentially a reason that they shouldn't be implicit.

**Comment by refried** [comment]
Oh yeah, I had to do this. :-/

**Comment by rossabaker** [comment]
I left a comment on #690 relating to prioritization that has me leaning toward this being a bad idea again.

**Comment by rossabaker** [comment]
I'm surprised that the `PrettyParams` is an issue.  I have a Chrome extension that pretty prints my JSON, and I either use httpie or pipe into Python's pretty printer from the console.  I think compact JSON is for services and tooling is for human debugging.  But I'm open to making this configurable if it's making people copy and paste.

**Comment by rossabaker** [comment]
If we're _not_ going to change this, and good reasons are emerging not to, I want to think about making the best of it and having a solid recommendation vs. the scattered approaches we have now.  

https://github.com/http4s/http4s/pull/689#discussion_r76669325

**Comment by ceedubs** [comment]
> I think compact JSON is for services and tooling is for human debugging.

@rossabaker I agree, and in fact the reason that I wanted to override it is to get a _more_ compact printer via `dropNullKeys = true` :). The default argonaut printer prints fields with `None` as a value as `"foo": null`, whereas generally the services that I've worked on have decided to just not include those fields in the JSON object.

**Comment by rossabaker** [comment]
Ah, so it's not just a whitespace issue, it's also a semantic issue.  Okay, I feel less grumpy about making that work.

**Comment by rossabaker** [comment]
Closing due to lack of mandate for change.
