### ISSUE TITLE
Date Header conformance

### ISSUE THREAD

**Issue by cquiroz** [http4s/http4s#669]
It seems the Date Header does not conform strictly too [RFC2616] https://www.ietf.org/rfc/rfc2616.txt, which states that dates should use the `GMT` timezone unlike http4s which uses `UTC`:

```
 All HTTP date/time stamps MUST be represented in Greenwich Mean Time
 (GMT), without exception. For the purposes of HTTP, GMT is exactly
 equal to UTC (Coordinated Universal Time).
```

**Comment by rossabaker** [comment]
Closed by cherry-picking of #670.
