### ISSUE TITLE
Thread blocking in version 0.23.14 or later of Ember Server?

### ISSUE THREAD

**Issue by takapi327** [http4s/http4s#6710]
Hi, Ember Server version 0.23.14 or later will behave like using block threads.

The same behavior was observed in versions 0.23.15 and 0.23.16.

After verifying the results by going back one version at a time, 0.23.13 showed no movement using the blocking threads.

I consulted the release notes for versions 0.23.13 through 0.23.14 and could not find anything causing this movement. What is causing this to happen?

## For version 0.23.13
```scala
ThisBuild / scalaVersion := "3.1.3"
libraryDependencies ++= Seq(
  ...
  "org.http4s" %% "http4s-ember-server" % "0.23.13",
)

// code
object Main extends IOApp:

  val helloWorldService = HttpRoutes.of[IO] {
    case GET -> Root / "hello" / name =>
      IO.println(Thread.currentThread().getName) >>
        IO.println(Thread.currentThread().getName) >>
        Ok(s"Hello, $name.") <* IO.println(Thread.currentThread().getName)
  }.orNotFound

  def run(args: List[String]): IO[ExitCode] =
    EmberServerBuilder
      .default[IO]
      .withHttpApp(helloWorldService)
      .build
      .use(_ => IO.never)
      .as(ExitCode.Success)

// result
[info] 2022-09-21 21:54:15 INFO  [io-compute-7] Ember-Server service bound to address: 127.0.0.1:8080 
[info] io-compute-7
[info] io-compute-7
[info] io-compute-7

```

## For version 0.23.14
```scala
ThisBuild / scalaVersion := "3.1.3"
libraryDependencies ++= Seq(
  ...
  "org.http4s" %% "http4s-ember-server" % "0.23.14",
)

// code
object Main extends IOApp:

  val helloWorldService = HttpRoutes.of[IO] {
    case GET -> Root / "hello" / name =>
      IO.println(Thread.currentThread().getName) >>
        IO.println(Thread.currentThread().getName) >>
        Ok(s"Hello, $name.") <* IO.println(Thread.currentThread().getName)
  }.orNotFound

  def run(args: List[String]): IO[ExitCode] =
    EmberServerBuilder
      .default[IO]
      .withHttpApp(helloWorldService)
      .build
      .use(_ => IO.never)
      .as(ExitCode.Success)

// result
[info] 2022-09-21 21:53:03 INFO  [io-compute-8] Ember-Server service bound to address: 127.0.0.1:8080 
[info] io-compute-8
[info] io-compute-blocker-8
[info] io-compute-8

```

**Comment by armanbilge** [comment]
Hi, thanks for the report. Actually I believe the change in what you _observe_ is due to Cats Effect.

To test this: try using the latest Cats Effect with different versions of http4s.

```scala
"org.typelevel" %% "http4s-cats-effect" % "3.3.14",
```

---

In fact, I believe your observations are very simply explained by two things.

1. https://github.com/typelevel/cats-effect/pull/3012
2. `IO.println(...)` is blocking :)
  https://github.com/typelevel/cats-effect/blob/badc9247976e66bad8f9395f5ce002a553086d45/std/shared/src/main/scala/cats/effect/std/Console.scala#L316-L319

**Comment by takapi327** [comment]
Thanks!
I changed the version of Cats Effect to 3.3.14 and tried it and confirmed the same behavior with 0.23.13 as with 0.23.14.
After reading the contents of the link you posted, my doubts were cleared up.
Thank you for your prompt response!
