### ISSUE TITLE
ember server: don't include log4cats-slf4j 

### ISSUE THREAD

**Issue by kubukoz** [http4s/http4s#6721]
Hi! I was wondering if there's a way we could remove the log4cats-slf4j dependency in 1.0's ember server.

I would suggest that we default to NoOp like the native/JS version do, and allow an override like the present. Or use a console logger made from `std.Console[IO]` so that there's _some_ feedback by default.

**Comment by armanbilge** [comment]
Yup, I already have this work sitting in a PR.
- https://github.com/http4s/http4s/pull/6645

**Comment by armanbilge** [comment]
We can't fix this backwards-compatibly in 0.23 unfortunately. But it is fixed in 1.x.
