### ISSUE TITLE
Setting request's ContentType in Scala 3 is not working

### ISSUE THREAD

**Issue by sergio-margale** [http4s/http4s#6791]
I'm trying to write a test for an http4s route that accepts an xml as body, no matter the content type that I set it's always `json/application`

```
  test("POST /foo/bar endpoint works") {
    val request: Request[IO] = Request(
      method = Method.POST,
      uri = Uri.unsafeFromString("/foo/bar")
    )
      .withContentType(`Content-Type`(MediaType.text.xml))
//      .withContentType(`Content-Type`(MediaType.text.strings))
      .withEntity("<foo/>")

    println(request)
    ...
}
```

```
Request(method=POST, uri=/foo/bar, httpVersion=HTTP/1.1, headers=Headers(Content-Length: 13, Content-Type: application/json))
```

This however works fine with Scala 2.13.10

```
Request(method=POST, uri=/foo/bar, httpVersion=HTTP/1.1, headers=Headers(Content-Length: 13, Content-Type: text/xml))
```

**Comment by hamnis** [comment]
Try reordering the withEntity and withContentType expressions.
```scala
val request: Request[IO] = Request(
      method = Method.POST,
      uri = Uri.unsafeFromString("/foo/bar")
    ).withEntity("<foo/>").withContentType(`Content-Type`(MediaType.text.xml))
```

**Comment by hamnis** [comment]
This may happen based on your imports. If you have imported http4s-circe and its entityencoders, you may get a incorrect serialization of this input in `withEntity("")`

Make sure you check which imports you have here.

**Comment by sergio-margale** [comment]
Ok, it was the imports issue, adding `import org.http4s.circe.*` solved the problem.

However fyi setting first the entity doesn't even compile:
```
Found:    org.http4s.Request[[_] =>> Any]#Self#Self
Required: org.http4s.Request[cats.effect.IO]
      .withContentType(`Content-Type`(MediaType.text.xml))
```
Or do I miss another import?

**Comment by hamnis** [comment]
if you add circe, you get json serialization of the entity, which is probably not what you want for XML.

Creating your own `EntityEncoder`, or using [http4s-xml ](https://github.com/http4s/http4s-scala-xml) might be what you actually want.

**Comment by sergio-margale** [comment]
Interestingly enough now it works with any encoding import. Seems that something was wrong in my setup. Sorry for the confusion!
