### ISSUE TITLE
json4s-native: keep it or no?

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#685]
json4s-native depends on `scala.text.Document`, which is deprecated in Scala 2.11.  It still exists in Scala 2.12, but it prevents enabling the `-Xfatal-warnings` compiler flag.  There is [stalled talk](json4s/json4s#199) about moving json4s-native off `scala.text.Document`.

I made it work on #684 by turning off fatal warnings for json4s-native, so we _can_ keep it.  But it's complication if it's little used.  I tried to deprecate our implementation, but you [can't deprecate a package object](https://issues.scala-lang.org/browse/SI-3115), which means if we remove it, it will have to be abruptly.

If you care to save json4s-native, please speak up here, or else it's going to go away.

**Comment by bryce-anderson** [comment]
I'm fine with letting it go.

**Comment by rossabaker** [comment]
json4s-native might live on upstream: https://github.com/json4s/json4s/pull/405

**Comment by refried** [comment]
What does it give us?

**Comment by rossabaker** [comment]
I added json4s because it's widely deployed, and because we used json4s-jackson at work.  In the end, I used circe wherever I used http4s, and never got either json4s module to prod.

json4s-native avoids a dependency vs. json4s-jackson.  I don't really have a recommendation other than to switch to circe or argonaut.

**Comment by refried** [comment]
I see.  Fwiw, I've been using argonaut, will probably continue until giving in to cats/circe.

**Comment by rossabaker** [comment]
json4s 3.5 got rid of the build exception, so I'll spare it for now.  We can leave this for now, though once we get done with the monorepo, I doubt I'll maintain this personally.
