### ISSUE TITLE
Abrupt kills of WebSockets logs `EndOfStream` as error

### ISSUE THREAD

**Issue by kareblak** [http4s/http4s#6872]
In `WebSocketHelpers.scala#228` a pull from the stream resulting in a `None` leads to an error being raised as `EndOfStreamError()`, resulting in a default error log. This is a normal state, and the server implementation should not concern itself on how clients choose to close the socket. Maybe the error could be explicitly handled and debug- or trace logged.

Steps to reproduce:
```
EmberServerBuilder
  .default[IO]
  .withHost(host"127.0.0.1")
  .withPort(port"7776")
  .withHttpWebSocketApp { builder =>
    HttpApp.liftF(builder.build(identity))
  }
  .build
  .use(_ => IO.never)
```

Run a client and end it ungracefully
```
wscat -c ws://127.0.0.1:7776 -x "not-a-close"
```

**Comment by armanbilge** [comment]
Thanks, what do you think about handling it similarly to the broken pipe case?
https://github.com/http4s/http4s/blob/4f0f0d6f918655283b0d1f5c6d2495283a729520/ember-server/shared/src/main/scala/org/http4s/ember/server/internal/WebSocketHelpers.scala#L100-L102

**Comment by kareblak** [comment]
I like it. It's beneficial if we handle all possible abnormal client side terminations similarily.

**Comment by armanbilge** [comment]
@kareblak a PR would be great! :)

**Comment by kareblak** [comment]
A uniform handling of these termination errors should probably be reviewed. I'm thinking about #6219 also...
