### ISSUE TITLE
Ember server responds with 500 when sent illegal characters in the query parameters

### ISSUE THREAD

**Issue by coltfred** [http4s/http4s#6931]
I do not know if this is an issue with ember server or http4s core, but if you send characters that should be URL encoded as query params the route that should match never gets called and the server returns 500.

Steps:
1: Clone the [g8 template](https://github.com/http4s/http4s.g8) - I did scala 2.
2: Start the server using `sbt run`
3: Use a browser (or JS) to send an invalid character.
```
await fetch("http://localhost:8080/hello/colt?foo={");
```

Note that the server fails with 500, instead of matching the route and returning the "Hello, colt" response.

This is a problem because people are sending garbage requests to a service I have exposed on the internet and it causes 500s to show up in our logs.

**Comment by armanbilge** [comment]
As a next step, it would be helpful to add some logging to find out what exception is being thrown that is causing the 500. That will point us to the problem.

**Comment by coltfred** [comment]
I tried adding logging in the routes, but it never gets there. So the logging would need to be down inside the request handling in http4s.

**Comment by armanbilge** [comment]
Ember has a configurable logger, does that report anything useful?

**Comment by coltfred** [comment]
I set the logback logger in the project to DEBUG and didn't get anything useful. Is there something else you'd like me to try?

**Comment by armanbilge** [comment]
Hmm, that's frustrating. Thanks for trying those. Then my best suggestion is to clone the repository, and debug the example directly out of here.

https://github.com/http4s/http4s/blob/570d60d5176d12352511fa6dd606f3aba53028ad/examples/ember/src/main/scala/com/example/http4s/ember/EmberServerSimpleExample.scala

Then, you can add debug `println`s etc. directly inside of http4s, until we can find the problem :)

**Comment by isomarcte** [comment]
I think the only error here is that the server is returning a 500. From [RFC 7230](https://www.rfc-editor.org/rfc/rfc7230).

> Recipients of an invalid request-line SHOULD respond with either a
>    400 (Bad Request) error or a 301 (Moved Permanently) redirect with
>    the request-target properly encoded.  A recipient SHOULD NOT attempt
>    to autocorrect and then process the request without a redirect, since
>    the invalid request-line might be deliberately crafted to bypass
>    security filters along the request chain.

The 301 seems very suspect to me...but we can certainly do a 400 in this case. 

I don't think we should allow the malformed URI to be matched on or otherwise enter the routes definition.

**Comment by coltfred** [comment]
I agree that the 400 bad request should be the response. I guess it should just be an empty body.

**Comment by isomarcte** [comment]
This actually a little hard to test. For example, curl doesn't even let you emit the request if the URI is bad.

```shell
 > curl 'http://localhost:8080/hello/colt?foo={'
curl: (3) unmatched brace in URL position 38:
http://localhost:8080/hello/colt?foo={
```

**Comment by coltfred** [comment]
@isomarcte That's why I gave the fetch call I was using from my browser because curl doesn't work and wget auto encodes the `{`.

**Comment by isomarcte** [comment]
@coltfred Ah that makes sense.

**Comment by valencik** [comment]
Just for fun, and because this is hard to test with curl, you can use netcat if you've got it:

```sh
printf "GET /hello/andrew?foo={ HTTP/1.0\r\n\r\n" | nc localhost 8080
```
```
HTTP/1.1 500 Internal Server Error
Content-Length: 0

```

Similarly with HTTP/1.1:

```sh
printf "GET /hello/andrew?foo={ HTTP/1.1\r\nHost: localhost:8080\r\n\r\n" | nc localhost 8080
```
```
HTTP/1.1 500 Internal Server Error
Content-Length: 0

```
