### ISSUE TITLE
Deprecate Jsonp middleware?

### ISSUE THREAD

**Issue by valencik** [http4s/http4s#6959]
While trying to review a 1.x optimization of the Jsonp middleware (https://github.com/http4s/http4s/pull/6937) I wrote a test suite and found that the Jsonp middleware has perhaps been broken for a few years.
PR with failing tests: https://github.com/http4s/http4s/pull/6958

The problem is a complicated regex for validating the callback param.
It [changed two years ago](https://github.com/http4s/http4s/commit/d67539378a1bc65cfc10d5698c339fc34a1842c4#diff-9f712c6cea40b287988742a7ad4d26f2e05a325770c0b988cc7fd8d55d0f21d0) and perhaps broke (I haven't tested if the above test suite would pass using the older version).
We can perhaps fix the first `Illegal character range` error, but then the regex will still not work on scala native because of its use of look-aheads.
If we really want to continue supporting Jsonp middleware we should perhaps stop using a regex for the validation.

However, JSONP is also no longer recommended:

> JSONP is vulnerable to the data source replacing the innocuous function call with malicious code, which is why it has been superseded by cross-origin resource sharing (available since 2009[[3]](https://en.wikipedia.org/wiki/JSONP#cite_note-caniuse-cors-3)) in modern applications.
https://en.wikipedia.org/wiki/JSONP

I'm proposing we deprecate the middleware in series/0.23 and remove it from 1.x

**Comment by rossabaker** [comment]
I agree with deprecating it, though I'm stubborn enough to spend five minutes trying to understand what made someone or something break it in the first place.
