### ISSUE TITLE
Add Deprecation and Sunset headers

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#6960]
These are useful headers, and we should have a model for them in `org.http4s.headers`:

https://greenbytes.de/tech/webdav/draft-ietf-httpapi-deprecation-header-latest.html#the-deprecation-http-response-header-field

**Comment by armanbilge** [comment]
Want to add them to the mega-list in https://github.com/http4s/http4s/issues/5010? Or are they special.

**Comment by rossabaker** [comment]
They are not special other than @zzmccoy wants them soon. :laughing:

**Comment by armanbilge** [comment]
@zan-preston go for it!
