### ISSUE TITLE
`Client.fromHttpApp` does not drain bodies

### ISSUE THREAD

**Issue by armanbilge** [http4s/http4s#7018]
This is especially a problem because finalizers are attached to the body, as demoed in this example which only prints "acquire" and not "release".

```scala
//> using lib "org.http4s::http4s-client::0.23.18"
//> using lib "org.http4s::http4s-server::0.23.18"

import cats.data._
import cats.effect._
import org.http4s._
import org.http4s.client._
import org.http4s.server.middleware._

object App extends IOApp.Simple {
  val app = BracketRequestResponse
    .bracketRequestResponseApp(IO.println("acquire"))(_ => IO.println("release"))
    .apply(Kleisli.pure(Response[IO]()))

  val client = Client.fromHttpApp(app)

  def run = client.status(Request()).void
}
```

h/t @fredshonorio

**Comment by kovstas** [comment]
If there is no one working on this, I would love to get my hands on this.

**Comment by ChristopherDavenport** [comment]
Note: The complication of this is only draining the body if it was not already drained by client.

**Comment by kovstas** [comment]
@armanbilge I have found out that @danicheg fixed this issue in this PR #6957

**Comment by armanbilge** [comment]
@kovstas do you mean this specific example? That must be a a coincidence then, because this is a bug in `Client`, and https://github.com/http4s/http4s/pull/6957 doesn't change any code in `Client`. Also that PR is targeting the `main` branch, which means this is still a problem that needs to be fixed in `series/0.23`.

**Comment by kovstas** [comment]
@armanbilge Yes. I wrote a test for bracketRequestResponseApp inspired by your example in the description of this task and found that it passes successfully in main. Sorry, the example confused me a bit, now I see that it's all about a client, not the middleware.

**Comment by armanbilge** [comment]
Btw, I suspect this bug still exists in `main` as well if you use a streaming response body for the response.
```scala
Kleisli.pure(Response[IO]().withEntity(Stream.empty: Stream[IO, Byte]))
```

**Comment by kovstas** [comment]
@armanbilge The fix handles the case with `Kleisli.pure(Response[IO]().withEntity(Stream.empty: Stream[IO, Byte]))` at `0.23` and when it was at `main`. Might I need to open a separate PR for `main`?

**Comment by armanbilge** [comment]
> Might I need to open a separate PR for `main`?

We regularly merge `series/0.23` into `main` e.g. https://github.com/http4s/http4s/pull/6970. So your fix will merge into `main` at that time :)
