### ISSUE TITLE
Feature Request Ember-Server: Defrag Websocket Frames

### ISSUE THREAD

**Issue by GrafBlutwurst** [http4s/http4s#7073]
Compared to Blaze, Ember does not handle Continuations and fragmented Frames automatically. It'd be great to have a configurable option (with a true default) to enable the same behaviour.

Blaze handles it here: https://github.com/http4s/blaze/blob/main/blaze-server/src/main/scala/org/http4s/blaze/server/WSFrameAggregator.scala

Presumably some additional code would need to go to: https://github.com/http4s/http4s/blob/main/ember-server/shared/src/main/scala/org/http4s/ember/server/internal/WebSocketHelpers.scala

**Comment by mox692** [comment]
I will work on this issue

**Comment by armanbilge** [comment]
Thanks @mox692!!
