### ISSUE TITLE
Wrong link in "Server Middleware" page in the docs

### ISSUE THREAD

**Issue by rsemlal** [http4s/http4s#7117]
In the documentation site (for the *0.23* version), in the [Server Middleware](https://http4s.org/v0.23/docs/server-middleware.html) page, the link to *CSRF* page actually points to [HSTS page](https://http4s.org/v0.23/docs/hsts.html) instead of [CSRF page](https://http4s.org/v0.23/docs/csrf.html).

It seems to be due to an unlucky copy/paste in `docs/docs/server-middleware.md`:

https://github.com/http4s/http4s/blob/e2617759fa60643401ec8aac2415c4660f858d88/docs/docs/server-middleware.md?plain=1#L679

**Comment by armanbilge** [comment]
Woops, thanks, a quick PR to fix it would be appreciated!
