### ISSUE TITLE
Retry should only resubmit idempotent methods with pure bodies

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#712]
1. Retry middleware should never resubmit a POST or other non-idempotent methods.
2. Retry middleware should only resubmit if it can verify that the body is pure.  Code for this already exists in FollowRedirect, which we can abstract out.  Right now, it just blanks out the body, which is bad.

I imagine this is all binary compatible and suitable for release-0.14.x.

**Comment by rossabaker** [comment]
> the other thing I feel is missing from Retry is when to retry since the function you can pass only takes an Int .... it can't inform if retry should be done for example ... if you get a 400 ... you shouldn't retry

I think this is _not_ binary compatible, but also a good idea.

**Comment by bryce-anderson** [comment]
Was this broken the last time that retry logic was touched? I recall discussing why the body was examined to determine if it was a halt.

**Comment by rossabaker** [comment]
I think that discussion was on the follow redirect?

**Comment by bryce-anderson** [comment]
Yeah, your probably right.

**Comment by rossabaker** [comment]
We should also be honoring the Retry-After header.

**Comment by rossabaker** [comment]
Retry-After is now honored.

I think we should be checking the idempotence of the method, but not the purity of the body.   We should assume and document that rerunning the body stream is idempotent.  I think `unsafeRetriable` should be the default behavior.  Of course, it's all parameterized now, because needs vary.

**Comment by rossabaker** [comment]
This got support for the `IdempotencyKey` header and more customizable policies.  Closing.

**Comment by rossabaker** [comment]
Though maybe this has interesting interactions with #4509, which does allow the detection of pure bodies. :thinking:

**Comment by danicheg** [comment]
This issue was addressed in #6379.
