### ISSUE TITLE
Ember client ignores timeout

### ISSUE THREAD

**Issue by hnaderi** [http4s/http4s#7121]
I'm facing some unexpected behavior which might be a bug or might require some documentation if that's what is intended.
When setting timeout to infinite, timeout is ignored and the default timeout (45s) is used instead.

You can reproduce this problem using:
Listen on a port using netcat or something similar:
```sh
nc -l 8080
```
Then run this code snippet:
```scala
//> using dep "org.http4s::http4s-ember-client:0.23.19"

import cats.effect._
import org.http4s.syntax.all._
import org.http4s.client.dsl.io._
import org.http4s.Method.GET
import org.http4s.ember.client.EmberClientBuilder
import scala.concurrent.duration._
import fs2.Stream
import fs2.Stream._

object Issue extends IOApp.Simple {
  private val buildClient = EmberClientBuilder
    .default[IO]
    .withTimeout(Duration.Inf)
    .build

  val client = resource(buildClient)
    .flatMap(_.stream(GET(uri"http://localhost:8080")))
    .flatMap(_.body.through(fs2.text.utf8.decode))
    .printlns

  def run: IO[Unit] = client.compile.drain

}

```

**Comment by armanbilge** [comment]
You need to increase all the timeouts. You may be hitting this one.
https://github.com/http4s/http4s/blob/b22f722d23eabd6fc3e5e95c69166b454ee15ca3/ember-client/shared/src/main/scala/org/http4s/ember/client/EmberClientBuilder.scala#L137-L139

**Comment by hnaderi** [comment]
Oh, my bad, sorry!
Thank you for the fast response, apparently I need some rest after making such a silly mistake :sweat_smile:

**Comment by armanbilge** [comment]
No problem, it's not very obvious at all :)
