### ISSUE TITLE
Ember server hangs on HTTP/2 request with body

### ISSUE THREAD

**Issue by armanbilge** [http4s/http4s#7146]
This is a regression between v0.23.19-RC3 and v0.23.19 that I bisected to https://github.com/http4s/http4s/pull/7096.

https://gist.github.com/Baccata/f29f5154b2628b047dd4d41b5c7725bc

<details>

```scala
//> using lib "org.http4s::http4s-ember-server:0.23.19"
//> using lib "org.http4s::http4s-dsl:0.23.19"

package foo

import cats.effect._
import cats.syntax.all._
import org.http4s.implicits._
import org.http4s.ember.server._
import org.http4s._
import org.http4s.dsl.io._
import org.http4s.dsl.request

object Main extends IOApp.Simple {

  // this works (http2 request w/o body):
  //    curl --http2 localhost:8080/hello
  // this works (http1 request w/ body):
  //    curl -X POST -d foo localhost:8080/text
  // this doesn't (http2 request w/ body, server hangs)
  //    curl --http2 -X POST -d foo localhost:8080/text
  //
  // Additionally, impossible to exit the application with a ctrl-c as soon
  // as ANY request has been sent to the server (whether we hit the first path or not)
  val app = HttpApp[IO] {
    case GET -> Root / "hello"           => Ok("hello")
    case request @ POST -> Root / "text" => request.as[String].flatMap(Ok(_))
    case request                         => NotFound()
  }

  def run: IO[Unit] = EmberServerBuilder
    .default[IO]
    .withHttp2
    .withHttpApp(app)
    .build
    .useForever
    .void

}
```

</details>

I was also able to reproduce with the `--http2-prior-knowledge` flag.

**Comment by wunderk1nd-e** [comment]
Hey @armanbilge - just gave it a spin this morning on my repro repo.
0.23.19-RC3 passes as seen [here](https://github.com/wunderk1nd-e/smithy4shttp2bugreproducer/pull/1)
0.23.20 still fails as seen [here](https://github.com/wunderk1nd-e/smithy4shttp2bugreproducer/actions/runs/5253047333/jobs/9489871655)

**Comment by armanbilge** [comment]
Hmm, thanks for trying that. We must have another bug 😕

**Comment by armanbilge** [comment]
Thank you, your reproducer was very helpful to explore this issue. I think I finally fixed it in https://github.com/http4s/http4s/pull/7156.

**Comment by wunderk1nd-e** [comment]
> Thank you, your reproducer was very helpful to explore this issue. I think I finally fixed it in https://github.com/http4s/http4s/pull/7156.

No worries at all - thank you for the fix! 🙏🙏🙏🙏
