### ISSUE TITLE
Mysterious error on post request: java.io.IOException: Broken pipe

### ISSUE THREAD

**Issue by omerlh** [http4s/http4s#7149]
Hey! 
I have a simple server (implemented using [endpoint4s](https://github.com/endpoints4s/endpoints4s)). The code is right [here](https://github.com/osskit/dafka-producer/blob/main/src/main/scala/adapters/endpoints/ProduceService.scala). When sending a post request I am seeing very mysterious error and I have no idea what to do:

 ```json
{
  "timestamp": "2023-06-12T06:54:24.464Z",

  "level": "ERROR",

  "thread": "io-compute-1",

  "logger": "org.http4s.ember.server.EmberServerBuilderCompanionPlatform",

  "message": "Request handler failed with exception",

  "context": "default",

  "exception": "java.io.IOException: Broken pipe\n\tat java.base/sun.nio.ch.FileDispatcherImpl.write0(Native Method)\n\tat java.base/sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)\n\tat java.base/sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:113)\n\tat java.base/sun.nio.ch.IOUtil.write(IOUtil.java:79)\n\tat java.base/sun.nio.ch.IOUtil.write(IOUtil.java:50)\n\tat java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.finishWrite(UnixAsynchronousSocketChannelImpl.java:591)\n\tat java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.finish(UnixAsynchronousSocketChannelImpl.java:195)\n\tat java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.onEvent(UnixAsynchronousSocketChannelImpl.java:213)\n\tat java.base/sun.nio.ch.EPollPort$EventHandlerTask.run(EPollPort.java:306)\n\tat java.base/sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:112)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\n\tat java.base/java.lang.Thread.run(Thread.java:829)\n\tat delay @ fs2.io.net.SocketCompanionPlatform$AsyncSocket.$anonfun$write$1(SocketPlatform.scala:134)\n\tat async @ fs2.io.net.SocketCompanionPlatform$AsyncSocket.go$2(SocketPlatform.scala:128)\n\tat flatMap @ fs2.io.net.SocketCompanionPlatform$AsyncSocket.go$2(SocketPlatform.scala:138)\n\tat delay @ fs2.io.net.SocketCompanionPlatform$AsyncSocket.write(SocketPlatform.scala:144)\n\tat flatMap @ fs2.io.net.SocketCompanionPlatform$AsyncSocket.write(SocketPlatform.scala:144)\n\tat apply @ org.http4s.ember.server.EmberServerBuilder.$anonfun$build$2(EmberServerBuilder.scala:202)\n"
}

```

I am suspecting something around request body too long maybe? I'll appreciate any help investigating it 🙏

**Comment by omerlh** [comment]
Yes, let me see what I can do here

**Comment by omerlh** [comment]
I don't think it's client disconnected because the client is getting 500 response back, I am still trying to reproduce it thought

**Comment by omerlh** [comment]
Maybe it's related to resources? I do see those errors: 
```
2023-06-12T06:54:21.255Z [WARNING] Your app's responsiveness to a new asynchronous event (such as a new connection, an upstream response, or a timer) was in excess of 100 milliseconds. Your CPU is probably starving. Consider increasing the granularity of your delays or adding more cedes. This may also be a sign that you are unintentionally running blocking I/O operations (such as File or InetAddress) without the blocking combinator.
```

**Comment by armanbilge** [comment]
For information about that warning and how to fix it, see this detailed guide:
https://typelevel.org/cats-effect/docs/core/starvation-and-tuning

**Comment by AndreasKillaitis0000** [comment]
I'm running into the same error with GET requests from the health check of Google's GCE instance group load balancers.

**Comment by armanbilge** [comment]
@AndreasKillaitis0000 any more details you can share? e.g. is this a change due to an http4s upgrade, etc.

If anyone can share a reproducer I'm happy to take a closer look :)

**Comment by jigarkhwar** [comment]
The same problem with Ember-server 0.23.19

**Comment by omerlh** [comment]
Same ember version here

**Comment by froth** [comment]
We are seeing this behavior when updating from 0.23.18 to 0.23.20. So in combination from what @jigarkhwar says: Maybe something introduced in 0.23.19?

**Comment by armanbilge** [comment]
Thanks, that is helpful! There were 3 RCs published between 0.23.18 and 0.23.19, it would be helpful to know which one of those RCs introduced the change.

A reproducer would also be excellent :) thanks everyone!

**Comment by omerlh** [comment]
I am now trying to downgrade to 0.23.18

**Comment by froth** [comment]
> Thanks, that is helpful! There were 3 RCs published between 0.23.18 and 0.23.19, it would be helpful to know which one of those RCs introduced the change, if any—it may have happened in 0.23.19 final.
> 
On it. Will take an hour or so due to ci pipelines as I can not reproduce this locally.

**Comment by froth** [comment]
Fast than I thought ;) Reproduced with 0.23.19-RC1

**Comment by armanbilge** [comment]
Wow, thanks!! Here's the release notes, which includes a change to Ember server.

https://github.com/http4s/http4s/releases/tag/v0.23.19-RC1

I wonder if it's related to this PR then. It's about write errors so seems relevant.

- https://github.com/http4s/http4s/pull/6930

`0.23.18-4-570d60d-SNAPSHOT` was published before that PR and `0.23.18-13-b164566-SNAPSHOT` was published after. Would you be able to try both to see if we can narrow it to that PR?

Snapshots are published here: https://s01.oss.sonatype.org/content/repositories/snapshots/org/http4s/

**Comment by froth** [comment]
Can *not* be reproduced with `0.23.18-4-570d60d-SNAPSHOT`
Can be reproduced with `0.23.18-13-b164566-SNAPSHOT`

Seems to be that particular PR :)

**Comment by AndreasKillaitis0000** [comment]
@armanbilge It's definitely related to http4s, as we observed this problem only recently after updating our dependencies. 

We can reproduce the error when we curl the health endpoint (which, for testing, we prolonged intentionally by some seconds) and cancel the curl command by hitting Ctrl+C. 

Updating to 0.23.20 did not fix it. But I can confirm that – as has been already mentioned above – downgrading to 0.23.18 fixed it.

**Comment by armanbilge** [comment]
Thanks everyone. I have a proposed fix up. I described some of the trade-offs in the PR, so I would appreciate it if anyone has some better ideas, or just to say yes, this is what we really want :)

- https://github.com/http4s/http4s/pull/7157
