### ISSUE TITLE
Encoder corrupts paths with unlucky letters

### ISSUE THREAD

**Issue by paulp** [http4s/http4s#720]
[This part of the encoder](https://github.com/http4s/http4s/blob/d3d8655dc44bfe37b5c688dafd7e0f00252c0892/core/src/main/scala/org/http4s/util/UrlCoding.scala#L41) changes the case of letters in paths it is encoding, for reasons not entirely clear.
```scala
            val c1 = in.get().toChar
            if (CharPredicate.HexDigit(c1)) {
              out.put(c0.toUpper)
              out.put(c1.toUpper)
            } else {
```
c0 and c1 are characters read from the input stream. If `toSkip('%')` is true, then `%` followed by two characters in the `a-f` range will see those letters flipped to upper case in the encoded path. (That's not what "skip" means!)

This is less directly relevant to me now because you just made the object containing this method private to the library (it was being called directly from quasar) but I thought you'd want to know.

**Comment by rossabaker** [comment]
The uppercasing is for normalization.  Quoth the RFC, "For consistency, URI producers and normalizers should use uppercase hexadecimal digits for all percent-encodings."  It would be good manners to mention that this happens.

It is indeed a bug in 0.14.x.  The old implementation capitalized percent encodings via a regex before encoding.  v0.14.6:

```
scala> urlEncode("%ab")
res4: String = %25AB
```

The code quoted above works in one pass:

```
scala> urlEncode("%ab")
res1: String = %25ab

urlEncode("%ab", toSkip = Set('%'))
res2: String = %AB
```

I didn't expect external consumers, but I'm happy to make this public again.  java.net.URLEncode only works for form encoding, whereas this supports other contexts, such as URI paths.  It would be better to have methods for the common use cases, saving callers the homework for the correct values of `spaceIsPlus` and `toSkip`.

In any event, I'll fix the bug in 0.14.  Thanks for the report.
