### ISSUE TITLE
Slow Response Handling with Custom Defined Model

### ISSUE THREAD

**Issue by mukhayy** [http4s/http4s#7246]
I have noticed that `http4s` client response handling is really slow, when handled with custom defined model.

For response size `40MB`, entity handling with user defined type is taking `25866 ms` = `~26 sec`
For the same size, when response is handled as String and then parsed to user defined type it is taking `1235ms` = `~1 sec`

When size is bumped just to `80MB`, handling is extremely slow with user defined type. It took around `~220 sec`
The response handled as String and then parsed to user defined type took around `~2 sec`

I was capturing packets sent in wireshark. Both `String` and `custom model`  handling the same amount of packets in stream. Difference is in how fast app handling stream of packets.

I have reproduced this case in following repo https://github.com/mukhayy/scala-http4s-decoder

How `String` parsing differs from `custom defined model` parsing, why performance between two is significant?

**Comment by armanbilge** [comment]
Sorry, what do you mean by "`custom model`"? What is it exactly?

Btw, I noticed you are using http4s 0.22. Note that this series is end-of-life. You should upgrade to 0.23 which is supported and has much better performance as well.

**Comment by armanbilge** [comment]
> How `String` parsing differs from `custom defined model` parsing, why performance between two is significant?

Yes, this is very different.

`String` "parsing" is very easy. The server receives bytes over the network socket. A `String` is actually just bytes, so it doesn't need to do any more work, just make a defensive copy and wrap it in `String` class.

For your `Response` class, I see you are decoding it as JSON. So first all those bytes need to parsed for JSON tokens and converted to the JSON ADT (an in-memory datastructure). Then, that JSON ADT needs to be decoded into your model class.

So it is not surprising you see a difference here: JSON will be slower than `String`.

**Comment by mukhayy** [comment]
1. When doing `response.as[String]` do we load entire string into memory? As by definition String is allocated in Heap Memory. I am just trying to understand how stream of bytes[] is pulled from OS receive buffer?

I also have updated http4s to latest, there was no significant change on performance.

2. One last question, what is best practice handling response in http4s to achieve better performance? As this example only ran in localhost, isolated from real network latency problems.

Thank you a lot!

**Comment by armanbilge** [comment]
> When doing `response.as[String]` do we load entire string into memory

Yes.

---

> I am just trying to understand how stream of bytes[] is pulled from OS receive buffer?

You can study the networking code in FS2 to learn more about how that works. Ember uses FS2 for all networking.

https://github.com/typelevel/fs2/blob/5dbe235e5a4e763251f94c3880a75ba20915edbb/io/jvm-native/src/main/scala/fs2/io/net/SocketPlatform.scala

---

> One last question, what is best practice handling response in http4s to achieve better performance? As this example only ran in localhost, isolated from real network latency problems.

http4s (and Cats Effect) make design choices that are optimized for real-world scenarios, where there is latency and a server is handling 1000s of concurrent connections at once. That is the situation where it will shine. If your goal is to maximize performance for moving bytes on a single connection on localhost, then http4s is not the right fit for your needs :)
