### ISSUE TITLE
Use MIMEDB to autogenerate MIME types

### ISSUE THREAD

**Issue by mdedetrich** [http4s/http4s#73]
There is a library called MIME-DB (https://github.com/jshttp/mime-db) which is basically a JSON index of every known MIME type according to two sources, that also identifies if the types are compressible, and their known extensions

Would be ideal if we could integrate this as part of the build process (download the .json, parse it, and generate a Scala source file similar to what is happening in https://github.com/http4s/http4s/blob/master/core/src/main/scala/org/http4s/MediaType.scala#L213-L377)

Note that, the index is currently missing whether a MIME-Type is binary or not, however this is an open issue, so we should only migrate when they implement this https://github.com/jshttp/mime-db/issues/3

**Comment by cquiroz** [comment]
At [scala-java-time](https://github.com/cquiroz/scala-java-locales) and [scala-java-locales](https://github.com/cquiroz/scala-java-locales) code is generated out of the IANA tzdb (former) and CLDR XML database (latter). This is a quite similar case, where code could be generated from the MIMA db for media types.

There are a few choices to do this, being the most straightforward to just add parsing code to the project src and call it from the [build](https://github.com/cquiroz/scala-java-locales/tree/master/project/src/main/scala/locales), up to write a [plugin](https://github.com/cquiroz/sbt-tzdb). The latter is likely overkill but the former may be complex to maintain.

I'd do something in between writing a small module to do the parsing and code generation in a separate project and then call it directly from the build.

I'll try to write a small prototype and we can discuss it further

**Comment by rossabaker** [comment]
Looks like you've got the most experience in this.  I guess at the end of the day, if it's an sbt task that writes into src_managed, it does what we need.

Maybe generate it into a private[http4s] abstract class? The `MediaType` companion can extend it and keep the other code in Pure Scala, and the abstract class means we can add to it without angering MiMa on Scala 2.11.  (Or, if it's private, we can just make it a trait and add MiMa exceptions, but that'll be a nuisance.)

**Comment by cquiroz** [comment]
I have a code generator that will take `MimeDB` and create lots of `MediaType` instances. I'm having some troubles to integrate it into the build and that got me thinking if I should instead just import the scala file into http4s.

The pro is that the build would be more stable but we'd need to remember to update the file when `MimeDB` changes.

The file is fairly large, above 300k with a few thousand `MediaType` instances

What do you think?
