### ISSUE TITLE
Support for Password Hashing with Basic Authentication 

### ISSUE THREAD

**Issue by m4dc4p** [http4s/http4s#730]
The `BasicAuthentication` class does not work with hashed passwords. In particular, the design of `checkAuth` requires that the server store plaintext passwords or be able to decrypt them:

``` scala
  private def checkAuth(realm: String, store: AuthenticationStore, req: Request): Task[AuthReply] = {
    req.headers.get(Authorization) match {
      case Some(Authorization(BasicCredentials(user, client_pass))) =>
        store(realm, user).map {
          case None => NeedsAuth
          case Some(server_pass) =>
            if (server_pass == client_pass) OK(user, realm)
   ...
```

(from [BasicAuthentication.scala](https://github.com/http4s/http4s/blob/master/server/src/main/scala/org/http4s/server/middleware/authentication/BasicAuthentication.scala#L32))

Note the test `server_pass == client_pass`; `server_pass` comes from the `store` function (which is fine). `client_pass` comes from the HTTP client, and there is no way to transform the value before comparing it to `server_pass`. Therefore, we cannot hash `client_pass` and compare it with some previously stored value (like the client's hashed, salted password).  Instead, `server_pass` must either be the plaintext equivalent of `client_pass`, which means we cannot store it as a hashed value.

I propose extending `store` so it takes the `client_pass` value and returns a value indicating if the user is authorized or not, rather than having the password comparison in this class.

**Comment by rossabaker** [comment]
Strongly agree.  I brought this up on Gitter while @reactormonk was working on #692.  Being able to recover the secret is necessary in Digest auth, but is bad practice in Basic.  These should not share the same type for the auth store.

**Comment by m4dc4p** [comment]
`BasicAuthentication` changed quite a bit in the master branch. My PR supports the previous behavior and adds enough support that you can implement a hashed password comparison too.

**Comment by rossabaker** [comment]
#763 extends #739 and solves this.
