### ISSUE TITLE
Propagate trace_id on logback produces empty value

### ISSUE THREAD

**Issue by francescofrontera** [http4s/http4s#7330]
I'm currently facing an issue while attempting to propagate the trace_id and span_id in my logback.xml file using http4s and Scala. Unfortunately, the variables appear to be empty.

To provide some context, I'm employing the OpenTelemetry auto-instrumentation (https://opentelemetry.io/docs/kubernetes/operator/automatic/) to implement tracing support over the http4s server.

Here's a snippet of my logback.xml encoding setup:

```
<encoder>
   <pattern>%highlight(%-5level) %-13(%d{HH:mm:ss.SSS}) %green(%logger{45}) TraceID=%X{trace_id}  SpanID=%X{span_id} - %message%n%xException{10}</pattern>
</encoder>
```
Despite my efforts, I've also attempted to change the variable names, such as trace.id, but the result remains unchanged.

Any suggestions on how to address this issue would be greatly appreciated.

Thanks in advance.

**Comment by armanbilge** [comment]
>  OpenTelemetry auto-instrumentation

Is this supported for Scala and http4s?

> Any suggestions on how to address this issue would be greatly appreciated.

I encourage you to look at the following projects, which provide interop with http4s and open telemetry without relying on "auto-instrumentation".
- https://github.com/typelevel/natchez/
- https://github.com/davenverse/natchez-http4s-otel
- https://typelevel.org/otel4s/
- https://github.com/http4s/http4s-otel4s

**Comment by francescofrontera** [comment]
@armanbilge Thanks for your response. I'll check out the projects you recommended.
