### ISSUE TITLE
Default values for timeout & idleConnectionTime in EmberClient lead to warn logs

### ISSUE THREAD

**Issue by froth** [http4s/http4s#7350]
With the addition of https://github.com/http4s/http4s/pull/7234 ember warns when timeouts are misconfigured.

However `EmberClientBuilder.default[IO]` has defaults that are "misconfigured".
`timeout (45 seconds) is >= idleConnectionTime (45 seconds). It is recommended to configure timeout < idleConnectionTime, or disable one of them explicitly by setting it to Duration.Inf.`

``` scala
    val idleConnectionTime: FiniteDuration = org.http4s.client.defaults.RequestTimeout
    val timeout: Duration = org.http4s.client.defaults.RequestTimeout
```

Maybe we should add another constant for idleConnectionTime (60s?).

**Comment by danicheg** [comment]
With the https://github.com/http4s/http4s/pull/7329, I guess this will be fixed. But we have not shipped the fix yet. @armanbilge @valencik any objections to publishing a fresh `0.23` release?

**Comment by froth** [comment]
Somehow I missed this when looking through the recent pull requests, sorry for the noise :)
