### ISSUE TITLE
Broken Pipe error logs in Ember Server when using `withTLS`

### ISSUE THREAD

**Issue by froth** [http4s/http4s#7356]
similar to #7014 but for `withTLS` instead of `withHttp2`

```
scala 3.3.1
org.typelevel:cats-effect_3:3.5.2
co.fs2:fs2-core_3:3.9.3
org.http4s:http4s-core_3:0.23.25
```

I get error logs when killing curl requests against ember with TLS enabled:

``` scala
EmberServerBuilder
        .default[IO]
        .withHost(ipv4"0.0.0.0")
        .withPort(port"8443")
        .withTLS(tlsContext)
        .withHttpApp(finalHttpApp)
        .build
```
Error log:
```
root 2024-01-10 09:33:34,714 [ERROR]             [io-compute-10] o.h.e.server.EmberServerBuilderCompanionPlatform - Request handler failed with exception
root java.io.IOException: Broken pipe
root    at java.base/sun.nio.ch.SocketDispatcher.write0(Native Method)
root    at java.base/sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:62)
root    at java.base/sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:137)
root    at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:102)
root    at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:65)
root    at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.finishWrite(UnixAsynchronousSocketChannelImpl.java:602)
root    at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.finish(UnixAsynchronousSocketChannelImpl.java:199)
root    at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.onEvent(UnixAsynchronousSocketChannelImpl.java:217)
root    at java.base/sun.nio.ch.EPollPort$EventHandlerTask.run(EPollPort.java:305)
root    at java.base/sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:113)
root    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
root    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
root    at java.base/java.lang.Thread.run(Thread.java:1583)
root    at delay @ fs2.io.net.SocketCompanionPlatform$AsyncSocket.go$2$$anonfun$1(SocketPlatform.scala:131)
root    at async @ fs2.io.net.SocketCompanionPlatform$AsyncSocket.go$2(SocketPlatform.scala:131)
root    at flatMap @ fs2.io.net.SocketCompanionPlatform$AsyncSocket.go$2(SocketPlatform.scala:135)
root    at delay @ fs2.io.net.SocketCompanionPlatform$AsyncSocket.write(SocketPlatform.scala:138)
root    at flatMap @ fs2.io.net.SocketCompanionPlatform$AsyncSocket.write(SocketPlatform.scala:138)
root    at apply @ org.http4s.ember.server.EmberServerBuilder.build$$anonfun$2(EmberServerBuilder.scala:216)
```

Broken pipes are errors, it is fine to log them but error loglevel is a little much in my opinion. I believe https://github.com/http4s/http4s/pull/7016 fixed something similar but it seems not to work for TLS.

**Comment by armanbilge** [comment]
`Request handler failed with exception`

Note the language there, "request handler"—this means that actually the error is happening inside of `finalHttpApp`, which is why it's being surfaced in the error logger.

I.e. this is not an error when the server is trying to write, this is a write error occurring inside of your application.

**Comment by froth** [comment]
That is weird, I can not reproduce this whithout tls being enabled and the finalHttpApp looks like this:

```
  def finalHttpApp = HttpRoutes.of[IO] {
    case GET -> Root / "hello" =>
      Ok("hello")
  }.orNotFound
```

I can not reliably reproduce this with curl, unfortunately. However crtl+c'ing `siege -c200 --with-ssl https://localhost:8443/hello` triggers this multiple times. I think it is fair to say that siege is no normal "http-client" and can trigger weird behaviour. But the Stacktrace is weird, especially if you say that it should come from inside the HttpApp.

Not sure what to do with this. Maybe you have an idea? If not I am fine with closing this for now and I will reopen if I find out more details.

**Comment by armanbilge** [comment]
> the finalHttpApp looks like this:

Ah, thanks, that's helpful, I didn't realize it was such a trivial app :)

> Maybe you have an idea?

Yes, I have an idea what is happening now. Probably writing the `"hello"` is failing because of the broken pipe (which is probably somehow related to TLS). However, because responses are modeled as `Stream`s unfortunately that means that errors in server code become convoluted with app errors (if possible, this is the thing that we should fix). Because of this, the logging mechanism activates to report what looks like a handler error, even though it was actually not your fault.

**Comment by armanbilge** [comment]
My guess is that the issue is here. Maybe we need to replace the `onError` with `handleErrorWith` 🤔 but to be honest I'm not sure. I feel less certain about my idea now 😅 
https://github.com/http4s/http4s/blob/cccbc321bddaf19a0c4c4cbcffa7dd4ef18ef023/ember-server/shared/src/main/scala/org/http4s/ember/server/internal/ServerHelpers.scala#L386-L399

**Comment by froth** [comment]
Thanks for having a look!

I changed the line from `onError` to `handleErrorWith` and retested with a locally published http4s. This unfortunately did not change the behavior.

**Comment by froth** [comment]
I see this also in "normal production usage" behind a nginx loadbalancer when terminating TLS in http4s.

Stacktraces are slightly different:
```
java.io.IOException: Broken pipe
	at java.base/sun.nio.ch.SocketDispatcher.write0(Native Method)
	at java.base/sun.nio.ch.SocketDispatcher.write(Unknown Source)
	at java.base/sun.nio.ch.IOUtil.writeFromNativeBuffer(Unknown Source)
	at java.base/sun.nio.ch.IOUtil.write(Unknown Source)
	at java.base/sun.nio.ch.IOUtil.write(Unknown Source)
	at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.finishWrite(Unknown Source)
	at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.finish(Unknown Source)
	at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.onEvent(Unknown Source)
	at java.base/sun.nio.ch.EPollPort$EventHandlerTask.run(Unknown Source)
	at java.base/sun.nio.ch.AsynchronousChannelGroupImpl$1.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
	at delay @ fs2.io.net.SocketCompanionPlatform$AsyncSocket.go$2$$anonfun$1(SocketPlatform.scala:131)
	at async @ fs2.io.net.SocketCompanionPlatform$AsyncSocket.go$2(SocketPlatform.scala:131)
	at flatMap @ fs2.io.net.SocketCompanionPlatform$AsyncSocket.go$2(SocketPlatform.scala:135)
	at delay @ fs2.io.net.SocketCompanionPlatform$AsyncSocket.write(SocketPlatform.scala:138)
	at flatMap @ fs2.io.net.SocketCompanionPlatform$AsyncSocket.write(SocketPlatform.scala:138)
	at getAndSet @ org.typelevel.keypool.KeyPool$.destroy(KeyPool.scala:120)
	at apply @ org.http4s.ember.server.EmberServerBuilder.build$$anonfun$2(EmberServerBuilder.scala:216
```

**Comment by froth** [comment]
@armanbilge ok I found where the log comes from:

https://github.com/http4s/http4s/blob/cccbc321bddaf19a0c4c4cbcffa7dd4ef18ef023/ember-server/shared/src/main/scala/org/http4s/ember/server/internal/ServerHelpers.scala#L343

it is this write on tlsSocket.

When I change it to 
``` scala
tlsSocket.write(fs2.Chunk.empty).handleErrorWith(e => logger.info(e)("tls-socket-error"))
```
I get info logs instead.

**Comment by armanbilge** [comment]
@froth ahhh very nice find! Want to open a PR?

**Comment by armanbilge** [comment]
We can bikeshed on the PR when I can stare at the change in more context. Also hopefully others can chime in too 😅

**Comment by froth** [comment]
Sounds good :) pull request incoming ;)
