### ISSUE TITLE
Ember client hangs when parsing response body from HEAD request

### ISSUE THREAD

**Issue by yanns** [http4s/http4s#7362]
When using `"org.http4s" %% "http4s-ember-client" % "0.23.25"`, a HEAD request never completes when parsing the response body.

I've created a reproduction case here: https://github.com/yanns/reproduce-head-issue

If I only check the HTTP status, then the function completes:
```
    val request = Request[IO](method = HEAD, uri = uri"http://localhost:8080/hello")
    client.run(request).use { http4sResp =>
      IO.println(http4sResp.status)
    }
```

If I parse the HTTP response, then the function hangs:
```
    val request = Request[IO](method = HEAD, uri = uri"http://localhost:8080/hello")
    client.run(request).use { http4sResp =>
      http4sResp
        .bodyText
        .compile
        .string
        .flatMap { decodedBody =>
          IO.println(http4sResp.status + " " + decodedBody)
        }
    }
```

I don't have this issue with blaze (`"org.http4s" %% "http4s-blaze-client" % "0.23.16"`)

The HTTP server is an akka-http-server.

**Comment by hamnis** [comment]
@yanns I believe the linked PR should fix this, issue, but please test.

**Comment by yanns** [comment]
@hamnis Thanks a lot for looking at it.
How can I try it? We don't publish any artifacts for PR, right? https://github.com/http4s/http4s/actions/runs/7685450374/job/20943477209?pr=7369

**Comment by hamnis** [comment]
you can run `sbt publishLocal` and use the packaged version as a dependency.
the locally published version should look something like this: `0.23.25-26-4e5679d-20240126T195341Z-SNAPSHOT`

**Comment by yanns** [comment]
OK I confirm it's working.
