### ISSUE TITLE
Sample code in Authentication middleware does not compile in versions after Scala 3.3.3

### ISSUE THREAD

**Issue by nineclue** [http4s/http4s#7416]
Following sample code from Authentication section in official documentation does not compiles and fails with `Type argument cats.data.OptionT[cats.effect.IO, ?] does not have the same kind as its bound [_$1]` message in Scala version 3.3.3 and 3.4.0

```scala
val authUser: Kleisli[OptionT[IO, ?], Request[IO], User] = ???
```

Found following code from web (discord http4s channel) which compiles.

```scala
val authUser: Kleisli[[A] =>> OptionT[IO, A], Request[IO], User] = ???
```

I can't understand why first code fails and second succeeds yet. But I think documentation should be updated.

**Comment by rossabaker** [comment]
This raises questions of which version(s) should be supported in the docs.  Quick analysis shows Scala 2 is still about 2/3 of our downloads, and most of its examples translate cleanly to Scala 3.  This is a case that doesn't, and is worth some sort of note.

I haven't looked at what other projects do, but as far as I know, there's no cross-build support in mdoc, and we have to pick one dialect of Scala that gets compiled, and banish the other to sidebars that we hope work?  In that case, I would say Scala 2 is the primary and Scala 3 gets the sidebar for now.

After that is the question of which Scala 3 should be documented.  I favor LTS in that case.

**Comment by armanbilge** [comment]
> I can't understand why first code fails and second succeeds yet.

Do you have the `-Ykind-projector` scalac option configured? I think if you add that and change `?` for `*` (we can do this in the docs too) everything should work.

**Comment by rossabaker** [comment]
I was wondering how kind projection cross-built in our code but not the REPL.  I didn't realize Scala 3 still required a flag.  That does indeed fix it, with the newer wildcard:

```
> scala-cli -S 3.3 --dependency org.typelevel::cats-core:2.10.0 --scalac-option -Ykind-projector
Welcome to Scala 3.3.3 (17.0.10, Java OpenJDK 64-Bit Server VM).
Type in expressions for evaluation. Or try :help.
                                                                                
scala> import cats.data._
                                                                                
scala> val authUser: Kleisli[OptionT[Vector, *], List[String], Int] = null
val authUser:
  cats.data.Kleisli[[_] =>> cats.data.OptionT[Vector, _], List[String], Int] = null
```

**Comment by nineclue** [comment]
> > I can't understand why first code fails and second succeeds yet.
> 
> Do you have the `-Ykind-projector` scalac option configured? I think if you add that and change `?` for `*` (we can do this in the docs too) everything should work.

You're right. Adding the flag solved the problem. 
I didn't know that option applies to Scala 3 either. 
Thanks a lot.
