### ISSUE TITLE
Cookie duplication using request.addCookie

### ISSUE THREAD

**Issue by roman0x58** [http4s/http4s#7444]
Hi, I'm facing an issue, when adding a cookie with the same name, it results the cookie being presented in request.cookies twice. 

The test will fail with `List(someCookieName=foo, someCookieName=bar) did not equal List (someCookieName=bar)`
```scala
val request: Request[IO] = Request()
    .addCookie(RequestCookie("someCookieName", "foo"))
    .addCookie(RequestCookie("someCookieName", "bar"))

request.cookies must equal (RequestCookie("someCookieName", "bar") :: Nil)
```

If this is the intended behavior, it would be great to have something like replaceCookie or so.

**Comment by danicheg** [comment]
I failed to find references in the spec that the `Cookie` header **must** contain only unique keys. However, this might be considered a natural behaviour. Given that, I'd suggest modifying the existing `Cookie` header in the Request via `org.http4s.Message#transformHeaders`, `org.http4s.Message#removeHeader` and `org.http4s.Message#addHeader`.
