### ISSUE TITLE
Support draining

### ISSUE THREAD

**Issue by bryce-anderson** [http4s/http4s#751]
It would be nice for servers and clients to have functionality to the tune of

``` scala
val shutdown: Task[Unit] = server.shutdown(10.seconds)
```

that will allow the server/client time to 'drain' requests that are already in flight. That means that a server will stop accepting new connections and begin to terminate sessions gracefully (think `Connection: close` header) as requests complete.

**Comment by rossabaker** [comment]
Is this not satisfied well by using non-daemon thread pools?  Those stop accepting new work, but continue to finish existing work.

**Comment by rossabaker** [comment]
Deeper discussion in #2216.
