### ISSUE TITLE
Why are attribute keys equal by reference?

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#756]
Excuses that come to mind are:
1. Speed.  Seems a premature optimization.
2. Avoids two keys with the same label and different types leading to CCE.  Solution requires bringing along a type tag, which adds to memory consumption.

Can we do better?  If we can't, how can we make this more obvious, since the scaladoc hasn't?

/cc @fadeddata

**Comment by bryce-anderson** [comment]
Is there more context behind this inquiry?

**Comment by rossabaker** [comment]
It has bitten me.  It bit someone on Gitter a while back.  And it just bit my colleague.  I think there's an expectation that `AttributeKey[A](s) == AttributeKey[A](s)` for any `A` and `s`.

**Comment by rossabaker** [comment]
We adopted Typelevel Vault a long time ago.
