### ISSUE TITLE
Support Link Headers

### ISSUE THREAD

**Issue by justjoheinz** [http4s/http4s#760]
It would be nice to have better support for `Link` Headers as defined by https://tools.ietf.org/html/rfc5988

For starters a HeaderKey `Link` would be already nice.

**Comment by cquiroz** [comment]
Should these update target master or cats?

**Comment by rossabaker** [comment]
Anything that isn't cats/fs2 specific should target master.  Then it can be merged to cats so it benefits both versions.

Shortly after 0.16, cats->master and master->scalaz-stream, and we'll still target master and merges will flow the other direction.

**Comment by ioganegambaputifonguser** [comment]
@justjoheinz 
https://github.com/http4s/http4s/pull/1687
does it make sense? 
actually it is my first PR here, could you please support me? thanks!

**Comment by guizmaii** [comment]
Maybe we can close this issue now ?
