### ISSUE TITLE
Support for multiple occurrences of the same query parameter

### ISSUE THREAD

**Issue by m4dc4p** [http4s/http4s#771]
I would like to add a matcher than can handle URLs with an optional parameter occurring multiple times. E.g.,:

    https://.../?foo=1&foo=2&foo=3

This almost exists (`QueryParamDecoderMatcher` and `OptionalValidatingQueryParamDecoderMatcher`) but in the first case, the parameter must appear at least once and in the second case, the paramater can be abset or appear once. 

Does anyone else find this feature useful?

**Comment by joshuasiler** [comment]
Seems like a bug that it doesn't handle it today

**Comment by rossabaker** [comment]
I'm surprised we don't have anything like that already.  I'm hoping to release 0.15 tonight.  Are you actively working on this?  This seems worth squeezing in if it's easy.

**Comment by m4dc4p** [comment]
@rossabaker  PR submitted.

**Comment by rossabaker** [comment]
Fixed by #772.
