### ISSUE TITLE
Exception while uploading multi part form

### ISSUE THREAD

**Issue by balatbn** [http4s/http4s#778]
Client -- Http4s 0.14.11a (with blaze client)
Server - Jetty with Spring Web MVC 4.2 

---

While uploading file, I'm seeing an exception 

Invalid mime type "multipart/form-data; boundary= Sv0aFj+y6kFBDxqAv/Th+.W.Emke, rm/+.40TZAg": Invalid token character ' ' in token \" Sv0aFj+y6kFBDxqAv/Th+.W.Emke, rm/+.40TZAg"

I'm not exactly sure what is the error here.

Here's the client code (based on provided example)

```scala
val multipart = Multipart(Vector(Part.formData("file", value)))
val request = Request(Method.POST, uri).withBody(multipart).map(_.replaceAllHeaders(multipart.headers))
client.expect[String](request)
```

**Comment by ritschwumm** [comment]
there's a space character between ```boundary=``` and ```v0aFj+y6kFBDxqAv/```, which afaik is not allowed per RFC

**Comment by balatbn** [comment]
When I look at tcpdump, I don't see any spaces 

> Content-Type: multipart/form-data; boundary="Sv0aFj+y6kFBDxqAv/Th+.W.Emke,'rm/+.40TZAg"

Are double quotes allowed here? Looks like spring is converting double quote to space?

**Comment by balatbn** [comment]
I manually overrode the header by removing quotes. Then I got an error saying "?" is not a supported character. Looks like Spring WebMVC is very picky on this.

After I specified my own boundary name with one alphabets, it worked fine.

---

I'm not sure what the RFC says here, but it would be great if we can support Spring as that is a pretty famous framework.

**Comment by rossabaker** [comment]
What alphabet did you use? Perhaps we can restrict ours.

**Comment by balatbn** [comment]
It was only alphanumeric(no quotes, question mark, etc)

**Comment by ritschwumm** [comment]
interesting that the exception you see differs from what you see in tcpdump..

**Comment by ritschwumm** [comment]
double quotes are allowed, but behave slightly different than a plain token.
the space is forbidden, if i understand the rfcs correctly:

https://tools.ietf.org/html/rfc7231#section-3.1.1.1 says
```
media-type      = type "/" subtype *( OWS ";" OWS parameter )
parameter       = token "=" ( token / quoted-string )
```    
https://tools.ietf.org/html/rfc7230#section-3.2.6 says
```
token           = 1*tchar
tchar           = "!" / "#" / "$" / "%" / "&" / "'" / "*"
                / "+" / "-" / "." / "^" / "_" / "`" / "|" / "~"
                / DIGIT / ALPHA
quoted-string   = DQUOTE *( qdtext / quoted-pair ) DQUOTE
qdtext          = HTAB / SP /%x21 / %x23-5B / %x5D-7E / obs-text
obs-text        = %x80-FF
```

**Comment by rossabaker** [comment]
This is what's allowed per [RFC](https://tools.ietf.org/html/rfc2046):

```
     boundary := 0*69<bchars> bcharsnospace

     bchars := bcharsnospace / " "

     bcharsnospace := DIGIT / ALPHA / "'" / "(" / ")" /
                      "+" / "_" / "," / "-" / "." /
                      "/" / ":" / "=" / "?"
```

Both spaces and question marks are legal, but aren't tchar, and thus need to be quoted.

**Comment by balatbn** [comment]
That is correct. I think this is an issue with Spring. Again, they might have implemented this way to support some old/popular servers.

I'm not sure whether we need to support it(thought it would be nice to have). So, I'll just copy/paste code here in case someone else faces the same problem.

```scala
val boundaryName = "ABDFFD123" //Sample boundary name
val formData = Part //One of the parts. Like file, etc.
val multipart = Multipart(Vector(formData), Boundary(boundaryName))
val request = Request(Method.POST, uri).withBody(multipart).map(_.replaceAllHeaders(multipart.headers))
              .map(_.putHeaders(Header("Content-Type", s"multipart/form-data; boundary=${multipart.boundary.value}")))
```

**Comment by rossabaker** [comment]
I've heard of frameworks struggling to parse quoted boundaries.  I think We can just remove `' '` and `'?'` from our alphabet of auto-generated boundary characters and stay out of trouble.

**Comment by rossabaker** [comment]
This should be binary compatible.  We could target release-0.15.x with this and do a patch.
