### ISSUE TITLE
Provide an Arbitrary[Uri] instance

### ISSUE THREAD

**Issue by Unisay** [http4s/http4s#779]
As per gitter discussion:
> @rossabaker Nov 30 16:42
> There are some arbitraries in TestInstances, but it's not published. There is no URI, but I needed one this week.
> @Unisay Nov 30 16:43
> I can contribute it if you want :grinning:
> @rossabaker Nov 30 16:43
> I would love that!
>

**Comment by rossabaker** [comment]
Closed by cherry-pick-and-merge of #780.
