### ISSUE TITLE
Prometheus integration

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#784]
A lot of people are using Prometheus for monitoring.  We should have a middleware for capturing and exporting those metrics just like we do for Dropwizard metrics.

**Comment by dbousamra** [comment]
@rossabaker What are your thoughts on abstracting metrics a little bit. 

My rationale is the fact that http4s now has 2 fairly similar metrics backends implemented (Dropwizard metrics and Prometheus), and internally at my company we also have a Datadog/StatsD impl too (https://gist.github.com/dbousamra/4836656a2083509cfd87efb0bb5ee546). 

Would it perhaps be advantageous to have some middleware that captured request and response metrics inside some type `MetricsData`. The middleware would also take some function from `MetricsData => Task[Unit]`, to actually send them out. We could still have the actual modules for each vendor, but this might save some code.

Or do you think that the different metrics impls would be 90% the same, but that last 10% leads to bad coupling?

**Comment by rossabaker** [comment]
I'm open to seeing what a DRYed up version would look like.  I think gathering is more similar than display.  The tricky part is we don't want the abstraction to measurably slow the measurements.

**Comment by rossabaker** [comment]
This is related to #35, the oldest ticket still on the board.

"Counter" and "gauge" are just concurrent variables.  "Histogram" is much harder:

- In Prometheus, you have a Histogram or a Summary.  The latter calculates more accurate quantiles, but the former can be aggregated across instances.
- In Dropwizard, you have a Histogram with configurable reservoirs with various tradeoffs.

We could provide a `Double => Unit` callback to handle observations for "histograms", but then it becomes bothersome to configure the listeners to capture this data.

An interesting discussion on this is happening in [the Go world](https://github.com/go-kit/kit/issues/378).  We'd use fancier types, but the pros and cons in that discussion are about what we're up against here.

**Comment by dbousamra** [comment]
To throw in another metrics producer, statsd, doesn't really have histogram. [DogStatsD](http://docs.datadoghq.com/guides/dogstatsd/) (the datadog extension version) does however, and it fits the `Double => Unit` mechanism well.

**Comment by rossabaker** [comment]
I think https://github.com/http4s/http4s/tree/wip/metrics may be a more interesting solution to this problem: expose events, and let listeners hook into those.

**Comment by ChristopherDavenport** [comment]
Closed By #1684
