### ISSUE TITLE
Out-of-memory exceptions

### ISSUE THREAD

**Issue by tindzk** [http4s/http4s#798]
Moved here from https://github.com/http4s/blaze/issues/56

@bryce-anderson This behaviour appears when I use `SimpleHttp1Client` for the requests. According to the documentation, `expect` should close the connection, but without an explicit `shutdownNow` call, the threads do not get disposed of.

**Comment by bryce-anderson** [comment]
`.expect` will close the connection, but it won't shut down the thread pool that belongs to the client. The thread pool won't be shut down without explicitly calling `shutdownNow`. Just make one `SimpleHttpClient` or `PooledHttpClient` and reuse it, shutting it down when you're finished with that client.

If you're still having trouble, please feel free to reopen this issue and post a complete example.
