### ISSUE TITLE
Consider using sbt-rig

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#806]
https://github.com/Verizon/sbt-rig

What I like:
* All our other builds happen in Travis, but releases happen on my laptop.  I have messed up several.
* Automation.

What I dislike:
* I don't like letting it manage our patch versions.  `.0` suggests things to people as well.
* Sometimes we bundle a few pull requests into one release.
* There are often ideas on master that aren't ready for a release that I want to support binary compatibility for.

Unresolved problems:
* Way of referring to current build throughout our documentation.  I do a global search and replace today.
* What happens when one crossbuild fails, as they are wont to do?

**Comment by reactormonk** [comment]
The version is defined via https://github.com/Verizon/sbt-rig/blob/master/src/main/scala/RigPlugin.scala#L322 - could set our own via https://github.com/sbt/sbt-release/blob/780af33a02602ba9a6e9835d97d6297adf3d0561/README.md#custom-versioning - or just side-effect out of that and ask git directly about the version: https://github.com/dwijnand/sbt-dynver

**Comment by rossabaker** [comment]
Generating automated changelogs is another challenge to consider.  We could have git generate a baseline, but they typically need manual tweaking.

**Comment by rossabaker** [comment]
We are using rig now on master.  There's still some work to be done with regard to sbt-pgp in order to publish releases from Travis.

**Comment by rossabaker** [comment]
Outstanding work replaced by #1276, which needn't be part of 0.16 milestone.
