### ISSUE TITLE
Separate http4s Macros into their own project

### ISSUE THREAD

**Issue by mdedetrich** [http4s/http4s#81]
After a lengthy discussion with @rossabaker, the best way to prevent any leaking of scala-reflect is to separate macros into their own project. Normally this wouldn't be needed, but the usage of QuasiQuotes plus scala 2.10.x support means that we need to pull in scala-reflect to compile the macros for scala 2.10.x.

If we separate out any usages of macros into their own sub project, make that subproject have a scala-reflect as a provided dependency, then the projects that depend on that sub project (in this case, http4s), won't pull the scala-reflect dependency.

Im fairly sure this is how it works, as I have done it before, will attempt this during the weekend, or early next week

**Comment by rossabaker** [comment]
Two years and no complaints. Closing.
