### ISSUE TITLE
Github pages for http4s is returning 404's

### ISSUE THREAD

**Issue by creswick** [http4s/http4s#816]
e.g.,

http://http4s.org/docs/0.15/dsl.html

**Comment by rossabaker** [comment]
Thanks.  Actively working on it.  Sorry I'm bad at sbt.  :)

**Comment by rossabaker** [comment]
Oops, I should have looked more closely.  Those moved in the site relaunch, to /0.15/dsl.html.  Where are you getting that link?

**Comment by creswick** [comment]
I had half a dozen tabs open from last week, and some google results from this morning were pointing me to that url.

This isn't working, either, though:

http://http4s.org/0.15/dsl.html

I don't actually see any documentation links on the http4s site right now -- is that intentional? (am I just overlooking it?)

**Comment by creswick** [comment]
ah, I should have clicked on the 'get started' button... I miss the 'documentation' link at the top, and the clickable versions in the release table, but this will work.

**Comment by rossabaker** [comment]
I'm doing too many things at once.  I stated the wrong URL. 😳 

I had just opened #819 to create a dropdown to list all the versions of the tuts.  I can bring back the links from the versions page, too.  We should also maybe consider redirects for old versions of the docs from Google links, though gh-pages is not real great at rewrites.

Thanks for the feedback, and sorry for the trouble!

**Comment by creswick** [comment]
Thanks! and no problem! I'm enjoying the library so far, and the docs have been pretty useful.

**Comment by rossabaker** [comment]
The lingering concerns are covered by #819 and #903.
