### ISSUE TITLE
Docs: Service Page showing Hugo Parameter instead of 'http4sVersion'

### ISSUE THREAD

**Issue by zarthross** [http4s/http4s#827]
On http://http4s.org/v0.15/service/ in the first code bloc, the `http4sVersion` val is not being properly set by hugo, instead showing the hugo variable.

See here:
![image](https://cloud.githubusercontent.com/assets/1111592/21533676/d1f10fdc-cd22-11e6-9249-8c081289f865.png)

**Comment by rossabaker** [comment]
*.md files need to use Hugo shortcodes, not interpolated variables.
