### ISSUE TITLE
Documentation of run vs unsafePerform(A)Sync

### ISSUE THREAD

**Issue by zarthross** [http4s/http4s#829]
People unfamiliar with scalaz, or people not realizing that http4s supports scalaz 7.1 and 7.2 may find that the use of the deprecated `Task.run` function in the documentation to be strange. Can we do something to make this more clear?

Random ideas:
1. Versioning the docs for the Scalaz version (probably a pain to do)
1. Using only the updated Scalaz version in the docs (though people on scalaz 7.1 the docs wouldn't work)
1. Making it clear in the documentation what one should be doing in scalaz 7.2 (probably the best, but unsure the exact nature of that, maybe just a comment each time run is used?)

**Comment by cquiroz** [comment]
During compilation you also see many deprecation warnings about that. Do we need `run` to support scalaz 7.1?

**Comment by reactormonk** [comment]
Yes. Unless you want to attach `unsafePerformSync` via implicit for 7.1

**Comment by rossabaker** [comment]
We only build for scalaz-7.2 now, so it makes some sense to upgrade the docs.  A couple things to consider:

* The cats branch is eventually going to be master.  That means that either this work is wasted, or we're going to have to solve the multiple-branches-of-docs problem.

* I wanted to add a `validate` alias to sbt to get people into the habit of running tut in addition to tests.  The problem there is the main code still needs to be on scalaz-7.1, unless we introduce that implicit, which adds clutter.

I think I'm still in favor of it, but that's my counterarguments.

**Comment by rossabaker** [comment]
I think we should do it.  `validate` can come with the cats branch, where life is simpler.  Travis will catch our errors in the interim.

**Comment by jmcardon** [comment]
We no longer support scalaz, so I believe this is an outdated issue
