### ISSUE TITLE
Add Logging middleware for http client and server

### ISSUE THREAD

**Issue by julien-truffaut** [http4s/http4s#85]
Ideally I would like to be able to log all http requests and response

**Comment by rossabaker** [comment]
We have a lot of good changes for 0.6, and no solid idea how we want to do this. Deferring to 0.7.

**Comment by rossabaker** [comment]
I've seen a lot of ad hoc solutions to this, especially for logging the body.  We should move this back to the frontburner.

Jetty and Tomcat already have solid logging stories.  We might want to tackle this in blaze.

**Comment by ChristopherDavenport** [comment]
Could our logging handle being moved to  `java-logging` and then we could utilize a transformer to expose it? This would get us off our java only dependency as `java.logging` can also be used for scala-js for #956 which would allow us to transition other components off.

**Comment by rossabaker** [comment]
I've had a lot of pain from Java logging. Is log4s not scala-js compatible? Could it be? It has served us well.

**Comment by cquiroz** [comment]
`log4s` is not scala.js compatible. Though I wrote the `java.util.logging` package for scala.js I certainly agree that is not the most fun to use, I only had to use it for business reasons

**Comment by rossabaker** [comment]
[slogging](https://github.com/jokade/slogging) looks interesting, but has an incompatible API and would be painful to migrate to.  I also don't know whether it has the proven API stability of log4s.

I have zero scala.js experience.  If slogging could do it, couldn't there be a log4s backend that wrote to the JavaScript console?  Maybe this is an issue for log4s, to see if there's interest in making that build multiplatform?

**Comment by cquiroz** [comment]
I investigated slogging but wasn't very happy that you need to mixin a trait to get to the logger, I don't know how relevant that is

**Comment by rossabaker** [comment]
Yeah, that was about when I left typesafe-logging behind.  slogging looks inspired by that.

I'm in favor of asking around on log4s.  If we don't get a positive response there, we could potentially inhale it like we did parboiled, and reduce our JVM footprint to slf4j-api.

**Comment by tindzk** [comment]
@cquiroz A library similar to slogging is [scribe](https://github.com/outr/scribe). It does not require you to mix-in a trait and has support for all platforms (JVM, JavaScript, LLVM).

**Comment by rossabaker** [comment]
Thanks for the pointer, @tindzk.  I hadn't seen that project.

Moving away from log4s would be expensive, and it looks like Sarah is open to getting log4s working on scala.js.  I think scribe looks like a great backup plan, but we should not give up on log4s yet.

**Comment by rossabaker** [comment]
Server support now exists.  Client support still needed.

**Comment by insdami** [comment]
Hi, could be possible to define the log level? At the moment it's fixed on `info`, it'd be nice to have control on that, maybe instead of passing a `Logger` it can be passed a function `log : String => Unit`
 ```
def logMessage[F[_], A <: Message[F]](message: A)(
      logHeaders: Boolean,
      logBody: Boolean,
      redactHeadersWhen: CaseInsensitiveString => Boolean = Headers.SensitiveHeaders.contains)(
      log: String => Unit)
```

**Comment by rossabaker** [comment]
@insdami That's a good idea.  (I think we had this conversation somewhere else.)  Would you be interested in making a PR?

Also, the client middleware now exists, so closing this one.

**Comment by insdami** [comment]
@rossabaker Sure thing. Have a look, please #1839
Thanks
