### ISSUE TITLE
Port client to fs2-cats

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#863]

**Comment by rossabaker** [comment]
@ChristopherDavenport has been working on this.  It compiles, but there are still a few failing tests.

**Comment by ChristopherDavenport** [comment]
So our last hold-up is PoolManager/borrow. I am trying to work through some solutions but a simple interim solution that gets borrow to compile would let blaze-client and the async client work to progress.  

Any ideas are appreciated.

**Comment by ChristopherDavenport** [comment]
Closed By #907
