### ISSUE TITLE
Port documentation to fs2-cats

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#867]
The tuts will need to be changed from the scalaz-stream references to compile against fs2-cats.

Some of this work is ready to start now.

**Comment by toddburnside** [comment]
I can take this one on.

**Comment by ChristopherDavenport** [comment]
@toddburnside Now that we have a working multi-version menu getting this operational has taken a bump in importance so that new users can work with the library and see what it has to offer with documentation and examples.

Checking in on what you have so far, or which branch in your repo any changes you have are on.

**Comment by toddburnside** [comment]
I have most of the tut files compiling, then will need to verify the text parts of it.

My changes are local only right now. I'll try to clean them up a bit and push to my repo this afternoon or evening. Unfortunately, I have domestic responsibilities today, but I should still be able to do that before tomorrow. I have a few questions about some differences with the streams, so I'll try to put in a preliminary pull request with the questions.

My hope is to finish this off tomorrow.

**Comment by toddburnside** [comment]
Sorry it's taking me longer than I had expected to get this done. I just put in an initial PR with some questions, etc. I should have time tomorrow evening to work on this and hopefully tie it up. If it is more urgent than that, I will not feel slighted if someone else wants to work on it.

**Comment by ChristopherDavenport** [comment]
Closed By #1007 and several small additions afterwards.
