### ISSUE TITLE
Port web socket support to fs2-cats

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#868]
The server and blaze-server ports have thus far commented out all web socket support.  The scalaz-stream version uses `Exchange`, which needs to be replaced.

**Comment by cquiroz** [comment]
Given that I use WebSockets this is appealing but my fs2 skills are still very basic. How complex do you think this task is it?

**Comment by rossabaker** [comment]
I haven't looked at it in a while, but I recall that `Exchange` is one of the bigger changes: that existed in scalaz-stream, and goes away here.  I think we'll just need a pair of a source and a sink.

I think this is probably more effort than the ones you've taken on, but doable.  Probably a lot easier than Multipart.

**Comment by cquiroz** [comment]
Yeah, multipart seems scary 😄 
Let me have a go at this issue

**Comment by cquiroz** [comment]
Sorry I've been so late on this, FS2 requires some learning. How soon do we need this done?

**Comment by ChristopherDavenport** [comment]
Do things right and keep us all updated. That's all anyone can hope for.

**Comment by cquiroz** [comment]
Did we agree on keeping the WebSocket as a regular `HttpService`?

**Comment by rossabaker** [comment]
I don't think we reached a final conclusion.

Pros:
* Doesn't break existing
* Failure to handshake can result in any HTTP response.  (What do most web socket clients display if the handshake fails?  Is this even useful in practice?)
* Means we don't need to figure out a way of mouting `HttpService` and `WebSocketService` together.

Cons:
* Requires the attributes map, which I've never felt great about.
* Makes it much harder to support on servlet containers
* Requires that awful "if-else" where the websocket stage is optionally mixed into the blaze stage.

I haven't done as much with web sockets as I'd like.  I'm pretty open to either design at this point.

**Comment by cquiroz** [comment]
Given that I know little about the current implementation I'd like to first do one as it is currently, i.e. using `HttpService` and then consider a refactor once it is done

**Comment by rossabaker** [comment]
:+1:
