### ISSUE TITLE
Port ChunkAggregator middleware to fs2-cats

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#873]
The existing version introspects the scalaz-stream (`asInstanceOf[Halt]`), which we can't do in fs2.

**Comment by agustafson** [comment]
I'm happy to try and pick this up, given I've looked at some Chunk-wrangling recently

**Comment by rossabaker** [comment]
Great, I'll move it over on the board.

**Comment by ChristopherDavenport** [comment]
Closed By #1125
