### ISSUE TITLE
Release version number for fs2-cats?

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#875]
The community is excited about this branch.  It would be nice to start publishing snapshots and eventually a milestone, even as this port is incomplete.  That raises a question of what we will call it.

I wonder about continuing scalaz-stream development as major version 0.x, and calling this major version 1.x.  That would let us release either branch independently, without fear of running out of numbers or coming up with ad-hoc "-cats" version qualifiers.

I don't like that it signals a maturity on what is the less mature branch, or that it hits 1.0 before the core dependencies of fs2 and cats.  If we call it 1.0, we might need to indicate clearly that it might eat your babies.

**Comment by rossabaker** [comment]
Ideas on the table for the first fs2-cats release:

### 1.0.0
* Lets both branches evolve on their own release cycle :+1:
* Implies stability before it's more mature than 0.15 :-1:
* Reluctant to go 1.x before cats or fs2 :-1:
* I hoped to get serious about semver in 1.x :-1:

### 1.0.0-M1
* Lets both branches evolve on their own release cycle :+1:
* Puts pressure on declaring a 1.0.0 :+1: and :-1:

### 0.50.0
* Lets both branches evolve on their own release cycle :+1:
* But only 35 more scalaz-stream releases :-1:
* 0.50 will be less featureful than 0.15 :-1:
* Creates odd gap between scalaz and cats releases :-1:

### 0.16.0
* scalaz-7.1 release would need a new name :-1:
* False expectation that 0.16.0 and 0.16.0a are similar except for dependencies :-1:
* Reflects the natural progression :+1:

### 0.16.0c or 0.16.0-cats
* Qualifiers are sad :-1:
* Lets scalaz-7.1 retain existing convention :+1:
* Otherwise, like the above

**Comment by ChristopherDavenport** [comment]
### Go Back to Release and Release as -1

- Time Travel is expensive :-1: 
- Versioning is easy :+1:
- Spacetime Continuum would be mad at us :fire:

**Comment by ChristopherDavenport** [comment]
Personally I am leaning towards 0.50.0

While it has lots of drawbacks the basic ideas of semantic versioning is maintained, and the meaning would mostly be preserved to those who came to the library. If we pointed people to the new numbers then we would only need to work to help make an easy transition for those switching over. In general people would be none the wiser in a year.

**Comment by rossabaker** [comment]
I think I agree. "Only 35 more scalaz-stream based releases" should be fine given that there were only 8 releases of scalaz-stream itself.

**Comment by bryce-anderson** [comment]
Not strongly opinionated about this, but I'd prefer `-cats` since its clear and `0.50.0` feels rather arbitrary. My second choice is `0.50.0`, even if its somewhat arbitrary.

**Comment by rossabaker** [comment]
Prior art: doobie uses the same version number, but puts `-cats` in the artifact ID.  Implied version number equality is not a problem because yax means it's released from one source tree.

It's also worth noting that the `a` convention we use for scalaz-7.2 breaks semantic versioning.

**Comment by rossabaker** [comment]
The plan was to convert topic/cats to master once it was viable.  Now I'll play devil's advocate:

* We have a viable server (#879), but are a long way from feature complete. (No client!)
* Once feature complete, I expect it to be slower until fs2-1.0 and its fast-concat ByteVectorChunk. (#876)
* The scalaz-stream branch is battle-tested at a Fortune 15 company.

I still strongly believe the topic/cats branch is the future, but it's still more for early adopters and cats enthusiasts.  (Not a putdown. I'm one!)

In semver, `x.y.z-cats < x.y.z`.  At this point in time, the `-cats` suffix has the right semantics.  Most pull requests arrive on master, which relieves pain in #877.  If we get a PR targeting cats, that's cool: I was going to have to backport it anyway as long as my job uses scalaz-stream.

I can write a script to publish off both branches to keep the release cycles in sync, so the next release would be 0.16.0, 0.16.0a, and 0.16.0-cats.

As long as we make clear on the site and on the gitters and the twitters that you can use cats-fs2 now, maybe it's fine if the master swap is delayed to close to 1.0?

**Comment by ChristopherDavenport** [comment]
Another thing to consider on version matching with an addendum -cats is that as we deal with small patches, that means that patches would be increasing on a branch that may be no different if the patch changes were only for one of the branches. Which is likely to be the case for any stream based modifications.

**Comment by cquiroz** [comment]
My 2 cents is for the `-cats` suffix

Maybe this has been discussed.

Any chance of e.g. `scalaz-fs2` or `cats-scalaz-stream` combinations. I can see how that would be a nightmare to maintain but for some users it could be simpler to only port one part. In my particular case porting to `fs2` maybe simpler than porting to `cats`

**Comment by rossabaker** [comment]
My heart is with fs2-cats and my work is with scalaz-stream, so I have a vested interest in both of those branches.  I'd be open to an fs2-scalaz, but am wary of more branches and would want a solid commitment for help maintaining it.  

Ways to realize fs2-scalaz without a third branch:
1. yax: maybe more reasonable for scalaz vs. cats than scalaz-stream vs. fs2, but hostile to contributors, especially on an IDE
2. shims: a good solution for typeclasses, a poor solution for data types (e.g. Kleisli)
3. a scalaz interop module atop fs2-cats
4. revive scataz
5. live with the mismatch

I'm inclined toward option 5, with option 3 or 4 if it hurts in practice.

**Comment by rossabaker** [comment]
@ChristopherDavenport is correct about the possibility of identical releases on the slower moving branch.  That's the biggest negative I can think of, and I think it's the least worst of all the other options, especially if the coordinated release is scripted.

**Comment by rossabaker** [comment]
We should imminently have an 0.16.0-cats-SNAPSHOT.

**Comment by BusyByte** [comment]
@rossabaker I recommend following [Semantic versioning](http://semver.org/)
Otherwise it is really hard to reason about when breaking changes are introduced or major shifts.

**Comment by ChristopherDavenport** [comment]
@BusyByte We are looking for true semantic versioning on the cats branch once it becomes our main go-to branch. With tags for scalaz branches that will tag along for those who have not yet switched, like Ross's work and many others.
