### ISSUE TITLE
Port `decode(Charset)` in util package

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#880]
A scalaz-stream version is commented out.  This needs to be ported to an fs2 pipe.  (The fs2 decoder works only for UTF-8.)

Fixing this should fix OAuthTest.

**Comment by agustafson** [comment]
hi @rossabaker I've put in a PR for this: https://github.com/http4s/http4s/pull/890. Lemme know if it needs fixing, but `OAuthTest` now passes.

**Comment by agustafson** [comment]
Hi have created https://github.com/http4s/http4s/pull/1040 for this

**Comment by ChristopherDavenport** [comment]
Closed By #1040
