### ISSUE TITLE
StaticFile.fileToBody is inefficient if start > 0

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#886]
The scalaz-stream implementation was built on nio.  The fs2-cats version is java.io.  We should be able to port the commented code to fs2.  Arguably the function belongs in fs2-io.

**Comment by cquiroz** [comment]
I could give this one a try. Could the methods in `pulls` be suitable?

https://github.com/functional-streams-for-scala/fs2/blob/series/1.0/io/src/main/scala/fs2/io/file/pulls.scala

**Comment by rossabaker** [comment]
I think `FileHandle` gives you what you need, but nothing in `pulls` is quite right: you need to pull from an arbitrary offset into the file, not 0L.  But the solution probably looks a lot like `_readAllFromFileHandle0`.
