### ISSUE TITLE
Upgrade blaze

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#894]
blaze-0.13 is out.  We should get on it.

**Comment by rossabaker** [comment]
This is challenging because blaze-0.13 dropped native web socket support.  We need to pull some of that code out into http4s-blaze.

**Comment by rossabaker** [comment]
@bryce-anderson started this in #1660, which I accidentally closed.  The revival of that will fix this.

**Comment by m-sp** [comment]
safe to say that this one was done, main is on 0.15.0-M1

**Comment by rossabaker** [comment]
Yep, and the rest has been on 0.14 for a very long time.
