### ISSUE TITLE
Move API scaladoc to a more visible spot on the website

### ISSUE THREAD

**Issue by reactormonk** [http4s/http4s#903]
People that have asked for the Scaladoc in the gitter channel since 1. February: 2

Ideas on where to put it:
- Right next to the "Get started"
- In the top row next to "Adopters"

**Comment by armanbilge** [comment]
Actually I suspect this is still a problem, but I haven't seen any recent complaints.

**Comment by armanbilge** [comment]
For the record scaladocs are linked from the top-right corner of every page:
https://http4s.org/v0.23/docs/quickstart.html
