### ISSUE TITLE
ServerApp#run does not terminate the application when exception is thrown

### ISSUE THREAD

**Issue by jtcwang** [http4s/http4s#911]
```
object Main extends ServerApp {
  override def server(args: List[String]): Task[Server] =
    for {
      _ <- Task.fail(...)
      runningServer <- ...
    } yield runningServer

    ...
}
```

The application doesn't seem to terminate if running `server: Task[Server]` throws an exception.
If you're not able to replicate it I can create a minimal example. Thanks!

I'm on version 0.15.3

**Comment by rossabaker** [comment]
Fixed by #1090, will be released in 0.15.9.
