### ISSUE TITLE
GenericCredentials is more opinionated than it should be

### ISSUE THREAD

**Issue by coltfred** [http4s/http4s#921]
If you want to implement an auth based solution which uses a base 64 encoding none of the credentials classes will work at all.

For instance say I want the following Authorization header:`Authorization: token t0s5DmvAr0wZP6mWdw/aTM0j3m9ES8dD6DOG+Z0JSYE=`. I cannot use this because the parser thinks that the `=` in the base64 encoding is part of a map for the `GenericCredentials`.

I propose the following. Change to  `GenericCredentials(authScheme: AuthScheme, value: String)`. If having a Key/Value solution is desired we could create `KeyValueCredentials` which behaves the same as the GenericCreditials today.

**Comment by rossabaker** [comment]
Fixed by #1184.
