### ISSUE TITLE
Cats - Memory Leak in fs2 0.9.3

### ISSUE THREAD

**Issue by ChristopherDavenport** [http4s/http4s#922]
Release 0.9.4 will be out shortly so we need to make it a priority to switch at that point. As this is a non-production branch we don't need to panic or revert, but we need to make sure we incorporate asap

**Comment by rossabaker** [comment]
If there's a snapshot, we can even get on that, as long as we're not releasing against it.

**Comment by ChristopherDavenport** [comment]
Fixed via #923
