### ISSUE TITLE
Implement AuthMiddleware.apply(authUser,onFailure) for cats with scala.util.Either

### ISSUE THREAD

**Issue by hejfelix** [http4s/http4s#924]
Currently the feature is commented out. It needs to be updated to work with Cats and scala.util.Either.

**Comment by hejfelix** [comment]
I have a working implementation of this. Trying to create a pull request at the moment

**Comment by hejfelix** [comment]
FYI: I failed to note down the issue number in the 2 subsequent commits

**Comment by rossabaker** [comment]
Fixed by #925
