### ISSUE TITLE
endpointAuthentication property name is confusing

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#927]
This has caused confusion on the job a couple times.  It is not about the TrustManager authenticating the server's cert, or the KeyManager allowing the server to verify us, but is about checking that the subject name on the cert matches the hostname of the request.  This is called [endpoint identification](https://www.ietf.org/rfc/rfc2818.txt) in the relevant RFC.  Turning off `endpointAuthentication` does not affect trust management.

Furthermore: is this a property of the client, or the request?  Perhaps a default on the client, but we might want to turn it on or off depending on hosts known to have misidentified certs.

**Comment by bryce-anderson** [comment]
Do you have a suggestion for an alternate name?

**Comment by rossabaker** [comment]
It's called "endpoint identification" in the [RFC](https://www.ietf.org/rfc/rfc2818.txt) and the [Java API](https://docs.oracle.com/javase/7/docs/api/javax/net/ssl/SSLParameters.html#setEndpointIdentificationAlgorithm(java.lang.String).

People seem to be confusing the existing name either for mutual authentication (2-way SSL) or cert validation (i.e., what the `TrustManager` does).

**Comment by bryce-anderson** [comment]
So `endpointIdentification` or `checkEndpointIdentification`? The latter is getting pretty wordy but the former is kind of meaningless. I do agree that it currently suggests mutual authentication which is a no-go.

**Comment by rossabaker** [comment]
I like `checkEndpointIdentification`.

**Comment by bryce-anderson** [comment]
:+1: Sounds good to me. When it comes to security, I prefer wordy over ambiguous.

**Comment by ChristopherDavenport** [comment]
:+1:  Descriptive is good if it's causing problems. We should make sure to reference RFC and the original name, so people have no trouble finding what they are looking for if they come from the RFC/java side.
