### ISSUE TITLE
Cats - Parboiled2 macros match incomplete in TLS 2.12.1

### ISSUE THREAD

**Issue by ChristopherDavenport** [http4s/http4s#958]
Parboiled2 macros show an incomplete match in 2.12.1 scala on the cats branch. We need to figure out what changes need to be made, it behaves on org.scala compiler, but when using the typelevel compiler we have match errors.
PR base is #950 
[Travis Build](https://travis-ci.org/http4s/http4s/jobs/204327928)

Match Error is `(x: Throwable forSome x not in StartTracingException)` for all match errors so that is what needs to be resolved.

**Comment by rossabaker** [comment]
Every reference I can find to `StartTracingException` is inside a catch block, which I wouldn't expect to be subject to exhaustiveness testing.

**Comment by rossabaker** [comment]
Upstream parboiled2 generates the same warnings on TLS 2.12.1.  It's just not fatal.

We could work around this for now by turning off fatal warnings in the parboiled2 module, but it would be nice to understand for the sake of TLS.

**Comment by rossabaker** [comment]
This is a manifestation of https://github.com/rossabaker/issues/tree/tls-strict-unsealed-patmat.  I'm inquiring in TLS gitter about whether this is intended behavior.  I don't think we would want this aggressive matching in a catch block.

I think I can fix this by turning off that new flag.

**Comment by ChristopherDavenport** [comment]
Closed by #950
