### ISSUE TITLE
First level support for Webjars

### ISSUE THREAD

**Issue by timo-schmid** [http4s/http4s#959]
[Webjars](http://www.webjars.org/) are a nice way to bring static content (eg. CSS, JS, ...) into the application via sbt. I think it would be nice if http4s had first level support for them, so it's very easy to include them into the application.

I suggest an API that looks like this:

**build.sbt**
```scala
libraryDependencies ++= Seq(
  "org.http4s"    %% "http4s-blaze-server"  % "$version",
  "org.http4s"    %% "http4s-dsl"           % "$version",
  "org.http4s"    %% "http4s-webjars"       % "$version",
  "org.webjars"   %  "jquery"               % "$version"
)
```

**Application.scala**
```scala
// ...
import org.http4s.webjars.WebjarService

// optional callback to decide which files are served
def isValidWebjarFile(library: String, version: String, asset: String): Boolean = ???

BlazeBuilder
  .bindHttp(port, host)
  // ...
  .mountService(WebjarService(isValidWebjarFile), "/webjars")
  .start
```

I guess I could make a PR this weekend, what do you think?

**Comment by rossabaker** [comment]
Seems interesting.  Do installed webjars end up as resources available on the classpath?  How would it differ from `StaticResourceService`?

**Comment by timo-schmid** [comment]
Yes, exactly - they end up on the classpath in `/META-INF/resources/webjars/$library/$version/$path`.
For the implementation I'd use `StaticFile.fromResource`.

IMO it's a bit more convinient this way, but not fundamentally different.

**Comment by rossabaker** [comment]
It seems like a static file server with a naming convention.  I think it's useful, but maybe as a function in http4s-server as opposed to a full module?  There's no dependency required other than whatever web jars are project pulls in, right?

**Comment by timo-schmid** [comment]
Nope, just core and theDsl.

**Comment by timo-schmid** [comment]
Actually I just noticed the package `org.http4s.server.staticcontent`, it'd fit really well there.

**Comment by rossabaker** [comment]
:+1:
