### ISSUE TITLE
http4s, scalaz, argonaut dependency sauna

### ISSUE THREAD

**Issue by aryairani** [http4s/http4s#961]
http4s 0.15.5 supports scalaz 7.1
http4s 0.15.5a supports scalaz 7.2
argonaut 6.1 supports scalaz 7.1
argonaut 6.2-RC2 supports scalaz 7.2 and cats 0.8.1
However, http4s 0.15.5 (like 0.15.5a) depends on argonaut 6.2-RC2.

I tried using
```
"io.argonaut" %% "argonaut" % "6.1" force()
```
and while that does cause sbt-dependency-graph to show 6.2-RC2 evicted in favor of 6.1, `compile` and `console-quick` and IntelliJ all still seem to bring in 6.2-RC2.

~I will try going all the way and just adding argonaut-scalaz 6.2-RC2 and hope there are no actual bincompat issues, although that would surprise me.~  <- Tried; not surprised; `NEL` is incompatible, `Free` is incompatible, ...

What do you think?  Can we have 0.15.5 depend on argonaut 6.1?  Or does that break something?(e.g. desired cats support)

**Comment by ChristopherDavenport** [comment]
Cats is very independent so no worries there. I'll get a PR with 6.1 to 0.15.x and then @rossabaker  can comment directly, or he can comment here if he beats me to the PR.

**Comment by refried** [comment]
Thanks @ChristopherDavenport.

**Comment by refried** [comment]
I expect it will likely need to be split, with 6.1 in 0.15.5 and 6.2 in 0.15.5a.

**Comment by bfritz** [comment]
@refried is http4s-argonaut61 what you need?
* https://github.com/http4s/http4s-argonaut61
* http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22org.http4s%22%20AND%20a%3A%22http4s-argonaut61_2.11%22
Ignore me if I'm missing something obvious.  There's a good chance of that; don't have my head around the full compatibility matrix yet.

**Comment by rossabaker** [comment]
So, the binary exists.  I'll try to be better about republishing to keep the version numbers in sync.  We should get this documented somewhere that it exists.

**Comment by refried** [comment]
@bfritz Yes, thanks!

@rossabaker Should I rename the ticket to be about mentioning it in the docs / setup tutorial?

**Comment by rossabaker** [comment]
If you rename it, make sure it still includes "sauna." :)

**Comment by rossabaker** [comment]
We could conceivably move this module into the main tree so we don't keep forgetting to publish it, as long as it's not published in unidoc.

**Comment by jmcardon** [comment]
Is this issue necessary still, considering the 0.15 variants are EOL?

**Comment by rossabaker** [comment]
Yes, but I hope we get more issues named "sauna" in the future.
