### ISSUE TITLE
Unit testing

### ISSUE THREAD

**Issue by cquiroz** [http4s/http4s#969]
It would probably be good to document how to do some simple unit testing for applications. e.g. testing  a GET/POST route, setting params, etc

**Comment by rossabaker** [comment]
I get asked this a lot at work, and for the most part, the answer is "it's just functions!" Which makes people really like it.  But it definitely merits covering.

Also, testing `Task`s is nicer with matchers.  I'd like to look into releasing `HttpMatchers` as part of our testing library.  The challenge there is it's bound to specs2.  Is there an http4s-specs2 and http4s-scalatest then?  I don't know.

**Comment by Daenyth** [comment]
There's also µtest.

**Comment by rossabaker** [comment]
If your itch is not scratched in #1718, please comment there.  Or if it's done by the time you read this, please open another issue.
