### ISSUE TITLE
Clean out hacks to preserve old docs with new sbt-ghpages

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#972]
sbt-ghpages-0.6.0 introduces [filters to protect part of your site](https://github.com/sbt/sbt-ghpages#protecting-existing-files).  I think this feature could get rid of many of the hacks in our project/Http4sGhPages.scala file.

**Comment by bfritz** [comment]
Might be worth experimenting with [the gh-pages branch as a submodule](https://github.com/http4s/http4s/pull/1067#issuecomment-290293769) when working on this one.

**Comment by rossabaker** [comment]
It's still janky, but we're now on a gh-pages version that helps a lot.
