### ISSUE TITLE
sporadic async-http-client spec timeouts fail build

### ISSUE THREAD

**Issue by bfritz** [http4s/http4s#978]
[AsyncHttpClientSpec](https://github.com/http4s/http4s/blob/1ea1ab3a18563159b0429313684a5b710c869b76/async-http-client/src/test/scala/org/http4s/client/asynchttpclient/AsyncHttpClientSpec.scala) and `BlazePooledHttp1ClientSpec` assertions occasionally fail on Travis.  A recent example is [build 3763.4](https://travis-ci.org/http4s/http4s/jobs/206659743#L1733):
```
[info] BlazePooledHttp1ClientSpec
[info] BlazePooledHttp1ClientRecycleSpec
[info] Passed: Total 36, Failed 0, Errors 0, Passed 36
[error]   ! Execute GET: http://testing-docker-79b58d7e-0899-4c7e-9f06-2b0a98a84d95:46117/simple
[error]    java.util.concurrent.TimeoutException: Timed out after 10000 milliseconds (ClientRouteTestBattery.scala:59)
[error] org.http4s.client.ClientRouteTestBattery.org$http4s$client$ClientRouteTestBattery$$runTest(ClientRouteTestBattery.scala:59)
[error] org.http4s.client.ClientRouteTestBattery$$anonfun$org$http4s$client$ClientRouteTestBattery$$runTest$1.apply(ClientRouteTestBattery.scala:50)
[error] org.http4s.client.ClientRouteTestBattery$$anonfun$org$http4s$client$ClientRouteTestBattery$$runTest$1.apply(ClientRouteTestBattery.scala:50)
[info] AsyncHttpClientSpec
[error] Error: Total 2, Failed 0, Errors 1, Passed 1
[error] Error during tests:
[error]         org.http4s.client.asynchttpclient.AsyncHttpClientSpec

...

[info] Passed: Total 718, Failed 0, Errors 0, Passed 718, Pending 2
[error] (async-http-client/test:test) sbt.TestsFailedException: Tests unsuccessful
```

Might be a continuation of #774 since we added a few Task timeouts recently.

Also related to #858.

**Comment by bfritz** [comment]
Examples:
* [3770.1](https://travis-ci.org/http4s/http4s/jobs/206876698#L621)

**Comment by rossabaker** [comment]
They don't both always fail together.  I tried running [2000 examples](https://travis-ci.org/http4s/http4s/builds/208011042) on CI, hoping to get a consistent red that we could attack.  Naturally, it passed.

I thought blaze used to fail like this, but I was less vigilant about writing those down.  There isn't a search tool for old Travis builds, is there?

**Comment by bfritz** [comment]
@rossabaker "together" meaning the blaze client and the async-http client?  Or something else?

Not aware of a proper search tool, but I started a collection of failed builds a while back with:
curl -L -o "tmp/$JOB_NUMBER" "https://api.travis-ci.org/jobs/$JOB_ID/log.txt"

I don't follow exactly what you're looking for yet, but I will update my list of examples in case that helps.  Probably be tomorrow or Wed.

**Comment by rossabaker** [comment]
"Together" meaning both tests in async-http-client.  One passes, one fails.  It's not a total meltdown of the client.

I would like to know the last time the build failed because of blaze-client tests.  I feel like this used to happen, but lately it's always AHC.

**Comment by bfritz** [comment]
Shoot.  When looking at it with fresh eyes, I misread the error snippet in the first comment because it started with the class names of the blaze specs.  I [re-]corrected the issue title.

The only recent example I've seen that involves the blaze client is this one:
https://travis-ci.org/http4s/http4s/jobs/207575990#L1732
```
[error]   x Request timeout on slow POST body
[error]    Expected: java.util.concurrent.TimeoutException. Got nothing (ClientTimeoutSpec.scala:92)
[error] org.http4s.client.blaze.ClientTimeoutSpec$$anonfun$2$$anonfun$apply$13.apply(ClientTimeoutSpec.scala:92)
[error] org.http4s.client.blaze.ClientTimeoutSpec$$anonfun$2$$anonfun$apply$13.apply(ClientTimeoutSpec.scala:75)
[info] ClientTimeoutSpec
[..]
[error] Failed: Total 36, Failed 1, Errors 0, Passed 35
[error] Failed tests:
[error]         org.http4s.client.blaze.ClientTimeoutSpec
```
There was an AHC timeout just following the `blaze.ClientTimeoutSpec` failure.

Also, from my personal stash of Travis failures:
```
$ grep "error.* Execute GET" * | sort -nr

3834.4:[error]   ! Execute GET: http://testing-docker-4dc85917-c724-4a3c-a109-315485878e0e:38795/simple (18 seconds, 960 ms)
3827.1:[error]   ! Execute GET: http://testing-docker-8f3c3d21-4050-4719-9b50-827cd1de2b72:38669/simple (16 seconds, 118 ms)
3812.4:[error]   ! Execute GET: http://testing-docker-4f04a350-6c09-4ebb-9ccc-3391d619d82b:46691/simple
3806.1:[error]   ! Execute GET: http://testing-docker-aedffe7d-01ba-4357-b301-af14ac8139e8:38271/simple (20 seconds, 654 ms)
3805.4:[error]   ! Execute GET: http://testing-docker-0d18be11-465d-456b-b190-eb010f670601:45023/simple (15 seconds, 375 ms)
3805.3:[error]   ! Execute GET: http://testing-docker-9d7459b9-15c7-438f-a867-16cd7e6e18ca:41187/simple (21 seconds, 496 ms)
3781.2:[error]   ! Execute GET: http://testing-docker-f41a68b0-57e5-4aaf-b089-e4fc8ab93db1:42231/simple (17 seconds, 38 ms)
3730.5:[error]   ! Execute GET: http://testing-docker-0e6b295f-ea60-4c25-b428-e2f1713e2b70:44457/simple (12 seconds, 407 ms)
3730.4:[error]   ! Execute GET: http://testing-docker-47a27ac4-1b7f-4cbe-bbcd-94c3c0b6db9b:41841/simple (48 seconds, 864 ms)
3728.4:[error]   ! Execute GET: http://testing-docker-762b2a13-abf9-49f4-bdf8-b9c780a7d87b:45517/simple (11 seconds, 369 ms)
3728.4:[error]   ! Execute GET: http://testing-docker-762b2a13-abf9-49f4-bdf8-b9c780a7d87b:44433/simple (12 seconds, 201 ms)
3728.4:[error]   ! Execute GET: http://testing-docker-762b2a13-abf9-49f4-bdf8-b9c780a7d87b:42721/simple (18 seconds, 436 ms)
3703.1:[error]   ! Execute GET: http://testing-docker-2a6c3ed5-fb78-460a-a962-4543c5d18e7e:37825/simple (14 seconds, 134 ms)
```

3728.4 was restarted so I'm not sure if you can get to it on travis-ci.org.

**Comment by rossabaker** [comment]
Cautiously optimistic this is fixed by #1022.  We'll reopen if it comes back.

**Comment by SethTisue** [comment]
not sure if same or different, but I saw this today:

```
[http4s] [info] AsyncHttpClientSpec
[http4s] [error] x Execute GET: /simple (629 ms)
[http4s] [error]  Array(115, 105, 109, 112, 108, 101, 32, 112, 97, 116,
[http4s] [error]        added: 104) (ClientRouteTestBattery.scala:111)
```

**Comment by SethTisue** [comment]
and again today https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/2616/consoleFull
